### ISSUE TITLE
使用AutoModelForCausalLM加载7B，调用chat_stream报错ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by kunzeng-ch** [QwenLM/Qwen#1009]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

tokenizer = AutoTokenizer.from_pretrained("Qwen-7B-Chat",trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("Qwen-7B-Chat",
                                                          quantization_config=quantization_config,
                                                          device_map="cuda:1",
                                                          trust_remote_code=True,
                                                          fp16=True).eval()
使用model.chat_stream(self.tokenizer, prompt_1, history=None,
                                               stop_words_ids=react_stop_words_tokens)
直接报错ValueError: too many values to unpack (expected 2)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
提供的代码里self.tokenizer的self是啥？

**Comment by jklj077** [comment]
As the error log is incomplete and reprodution is also not possible, we are unable to provide assistance.

Here are the general trouble-shooting instructions:
1. Update the environment and try using latest code.
2. Our best guess is you are using example code from `langchain_tooluse.ipynb`, but change `model.chat` to `model.chat_stream` on your own, thus causing the error. Please note `model.chat_stream` and `model.chat` has different return types.
