### ISSUE TITLE
How to set model context length in FastChat openai_api_server for Qwen-72B-Chat

### ISSUE THREAD

**Issue by Haxeebraja** [QwenLM/Qwen#1010]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I am getting the following error on Qwen-72B-Chat served via FastChat openai_api_server and using it on TaskWeaver. It occurs when response is long. However context length of Qwen 72b is 32k which should be enough. Is there a parameter in FastChat or Taskweaver to set this or is the below error due to any other reason?

Short responses are working fine. for example printing number 1 - 100.
However, printing number 1 to 500 fail with this error:

2024-01-25 11:41:44 - Use back up engine: False
2024-01-25 11:41:46 - LLM output: {"
2024-01-25 11:41:46 - Failed to parse LLM output stream due to JSONError: incomplete JSON str ends prematurely
2024-01-25 11:41:46 - Traceback (most recent call last):
File "/workspace/mounted/TaskWeaver/playground/UI/../../taskweaver/session/session.py", line 134, in _send_text_message
post = _send_message(post.send_to, post)
File "/workspace/mounted/TaskWeaver/playground/UI/../../taskweaver/session/session.py", line 108, in _send_message
reply_post = self.planner.reply(
File "/workspace/mounted/TaskWeaver/playground/UI/../../taskweaver/planner/planner.py", line 263, in reply
self.planner_post_translator.raw_text_to_post(
File "/workspace/mounted/TaskWeaver/playground/UI/../../taskweaver/role/translator.py", line 118, in raw_text_to_post
validation_func(post_proxy.post)
File "/workspace/mounted/TaskWeaver/playground/UI/../../taskweaver/planner/planner.py", line 229, in check_post_validity
post.attachment_list[0].type == AttachmentType.init_plan
IndexError: list index out of range

**Comment by jklj077** [comment]
Hi, for `model_worker.py` in fastchat, you should be able to pass `max_new_tokens` when calling the api, and setting it to a larger number may help. The default is [256](https://github.com/lm-sys/FastChat/blob/6d4ca23782d4deec0361dc4bee3a4fa9459164c4/fastchat/serve/inference.py#L81).

**Comment by Haxeebraja** [comment]
> Hi, for `model_worker.py` in fastchat, you should be able to pass `max_new_tokens` when calling the api, and setting it to a larger number may help. The default is [256](https://github.com/lm-sys/FastChat/blob/6d4ca23782d4deec0361dc4bee3a4fa9459164c4/fastchat/serve/inference.py#L81).

I am setting up the model using below then using Taskweaver to connect with it:
python3 -m fastchat.serve.controller --host 0.0.0.0 &
python3 -m fastchat.serve.model_worker --model-path mounted/Qwen-72B-Chat --num-gpus 8
python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 8787

From where can I pass max_new_tokens parameter?

**Comment by jklj077** [comment]
if you are using the `openai_api_server`, the argument is `max_tokens`. i'm not familiar with taskweaver. you could probably configure the default in the json config file. The key seems to be `llm.max_tokens` and the default seems to be [1024](https://github.com/microsoft/TaskWeaver/blob/e9ad5abfda2d43e72e1829695725ec8b9eb8aa46/taskweaver/llm/openai.py#L99). however, that's my best guess. please open an issue at taskweaver for more advice.

i'm not sure why this happened though, LLM outputting only `{"` seems wired. if you continue to meet that error after the length issue is resolved, it could be a prompt issue.

**Comment by Haxeebraja** [comment]
The issue was resolved by increasing the allocated GPU memory for the model in FastChat
