### ISSUE TITLE
💡 [REQUEST] - 官方是否用TensorRT-LLM 跑过 Qwen-14b-chat-Int4 模型？效果如何？提速几倍？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#1012]
### 摘要 | Summary

官方是否用TensorRT-LLM 跑过 Qwen-14b-chat-Int4 模型？效果如何？提速几倍？

### 基本示例 | Basic Example

none

### 缺陷 | Drawbacks

none

**Comment by ArlanCooper** [comment]
+1

**Comment by jklj077** [comment]
We haven't try TensorRT-LLM ourselves and consequently we don't have any data to share.
