### ISSUE TITLE
请问是否支持增量预训练呢？

### ISSUE THREAD

**Issue by listwebit** [QwenLM/Qwen#1013]
### 摘要 | Summary

1.目前官方是否支持增量预训练呢？好像没有找到，预计什么时候回发布呢?
2.我如果自己从微调代码改造一下就行了，将input和label进行一个字符的偏移，理论上不就是预训练了吗？

### 基本示例 | Basic Example

ce 

### 缺陷 | Drawbacks

s 

### 未解决问题 | Unresolved questions

s

**Comment by jklj077** [comment]
1. 没支持。
2. 当前finetune.py微调使用的训练目标和（增量）预训练是一样的，区别只在输入数据的类型上。按照你的逻辑的话，现在input和label也是错位的，“理论上”也是预训练。要改（增量）预训练只需要改数据处理逻辑就可以，如果能接受这个运行效率的话，也是可以的。
