### ISSUE TITLE
[BUG] Docker: ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported

### ISSUE THREAD

**Issue by tzdmwwdz** [QwenLM/Qwen#1015]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

docker container start qwen报错：
Traceback (most recent call last):
  File "openai_api.py", line 532, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 784, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### 期望行为 | Expected Behavior

期望解决问题

### 运行环境 | Environment

```Markdown
- OS:Centos 7.9
- Python:3.11
- Transformers:4.32
- PyTorch:2.12
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jklj077** [comment]
checkpoint_path不正确，或者没设置trust_remote_code=True

**Comment by tzdmwwdz** [comment]
“QWEN_CHECKPOINT_PATH=/app/dev/Qwen/Qwen-72B-Chat-Int4”
“    tokenizer = AutoTokenizer.from_pretrained(
        args.checkpoint_path,
        trust_remote_code=True,
        resume_download=True,“
感谢答复，这两个地方这么设置应该是没问题吧，一开始就是这么设置的。再帮忙看看吧

**Comment by tzdmwwdz** [comment]
模型下载不完整
