### ISSUE TITLE
How to fine tune the model to complete information extraction tasks

### ISSUE THREAD

**Issue by jjl001** [QwenLM/Qwen#1018]
Information extraction task： Enter a paragraph to extract key content .
eg:
input: "生成一个婚礼贺请柬，12月25日举办，李颖和刘涛的婚礼，红色"
output：{"有效":"是", "场景": "邀请函","颜色": "红色", "设计用途":"婚礼贺请柬", "人物":"李颖和刘涛", "时间":"12月25日", "关键词":"婚礼贺请柬", "主标题":""}

 Can I set the “ Information extraction” for "system" ？

**Comment by jklj077** [comment]
I don't think settig the system message this way is effective. In genernal, the system message should specify how the task should be conducted and include examples, unless the task is known in training.
