### ISSUE TITLE
[BUG] <title>lora微调14b-chat可以用deepspeed zreo 3 吗？显卡是8 x V100(16G)，不管是zero2还是zero3 都存在OOM 

### ISSUE THREAD

**Issue by yyyzhao** [QwenLM/Qwen#1030]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
16GB的8卡没测过，24GB的4卡是可以的。参见：https://github.com/QwenLM/Qwen/blob/main/recipes/finetune/deepspeed/readme.md#settings-and-gpu-requirements

**Comment by LittleYouEr** [comment]
同样的问题，8卡V100，全量+Zero3+Offload-CPU，还是出OOM。扩充到两台2*8卡V100，同样的任务还是出OOM。

**Comment by WangJianQ-cmd** [comment]
> 同样的问题，8卡V100，全量+Zero3+Offload-CPU，还是出OOM。扩充到两台2*8卡V100，同样的任务还是出OOM。

请问您是如何扩充到两台微调的呀，设置的参数可以借鉴一下吗？
