### ISSUE TITLE
qlora微调后无法读取权重文件

### ISSUE THREAD

**Issue by zzzcccxx** [QwenLM/Qwen#1036]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在使用qwen-1.8b-int4-chat微调时用了bash finetune/finetune_qlora_single_gpu.sh得到了output_qwen文件夹
![image](https://github.com/QwenLM/Qwen/assets/94726836/99b9bfe4-c388-438d-996b-b0f1606032f7)
但当我使用
```
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    '/Qwen/output_qwen', # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()
```
进行读取模型时，出现了以下报错：
```
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.
```

我看到了其他issue，但我生成的output_qwen文件夹里并没有少那几个文件呀

### 期望行为 | Expected Behavior

可以正常合并

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.10.13
- Transformers:
- PyTorch:2.2.0+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by seamoon224** [comment]
我运行lora微调，在推理中也出现了同样的报错，同样文件是没有问题的。
之前是可以正常运行的，不知道今天为什么突然就出错了。

**Comment by jklj077** [comment]
> `/Qwen/output_qwen`

感觉这个路径不太对

**Comment by zzzcccxx** [comment]
> > `/Qwen/output_qwen`
> 
> 感觉这个路径不太对

路径应该没问题，我pdb看了下，发现在
![image](https://github.com/QwenLM/Qwen/assets/94726836/d8086dae-6c0d-4387-ae79-662ebacbc688)
这个transformers库中的from_pretrained函数中也有tokenizer_config
![image](https://github.com/QwenLM/Qwen/assets/94726836/b6197820-5aa2-4023-bdea-874ecb8048d7)
而在下面这几行代码中，config_tokenizer_class='QWenTokenizer'，但tokenizer_class_from_name(tokenizer_class_candidate)就是None了，所有我有这个报错问题，请问该怎么解决呢？
![image](https://github.com/QwenLM/Qwen/assets/94726836/e11cf0ec-c3c9-43c0-8b6c-00409aa2442a)

**Comment by zzzcccxx** [comment]
已解决，需要将peft版本从最新降低到0.7，然后再
![image](https://github.com/QwenLM/Qwen/assets/94726836/7373e1b6-71da-44cf-9cb8-603e59bbf273)
就可以了

**Comment by jklj077** [comment]
噢，你的`peft>=0.8.0`，那这个没啥办法，它from_pretrained的时候会加载tokenizer，写法等价于`trust_remote_code=False`。这个你把tokenizer相关的和model相关的放到不同的文件夹就行。
