### ISSUE TITLE
计算推理速度的profile.py不能运行

### ISSUE THREAD

**Issue by rabum** [QwenLM/Qwen#1037]
测的是Qwen-72B-Chat-Int4，加载完后卡在这里：
![image](https://github.com/QwenLM/Qwen/assets/58140899/c9e3c6f2-f603-44df-a9d6-e49b00577d97)

**Comment by jklj077** [comment]
环境配置（几张卡、什么卡、transformers、pytorch、cuda、autogptq版本）请提供下
另外profile.py加载不了量化模型才对，复现脚本提供下

**Comment by rabum** [comment]
不好意思是能运行的，图上不动就是在计算了
