### ISSUE TITLE
在chat上SFT max_seq_len开大后指令遵循能力下降很严重

### ISSUE THREAD

**Issue by menghonghan** [QwenLM/Qwen#1042]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

请问在chat上全量SFT max_seq_len开到32k相比2048 指令遵循能力下降非常严重  请问可能有什么原因呢 是数据不够长？ 谢谢解答 谢谢

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by WangJianQ-cmd** [comment]
您说的这个指令遵从能力，可以举一个具体的例子吗？

**Comment by jklj077** [comment]
Directy training on long sequences can be harmful to model performances, as in training, dynamic_ntk and logn attention is effectively disabled; see line 833 of modeling_qwen.py. It means that the model can only handle a sequence length up to 2K or 8K at the start of the finetuning and adapting to a 32K sequence length will require a lot of data.

We advise you to take a look at Qwen1.5, which changes the strategy in extending context length and is more admissive to finetuning on long sequences.
