### ISSUE TITLE
请看下这个问题是什么原因：Token indices sequence length is longer than the specified maximum sequence length for this model (579376 > 512). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by chesp** [QwenLM/Qwen#1044]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![1706854951463](https://github.com/QwenLM/Qwen/assets/8938818/d67b9878-0481-4c7a-b9a9-229e003fce95)
微调时报错了，但是进度又是100%了，这到底是调好了还是没调好？

微调的启动命令是：docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat-Int4,target=/data/shared/Qwen/Qwen-7B --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen --mount type=bind,source=/data/qwen/Qwen-main/,target=/data/shared/Qwen --shm-size=2gb -it qwenllm/qwen:cu114 bash finetune/finetune_qlora_single_gpu.sh -m /data/shared/Qwen/Qwen-7B/ -d /data/shared/Qwen/data/qwen_data.json

### 运行环境 | Environment

```Markdown
- OS:Ubuntu Server 18.04
- Python:3.10
- Transformers:4.35.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
```

**Comment by jklj077** [comment]
忽略这个提示中的indexing errors部分，原因就是transformers有一些过时的设计，对于Qwen这类使用相对位置编码的模型，并不会有indexing errors问题。

不过这个提示中的输入长度需要注意下，579376太长了，请检查下数据是不是有问题。

**Comment by WangJianQ-cmd** [comment]
这个应该是训练集中 有QA对话的长度大于model_max_length，我理解的是找出来之后将其截断（512）训练

**Comment by GXKIM** [comment]
> 忽略这个提示中的indexing errors部分，原因就是transformers有一些过时的设计，对于Qwen这类使用相对位置编码的模型，并不会有indexing errors问题。
> 
> 不过这个提示中的输入长度需要注意下，579376太长了，请检查下数据是不是有问题。

数据集长度太长，比max_length长的话，会影响训练效果吗
