### ISSUE TITLE
[BUG] <title>微调qwen-chat-7B-int4的时候Target module QuantLinear() is not supported. 

### ISSUE THREAD

**Issue by Yining0907** [QwenLM/Qwen#1045]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.

### 期望行为 | Expected Behavior

无报错

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.8
- Transformers:4.34.0
- PyTorch:2.0.1
- auto-gptq：0.4.2
- optimum：1.13.2
- peft：0.6.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
升级deepspeed。

**Comment by taoxifa** [comment]
有没有解决，我也遇到了这个问题

**Comment by lvsh2012** [comment]
俺也一样，如何解决

**Comment by Yining0907** [comment]
各个依赖版本不match的原因，建议按照官方文档确定每个的版本，应该就可以解决问题
