### ISSUE TITLE
[BUG] <title>Value Error: Tokenizer class QwenTokenizier does not exist or is not currently imported

### ISSUE THREAD

**Issue by h66840** [QwenLM/Qwen#1046]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我在微调完qwen-7B-Chat-Int4后，使用 AutoPeftModelForCausalLM.from_pretrained方法加载微调后的模型，会报出此Error，我该怎么解决？

### 期望行为 | Expected Behavior

应该能加载我微调后的模型才对

### 复现方法 | Steps To Reproduce

none

### 运行环境 | Environment

```Markdown
- OS:Ubuntu20.04
- Python:3.9
- Transformers:4.32.0
- PyTorch:2.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

无

**Comment by jklj077** [comment]
请参考README中说明。

![image](https://github.com/QwenLM/Qwen/assets/17811943/e6bb1bb1-9db9-4505-aaa1-bacb569c54f2)
