### ISSUE TITLE
流式推理时，完成一轮对话后，模型输出最后一个字后，有没有什么结束标识呢？

### ISSUE THREAD

**Issue by stevin-dong** [QwenLM/Qwen#1049]
流式推理时，完成一轮对话后，模型输出最后一个字后，有没有什么结束标识可以用呢？

**Comment by stevin-dong** [comment]
使用的是chat_stream这个接口

**Comment by jklj077** [comment]
`model.chat_stream`这个，模型输出结束后，返回的generator也就结束了。
```python
for response in model.chat_stream(query, ...):
    pass
print(response)
```
最后的`response`就是完整的了。

**Comment by WangxuP** [comment]
是否可以使用next方法呢？
```
response  =  model.chat_stream(query, ...)
curr_line = ""
try:
    curr_line = next(response)
except StopIteration:
    print(f"大模型流式输出最后一行结果 {curr_line}")
```

**Comment by stevin-dong** [comment]
> 是否可以使用next方法呢？
> 
> ```
> response  =  model.chat_stream(query, ...)
> curr_line = ""
> try:
>     curr_line = next(response)
> except StopIteration:
>     print(f"大模型流式输出最后一行结果 {curr_line}")
> ```

我现在判断模型输出时间，比如超过2秒没有输出了，就认为本次回答完了

**Comment by stevin-dong** [comment]
> `model.chat_stream`这个，模型输出结束后，返回的generator也就结束了。
> 
> ```python
> for response in model.chat_stream(query, ...):
>     pass
> print(response)
> ```
> 
> 最后的`response`就是完整的了。

感谢，意思就是只要执行到print(response)就证明模型已经输出完毕了，要不就会阻塞在for循环

**Comment by WangxuP** [comment]
> 我现在判断模型输出时间

判断模型输出时间和我提供的这个方法没必然关系，你可以加个定时器来判断时间的。
`model.chat_stream`返回的是一个`yield`对象，这个对象可通过next方法迭代，报`StopIteration`的错的时候，就认为是迭代完毕了。
