### ISSUE TITLE
[BUG] <title>为什么千问14B的config里面的seq_length 和max_position_embedding不一样，而7B和72B是一样的。同时vllm的千问的实现中没有Q*logn的实现

### ISSUE THREAD

**Issue by wqh17101** [QwenLM/Qwen#1051]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/26429138/d558d345-cd14-4ec6-8659-072eb23b3533)

而且在vllm的实现中没有Q*logn_tensor的逻辑
https://github.com/vllm-project/vllm/blob/c9b45adeeb0e5b2f597d1687e0b8f24167602395/vllm/model_executor/models/qwen.py#L109

### 期望行为 | Expected Behavior

修复bug？

### 复现方法 | Steps To Reproduce

白盒代码发现的问题

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
1.8B 7B 14B 72B支持的长度有差异，请参阅readme判断。
另外，vllm尚未支持Qwen版本的dynamic ntk/logn attention，长序列推理结果可能不符合预期。
如有需要利用vllm进行长序列推理，建议使用Qwen1.5版本的模型。

**Comment by wqh17101** [comment]
> 1.8B 7B 14B 72B支持的长度有差异，请参阅readme判断。 另外，vllm尚未支持Qwen版本的dynamic ntk/logn attention，长序列推理结果可能不符合预期。 如有需要利用vllm进行长序列推理，建议使用Qwen1.5版本的模型。

无论是huggingface还是vllm里面其实都没有1.5版本的模型文件，我觉得指的应该是qwen2.py。  
不管是vllm还是huggingface上的qwen2.py 其实里面已经没有 logn attention 相关的内容，是否可以认为未来的演进中将不会再出现这个

**Comment by jklj077** [comment]
是的，输入长序列支持目前最新的模型（Qwen1.5）采用了不同的技术方案（非logn attention/dynamic ntk），Qwen2会有进一步变化。
