### ISSUE TITLE
[BUG] openai_api request with functions payload returns 400

### ISSUE THREAD

**Issue by akinlong** [QwenLM/Qwen#1057]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Call openai_api API with functions payload returns 400. I checked the openai_api.py: 
    if request.stream:
        if request.functions:
            raise HTTPException(
                status_code=400,
                detail=
                'Invalid request: Function calling is not yet implemented for stream mode.',
            )

Those lines indicate it doesn't support functions payload. Is there any other reason which will affect the model to run with functions? Do you have any plans to support this?

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JianxinMa** [comment]
This repository (Qwen1) is no longer actively maintained. We are moving towards Qwen1.5, found in another repo. Regarding streaming function calls, a wrapper is available at Qwen-Agent which facilitates this feature. See the README in Qwen1.5 for more details.

- [Qwen1.5](https://github.com/QwenLM/Qwen1.5)
- [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent) (this repo is still in its early stages. Any suggestions are welcomed.)
