### ISSUE TITLE
我微调了预训练模型Qwen-7B如何让他实现多轮问答产生上下文联系

### ISSUE THREAD

**Issue by AnYiz** [QwenLM/Qwen#1061]
![1708139197446](https://github.com/QwenLM/Qwen/assets/95127377/d5905655-2439-4181-a0ca-35b67e741e15)
这样输入他不会产生上下文联系，如何修改让他的回答可以产生上下文联系

**Comment by jklj077** [comment]
采用本repo的微调脚本的话，与模型对话需要使用ChatML格式，调用model.chat与model.chat_stream，并传入相应的query和history即可进行多轮对话。

由于Qwen1.5已发布，建议您使用最新的模型。Qwen1.5支持通过tokenizer.apply_chat_template构造多轮对话输入，建议查阅有关文档。
