### ISSUE TITLE
lora微调，训练集长度扩展问题

### ISSUE THREAD

**Issue by fanbooo** [QwenLM/Qwen#1065]
Hi 作者：
     感谢作者工作，目前想lora finetune实验下一批长文本指令，有几个问题；
     1.目前看https://github.com/QwenLM/Qwen/issues/490，应该直接改--model_max_length 4096，应该是无法支持4096个token输入的？
     2.如果通过PI或者其他方式，在训练时支持4096长度token输入，是否必须从预训练开始重头训练呢？还是直接lora就可以了？

**Comment by fanbooo** [comment]
模型是qwen-14B-chat

**Comment by jklj077** [comment]
1. Qwen-1.8B、Qwen-7B、Qwen-72B是可以支持输入4096的（训练到8192，推理扩展到32K）；Qwen-14B可以支持输入2048，推理8192。Qwen1.5的输入训练长度支持进行了统一。#490 讨论的是主要是使用dynamic ntk进行训练中长度扩展的问题，跟您提到的问题有些区别。
2. 这个一般是不用的，可以采用继续预训练的方式，也有Long LoRA等方案，仅供参考。

**Comment by puppet101** [comment]
@jklj077 请问qwen1.5的训练长度是多少？ 是32k还是8k呢？我直接用12k的长度训练，效果并不是很好，远不如yi-34b-200k的效果

**Comment by jklj077** [comment]
@puppet101 Please refer to the pinned issue and kindly direct your inquiry to Qwen1.5 at <https://github.com/QwenLM/Qwen1.5>
