### ISSUE TITLE
qwen大模型在基于背景知识总结答案过程中，针对特殊符号比如竖线、横杠之类的会存在丢失情况

### ISSUE THREAD

**Issue by WangxuP** [QwenLM/Qwen#1066]
求助下作者：
qwen14b-chat在根据背景知识总结答案的时候，如果背景知识当中有特殊符号  比如 横杠、竖线之类的，大模型经常会丢失这些符号，这些特殊符号比较重要，我不想让大模型丢失。我在prompt当中已经说明了， 但是效果并不理想，有没有办法保证大模型不丢失呢？

**Comment by jklj077** [comment]
由于不清楚输入的实际情况，一般建议通过prompt engineering或调整system的方式来引导模型行为。比如将相关部分用特殊符号环绕标记、使用肯定形式而非否定形式、调整system prompt等。如需要更具体的建议，建议提供输入的示例。另外，如果您使用的是Qwen14B-Chat，建议也尝试下最新的Qwen1.5-14B-Chat模型，看下是否有改善。

**Comment by WangxuP** [comment]
> 由于不清楚输入的实际情况，一般建议通过prompt engineering或调整system的方式来引导模型行为。比如将相关部分用特殊符号环绕标记、使用肯定形式而非否定形式、调整system prompt等。如需要更具体的建议，建议提供输入的示例。另外，如果您使用的是Qwen14B-Chat，建议也尝试下最新的Qwen1.5-14B-Chat模型，看下是否有改善。

**背景样例：**
```
背景知识：
公司出差补贴表如下：
|职级|住宿费标准|||
|^|北京|一线城市及部分城市旺季期间|其他城市|
|---|---|---|---|
|公司老总|1000元/人•天|800元/人•天|650元/人•天|
|其他人员|500元/人•天|600元/人•天|500元/人•天|

问题:出差人员补贴标准是什么？
```
我把背景知识和我现有的prompt脱敏处理了，大致内容如上所述。我发现在不同的GPU上回答也有差异，我使用A800回答正确，但是使用V100就回答错误了。

如果要调整system prompt的话，有没有具体的建议呢？

**Comment by jklj077** [comment]
这类样例比较特殊：
- 输入表格：模型倾向于解析具体内容以文字形式输出。提示模型`保留原始格式`、`输出表格`一般可以让模型更稳定的输出表格。
- 输入表格采用了MultiMarkdown/php-markdown-extra格式：模型生成表格时有gfm格式倾向，但输入的表格无法以gfm格式保留，模型即使输出表格也很难保持与原输入格式一致。

针对14B模型目前我没有特别好的建议，我们测试了下Qwen1.5-4B和Qwen1.5-72B在这个样例上表现较为稳定。
![image](https://github.com/QwenLM/Qwen/assets/17811943/28225efa-8c06-45da-a6c5-1328bd225c56)

**Comment by WangxuP** [comment]
好的，那我大概知道了，感谢。
