### ISSUE TITLE
请问模型的并发能力

### ISSUE THREAD

**Issue by rabum** [QwenLM/Qwen#1067]
目前用8*4090跑qwen-72B-int4，每秒输出10个Token左右，但在两人同时使用时，速度明显下降一半都不止，已经使用了flash_attention，请问是否还有加速方案？

**Comment by jklj077** [comment]
由于您提到了使用了flash_attention，您应该使用的是transformers加载的模型，transformers是缺少有效的并发管理的。建议您尝试采用FastChat+vLLM的方案，如果设备性能有并发的空间（比如显存仍有剩余），总吞吐量一般会有提升。
