### ISSUE TITLE
请问通义千问1.0的bash finetune/finetune_qlora_single_gpu.sh微调命令，对通义千问1.5适用吗？

### ISSUE THREAD

**Issue by annian101** [QwenLM/Qwen#1072]
请问通义千问1.0的bash finetune/finetune_qlora_single_gpu.sh微调命令，对通义千问1.5适用吗？

**Comment by jklj077** [comment]
I believe the compatibility issue exists due to significant differences in the codebase. For fine-tuning Qwen1.5 models, I recommend referring to the official repository at <https://github.com/QwenLM/Qwen1.5> and seeking guidance there. Thank you.

**Comment by annian101** [comment]
> 我认为由于代码库存在显着差异，因此存在兼容性问题。对于微调 Qwen1.5 模型，我建议参考官方存储库https://github.com/QwenLM/Qwen1.5并在那里寻求指导。谢谢。

好的，明白了谢谢您，那我去尝试用swift来进行微调吧
