### ISSUE TITLE
windows部署，启动时报错Tokenizer class Qwen2Tokenizer does not exist or is not currently imported

### ISSUE THREAD

**Issue by logan4753** [QwenLM/Qwen#1077]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

miniconda3\python.exe cli_demo.py
Traceback (most recent call last):
  File "F:\Qwen\Qwen-main\Qwen\cli_demo.py", line 210, in <module>
    main()
  File "F:\Qwen\Qwen-main\Qwen\cli_demo.py", line 116, in main
    model, tokenizer, config = _load_model_tokenizer(args)
  File "F:\Qwen\Qwen-main\Qwen\cli_demo.py", line 45, in _load_model_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "F:\Qwen\Qwen-main\Qwen\miniconda3\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 765, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

### 运行环境 | Environment

```Markdown
- OS: windows10
- Python:3.10.10
- Transformers:4.35.0
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by h66840** [comment]
您好，请问解决了吗

**Comment by LiJiaqi96** [comment]
同问，解决了吗

**Comment by FFFro** [comment]
+1

**Comment by Ningshiqi** [comment]
+1，无论是用官方给的modelscope方法，还是自己download模型，均无法用AutoTokenizer.from_pretrained(model_dir)加载

**Comment by Ningshiqi** [comment]
各位官方给的提示。

注意: 如果peft>=0.8.0，加载模型同时会尝试加载tokenizer，但peft内部未相应设置trust_remote_code=True，导致ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.要避过这一问题，你可以降级peft<0.8.0或将tokenizer相关文件移到其它文件夹。
