### ISSUE TITLE
微调后的模型，用vllm推理出来的结果都是空是什么原因呀

### ISSUE THREAD

**Issue by lalalabobobo** [QwenLM/Qwen#1082]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

sft+vllm 推理为空

### 期望行为 | Expected Behavior

推理有结果

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Mingfeng-Chen** [comment]
遇到相同问题
![image](https://github.com/QwenLM/Qwen/assets/59349853/7dbb3732-e886-4595-a751-aeff136291f9)

**Comment by jklj077** [comment]
1. If you are using vLLM, it is not compatible with Qwen1.0. Consider FastChat+Qwen1.0, which includes the chat template and the stopping criteria by default.
2. If you are not using Chat models, it is possible that the model believes that the input is complete and generates "<|endoftext|>" (151643) directly.
3. If you have run supervised finetuning (SFT) on base models, compare the saved `*_config.json` with those of chat models and modify as needed.
