### ISSUE TITLE
使用qwen模型进行RLHF时出错

### ISSUE THREAD

**Issue by 128Ghe980** [QwenLM/Qwen#1085]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我现在正在使用qwen-chat模型进行RLHF，使用的deepspeed-chat的example。
但是老是报错跑不通，现在有几个问题：
1.RLHF是使用chat版好还是base版好
2.chat版本只能用AutoModelForCausalLM初始化吗？
3.base版本用AutoModelForCausalLM是否会出现重复输出、不停输出问题

麻烦各位大佬指点一下

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
1. It is commonly chosen as the SFT model in the literature.
2. Yes. The important thing is the model structure defined in modeling_qwen.py. `AutoModelForCausalLM` is the common way to instantiate such as model.
3. Definitely yes.

**Comment by ggbondcxl** [comment]
Did you finally succeed in using deepspeed-chat to RLHF qwen?
