### ISSUE TITLE
[BUG] 莫名其妙的TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ElinLiu0** [QwenLM/Qwen#1087]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

当我使用：
```bash
python openai_api.py
```
将千问模型以OpenAI方式挂起，并尝试使用下述代码：
```python
# 原始代码出处：https://blog.csdn.net/huiguo_/article/details/134793373
from langchain.chat_models import ChatOpenAI

from langchain.schema import HumanMessage

llm = ChatOpenAI(
    streaming=True,
    verbose=True,
    # callbacks=[callback],
    openai_api_key="none",
    openai_api_base="http://127.0.0.1:8000/v1",
    model_name="Qwen-7B-Chat"
)
instructions = """
你将得到一个带有水果名称的句子,提取这些水果名称并为其分配一个表情符号
在 python 字典中返回水果名称和表情符号
"""

fruit_names = """
苹果,梨,这是奇异果
"""

# 制作结合说明和水果名称的提示
prompt = (instructions + fruit_names)

# Call the LLM
output = llm([HumanMessage(content=prompt)])

print (output.content)
print("========")
print (type(output.content))
# 苹果: 🍎梨: 🥐奇异果: 🍓
# ========
# <class 'str'>
```
当我切屏过去看Server的终端时，它抛出了如下的异常：
```bash
Traceback (most recent call last):
    |   File "/home/elin/anaconda3/envs/Qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in wrap
    |     await func()
    |   File "/home/elin/anaconda3/envs/Qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 251, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/elin/Qwen/openai_api.py", line 487, in predict
    |     delay_token_num = max([len(x) for x in stop_words])
    | TypeError: 'NoneType' object is not iterable
```

### 期望行为 | Expected Behavior

按原博客博主的描述，其应当打印出千问Chat模型返回的文本，而实际在Client端显示连接已损坏：
```bash
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

### 复现方法 | Steps To Reproduce

无

### 运行环境 | Environment

```Markdown
- OS:Ubuntu22.04(WSL2)
- Python: 3.11.0
- Transformers:4.32.0
- PyTorch:2.2.0
- CUDA:11.8
```

### 备注 | Anything else?

这是我第一次尝试学习LangChain，给各位带来不便还望谅解。

**Comment by jklj077** [comment]
The `openai_api.py` script generates an API that isn't fully compatible with the most recent version of the OpenAI Python SDK. To circumvent this issue in `openai_api.py`, it's recommended to pass stop words through Langchain when making API calls.

For those who don't require tool use or function support, we suggest using FastChat in conjunction with vLLM for Qwen(1.0) as an alternative means to deploy the OpenAI API.

Please note that Qwen(1.0) models and associated codes are no longer under active development and will not receive any further updates or enhancements. The focus has shifted to Qwen1.5, which boasts better integration with the `transformers` ecosystem. For more information and to stay updated, kindly visit <https://github.com/QwenLM/Qwen1.5>.

**Comment by ElinLiu0** [comment]
> The `openai_api.py` script generates an API that isn't fully compatible with the most recent version of the OpenAI Python SDK. To circumvent this issue in `openai_api.py`, it's recommended to pass stop words through Langchain when making API calls.
> 
> For those who don't require tool use or function support, we suggest using FastChat in conjunction with vLLM for Qwen(1.0) as an alternative means to deploy the OpenAI API.
> 
> Please note that Qwen(1.0) models and associated codes are no longer under active development and will not receive any further updates or enhancements. The focus has shifted to Qwen1.5, which boasts better integration with the `transformers` ecosystem. For more information and to stay updated, kindly visit https://github.com/QwenLM/Qwen1.5.

First,when i using `Qwen/Qwen1.5-7B-Chat` as a entrypoint to load up the service,it raise an error like below:
```bash
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```
Should i turn to 4B checkpoint and retry?
Second,please answer me in Chinese,although you see my username maynot like a Chinese,but hey.铁打的中国人好吧！Don't do that to our pepole just because of that boring globalization...

**Comment by ElinLiu0** [comment]
> > The `openai_api.py` script generates an API that isn't fully compatible with the most recent version of the OpenAI Python SDK. To circumvent this issue in `openai_api.py`, it's recommended to pass stop words through Langchain when making API calls.
> > For those who don't require tool use or function support, we suggest using FastChat in conjunction with vLLM for Qwen(1.0) as an alternative means to deploy the OpenAI API.
> > Please note that Qwen(1.0) models and associated codes are no longer under active development and will not receive any further updates or enhancements. The focus has shifted to Qwen1.5, which boasts better integration with the `transformers` ecosystem. For more information and to stay updated, kindly visit https://github.com/QwenLM/Qwen1.5.
> 
> First,when i using `Qwen/Qwen1.5-7B-Chat` as a entrypoint to load up the service,it raise an error like below:
> 
> ```shell
> ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
> ```
> 
> Should i turn to 4B checkpoint and retry?I am currently using RTX3080Ti Laptop with 16GB VRAM. Second,please answer me in Chinese,although you see my username maynot like a Chinese,but hey.铁打的中国人好吧！Don't do that to our pepole just because of that boring globalization...

修好了，在启动模型的时候修改`--max-model-length`参数为1024就可以正常使用了。
Issue has solved due to nologger need for help.
