### ISSUE TITLE
[BUG] finetune.py中的实现，默认会跳过用户设置的system_message，而使用默认的"You are a helpful assistant."

### ISSUE THREAD

**Issue by yetionyo** [QwenLM/Qwen#1089]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在finetune.py中的preprocess里，默认会跳过第一个非user的message（如果用户在sft的时候，只在data文件中设置system message，最终其实是不起作用的，这很容易导致训练不符合预期），同时system会使用默认的"You are a helpful assistant."。

所以官方不建议修改system prompt的情况下进行sft吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by WangJianQ-cmd** [comment]
def preprocess(
    sources,
    tokenizer: transformers.PreTrainedTokenizer,
    max_len: int,
    system_message: str = "You are a helpful assistant."
) -> Dict:  难道不是改这里的system_message微调吗

**Comment by jklj077** [comment]
The `finetune.py` provided in this repo does not support setting the system message per training example. But as WangJianQ-cmd mentioned, you can indeed change the default system message for all training examples. 

In the recent Qwen1.5 release, its codebase has been seamlessly integrated into the popular `transformers` package, aligning with the established best practices of the `transformers` library. This integration signifies that the `transformers` ecosystem is now designed to natively support Qwen1.5 models in most scenarios without any additional configuration, including the `system message` functionality. A corresponding `finetune.py` is provided in <https://github.com/QwenLM/Qwen1.5>.
