### ISSUE TITLE
请问模型并发上限有没有测试

### ISSUE THREAD

**Issue by rabum** [QwenLM/Qwen#1092]
我是用fastchat+vLLM调用qwen-14b-chat的api来使用大模型，要多人使用，请问有没有并发上限这方面的数据？或者大致预估一下在8*4090的机器上的并发人数？

**Comment by WangJianQ-cmd** [comment]
L40 8卡 40G，使用vllm起的，大概支持247并发，超过这个数就会报错

**Comment by jklj077** [comment]
VLLM autonomously handles concurrency of user requests through a queue system, optimizing performance based on available memory cache blocks and the sequence length of individual requests. To estimate the concurrent capacity, consider the total memory, average tokens per minute, and typical user request lengths.
