### ISSUE TITLE
[BUG] <title> Gradio demo 无法正常显示模型输出

### ISSUE THREAD

**Issue by zzc20001** [QwenLM/Qwen#1095]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

<img width="1217" alt="image" src="https://github.com/QwenLM/Qwen/assets/123918486/7d385947-4de6-4658-bb7c-845a4f63b6b8">

如图所示，当输入之后gradio无法正常捕获模型输出并显示，但是后端可以看到是正常的

<img width="461" alt="image" src="https://github.com/QwenLM/Qwen/assets/123918486/96f48460-e8fe-4def-b070-daabbab7021a">

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by zzc20001** [comment]
将chat_stream生成改成使用chat阻塞式就可以正常输出了，这是什么原因呢？

**Comment by jklj077** [comment]
If it is not a gradio version issue, something could be wrong with your network connection.
