### ISSUE TITLE
[BUG] <AttributeError: 'NoneType' object has no attribute 'size'>

### ISSUE THREAD

**Issue by AZYoung233** [QwenLM/Qwen#1099]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

魔塔社区中qwen1.8B提供的modeling文件中的bug仍为被修复，该bug曾经在issue中被讨论过，替换成7B版本的代码即可解决

### 期望行为 | Expected Behavior

希望作者能够替换一下魔塔社区中qwen1.8B提供的modeling文件

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by antaili66** [comment]
AttributeError: 'NoneType' object has no attribute 'size'
