### ISSUE TITLE
多显卡问题

### ISSUE THREAD

**Issue by Remian777** [QwenLM/Qwen#1116]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我有一台3090*4的服务器，现在我想让其中三张显卡运行通义千问14B模型，请问有方法指定吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Since you are not giving any information, we suppose the most general approch is
```
export CUDA_VISIBLE_DEVICES=0,1,2

# related command to start your application
```

由于您未提供任何具体应用信息，我们推测最通用的方法是：
```bash
export CUDA_VISIBLE_DEVICES=0,1,2

# 相关命令以启动您的应用程序
```
