### ISSUE TITLE
[BUG] <title> open_api_py方式启动，调用/v1/chat/completions会报RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by Shady2333** [QwenLM/Qwen#1121]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用oneapi对接qwen，发起调用模型会报RuntimeError: probability tensor contains either `inf`, `nan` or element < 0的error

### 期望行为 | Expected Behavior

回答问题

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by 2277419213** [comment]
这个问题有人回答过，因为温度问题，ONE API进行请求时，温度是0，Qwen这个模型在温度低于0.5的时候会报错这个

**Comment by ccsc006** [comment]
如何解决呢？？

**Comment by ccsc006** [comment]
> 这个问题有人回答过，因为温度问题，ONE API进行请求时，温度是0，Qwen这个模型在温度低于0.5的时候会报错这个

如何解决？？

**Comment by 2277419213** [comment]
> > 这个问题有人回答过，因为温度问题，ONE API进行请求时，温度是0，Qwen这个模型在温度低于0.5的时候会报错这个
> 
> 如何解决？？

https://github.com/QwenLM/Qwen1.5/issues/145
看这个
