### ISSUE TITLE
多卡lora训练

### ISSUE THREAD

**Issue by GXKIM** [QwenLM/Qwen#1126]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

是否是因为gcc版本过低报错，模型是正常可以加载的
脚本
```
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=3
DIR=`pwd`


export CUDA_VISIBLE_DEVICES=2,3,4





GPUS_PER_NODE=3
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

# Guide:
# This script supports distributed training on multi-gpu workers (as well as single-worker training).
# Please set the options below according to the comments.
# For multi-gpu workers training, these options should be manually set for each worker.
# After setting the options, please run the script on each worker.

# Number of GPUs per GPU worker
#GPUS_PER_NODE=$(python -c 'import torch; print(torch.cuda.device_count())')

# Number of GPU workers, for single-worker training, please set to 1
#NNODES=${NNODES:-1}

# The rank of this worker, should be in {0, ..., WORKER_CNT-1}, for single-worker training, please set to 0
#NODE_RANK=${NODE_RANK:-0}

# The ip address of the rank-0 worker, for single-worker training, please set to localhost
#MASTER_ADDR=${MASTER_ADDR:-localhost}

# The port for communication
#MASTER_PORT=${MASTER_PORT:-6001}

MODEL="/data/ai/data/models/Qwen-14B-Chat" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="/data/ai/user/jingx/Qwen-main/finetune/SRM_1.json"
DS_CONFIG_PATH="/data/ai/user/jingx/Qwen-main/finetune/ds_config_zero2.json"

function usage() {
    echo '
Usage: bash finetune/finetune_lora_ds.sh [-m MODEL_PATH] [-d DATA_PATH] [--deepspeed DS_CONFIG_PATH]
'
}

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 512 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed ${DS_CONFIG_PATH}
```
报错如下
<img width="1066" alt="56b1e790b472af07f40f1954827228a7" src="https://github.com/QwenLM/Qwen/assets/125621025/0321f15c-4002-41ce-b421-57b453cf6ce5">

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
From the provided log, `DeepSpeed` needs to compile efficient kernels which require matching CUDA complier and PyTorch versions. Your error is indeed related to `gcc` versions. It is not common, but it can happens if you use a really old operating system such as CentOS 7.

See also <https://github.com/QwenLM/Qwen/issues/520>.

**Comment by GXKIM** [comment]
> From the provided log, `DeepSpeed` needs to compile efficient kernels which require matching CUDA complier and PyTorch versions. Your error is indeed related to `gcc` versions. It is not common, but it can happens if you use a really old operating system such as CentOS 7. You could install newer version of compilers or downgrade pytorch.从提供的日志中，需要编译高效的内核， `DeepSpeed` 这需要匹配的 CUDA 编译器和 PyTorch 版本。您的错误确实与 `gcc` 版本有关。这并不常见，但如果您使用非常旧的操作系统，例如 CentOS 7，就会发生这种情况。您可以安装较新版本的编译器或降级 pytorch。
> 
> See also #520. 另请参阅 #520。

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

MODEL="/data/ai/data/models/Qwen-14B-Chat" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="/data/ai/user/jingx/Qwen1_1/SRM_final_qwen.json"
DEEPSPEED="/data/ai/user/jingx/Qwen1_1/finetune/ds_z3_config.json"



GPUS_PER_NODE=8
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost

MASTER_PORT=9902

function usage() {
    echo '
Usage: bash finetune/finetune_ds_jingx.sh [-m MODEL_PATH] [-d DATA_PATH]
'
}

while [[ "$1" != "" ]]; do
    case $1 in
        -m | --model )
            shift
            MODEL=$1
            ;;
        -d | --data )
            shift
            DATA=$1
            ;;
        -h | --help )
            usage
            exit 0
            ;;
        * )
            echo "Unknown argument ${1}"
            exit 1
            ;;
    esac
    shift
done

export CUDA_VISIBLE_DEVICES=0,1
DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen1 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 512 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --deepspeed $DEEPSPEED
