### ISSUE TITLE
QLoRA微调后生成的目录结构是什么样子的？💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by xiaohaiqing** [QwenLM/Qwen#1131]
### 摘要 | Summary

from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer

model = AutoPeftModelForCausalLM.from_pretrained("output_qwen", device_map="auto", trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained("output_qwen", trust_remote_code=True)
response, history = model.chat(tokenizer, "类型#裤*风格#英伦*风格#简约", history=None)
print(response)

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

1、我在微调完成后，最后提示了一句：/home/user/anaconda3/envs/qwen-7b-single/lib/python3.11/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in /home/xhq/Qwen-7B-Chat-Int4 - will assume that the vocabulary was not modified.
这个有影响不

2、然后我直接进行测试，测试脚本如实例部分，最后报错：ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.

**Comment by xiaohaiqing** [comment]
我升级了 transformers=4.38.2后，执行测试实例又报了如下错误：TypeError: Object of type Tensor is not JSON serializable

**Comment by jklj077** [comment]
Closed in favor of <https://github.com/QwenLM/Qwen/issues/1132>.

For `TypeError: Object of type Tensor is not JSON serializable`, see also <https://github.com/QwenLM/Qwen/issues/1115>.
