### ISSUE TITLE
LoRA微调合并后回答的问题不是自己准备的数据集中的数据

### ISSUE THREAD

**Issue by xiaohaiqing** [QwenLM/Qwen#1136]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

LoRA在微调合并后，使用如下方式进行问答：
```python
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig 
tokenizer = AutoTokenizer.from_pretrained("qwen-7b-chat-int4", trust_remote_code=True)
 
model = AutoModelForCausalLM.from_pretrained("qwen-7b-chat-int4", device_map="auto", 
trust_remote_code=True).eval() 
response, history = model.chat(tokenizer, "类型#上衣*材质#牛仔布*颜色#白色*风格#简约*图案#刺绣*衣样式#外套*衣款式#破洞", history=None) 
print(response)
```
系统回复的答案并不是数据集中定义的，这是怎么回事呢？

**Comment by Pierre-Wong** [comment]
我之前数据过少然后batch size过大，训练出来没有效果
后来把梯度累积改成1就没有问题了
