### ISSUE TITLE
opem_ai方式启动传递get_current_weather function call，如何在open_ai.py内部调用到get_current_weather方法，这个方法如何定义有什么要求吗？请提供例子说明，网上找不到实例

### ISSUE THREAD

**Issue by Andy1018** [QwenLM/Qwen#1137]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

opem_ai方式启动传递get_current_weather function call，如何在open_ai.py内部调用到get_current_weather方法，这个方法如何定义有什么要求吗？请提供例子说明，网上找不到实例

**Comment by JianxinMa** [comment]
function calling的使用方式是参考openai官方的设计的，按这个设计，open_ai.py内部并不能调用get_current_weather方法，这个方法需要由用户自己调用。例子：https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py

但如果您是想要类似 assistant api 或 langchain 的接口，让框架也把get_current_weather这个方法帮忙调用了，那可以参考 https://github.com/QwenLM/Qwen-Agent 的 README 或 examples 目录（注意该项目目前默认要求 qwen1.5，不再为 qwen1 维护了）。

**Comment by JianxinMa** [comment]
> 非常感谢你的回答，也就是说不能像chatglm3 @register_tool那样自定义工具是吧？

可以支持自定义工具的。请看下qwen-agent的readme。
