### ISSUE TITLE
关于进行代码模型微调的问题

### ISSUE THREAD

**Issue by toufunao** [QwenLM/Qwen#114]
你好，如果需要进行代码能力微调，请问是建议使用Chat版本模型还是使用Base版本模型？考虑到主要需要增强自有Java代码生成能力，请问对微调的数据格式有什么要求吗？期待社区的解答，谢谢！

**Comment by JustinLin610** [comment]
Chat模型的二次微调经验不足，建议还是用Base模型。Base模型finetune可以不考虑格式做finetune，Chat模型对格式有要求。我们这边尽快把Chat模型的输入输出格式在README说明下

**Comment by libing-cn** [comment]
mark

**Comment by huayicong23** [comment]
mark

**Comment by patrick-lau** [comment]
mark

**Comment by GuanghuiMin** [comment]
mark

**Comment by gy297879328** [comment]
请问关于进行代码模型微调 有更新吗 现在

**Comment by goog** [comment]
不开放微调 已取消star

**Comment by xiefan233** [comment]
你好，能请教一下如何微调吗？

**Comment by jklj077** [comment]
我们已开源基于transformers Trainer的微调代码，支持Qwen-7B和Qwen-7B-Chat的微调，其中包括全参数微调、LoRA以及Q-LoRA。相关使用说明（包括数据格式）请见README，欢迎试用参考。
