### ISSUE TITLE
vllm + api方式调用失败

### ISSUE THREAD

**Issue by xiaohaiqing** [QwenLM/Qwen#1144]
### 实现PR | Implementation PR

启动方式：
```powershell
python -m fastchat.serve.controller > controller.log 2>&1 &
```
```powershell
python -m fastchat.serve.vllm_worker --model-path /home/qwen/lora/Qwen-7B-Chat-Int4/ --tensor-parallel-size 1 --trust-remote-code --dtype float16  > model_worker.log 2>&1 &
```
```powershell
python -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 8001 > api_server.log 2>&1 &
```

调用：
![image](https://github.com/QwenLM/Qwen/assets/28615061/8808b11f-db21-4d6b-ad31-2d039142a6d4)

### 摘要 | Summary

无

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

worker报错：
![image](https://github.com/QwenLM/Qwen/assets/28615061/06f8c59c-fce0-4180-9f88-1629694fa672)
api服务报错：
![image](https://github.com/QwenLM/Qwen/assets/28615061/4b3bdeb6-5f7b-4642-8628-a960db42588f)

### 未解决问题 | Unresolved questions

请问这是什么原因导致的呢？

**Comment by jklj077** [comment]
For the error raised by the worker, you may need to downgrade `fschat<0.2.36` and `vllm<0.2.7`. Unfortunately, FastChat 0.2.36 adopts a quick but dirty way to realize compatibility with vLLM 0.2.7 (<https://github.com/lm-sys/FastChat/blob/b21d0f780ca4472a13714262a0790f2ee1ade659/fastchat/serve/vllm_worker.py#L60>). As QwenTokenizer uses custom code, the change in FastChat introduces an unexpected behaviour (seemingly only) for Qwen.

For the error raised by the api server, it is similar to <https://github.com/QwenLM/Qwen/issues/1062>
