### ISSUE TITLE
怎么控制生成的token数量

### ISSUE THREAD

**Issue by Csy03** [QwenLM/Qwen#1145]
如题……有没有大佬研究过qwen模型在哪能控制模型每次输出的token个数为定值呢

**Comment by jklj077** [comment]
I don't think it is possible. You could instead set the number of max new tokens in generation_config.json. Also I'm very curious why do you need to make the generated token length a fix number?

**Comment by Csy03** [comment]
Thanks for your advice! I've tried to change that max_new_token but maybe I did it the wrong way and it didn't help... And I'm sorry I don't know exactly what the actual scenario is, so I am still trying.



---- 回复的原邮件 ----
| 发件人 | Ren ***@***.***> |
| 日期 | 2024年03月13日 21:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [QwenLM/Qwen] 怎么控制生成的token数量 (Issue #1145) |

I don't think it is possible. You could instead set the number of max new tokens in generation_config.json. Also I'm very curious why do you need to make the generated token length a fix number? What is the actual scenario?

**Comment by Devliang24** [comment]
> 谢谢你的建议！我尝试过更改 max_new_token，但可能我做错了，没有帮助……抱歉，我不知道实际情况到底是怎样的，所以我仍在尝试。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 |任***@***.***> | | 日期 | 2024年03月13日 21:09 | | 营养 | ***@***.***> | | 抄送至| ***@***.***>***@***.***> | | 主题 |回复: [QwenLM/Qwen] 怎么控制生成的代币数量 (Issue #1145 ) |我认为这是不可能的。您可以在 Generation_config.json 中设置最大新令牌数。我也很好奇为什么需要将生成的令牌长度设置为固定数字？实际场景是怎样的？ — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：***@***.***>

hi! bro, have you set up the fixed tokens and gotten a response yet?
