### ISSUE TITLE
OpenAI API形式的调用如何使用系统指令？

### ISSUE THREAD

**Issue by aaronliu7** [QwenLM/Qwen#1148]
如题，OpenAI API形式的接口调用如何使用系统指令的功能？还是现阶段的调用只支持model.chat的形式

**Comment by jklj077** [comment]
OpenAI API uses the messages format. You can just pass the system message as the first message with role "system". 

```
messages: [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "你好"}
    ]
```

**Comment by aaronliu7** [comment]
> OpenAI API uses the messages format. You can just pass the system message as the first message with role "system".
> 
> ```
> "messages": [
>         {"role": "system", "content": "You are a helpful assistant."},
>         {"role": "user", "content": "你好"}
>     ]
> ```

好的，感谢
