### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'bf16'

### ISSUE THREAD

**Issue by houliangxue** [QwenLM/Qwen#1154]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

self.model = AutoModelForCausalLM.from_pretrained(model_path,torch_dtype="auto",device_map="auto",trust_remote_code=True, bf16=True).eval()
        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        self.generation_Config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)

### 期望行为 | Expected Behavior

无

### 运行环境 | Environment

```Markdown
4090显卡，transformer 4.37
，使用bf16=True
```

### 备注 | Anything else?

TypeError: __init__() got an unexpected keyword argument 'bf16'

**Comment by jklj077** [comment]
Don't mix the use of Qwen and Qwen1.5 code examples. For information on Qwen1.5, please refer to <https://github.com/Qwen/Qwen1.5> or <https://qwen.readthedocs.io/en/latest/>.
