### ISSUE TITLE
arm版本docker镜像

### ISSUE THREAD

**Issue by abigstupidbear** [QwenLM/Qwen#1156]
### 摘要 | Summary

目前docker里面是X86版本的，是否能提供arm版本的docker镜像

### 基本示例 | Basic Example

目前docker里面是X86版本的，是否能提供arm版本的docker镜像

### 缺陷 | Drawbacks

目前docker里面是X86版本的，是否能提供arm版本的docker镜像

**Comment by jklj077** [comment]
As stated in the README, Qwen(1.0) code and models will not receive further updates. Please try upgrading to Qwen1.5 and direct your request to <https://github.com/QwenLM/Qwen>.
