### ISSUE TITLE
文档阅读的千问大模型

### ISSUE THREAD

**Issue by 474420502** [QwenLM/Qwen#1162]
### 起始日期 | Start Date

03/20/2024

### 实现PR | Implementation PR

请问有文档阅读的千问大模型开源吗,  我找不到, 不知道是那个. 谢谢回答, 目前国内开源就千问最好. 实力最强

### 相关Issues | Reference Issues

请问有文档阅读的千问大模型开源吗,  我找不到, 不知道是那个. 谢谢回答, 目前国内开源就千问最好. 实力最强

### 摘要 | Summary

请问有文档阅读的千问大模型开源吗,  我找不到, 不知道是那个. 谢谢回答, 目前国内开源就千问最好. 实力最强

### 基本示例 | Basic Example

请问有文档阅读的千问大模型开源吗,  我找不到, 不知道是那个. 谢谢回答, 目前国内开源就千问最好. 实力最强

### 缺陷 | Drawbacks

请问有文档阅读的千问大模型开源吗,  我找不到, 不知道是那个. 谢谢回答, 目前国内开源就千问最好. 实力最强

**Comment by jklj077** [comment]
If you are looking for the functionality of RAG, you can take a look at Qwen-Agent or LangChain or LlamaIndex. I don't think there is a Qwen model released specifically for this use.
