### ISSUE TITLE
想请问模型合并的时候没有看到原模型是怎么加路径的，只看到lora权重路径

### ISSUE THREAD

**Issue by GXKIM** [QwenLM/Qwen#1163]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()

merged_model = model.merge_and_unload()
# max_shard_size and safe serialization are not necessary. 
# They respectively work for sharding checkpoint and save the model to safetensors
merged_model.save_pretrained(new_model_directory, max_shard_size="2048MB", safe_serialization=True)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by swilly0906** [comment]
可以參考我去年的疑問 問題2最後一段文字(應該跟您的疑問一樣?
https://github.com/QwenLM/Qwen/issues/470

**Comment by GXKIM** [comment]
> 可以參考我去年的疑問 問題2最後一段文字(應該跟您的疑問一樣? #470

我也可以正常合并，我只是好奇，我没写微调前路径的情况下，是怎么和Lora权重合并的

合并之后也可以正常加载，只是我没看到微调前路径的路径

**Comment by jklj077** [comment]
`adapter_config.json` keeps a record of the base model name or path.
