### ISSUE TITLE
💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by fangmeichuan** [QwenLM/Qwen#1164]
### 摘要 | Summary

我微调72b int4模型之后，想要加载模型进行推理，加载的时候报错，报错情况如下

### 基本示例 | Basic Example

<img width="965" alt="企业微信截图_17109895033309" src="https://github.com/QwenLM/Qwen/assets/52958444/cb04d937-0300-48d8-b307-03e08d3c3d61">

### 缺陷 | Drawbacks

推理报错

### 未解决问题 | Unresolved questions

有哪位大神帮我分析分析吗

**Comment by fangmeichuan** [comment]
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /data/fmc/my_qianwen/output_qwen2.

**Comment by jklj077** [comment]
You used Q-LoRA and tried to load it in a wrong way. Please **read** the README. 

![image](https://github.com/QwenLM/Qwen/assets/17811943/40a92dff-7f5e-4dfc-9e9a-b46fb7a74ef8)
