### ISSUE TITLE
微调加载微调模型显存不够，RuntimeError: CUDA error: invalid device ordinal CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions

### ISSUE THREAD

**Issue by xvgaoxing2023** [QwenLM/Qwen#1165]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="cuda:2",
    trust_remote_code=True
).eval()

### 期望行为 | Expected Behavior

正常加载微调模型

### 复现方法 | Steps To Reproduce

from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="cuda:2",
    trust_remote_code=True
).eval()
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.0420.04.6
- Python:3.8
- Transformers:4.39.0
- PyTorch:2.1.2
- CUDA:12.1
```

**Comment by xvgaoxing2023** [comment]
我使用的是4090的显卡，24G,使用q_lora成功微调，就是不能加载微调后的模型，总是报显存不够！，请指导

**Comment by xvgaoxing2023** [comment]
我使用的是4090的显卡，24G,使用对Qwen-7B-Chat-Int4模型进行q_lora成功微调，就是不能加载微调后的模型，总是报显存不够！，请指导

**Comment by jklj077** [comment]
> CUDA error: invalid device ordinal

Please double check if `cuda:2` is a valid device.
