### ISSUE TITLE
損失函數計算(評估)方式

### ISSUE THREAD

**Issue by swilly0906** [QwenLM/Qwen#1167]
您好
我用A100進行 [finetune_lora_single_gpu.sh](https://github.com/QwenLM/Qwen/blob/main/finetune/finetune_lora_single_gpu.sh)訓練
我會看到很多次的loss數字變化

我個人理解LLM計算loss的做法
都是算下一個字詞(token)出現的log_loss序列
來評估的
不過我看您的技術報告 好像沒有特別寫??(還是其實有 但我沒看到 抱歉)

想請問code裡面有哪一段(或哪幾段) 
是評估/計算 loss的做法?

我想要了解一下

感恩

**Comment by jklj077** [comment]
In `transformers`, it is normally written in the `modeling_<modelname>.py` file.

Please refer to the following for the code that computes the loss for Qwen: 
<https://huggingface.co/Qwen/Qwen-7B/blob/ef3c5c9c57b252f3149c1408daf4d649ec8b6c85/modeling_qwen.py#L1062-L1070>.
