### ISSUE TITLE
在使用多卡做Qwen-7B-Chat做微调过程中出现ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: finetune/ds_config_zero3.json

### ISSUE THREAD

**Issue by TuDaCheng** [QwenLM/Qwen#1171]
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: finetune/ds_config_zero3.json

**Comment by jklj077** [comment]
Please double check if the finetune/ds_config_zero3.json file exists and can be accessed relative to the working path of the program.

**Comment by JYru** [comment]
finetune/ds_config_zero3.json is this file in where?
