### ISSUE TITLE
deepspeed 单机多卡训练报错 

### ISSUE THREAD

**Issue by GXKIM** [QwenLM/Qwen#1175]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

bash 脚本：
```
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

MODEL="/data/ai/data/models/Qwen-14B-Chat"
DATA="/data/ai/user/Qwen1_1/SRM_final_qwen.json"
DEEPSPEED="/data/ai/user/Qwen1_1/finetune/ds_z3_config.json"

GPUS_PER_NODE=8
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost

MASTER_PORT=9902

function usage() {
    echo '
Usage: bash finetune/finetune_ds_sh [-m MODEL_PATH] [-d DATA_PATH]
'
}

while [[ "$1" != "" ]]; do
    case $1 in
        -m | --model )
            shift
            MODEL=$1
            ;;
        -d | --data )
            shift
            DATA=$1
            ;;
        -h | --help )
            usage
            exit 0
            ;;
        * )
            echo "Unknown argument ${1}"
            exit 1
            ;;
    esac
    shift
done

export CUDA_VISIBLE_DEVICES=0,1






DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen1 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 512 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --deepspeed $DEEPSPEED
```
传参方式，正常可以训练：
```
deepspeed --include localhost:0,1,3,5 --master_port 9901 finetune.py  --deepspeed /data/ai/user/Qwen1_1/finetune/ds_z3_config.json --model_name_or_path  /data/ai/data/models/Qwen-14B-Chat --data_path /data/ai/user/Qwen1_1/SRM_final_qwen.json --bf16 True  --output_dir /data/ai/user/Qwen1_1/output_srm_qwen --num_train_epochs 5 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8  --evaluation_strategy "no"   --save_strategy "steps"  --save_steps 1000 --save_total_limit 10 --learning_rate 3e-4 --weight_decay 0.1 --adam_beta2 0.95  --warmup_ratio 0.01 --lr_scheduler_type "cosine"  --logging_steps 100  --report_to "none" --model_max_length 512 --lazy_preprocess True --use_lora --gradient_checkpointing
```
deepspeed配置 
```
{
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "zero_optimization": {
    "stage": 3,
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  }
}
```
不知道finetune_ds_sh哪里写的不对

### 运行环境 | Environment

```Markdown
- OS: centos 7
- Python: 3.9
- Transformers: 4.37.2
- PyTorch: 2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by jklj077** [comment]
Please report actual errors.

**Comment by GXKIM** [comment]
> Please report actual errors. What error did you meet?

/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-27 17:06:27,107] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-03-27 17:06:27,108] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-27 17:06:27,145] [INFO] [comm.py:637:init_distributed] cdb=None
/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-27 17:06:27,188] [INFO] [comm.py:637:init_distributed] cdb=None
Traceback (most recent call last):
  File "/data/ai/user/jingx/Qwen1_1/finetune.py", line 392, in <module>
    train()
  File "/data/ai/user/jingx/Qwen1_1/finetune.py", line 267, in train
    ) = parser.parse_args_into_dataclasses()
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 124, in __init__
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/training_args.py", line 1483, in __post_init__
    and (self.device.type != "cuda")
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/training_args.py", line 1921, in device
    return self._setup_devices
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/transformers/training_args.py", line 1853, in _setup_devices
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/accelerate/state.py", line 207, in __init__
    torch.cuda.set_device(self.device)
  File "/data/miniconda3/envs/vllm/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by GXKIM** [comment]
> Please report actual errors. What error did you meet?

Could it be that the torch version is too high? However, in that case, the way of passing parameters would also cause an error, but it doesn't. Personally, I think it's still a script error.

**Comment by GXKIM** [comment]
> Please report actual errors. What error did you meet?

qwen 14B-chat muti-gpu deepspeed zero3 
![image](https://github.com/QwenLM/Qwen/assets/125621025/4004aafc-980f-4887-b60a-8dcd69207097)

qwen1.5 14B-chat muti-gpu deepspeed zero3 
![image](https://github.com/QwenLM/Qwen/assets/125621025/41663dc8-076d-47f8-b387-c8aa2675ecb6)

**Comment by jklj077** [comment]
The error is
```
RuntimeError: CUDA error: invalid device ordinal
```

In the script you provided
```
GPUS_PER_NODE=8
...
export CUDA_VISIBLE_DEVICES=0,1
```

the rest 6 gpus are invalid, thus causing the error.

**Comment by GXKIM** [comment]
> The error is 错误是
> 
> ```
> RuntimeError: CUDA error: invalid device ordinal
> ```
> 
> In the script you provided在您提供的脚本中
> 
> ```
> GPUS_PER_NODE=8
> ...
> export CUDA_VISIBLE_DEVICES=0,1
> ```
> 
> the rest 6 gpus are invalid, thus causing the error.其余 6 个 GPU 无效，从而导致错误。

Thank you for your reply. I was able to run it normally by setting the number of GPUs, thank you very much.
