### ISSUE TITLE
多卡并行微调卡住

### ISSUE THREAD

**Issue by HooRin** [QwenLM/Qwen#1183]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Loading checkpoint shards:  50%|█████████████████████████████████████████████████████████████                                                             | 4/8 [00:03<00:03,  1.12it/s]Formatting inputs...Skip in lazy mode
Formatting inputs...Skip in lazy mode
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.49it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.60it/s]
trainable params: 143,130,624 || all params: 7,864,455,168 || trainable%: 1.8199687192876373
trainable params: 143,130,624 || all params: 7,864,455,168 || trainable%: 1.8199687192876373
Using /root/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Using /root/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu118/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.5540647506713867 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.5108935832977295 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.6046316623687744 seconds

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by HooRin** [comment]
我还想问下，多卡并行的时候，可不可以只在一张卡上放基座

**Comment by jklj077** [comment]
Please check the trouble-shooting guide from NCCL at <https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-direct>. If you can bypass the issue by setting `NVIDIA P2P_DISABLED=1`, it is likely due to misconfiguration of your hardware devices.

**Comment by jklj077** [comment]
I think you need to first understand how parallelism in training works, and here is a good starting point: https://huggingface.co/docs/transformers/v4.39.2/perf_train_gpu_many
