### ISSUE TITLE
May I ask when Lisa fine-tuning is supported?

### ISSUE THREAD

**Issue by zhaoyinjiang9825** [QwenLM/Qwen#1187]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

It is said that Lisa's fine-tuning effect is better than Lora's. Do you have a support plan？

### 期望行为 | Expected Behavior

None

### 复现方法 | Steps To Reproduce

None

### 运行环境 | Environment

```Markdown
None
```

**Comment by jklj077** [comment]
Please be informed that Qwen(1.0) models and codes are actively maintained. We suggest you to upgrade to Qwen1.5.

A key characteristic of Qwen1.5 is its enhanced compatibility with the `transformers` ecosystem, where it seamlessly integrates into the thriving community and harnesses its collective power for capability expansion. Users can leverage Qwen1.5 just as they would any other models within the established `transformers` framework, such as LLaMA or Mistral. One should be able to code more easily with Qwen1.5.
