### ISSUE TITLE
[HELP] I wonder how the MMLU result is evaluated?

### ISSUE THREAD

**Issue by YuMeng2v** [QwenLM/Qwen#1189]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

The test result of Qwen-7B, Qwen-0.5B is lower than reported. I wonder if you test the result after  training with the training set of MMLU?

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by hzhwcmhf** [comment]
All evaluation codes are here: https://github.com/QwenLM/Qwen/tree/main/eval

Please confirm whether the result you want to reproduce was generated by the base model or the chat model. If it is from the base model, please use the corresponding evaluation script (evaluate_mmlu.py) and model (e.g., Qwen1.5-7B not Qwen1.5-7B-Chat).

**Comment by zjintheroom** [comment]
> All evaluation codes are here: https://github.com/QwenLM/Qwen/tree/main/eval
> 
> Please confirm whether the result you want to reproduce was generated by the base model or the chat model. If it is from the base model, please use the corresponding evaluation script (evaluate_mmlu.py) and model (e.g., Qwen1.5-7B not Qwen1.5-7B-Chat).

你好，想问一下，这部分代码的评测适用于qwen2的模型么

**Comment by NkdmsL** [comment]
I run the evaluation script for `'Qwen/Qwen2-0.5B-Instruct'` variant and the results I am getting are 

 total cnt: 14042 

stem ACC: 37.58 
Humanities ACC: 40.89 
other ACC: 48.28 
social ACC: 50.02 
AVERAGE ACC:43.78

Which are different from HF and Technical report. Can you please shade some light?
