### ISSUE TITLE
openai_api.py启动的时候添加了username/password, 然后调用的时候怎么传入username/password呢？

### ISSUE THREAD

**Issue by zengqingfu1442** [QwenLM/Qwen#1190]
https://github.com/QwenLM/Qwen/blob/main/openai_api.py#L581 在启动openai_api.py加上了`--api-auth=username:password` 参数，那么在使用`openai.ChatCompletion.create` 调用接口的时候，如何传入这个username/password呢？是在openai.api_key 这里设置？

**Comment by jklj077** [comment]
It roughly implements HTTP Basic authentication and the client sends _the user name and password as unencrypted base64 encoded text_. **It should only be used over HTTPS.**

You should be able to set the api_key to `base64.b64encode(f'{username}:{password}'.encode()).decode()` (You can save the result string in a safe place for later reuse and treat it like a secret).

If you are using `curl` to directly call the endpoint, pass `-H "Authorization: Basic $API_KEY"` in addition.
