### ISSUE TITLE
[BUG] <title> code_interpreter 生成的图像只能生成到阿里云上么，不能不传到云上，只在本地保存么？

### ISSUE THREAD

**Issue by cheng18175030250** [QwenLM/Qwen#1193]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

 code_interpreter 生成的图像只能生成到阿里云上么，不能不传到云上，只在本地保存么？

**Comment by JianxinMa** [comment]
请问您是用的什么方案提供的code interpreterr？

- 如果是用dashscope或者通义app&网页提供的code Interpreter，那代码本来就是在云上执行的。
- 如果是用 qwen-agent 或 modelscope-agent 提供的 code interpreter，那生成的图片本来就是在本地执行、存放于本地的，并没有用到阿里云。

**Comment by JianxinMa** [comment]
另外，本仓库（qwen1）已废弃。可以移步 qwen1.5 或 qwen-agent 的仓库提 issues。
