### ISSUE TITLE
[BUG] <title> 如何用vllm部署qlora后的模型

### ISSUE THREAD

**Issue by KevinFan0** [QwenLM/Qwen#1197]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 期望行为 | Expected Behavior

请问下如何使用vllm部署qlora微调后的模型呢？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by cv2-bo** [comment]
同问
