### ISSUE TITLE
how to convert qwen.tiktoken to tokenzier.model

### ISSUE THREAD

**Issue by cloudyuyuyu** [QwenLM/Qwen#1204]
### 摘要 | Summary

端侧推理引擎只能兼容 tokenizer.model，无法支持tiktoken模式

### 基本示例 | Basic Example

端侧推理引擎只能兼容 tokenizer.model

### 缺陷 | Drawbacks

端侧推理引擎只能兼容 tokenizer.model

**Comment by jklj077** [comment]
Please refer to tokenization_note.md in this repo. Essentially, they are different algorithms and converting BPE vocabulary at the byte-level to sentencepiece vocabulary simply cannot be done due to inherent differences.
