### ISSUE TITLE
[BUG] lora微调后,合并成一个模型。这种方式如何加载且推理

### ISSUE THREAD

**Issue by wangyao123456a** [QwenLM/Qwen#1220]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by wangyao123456a** [comment]
@jklj077  but 按照你的建议运行出会提示 lora 参数没有加载上，请问配置文件需要对应修改吗

**Comment by jklj077** [comment]
Show your code.
