### ISSUE TITLE
请问基于qwen-72b-chat，基于怎样的配置可以在一台4090上训练起来？

### ISSUE THREAD

**Issue by taishan1994** [QwenLM/Qwen#1224]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
For ZeRO Stage 2, having each GPU capable of holding the entire model is a bare minimum requirement. Given that Qwen-72B-Chat-Int4 exceeds 40GB, trying to finetune a model of this scale using Q-LoRA with GPUs that only have 24GB (or even 48GB) of memory simply won't cut it.

**Comment by taishan1994** [comment]
了解了，谢谢您的回答。
