### ISSUE TITLE
请问哪里可以找到qwen用于vllm的jinja template?

### ISSUE THREAD

**Issue by xudong2019** [QwenLM/Qwen#1236]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
chat_template in tokenizer_config.json in Qwen1.5 models. For example, <https://huggingface.co/Qwen/Qwen1.5-7B-Chat/blob/main/tokenizer_config.json#L31>
