### ISSUE TITLE
本地部署后，运行很慢啊 

### ISSUE THREAD

**Issue by wangwm** [QwenLM/Qwen#1245]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

本地部署后，cpu和磁盘占用率过高。chatbot聊天 1分钟出一个字。什么原因啊？

![3a424b2d0de57970872103881be2148](https://github.com/QwenLM/Qwen/assets/2868767/61634904-f634-4ad9-82b7-753916a6596d)

**Comment by wangwm** [comment]
直接 git clone https://github.com/QwenLM/Qwen-7B.git   。不知道是哪个版本，我的显卡是rtx3060 ，没被使用。磁盘io非常高

**Comment by 1asdasdasda** [comment]
我是使用的docker部署的。没有直接clone代码。可以使用Ollama部署Qwen模型，挺方便的

**Comment by jklj077** [comment]
As Qwen1.0 is no longer actively maintained, we kindly ask to you migrate to [Qwen1.5](https://github.com/QwenLM/Qwen1.5) and direct your related question there. Thanks for you cooperation.
