### ISSUE TITLE
使用SFTTrainer微调时遇到的问题

### ISSUE THREAD

**Issue by Mx-Lvq** [QwenLM/Qwen#125]
总是会出现下面的错误：ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`. 当我在前面加上了 tokenizer.pad_token = tokenizer.eos_token 后依然会产生报错，有什么可以解决的办法？

**Comment by jklj077** [comment]
您好，感谢您对本项目的支持！但我们尚未支持模型微调。如您使用其它库进行模型微调，有可能该库并未适配Qwen-7B系列模型，建议您与所述库的维护人员联系。

对于该问题提示，可以在tokenizer初始化的时候，指定pad_token为任意已知的特殊token。如
```python
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-7B", trust_remote_code=True, pad_token="<|endoftext|>")
```
关于tokenizer的说明，请见[这里](https://github.com/QwenLM/Qwen-7B/blob/main/tokenization_note_zh.md)

**Comment by jklj077** [comment]
我们提供了基于tranformers Trainer的微调代码示例，支持Qwen-7B和Qwen-7B-Chat的微调，其中包括全参数微调、LoRA以及Q-LoRA。欢迎试用参考~
