### ISSUE TITLE
Qwen pre_trained, 打印一下内容，就没有了，不确定是否训练完成

### ISSUE THREAD

**Issue by lenovoDTC** [QwenLM/Qwen#1252]
![image](https://github.com/QwenLM/Qwen/assets/28916374/837f1084-69d1-4765-82a9-0d8ec14f3213)

**Comment by jklj077** [comment]
Hi, it is necessary to describe your issue with more details. For example, what is "Qwen pre_trained"? what code were you running? Please ensure that you were training the model instead of just loading the model.

**Comment by jklj077** [comment]
Anyhow, Qwen1.0 is no longer actively maintained, and we kindly ask to you migrate to [Qwen1.5](https://github.com/QwenLM/Qwen1.5), and direct your related question there. Thanks for you cooperation.
