### ISSUE TITLE
[BUG] 转换Qwen1.5-14B报错

### ISSUE THREAD

**Issue by rickywu** [QwenLM/Qwen#1256]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用docker_qwen.sh在升腾910B上转换Qwen1.5-14B-Chat

### 期望行为 | Expected Behavior

正常转换

### 复现方法 | Steps To Reproduce

使用docker_qwen.sh在升腾910B上转换Qwen1.5-14B-Chat

### 运行环境 | Environment

```Markdown
- OS: KylinOS V10
- Python: 3.9
- Transformers: 
- PyTorch: 
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Hi!

This is the repo for Qwen(1.0) model series and the materials provided here **DO NOT** apply to Qwen1.5. It is expected that it does not work. There is a clear warning at the README. 
![image](https://github.com/QwenLM/Qwen/assets/17811943/ef17ca73-2310-42ac-9366-43c7a4538e3b)

As to your original question, we advise to refer to mindformers, as they have provided support for certain Qwen1.5 models: <https://gitee.com/mindspore/mindformers/blob/dev/research/qwen1_5/qwen1_5.md>.
