### ISSUE TITLE
多轮对话训练数据格式组织

### ISSUE THREAD

**Issue by yangxin60-tal** [QwenLM/Qwen#1258]
我现在想基于多轮对话数据来微调模型，想问下训练数据的格式应该怎么组织呢

**Comment by jklj077** [comment]
As Qwen1.0 is no longer actively maintained, we kindly ask to you migrate to [Qwen1.5](https://github.com/QwenLM/Qwen1.5) and direct your related question there. Thanks for you cooperation.
