### ISSUE TITLE
运行web_demo.py程序时问答卡顿

### ISSUE THREAD

**Issue by xiaofeixuan** [QwenLM/Qwen#1271]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

通过执行web端示例程序时，从页面输入问答，到页面能正常显示，并且受到返回的信息，最少需要3-5分钟的反应时间，不是说输入马上就有反馈，怎么可以实现像示例中一样，发送了数据马上会有返回结果，没有这么长时间的延时

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.31.0
- PyTorch:2.3
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
Hi, I don't think it could lead to meaningful conclusions with the information provided. Anyhow, please upgrade to Qwen1.5; this repo is no longer actively maintained.
