### ISSUE TITLE
[BUG] <title>Qwen有支持OpenAI形式的functoncall的计划吗

### ISSUE THREAD

**Issue by hanshaofei** [QwenLM/Qwen#1273]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

已经查看：“如何让 Qwen-7b 使用 Langchain 中的 工具”，目前只能使用React和prompt自己实现代码，调用工具，过程比较复杂，主要原因是在“built-in support for function calling”,只能通过prompt控制，会打断所有的流程，chatglm目前支持function call，但是识别效率很低

### 期望行为 | Expected Behavior

期望Qwen能够支持function call，简化大模型落地步骤。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Hi, Qwen1.0 is not actively maintained and we advise you to upgrade to Qwen1.5/2 with QwenAgent.
