### ISSUE TITLE
量化细节请教

### ISSUE THREAD

**Issue by zixi01chen** [QwenLM/Qwen#1279]
### 摘要 | Summary

请问一下，我看Qwen模型的量化模型效果损失较小，全程都是用Int8推理的吗？还是只是参数Int8，中间反量化为fp16去推理了？

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
Hi, both AWQ and GPTQ are weight quantization.
