### ISSUE TITLE
[BUG] 这模型似乎很固执或直男癌，prompt里明确了不要怎么怎么样，每次输出还是不按要求去

### ISSUE THREAD

**Issue by bolt163** [QwenLM/Qwen#1280]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] #1292

### 当前行为 | Current Behavior
【case1】
<img width="913" alt="企业微信截图_d0ca2981-3c4f-439c-874b-27c946c7a01e" src="https://github.com/QwenLM/Qwen/assets/25170435/c05acd41-1316-4343-8ecb-94582f42ae43">

【case2】
<img width="901" alt="企业微信截图_e70e6d93-e315-4404-9d3a-55f1cd2d3834" src="https://github.com/QwenLM/Qwen/assets/25170435/3753e32d-04ed-4923-a5cd-6b19d28fae3a">

### 期望行为 | Expected Behavior

尽量符合prompt的要求
【llama3-8B的效果】
<img width="874" alt="企业微信截图_59c5cbbd-6a1f-419b-bb61-1ab04af20ea7" src="https://github.com/QwenLM/Qwen/assets/25170435/8c67ef15-649d-45d5-8aca-3558cf404aa1">

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
The Qwen1.0 models will not be updated any more. You have opened the same issue in Qwen2.0 repo.
