### ISSUE TITLE
如何修改模型的结构

### ISSUE THREAD

**Issue by zzc-1024** [QwenLM/Qwen#1290]
我想要通过修改模型的结构，实现让模型在保留原来的lm_head和权重的基础上，新增一个用于标注的lm_head，但是我发现transformers并没有提供修改模型结构的相关接口，请问有没有什么办法可以修改模型的结构（使用torch或者tf实现均可）。

**Comment by jklj077** [comment]
I don't quite understand. In the modeling code, `transformers` modules are PyTorch `nn.Module`s, and you can just modify the code as you wish.
