### ISSUE TITLE
Qwen 的开源模型能输出 logprobs吗？

### ISSUE THREAD

**Issue by Miracle1207** [QwenLM/Qwen#1294]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Artessay** [comment]
调用dashscope的qwen-turbo，qwen-plus等模型时，可以正常获取logprob，但是调用qwen2-7b-instruct等模型时却无法获取。是不是开源的模型没有提供相关输出呢？

**Comment by bigbrother001** [comment]
我也想知道怎么获得logits
