### ISSUE TITLE
[BUG] docker_openai_api.sh 报can't open file 'openai_api.py'

### ISSUE THREAD

**Issue by juhuan** [QwenLM/Qwen#1296]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

python: can't open file 'openai_api.py': [Errno 2] No such file or directory

### 期望行为 | Expected Behavior

能正常启动镜像

### 复现方法 | Steps To Reproduce

bash docker_openai_api.sh -i qwenllm/qwen:2-cu121 -c ~/Qwen1_5-14B --port 8901

### 运行环境 | Environment

```Markdown
- OS: CentOS Linux release 7.9.2009 (Core)
```

### 备注 | Anything else?

查过镜像内并不存在openai_api.py

**Comment by jklj077** [comment]
你把Qwen和Qwen2搞混了欸。
