### ISSUE TITLE
推理时的显存使用为啥这么少呢？

### ISSUE THREAD

**Issue by renoyuan** [QwenLM/Qwen#1297]
### 相关Issues | Reference Issues

![image](https://github.com/QwenLM/Qwen/assets/50486789/28601caa-5af3-4a9d-bbcc-48e548253de4)

我看一些评论说正常 1B 参数 fp32 推理需要 4G左右。7B *4 =28G
qwen 7B 推理只需要8.2G  比理论上少 20G 请问是怎么做到的呢？

### 摘要 | Summary

为啥qwen 推理时需要使用的显存这么少的？

### 基本示例 | Basic Example

为啥qwen 推理时需要使用的显存这么少的？

### 缺陷 | Drawbacks

为啥qwen 推理时需要使用的显存这么少的？

**Comment by jklj077** [comment]
int4
