### ISSUE TITLE
大模型function call对比传统nlp方式有什么优势？

### ISSUE THREAD

**Issue by LawlightXY** [QwenLM/Qwen#1300]
function call通过识别要调用的工具+抽取工具所需的参数来实现工具调用。想问下这样做对比传统的意图识别（调用什么工具）+信息抽取（参数抽取）有什么优势呢？都能实现相似的功能。

**Comment by xueyouluo** [comment]
个人感觉：
优点：

1. 接入效率高，无需去训练模型判断意图和做槽位提取，可以方便的通过修改工具描述和系统说明来调整、加减工具；（当然，效果不好还是得微调）；
2. 可能可以省掉workflow，模型自己判断需要调用哪些工具，或者只需要在系统描述中使用自然语言描述；
3. 语义理解更好，比如经典case：帮我查附近的美食，不要日料，基于意图和槽位容易翻车。
4. 开发简单一些，不用维护太多模块

缺点：

1. 黑盒，你也不知道它什么时候会调用工具，什么时候不调用，或者什么时候停止调用
2. 慢，如果是多步骤，还得调多次
3. 如果模型能力不行，听不懂指令，或者业务有些复杂逻辑，模型理解不了就很难受，只能靠微调，代价大

**Comment by tarfnet** [comment]
抽取工具所需的参数来实现工具调用效果不好
