### ISSUE TITLE
[BUG] <title>  文档中function call 的示例有误

### ISSUE THREAD

**Issue by zzj2404** [QwenLM/Qwen#1301]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行api文档中如下位置的function call ：
https://help.aliyun.com/zh/model-studio/developer-reference/use-qwen-by-calling-api?spm=a2c4g.11186623.0.0.459619a1mT8CvR#b5e1375f75n6f

得到参数错误：
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'messages with role "tool" must be a response to a preceeding message with "tool_calls".', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-3f265697-994d-9539-822b-508190d7e7e9'}

### 期望行为 | Expected Behavior

```python
    first_response = client.chat.completions.create(
        model="qwen-plus",
        messages=messages,
        tools=tools
    )
    assistant_output = first_response.choices[0].message
```
再加上这行：
```python
    messages.append(assistant_output)
```
之后我能得到正确的输出

### 运行环境 | Environment

```Markdown
- OS: windows10
- Python: 3.10.13
- openai：1.3.6
```

**Comment by jklj077** [comment]
文档好像更新了，看着是修复了。这部分文档由百炼维护，建议通过该页面右下方的小问卷进行反馈呢。

![image](https://github.com/user-attachments/assets/48264b25-b4b4-4b87-bde9-55d47048088e)
