### ISSUE TITLE
请教下为什么Qwen/finetune.py和Qwen/eval/evaluate_ceval.py 的tokenizer的padding_side 不一样呢？

### ISSUE THREAD

**Issue by DemingCheng** [QwenLM/Qwen#1302]
请教下为什么Qwen/finetune.py 和 Qwen/eval/evaluate_ceval.py 的padding_side 不一样呢？
![image](https://github.com/user-attachments/assets/0b30ed4b-ae1e-468b-9fd5-d157ce2d8d66)
![image](https://github.com/user-attachments/assets/43dd94aa-a95c-4f7b-9f1b-58039aba94f1)

**Comment by jklj077** [comment]
理论上padding是对模型无影响的，但由于`transformers`中相关代码的具体实现，batch generation必须left padding。
