### ISSUE TITLE
请问可以支持加入本地知识库进行微调大模型吗

### ISSUE THREAD

**Issue by jingmingtao** [QwenLM/Qwen#1314]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

请问可以支持加入本地知识库进行微调大模型吗

### 期望行为 | Expected Behavior

请问可以支持加入本地知识库进行微调大模型吗

### 复现方法 | Steps To Reproduce

请问可以支持加入本地知识库进行微调大模型吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

请问可以支持加入本地知识库进行微调大模型吗

**Comment by jingmingtao** [comment]
请问我想要微调，让模型回答同学的名字与出生日期，我的微调数据可以这么设计吗：[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "人名与生日"
      },
      {
        "from": "assistant",
        "value": "人名:小明,出生日期: 2021年5月11日"
      },
      {
        "from": "assistant",
        "value": "人名:小涛,出生日期: 2008年6月23日"
      }
    ]
  }
]
我想要达到这样的效果：问大模型，请问2021年5月11日出生的人名字是谁

**Comment by zpge** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> 请问可以支持加入本地知识库进行微调大模型吗
> 
> ### 期望行为 | Expected Behavior
> 请问可以支持加入本地知识库进行微调大模型吗
> 
> ### 复现方法 | Steps To Reproduce
> 请问可以支持加入本地知识库进行微调大模型吗
> 
> ### 运行环境 | Environment
> ```
> - OS:
> - Python:
> - Transformers:
> - PyTorch:
> - CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
> ```
> 
> ### 备注 | Anything else?
> 请问可以支持加入本地知识库进行微调大模型吗

同问，目前提供的微调方式都是构建对话的，如果我有很多文档，想先让模型学一些领域知识，应该怎么微调？
