### ISSUE TITLE
[BUG] <title> 多卡推理报错

### ISSUE THREAD

**Issue by 87oo** [QwenLM/Qwen#132]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [x] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

运行readme中的示例和cli_demo.py，单卡推理正常，但是多卡推理会报错。

报错部分片段如下：

│   2675 │   │   │                                                             │
│   2676 │   │   │   # sample                                                  │
│   2677 │   │   │   probs = nn.functional.softmax(next_token_scores, dim=-1)  │
│ ❱ 2678 │   │   │   next_tokens = torch.multinomial(probs, num_samples=1).squ │
│   2679 │   │   │                                                             │
│   2680 │   │   │   # finished sentences should have their next token be a pa │
│   2681 │   │   │   if eos_token_id is not None:                              │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

Process finished with exit code 1

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
多卡推理的需求是想做多卡部署，把模型切分到不同的卡上对吧？这块我们还没支持，我看下

**Comment by tanhzongbei** [comment]
> 多卡推理的需求是想做多卡部署，把模型切分到不同的卡上对吧？这块我们还没支持，我看下

请问现在支持了吗？我也遇到这个问题了

**Comment by JustinLin610** [comment]
目前已经支持

**Comment by AnitaSherry** [comment]
> 目前已经支持

有代码吗？
