### ISSUE TITLE
请问Qwen支持的Tools有哪些？可以给出一个列表吗？💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by liucongg** [QwenLM/Qwen#148]
### 摘要 | Summary

请问Qwen支持的Tools有哪些？可以给出一个列表吗？自己尝试定义一些工具，发现Qwen没有办法很好的识别，Thought过程会忽略自定义的Tools，想知道Qwen在训练的时候，本身使用了哪些工具来微调模型。

### 基本示例 | Basic Example

自定义工具声明如下：
{
        'name_for_human': '图谱查询',
        'name_for_model': 'gremlin_execute',
        'description_for_model': '图谱查询是一个图谱查询服务，输入gremlin语句，基于现有知识图谱执行gremlin，获取答案。',
        'parameters': [{'name': 'gremlin_str',
                        'description': 'gremlin语句查询',
                        'required': True,
                        'schema': {'type': 'string'},
                        }],
    }
不知道是否是自己定义时写的有问题。

### 缺陷 | Drawbacks

无

**Comment by JianxinMa** [comment]
qwen-7b 训练时见过的工具比较类似 https://www.apispace.com/ 这类网站里的这些 APIs。

我不了解图谱和gremlin，请问一般什么问题适合“图谱查询”呢，方便提供典型的 user question 用于测试吗？

以下是我测试的效果：

为了可复现，首先关闭 sampling：
```py

model.generation_config.do_sample = False  # greedy decoding
```

输入的prompt:
```
Answer the following questions as best you can. You have access to the following tools:

gremlin_execute: Call this tool to interact with the 图谱查询 API. What is the 图谱查询 API useful for? 图谱查询是一个图谱查询服务，输入gremlin语句，基于现有知识图谱执行gremlin，获取答案。 Parameters: [{"name": "gremlin_str", "description": "gremlin语句查询", "required": true, "schema": {"type": "string"}}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [gremlin_execute]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 加拿大2023年人口统计数字是多少？
```

qwen-7b的output（配了 stop word）：
```
Thought: 我应该使用图谱查询API来查询加拿大的人口统计数据。
Action: gremlin_execute
Action Input: {"gremlin_str": "call org.apache.tinkerpop.gremlin.driver.GremlinClient('[http://localhost:8182](http://dsw-gateway.pai-damo.alibaba-inc.com/dsw-3060/proxy/8182/)', 'admin', 'password').traversal().V().count().next().asLong()"}
Observation:
```

看起来是能调起来的，只是 action input 不一定对。

**Comment by JianxinMa** [comment]
如果您无法复现的话，请告知我们您使用的框架（比如fastchat）、是否使用了量化等，以便我们排查下非官方的实现是否存在问题。
