### ISSUE TITLE
[BUG]  通过tokenizer和generate进行batch批量推理遇到问题，回答感觉了。不知道哪里写错了。

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen#159]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

import torch

batch_question = ["今天我想吃点啥，甜甜的，推荐下","我马上迟到了，怎么做才能不迟到","我想听你说爱我。"]
batch_input_ids = tokenizer(
        batch_question
        ,padding=True
        ,max_length=2048
        ,truncation=True
        ,return_tensors="pt"
    )
# print(batch_input_ids)
batch_input_ids1 = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
# print(batch_input_ids1)

batch_out_ids = model.generate(
    input_ids=batch_input_ids1
    ,return_dict_in_generate=False
    ,max_length=2048
    # ,do_sample=True
    # ,temperature=0.95
    # ,top_p=0.7
    # ,num_beams=1
    # ,eos_token_id=2
)
batch_response = [tokenizer.decode(o, skip_special_tokens=True) for o in batch_out_ids]
print(batch_response)

返回结果，第二个和第三个回答有问题。
['今天我想吃点啥，甜甜的，推荐下。\n\n\n作为AI语言模型，我可以推荐一些甜食供您选择。以下是一些常见的甜食：\n\n1. 巧克力：巧克力是一种非常受欢迎的甜食，可以是黑巧克力、牛奶巧克力或白巧克力。它具有浓郁的口感和丰富的味道，可以满足甜食爱好者的需求。\n\n2. 糖果：糖果是一种小巧玲珑的甜食，可以是硬糖、软糖或巧克力糖果。糖果有各种各样的口味，包括草莓、蓝莓、柠檬、橙子等等。\n\n3. 果汁冰沙：果汁冰沙是一种健康的甜食，由果汁、冰块和一些配料组成。它具有清新的口感和多种口味，可以满足甜食爱好者的需求。\n\n4. 蛋糕：蛋糕是一种非常受欢迎的甜食，可以是戚风蛋糕、海绵蛋糕或慕斯蛋糕。蛋糕有各种各样的口味和装饰，可以满足不同的需求。\n\n5. 酸奶：酸奶是一种非常健康的甜食，由酸奶、水果和谷物组成。它具有丰富的口感和多种口味，可以满足甜食爱好者的需求。\n\n希望这些建议能够帮助您找到适合自己的甜食。\n', '我马上迟到了，怎么做才能不迟到\n\n\n\n\n', '我想听你说爱我。\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n']

### 期望行为 | Expected Behavior

回答正常。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by wellcasa** [comment]
整体代码如下。
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

model_path = "/mnt/workspace/llm/model/manual/qwen2/Qwen-7B-Chat"
# model_path = "Qwen/Qwen-7B-Chat"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
## use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
## use fp16
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cuda:1", trust_remote_code=True, fp16=True).eval()
# use fp32
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True) # 可指定不同的生成长度、top_p等相关超参
tokenizer.add_special_tokens({
    "pad_token": "<|extra_0|>",
})
# tokenizer.add_special_tokens({
#     "bos_token": "<|extra_1|>",
#     "eos_token": "<|extra_2|>",
#     "unk_token": "<|extra_3|>",
#     "sep_token": "<|extra_4|>",
#     "pad_token": "<|extra_5|>",
# })

import torch


batch_question = ["今天我想吃点啥，甜甜的，推荐下","我马上迟到了，怎么做才能不迟到","我想听你说爱我。"]
batch_input_ids = tokenizer(
        batch_question
        ,padding=True
        ,max_length=2048
        ,truncation=True
        ,return_tensors="pt"
    )
# print(batch_input_ids)
batch_input_ids1 = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
# print(batch_input_ids1)

batch_out_ids = model.generate(
    input_ids=batch_input_ids1
    ,return_dict_in_generate=False
    ,max_length=2048
    # ,do_sample=True
    # ,temperature=0.95
    # ,top_p=0.7
    # ,num_beams=1
    # ,eos_token_id=2
)
batch_response = [tokenizer.decode(o, skip_special_tokens=True) for o in batch_out_ids]
print(batch_response)

**Comment by jklj077** [comment]
感谢支持Qwen-7B！

我们发现您在使用`.generate(...)`方法调用Qwen-7B-Chat模型。

1. 请注意Qwen-7B-Chat对输入数据的格式有特殊规定（ChatML）格式，建议您使用`.chat(...)`方法调用（推理时单条数据的格式类似`"<|im_start|>user\n今天我想吃点啥，甜甜的，推荐下<|im_end|>\n<|im_start|>assistant\n"`，chat相关代码中包含相关逻辑）。由于不同样本间的对话历史路径可能非常不同，该方法尚未支持批量推理。
2. 使用batch推理，但样本长度不同时，padding建议设置为left padding。
   ```python
   tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B-Chat', trust_remote_code=True, padding_side="left", pad_token="<|endoftext|>") # pad_token用其它的特殊token也可以
   ```
   但需要提醒您，我们目前不建议使用generate方法进行Qwen-7B-Chat模型推理。

**Comment by wellcasa** [comment]
好的。听你这么说我， 弄出来。 非常感谢。给有需要的人。

只不过参数的设置，我看官方给的都是默认值。

`from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

model_path = "/mnt/workspace/llm/model/manual/qwen2/Qwen-7B-Chat"
# model_path = "Qwen/Qwen-7B-Chat"
# tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B-Chat', trust_remote_code=True, padding_side="left", pad_token="<|endoftext|>") # pad_token用其它的特殊token也可以
## use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
## use fp16
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cuda:3", trust_remote_code=True, fp16=True).eval()
# use fp32
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True) # 可指定不同的生成长度、top_p等相关超参
import torch


batch_question = ["<|im_start|>user\n今天我想吃点啥，甜甜的，推荐下<|im_end|>\n<|im_start|>assistant\n",
                  "<|im_start|>user\n我马上迟到了，怎么做才能不迟到<|im_end|>\n<|im_start|>assistant\n",
                  "<|im_start|>user\n我想听你说爱我。<|im_end|>\n<|im_start|>assistant\n"
                 ]
batch_input_ids = tokenizer(
        batch_question
        ,padding=True
        ,max_length=1024
        ,truncation=True
        ,return_tensors="pt"
    )
batch_input_ids1 = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
print("batch_input_ids \r\n{}".format(batch_input_ids))
batch_out_ids = model.generate(
    input_ids=batch_input_ids1
    ,max_length=2048
    # ,temperature=0.95
    # ,top_p=0.7
    # ,do_sample=True
    # ,num_beams=1
)
batch_response = [tokenizer.decode(o, skip_special_tokens=True) for o in batch_out_ids]
print(batch_response)
`

**Comment by bh4ffu** [comment]
@jklj077 由于不同样本间的对话历史路径可能非常不同，该方法尚未支持批量推理。

**Comment by bh4ffu** [comment]
@jklj077 由于不同样本间的对话历史路径可能非常不同，该方法尚未支持批量推理。

我看chat方法内部也是调用的generate，所以能详细科普一下为啥chat不能支持批量推理么？这个解析没太理解，非常感谢！

**Comment by heihei2015** [comment]
> > 感谢支持Qwen-7B！
> > 我们发现您在使用`.generate(...)`方法调用Qwen-7B-Chat模型。
> > 
> > 1. 请注意Qwen-7B-Chat对输入数据的格式有特殊规定（ChatML）格式，建议您使用`.chat(...)`方法调用（推理时单条数据的格式类似`"<|im_start|>user\n今天我想吃点啥，甜甜的，推荐下<|im_end|>\n<|im_start|>assistant\n"`，chat相关代码中包含相关逻辑）。由于不同样本间的对话历史路径可能非常不同，该方法尚未支持批量推理。
> > 2. 使用batch推理，但样本长度不同时，padding建议设置为left padding。
> >    ```python
> >    tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B-Chat', trust_remote_code=True, padding_side="left", pad_token="<|endoftext|>") # pad_token用其它的特殊token也可以
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    但需要提醒您，我们目前不建议使用generate方法进行Qwen-7B-Chat模型推理。
> 
> 希望能扩展支持batch的chat方法，否则测试ceval和mmlu太慢了。我自己尝试将chat方法改成batch形式的，然而发现只要加了pad token的模型回答都很差
> 
> ```
> tokenizer = transformers.AutoTokenizer.from_pretrained(
>         path,
>         cache_dir=None,
>         model_max_length=2048,
>         padding_side="left",
>         use_fast=False,
>         trust_remote_code=True,
>         pad_token='<|endoftext|>'
>     )
> pad_id = tokenizer.encode('<|endoftext|>')
> model.generation_config = GenerationConfig.from_pretrained(path, trust_remote_code=True)
> model.generation_config.do_sample = False
> all_raw_text = ['给我推荐一些深度学习的学习资料', '实现一个银行系统，包括存钱、取钱、转账等多项业务，最恰当的资源组合方式是____ A. 继承 B.重载 C.组合 D.实例化']
> question = []
> for q in all_raw_text:
>     raw_text, _ = make_context(
>         tokenizer,
>         q,
>         system="You are a helpful assistant.",
>         max_window_size=6144,
>         chat_format=model.generation_config.chat_format,
>     )
>     question.append(raw_text)
> 
> x = tokenizer(question, padding=True)
> input_ids = torch.tensor(x['input_ids'], dtype=torch.long).to(model.device)
> attention_mask = torch.tensor(x['attention_mask'], dtype=torch.long).to(model.device)
> 
> stop_words_ids = []
> stop_words_ids.extend(get_stop_words_ids(
>         model.generation_config.chat_format, tokenizer
>     ))
> outputs = model.generate(
>                 input_ids,
>                 stop_words_ids = stop_words_ids,
>                 return_dict_in_generate = False,
>                 attention_mask=attention_mask
>             )
> print(tokenizer.decode(outputs[0], skip_special_tokens=True))
> print(tokenizer.decode(outputs[1], skip_special_tokens=True))
> ```
> 
> 模型的回答是（第一句有padding）： ![image](https://user-images.githubusercontent.com/83623643/260481442-fb472dac-98bf-49d1-8039-e2e88e7aa21a.png)


用bath推理，往往第一个样本生成的还行，第二个就变的很差了，不知道为什么？

**Comment by miiiiiko** [comment]
我也是这样

**Comment by heihei2015** [comment]
Qwen的batch推理结果非常差是因为长度补齐导致的。即填补的token会影响generate的输出。
我自己想出了一个方案：不要用官方的pad_id来填补，直接用0填补就可以。但是填补的时候需要注意，不能在最左侧或者最右侧填补。因为模型时decoder only,在左侧填补会引入大量空无意义的字符，在最右侧填补会导致原本句子的结束符跑到中间去了，模型在推理的时候找不到结束符。所以最好的方式就是在原始句子的最后，结束符之前填补无意义的字符，是比较好的选择。通过该种方式，就能保证输出结果的准确性。

**Comment by miiiiiko** [comment]
> 

请问可以参考下推理的代码吗

**Comment by miiiiiko** [comment]
> Qwen的batch推理结果非常差是因为长度补齐导致的。即填补的token会影响generate的输出。 我自己想出了一个方案：不要用官方的pad_id来填补，直接用0填补就可以。但是填补的时候需要注意，不能在最左侧或者最右侧填补。因为模型时decoder only,在左侧填补会引入大量空无意义的字符，在最右侧填补会导致原本句子的结束符跑到中间去了，模型在推理的时候找不到结束符。所以最好的方式就是在原始句子的最后，结束符之前填补无意义的字符，是比较好的选择。通过该种方式，就能保证输出结果的准确性。

请问可以参考下推理的代码吗

**Comment by heihei2015** [comment]
> > Qwen的batch推理结果非常差是因为长度补齐导致的。即填补的token会影响generate的输出。 我自己想出了一个方案：不要用官方的pad_id来填补，直接用0填补就可以。但是填补的时候需要注意，不能在最左侧或者最右侧填补。因为模型时decoder only,在左侧填补会引入大量空无意义的字符，在最右侧填补会导致原本句子的结束符跑到中间去了，模型在推理的时候找不到结束符。所以最好的方式就是在原始句子的最后，结束符之前填补无意义的字符，是比较好的选择。通过该种方式，就能保证输出结果的准确性。
> 
> 请问可以参考下推理的代码吗

照着LLaMA-Efficient-Tuning 里面的stream_chat.py改的，可以自己试一试
```
  def batch_chat(
      self,
      query_list: List[str],
      history: Optional[List[Tuple[str, str]]] = None,
      prefix: Optional[str] = None,
      **input_kwargs
  ) -> Tuple[str, Tuple[int, int]]:

      input_ids_list = []
      input_ids_len =[]
      prompt_length_list = []
      for query in query_list:
          gen_kwargs, prompt_length = self.process_args(query, history, prefix, **input_kwargs)
          _input_ids = gen_kwargs.get('input_ids')
          input_ids_list.append(_input_ids)
          input_ids_len.append(_input_ids.size()[1])
          prompt_length_list.append(prompt_length)
      len_max = max(input_ids_len)
      tensor_size = (len(input_ids_list), len_max)

      token_type_ids=torch.zeros(
          size=tensor_size,
          dtype=torch.int64,
          device=self.model.device
      )
      attention_mask=torch.ones(
          size=tensor_size,
          dtype=torch.int64,
          device=self.model.device
      )

      # 用0补齐batch
      for i in range(tensor_size[0]):
          _diff = len_max-input_ids_len[i]
          if _diff ==0:
              pass
          else:
              input_ids_list[i] = torch.concat([
                  input_ids_list[i][:, :-1],
                  torch.zeros(size=(1, _diff), dtype=torch.int64, device=self.model.device),
                  input_ids_list[i][:, -1:]],
              dim=-1
              )
              attention_mask[i, input_ids_len[i]:-1] = 0

      input_ids = torch.concat(input_ids_list, dim=0)

      gen_kwargs.update({'input_ids':input_ids,'attention_mask':attention_mask,'token_type_ids':token_type_ids})

      generation_output = self.model.generate(**gen_kwargs).tolist()

      outputs = []
      for output, prompt_length in zip(generation_output, prompt_length_list):
          output = output[prompt_length:]
          response = self.tokenizer.decode(output, skip_special_tokens=True)
          response = re.sub("\!{3,}|<\|endoftext\|>", "", response)
          print(response)
          print('------------------------------')
          response_length = len(output)
          outputs.append(response)
      return outputs
```

**Comment by miiiiiko** [comment]
> 



> > > Qwen的batch推理结果非常差是因为长度补齐导致的。即填补的token会影响generate的输出。 我自己想出了一个方案：不要用官方的pad_id来填补，直接用0填补就可以。但是填补的时候需要注意，不能在最左侧或者最右侧填补。因为模型时decoder only,在左侧填补会引入大量空无意义的字符，在最右侧填补会导致原本句子的结束符跑到中间去了，模型在推理的时候找不到结束符。所以最好的方式就是在原始句子的最后，结束符之前填补无意义的字符，是比较好的选择。通过该种方式，就能保证输出结果的准确性。
> > 
> > 
> > 请问可以参考下推理的代码吗
> 
> 照着LLaMA-Efficient-Tuning 里面的stream_chat.py改的，可以自己试一试
> 
> ```
>   def batch_chat(
>       self,
>       query_list: List[str],
>       history: Optional[List[Tuple[str, str]]] = None,
>       prefix: Optional[str] = None,
>       **input_kwargs
>   ) -> Tuple[str, Tuple[int, int]]:
> 
>       input_ids_list = []
>       input_ids_len =[]
>       prompt_length_list = []
>       for query in query_list:
>           gen_kwargs, prompt_length = self.process_args(query, history, prefix, **input_kwargs)
>           _input_ids = gen_kwargs.get('input_ids')
>           input_ids_list.append(_input_ids)
>           input_ids_len.append(_input_ids.size()[1])
>           prompt_length_list.append(prompt_length)
>       len_max = max(input_ids_len)
>       tensor_size = (len(input_ids_list), len_max)
> 
>       token_type_ids=torch.zeros(
>           size=tensor_size,
>           dtype=torch.int64,
>           device=self.model.device
>       )
>       attention_mask=torch.ones(
>           size=tensor_size,
>           dtype=torch.int64,
>           device=self.model.device
>       )
> 
>       # 用0补齐batch
>       for i in range(tensor_size[0]):
>           _diff = len_max-input_ids_len[i]
>           if _diff ==0:
>               pass
>           else:
>               input_ids_list[i] = torch.concat([
>                   input_ids_list[i][:, :-1],
>                   torch.zeros(size=(1, _diff), dtype=torch.int64, device=self.model.device),
>                   input_ids_list[i][:, -1:]],
>               dim=-1
>               )
>               attention_mask[i, input_ids_len[i]:-1] = 0
> 
>       input_ids = torch.concat(input_ids_list, dim=0)
> 
>       gen_kwargs.update({'input_ids':input_ids,'attention_mask':attention_mask,'token_type_ids':token_type_ids})
> 
>       generation_output = self.model.generate(**gen_kwargs).tolist()
> 
>       outputs = []
>       for output, prompt_length in zip(generation_output, prompt_length_list):
>           output = output[prompt_length:]
>           response = self.tokenizer.decode(output, skip_special_tokens=True)
>           response = re.sub("\!{3,}|<\|endoftext\|>", "", response)
>           print(response)
>           print('------------------------------')
>           response_length = len(output)
>           outputs.append(response)
>       return outputs
> ```
好的，谢谢！

**Comment by logicwong** [comment]
@wellcasa @bh4ffu @McCarrtney @heihei2015 @miiiiiko 最新代码支持上batch infer了，大家可以试用一下，有问题就在这里继续讨论就行。我自己在本地测试的代码如下，供参考：

```
import torch
from tokenization_qwen import QWenTokenizer
from modeling_qwen import QWenLMHeadModel
from transformers import GenerationConfig
from qwen_generation_utils import make_context


tokenizer = QWenTokenizer.from_pretrained('./', pad_token='<|extra_0|>', eos_token='<|endoftext|>', padding_side='left')
model = QWenLMHeadModel.from_pretrained('./', device_map="auto").eval()
model.generation_config = GenerationConfig.from_pretrained('./')

all_raw_text = ["我想听你说爱我。", "今天我想吃点啥，甜甜的，推荐下", "我马上迟到了，怎么做才能不迟到"]
batch_question = []
for q in all_raw_text:
    raw_text, _ = make_context(
        tokenizer,
        q,
        system="You are a helpful assistant.",
        max_window_size=model.generation_config.max_window_size,
        chat_format=model.generation_config.chat_format,
    )
    batch_question.append(raw_text)

batch_input_ids = tokenizer(batch_question, padding='longest')
print(batch_input_ids)

batch_input_ids1 = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
batch_out_ids = model.generate(
    input_ids=batch_input_ids1
    ,return_dict_in_generate=False
)
batch_response = [tokenizer.decode(o, skip_special_tokens=True) for o in batch_out_ids]
print(batch_response)

response, _ = model.chat(tokenizer, "我想听你说爱我。", history=None)
print(response)

response, _ = model.chat(tokenizer, "今天我想吃点啥，甜甜的，推荐下", history=None)
print(response)

response, _ = model.chat(tokenizer, "我马上迟到了，怎么做才能不迟到", history=None)
print(response)

```

**Comment by lkluo** [comment]
> @wellcasa @bh4ffu @McCarrtney @heihei2015 @miiiiiko 最新代码支持上batch infer了，大家可以试用一下，有问题就在这里继续讨论就行。我自己在本地测试的代码如下，供参考：
> 
> ```
> import torch
> from tokenization_qwen import QWenTokenizer
> from modeling_qwen import QWenLMHeadModel
> from transformers import GenerationConfig
> from qwen_generation_utils import make_context
> 
> 
> tokenizer = QWenTokenizer.from_pretrained('./', pad_token='<|extra_0|>', eos_token='<|endoftext|>', padding_side='left')
> model = QWenLMHeadModel.from_pretrained('./', device_map="auto").eval()
> model.generation_config = GenerationConfig.from_pretrained('./')
> 
> all_raw_text = ["我想听你说爱我。", "今天我想吃点啥，甜甜的，推荐下", "我马上迟到了，怎么做才能不迟到"]
> batch_question = []
> for q in all_raw_text:
>     raw_text, _ = make_context(
>         tokenizer,
>         q,
>         system="You are a helpful assistant.",
>         max_window_size=model.generation_config.max_window_size,
>         chat_format=model.generation_config.chat_format,
>     )
>     batch_question.append(raw_text)
> 
> batch_input_ids = tokenizer(batch_question, padding='longest')
> print(batch_input_ids)
> 
> batch_input_ids1 = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
> batch_out_ids = model.generate(
>     input_ids=batch_input_ids1
>     ,return_dict_in_generate=False
> )
> batch_response = [tokenizer.decode(o, skip_special_tokens=True) for o in batch_out_ids]
> print(batch_response)
> 
> response, _ = model.chat(tokenizer, "我想听你说爱我。", history=None)
> print(response)
> 
> response, _ = model.chat(tokenizer, "今天我想吃点啥，甜甜的，推荐下", history=None)
> print(response)
> 
> response, _ = model.chat(tokenizer, "我马上迟到了，怎么做才能不迟到", history=None)
> print(response)
> ```

速度跟single batch相比并没有明显提升。大家有相同体验吗？

**Comment by logicwong** [comment]
@lkluo 请问你有开启flash-attention吗？

- 没开flash-attention的情况下，我们内部测试速度确实是差不多的。因为batch_infer需要对文本进行左pad，短文本的计算量相较于分开generate反而增加了
- 如果开启flash-attention，那batch_infer会有40%左右的加速。因为我们在进行flash_attention计算时会把多余的padding给踢掉，效率因此也提高了一些

**Comment by ChinesePainting** [comment]
请问这个代码支持最新的Qwen14B int4量化版吗

**Comment by lkluo** [comment]
> @lkluo 请问你有开启flash-attention吗？
> 
> * 没开flash-attention的情况下，我们内部测试速度确实是差不多的。因为batch_infer需要对文本进行左pad，短文本的计算量相较于分开generate反而增加了
> * 如果开启flash-attention，那batch_infer会有40%左右的加速。因为我们在进行flash_attention计算时会把多余的padding给踢掉，效率因此也提高了一些

多谢回复。没用flahattn，回头再试一下。

**Comment by logicwong** [comment]
@ChinesePainting 支持

**Comment by ChinesePainting** [comment]
@logicwong 

- 我在batch=4的时候（各个prompt长度相近），用该代码测试正常，且速度很快。
- 但我开batch=8（prompt长度差别很大）的时候，虽然response也能返回，但是只有比较长的prompt的返回值正常，短的prompt返回的是类似

`“assistant\n0\n7\n1\n\n7\n，\n3\n的 to in\n:\n with\n的\n5的，\”`
的乱码。

代码我几乎没有改，用的是上面的示例代码。

**Comment by logicwong** [comment]
@ChinesePainting 方便提供一下你测试用的prompt吗？最好是把完整代码贴上来，我做下测试

**Comment by menghonghan** [comment]
> 感谢支持Qwen-7B！
> 
> 我们发现您在使用`.generate(...)`方法调用Qwen-7B-Chat模型。
> 
> 1. 请注意Qwen-7B-Chat对输入数据的格式有特殊规定（ChatML）格式，建议您使用`.chat(...)`方法调用（推理时单条数据的格式类似`"<|im_start|>user\n今天我想吃点啥，甜甜的，推荐下<|im_end|>\n<|im_start|>assistant\n"`，chat相关代码中包含相关逻辑）。由于不同样本间的对话历史路径可能非常不同，该方法尚未支持批量推理。
> 2. 使用batch推理，但样本长度不同时，padding建议设置为left padding。
>    ```python
>    tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B-Chat', trust_remote_code=True, padding_side="left", pad_token="<|endoftext|>") # pad_token用其它的特殊token也可以
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    但需要提醒您，我们目前不建议使用generate方法进行Qwen-7B-Chat模型推理。

请问为啥不建议用generate评Qwen-7B-Chat呢，想知道原因是什么。
我用generate评Qwen-7B-Chat，用batch预测会出现答案左边全是叹号的情况
![image](https://github.com/QwenLM/Qwen/assets/61367724/c2bb7c8b-c8f1-4822-bc25-5c8e52c2ee8c) batch预测的代码评其他huggingface开源模型（llama，baichuan……）均不会出现这种问题，请问是什么原因会导致左侧很多叹号呢，谢谢

**Comment by banxia1994** [comment]
> @wellcasa @bh4ffu @McCarrtney @heihei2015 @miiiiiko 最新代码支持上batch infer了，大家可以试用一下，有问题就在这里继续讨论就行。我自己在本地测试的代码如下，供参考：
> 
> ```
> import torch
> from tokenization_qwen import QWenTokenizer
> from modeling_qwen import QWenLMHeadModel
> from transformers import GenerationConfig
> from qwen_generation_utils import make_context
> 
> 
> tokenizer = QWenTokenizer.from_pretrained('./', pad_token='<|extra_0|>', eos_token='<|endoftext|>', padding_side='left')
> model = QWenLMHeadModel.from_pretrained('./', device_map="auto").eval()
> model.generation_config = GenerationConfig.from_pretrained('./')
> 
> all_raw_text = ["我想听你说爱我。", "今天我想吃点啥，甜甜的，推荐下", "我马上迟到了，怎么做才能不迟到"]
> batch_question = []
> for q in all_raw_text:
>     raw_text, _ = make_context(
>         tokenizer,
>         q,
>         system="You are a helpful assistant.",
>         max_window_size=model.generation_config.max_window_size,
>         chat_format=model.generation_config.chat_format,
>     )
>     batch_question.append(raw_text)
> 
> batch_input_ids = tokenizer(batch_question, padding='longest')
> print(batch_input_ids)
> 
> batch_input_ids1 = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
> batch_out_ids = model.generate(
>     input_ids=batch_input_ids1
>     ,return_dict_in_generate=False
> )
> batch_response = [tokenizer.decode(o, skip_special_tokens=True) for o in batch_out_ids]
> print(batch_response)
> 
> response, _ = model.chat(tokenizer, "我想听你说爱我。", history=None)
> print(response)
> 
> response, _ = model.chat(tokenizer, "今天我想吃点啥，甜甜的，推荐下", history=None)
> print(response)
> 
> response, _ = model.chat(tokenizer, "我马上迟到了，怎么做才能不迟到", history=None)
> print(response)
> ```

请教一下这种形式单case和batch推理结果是一致的吗？确保seed和其他参数等因素不影响的情况下

**Comment by KevinFan0** [comment]
> @lkluo 请问你有开启flash-attention吗？
> 
> * 没开flash-attention的情况下，我们内部测试速度确实是差不多的。因为batch_infer需要对文本进行左pad，短文本的计算量相较于分开generate反而增加了
> * 如果开启flash-attention，那batch_infer会有40%左右的加速。因为我们在进行flash_attention计算时会把多余的padding给踢掉，效率因此也提高了一些

请教下这个batch infer的代码如何启用flash-attention呢

**Comment by logicwong** [comment]
@ChinesePainting @menghonghan @banxia1994 @Ke

**Comment by menghonghan** [comment]
@ogicwong 谢谢 但是batchsize不同的时候 分数波动很大的 包括生成任务和算logits的选择题

**Comment by logicwong** [comment]
@menghonghan 有点奇怪，问一下：

1. 确认是参照https://github.com/QwenLM/Qwen#batch-inference编写的脚本吗？
2. 你测评的场景是短序列还是长序列（样本长度是小于2048还是大于2048）
3. 有开关flashattenion进行测评吗？两种情况下分数波动都很大吗？

你的回复可以帮助我们更好的定位问题

**Comment by kaishxu** [comment]
> @ogicwong 谢谢 但是batchsize不同的时候 分数波动很大的 包括生成任务和算logits的选择题

同样遇到了这个问题，batchsize不一样，结果差异很大。

**Comment by nameleiyu** [comment]
> @wellcasa @bh4ffu @McCarrtney @heihei2015 @miiiiiko 最新代码支持上batch infer了，大家可以试用一下，有问题就在这里继续讨论就行。我自己在本地测试的代码如下，供参考：
> 
> ```python
> import torch
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from transformers import GenerationConfig
> from qwen_generation_utils import make_context, decode_tokens, get_stop_words_ids
> 
> tokenizer = AutoTokenizer.from_pretrained(
>     './',
>     pad_token='<|extra_0|>',
>     eos_token='<|endoftext|>',
>     padding_side='left',
>     trust_remote_code=True
> )
> model = AutoModelForCausalLM.from_pretrained(
>     './',
>     pad_token_id=tokenizer.pad_token_id,
>     device_map="auto",
>     trust_remote_code=True
> ).eval()
> model.generation_config = GenerationConfig.from_pretrained('./', pad_token_id=tokenizer.pad_token_id)
> 
> all_raw_text = ["我想听你说爱我。", "今天我想吃点啥，甜甜的，推荐下", "我马上迟到了，怎么做才能不迟到"]
> batch_raw_text = []
> for q in all_raw_text:
>     raw_text, _ = make_context(
>         tokenizer,
>         q,
>         system="You are a helpful assistant.",
>         max_window_size=model.generation_config.max_window_size,
>         chat_format=model.generation_config.chat_format,
>     )
>     batch_raw_text.append(raw_text)
> 
> batch_input_ids = tokenizer(batch_raw_text, padding='longest')
> batch_input_ids = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
> batch_out_ids = model.generate(
>     batch_input_ids,
>     return_dict_in_generate=False,
>     generation_config=model.generation_config
> )
> padding_lens = [batch_input_ids[i].eq(tokenizer.pad_token_id).sum().item() for i in range(batch_input_ids.size(0))]
> 
> batch_response = [
>     decode_tokens(
>         batch_out_ids[i][padding_lens[i]:],
>         tokenizer,
>         raw_text_len=len(batch_raw_text[i]),
>         context_length=(batch_input_ids[i].size(0)-padding_lens[i]),
>         chat_format="chatml",
>         verbose=False,
>         errors='replace'
>     ) for i in range(len(all_raw_text))
> ]
> print(batch_response)
> 
> response, _ = model.chat(tokenizer, "我想听你说爱我。", history=None)
> print(response)
> 
> response, _ = model.chat(tokenizer, "今天我想吃点啥，甜甜的，推荐下", history=None)
> print(response)
> 
> response, _ = model.chat(tokenizer, "我马上迟到了，怎么做才能不迟到", history=None)
> print(response)
> ```

@logicwong 使用这个推理代码，batch推理时会出现某几个回答与prompt毫不相关，数据量大约200条

**Comment by FlexLaughing** [comment]
> 感谢支持Qwen-7B！
> 
> 我们发现您在使用`.generate(...)`方法调用Qwen-7B-Chat模型。
> 
> 1. 请注意Qwen-7B-Chat对输入数据的格式有特殊规定（ChatML）格式，建议您使用`.chat(...)`方法调用（推理时单条数据的格式类似`"<|im_start|>user\n今天我想吃点啥，甜甜的，推荐下<|im_end|>\n<|im_start|>assistant\n"`，chat相关代码中包含相关逻辑）。由于不同样本间的对话历史路径可能非常不同，该方法尚未支持批量推理。
> 2. 使用batch推理，但样本长度不同时，padding建议设置为left padding。
>    ```python
>    tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B-Chat', trust_remote_code=True, padding_side="left", pad_token="<|endoftext|>") # pad_token用其它的特殊token也可以
>    ```
>    
>      
>    但需要提醒您，我们目前不建议使用generate方法进行Qwen-7B-Chat模型推理。

您好，当前我是用如下方法，在CPU推理模型看起来正常：
        fix_left = (self.tokenizer.encode('<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n'))
        question_id = self.tokenizer.encode(got_input_question)
        fix_right = (self.tokenizer.encode('<|im_end|>\n<|im_start|>assistant\n'))
但是我希望把原始的问题输入去做推理，目前Qwen-7B-chat的模型支持吗？具体需要怎么操作？

**Comment by Boyan-Wang** [comment]
请问在Qwen2.5-72B上也可以做到batch inference吗？
