### ISSUE TITLE
[BUG] Exception in ASGI application

### ISSUE THREAD

**Issue by shen5455** [QwenLM/Qwen#160]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/15943741/58f58bd0-6502-4c3c-af1b-d112aa798e12)
。

### 期望行为 | Expected Behavior

。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
。
```

### 备注 | Anything else?

。

**Comment by JustinLin610** [comment]
提供复现方法

**Comment by shen5455** [comment]
这句话可以必选错误：      写一首词，有花有月有风有雨
![image](https://github.com/QwenLM/Qwen-7B/assets/15943741/be1f129a-816f-4001-b190-6968e73a5bdb)

**Comment by JustinLin610** [comment]
尝试一下最新的模型或者demo看看还没有这类问题？

**Comment by jklj077** [comment]
Closed due to model/code update and no responses from the author. Please reopen this if the problem still exists.
