### ISSUE TITLE
问问题回答老是重复的，应该怎么调整

### ISSUE THREAD

**Issue by abc20220327** [QwenLM/Qwen#165]
用户：
讲个笑话

ChatBot：
A：你会学鸽子说话吗？

B：在路上了。

用户：
给我另一个与之前完全不同的笑话。

ChatBot：
A：你会学鸽子说话吗？

B：在路上了。

以上是我测试的情况，temperature =0.5，我调整了各种值还是一直重复

**Comment by JustinLin610** [comment]
temperature太低的问题吧，使用默认配置就可以生成不同的结果，增大top_p可以进一步提升多样性

**Comment by abc20220327** [comment]
temperature =0.5改到0.8之类的，还是一样的问题

**Comment by sxueck** [comment]
试着调整一下 repetition_penalty 重复惩罚这个参数，我将其配置为 1.3 情况能有所缓解，建议 1.2-1.5 以内

**Comment by xiefan233** [comment]
> 你好，请问repetition_penalty这个参数在哪里修改？

**Comment by xiefan233** [comment]
> 试着调整一下 repetition_penalty 重复惩罚这个参数，我将其配置为 1.3 情况能有所缓解，建议 1.2-1.5 以内
> 
> Examples:
> 
> 1. 给我讲一个笑话
>    答：一位家长找到老师说：“孩子最近成绩下降了。” 老师答道：“因为你们家的网速变快了
> 2. 给我另一个与之前完全不同的笑话
>    答：
>    好的，这是另一个笑话：
>    一个男人走进酒吧里对酒保说：“来一份双份马丁尼！”
>    酒保问他：“你为什么要两份呢？”
>    那个男人回答道：“因为我今晚有两个约会！”
> 3. 再给我讲一个，刚刚那个不好笑
>    答：
>    对不起，如果我之前的笑话没有让您开心。
>    这里是一个新的笑话：
>    一个人在一家餐厅点了一份牛排，并问服务员需要等多久才能上菜。
>    服务生告诉他：“您的牛排已经煮熟并正在烤箱中保温，我们会把它放在盘子里并立即端给您。”
> 
> 过了一会儿后，他又回到同一个地方问同样的问题。 然后这次的服务员回答他：“很抱歉先生，您刚才点的是煮饺。”

你好，请问repetition_penalty这个参数在哪里修改？

**Comment by sxueck** [comment]
> 你好，请问repetition_penalty这个参数在哪里修改？

```
model.generation_config = (
    GenerationConfig.from_pretrained(
        model_name, trust_remote_code=True, top_k=30000, repetition_penalty=1.3))
```

**Comment by sxueck** [comment]
而且你这个可能是 `history=None` 导致的，模型预训练的时候会倾向使用同一个回答（不做微调的情况下），可以加入上下文试试？
