### ISSUE TITLE
[BUG] <title>流式输出如何固定输出结果

### ISSUE THREAD

**Issue by Amy234543** [QwenLM/Qwen#169]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

chat_stream加了do_sample= False 会报错，

### 期望行为 | Expected Behavior

正常输出

### 复现方法 | Steps To Reproduce

model.generation_config.do_sample = False
def _clear_screen():
    if platform.system() == "Windows":
        os.system("cls")
    else:
        os.system("clear")
for response in model.chat_stream(tokenizer, prompt, history=None):
    # _clear_screen()
    print(f"\nUser: {prompt}")
    print(f"\nQwen-7B: {response}")

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by fyabc** [comment]
@Amy234543 您好，目前流式输出还不支持`do_sample=False`，您可以通过在调用`model.chat_stream()`之前手动设置random seed的方式固定输出结果：
```python
from transformers.trainer_utils import set_seed
set_seed(1234)
for response in model.chat_stream(...):
    ...
```

**Comment by JianxinMa** [comment]
> @Amy234543 您好，目前流式输出还不支持`do_sample=False`，您可以通过在调用`model.chat_stream()`之前手动设置random seed的方式固定输出结果：
> 
> ```python
> from transformers.trainer_utils import set_seed
> set_seed(1234)
> for response in model.chat_stream(...):
>     ...
> ```

为什么不支持呢？流式可以通过 `model.generation_config.do_sample = False` 关闭 sampling、打开 greedy decoding 吗？

**Comment by fyabc** [comment]
> > @Amy234543 您好，目前流式输出还不支持`do_sample=False`，您可以通过在调用`model.chat_stream()`之前手动设置random seed的方式固定输出结果：
> > ```python
> > from transformers.trainer_utils import set_seed
> > set_seed(1234)
> > for response in model.chat_stream(...):
> >     ...
> > ```
> 
> 为什么不支持呢？流式可以通过 `model.generation_config.do_sample = False` 关闭 sampling、打开 greedy decoding 吗？

@JianxinMa  目前内部使用的transformers_stream_generator不支持`do_sample=False`，可参考 LowinLi/transformers-stream-generator#1 。

**Comment by jxst539246** [comment]
可以通过指定一个很小的temperature来模拟greedy。

**Comment by JianxinMa** [comment]
top_k=1是不是也能实现greedy。chat_stream支持top_k的话，遇到do_sample=False就改成top_k=1?

**Comment by zhufz** [comment]
看起来qwen用的是sample模式，topk top p在beam_sample下才会生效，可能需要调整采样模式？

**Comment by fyabc** [comment]
> > > > @Amy234543 您好，目前流式输出还不支持`do_sample=False`，您可以通过在调用`model.chat_stream()`之前手动设置random seed的方式固定输出结果：
> > > > ```python
> > > > from transformers.trainer_utils import set_seed
> > > > set_seed(1234)
> > > > for response in model.chat_stream(...):
> > > >     ...
> > > > ```
> > > 
> > > 
> > > 为什么不支持呢？流式可以通过 `model.generation_config.do_sample = False` 关闭 sampling、打开 greedy decoding 吗？
> > 
> > 
> > @JianxinMa 目前内部使用的transformers_stream_generator不支持`do_sample=False`，可参考 [LowinLi/transformers-stream-generator#1](https://github.com/LowinLi/transformers-stream-generator/issues/1) 。
> 
> `set_seed(1234)` 不能保证输出结果固定吧？

目前在每次chat/chat_stream调用前设置`set_seed(1234)`是可以保证结果固定的，您可以提供下不固定的复现方法吗？

**Comment by Wyfnnnnb** [comment]
请教，为什么我chat_stream调用会报错
Traceback (most recent call last):
...
    for response in self.model.chat_stream(self.tokenizer, query=query, history=history):
  File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-div/modeling_qwen.py", line 1059, in stream_generator
    outputs.append(token.item())
RuntimeError: a Tensor with 29 elements cannot be converted to Scalar

**Comment by fyabc** [comment]
> 请教，为什么我chat_stream调用会报错 Traceback (most recent call last): ... for response in self.model.chat_stream(self.tokenizer, query=query, history=history): File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-div/modeling_qwen.py", line 1059, in stream_generator outputs.append(token.item()) RuntimeError: a Tensor with 29 elements cannot be converted to Scalar

您好，可以提供详细的复现方式吗？
另外您使用的模型和modeling_qwen.py代码似乎不是最新的版本，可以从HF下载最新的代码之后重新尝试一下

**Comment by Wyfnnnnb** [comment]
> 您好，可以提供详细的复现方式吗？ 另外您使用的模型和modeling_qwen.py代码似乎不是最新的版本，可以从HF下载最新的代码之后重新尝试一下
generation_config = {
            "chat_format": "chatml",  # chatml,raw
            "eos_token_id": 151643,
            "pad_token_id": 151643,
            "max_window_size": 6144,
            "max_new_tokens": 512,
            "do_sample": False,
            "top_k": 0,
            "top_p": 0.5,
            "transformers_version": "4.31.0",
            "stop_words_ids": [
                [151643]
            ]
        }
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True).eval()

# Specify hyperparameters for generation
# model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)
model.generation_config = GenerationConfig(**generation_config)

current_length = 0
for response in model.chat_stream(tokenizer, "给这个故事起一个标题，并写一个一百字的故事", history=None):
    print(response[current_length:], end="", flush=True)
    current_length = len(response)

已经全部更新了最新的文件，在调用qwen-7b-chat模型正常，调用qwen-7b-base时报错。Traceback (most recent call last):
  File "/mnt/aiteam/wangyifan/project/chatglm6B/style_transfer/test/qwen_text.py", line 35, in <module>
    for response in model.chat_stream(tokenizer, "给这个故事起一个标题，并写一个一百字的故事", history=None):
  File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py", line 1073, in stream_generator
    outputs.append(token.item())
RuntimeError: a Tensor with 543 elements cannot be converted to Scalar

**Comment by Wyfnnnnb** [comment]
> > 请教，为什么我chat_stream调用会报错 Traceback (most recent call last): ... for response in self.model.chat_stream(self.tokenizer, query=query, history=history): File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-div/modeling_qwen.py", line 1059, in stream_generator outputs.append(token.item()) RuntimeError: a Tensor with 29 elements cannot be converted to Scalar
> 
> 您好，可以提供详细的复现方式吗？ 另外您使用的模型和modeling_qwen.py代码似乎不是最新的版本，可以从HF下载最新的代码之后重新尝试一下

generation_config = {
"chat_format": "chatml", # chatml,raw
"eos_token_id": 151643,
"pad_token_id": 151643,
"max_window_size": 6144,
"max_new_tokens": 512,
"do_sample": False,
"top_k": 0,
"top_p": 0.5,
"transformers_version": "4.31.0",
"stop_words_ids": [
[151643]
]
}
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig(**generation_config)

current_length = 0
for response in model.chat_stream(tokenizer, "给这个故事起一个标题，并写一个一百字的故事", history=None):
print(response[current_length:], end="", flush=True)
current_length = len(response)

已经全部更新了最新的文件，在调用qwen-7b-chat模型正常，调用qwen-7b-base时报错。Traceback (most recent call last):
File "/mnt/aiteam/wangyifan/project/chatglm6B/style_transfer/test/qwen_text.py", line 35, in
for response in model.chat_stream(tokenizer, "给这个故事起一个标题，并写一个一百字的故事", history=None):
File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py", line 1073, in stream_generator
outputs.append(token.item())
RuntimeError: a Tensor with 543 elements cannot be converted to Scalar

**Comment by fyabc** [comment]
> > > 请教，为什么我chat_stream调用会报错 Traceback (most recent call last): ... for response in self.model.chat_stream(self.tokenizer, query=query, history=history): File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-div/modeling_qwen.py", line 1059, in stream_generator outputs.append(token.item()) RuntimeError: a Tensor with 29 elements cannot be converted to Scalar
> > 
> > 
> > 您好，可以提供详细的复现方式吗？ 另外您使用的模型和modeling_qwen.py代码似乎不是最新的版本，可以从HF下载最新的代码之后重新尝试一下
> 
> generation_config = { "chat_format": "chatml", # chatml,raw "eos_token_id": 151643, "pad_token_id": 151643, "max_window_size": 6144, "max_new_tokens": 512, "do_sample": False, "top_k": 0, "top_p": 0.5, "transformers_version": "4.31.0", "stop_words_ids": [ [151643] ] } tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True) model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True).eval() model.generation_config = GenerationConfig(**generation_config)
> 
> current_length = 0 for response in model.chat_stream(tokenizer, "给这个故事起一个标题，并写一个一百字的故事", history=None): print(response[current_length:], end="", flush=True) current_length = len(response)
> 
> 已经全部更新了最新的文件，在调用qwen-7b-chat模型正常，调用qwen-7b-base时报错。Traceback (most recent call last): File "/mnt/aiteam/wangyifan/project/chatglm6B/style_transfer/test/qwen_text.py", line 35, in for response in model.chat_stream(tokenizer, "给这个故事起一个标题，并写一个一百字的故事", history=None): File "/mnt/aiteam/.cache/huggingface/modules/transformers_modules/Qwen-7B/modeling_qwen.py", line 1073, in stream_generator outputs.append(token.item()) RuntimeError: a Tensor with 543 elements cannot be converted to Scalar

您好，
首先，将`generation_config`中的`do_sample`改为`True`，即可正常调用`chat_stream`；
其次，qwen-7b-base模型是未经过微调的预训练模型，不建议调用`chat`接口，建议使用`generate`接口，以续写方式生成，具体可以参考README中的相关内容。
