### ISSUE TITLE
清除历史后，系统提示不起作用

### ISSUE THREAD

**Issue by Lufffya** [QwenLM/Qwen#171]
![image](https://github.com/QwenLM/Qwen-7B/assets/49063302/f431e46c-6c7d-4f19-b604-3fcb517614b1)

`for response in model.chat_stream(tokenizer, _query, history=task_history, system=SYSTEAM):`

当我定义了系统提示，并传递到模型时，是有效的，如下图（中括号是输出的 `task_history`）：
![image](https://github.com/QwenLM/Qwen-7B/assets/49063302/fa2dc904-b802-441b-b378-53f6c0913b05)

但是当我在web上点击了` 清除历史 ` 后，系统提示就不再生效，如下图：
![image](https://github.com/QwenLM/Qwen-7B/assets/49063302/91c09561-7aa3-4680-9504-79ab1e98b3ee)

有时候点击一次` 清除历史 ` 就失效，有时需要点击多次，然后就失效，但是系统提示又不包括在历史对话中，为什么会失效呢？

**Comment by fyabc** [comment]
@Lufffya 您好，对于“你是谁”这个问题，有可能是overfit到了我司数据，导致效果不佳。可以参考 [issue-91](https://github.com/QwenLM/Qwen-7B/issues/91#issuecomment-1673061773)，换一些其他的问题尝试一下。

**Comment by JianxinMa** [comment]
> @Lufffya 您好，对于“你是谁”这个问题，有可能是overfit到了我司数据，导致效果不佳。可以参考 [issue-91](https://github.com/QwenLM/Qwen-7B/issues/91#issuecomment-1673061773)，换一些其他的问题尝试一下。

我感觉不是。我测试下来，用 user 传入角色扮演要求，回答“你是谁”其实还好。这个 case 有两种可能：（1）代码有问题，system没生效；（2）qwen-7b 对 system 区的响应不理想，因为开源的这一版并没有针对性的训练过 system 区。

建议用户不要改 system，有角色扮演需求就用普通的 user 区传入指令就好。

**Comment by liaoweiguo** [comment]
> > @Lufffya 您好，对于“你是谁”这个问题，有可能是overfit到了我司数据，导致效果不佳。可以参考 [issue-91](https://github.com/QwenLM/Qwen-7B/issues/91#issuecomment-1673061773)，换一些其他的问题尝试一下。
> 
> 我感觉不是。我测试下来，用 user 传入角色扮演要求，回答“你是谁”其实还好。这个 case 有两种可能：（1）代码有问题，system没生效；（2）qwen-7b 对 system 区的响应不理想，因为开源的这一版并没有针对性的训练过 system 区。
> 
> 建议用户不要改 system，有角色扮演需求就用普通的 user 区传入指令就好。

如何通过user区设置自我认知
