### ISSUE TITLE
[BUG] base模型以及generate和chat模型的chat，只要更改了相关参数如temperature，出现报错

### ISSUE THREAD

**Issue by sugarfreeLiuYuXuan** [QwenLM/Qwen#187]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

您好！感谢你们的杰出工作
我在设置model.generation_config.temperature=0.1或者更改了其他参数 时不管遇见什么prompt都会报错，只能支持do_sample =False，但是就强制greed search了。
我的报错信息如下：
Loading checkpoint shards: 100%|█████████████████████████| 8/8 [00:11<00:00,  1.40s/it]
Traceback (most recent call last):
  File "/data/juicefs_translation/11162367/LLAMA/temp.py", line 46, in <module>
    response, _ = model.chat(tokenizer, prompt, history=None) # chat
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-chat/modeling_qwen.py", line 982, in chat
    outputs = self.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-chat/modeling_qwen.py", line 1095, in generate
    return super().generate(
  File "/root/anaconda3/envs/dev/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/dev/lib/python3.10/site-packages/transformers/generation/utils.py", line 1665, in generate
    return self.beam_sample(
  File "/root/anaconda3/envs/dev/lib/python3.10/site-packages/transformers/generation/utils.py", line 3309, in beam_sample
    next_tokens = torch.multinomial(probs, num_samples=2 * num_beams)
**RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**

### 复现方法 | Steps To Reproduce

测试推理代码如下：
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
import torch
path = "/data/Qwen-7B-chat"
tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True, fp16=True, padding_side='left', pad_token='<|endoftext|>')
model = AutoModelForCausalLM.from_pretrained(path, device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained(path, trust_remote_code=True)


device = torch.device("cuda")
max_new_tokens = 256
top_p = 0.9
num_beams = 4
temperature = 0.1
no_repeat_ngram_size = 15
max_length = 512

model.generation_config.do_sample = True
model.generation_config.temperature = temperature
model.generation_config.max_new_tokens = max_new_tokens
model.generation_config.top_p = top_p
model.generation_config.num_beams = num_beams
model.generation_config.no_repeat_ngram_size = no_repeat_ngram_size

prompt = "你好，这是一个测试prompt。"
response, _ = model.chat(tokenizer, prompt, history=None) # chat
# response = generate_sample(model, tokenizer, prompt) # base
print(prompt)
print(response)
```

### 运行环境 | Environment

```Markdown
我的环境如下：
python 3.10
Name: torch Version: 2.0.1
Name: transformers Version: 4.31.0
```

### 备注 | Anything else?

我的所有模型源代码均来自于，2023年8月14日15点，在 https://huggingface.co/Qwen/Qwen-7B-Chat/tree/main (以chat模型为例)上下载的最新源码。
我发现在generation_config.json文件只有这些参数，是不是只能修改这些参数？

{
  "chat_format": "chatml",
  "eos_token_id": 151643,
  "pad_token_id": 151643,
  "max_window_size": 6144,
  "max_new_tokens": 512,
  "do_sample": true,
  "top_k": 0,
  "top_p": 0.9,
  "transformers_version": "4.31.0"
}

**Comment by fyabc** [comment]
@sugarfreeLiuYuXuan 您好，这个问题是由generation config中的num_beams参数导致的，我们目前正在排查中。
作为临时解决方案，将num_beams设置为1可以暂时避免该问题。

**Comment by sugarfreeLiuYuXuan** [comment]
> @sugarfreeLiuYuXuan 您好，这个问题是由generation config中的num_beams参数导致的，我们目前正在排查中。 作为临时解决方案，将num_beams设置为1可以暂时避免该问题。

好的，num_beams设置为1后，设置其他的参数，如temperature，依然会出现这样的错误
**测试代码：**
`
model.generation_config.do_sample = True
model.generation_config.temperature = temperature

model.generation_config.max_new_tokens = max_new_tokens
model.generation_config.top_p = top_p
model.generation_config.num_beams = 1
model.generation_config.no_repeat_ngram_size = no_repeat_ngram_size
`
**报错信息：**
  File "/root/anaconda3/envs/dev/lib/python3.10/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
**RuntimeError: probability tensor contains either `inf`, `nan` or element < 0**

**Comment by geekinglcq** [comment]
> > @sugarfreeLiuYuXuan 您好，这个问题是由generation config中的num_beams参数导致的，我们目前正在排查中。 作为临时解决方案，将num_beams设置为1可以暂时避免该问题。
> 
> 好的，谢谢您的建议，不过我将num_beams设置为1后，再设置其他的参数，如temperature，依然会出现这样的错误 测试代码： ` model.generation_config.do_sample = True model.generation_config.temperature = temperature
> 
> model.generation_config.max_new_tokens = max_new_tokens model.generation_config.top_p = top_p model.generation_config.num_beams = 1 model.generation_config.no_repeat_ngram_size = no_repeat_ngram_size ` 报错信息： File "/root/anaconda3/envs/dev/lib/python3.10/site-packages/transformers/generation/utils.py", line 2678, in sample next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
> 
> RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

你好，我们这里经过尝试无法复现这个问题，一般来说`num_beams = 1`设置之后，就能正常运行了，如下：
```
In [5]: 
   ...: 
   ...: device = torch.device("cuda")
   ...: max_new_tokens = 256
   ...: top_p = 0.9
   ...: num_beams = 1
   ...: temperature = 0.1
   ...: no_repeat_ngram_size = 15
   ...: max_length = 512
   ...: 
   ...: model.generation_config.do_sample = True
   ...: model.generation_config.temperature = temperature
   ...: model.generation_config.max_new_tokens = max_new_tokens
   ...: model.generation_config.top_p = top_p
   ...: model.generation_config.num_beams = num_beams
   ...: model.generation_config.no_repeat_ngram_size = no_repeat_ngram_size
   ...: 
   ...: prompt = "你好，这是一个测试prompt。"
   ...: response, _ = model.chat(tokenizer, prompt, history=None) # chat
   ...: # response = generate_sample(model, tokenizer, prompt) # base
   ...: print(prompt)
   ...: print(response)

你好，这是一个测试prompt。
你好！很高兴为你提供帮助。如果你有任何问题，请随时告诉我。
```
请问方便提供一下更多环境信息帮助我们复现这个问题吗，我们尝试复现的环境为：
```
python == 3.10.12
torch == 2.0.1
transformers == 4.31.0
cuda == 11.8
```

**Comment by younger-diao** [comment]
请问这个问题解决了吗，我在T4显卡上改变temperature 的值也会报这个错，在A6000显卡上正常运行，是不是因为T4这种显卡默认的fp16，A6000默认的bf16，fp16会造成计算溢出。

**Comment by sugarfreeLiuYuXuan** [comment]
> 请问这个问题解决了吗，我在T4显卡上改变temperature 的值也会报这个错，在A6000显卡上正常运行，是不是因为T4这种显卡默认的fp16，A6000默认的bf16，fp16会造成计算溢出。

> 

你好，可以贴出你在A6000上的chat或者generate逻辑那里的代码吗？你是怎么设置temperature 的？

**Comment by younger-diao** [comment]
> 

model.generation_config.temperature = 0.5
prompt = "你好"
response, _ = model.chat(tokenizer, prompt, history=None)

**Comment by younger-diao** [comment]
> > 请问这个问题解决了吗，我在T4显卡上改变temperature 的值也会报这个错，在A6000显卡上正常运行，是不是因为T4这种显卡默认的fp16，A6000默认的bf16，fp16会造成计算溢出。
> 
> > 
> 
> 你好，可以贴出你在A6000上的chat或者generate逻辑那里的代码吗？你是怎么设置temperature 的？

跟一楼的代码一样

**Comment by xiamaozi11** [comment]
不要用device_map=auto就可以了，AutoModelForCausalLM.from_pretrained(name_or_path, low_cpu_mem_usage=True,trust_remote_code=True).half().cuda()

**Comment by josh-zhang** [comment]
> > > 请问这个问题解决了吗，我在T4显卡上改变temperature 的值也会报这个错，在A6000显卡上正常运行，是不是因为T4这种显卡默认的fp16，A6000默认的bf16，fp16会造成计算溢出。
> > 
> > 
> > > 
> > 
> > 
> > 你好，可以贴出你在A6000上的chat或者generate逻辑那里的代码吗？你是怎么设置temperature 的？
> 
> 跟一楼的代码一样

这边也一样的错误。

环境v100s，cuda11.7，python3.10，torch 2.0.1，显卡不支持flash_attn，不支持bf16，加载用的fp16。

model.chat前，通过model.generation_config.*= x 方式赋值，在temp0.5 及以下，num_beams=1，do_sample=True时抛这个错误；temp0.5 以上或者do_sample=False 就没事。

**Comment by fyabc** [comment]
> > > > 请问这个问题解决了吗，我在T4显卡上改变temperature 的值也会报这个错，在A6000显卡上正常运行，是不是因为T4这种显卡默认的fp16，A6000默认的bf16，fp16会造成计算溢出。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > 你好，可以贴出你在A6000上的chat或者generate逻辑那里的代码吗？你是怎么设置temperature 的？
> > 
> > 
> > 跟一楼的代码一样
> 
> 这边也一样的错误。
> 
> 环境v100s，cuda11.7，python3.10，torch 2.0.1，显卡不支持flash_attn，不支持bf16。
> 
> 模型加载用的readme的代码。调用model.chat()前，通过model.generation_config.*= x 方式赋值，在temp0.5 及以下，num_beams=1，do_sample=True时抛这个错误；temp0.5 以上或者do_sample=False 就没事。

可以参考[这里](https://github.com/QwenLM/Qwen-7B/issues/276#issuecomment-1714890029)，温度值过低时softmax会出现精度溢出的情况。

**Comment by Aix-chengjie** [comment]
插眼记录。 我也是只要temperature < 0.5 就会报错。
`RuntimeError: probability tensor contains either inf, nan or element < 0`

**Comment by lrx1213** [comment]
20231027，遇到相同问题，只要temperature < 0.5 就会报错

**Comment by zdgithub** [comment]
我加载的`model.half()`精度，预测时设置参数为：
```
do_sample=True,
num_beams=1,
temperature=0.5,
top_p=0.95
```
还会报错`RuntimeError: probability tensor contains either inf, nan or element < 0`
然后把temperature=0.7，才没报错。
