### ISSUE TITLE
💡 [REQUEST] - 8卡A100 40G 用DeepSpeed-Chat无法全微调训练8192序列长度，OOM

### ISSUE THREAD

**Issue by LiuShixing** [QwenLM/Qwen#188]
### 摘要 | Summary

flash attention已开启，deepspeed使用offload_optimizer也不行。不知道是Qwen的问题还是DeepSpeed-Chat or 我的问题（>_<）

同样的机器配置+flash attenion，使用bigscience Megatron-DeepSpeed框架训练bloom是能训练12k序列长度的，加上offload_optimizer能训练20k长度。所以理论上配置是满足要求的
(https://github.com/bigscience-workshop/Megatron-DeepSpeed)

能否开放微调代码或者哪个代码能训练？

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by Jiangchenglin521** [comment]
请问您这边有尝试过pretrain版本的么，我这边用hugging face block进行训练，per_device_batch没法加大，超过1就会报embedding_ index越界问题。想请教下

**Comment by LiuShixing** [comment]
我用的是pretrain版本，没试过batch size > 1

**Comment by Jiangchenglin521** [comment]
> 我用的是pretrain版本，没试过batch size > 1

好的，感谢

**Comment by LiuShixing** [comment]
> > 我用的是pretrain版本，没试过batch size > 1
> 
> 好的，感谢

我测试batch size =2可以跑序列长度2048

**Comment by jklj077** [comment]
我们微调示例代码已经开源了，可以看下能否使用哈。现在支持Qwen-7B的全量微调、LoRA、QLoRA。使用说明、数据格式，可以参考README。欢迎试用反馈~
