### ISSUE TITLE
💡 [REQUEST] - <title>8张80G A-100微调，batch无法调大，否则index越界

### ISSUE THREAD

**Issue by Jiangchenglin521** [QwenLM/Qwen#189]
### 起始日期 | Start Date

08/14/2023

### 实现PR | Implementation PR

hugging face接口加载Qwen-7B训练，per_device_batch无法>1，超过1就报错index越界：../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [176,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

### 相关Issues | Reference Issues

1，batch > 1就不行，请问是否是flash-attn的问题，该如何解决
2，请问能否开源微调代码~ 谢谢

### 摘要 | Summary

- 提供微调代码，数据split细节等信息，方便大家使用，感谢

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
微调示例代码已经开源了，可以试下。支持全量微调、LoRA、QLoRA，使用说明，数据格式，可以参考README。欢迎试用反馈~
