### ISSUE TITLE
建议增加mac M1推理💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by doctor1984** [QwenLM/Qwen#192]
### 摘要 | Summary

建议增加mac m1推理功能

### 基本示例 | Basic Example

建议增加mac m1推理功能

### 缺陷 | Drawbacks

缺失mac m1推理功能，不利于大范围测试

**Comment by thkfly** [comment]
借楼, 如果想在4060ti 16gb上加载,如何设置呢

**Comment by zouy50** [comment]
I think there is a method to run this model on M1 Mac, but need an another platform PC to quant the model.

**Comment by JianxinMa** [comment]
see https://github.com/QwenLM/qwen.cpp

**Comment by jklj077** [comment]
closed in favor of https://github.com/QwenLM/Qwen/issues/17
