### ISSUE TITLE
💡 [REQUEST] - 是否会出更长的上下文模型比如32k

### ISSUE THREAD

**Issue by RipperTs** [QwenLM/Qwen#193]
### 摘要 | Summary

希望支持更长的上下文

### 基本示例 | Basic Example

-

### 缺陷 | Drawbacks

-

**Comment by jklj077** [comment]
现已发布，欢迎试用！

**Comment by weiminw** [comment]
> 现已发布，欢迎试用！

Qwen-14B 一直是8k, 什么时候出32K呢?
