### ISSUE TITLE
Bug and Error Report

### ISSUE THREAD

**Issue by DaveKJB** [QwenLM/Qwen#205]
Hello, 

I am reaching out regarding your source code files for your Qwen-7B eval(https://github.com/QwenLM/Qwen-7B/tree/main/eval) python codes. After running tests using Pyflakes and Pylint, there were a few errors present in the source codes and I felt that it could be something you guys could fix or look into.

evaluate_chat_gsm8k.py:1:1: 'random' imported but unused
evaluate_chat_gsm8k.py:3:1: 'os' imported but unused
evaluate_chat_gsm8k.py:5:1: 'sys' imported but unused
evaluate_chat_gsm8k.py:6:1: 'torch' imported but unused
evaluate_chat_gsm8k.py:8:1: 'jsonlines' imported but unused

evaluate_chat_humaneval.py:1:1: 'random' imported but unused
evaluate_chat_humaneval.py:3:1: 'os' imported but unused
evaluate_chat_humaneval.py:4:1: 'sys' imported but unused
evaluate_chat_humaneval.py:5:1: 'torch' imported but unused
evaluate_chat_humaneval.py:8:1: redefinition of unused 'jsonlines' from line 6
evaluate_chat_humaneval.py:35:41: f-string is missing placeholders

[pylint_report.txt](https://github.com/QwenLM/Qwen-7B/files/12363910/pylint_report.txt)

There were a few more present in the remaining source code files, but for sake of not creating too long a message, I have shown a few errors that I found using Pyflakes. I also added a link to a text file in which the errors/bugs that were present in all source files were reported using Pylint. Hope this helps.

Regards,
Dave

**Comment by jklj077** [comment]
This have been fixed. Please try pull the latest code. If there the problems still exist, feel free to re-open this issue. Thanks.
