### ISSUE TITLE
Could you please provide scripts for us to reproduce the results of long-context understanding for Qwen-7B and Qwen-7B-Chat?

### ISSUE THREAD

**Issue by chendulearn** [QwenLM/Qwen#206]

**Comment by logicwong** [comment]
You can process the arxiv data and calculate perplexity by following these steps:

1. Encode the arxiv text.
2. Cut or concatenate the encoded sequences into multiple fixed-length samples (e.g., 8192).
3. Calculate the model's perplexity.
