### ISSUE TITLE
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects[BUG] <title>

### ISSUE THREAD

**Issue by aaronysl** [QwenLM/Qwen#210]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

pip install -r requirements.txt 报错

### 运行环境 | Environment

```Markdown
- OS:MAC OS
- Python: 3.10
- Transformers:
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

有没有遇到同样情况的

**Comment by CharlexChen** [comment]
我也遇到这种情况，楼主有解决方案了吗

**Comment by MehmetOzaslan** [comment]
Check this: https://github.com/huggingface/transformers/issues/2831

Seems that we need a rust compiler to fix the issue. 
Primary solution: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by bugsebe** [comment]
same dipshit ass bullshit here as well take your skirts off ladies and it the fuck together: Building wheels for collected packages: safetensors
  Building wheel for safetensors (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for safetensors (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\safetensors
      copying py_src\safetensors\flax.py -> build\lib.win-amd64-cpython-310\safetensors
      copying py_src\safetensors\numpy.py -> build\lib.win-amd64-cpython-310\safetensors
      copying py_src\safetensors\paddle.py -> build\lib.win-amd64-cpython-310\safetensors
      copying py_src\safetensors\tensorflow.py -> build\lib.win-amd64-cpython-310\safetensors
      copying py_src\safetensors\torch.py -> build\lib.win-amd64-cpython-310\safetensors
      copying py_src\safetensors\__init__.py -> build\lib.win-amd64-cpython-310\safetensors
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for safetensors
Failed to build safetensors
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects

**Comment by bugsebe** [comment]
> Check this: [huggingface/transformers#2831](https://github.com/huggingface/transformers/issues/2831)
> 
> Seems that we need a rust compiler to fix the issue. Primary solution: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

or, someone in the pipeline fix the error and the deps needed?  Crazy thought I know.

**Comment by MehmetOzaslan** [comment]
If you want to get your feet wet quickly, I've had better luck using hosted services like google collab. It's a bit unfortunate that running these things locally can lead to issues like this.  Too many random dependencies.

**Comment by hytting** [comment]
Had the same issue and the following code worked well for me:

conda install -c conda-forge rust
git clone https://github.com/huggingface/safetensors
cd safetensors/bindings/python
pip install setuptools_rust
pip install -e .

source from: https://github.com/huggingface/safetensors

**Comment by lzxue** [comment]
> @aaronysl @CharlexChen @bugsebe Will it work fine if you try the commands @hytting just provided?

I have resolved

**Comment by osm-zrl** [comment]
> Had the same issue and the following code worked well for me:
> 
> conda install -c conda-forge rust git clone https://github.com/huggingface/safetensors cd safetensors/bindings/python pip install setuptools_rust pip install -e .
> 
> source from: https://github.com/huggingface/safetensors

this worked for me until the last command didn't work, so i tried to change my python version from 3.12 to 3.10 and it worked
