### ISSUE TITLE
💡 [REQUEST] 请问贵公司以后会开源更大参数的模型吗

### ISSUE THREAD

**Issue by endNone** [QwenLM/Qwen#218]
### 起始日期 | Start Date

8/21/2023

### 实现PR | Implementation PR

请问贵公司以后会开源更大参数的模型吗

### 摘要 | Summary

更大参数的模型

### 基本示例 | Basic Example

更大参数的模型

### 缺陷 | Drawbacks

更大参数的模型

**Comment by jklj077** [comment]
我们已在魔搭社区（ModelScope）和Hugging Face推出**Qwen-14B**和**Qwen-14B-Chat**模型，并开源 [qwen.cpp](https://github.com/QwenLM/qwen.cpp) 和 [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent)。**Qwen-7B**和**Qwen-7B-Chat**的代码和模型也同步得到更新。**请使用最新的代码和模型！**
- 相比原版Qwen-7B，新版用了更多训练数据（从2.2T增加到2.4T tokens），序列长度从2048扩展至8192。整体中文能力以及代码能力均有所提升。

欢迎使用体验！
