### ISSUE TITLE
⚗️ Pretrain experiments

### ISSUE THREAD

**Issue by averkij** [QwenLM/Qwen#220]
你好!

I want to know more about pretrain experiments mentioned in **tech_memo.md**.

```
The mix of pretraining corpora has been optimized through numerous ablation experiments.
```

Can you please share your experience on this?

_It would be very useful for other AI researchers._

**Comment by jklj077** [comment]
你好！

We have recently released a technical report on arXiv. However, I doubt that it can really answer to your issue. At the time, we are unable to provide more information. Thanks for the support!

**Comment by averkij** [comment]
谢谢。 我明白了。
