### ISSUE TITLE
web_demo.py起来以后，推理时间很长怎么解决？

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [QwenLM/Qwen#223]
web_demo.py起来以后，推理时间很长怎么解决？

**Comment by JustinLin610** [comment]
是因为生成序列较长吗？

**Comment by ymmbb8882ymmbb** [comment]
> 是因为生成了一系列吗？

什么意思？是每一次的的对话推理时间都很长，最短的对话字数5个字左右，也需要3-4秒才能回复

**Comment by acan0513** [comment]
检查模型是否加载到两张GPU上了。我在一个拥有两个GPU的主机上运行，遇到了同样的问题，但是当我指定GPU后，问题得到解决。
