### ISSUE TITLE
Qwen-7B-Chat的Int4量化模型怎么写进web_demo.py里，按照readme写不对啊，都需要改哪里啊？

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [QwenLM/Qwen#226]
Qwen-7B-Chat的Int4量化模型怎么写进web_demo.py里，按照readme写不对啊，都需要改哪里啊？

**Comment by qijigaici** [comment]
同问

**Comment by JustinLin610** [comment]
我已经更新了web_demo，可以用int4起。

**Comment by ymmbb8882ymmbb** [comment]
> 我已经更新了web_demo，可以用int4起。

除了int4模型能起来，其他模型起不来了

**Comment by JustinLin610** [comment]
现在最新的transformers的接口已经支持了autogptq，不需要修改代码
