### ISSUE TITLE
[BUG] 无法生成指定长度文本

### ISSUE THREAD

**Issue by JDanielWu** [QwenLM/Qwen#233]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

对话无法输出指定长度的文本，例如：请以“5G远程医疗”作为题目，写一篇作文，要求5000字以上。
生成的结果只有800字左右，并且有很强的截断痕迹

### 期望行为 | Expected Behavior

能够生成长文本

### 复现方法 | Steps To Reproduce

测试环境，请以“5G远程医疗”作为题目，写一篇作文，要求5000字以上。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JDanielWu** [comment]
我在generation_config.json中修改max_new_tokens，但是还是没有效果

**Comment by JustinLin610** [comment]
改成8192，我web demo上测试正常
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/9581a7f0-56d1-4d92-836e-c219a12e851b)

**Comment by JDanielWu** [comment]
> 改成8192，我web demo上测试正常 ![image](https://user-images.githubusercontent.com/27664428/262858388-9581a7f0-56d1-4d92-836e-c219a12e851b.png)

这个没超过5000字吧

**Comment by JDanielWu** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/28683533/b08e086e-5f28-49b4-97a5-bce8a5a5e551)
这个是 写一篇5000字以上的作文，主题是AI大模型

**Comment by yangapku** [comment]
@JDanielWu 这个问题具体涉及了几个方面。首先，对于您在demo和命令行中遇到的出现硬性截断的问题，这个一定程度上是可以通过增大model.generation_config中的`max_new_tokens`（新生成长度的最大值，超过就强制截断）来规避的，可以调大此值，避免生成过程中提前被强制截断。

当然增大`max_new_tokens`之后，还是有小概率可能仍然出现这个截断问题，此时就是模型自己中途主动生成了结束符，而非被动被强行截断的，只是表现上和被截断一致。这种情况下，由于chat模型本身是多轮交互的，可以尝试输入“继续”，让模型在下一轮主动续写，也可以继续进行下去。

在绕开了截断问题后，如果发现模型写的完整文章长度仍然达不到指定字数，您可以再试试在后面轮次的交互中，让模型针对一部分内容扩写，比如继续追问“针对5G远程医疗的挑战部分，可以再提供更多细节，给出更多实例，进行一些扩写吗”类似这样，让模型在下一轮中扩充更多内容，这样也可以在交互中完成一篇长文章。

**Comment by geoxpert0001** [comment]
> generation_config.json

不好意思 請問這份json 在哪邊可以看到 我也想修改字數上限
