### ISSUE TITLE
qwen-chat-int4模型执行beam-search解码时，相同的input会得到不同的生成内容

### ISSUE THREAD

**Issue by qiufengyuyi** [QwenLM/Qwen#236]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

当前下载了hf上的qwen-chat-int4模型，调用model.chat()，generation_config配置代码如下：
generation_config = GenerationConfig.from_pretrained(self.checkPoint.model_path, trust_remote_code=True)
generation_config.update(**{"do_sample": False, "max_new_tokens": 8192 - input_ids.size(1), "temperature": 0.1,"num_beams":3})
model.chat(generation_config=generation_config)
使用了相同的input，重复跑了5次，发现有5次返回的回复会有不同。

### 期望行为 | Expected Behavior

使用beam-search时，理论上应该是一个确定性的解码方法，相同input只会得到相同的生成内容。

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.10
- Transformers:4.31.0
- PyTorch:2.01
- CUDA 11.4
```

**Comment by JustinLin610** [comment]
do_sample你手动改成了False，就是greedy，肯定就会生成同一个结果了。我们没做beam search

**Comment by jklj077** [comment]
您好，请问结果差的多吗？结果很类似的话，可以看看是不是以下问题
- https://github.com/QwenLM/Qwen/issues/885

如结果差的很多的话，请重开本issue哈。
