### ISSUE TITLE
qwen-7b模型如何调整可以不询问的内容作为返回值，以及如何控制最终回答的结果不重复

### ISSUE THREAD

**Issue by fernlishon** [QwenLM/Qwen#237]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

qwen-7b（不是7b-chat模型）模型如何调整可以不询问的内容作为返回值，以及如何控制最终回答的结果不重复

代码：
```
# qwen_chat_model_path = "/root/.cache/huggingface/hub/models--Qwen--Qwen-7B-Chat/snapshots/6463a1ff9fe3b8924b5350d7db00c557c133517e"
model_path = "/root/.cache/huggingface/hub/models--Qwen--Qwen-7B/snapshots/31e5e649c6505870ec0500efaa25789b44401565"
# 请注意：分词器默认行为已更改为默认关闭特殊token攻击防护。
base_tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
base_qwen_model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True).eval()
base_qwen_model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)
lora_checkpoint_path = "/LLaMA-Efficient-Tuning/self_train_dir/path_to_sft_checkpoint"
lora_model = PeftModel.from_pretrained(base_qwen_model, lora_checkpoint_path)
base_qwen_model.eval()
lora_model.eval()

inputs = base_tokenizer( prompt, return_tensors='pt')
inputs = inputs.to(lora_model.device)
pred = lora_model.generate(**inputs)
# print("\n\nRES...>>>>>", base_tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
sql_res = base_tokenizer.decode(pred.cpu()[0], skip_special_tokens=True)

print("....>>>> QUERY: ", query)
print("....>>>> LORA MODEL: ", sql_res)
sql_query_res, history = model.chat(tokenizer, prompt, history=None)
```
返回结果：其中蓝框部分为prompt，红框为回答结果一直在重复
![image](https://github.com/QwenLM/Qwen-7B/assets/40875653/12391e89-919e-4e14-8a3b-97f4f6d50e1f)

### 期望行为 | Expected Behavior
期望只回答一句结果：
SELECT * FROM dwd_table_order_di WHERE status_code = -5;
_No response_

### 复现方法 | Steps To Reproduce
输入prompt：
你现在是SQL文本转换器，只回答SQL。查询订单状态为'订单创建'的订单。\n表:dwd_table_order_di\n字段:order_id : 订单id, order_dt : 订单日期(yyyy-mm-dd), status_code : 订单状态(-6:风控拦截,-5:订单创建,-4:支付失败,-3:用户支付中,-2:支付完成,-1:订单无效,0:订单待接单,1:客服代接单,2:商户接单,3:订单取消中,9:订单完结)。
_No response_

### 运行环境 | Environment

```Markdown
- OS: 2023 x86_64 x86_64 x86_64 GNU/Linux
- Python:3.10.12
- Transformers:4.31.0
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):V12.2.91

```

**Comment by JustinLin610** [comment]
有点没理解问题。现在是要用base模型，通过prompt直接得到结果而非续写？为什么要这么做而不是使用chat模型呢

**Comment by jklj077** [comment]
由于较长时间没有新响应，代码与模型已经历较多更新，请尝试最新代码与模型。如问题仍存在，欢迎新开issue。
