### ISSUE TITLE
[BUG] int4模型加载速度较慢

### ISSUE THREAD

**Issue by jackaihfia2334** [QwenLM/Qwen#239]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

int4模型和fp16模型均存放在固态硬盘中，采用官方reademe进行模型加载，fp16的加载速度正常，int4模型加载速度极慢，不符合固态硬盘的读取速度

![image](https://github.com/QwenLM/Qwen-7B/assets/52377418/1d04f6b2-e1e9-4258-97d8-a096c9cfb8d6)

### 期望行为 | Expected Behavior

int加载应该更快

### 复现方法 | Steps To Reproduce

from auto_gptq import AutoGPTQForCausalLM
model = AutoGPTQForCausalLM.from_quantized("/data1/llm/model/Qwen-7B-Chat-Int4", device_map="auto", trust_remote_code=True, use_safetensors=True).eval()

### 运行环境 | Environment

```Markdown
- OS:wsl+docker(ubuntu22.04)
- Python:3.10.12
- Transformers:4.32.0
- PyTorch:2.0.1+cu11.8
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by JustinLin610** [comment]
safetensors比bin文件加载还要更快，未遇到过加载速度问题。看能不能有更多机器信息和运行环境信息提供，这类问题比较难复现

**Comment by jackaihfia2334** [comment]
> safetensors比bin文件加载还要更快，未遇到过加载速度问题。看能不能有更多机器信息和运行环境信息提供，这类问题比较难复现

我使用的是wsl+docker的形式，docker是pytorch的官方ngc镜像。猜测应该是docker本身的io性能存在问题，与qwen无关

**Comment by dage0127** [comment]
pip install auto-gptq optimum 这个试试。
