### ISSUE TITLE
[BUG] 关于Tokenize中特殊token使用求解

### ISSUE THREAD

**Issue by keaidechen** [QwenLM/Qwen#240]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

https://github.com/QwenLM/Qwen-7B/blob/main/tokenization_note_zh.md 
文档中描述可以使用 可用<|extra_0|>到<|extra_204|>来指代一些特殊token，比如bos、eos
实际使用中我们使用了 <|extra_0|>等几个特殊token，使用lora微调，发现了如下问题：
1.发现几乎不会生成这些特殊token
![image](https://github.com/QwenLM/Qwen-7B/assets/52874445/73c9cbb6-25f9-4859-9f3b-f05638c0978f
![image](https://github.com/QwenLM/Qwen-7B/assets/52874445/0ca4ac4f-7746-4fa1-8adc-68eb2f0c8fc6)
2.会生成微调训练集中从来没有出过的“乱token” -> printStats()、RTBU等
3.如果我们add bos等作为特殊token，会直接生成乱码
我们猜测有几个可能的原因：
1.预训练时并没有这些特殊token参与训练，导致其embedding没有参与训练，而使用lora微调不会调整embedding，导致这些token仍然不会有语义存在

### 期望行为 | Expected Behavior

我们期望不生成 RTBU 等接近乱码的token，且按照label的形式生成 <|extra_2|> 等特殊token

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
对于`<|extra_0|>`至`<|extra_204|>`，无论是预训练中还是Chat模型微调中，它们都没有被使用，相当于是“空白”概念。因而通过后续微调可以赋予全新的意义，且不与之前训练过程中使用的特殊token冲突。未微调新加入的token的话，确实也会导致生成异常。

对于该场景，以下方案供您参考：
1. 建议微调embedding，可开启peft中微调embedding的功能，参见https://github.com/huggingface/peft/pull/337#issuecomment-1527412343
2. 复用类似功能的特殊token，如chat模型中的`<|endoftext|>`表示文档结束、`<|im_start|>`表示一轮开始、`<|im_end|>`表示一轮结束，但可能难以修正其原有含义。
3. 采用纯文本表达，但可能不够鲁棒。

**Comment by LotuSrc** [comment]
实际上，尝试了lora+embedding微调后，仍然还是会存在无法正确生成特殊token的问题，模型预测不会停止，前几个字符和问题有一些关联，后续生成的都没有太大意义
