### ISSUE TITLE
[BUG] <title> Failed building wheel for dropout-layer-norm

### ISSUE THREAD

**Issue by maorenyi96** [QwenLM/Qwen#241]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

 RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dropout-layer-norm
  Running setup.py clean for dropout-layer-norm
Failed to build dropout-layer-norm
ERROR: Could not build wheels for dropout-layer-norm, which is required to install pyproject.toml-based projects

### 复现方法 | Steps To Reproduce

pip install csrc/layer_norm

### 运行环境 | Environment

```Markdown
- OS:win11
- Python:3.11
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

无法成功安装layer_norm，报错找不到原因

**Comment by JustinLin610** [comment]
安装flash attention相关的问题最好在官方repo查看相关指导和issue。我们暂时没遇到这个问题。另，如不安装，也不影响使用

**Comment by ZhenyuYangGithub** [comment]
> 安装flash attention相关的问题最好在官方repo查看相关指导和issue。我们暂时没遇到这个问题。另，如不安装，也不影响使用

我也遇到了同样的错误，并且不安装无法使用千问模型

**Comment by gree2** [comment]
可以参考：https://zhuanlan.zhihu.com/p/675270332

**Comment by mouju** [comment]
> 可以参考：https://zhuanlan.zhihu.com/p/675270332

博文失效了，可以详细说一下吗？
