### ISSUE TITLE
💡 [REQUEST] - 有开源更大模型的计划吗

### ISSUE THREAD

**Issue by Xu-Chen** [QwenLM/Qwen#245]
### 摘要 | Summary

目前很多模型推出了10b+版本，甚至更大参数规模版本，理论上效果更好。请问通义千问有更大规模模型开源计划吗

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by changzhou-pku** [comment]
可以持续关注我们 :D

**Comment by jklj077** [comment]
我们已在魔搭社区（ModelScope）和Hugging Face推出**Qwen-14B**和**Qwen-14B-Chat**模型，并开源 [qwen.cpp](https://github.com/QwenLM/qwen.cpp) 和 [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent)。**Qwen-7B**和**Qwen-7B-Chat**的代码和模型也同步得到更新。**请使用最新的代码和模型！**
- 相比原版Qwen-7B，新版用了更多训练数据（从2.2T增加到2.4T tokens），序列长度从2048扩展至8192。整体中文能力以及代码能力均有所提升。

欢迎使用体验！
