### ISSUE TITLE
[BUG] 通过fastchat利用vllm部署qwen-7b-chat，使用fastchat发布的openai接口发生“输入长度超过2048”异常

### ISSUE THREAD

**Issue by Hspix** [QwenLM/Qwen#248]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用fastchat来部署qwen-7b-chat，发现调用openai的接口输入超过2048 tokens 长度时，出现异常
```
openai.error.APIError: Invalid response object from API: '{"object":"error","message":"This model\'s maximum context length is 2048 tokens. However, you requested 2167 tokens (1655 in the messages, 512 in the completion). Please reduce the length of the messages or completion.","code":40303}' (HTTP response code was 400)
```
但是这种异常在使用modelscope等库直接调用qwen-7b-chat推理时并不会发生。

### 期望行为 | Expected Behavior

注意到可能和```use_dynamic_ntk```与```use_logn_attn```有关。根据hf下模型的长序列评测描述，开启这两个参数后，[已经平均长度15k上的VCSUM摘要数据集测试过](https://huggingface.co/Qwen/Qwen-7B-Chat)，但是似乎在fastchat下不生效。

### 复现方法 | Steps To Reproduce

fastchat部署
1. python3 -m fastchat.serve.controller
2. CUDA_VISIBLE_DEVICES=1 python3 -m fastchat.serve.vllm_worker --model-path ** --trust-remote-code --model-names qwen-7b-chat
3. python3 -m fastchat.serve.openai_api_server --host localhost --port 8000

运行代码
```
    from langchain.prompts import PromptTemplate
    from langchain.chat_models import ChatOpenAI
    from langchain.schema import HumanMessage

    openai_api_key = "EMPTY"
    openai_api_base = "http://localhost:8000/v1"
    model_name = "qwen-7b-chat"

    prompt = PromptTemplate(template=template, input_variables=["html_text"])
    model = ChatOpenAI(
        model=model_name, openai_api_key=openai_api_key, openai_api_base=openai_api_base, verbose=True,
        # use_dynamc_ntk=True, use_logn_attn=True, #no effect
        # model_kwargs={'use_dynamc_ntk': True, 'use_logn_attn': True} #no effect
    )
    query = prompt.format_prompt(html_text=html_text).to_string()
    output = model([HumanMessage(content=query)]) # raise the Exception
```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.32.0
- PyTorch:2.0.1
- vllm:0.1.4
- fschat:0.2.24
- langchain:0.0.274
- openai:0.27.9
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.4
```

**Comment by LouisHeck** [comment]
我也遇到这个问题，检查了下不是vllm问题，是Qwen-7B模型生成问题，模型直接没有达到最大文本长度max_tokens就生成了一个停止符<|im_end|>，同问是什么原因？？？

**Comment by pythongc** [comment]
> 我也遇到这个问题，检查了下不是vllm问题，是Qwen-7B模型生成问题，模型直接没有达到最大文本长度max_tokens就生成了一个停止符<|im_end|>，同问是什么原因？？？

好像是vllm现在还不支持ntk插值

**Comment by pythongc** [comment]
> 我也遇到这个问题，检查了下不是vllm问题，是Qwen-7B模型生成问题，模型直接没有达到最大文本长度max_tokens就生成了一个停止符<|im_end|>，同问是什么原因？？？

错了，这个问题是要把stop传参的时候把这个停止符加进去
