### ISSUE TITLE
[BUG] 提示词长度超过2048后，生成出错

### ISSUE THREAD

**Issue by LouisHeck** [QwenLM/Qwen#249]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1. 提示词长度没有超过2048（不一定是2048，但很接近这个值），可以正确输出结果(输出长度设定为1000)：
  
![1693206080658](https://github.com/QwenLM/Qwen-7B/assets/38588261/46e893db-0455-47e0-89cc-cfc4b8f8319a)

   比如：{ "答案": "是的，高血压是导致脑卒中的危险因素之一。" }
2.  提示词长度超过2048（不一定是2048，但很接近这个值），输出错误(输出长度设定为1000)：
 错误1：生成长度没有达到最大值，就停止生成。
![1693206203091](https://github.com/QwenLM/Qwen-7B/assets/38588261/99741722-f861-40b8-9e59-c909100e54ef)
 错误2：提示词长度超过2048生成空字符，输出错误(输出长度设定为1000)：
![1693206594271](https://github.com/QwenLM/Qwen-7B/assets/38588261/8a5d39e0-4184-441b-b3d3-dbccf9fca3d8)

错误3：继续增加输出长度，超过2048，超过2560，输出结果重复，还带有日文！！！
![1693206556254](https://github.com/QwenLM/Qwen-7B/assets/38588261/a2f900fc-7f83-44ba-b1b0-3202966bcf1a)

### 期望行为 | Expected Behavior

超过2560，甚至4096长度，都能回答正确

### 复现方法 | Steps To Reproduce

使用vllm库中的openai接口，加载Qwen-7B-chat模型，在少于2000个输入token时正常运行，超过就会有问题

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by xusenlinzy** [comment]
https://github.com/vllm-project/vllm/blob/d2b2eed67c49cdda3c1d6fa09ee2ec128b318138/vllm/entrypoints/openai/api_server.py#L626

vllm里面设置的最大长度是config里面的2048，你可以手动修改max_model_len 的取值，比如max_model_len =8192，另外还有一个参数max_num_batched_tokens也会限制文本长度

**Comment by RipperTs** [comment]
You can check out this answer
https://github.com/vllm-project/vllm/issues/809#issuecomment-1692672354
