### ISSUE TITLE
Are you planning on making bigger models?

### ISSUE THREAD

**Issue by francqz31** [QwenLM/Qwen#25]
Are there any intensions on making  13B , 30B or 60B kind of models , or any kind of bigger open-source foundation models??

**Comment by JustinLin610** [comment]
Stay tuned!

**Comment by jklj077** [comment]
We release Qwen-14B and Qwen-14B-Chat on ModelScope and Hugging Face, along with [qwen.cpp](https://github.com/QwenLM/qwen.cpp) and [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent). Codes and checkpoints of Qwen-7B and Qwen-7B-Chat are also updated. PLEASE PULL THE LATEST VERSION!
- Compared to Qwen-7B (original), Qwen-7B uses more training tokens, increasing from 2.2T tokens to 2.4T tokens, while the context length extends from 2048 to 8192. The Chinese knowledge and coding ability of Qwen-7B have been further improved.
