### ISSUE TITLE
Support for llama.cpp

### ISSUE THREAD

**Issue by histfuture** [QwenLM/Qwen#252]
### 起始日期 | Start Date

now

### 实现PR | Implementation PR

Any idea or schedule for supporting llama.cpp?

### 摘要 | Summary

High performance for embeded system.

### 基本示例 | Basic Example

https://github.com/ggerganov/llama.cpp

### 缺陷 | Drawbacks

None

**Comment by JustinLin610** [comment]
On the way.

**Comment by jklj077** [comment]
We have recently released [qwen.cpp](https://github.com/QwenLM/qwen.cpp). Hope it helps.
