### ISSUE TITLE
[BUG] 生成内容夹杂日语文字

### ISSUE THREAD

**Issue by ricosr** [QwenLM/Qwen#260]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/34499660/144aaef3-b0b0-4fb8-9691-3608185d8878)
生成的回复中经常含有日语文字

### 期望行为 | Expected Behavior

全中文或全英文，不要夹杂日文

### 复现方法 | Steps To Reproduce

几乎必现

### 运行环境 | Environment

```Markdown
- OS:ubuntu 22.04.3 LTS
- Python:Python 3.10.12
- Transformers:4.30.2
- PyTorch:2.0.1
- CPU
```

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/acd31f9e-460e-499e-ac87-2733a4aa1de8)
是不是改了参数

**Comment by ricosr** [comment]
> ![image](https://user-images.githubusercontent.com/27664428/264585537-acd31f9e-460e-499e-ac87-2733a4aa1de8.png) 是不是改了参数

我是用这个py脚本启动的，这是我的启动命令，没有改过里面的参数。观察来看，每轮对话，都是出现一次日文，不会多次出现；不同的问题，出现的日文不同；一样的问题貌似出现的日文是一样的（不确定）：
![image](https://github.com/QwenLM/Qwen-7B/assets/34499660/46ac3c37-9d72-46db-b795-3da481d1a2bc)

![image](https://github.com/QwenLM/Qwen-7B/assets/34499660/9d4922f8-f010-4722-b24f-e88794069fc5)

**Comment by JustinLin610** [comment]
尝试下最新的模型并且使用我们提供的默认参数看看是否还会有这类问题？
