### ISSUE TITLE
[BUG] 为什么使用Deepspeed-chat微调LLaMA和Baichuan，batch_size可以开很大，但Qwen就只能特别特别小呢

### ISSUE THREAD

**Issue by sharejing** [QwenLM/Qwen#262]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
未使用过deepspeed-chat，三方库相关代码最好询问官方代码维护者
