### ISSUE TITLE
[BUG] 回复好多与问题无关的字符：好多重复的 Take Five

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#265]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

问题：classic and new jazz
回复：Sure, here are some lyrics to a classic jazz song called 
Take Five by Dave Brubeck: Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five Take Five 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
hi，我们尝试了下这个问题，没有遇到这个问题

![image](https://github.com/QwenLM/Qwen-7B/assets/17811943/a2e95824-81e4-4a14-badf-1f62154a2770)

请提供下复现方法，以便我们重现问题
