### ISSUE TITLE
💡 [REQUEST] - 请问有没有方法可以扩增参数量

### ISSUE THREAD

**Issue by endNone** [QwenLM/Qwen#270]
### 起始日期 | Start Date

请问有没有方法可以扩增参数量

### 实现PR | Implementation PR

请问有没有方法可以扩增参数量

### 摘要 | Summary

请问有没有方法可以扩增参数量

### 基本示例 | Basic Example

请问有没有方法可以扩增参数量

### 缺陷 | Drawbacks

请问有没有方法可以扩增参数量

**Comment by JustinLin610** [comment]
暂时没有这方面尝试经验去做直接的参数扩增
