### ISSUE TITLE
关于引用

### ISSUE THREAD

**Issue by yisunlp** [QwenLM/Qwen#271]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在我的文章中使用Qwen时该引用哪一篇paper？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
我们将尽快公开tech report，暂时还只能引用本github项目

**Comment by JustinLin610** [comment]
引用信息已经在readme中给出
