### ISSUE TITLE
Readme的样例cpu模式报错 

### ISSUE THREAD

**Issue by zouzoutingting** [QwenLM/Qwen#273]
“RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'”
我直接用Readme的样例跑的，cpu模式。
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cpu", trust_remote_code=True).eval()
model.chat(tokenizer, 'hi',history=None)

**Comment by JustinLin610** [comment]
确认有更新到最新代码，或者修改过其中的配置文件之类的吗？这个报错的原因是cpu不支持半精度。但我们默认配置设的是auto，会根据你的机器来自动选择精度。如果还遇到问题，可以试下手动设置fp32=True

**Comment by sunbo1999** [comment]
> 确认有更新到最新代码，或者修改过其中的配置文件之类的吗？这个报错的原因是cpu不支持半精度。但我们默认配置设的是auto，会根据你的机器来自动选择精度。如果还遇到问题，可以试下手动设置fp32=True

cpu推理 cli_demo和web_demo都有问题：
TypeError: transformers_stream_generator.main.NewGenerationMixin.generate() got multiple values for keyword argument 'generation_config'

**Comment by zouzoutingting** [comment]
> 确认有更新到最新代码，或者修改过其中的配置文件之类的吗？这个报错的原因是cpu不支持半精度。但我们默认配置设的是auto，会根据你的机器来自动选择精度。如果还遇到问题，可以试下手动设置fp32=True

加了一行‘model.float()’，解决了
