### ISSUE TITLE
[BUG] function_call是否可以兼容OpenAI规范？

### ISSUE THREAD

**Issue by zhengxiang5965** [QwenLM/Qwen#275]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

当前的function_call 与OpenAI规范不太一样
![image](https://github.com/QwenLM/Qwen-7B/assets/31379313/996b11ce-e88b-43ce-ba81-4cc6b787e948)
主要是parameters的schema不一致

### 期望行为 | Expected Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/31379313/645043fd-de07-42b2-8cc8-6e154411df45)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

stream流的支持十分期待

**Comment by jklj077** [comment]
您好，由于OpenAI API的function描述已发生变动，本issue标记为过时，目前无法与OpenAI API兼容。
