### ISSUE TITLE
[BUG] 设置温度为小数推理报错RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by kingdomad** [QwenLM/Qwen#276]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

int4量化模型设置温度为0.5推理会报错，设置大一点就不会报错。
如何解决？
![image](https://github.com/QwenLM/Qwen-7B/assets/34766852/2aee39ed-4174-4950-a8a5-b8e4a9f8c2a3)
![image](https://github.com/QwenLM/Qwen-7B/assets/34766852/9ab34bdc-607e-4251-b283-4e6b8d72624e)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by kingdomad** [comment]
发现非量化的版本推理时设置温度为小数也会出现同样的报错。

**Comment by JustinLin610** [comment]
暂时没找到较好的解决办法，这个应该还是因为softmax由于温度太低出现精度溢出的情况。建议使用topp来调整生成确定性

**Comment by dayL-W** [comment]
> lora微调qwen14B后，运行模型后报错： RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 请求各位大佬支支招哈~

一样的问题

**Comment by mikeleatila** [comment]
@JustinLin610 @dayL-W @chenhongwu127 I am using Qwen-14B-Chat-Int4 and in the inference I am also getting: "RuntimeError: probability tensor contains either inf, nan or element < 0" I have used different temperature, top_p values in addition to do_sample but with the same result. Has this been fixed and how? Many thanks

**Comment by JJASMINE22** [comment]
精度溢出导致probs出现nan的现象，需要到python环境内的site-packages/transformers/generation/utils.py文件中修改：
<img width="593" alt="11e034268760af66f5771e11a2398bb" src="https://github.com/QwenLM/Qwen/assets/71243616/231958cc-0ed2-47a1-9e87-4768b2889d36">

**Comment by liuyijiang1994** [comment]
> 精度溢出导致probs出现nan的现象，需要到python环境内的site-packages/transformers/generation/utils.py文件中修改： <img alt="11e034268760af66f5771e11a2398bb" width="593" src="https://private-user-images.githubusercontent.com/71243616/285404794-231958cc-0ed2-47a1-9e87-4768b2889d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjY3NDcsIm5iZiI6MTcwMjk2NjQ0NywicGF0aCI6Ii83MTI0MzYxNi8yODU0MDQ3OTQtMjMxOTU4Y2MtMGVkMi00N2ExLTllODctNDc2OGIyODg5ZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOTI5ZmY3MDhmYTAyYTIzZWRkYjczNThhYzk3ZmU0OGQ0NWZkZGExNTFiMjE5NThjZDgzZmQxNDMyMDgxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KdKu7M_36BfxvOy3FL2fyLwlO0l8PNcShLXqn-i2PXU">

这么做相当于greedy search了，不想采样的话generation_config中do_sample设置为false就可以。

**Comment by qinhuangdaoStation** [comment]
> > 精度溢出导致probs出现nan的现象，需要到python环境内的site-packages/transformers/generation/utils.py文件中修改： <img alt="11e034268760af66f5771e11a2398bb" width="593" src="https://private-user-images.githubusercontent.com/71243616/285404794-231958cc-0ed2-47a1-9e87-4768b2889d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjY3NDcsIm5iZiI6MTcwMjk2NjQ0NywicGF0aCI6Ii83MTI0MzYxNi8yODU0MDQ3OTQtMjMxOTU4Y2MtMGVkMi00N2ExLTllODctNDc2OGIyODg5ZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA2MTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOTI5ZmY3MDhmYTAyYTIzZWRkYjczNThhYzk3ZmU0OGQ0NWZkZGExNTFiMjE5NThjZDgzZmQxNDMyMDgxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KdKu7M_36BfxvOy3FL2fyLwlO0l8PNcShLXqn-i2PXU">
> 
> 这么做相当于greedy search了，不想采样的话generation_config中do_sample设置为false就可以。

感谢，解决了
