### ISSUE TITLE
[BUG] 返回重复的内容

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#277]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

返回重复的内容：
问题：给我讲讲瞭望塔
回复：
瞭望塔的外部看起来像一座高大的塔楼，但内部却是由高维生命体所居住。 瞭望塔的内部有一个巨大的圆形空间，里面有一个巨大的能源晶体，每当居民开始冥想时，晶体就会开始倒计时，倒计时结束后，居民才能结束冥想。 瞭望塔的外部看起来像一座高大的塔楼，但内部却是由高维生命体所居住。 瞭望塔的内部有一个巨大的圆形空间，里面有一个巨大的能源晶体，每当居民开始冥想时，晶体就会开始倒计时，倒计时结束后，居民才能结束冥想。 瞭望塔的外部看起来像一座高大的塔楼，但内部却是由高维生命体所居住。 瞭望塔的内部有一个巨大的圆形空间，里面有一个巨大的能源晶体，每当居民开始冥想时，晶体就会开始倒计时，倒计时结束后，居民才能结束冥想。 瞭望塔的外部看起来像一座高大的塔楼，但内部却是由高维生命体所居住。 瞭望塔的内部有一个巨大的圆形空间，里面有一个巨大的能源晶体，每当居民开始冥想时，晶体就会开始倒计时，倒计时结束后，居民才能结束冥想。 瞭望塔的外部看起来像一座高大的塔楼，但内部却是由高维生命体所居住。 瞭望塔的内部有一个巨大的圆形空间，里面有一个巨大的能源晶体，每当居民开始冥想时，晶体就会开始倒计时，倒计时结束后

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
试下调高repetition_penalty，比如调到1.2

**Comment by wangschang** [comment]
> 试下调高repetition_penalty，比如调到1.2

这个参数在什么位置？

**Comment by aikangjun** [comment]
是不是做了量化操作？量化会导致这种情况吗？

**Comment by Nicker-lan** [comment]
> 试下调高repetition_penalty，比如调到1.2

我设置到1.1还是会重复，这个值如何选择
