### ISSUE TITLE
[BUG] 结合使用langchain和openai_api后，qwen推理提前结束

### ISSUE THREAD

**Issue by zhengxiang5965** [QwenLM/Qwen#279]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

提前触发Final Answer:

### 期望行为 | Expected Behavior

thought触发完整

### 复现方法 | Steps To Reproduce

from langchain.agents import Tool
from langchain.tools import BaseTool
from math import pi
from typing import Union
from langchain.agents import initialize_agent
from langchain.agents import AgentType
import os
from langchain.chat_models import ChatOpenAI

os.environ["OPENAI_API_KEY"] = "sk-xxxxxxxxxxxxxxxxxxxxxxx"
llm = ChatOpenAI(
    openai_api_key=os.environ["OPENAI_API_KEY"],
    openai_api_base='http://192.168.233.48:8008/v1',
    temperature=0,
    model_name='gpt-3.5-turbo-0613'
)
class QueryCurrentAlarm(BaseTool):
    name = "query-current-alarm"
    description = """Call this tool to interact with the 获取实时告警 API. What is the 获取实时告警 API useful for? 查询实时未恢复的告警 Parameters: [%7B"name": "userId", "description": "用户ID", "required": true, "schema": %7B"type": "string"%7D%7D] Format the arguments as a JSON object."""

    def _run(self, text: str) -> str:
        return """{"m3":1}"""

    def _arun(self, query: str):
        raise NotImplementedError("This tool does not support async")
    

class SendDingDing(BaseTool):
    name = "SendDingDing"
    description = """Call this tool to interact with the 发送钉钉消息 API. What is the 发送钉钉消息 API useful for? 发送钉钉消息给用户 Parameters: [%7B"name": "title", "description": "消息标题", "required": true, "schema": %7B"type": "string"%7D%7D, %7B"name": "content", "description": "消息内容", "required": true, "schema": %7B"type": "string"%7D%7D, %7B"name": "userId", "description": "收信人用户ID,值为5位数字", "required": false, "schema": %7B"type": "string"%7D%7D] Format the arguments as a JSON object."""

    def _run(self, text: str) -> str:
        return "发送成功"

    def _arun(self, query: str):
        raise NotImplementedError("This tool does not support async")

tools = [QueryCurrentAlarm(),SendDingDing()]

agent = initialize_agent(tools,
                         llm,
                         agent="zero-shot-react-description",
                         verbose=True)
agent("""(登录用户18011)获取当前告警信息后,并将结果使用钉钉发送给用户ID 18011""")

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

同期对比openai，有所欠缺

**Comment by zhengxiang5965** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/31379313/1a784054-0b17-4d46-a14f-d9fb4ee1b263)

OpenAI
![image](https://github.com/QwenLM/Qwen-7B/assets/31379313/ba41fe62-e5c0-49f4-901b-97c47369a68f)

**Comment by zhengxiang5965** [comment]
好像是模型对中文的钉钉关键字理解有问题

**Comment by JianxinMa** [comment]
这一版模型主要关注“执行单次Action”的能力，近期会争取更新一版新的模型增强“执行多次 Actions” 的能力。
