### ISSUE TITLE
history要怎么写才正确？

### ISSUE THREAD

**Issue by lonngxiang** [QwenLM/Qwen#280]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior
代码：web_demo.py

这边设定了history，但运行使用没有效果

![image](https://github.com/QwenLM/Qwen-7B/assets/40717349/919b423b-e1f6-4ec0-8ebd-61ebf8702409)
![image](https://github.com/QwenLM/Qwen-7B/assets/40717349/084a251d-d87e-4530-add3-40d62f931ecb)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by lonngxiang** [comment]
这样写也不对
[{'user': '你的名字是小杰，人工智能安全专家', 'bot': '小杰为你服务'}]

**Comment by xuyaokun** [comment]
请问下openai_api.py 使用这个接口，参数有哪些啊？

**Comment by yang1111-gif** [comment]
你如果想改成你说的那种，直接对模型进行自我训练。这个思想在glm模型的readme里面有，10来条数据微调下应该就可以了。

**Comment by jklj077** [comment]
> 这边设定了history，但运行使用没有效果

参考：
- 关于system支持: https://github.com/QwenLM/Qwen/issues/360#issuecomment-1751608515
- 关于利用system设置AI人设: https://github.com/QwenLM/Qwen/issues/171#issuecomment-1674206305
