### ISSUE TITLE
請問回答長度如何設定

### ISSUE THREAD

**Issue by geoxpert0001** [QwenLM/Qwen#283]
你好 這是我的代碼
```
from transformers import AutoTokenizer, AutoModelForCausalLM

# Note: The default behavior now has injection attack prevention off.
tokenizer = AutoTokenizer.from_pretrained("Qwen-7B-Chat-Int4", trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen-7B-Chat-Int4",
    device_map="auto",
    trust_remote_code=True
).eval()

exit_commands = ['exit', '88', 'bye']  # Define exit commands

history = None

while True:
    user_input = input("Questions (type an 'exit', 'bye' or '88' command to quit):")
    
    # Check if the user input is part of the exit commands
    if user_input.lower() in exit_commands:
        break
    
    response, history = model.chat(tokenizer, user_input, history=history)
    print("Answers:", response)
    print('\n')

print("See you next time.")
```

然後我也在hf git https://huggingface.co/Qwen/Qwen-7B-Chat-Int4/tree/main 下來

但請它回答長描述 似乎都不會有反應 不知道哪邊代碼有寫錯 我請它寫3000字 但回答都永遠只有幾百字而已
![image](https://github.com/QwenLM/Qwen-7B/assets/141697815/9e636943-9b78-419d-a378-6799ae78ffee)

**Comment by JustinLin610** [comment]
I think this is not related to your code. We did not find a good solution to write extremely long text through prompting with the number of tokens yet, and I found even GPT-4 cannot do this work. We try to make the model talk more in our next release and mitigate this problem a bit, but for now, if you really want it to write a long text, you can try with some arguments in generation config of transformers, such as length_penalty, which however may affect the generation quality.

**Comment by geoxpert0001** [comment]
> I think this is not related to your code. We did not find a good solution to write extremely long text through prompting with the number of tokens yet, and I found even GPT-4 cannot do this work. We try to make the model talk more in our next release and mitigate this problem a bit, but for now, if you really want it to write a long text, you can try with some arguments in generation config of transformers, such as length_penalty, which however may affect the generation quality.

只能期待下一版的成品
另外想詢問一下 如果固定語言方式
一開始有請它輸出成繁體 但還是會出現簡體 偶而也會冒出日文
不知道那邊可以去調整修正？

想知道訓練的data 未來有機會加入更多港澳台內容嘛 謝謝

**Comment by JustinLin610** [comment]
For the last question, sry I can't give you an answer for sure. You might try the latest models to see if it works better for you.
