### ISSUE TITLE
自定义history没效果

### ISSUE THREAD

**Issue by lonngxiang** [QwenLM/Qwen#287]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

 自定义history角色没有作用

![image](https://github.com/QwenLM/Qwen-7B/assets/40717349/83ec8f66-687e-4e3f-a05e-ae9cf7478619)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
这个不是history不起作用，而是身份转变相对比较难，这方面问题我们在看如何通过prompt的方法来帮大家解决，当然后续也可能需要更新模型。
