### ISSUE TITLE
同样参数量条件下，qwen的推理速度和显存占用都比llama优秀，原因是什么？

### ISSUE THREAD

**Issue by ASR-SCI** [QwenLM/Qwen#288]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

无

### 期望行为 | Expected Behavior

无

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

无

**Comment by JustinLin610** [comment]
我们没有做过和llama的推理性能对比测算，能提供一个给我们参考吗？
