### ISSUE TITLE
[BUG] <title>huggingface的模型删除了？

### ISSUE THREAD

**Issue by af-74413592** [QwenLM/Qwen#295]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by NirViaje** [comment]
https://huggingface.co/4bit/Qwen-VL-Chat-Int4

**Comment by wujindou** [comment]
Mark ,模型下载不了了

**Comment by Xu-Chen** [comment]
魔塔社区也没了。

**Comment by pei55** [comment]
什么情况，是政策限制还是咋的啊

**Comment by DTliudong** [comment]
mark，同样的问题

**Comment by Brucewuzhang** [comment]
啥情况，阿里的开发大哥能不能透露点消息。后续还会再开源吗？

**Comment by zd1990** [comment]
+1

**Comment by xxxlil** [comment]
+

**Comment by patrick-lau** [comment]
mark

**Comment by trexliu** [comment]
+1

**Comment by Xu-Chen** [comment]
+1

**Comment by Trangle** [comment]
一贯特色？换老板，然后又一波鸡飞狗跳？

**Comment by songsa1** [comment]
蹲

**Comment by thcheung** [comment]
可能跟这个有关係: 阿里云通义千问AI 大模型今日正式向全社会开放

**Comment by xxxlil** [comment]
> 

chatglm不也开放吗

**Comment by xxxlil** [comment]
> 可能跟这个有关係: 阿里云通义千问AI 大模型今日正式向全社会开放

chatglm不也开放吗

**Comment by kanslor** [comment]
是不是原先开源的模型训练数据有问题，需要更新模型

**Comment by JianxinMa** [comment]
> 可能跟这个有关係: 阿里云通义千问AI 大模型今日正式向全社会开放

这两件事没关系，不要恶意揣测。

**Comment by lawmillion** [comment]
蹲个答案~

**Comment by SakuraAcedia** [comment]
mark

**Comment by pei55** [comment]
有消息了吗，还会有不

**Comment by JustinLin610** [comment]
加速解决中，预计很快会恢复。

**Comment by wuyifan18** [comment]
什么情况？

**Comment by Xu-Chen** [comment]
> 加速解决中，预计很快会恢复。

弱弱问一下，再次开源后，会有新版本和更大模型吗？

**Comment by jxst539246** [comment]
已恢复。
