### ISSUE TITLE
[BUG]如此好用qwen模型去哪里了？

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen#297]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如题。

### 期望行为 | Expected Behavior

如题。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by xxm1668** [comment]
@JustinLin610 13b啥时候出来呢

**Comment by jxst539246** [comment]
已恢复
