### ISSUE TITLE
modeling_qwen.py 去哪儿了？？？

### ISSUE THREAD

**Issue by LOGIC-10** [QwenLM/Qwen#298]
没有找到modeling_qwen.py，想查看源代码阅览chat_stream函数

我看在FAQ中有提到modeling_qwen.py，但是仓库里没有，全网搜到huggingface的页面也404了。请问你们是删除了吗

所以，modeling_qwen.py去哪儿了？

**Comment by logicwong** [comment]
已恢复

**Comment by mitoumao** [comment]
还是没有啊， HF上面的页面也是404
OSError: output_qwen_merged does not appear to have a file named modeling_qwen.py. Checkout 'https://huggingface.co/output_qwen_merged/tree/None' for available files.
