### ISSUE TITLE
[BUG] <title>GPTQint4版本运行速度比BitsAndBytes，int4  慢了有10多倍

### ISSUE THREAD

**Issue by invisifire** [QwenLM/Qwen#300]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

GPTQint4版本运行速度比BitsAndBytes，int4  慢了有10多倍，1080ti环境运行

### 期望行为 | Expected Behavior

GPTQint4版本运行速度应当差不多。

### 复现方法 | Steps To Reproduce

1080ti环境运行

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.11
- Transformers:4.32.0
- PyTorch:2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by JustinLin610** [comment]
这个不符合预期哈，GPTQ是要比bnb快很多的，官方readme有测速性能和测速脚本，可以检查是否有cuda的问题或者安装autogptq的问题

**Comment by invisifire** [comment]
@JustinLin610 JustinLin610 我测试过了。生成速度咩有问题，但是读取速度查了20倍。。。GPTQ在读取长文章时速度特别慢请问是正常现象么

**Comment by invisifire** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/59678894/c7afecab-f3df-48fd-8edd-dbf86a588b63)
一个5秒一个125秒可以看一下为什么么

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/9a72a0cb-706f-4d09-9d3f-b97c222a594c)
这是为何？

**Comment by invisifire** [comment]
> ![image](https://user-images.githubusercontent.com/27664428/268196540-9a72a0cb-706f-4d09-9d3f-b97c222a594c.png) 这是为何？
模型库config默认是fp16，就会报这个改fp32就没事，实测改这个没有任何速度区别只会改变第一步加载进cpu时占用的内存

**Comment by yeyupiaoling** [comment]
@invisifire 请问你解决了吗？我也遇到同样的问题，生成速度是挺快的，但是在读取文本的时候非常慢。

**Comment by yeyupiaoling** [comment]
@invisifire 显卡问题，你换一个支持fp16的应该就可以了，我用2080ti就正常速度。

**Comment by jklj077** [comment]
1080Ti上的fp16计算性能会比fp32低很多（大约1/64），实际速度跟直接用fp32计算不太好说，一般是要慢的，也有可能稍快。
autogptq跟bnb比的话，可能也是缺kernel实现，这个请到autogptq里提下吧。换用autogptq也是对普通用户友好很多，效果效率比较均衡。本issue就先关闭了。
