### ISSUE TITLE
💡 调用aiopen_api.py ，提示显存不够，应如何配置支持多卡呢

### ISSUE THREAD

**Issue by xuyaokun** [QwenLM/Qwen#305]
### 起始日期 | Start Date

2023-9-15

### 实现PR | Implementation PR

![1694760608810](https://github.com/QwenLM/Qwen-7B/assets/20808760/11629151-a311-49fb-9f3b-85a15f596a26)

![1694760515278](https://github.com/QwenLM/Qwen-7B/assets/20808760/7b0443ef-ac7e-400a-8206-87525e9d1dec)

我有4张显卡，应该够用，现在看上去只用了一张吧。应如何配置支持多卡呢

### 相关Issues | Reference Issues

应如何配置支持多卡呢

### 摘要 | Summary

应如何配置支持多卡呢

### 基本示例 | Basic Example

应如何配置支持多卡呢

### 缺陷 | Drawbacks

应如何配置支持多卡呢

### 未解决问题 | Unresolved questions

应如何配置支持多卡呢

**Comment by xuyaokun** [comment]
还有一个事儿，我这调用的提交参数看下对否。

{
    "messages": [
        {
            "role": "user",
            "content": "你是谁?"
        }
    ], 
    "model": "Qwen",
    "stream": true
}

**Comment by jklj077** [comment]
> 应如何配置支持多卡呢

多卡部署建议参考README中Deployment部分使用vllm与FastChat。如果使用transformers导入，可以配置`device_map="auto"`，但可能有一定效率问题，原因参见<https://github.com/QwenLM/Qwen/issues/511#issuecomment-1801972535>。

> 我这调用的提交参数看下对否

可以的。
