### ISSUE TITLE
💡 [REQUEST]  如此好用的 qwen，什么时候出 13B ？

### ISSUE THREAD

**Issue by tpoisonooo** [QwenLM/Qwen#308]
### 摘要 | Summary

 如此好用的 qwen，什么时候出 13B ？

### 基本示例 | Basic Example

 如此好用的 qwen，什么时候出 13B ？

### 缺陷 | Drawbacks

huggingface 失踪 5 天了。

**Comment by JustinLin610** [comment]
:) No idea when。有用户上传的版本，可以暂时使用，会尽快恢复。

**Comment by tpoisonooo** [comment]
> :) No idea when。有用户上传的版本，可以暂时使用，会尽快恢复。

纯八卦：你们组还好么。

**Comment by JustinLin610** [comment]
> > :) No idea when。有用户上传的版本，可以暂时使用，会尽快恢复。
> 
> 纯八卦：你们组还好么。

好，非常好，好得很 [wink]

**Comment by jklj077** [comment]
我们近日在魔搭社区（ModelScope）和Hugging Face推出**Qwen-14B**和**Qwen-14B-Chat**模型，并开源 [qwen.cpp](https://github.com/QwenLM/qwen.cpp) 和 [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent)。**Qwen-7B**和**Qwen-7B-Chat**的代码和模型也同步得到更新。**请使用最新的代码和模型！**
- 相比原版Qwen-7B，新版用了更多训练数据（从2.2T增加到2.4T tokens），序列长度从2048扩展至8192。整体中文能力以及代码能力均有所提升。

**Comment by gongel** [comment]
@jklj077 请教下，为啥size要用14B，而不是13B呢？
