### ISSUE TITLE
怎么调用openai_api.py呢，文档也没有说明下啊💡 

### ISSUE THREAD

**Issue by xuyaokun** [QwenLM/Qwen#311]
### 起始日期 | Start Date

2023-9-15

### 实现PR | Implementation PR

.

### 相关Issues | Reference Issues

同上

### 摘要 | Summary

.

### 基本示例 | Basic Example

**是下面这样用的吗，好像也不对啊**

`{
"messages": [
{
"role": "user",
"content": "你是谁?"
}
],
"model": "Qwen",
"stream": true
}`

### 缺陷 | Drawbacks

.

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/120be86b-8a11-41e4-8c67-96ce5d4d5356)
