### ISSUE TITLE
[BUG] the error in Running the open_api.py 

### ISSUE THREAD

**Issue by rexqin** [QwenLM/Qwen#314]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/7374867/f8698279-0fc2-424a-a0d5-cecf08a31857)
I try to run the open_ai.py, but get the error above.  It  seem the network error. I have install pip library by the README.md. So how to slove this? 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JianxinMa** [comment]
see https://github.com/QwenLM/Qwen/issues/330#issuecomment-1733322079

**Comment by JianxinMa** [comment]
You need to use a proxy when connecting to huggingface if you are in the mainland china.
