### ISSUE TITLE
[BUG] Missing models form HuggingFace

### ISSUE THREAD

**Issue by manmax31** [QwenLM/Qwen#316]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Where did the models go from HuggingFace?
Can't find anywhere in:
https://huggingface.co/Qwen

### 期望行为 | Expected Behavior

Missing models

### 复现方法 | Steps To Reproduce

NA

### 运行环境 | Environment

```Markdown
NA
```

### 备注 | Anything else?

NA

**Comment by tpoisonooo** [comment]
#318  released.

**Comment by jklj077** [comment]
The models should be up now.
