### ISSUE TITLE
关于预训练文本长度的问题

### ISSUE THREAD

**Issue by suolyer** [QwenLM/Qwen#317]
哈喽，你好，感谢开源。对于预训练，我有个问题想请教一下，我看readme写的是预训练过了2.2T的token，支持8k的长度。而我在config中看到的是

```
{
  "seq_length": 2048,
  "use_dynamic_ntk": true,
  "use_logn_attn": true
}

```
所以想请问下，是预训练的时候长度是2k，然后通过ntk等方式外推到8k是吗，还是说预训练的时候你们就用的8k。

望回复简答

**Comment by CHENhush** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/30424609/7c9e64f2-1598-47db-8fe4-d120b81a10d0)


https://github.com/QwenLM/Qwen-7B/blob/main/tech_memo.md

**Comment by Losin** [comment]
是的，预训练2048，外推到8192

**Comment by Losin** [comment]
今天新放出来的7B预训练token数扩展到2.4T，长度扩展到8K，利用外推可支持16K/32K

**Comment by suolyer** [comment]
> 今天新放出来的7B预训练token数扩展到2.4T，长度扩展到8K，利用外推可支持16K/32K

太赞了，就喜欢你们这种工作，点赞点赞！

**Comment by Scarlett-H** [comment]
> 今天新放出来的7B预训练token数扩展到2.4T，长度扩展到8K，利用外推可支持16K/32K

我看了下config.py中max_position_embeddings为8k，为什么不是2048呢，还有一个问题哈，外推是说seq_length可以为16k或者32k吗，那max_position_embeddings不变？

**Comment by secain** [comment]
> > 今天新放出来的7B预训练token数扩展到2.4T，长度扩展到8K，利用外推可支持16K/32K
> 
> 我看了下config.py中max_position_embeddings为8k，为什么不是2048呢，还有一个问题哈，外推是说seq_length可以为16k或者32k吗，那max_position_embeddings不变？

我现在还没理解这个问题 长度外推的话 需要修改config里面的max_position_embeddings吗
