### ISSUE TITLE
Qwen-14B 如何获取💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by HouYueJie** [QwenLM/Qwen#318]
### 起始日期 | Start Date

9/24/2023

### 摘要 | Summary

C-Eval显示Qwen-14B是开源模型，请问如何获取权重？
![image](https://github.com/QwenLM/Qwen-7B/assets/66465115/f973e190-eef2-4d72-9624-fec1685d7cf0)

### 基本示例 | Basic Example

*

### 缺陷 | Drawbacks

*

**Comment by GanjinZero** [comment]
已发布

**Comment by HouYueJie** [comment]
谢谢
