### ISSUE TITLE
[BUG] <title> 商用申请链接，还是 7B 的

### ISSUE THREAD

**Issue by liwenju0** [QwenLM/Qwen#324]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/16049564/93e2cb49-c213-4800-b29b-f91310f8deda)

### 期望行为 | Expected Behavior

加入 14B 的商用申请协议

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yingdachen** [comment]
哪里的链接？modelscope上的是正确的

https://dashscope.console.aliyun.com/openModelApply/Qwen-14B-Chat

**Comment by liwenju0** [comment]
该 repo 下面的

**Comment by jklj077** [comment]
readme中链接已调整，感谢报告问题~
