### ISSUE TITLE
[BUG] Qwen-14B-chat的推理速度很慢，比7B慢很多，有人遇到这个情况吗

### ISSUE THREAD

**Issue by liuyukid** [QwenLM/Qwen#327]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by liuyukid** [comment]
没有flash-attention，GPU是A10

**Comment by bittteerr** [comment]
同样的问题，特别慢，A800，生成1450字，用时507秒。

**Comment by liwenju0** [comment]
同样的问题，推理很慢，有解决的吗

**Comment by logicwong** [comment]
请移步 #372 进行讨论，方便查找问题。
