### ISSUE TITLE
Qlora 微调报错，无法加载tokenizer

### ISSUE THREAD

**Issue by yijunL** [QwenLM/Qwen#328]
拉取的9.25最新代码，模型是9.25 modelscope上下载的qwen-7B
torch=2.0.0

Traceback (most recent call last):
  File "finetune.py", line 353, in <module>
    train()
  File "finetune.py", line 294, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/optimum/gptq/quantizer.py", line 300, in quantize_model
    raise ValueError(
ValueError: We were not able to get the tokenizer using `AutoTokenizer.from_pretrained`
                    with the string that you have passed /root/autodl-tmp/qwen/Qwen-7B. If you have a custom tokenizer, you can pass it as input.
                    For now, we only support quantization for text model. Support for vision, speech and multimodel will come later.

**Comment by ChiQiuHong** [comment]
使用Int4量化模型不会报错

**Comment by yijunL** [comment]
> from transformers import BitsAndBytesConfig

感谢！ 问题已解决！

**Comment by zzwtop1** [comment]
> 同样的错，请问解决没？ same issue, any solution?
> 
> 目前自己测试成功的解决方法 finetune.py里，load model的代码
> 
> ```
>     model = transformers.AutoModelForCausalLM.from_pretrained(
>         model_args.model_name_or_path,
>         config=config,
>         cache_dir=training_args.cache_dir,
>         device_map=device_map,
>         trust_remote_code=True,
>         quantization_config=GPTQConfig(
>             bits=4, disable_exllama=True
>         )
>         if training_args.use_lora and lora_args.q_lora
>         else None,
>     )
> ```
> 
> 量化的config改成BitsAndBytesConfig
> 
> ```
>     model = transformers.AutoModelForCausalLM.from_pretrained(
>         model_args.model_name_or_path,
>         config=config,
>         cache_dir=training_args.cache_dir,
>         device_map=device_map,
>         load_in_4bit=True,
>         trust_remote_code=True,
>         quantization_config=BitsAndBytesConfig(
>             load_in_4bit=True,
>             bnb_4bit_compute_dtype=torch.float16,
>             bnb_4bit_use_double_quant=True,
>             bnb_4bit_quant_type="nf4",
>             llm_int8_threshold=6.0,
>             llm_int8_has_fp16_weight=False,
>         )
>         if training_args.use_lora and lora_args.q_lora
>         else None,
>     )
> ```
> 
> 开头加“from transformers import BitsAndBytesConfig” 没有bitsandbytes要先pip install bitsandbytes

哥们，这个方法是不报加载分词器错误了，但显存明显升高直接爆了。。。

**Comment by zzwtop1** [comment]
仔细看了一下官方文档，qlora只支持int量化后的，我加载的是qwen-14b-chat，报了这个错
