### ISSUE TITLE
openai_api.py 使用流式调用时出错了

### ISSUE THREAD

**Issue by xuyaokun** [QwenLM/Qwen#330]
### 起始日期 | Start Date

2023-9-25

### 摘要 | Summary

![image](https://github.com/QwenLM/Qwen/assets/20808760/5eb16311-5b80-4827-bb89-b177a3a31361)

### 基本示例 | Basic Example

如上图

### 缺陷 | Drawbacks

如上图

### 未解决问题 | Unresolved questions
![1695620093831](https://github.com/QwenLM/Qwen/assets/20808760/c57bd2f4-7d7b-432d-b883-88a958ebf284)

![image](https://github.com/QwenLM/Qwen/assets/20808760/cea1c002-d4eb-4d11-b11d-d6d8778127b5)

**Comment by xuyaokun** [comment]
咋回事儿啊，这个，有人遇到没

**Comment by JianxinMa** [comment]
pip install pydantic>=2.3.0

**Comment by xuyaokun** [comment]
> pip install pydantic>=2.3.0

按这安装了，还是报一样的错误 ！

**Comment by JianxinMa** [comment]
> > pip install pydantic>=2.3.0
> 
> 按这安装了，还是报一样的错误 ！

之前的文档没有指定 pydantic 版本，会出现安装了 1.x.x 版本的pydantic的问题，会报您截图的这个错误。建议卸载并重新安装pydantic试试？
```
pip uninstall pydantic
pip install pydantic>=2.3.0
```

**Comment by xuyaokun** [comment]
![image](https://github.com/QwenLM/Qwen/assets/20808760/452b8c79-c441-48fc-a8c7-673a4c71b12b)
**终于成功了，太爱你了 ！！！**

> > > pip install pydantic>=2.3.0
> > 
> > 
> > 按这安装了，还是报一样的错误 ！
> 
> 之前的文档没有指定 pydantic 版本，会出现安装了 1.x.x 版本的pydantic的问题，会报您截图的这个错误。建议卸载并重新安装pydantic试试？
> 
> ```
> pip uninstall pydantic
> pip install pydantic>=2.3.0
> ```

**Comment by xuyaokun** [comment]
**最后问下，历史history 怎么使用呢？ 请提供下例子吧，感谢！**
`{
    "model": "Qwen",
    "messages": [
        {
            "role": "user",
            "content": "东面有哪几个省"
        }
    ],
    "top_p": 0.7,
    "temperature": 0.9,
    "stream": true ,
    "history":[
        {
            "role": "user",
            "content": "河南西面有哪几个省"
        }
    ]
}`  这样不对呢

**Comment by xuyaokun** [comment]
`{ "model": "Qwen", "messages": [ { "role": "user", "content": "东面有哪几个省" } ], "top_p": 0.7, "temperature": 0.9, "stream": true , "history":[ { "role": "user", "content": "河南西面有哪几个省" } ] }`

**Comment by JianxinMa** [comment]
> **最后问下，历史history 怎么使用呢？ 请提供下例子吧，感谢！** `{ "model": "Qwen", "messages": [ { "role": "user", "content": "东面有哪几个省" } ], "top_p": 0.7, "temperature": 0.9, "stream": true , "history":[ { "role": "user", "content": "河南西面有哪几个省" } ] }` 这样不对呢

和gpt的用法一致，history也放messages里，不需要单独传history这个字段。
```
    messages = [{"role": "user", "content": "你好"}]
    messages.append({"role": "assistant", "content": "你好！很高兴为你提供帮助。"})
    messages.append({"role": "user", "content": "给我讲一个年轻人奋斗创业最终取得成功的故事。故事只能有一句话。"})
    messages.append(
        {
            "role": "assistant",
            "content": "故事的主人公叫李明，他来自一个普通的家庭，父母都是普通的工人。李明想要成为一名成功的企业家。……",
        }
    )
    messages.append({"role": "user", "content": "给这个故事起一个标题"})
    response = openai.ChatCompletion.create(model="Qwen", messages=messages)  # model的值不重要，有这个参数即可
    print(response)
```
另外，不建议配temperature参数，容易有数值溢出问题。

**Comment by xuyaokun** [comment]
> > **最后问下，历史history 怎么使用呢？ 请提供下例子吧，感谢！** `{ "model": "Qwen", "messages": [ { "role": "user", "content": "东面有哪几个省" } ], "top_p": 0.7, "temperature": 0.9, "stream": true , "history":[ { "role": "user", "content": "河南西面有哪几个省" } ] }` 这样不对呢
> 
> 和gpt的用法一致，history也放messages里，不需要单独传history这个字段。
> 
> ```
>     messages = [{"role": "user", "content": "你好"}]
>     messages.append({"role": "assistant", "content": "你好！很高兴为你提供帮助。"})
>     messages.append({"role": "user", "content": "给我讲一个年轻人奋斗创业最终取得成功的故事。故事只能有一句话。"})
>     messages.append(
>         {
>             "role": "assistant",
>             "content": "故事的主人公叫李明，他来自一个普通的家庭，父母都是普通的工人。李明想要成为一名成功的企业家。……",
>         }
>     )
>     messages.append({"role": "user", "content": "给这个故事起一个标题"})
>     response = openai.ChatCompletion.create(model="Qwen", messages=messages)  # model的值不重要，有这个参数即可
>     print(response)
> ```
> 
> 另外，不建议配temperature参数，容易有数值溢出问题。

![image](https://github.com/QwenLM/Qwen/assets/20808760/8ad7ac28-a34a-45c8-af87-46301c400b93)
### 好了，多谢！！！
