### ISSUE TITLE
report中的QWEN-1.8B版会考虑开源吗？

### ISSUE THREAD

**Issue by nlp4whp** [QwenLM/Qwen#331]
看Table 2, 5里的结果，1.8B 对比很多 7B 依然很有竞争力，所以好奇是否会开源1.8B的版本

**Comment by Losin** [comment]
会考虑，但暂无法给出时间

**Comment by lj163ucas** [comment]
https://zhuanlan.zhihu.com/p/660887689
1-3B的战斗已经打响，小羊驼都怼脸上，坤哥怎么能输捏？[狗头]
![image](https://github.com/QwenLM/Qwen/assets/126590140/58d4c620-d287-41d0-b3cb-a6bb06cf4e0f)
