### ISSUE TITLE
[BUG] 14B 回答的中文里夹带了乱七八糟的语言

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#334]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

下面的回复中包含未知语言：néparation
问：详细介绍一下纽约
答：纽约是美国最大的城市，也是世界上最重要的金融中心之一。它位于美国东海岸的北部，并且拥有许多著名的景点和文化活动。它的历史可以追溯到17世纪，当时荷兰人在这里建立了新阿姆斯特丹殖民地。现在，纽约是一个多元文化的都市，拥有多样化的文化和美食，以及世界级的艺术、音乐和体育活动。\n\néparation

下面的回复中包含不相关的英文单词 softly ，carving 
问：详细介绍一下纽约
答：纽约是美国最大的城市，位于美国东北部的纽约州。它 softly 以其独特的文化和历史而闻名，拥有世界上最高的摩天大楼、最著名的博物馆和艺术馆以及世界上最繁忙的港口之一。
纽约市由五个行政区组成：曼哈顿、布鲁克林、皇后区、斯塔滕岛和布朗克斯。每个行政区都有其独特的历史、文化和社会特色，并且在经济上都发挥着重要作用。
纽约市也是全球金融中心之一，有许多大型金融机构总部设 carving 在这里。此外，该市还拥有许多知名的公司和企业，包括媒体巨头如新闻集团和幹达利环球集团等。
除了商业活动外，纽约市还是一个充满活力的文化中心，拥有多家世界级的艺术机构和表演场所。例如大都会艺术博物馆、现代艺术博物馆、百老汇剧院和中央公园等都是游客必去之地。
总的来说，纽约是一个多元化的大都市，融合了各种不同的文化、美食、娱乐和购物体验。无论你是来旅游还是生活在这里，都能找到适合自己的乐趣和享受。

### 期望行为 | Expected Behavior

回复全部是中文

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by micronetboy** [comment]
下面的回答中包含：nullable
问：详细介绍一下纽约
答：好的，我可以为您介绍一些关于纽约的信息。首先，它是美国nullable最大的城市，也是全球最重要的金融中心之一。它拥有丰富的历史和文化，并且有许多世界著名的景点，如自由女神像、中央公园等。此外，纽约也是一个购物天堂，有很多知名的购物中心和品牌商店。最后，它还是一个多元化的国际大都市，有着来自世界各地的美食、文化和艺术活动。

**Comment by JustinLin610** [comment]
应该是群里说的改了topp和temperature的？用默认的试下
![image](https://github.com/QwenLM/Qwen/assets/27664428/b2e801e5-cee4-48c4-9694-598bb946dfd9)

**Comment by ye7love7** [comment]
请问加载14B模型需要多少显存？

**Comment by MelodyChenjun** [comment]
你是用fastchat进行的推理吗，还是用qwen的web呀

**Comment by ye7love7** [comment]
使用fastchat的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月28日(周四) 上午10:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen] [BUG] 14B 回答的中文里夹带了乱七八糟的语言 (Issue #334)




 
你是用fastchat进行的推理吗，还是用qwen的web呀
