### ISSUE TITLE
流式调用api报错，webui启动报错

### ISSUE THREAD

**Issue by nimo12138** [QwenLM/Qwen#336]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

**部署量化的init4  14b模型，启动api服务正常，使用非流式正常调用，使用流式会报错
启动webui服务直接报错，说找不到模型文件，报错截图如下，已经修改了模型文件地址，使用的huggingface上的14b量化模型**
![image](https://github.com/QwenLM/Qwen/assets/15177513/d9bb659e-cef4-4b0c-b49c-c05f48f350c2)
![image](https://github.com/QwenLM/Qwen/assets/15177513/22b96425-0423-4012-945e-e9638c5c5667)

**下面这个是流式访问api报错**
![image](https://github.com/QwenLM/Qwen/assets/15177513/e07fa33e-8f56-4d34-b782-beda7896c46d)

### 期望行为 | Expected Behavior

期望的是api模式下流式也能正常访问，webui能够正常启动

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by thb10086** [comment]
同问+1

**Comment by JianxinMa** [comment]
see https://github.com/QwenLM/Qwen/issues/330#issuecomment-1733322079

**Comment by nimo12138** [comment]
非量化的14B使用webui启动正常，int4量化后的14B使用webui就一直提示找不到模型文件的报错

**Comment by fyabc** [comment]
@nimo12138 您好，目前我们这边暂时无法复现Qwen-14B-Chat-Int4模型加载的问题
看截图中Qwen-14B-Chat-Int4模型加载时使用的还是旧的web_demo.py，您可以更新一下GitHub代码和HF中的配置，重新尝试一下。

**Comment by nimo12138** [comment]
> @nimo12138 您好，目前我们这边暂时无法复现Qwen-14B-Chat-Int4模型加载的问题 看截图中Qwen-14B-Chat-Int4模型加载时使用的还是旧的web_demo.py，您可以更新一下GitHub代码和HF中的配置，重新尝试一下。

更新文件后已解决，但是webui回复的内容无法显示，后台可以显示，应该是消息拼接的问题

**Comment by fyabc** [comment]
> > @nimo12138 您好，目前我们这边暂时无法复现Qwen-14B-Chat-Int4模型加载的问题 看截图中Qwen-14B-Chat-Int4模型加载时使用的还是旧的web_demo.py，您可以更新一下GitHub代码和HF中的配置，重新尝试一下。
> 
> 更新文件后已解决，但是webui回复的内容无法显示，后台可以显示，应该是消息拼接的问题

您好，可以提供一下问题的截图吗？

**Comment by jklj077** [comment]
由于相关代码已经过多次更新，issue可能已经不适用了，请尝试使用最新代码和使用说明看下哈。如果仍有问题的话，请重开本issue吧。
