### ISSUE TITLE
💡 [REQUEST] - QWen-1.8B模型开放开源

### ISSUE THREAD

**Issue by WangRongsheng** [QwenLM/Qwen#337]
### 摘要 | Summary

QWen-1.8B模型开放开源吗？

### 基本示例 | Basic Example

QWen-1.8B模型开放开源吗？

### 缺陷 | Drawbacks

QWen-1.8B模型开放开源吗？

**Comment by jklj077** [comment]
参见以下回复，感谢支持！

https://github.com/QwenLM/Qwen/issues/331#issuecomment-1733105546
