### ISSUE TITLE
[BUG] 我就想问“比赛中贡献”这五个字到底哪里违规了，7B的demo的prompt死活无法输出，这显然是LLM之外的人为设置吧

### ISSUE THREAD

**Issue by zmcmcc** [QwenLM/Qwen#338]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

。

### 期望行为 | Expected Behavior

。

### 复现方法 | Steps To Reproduce

。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

。

**Comment by changzhou-pku** [comment]
完整的prompt是啥？modelscope的demo对吧

**Comment by zmcmcc** [comment]
> 完整的prompt是啥？modelscope的demo对吧

一开始是一个长的prompt，后面经过我反复测试，你就只写“比赛中贡献”这几个字就error了

**Comment by zmcmcc** [comment]
> > 完整的prompt是啥？modelscope的demo对吧
> 
> 一开始是一个长的prompt，后面经过我反复测试，你就只写“比赛中贡献”这几个字就error了

对 modelscope的demo

**Comment by JianxinMa** [comment]
比赛 中贡 献

**Comment by zmcmcc** [comment]
> 比赛 中贡 献
无敌了呀。。。多少有点超级敏感了。其他国内模型好像也不至于这样
