### ISSUE TITLE
会有Qwen-VL 14B吗？

### ISSUE THREAD

**Issue by summerbuild** [QwenLM/Qwen#339]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如题

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by qnguyen3** [comment]
same question!

**Comment by lucasjinreal** [comment]
No

**Comment by JustinLin610** [comment]
Stay tuned!
