### ISSUE TITLE
💡 [REQUEST] - ollama 安装和api启动支持

### ISSUE THREAD

**Issue by EsqerYasen** [QwenLM/Qwen#344]
### 起始日期 | Start Date

09252023

### 摘要 | Summary

https://ollama.ai/library
加入https://ollama.ai/library ， 支持一键启动和调用接口。

### 基本示例 | Basic Example

curl -X POST http://localhost:11434/api/generate -d '{
  "model": "llama2-chinese:13b-chat-q4_0",
  "prompt":"写一个python程序？"
 }'

### 缺陷 | Drawbacks

curl -X POST http://localhost:11434/api/generate -d '{
  "model": "llama2-chinese:13b-chat-q4_0",
  "prompt":"写一个python程序？"
 }'

**Comment by jklj077** [comment]
With the latest launch of Qwen1.5, the `ollama` tool now officially extends its support to this new version. For in-depth discussions, troubleshooting, and further information regarding compatibility and usage with Qwen1.5, please visit the official GitHub repository at <https://github.com/QwenLM/Qwen1.5>.
