### ISSUE TITLE
[BUG] 配置环境、下载参数后，第一次可以正常运行，之后会报错ImportError

### ISSUE THREAD

**Issue by Maydaytyh** [QwenLM/Qwen#345]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

``` python
python cli_demo.py
```
会出现如下错误
![image](https://github.com/QwenLM/Qwen/assets/13815598/4f8063f3-f094-40a9-a779-1e2c33e2e040)

### 期望行为 | Expected Behavior

正常进入命令行交互

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04
- Python:3.8
- Transformers: 4.32.0
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by yuanzhibang-tool** [comment]
sampe error

**Comment by kanppa** [comment]
same error

**Comment by EternalFeather** [comment]
This project relies on the packages provided in its own kernels folder. You need to run the script in the Qwen-14B-XX directory.
![3D1A82E2-0B7A-4459-9DCE-1DAEFFA20FEC](https://github.com/QwenLM/Qwen/assets/22835797/36153c5f-6c5d-4629-b628-f33129a21a18)

**Comment by pihang** [comment]
> This project relies on the packages provided in its own kernels folder. You need to run the script in the Qwen-14B-XX directory. ![3D1A82E2-0B7A-4459-9DCE-1DAEFFA20FEC](https://user-images.githubusercontent.com/22835797/270519562-36153c5f-6c5d-4629-b628-f33129a21a18.jpg)
This kernels folder I ran the cpp_kernels.py file still can't work, how to run the script

**Comment by yangapku** [comment]
The issues has been solved during the update of HF model repo. Please pull the latest code and try again.
