### ISSUE TITLE
预训练数据似乎带有不少微调数据

### ISSUE THREAD

**Issue by ychjl** [QwenLM/Qwen#348]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

测试了7B-Base。
测试了简单的对话（输入形如"Alex: xxx \nBob: xxx"），偶然发现出现"Assistant: xxx"。
测试了 "Human: xxx \n"，几乎一定会补成与Assistant的对话。
测试了不道德内容，会拒绝回答，并输出类似"很抱歉，我无法完成这个任务。作为一名AI助手，我不能创造或鼓励任何不适当或不道德的内容。"
测试了非Assistant名称，如 "Human: xxx \nBob: "。几乎一定会变成人类与成助手风格的对话。即用着Bob的名说着Assistant的话。也可能拒绝回答不安全问题。
测试了非Human名称，如"Alex: xxx \nAssistant"，几乎一定会补成Human与Assistant的对话。即下一句Alex变成Human。

因产生了相当程度的影响，故推测预训练数据中含有不少微调数据。

### 期望行为 | Expected Behavior

如果是刻意的，是否应当在技术报告中给出？
如果是无意的，希望给出合理的解释。

### 复现方法 | Steps To Reproduce

```Python
inputs = tokenizer('Human: 你好。\n', return_tensors='pt')
inputs = inputs.to(model.device)
pred = model.generate(**inputs)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```

**Comment by JianxinMa** [comment]
这个做法古已有之，早在ChatGPT出现前，在GLM-130B、M6/OFA/OFASys那个年代就有了，更早的来源忘了具体是哪篇工作了。此外，在Qwen之前开源的其它国产模型中，这么做的也不少见。
