### ISSUE TITLE
qlora微调权重未初始化

### ISSUE THREAD

**Issue by yxk9810** [QwenLM/Qwen#351]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

arning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
^[[2;2R^[[2;2R^[[2;2R^[[2;2R^[[2;2R^[[2;2RSome weights of the model checkpoint at /root/.cache/modelscope/hub/qwen/Qwen-7B-Chat-Int4 were not used when initializing QWenLMHeadModel: ['transformer.h.25.attn.c_proj.qzeros', 'transformer.h.18.mlp.c_proj.qzeros', 'transformer.h.7.mlp.c_proj.qzeros', 'transformer.h.3.attn.c_attn.qzeros', 'transformer.h.24.mlp.w1.g_idx', 'transformer.h.19.attn.c_proj.g_idx', 'transformer.h.4.mlp.w1.scales', 'transformer.h.14.mlp.w2.qzeros', 'transformer.h.17.mlp.w2.g_idx', 'transformer.h.12.mlp.c_proj.qzeros', 'transformer.h.21.attn.c_attn.qzeros', 'transformer.h.9.attn.c_proj.qzeros', 'transformer.h.6.mlp.w1.qzeros', 'transformer.h.26.mlp.c_proj.qweight', 'transformer.h.10.mlp.w1.qzeros', 'transformer.h.22.mlp.w2.qzeros', 'transformer.h.21.mlp.w2.scales', 'transformer.h.2.attn.c_proj.scales', 'transformer.h.18.mlp.c_proj.bias', 'transformer.h.12.attn.c_proj.qzeros', 'transformer.h.22.mlp.w1.qzeros', 'transformer.h.2.mlp.w1.g_idx', 'transformer.h.20.mlp.w1.bias', 'transformer.h.11.mlp.w1.g_idx', 'transformer.h.21.mlp.c_proj.bias', 'transformer.h.27.mlp.c_proj.bias', 'transformer.h.8.mlp.w2.qzeros', 'transformer.h.6.mlp.w2.scales', 'transformer.h.27.mlp.w2.qweight', 'transformer.h.7.mlp.c_proj.bias', 'transformer.h.23.attn.c_proj.qweight', 'transformer.h.4.attn.c_attn.qweight', 'transformer.h.1.mlp.w1.g_idx', 'transformer.h.20.mlp.c_proj.qweight', 'transformer.h.31.mlp.c_proj.g_idx', 'transformer.h.20.attn.c_proj.g_idx', 'transformer.h.17.mlp.w1.bias', 'transformer.h.9.mlp.w2.scales', 'transformer.h.28.attn.c_proj.qweight', 'transformer.h.30.attn.c_proj.g_idx', 'transformer.h.10.mlp.w2.qweight', 'transformer.h.14.mlp.c_proj.qweight', 'transformer.h.6.mlp.c_proj.qzeros', 'transformer.h.30.mlp.w2.bias', 'transformer.h.11.attn.c_proj.g_idx', 'tra

### 复现方法 | Steps To Reproduce
python finetune.py \
  --model_name_or_path $MODEL \
  --data_path  train_qwen_0915.json \
  --eval_data_path dev_qwen_0915.json \
  --fp16 False \
  --output_dir output_qwen \
  --num_train_epochs 3 \
  --per_device_train_batch_size 1 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 4 \
  --evaluation_strategy "steps" \
  --save_strategy "steps" \
  --save_steps 10 \
  --save_total_limit 1 \
  --learning_rate 1e-5 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --report_to "none" \
  --model_max_length 768 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora \
  --q_lora

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.9.15
- Transformers:4.33.2
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by yxk9810** [comment]
补充：模型权重是使用modelscope下载的路径，把gptq的模型重新命名未model.safetensors

**Comment by JustinLin610** [comment]
确认下用的是不是最新模型，以及确认一下是不是用的int4模型。单卡qlora之前因为torch amp训练的原因会有问题，可以试下最新更新的脚本包括finetune.py

**Comment by yxk9810** [comment]
好的，我试试看
