### ISSUE TITLE
[BUG] fschat SFT微调loss 为0

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen#353]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

<img width="586" alt="image" src="https://github.com/QwenLM/Qwen/assets/21303438/c16f9864-1eb8-4422-9376-8dc82da2a91b">

### 期望行为 | Expected Behavior

正常loss

### 复现方法 | Steps To Reproduce

用fschat微调

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by kyriekevin** [comment]
参考项目的finetune.py代码，qwen数据预处理是特殊的，fastchat这部分不一样。
