### ISSUE TITLE
还是关于14B输出长度

### ISSUE THREAD

**Issue by WIKI2020** [QwenLM/Qwen#356]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

看到14B模型config.json的长度是2014，体验模型输出内容会被截断，那需要把这里修改成8K吗，还是怎样？看到那些Ntk也开启了

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by logicwong** [comment]
@WIKI2020 决定输出长度的是generation_config.json里的max_new_tokens参数，把它设置成合适的数值就行

**Comment by EricYangCn** [comment]
@logicwong 有时候我希望模型回答yes or no并不希望模型进行解释，这时候希望用max_new_tokens来控制输出的长度以提高效率。但是改变了max_new_tokens的设置后，比如在generation_config.json中改成了6，模型还是会有时给出很长的解释，貌似这个参数不起作用啊。但从transformer的文档来看，这个参数应该可以控制输出长度，这是为什么呢？如何强制模型不要超过max_new_tokens所规定的长度呢?

**Comment by EricYangCn** [comment]
简单地说就是希望强制截断但强制截断没有发生。
