### ISSUE TITLE
部署Qwen-14B-Chat-Int4，推理时GPU几乎不工作，CPU小量工作就输出了，这种情况是性能冗余吗？那么能否加速推理的速度？如何做？

### ISSUE THREAD

**Issue by gbfansheng** [QwenLM/Qwen#362]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

部署最新版本的Qwen-14B-Chat-Int4，推理时GPU几乎不工作，CPU小量工作就输出了回答，为什么？
如图：
CPU: Core(TM) i7-13700KF 
GPU: 4090 24G
![image](https://github.com/QwenLM/Qwen/assets/8793065/ac96d7e4-800b-4c94-8d8a-553a4221e0e3)
这种情况是性能冗余吗？那么能否加速推理的速度？如何做？

### 运行环境 | Environment

```Markdown
- OS: Windows
- Python: 3.10
- Transformers: 4.32.1
- PyTorch: 2.0.1+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

**Comment by jklj077** [comment]
关于性能监控：Windows上的GPU性能监视默认视图不包含CUDA。可以点击任意一项指标，比如Video Encode，在弹出的下拉列表中选择CUDA（或者其它感兴趣的指标项），再观察看下。

![image](https://github.com/QwenLM/Qwen/assets/17811943/3d5855f8-762f-4b6b-ac8c-54430efbbf5f)
