### ISSUE TITLE
如何进行批量推理？

### ISSUE THREAD

**Issue by yorhaha** [QwenLM/Qwen#365]
显存足够的情况下，希望将一个 batch 的 instruction 批量输入 Chat 模型进行计算，请问能否实现？

**Comment by jklj077** [comment]
请参考 https://github.com/QwenLM/Qwen/issues/159#issuecomment-1727139620

**Comment by yorhaha** [comment]
感谢。但我已经放弃使用批量推理了，单卡逐个推理的速度已经能满足我的需求了。

另外，在有多卡可用时，逐个推理的速度会下降很多，Qwen 是自动把模型拆分到多卡了吧？

**Comment by logicwong** [comment]
@yorhaha 这个是transformers内部的操作，当device_map="auto"时它会把模型拆到多张卡上

**Comment by yorhaha** [comment]
谢谢！
