### ISSUE TITLE
[BUG] finetune_qlora_ds.sh 看起来需要明确 auto_gptq 版本

### ISSUE THREAD

**Issue by tpoisonooo** [QwenLM/Qwen#368]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

# 概述
运行 `finetune_qlora_ds.sh` 报错，修了一个还有一个。不想修了直接发 issue 

## 第一个报错: 没给 tokenizer 
```bash
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 298, in quantize_model
    tokenizer = AutoTokenizer.from_pretrained(tokenizer)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/GitProjects/Qwen/finetune.py", line 353, in <module>
    train()
  File "/workspace/GitProjects/Qwen/finetune.py", line 294, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 300, in quantize_model
    raise ValueError(
ValueError: We were not able to get the tokenizer using `AutoTokenizer.from_pretrained`
                    with the string that you have passed /models/Qwen-14B-Chat/. If you have a custom tokenizer, you can pass it as input.
                    For now, we only support quantization for text model. Support for vision, speech and multimodel will come later.
```
修复方式：
先load tokenizer 再 assign 给 gptq 参数

## 第二个报错: 没提供 dataset
```bash
Traceback (most recent call last):
  File "/workspace/GitProjects/Qwen/finetune.py", line 355, in <module>
    train()
  File "/workspace/GitProjects/Qwen/finetune.py", line 304, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 306, in quantize_model
    raise ValueError("You need to pass `dataset` in order to quantize your model")
ValueError: You need to pass `dataset` in order to quantize your model
```

## 怀疑
你们肯定是测过的，所以大概率是版本没对齐。 所以需要大佬提供你们测试用的 auto_gptq 的版本

我用的版本
```bash
auto_gptq-0.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

### 期望行为 | Expected Behavior

能正确 qlora 训练。

### 运行环境 | Environment

```Markdown
- OS: ubuntu20.04 docker 
- Python: 3.10
- Transformers: transformers==4.32.0 和 requirements.txt 一致
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):  11.7
```

**Comment by Xccanxin** [comment]
同样的版本，同样的问题

**Comment by JustinLin610** [comment]
版本是ok的，问题是qlora需要load int4的模型，不能load非量化的模型。

qlora分布式ok的，但此前单卡用torch的amp训练有问题。建议大家更新最近更新的单卡qlora微调脚本，包括finetune.py，目前已经解决单卡qlora报错的问题。另外，相关训练的显存占用和训练速度也已经给出

**Comment by zhangd732** [comment]
我将模型文件下载到本地，用tokenizer = AutoTokenizer.from_pretrained(YOURPATH, local_files_only=True)加载tokenizer，报错：Tokenizer class QWenTokenizer does not exist or is not currently imported.

**Comment by zhangd732** [comment]
> 我将模型文件下载到本地，用tokenizer = AutoTokenizer.from_pretrained(YOURPATH, local_files_only=True)加载tokenizer，报错：Tokenizer class QWenTokenizer does not exist or is not currently imported.

应该是transformers不支持Qwen现在

**Comment by jklj077** [comment]
> 应该是transformers不支持Qwen现在

嗯，这个需要trust_remote_code=True，即使是用本地文件，因为导入了外源代码，也需要这样设置。

**Comment by zhangd732** [comment]
> > 应该是transformers不支持Qwen现在
> 
> 嗯，这个需要trust_remote_code=True，即使是用本地文件，因为导入了外源代码，也需要这样设置。

嗯呢，谢谢，问题解决了( •̀ ω •́ )y

**Comment by ZHANGJINKUI** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> # 概述
> 运行 `finetune_qlora_ds.sh` 报错，修了一个还有一个。不想修了直接发 issue
> 
> ## 第一个报错: 没给 tokenizer
> ```shell
> Traceback (most recent call last):
>   File "/root/miniconda3/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 298, in quantize_model
>     tokenizer = AutoTokenizer.from_pretrained(tokenizer)
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
>     raise ValueError(
> ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/workspace/GitProjects/Qwen/finetune.py", line 353, in <module>
>     train()
>   File "/workspace/GitProjects/Qwen/finetune.py", line 294, in train
>     model = transformers.AutoModelForCausalLM.from_pretrained(
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
>     return model_class.from_pretrained(
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
>     quantizer.quantize_model(model, quantization_config.tokenizer)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 300, in quantize_model
>     raise ValueError(
> ValueError: We were not able to get the tokenizer using `AutoTokenizer.from_pretrained`
>                     with the string that you have passed /models/Qwen-14B-Chat/. If you have a custom tokenizer, you can pass it as input.
>                     For now, we only support quantization for text model. Support for vision, speech and multimodel will come later.
> ```
> 
> 修复方式： 先load tokenizer 再 assign 给 gptq 参数
> 
> ## 第二个报错: 没提供 dataset
> ```shell
> Traceback (most recent call last):
>   File "/workspace/GitProjects/Qwen/finetune.py", line 355, in <module>
>     train()
>   File "/workspace/GitProjects/Qwen/finetune.py", line 304, in train
>     model = transformers.AutoModelForCausalLM.from_pretrained(
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
>     return model_class.from_pretrained(
>   File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
>     quantizer.quantize_model(model, quantization_config.tokenizer)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 306, in quantize_model
>     raise ValueError("You need to pass `dataset` in order to quantize your model")
> ValueError: You need to pass `dataset` in order to quantize your model
> ```
> 
> ## 怀疑
> 你们肯定是测过的，所以大概率是版本没对齐。 所以需要大佬提供你们测试用的 auto_gptq 的版本
> 
> 我用的版本
> 
> ```shell
> auto_gptq-0.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> ```
> 
> ### 期望行为 | Expected Behavior
> 能正确 qlora 训练。
> 
> ### 复现方法 | Steps To Reproduce
> _No response_
> 
> ### 运行环境 | Environment
> ```
> - OS: ubuntu20.04 docker 
> - Python: 3.10
> - Transformers: transformers==4.32.0 和 requirements.txt 一致
> - PyTorch: 2.0.1
> - CUDA (`python -c 'import torch; print(torch.version.cuda)'`):  11.7
> ```

请问一下，第一个问题怎么解决的呀，怎么load tokenizer呀， 再 assign 给 gptq 参数？
