### ISSUE TITLE
关于kv cache开启问题，请问可以单独设置use_cache_kernel=True，use_cache_quantization=False

### ISSUE THREAD

**Issue by cgq0816** [QwenLM/Qwen#369]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

提供use_cache_quantization以及use_cache_kernel两个参数对模型控制，当use_cache_quantization以及use_cache_kernel均开启时，将启动kv-cache量化的功能。具体使用如下：

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen-7B-Chat",
     device_map="auto",
     trust_remote_code=True,
     use_cache_quantization=True,
     use_cache_kernel=True,
     use_flash_attn=False
)
注意：当前该功能目前不支持与flash attn同时开启，如果你开了kv cache量化的同时又开了flash attn（use_flash_attn=True， use_cache_quantization=True, use_cache_kernel=True），会默认将use_flash_attn关闭。

### 期望行为 | Expected Behavior

期望单独使用use_cache_kernel=True
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen-7B-Chat",
     device_map="auto",
     trust_remote_code=True,
     use_cache_quantization=False,
     use_cache_kernel=True,
     use_flash_attn=False
)
 或者use_cache_kernel=True ， use_flash_attn=True 
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen-7B-Chat",
     device_map="auto",
     trust_remote_code=True,
     use_cache_quantization=False,
     use_cache_kernel=True,
     use_flash_attn=True
)
从而使用多个方式来提高推理性能，请问可以这样使用吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ZhangJianwei0311** [comment]
你好，

你提到的问题，这里面大体上涉及三个参数：use_cache_quantization、use_cache_kernel、use_flash_attn。

1.你说的第一个选项，use_cache_quantization=false，这个参数是控制是否在模型推理上开启kv cache量化，如果你指定成false，那就不会进行kv cache量化了。use_cache_kernel可以指定为false，程序就通过python func的手段进行kv cache量化反量化的逻辑。
2.你说的第二个选项，use_cache_quantization=true（这个必须指定为true，原因见第一点），并且use_flash_attn=true，这个涉及到把kv cache量化的逻辑写到flash attn里，这个暂时还未开发，所以暂时不支持。
