### ISSUE TITLE
[BUG] Qwen 14B Finetuning -> RuntimeError: The size of tensor a (1480) must match the size of tensor b (2048) at non-singleton dimension 1

### ISSUE THREAD

**Issue by queue-min** [QwenLM/Qwen#370]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Thanks for providing wonderful Language model for study 😄 

I got an RuntimeError when I run the training code. 
All the error message is as follows.

Traceback (most recent call last):
  File "/data/di-LLM_458/queue.min/Project/qwen/qwen_14b_finetuning_hf.py", line 74, in <module>
    trainer.train()
  File "/home/bc-user/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/bc-user/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2682, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2707, in compute_loss
    outputs = model(**inputs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bc-user/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 1110, in forward
    transformer_outputs = self.transformer(
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 919, in forward
    outputs = torch.utils.checkpoint.checkpoint(
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/bc-user/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 915, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/home/bc-user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bc-user/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 647, in forward
    layernorm_input = attn_output + residual
RuntimeError: The size of tensor a (1480) must match the size of tensor b (2048) at non-singleton dimension 1

### 期望行为 | Expected Behavior

When I run Qwen-7B model with the same training code and dataset, it is trained very well. 
I expected Qwen-14B works as same as Qwen-7B

### 复现方法 | Steps To Reproduce

I customized the data processing code and training code. The data preprocessing and Training code is as follows. 
The all the elements of preprocessed data have size of 2048. 

### Preprocessing code
```python
import torch
import transformers
from transformers import AutoTokenizer
from transformers.trainer_pt_utils import LabelSmoother

from pathlib import Path
import os
import sys
import datasets
import copy
import tqdm

model_id="/data/di-LLM_458/models/Qwen-14B"
max_words = 2048

tokenizer = transformers.AutoTokenizer.from_pretrained(
        model_id,
        model_max_length=max_words,
        padding_side="right",
        use_fast=False,
        trust_remote_code=True,
    )

tokenizer.pad_token_id = tokenizer.eod_id
IGNORE_TOKEN_ID = LabelSmoother.ignore_index

dataset_train = datasets.load_dataset("data-intelligence/news_qa_ko", split='train', delimiter='\t')
dataset_val = datasets.load_dataset("data-intelligence/news_qa_ko", split='validation', delimiter='\t')

PROMPT_template = "다음 문서의 내용을 참고하여 질문에 대한 알맞은 응답을 해주세요.\n### 문서:\n{document}\n\n### 질문:\n{question}\n\n### 응답:\n"

def preprocess(sources):
    roles = {"document": "<|im_start|>document", "question": "<|im_start|>question", "answer": "<|im_start|>answer"}

    im_start = tokenizer.im_start_id
    im_end = tokenizer.im_end_id
    nl_tokens = tokenizer('\n').input_ids
    
    # Apply prompt templates
    input_ids, targets, attention_masks = [], [], []

    system_message = "다음 문서의 내용을 참고하여 질문에 대한 알맞은 응답을 해주세요."
    system = [im_start] + tokenizer(system_message).input_ids + [im_end] + nl_tokens
    
    for i in range(len(sources['document'])):  
        input_id, target = [], []
        
        _input_id = system + \
                    tokenizer(roles['document']).input_ids + nl_tokens + tokenizer(sources['document'][i]).input_ids + [im_end] + nl_tokens + \
                    tokenizer(roles['question']).input_ids + nl_tokens + tokenizer(sources['question'][i]).input_ids + [im_end] + nl_tokens + \
                    tokenizer(roles['answer']).input_ids + nl_tokens

        input_id += _input_id + tokenizer(sources['answer'][i]).input_ids + [im_end] + nl_tokens
        
        _target = copy.deepcopy(input_id)
        _target[:len(_input_id)] = [IGNORE_TOKEN_ID] * len(_input_id)

        target = _target

        input_id += [tokenizer.pad_token_id] * (max_words - len(input_id))
        target += [IGNORE_TOKEN_ID] * (max_words - len(target))

        input_id = torch.tensor(input_id[:max_words])
        target = torch.tensor(target[:max_words])
        mask = input_id.ne(tokenizer.pad_token_id)
        
        input_ids.append(input_id)
        targets.append(target)
        attention_masks.append(mask)

    return {
        "input_ids": input_ids,
        "labels": targets,
        "attention_mask":attention_masks,
    }

    return dict(
        input_ids=input_ids,
        labels=targets,
        attention_mask=input_ids.ne(tokenizer.pad_token_id),
    )

train_dataset = dataset_train.map(preprocess, remove_columns=list(dataset_train.features), batched=True)
val_dataset = dataset_val.map(preprocess, remove_columns=list(dataset_val.features), batched=True)

train_dataset.save_to_disk('saved_datasets/news_qa/train/')
val_dataset.save_to_disk('saved_datasets/news_qa/validation/')
```

### Training code 
```python
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
import datasets
import torch
import numpy as np 
import random 
from tqdm import tqdm 

model_id="/data/di-LLM_458/models/Qwen-14B"

train_data_dir = "./saved_datasets/news_qa/train"
eval_data_dir = "./saved_datasets/news_qa/validation"

out_dir= "./saved_models/news_qa_14b"

tokenizer_max_len = 2048 

n_gpus = 2
log_step = 200
save_step = 500

max_memory = f'{81920}MB'

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    low_cpu_mem_usage=True,
    device_map="auto", # dispatch efficiently the model on the available ressources
    max_memory = {i: max_memory for i in range(n_gpus)},
    trust_remote_code=True,
)

tokenizer = AutoTokenizer.from_pretrained(
    model_id,
    model_max_length=tokenizer_max_len,
    padding_side="right",
    use_fast=False,
    trust_remote_code=True,
)

tokenizer.pad_token_id = tokenizer.eod_id

dataset_train = datasets.load_from_disk(train_data_dir)
dataset_test = datasets.load_from_disk(eval_data_dir)

training_args = TrainingArguments(output_dir=out_dir,     
                                  evaluation_strategy="steps", 
                                  eval_steps = log_step,
                                  per_device_train_batch_size=8,
                                  per_device_eval_batch_size=2,
                                  num_train_epochs=5,
                                  logging_steps=log_step,
                                  save_steps=save_step,
                                  report_to="tensorboard",
                                  lr_scheduler_type="cosine",
                                  warmup_ratio=0.01,
                                  save_total_limit = 2,
                                  gradient_accumulation_steps=4, 
                                  gradient_checkpointing=True,
                                  bf16=True,
                                  optim="adafactor",
                                  dataloader_num_workers=8,
                                  )

trainer = Trainer(
    model,
    training_args,
    train_dataset=dataset_train,
    eval_dataset=dataset_test,
    tokenizer=tokenizer,
)

trainer.train()
trainer.save_model(out_dir)
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04.5 LTS 
- Python: 3.10.11
- Transformers: 4.32.0
- PyTorch: 2.0.1+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8

Also, I installed flash_attn, flash_attn rotaty and rms_norm
```

**Comment by kyriekevin** [comment]
+1

**Comment by queue-min** [comment]
@MRKINKI 
The previous model you mentioned is the 7B model? or is it the 14B model?

**Comment by MRKINKI** [comment]
> @MRKINKI The previous model you mentioned is the 7B model? or is it the 14B model?

I have this problem with both of them

**Comment by queue-min** [comment]
This problem is solved by using the latest model! :)

**Comment by ldong1111** [comment]
> This problem is solved by using the latest model! :)

Hi, what does this mean?
