### ISSUE TITLE
为啥学科能力这么强。

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen#374]
### 实现PR | Implementation PR

1

### 相关Issues | Reference Issues

1

### 摘要 | Summary

![image](https://github.com/QwenLM/Qwen/assets/15667364/e110df14-123f-4d6d-b356-99367c91872f)
为啥学科能力这么强，主要和下面的差距过大。有谁能解释解释。

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

### 未解决问题 | Unresolved questions

1

**Comment by wellcasa** [comment]
https://opencompass.org.cn/leaderboard-llm

**Comment by Losin** [comment]
和数据的质量、规模、领域的多样性都有关系
