### ISSUE TITLE
量化int4版本 OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory 

### ISSUE THREAD

**Issue by jingzl** [QwenLM/Qwen#375]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用最新的代码，并下载了modelscope上最新了模型文件，载入Qwen-7B-Chat，正常。
但载入 Qwen-7B-Chat-Int4时，报错：
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory  G:\Qwen-7B-Chat-Int4.
已参考readme文件，安装 auto-gptq optimum。
使用 web_demo.py 和 cli_demo.py 均报错。
查看模型文件，只有一个 gptq_model-4bit-128g.safetensors，没有报错提示中的 bin 等文件。

### 运行环境 | Environment

```Markdown
- OS: Windows 10 企业版 22H2
- Python: 3.8.18
- Transformers: 4.32.0
- PyTorch: 2.0.1+cu117
- CUDA: 11.7
```

**Comment by jingzl** [comment]
谢谢，兄弟，你真快

**Comment by jingzl** [comment]
更新最新的模型文件，问题解决了

**Comment by MAIMAIBO** [comment]
> 更新最新的模型文件，问题解决了

解决模型文件后有遇到这个问题么？
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-Int4/modeling_qwen.py", line 209, in forward
    assert seqlen_k == seqlen_q
AssertionError

**Comment by MAIMAIBO** [comment]
> 更新最新的模型文件，问题解决了

成功微调了？
我遇到个问题：
File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-Int4/modeling_qwen.py", line 209, in forward
    assert seqlen_k == seqlen_q
AssertionError
大佬遇到过么？

**Comment by jingzl** [comment]
> > 更新最新的模型文件，问题解决了
> 
> 成功微调了？ 我遇到个问题： File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-Int4/modeling_qwen.py", line 209, in forward assert seqlen_k == seqlen_q AssertionError 大佬遇到过么？

我没有微调，不过你可以看一下HF上是否是刚更新的版本，我是从MS上下载的，今天官方刚更新了模型相关文件。你可以下载了对比一下。

**Comment by chenhongwu127** [comment]
**微调qwen_14B成功后，运行模型文件报错：**
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/alg/AI/qwen_14B/Qwen-main/output_qwen.
请教各位大佬们~~

**Comment by jingzl** [comment]
你这个就是模型文件的问题，你下载最新的模型试试

**Comment by cheng18175030250** [comment]
> 更新最新的模型文件，问题解决了

请问如何在魔搭社区中更新

**Comment by Qinger27** [comment]
报错的这些文件只需要下载一个就行吗？还是都需要下载呀？
