### ISSUE TITLE
[BUG] qwen-7b-chat-int4微调报错assert seqlen_k == seqlen_q

### ISSUE THREAD

**Issue by MAIMAIBO** [QwenLM/Qwen#376]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在对qwen-7b-chat-int4进行微调时报错：
 File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-Int4/modeling_qwen.py", line 209, in forward
    assert seqlen_k == seqlen_q
AssertionError

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04.6
- Python:3.8
- Transformers:4.33.2
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by studyhardstudyhard** [comment]
可以拉最新的代码

**Comment by MAIMAIBO** [comment]
> 可以拉最新的代码

已经是最新的了

**Comment by logicwong** [comment]
20分钟前刚刚更新了代码，请确运行的是最新代码而不是cache里的代码。

**Comment by greatzane** [comment]
huggingface上更新了，但是modelscope上没更新

**Comment by MAIMAIBO** [comment]
> 20分钟前刚刚更新了代码，请确运行的是最新代码而不是cache里的代码。

拉取的魔塔上最新的模型，

> huggingface上更新了，但是modelscope上没更新

嗯嗯，去huggingface上手动拉了下，问题已解决。
