### ISSUE TITLE
[BUG] wed demo无法显示返回过来的结果

### ISSUE THREAD

**Issue by sec4115** [QwenLM/Qwen#377]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/7736109/4bcd555b-260c-4b01-8a93-f159db262821)
![image](https://github.com/QwenLM/Qwen/assets/7736109/958e7097-8e37-4a9a-9e4c-414e899daad5)
输入之后，返回的文字无法在页面上显示，但是在控制台是有返回数据的

### 期望行为 | Expected Behavior

期望输入提示词之后，页面可以正常显示返回结果

### 复现方法 | Steps To Reproduce

在Input框中输入“你好”
点击submit按钮

### 运行环境 | Environment

```Markdown
- OS: windows 11 专业版
- Python: 3.9
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by thb10086** [comment]
同问+1

**Comment by nimo12138** [comment]
> 同问+1

+1

**Comment by samchugit** [comment]
安装依赖的时候 `requirements_web_demo.txt` 没有指定 gradio 版本，默认安装最新版，接口发生了改变，降低 gradio 版本就可以了。使用 `pip install gradio==3.41.0` 测试可行。

**Comment by jklj077** [comment]
requirements_web_demo.txt已更新了，感谢指出！
