### ISSUE TITLE
💡 [REQUEST] - Openai API how to stop streaming from client?

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen#382]
### 摘要 | Summary

例如客户端点击 停止生成，服务端便停止streaming

### 基本示例 | Basic Example

例如客户端点击 停止生成，服务端便停止streaming

### 缺陷 | Drawbacks

如何停止streaming

**Comment by JianxinMa** [comment]
openai_api.py 使用的协议是 server-sent event（sse），这是个单向的协议（只能从server发消息到client，不能从client发消息给server）。要实现的话得把sse换成websockets。实际上，真正的生产环境下服务端停止生成能节省的资源并不多，因为有组batch等因素。

**Comment by lucasjinreal** [comment]
目前只能单向客户端断开链接吗
