### ISSUE TITLE
如何在Guidance工具中使用chat模型

### ISSUE THREAD

**Issue by cnlnpjhsy** [QwenLM/Qwen#383]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

从Huggingface中下载了[Qwen-7B-Chat-Int4](https://huggingface.co/Qwen/Qwen-7B-Chat-Int4)之后部署到本地，直接使用transformers库可以正常地推理。目前我希望在[Guidance](https://github.com/guidance-ai/guidance)中使用这个模型，但似乎Guidance不能很好地提供支持。

代码：
```python
import guidance
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("/mnt/lustre/sjtu/home/syh25/PretrainedModels/Qwen-7B-Chat-Int4", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("/mnt/lustre/sjtu/home/syh25/PretrainedModels/Qwen-7B-Chat-Int4", device_map="cuda", trust_remote_code=True).eval()
qwen = guidance.llms.Transformers(model=model, tokenizer=tokenizer, device="cuda")
guidance.llm = qwen

tester = guidance("This is a test guidance. My name is {{name}}, your name is {{gen 'ans'}}.")
tester(name="Hedda")
```

输出的错误log：
```
Using eos_token, but it is not set yet.
Traceback (most recent call last):
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/_program_executor.py", line 109, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/_program_executor.py", line 266, in visit
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/_program_executor.py", line 266, in <listcomp>
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/_program_executor.py", line 379, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/library/_gen.py", line 140, in gen
    gen_obj = await parser.llm_session(
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/guidance/llms/_transformers.py", line 202, in __call__
    stop_regex.append(regex.escape(self.llm.tokenizer.eos_token)) # make sure the end of sequence token is always included
  File "/mnt/lustre/sjtu/home/syh25/.conda/envs/llm/lib/python3.9/site-packages/regex/regex.py", line 389, in escape
    for c in p:
TypeError: 'NoneType' object is not iterable

Error in program:  'NoneType' object is not iterable
This is a test guidance. My name is {{name}}, your name is {{gen 'ans'}}.
```

请问目前Qwen支持Guidance工具的调用吗？如果支持的话又应该如何正确使用？

### 运行环境 | Environment

```Markdown
- OS: Linux SMP
- Python: 3.9
- Transformers: 4.32.0
- PyTorch: 2.0.1+cu117
- CUDA: 11.7
- guidance: 0.0.64
```

### 备注 | Anything else?

README里提到了可以使用OpenAI API风格对模型进行调用。搭配上guidance对OpenAI模型的支持，也许可以解决这个问题，但我暂时还没有尝试~

**Comment by JustinLin610** [comment]
我个人没使用过guidance这个工具，我们测试下看看问题在哪

**Comment by jklj077** [comment]
@cnlnpjhsy guidance似乎主要支持的generation类接口的（好像也有提支持chat类接口）。它会强制添加`tokenizer.eos_token`做字符串级别的识别，error log也有提示：
```
Using eos_token, but it is not set yet.
```

在这个用例中，请尝试配置一下eos_token。
- 对于Chat模型，请使用`<|im_end|>`
  ```python
  tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True, eos_token="<|im_end|>")
  ```
- 对于非Chat模型，请使用`<|endoftext|>`
  ```python
  tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True, eos_token="<|endoftext|>")
  ```

同时，由于guidance在做token解码时是增量式的，且无法传入参数；您还需要修改tokenizer的errors参数：
```python
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True, eos_token=EOS_TOKEN, errors="ignore")
```
这些是tokenizer方面涉及的适配操作。如果其它问题，欢迎提问！

**Comment by felixstander** [comment]
> @cnlnpjhsy guidance似乎主要支持的generation类接口的（好像也有提支持chat类接口）。它会强制添加`tokenizer.eos_token`做字符串级别的识别，error log也有提示：
> 
> ```
> Using eos_token, but it is not set yet.
> ```
> 
> 在这个用例中，请尝试配置一下eos_token。
> 
> * 对于Chat模型，请使用`<|im_end|>`
>   ```python
>   tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True, eos_token="<|im_end|>")
>   ```
> * 对于非Chat模型，请使用`<|endoftext|>`
>   ```python
>   tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True, eos_token="<|endoftext|>")
>   ```
> 
> 同时，由于guidance在做token解码时是增量式的，且无法传入参数；您还需要修改tokenizer的errors参数：
> 
> ```python
> tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True, eos_token=EOS_TOKEN, errors="ignore")
> ```
> 
> 这些是tokenizer方面涉及的适配操作。如果其它问题，欢迎提问！
@jklj077 
prfix_str = token_str + prefix_str 
TypeError : can't concat str to bytes
Error in program: can't concat str to bytes
请问出现该报错是什么原因呢？

**Comment by jklj077** [comment]
guidance目前的Token healing实现不兼容QWenTokenizer哈，这个您可以关闭token healing吗？

**Comment by felixstander** [comment]
> guidance目前的Token healing实现不兼容QWenTokenizer哈，这个您可以关闭token healing吗？

@jklj077 是可以的感谢！然后还有就是qwen的generation config是不包括temperature这个参数的，所以如果开do_sample=True的话，gen部分必须加temperature,不然会报错。

**Comment by JianxinMa** [comment]
> guidance目前的Token healing实现不兼容QWenTokenizer哈，这个您可以关闭token healing吗？

@jklj077 请问这个token healing支持难度大吗？
