### ISSUE TITLE
qlora_finetune 直接被killed

### ISSUE THREAD

**Issue by DuBaiSheng** [QwenLM/Qwen#384]
用14B-int4自己微调的时候，也没明显的报错，直接被killed了。finetune/finetune_qlora_single_gpu.sh: line 39: 2810536 Killed。有大神遇到同样的问题吗？

**Comment by sinan106** [comment]
+1 我也是

**Comment by YFCHEN-LEEDS** [comment]
是内存不足导致的，但int4微调好像还有其他问题，你如果能调了可以教我下吗？

**Comment by jinqiupeter** [comment]
就是内存不足导致的，qlora和lora微调14B需要大约70G 内存。Linux上可以通过调大swap分区来解决

**Comment by JustinLin610** [comment]
建议大家更新最近更新的单卡qlora微调脚本，包括finetune.py，目前已经解决单卡qlora报错的问题。另外，相关训练的显存占用和训练速度也已经给出

**Comment by DuBaiSheng** [comment]
> 建议大家更新最近更新的单卡qlora微调脚本，包括finetune.py，目前已经解决单卡qlora报错的问题。另外，相关训练的显存占用和训练速度也已经给出

重新下载了代码和7B-int4的模型，q_lora的时候，又出现了 AttributeError: 'DummyOptim' object has no attribute 'step' 这个问题。

**Comment by jklj077** [comment]
@DuBaiSheng 请问目前QLoRA仍有问题吗，如问题仍存在，可否提供更多的信息，比如软件版本等。

**Comment by jklj077** [comment]
AttributeError: 'DummyOptim' object has no attribute 'step' 与accelerate和deepspeed的版本兼容性有关，建议进行更新看看。

**Comment by DuBaiSheng** [comment]
> @DuBaiSheng 请问目前QLoRA仍有问题吗，如问题仍存在，可否提供更多的信息，比如软件版本等。

有问题，这个问题一直没解决 ，https://github.com/QwenLM/Qwen/issues/465
