### ISSUE TITLE
能否将openai_api.py修改为定义模型而不是加载模型？

### ISSUE THREAD

**Issue by ye7love7** [QwenLM/Qwen#389]
已经用fastchat启动了openai接口，这个项目的openai_api能否使用定义模型的方式，而不是加载模型。
model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
    ).eval()
    model.generation_config = GenerationConfig.from_pretrained(
        args.checkpoint_path,
        trust_remote_code=True,
        resume_download=True,
    )
能否修改为定义模型，而非加载模型？

**Comment by ye7love7** [comment]
求大佬解答~

**Comment by JianxinMa** [comment]
请问“已经用fastchat启动了openai接口“，那为什么还需要用到这个项目下的openai_api.py呢？

**Comment by ye7love7** [comment]
这个项目有function_call，fastchat没有做



---原始邮件---
发件人: "Jianxin ***@***.***&gt;
发送时间: 2023年10月6日(周五) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen] 能否将openai_api.py修改为定义模型而不是加载模型？ (Issue #389)




 
请问“已经用fastchat启动了openai接口“，那为什么还需要用到这个项目下的openai_api.py呢？
