### ISSUE TITLE
Inducing another language

### ISSUE THREAD

**Issue by Tejaswgupta** [QwenLM/Qwen#390]
I've been using Qwen-14B for quite some time now and the reasoning and other capabilities are really great. However , I'd like to induce Hindi(and other languages) knowledge into the model. Which approach would be better Continued fine-tuning or Supervised fine-tuning. Also , what size of dataset would be required to have the model function correctly.

Thank you for your response.

**Comment by JustinLin610** [comment]
I think it might be a little bit hard to directly transfer to hindi, but for the first step, I advise you to use SFT first to see how far its performance is from your expectation and then consider trying continued pretraining. No answer for sure about the size, but I guess billions of tokens might be necessary.

**Comment by jklj077** [comment]
For reference, there are Qwen-based model for Japanese and Vietnamese on HuggingFace Hub, e.g., <https://huggingface.co/rinna/nekomata-14b>. I think it suggests Qwen can serve as a good starting point. If you made progress on this, we are happy to hear from you!
