### ISSUE TITLE
💡 [REQUEST] - <title>请问，ReAct Prompting只能使用英文吗？

### ISSUE THREAD

**Issue by jinghai** [QwenLM/Qwen#391]
### 摘要 | Summary

请问，ReAct Prompting只能使用英文吗？

### 基本示例 | Basic Example

请问，ReAct Prompting只能使用英文吗？

### 缺陷 | Drawbacks

请问，ReAct Prompting只能使用英文吗？

**Comment by JianxinMa** [comment]
中文也可以的，把那个prompt模板翻译成中文，一般也能走通的。
