### ISSUE TITLE
[BUG] 在进行Qwen-14B量化int8时报错

### ISSUE THREAD

**Issue by iaoxuesheng** [QwenLM/Qwen#392]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

可以运行，但是一提问就报错。
![微信截图_20231004180231](https://github.com/QwenLM/Qwen/assets/94165844/128dd6a1-9eb5-4c19-901d-7ef42280fa81)

### 运行环境 | Environment

```Markdown
- OS:windows 10
- Python:3.9
- Transformers:4.32与4.33都试过了
- PyTorch:1.13.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by Coder-nlper** [comment]
gptq量化的，使用gptq自带的API加载是可以的。使用transformers加载就会报这个错误
