### ISSUE TITLE
[BUG] web界面没反应，但是在命令行可以看到

### ISSUE THREAD

**Issue by iaoxuesheng** [QwenLM/Qwen#393]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![1](https://github.com/QwenLM/Qwen/assets/94165844/1fe8a581-22ae-49f9-9e8f-3cd6df99c30f)

### 运行环境 | Environment

```Markdown
- OS:win10
- Python:3.9
- Transformers:4.33
- PyTorch:1.13.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by iaoxuesheng** [comment]
解决了

**Comment by hhk123** [comment]
咋解决的？

**Comment by iaoxuesheng** [comment]
> 咋解决的？
时间有点久，好像是降级gradio
