### ISSUE TITLE
[BUG]  token more than 5k, the answer is incorrect

### ISSUE THREAD

**Issue by allenhaozi** [QwenLM/Qwen#398]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Do summary answer, token more than 5k, the answer is incorrect

### 复现方法 | Steps To Reproduce

use vllm and token more thank 5k

### 运行环境 | Environment

```Markdown
vllm + qwen-7b-chat
```

**Comment by logicwong** [comment]
Check out this answer
https://github.com/vllm-project/vllm/issues/809#issuecomment-1692672354

**Comment by allenhaozi** [comment]
> Check out this answer [vllm-project/vllm#809 (comment)](https://github.com/vllm-project/vllm/issues/809#issuecomment-1692672354)

@logicwong  according to the [Quickstart](https://huggingface.co/Qwen/Qwen-7B-Chat#%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8%EF%BC%88quickstart%EF%BC%89) long text effect is also not good.

Any suggestions? I see use_dynamc_ntk is already enabled by default

**Comment by allenhaozi** [comment]
@logicwong @yangapku @LiuXiaoxuanPKU

There are some differences between [qwen-ntk-alpha-generate](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py#L779) and [vllm-ntk-alpha-generate](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/rotary_embedding.py#L158)
 in generating ntk_alpha

 if I want vllm to support qwen's long chat. How to modify it? thank you

**Comment by lucasjinreal** [comment]
it's not supported.

**Comment by JustinLin610** [comment]
Not supported. Hard for vllm to adapt to our dynamic NTK

**Comment by Bowen-n** [comment]
It seems that @allenhaozi has already implemented Qwen's dynamic-NTK in vllm, check [here](https://github.com/allenhaozi/vllm/blob/a1b8bee922196367123d96ef0e9b4c9ae3333302/vllm/model_executor/layers/rotary_embedding.py#L213C16-L213C16).

I'm wondering why it is hard for vllm to adapt to dynamic-NTK. Is there any details the above implementation missing?
