### ISSUE TITLE
SentencePiece词表合并问题

### ISSUE THREAD

**Issue by zetian1025** [QwenLM/Qwen#399]
请问可以公开merge词表部分的代码吗？

另外，在我自己将sentencepiece bpe训得的词表merge到tiktoken中时，会存在解码不一致的问题：
![image](https://github.com/QwenLM/Qwen/assets/51821665/0f3290ab-6ab0-4b3b-9fc3-3cfe94489f44)

其中token_id前256为byte_fallback。请问官方是否有遇到相似的问题？

**Comment by JustinLin610** [comment]
没有尝试过转成sentencepiece的，建议还是使用我们的tokenizer

**Comment by zetian1025** [comment]
您好，我补充一下问题背景。在 #164 中官方有提到，qwen的词表是在tiktoken (应该是cl100k_base)的基础上扩充了中文词表，且中文词表是使用sentencepiece的方式训练得到的。

现在我尝试follow官方的思路，将sentencepiece训得的bpe词表构造mergeable_ranks得到.tiktoken文件。但遇到了上文所述的问题。

我猜测是tiktoken使用的分词正则式和sentencepiece不同？

这是我构造.model（sentencepiece）时使用的代码：
```python
spm.SentencePieceTrainer.train(
    sentence_iterator=data_file,
    model_prefix="customize_tokenizer",
    model_type="bpe",
    vocab_size="16784",
    max_sentencepiece_length=32,
    num_threads=128,
    character_coverage=1.0,
    byte_fallback=True,
    remove_extra_whitespaces=False,
    bos_id=-1,
    eos_id=-1,
    train_extremely_large_corpus=True,
)
```

这是我构造.tiktoken时使用的代码：
```python
def save_vocabulary_from_sentencepiece(sp_file, save_directory: str, **kwargs) -> Tuple[str]:
    """
    Save only the vocabulary of the tokenizer (vocabulary).

    Returns:
        `Tuple(str)`: Paths to the files saved.
    """
    sp = sentencepiece.SentencePieceProcessor()
    sp.Load(sp_file)
    file_path = os.path.join(save_directory, "customize_tokenizer.tiktoken")
    mergeable_ranks = {}
    idx = 0
    with open(file_path, "w", encoding="utf8") as w:
        # 构造byte_fallback
        for i in range(0, 256):
            if bytes([i]) not in mergeable_ranks.keys():
                mergeable_ranks[bytes([i])] = str(idx)
                idx = idx + 1
        # 将词表中其余token顺序得到kv对
        for i in range(257, sp.vocab_size()):
            k = sp.IdToPiece(i)
            v = i
            if k.replace('▁', ' ').encode() not in mergeable_ranks.keys():
                mergeable_ranks[k.replace('▁', ' ').encode()] = str(idx)
                idx = idx + 1
        for k, v in mergeable_ranks.items():
            line = base64.b64encode(k).decode("utf8") + " " + v + "\n"
            w.write(line)
    return (file_path,)
```

想问问官方是否有遇到类似的问题？或者merge部分的代码是否可以公开？

**Comment by jklj077** [comment]
思路供参考：
1. sentencepiece的BPE的起始基础单位好像是一个Unicode码位(对应1-4个UTF-8编码字节)；如果是未登录的话，"fall back"到UTF-8编码的字节。tiktoken的BPE的起始基础单位是UTF-8编码的字节。**单看**提供的代码是基础单位不同的问题，缺了"UTF-8编码的字节"到"Unicode码位对应的UTF-8编码的字节序列"的merge。对于中文的话，最后结果相当于完全没merge，全是单字节的token。单解这个问题的话可以暴力把这些merge搞出来。pretokenize方式对这个不会有太大影响，它影响的是一个"最大"的token可能形态。
2. 考虑**基于已有的**tiktoken词表扩展的话，还要考虑merge优先级的兼容性。两边同一个token从"起始基础单位"开始merge到这个token的路径可能是不同的。这个需要把sentencepiece的token，从UTF-8编码的字节开始，先按已有的tiktoken merges处理下，然后再把剩下的部分的对应merge学一下（需要频率信息），最后加到merge表/词表后面。这个还是建议谨慎处理了，会有些tricky。（还有更tricky的方式，利用tiktoken的special tokens功能绕过merge学习，纯仅供参考..）

代码后面应该会公开的。但还是建议先用提供的tokenizer吧，也想了解下具体什么场景需要扩充词表然后再训练呢？

**Comment by jklj077** [comment]
相关代码已公开，说明（英文）在<https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md#vocabulary-expansion>。

请试下看看，有问题的话，也请反馈到这个issue吧。

**Comment by zetian1025** [comment]
非常感谢！我会用提供的代码试试

**Comment by zhangbin1997** [comment]
> 思路供参考：
> 
> 1. sentencepiece的BPE的起始基础单位好像是一个Unicode码位(对应1-4个UTF-8编码字节)；如果是未登录的话，"fall back"到UTF-8编码的字节。tiktoken的BPE的起始基础单位是UTF-8编码的字节。**单看**提供的代码是基础单位不同的问题，缺了"UTF-8编码的字节"到"Unicode码位对应的UTF-8编码的字节序列"的merge。对于中文的话，最后结果相当于完全没merge，全是单字节的token。单解这个问题的话可以暴力把这些merge搞出来。pretokenize方式对这个不会有太大影响，它影响的是一个"最大"的token可能形态。
> 2. 考虑**基于已有的**tiktoken词表扩展的话，还要考虑merge优先级的兼容性。两边同一个token从"起始基础单位"开始merge到这个token的路径可能是不同的。这个需要把sentencepiece的token，从UTF-8编码的字节开始，先按已有的tiktoken merges处理下，然后再把剩下的部分的对应merge学一下（需要频率信息），最后加到merge表/词表后面。这个还是建议谨慎处理了，会有些tricky。（还有更tricky的方式，利用tiktoken的special tokens功能绕过merge学习，纯仅供参考..）
> 
> 代码后面应该会公开的。但还是建议先用提供的tokenizer吧，也想了解下具体什么场景需要扩充词表然后再训练呢？

借楼问一下哈。我这边目前扩充Qwen词表的做法是直接把新的词加入到mergeable_ranks的最后，也就是说新的词的index是从151643开始的，也就是说我没有使用extra_vocab_file，而是直接修改qwen.tiktoken，并且呢在word embedding 和 lm head weight初始化时，我会把原始Qwen里面的那208个special token的embedding平移到相对应的位置去，请问我这样做会有什么比较明显的问题吗，我check了一下新扩词表的tokenize结果，结果是符合预期的。

**Comment by jklj077** [comment]
@zhangbin1997 
> 我这边目前扩充Qwen词表的做法是直接把新的词加入到mergeable_ranks的最后

主要是merge兼容的问题，直接加词进去的话，不容易确定是不是（各种上下文下）都能切出来。建议跑下add_merges.py看下log里有没有比较奇怪的token，如果有的话，很可能有不兼容的问题。

> 新的词的index是从151643开始的，也就是说我没有使用extra_vocab_file，而是直接修改qwen.tiktoken，并且呢在word embedding 和 lm head weight初始化时，我会把原始Qwen里面的那208个special token的embedding平移到相对应的位置去

这个逻辑看您描述的没有明显问题。
