### ISSUE TITLE
希望能像MOSS和GLM一样，提供一下多轮对话微调的说明

### ISSUE THREAD

**Issue by metacarbon** [QwenLM/Qwen#4]
比如 数据格式对齐方式 等

**Comment by xiaobaibai1** [comment]
这个有回答吗？

**Comment by jklj077** [comment]
我们已提供Qwen-7B和Qwen-7B-Chat的微调代码样例，其中包括全参数微调、LoRA以及Q-LoRA。相关脚本请参见本存储库下的finetune文件夹，使用说明（包括数据格式等）在README中，欢迎试用！
