### ISSUE TITLE
💡 [REQUEST] - 希望官方提供一个函数调用的微调功能

### ISSUE THREAD

**Issue by staticTao** [QwenLM/Qwen#402]
### 摘要 | Summary

目前的函数调用需要更多的prompt，对于效果好的情况，就可能需要更多的例子，这样就会让提示词工程显得很的庞大。
针对函数调用比较多的情况，如果能把这些例子融入到模型里面去，就会减少prompt的工作量。在使用过程中，对于**链式调用**的情况应该会比目前的prompt效果更好。
在解耦的情况下，prompt-->函数调用-->微调后的模型
**prompt**：少量且灵活，具有专注性。
**函数调用**：fcuntion汇总
**微调后的模型**：能够更聪明的找到需要的函数调用。_对于垂直行业内，相似问题会有更好的选择函数的能力_。（目前采用 prompt对于行业内相似问题效果有点差）

### 基本示例 | Basic Example

例：某日期（今天）的某数据怎么样？是否能达到标准？
过程：思考-->某数据需要用到的函数-->能否达标（可能是另一个函数，也可能是知识库里面的某公式）--->拿到结果--->带入思考---返回结果。

### 缺陷 | Drawbacks

增加了训练的成本

**Comment by JianxinMa** [comment]
参考这个示例的格式构造类似的训练样本即可：https://github.com/QwenLM/Qwen/pull/406/files （ @JustinLin610 请帮忙顺手merge下该PR。）

**Comment by staticTao** [comment]
> 参考这个示例的格式构造的类似的训练样本即可：https://github.com/QwenLM/Qwen/pull/406/files（@JustinLin610请帮忙顺手merge下该PR。）

sry，昨晚回去没有电脑，未能及时回复。感谢

**Comment by staticTao** [comment]
> 参考这个示例的格式构造的类似的训练样本即可：https://github.com/QwenLM/Qwen/pull/406/files（@JustinLin610请帮忙顺手merge下该PR。）
`[
  {
    "id": "identity_0",
    "conversations": [
      {
        "role": "user",
        "content": "{example_instruction}\n Question: Who is jay chou? And who is his wife?"
      },
      {
        "role": "assistant",
        "content": "Thought: I need to google Jay Chou.\n Action: google_search\n Action Input: {\"search_query\": \"Jay Chou\"} \n Observation: Jay Chou is ...,"
      }
    ]
  },
  {
    "id": "identity_1",
    "conversations": [
      {
        "role": "user",
        "content": "{example_instruction}\n Question: Who is jay chou? And who is his wife?"
      },
      {
        "role": "assistant",
        "content": "Thought: I need to google Jay Chou.\n Action: google_search\n Action Input: {\"search_query\": \"Jay Chou\"} \n Observation: Jay Chou is ...,"
      }
    ]
  }
]`


抱歉，有点没能明白。请问是这样做样本吗？如果是这样做的话，{example_instruction}自定义函数是写在examples/function_call_finetune_examples.py文件的example_functions里面吗？emmmm，那么训练的时候用lora 怎么才能和function_call_finetune_examples.py这个文件关联上呢？

**Comment by JianxinMa** [comment]
function_call_finetune_examples.py 只是用来产出sft训练数据的。然后训练的时候就和普通的sft没有任何区别，不需要为function calling做任何训练代码上的改动。

**Comment by staticTao** [comment]
> function_call_finetune_examples.py 只是用来产出sft训练数据的。然后训练的时候就和普通的sft没有任何区别，不需要为function calling做任何训练代码上的改动。

抱歉，我刚看懂，我就把那个提问删了，谢谢

**Comment by staticTao** [comment]
> function_call_finetune_examples.py 只是用来产出sft训练数据的。然后训练的时候就和普通的sft没有任何区别，不需要为function calling做任何训练代码上的改动。


你好，当我做好sft训练数据并用lora训练后，启动模型，使用examples/react_demo.py进行自定义的函数接口改造，进行输入，dubugger发现代码执行没有走react_demo.py的189行  def call_plugin(plugin_name: str, plugin_args: str)，执行过程好像没有调用函数接口。不知道怎么回事。
![image](https://github.com/QwenLM/Qwen/assets/39627071/b7678fb0-6ec8-4fa3-a6d3-b81a76be7afd)
这个数据并不是接口里面的。他没有调用到接口。

![image](https://github.com/QwenLM/Qwen/assets/39627071/5b892049-eddf-417f-b9a7-1d391ac892c2)
这是准备的sft训练数据样式。

**Comment by JianxinMa** [comment]
仅从提供的信息，我无法给出准确的判断。但是一种常见的原因是：没有命中 stop words 的 tokens。具体而言：

- 目前代码里配置的是 stop_words=['Observation:', 'Observation:\n'] ， 对应的 tokens 分别是 [37763, 367, 25] [37763, 367, 510]。
- 但假如准备SFT数据时，数据中混有 'Observation:\n\n' 之类的 str，并且推理时也生成了这个 str，则需要注意 'Observation:\n\n' 实际对应的 tokens 为 [37763, 367, 1447]！这个 tokens 实际无法命中前面配置的 stop words。

简便的解决方案就是清洗SFT数据，确保 Observation 这个关键词对应的 tokens 都是对的。复杂些的解法则是在 inference 时引入更多的 stop words、或者引入 token healing 等技巧。

**Comment by JianxinMa** [comment]
另外，截图里的“思想、行动、观察“这些是模型生成的吗，还是规则后处理替换的？如果是前者，就需要改react_demo.py脚本里相应的关键词。如果是后者， 如果可以把模型实际生成的结果发一下，可以帮助我们更准确地定位问题。

**Comment by staticTao** [comment]
> 仅从提供的信息，我无法给出准确的判断。但是一种常见的原因是：没有命中 stop words 的 tokens。具体而言：
> 
> * 目前代码里配置的是 stop_words=['Observation:', 'Observation:\n'] ， 对应的 tokens 分别是 [37763, 367, 25] [37763, 367, 510]。
> * 但假如准备SFT数据时，数据中混有 'Observation:\n\n' 之类的 str，并且推理时也生成了这个 str，则需要注意 'Observation:\n\n' 实际对应的 tokens 为 [37763, 367, 1447]！这个 tokens 实际无法命中前面配置的 stop words。
> 
> 简便的解决方案就是清洗SFT数据，确保 Observation 这个关键词对应的 tokens 都是对的。复杂些的解法则是在 inference 时引入更多的 stop words、或者引入 token healing 等技巧。

这个问题应该是出现在，我准备数据的时候Observation: 没有像你给的例子一样向左定格，我重新试了，现在可行。

**Comment by staticTao** [comment]
> 另外，截图里的“思想、行动、观察“这些是模型生成的吗，还是规则后处理替换的？如果是前者，就需要改react_demo.py脚本里相应的关键词。如果是后者， 如果可以把模型实际生成的结果发一下，可以帮助我们更准确地定位问题。

这个是因为我把prompt的英文翻译成中文了，可以这个和stop_words没有关联上？我修改成英文就正常了。非常感谢你帮助。

**Comment by knjwhn969** [comment]
@staticTao 您好，请问您在上面提的示例中提到的效果实现了吗，效果如何呢？
例：某日期（今天）的某数据怎么样？是否能达到标准？
过程：思考-->某数据需要用到的函数-->能否达标（可能是另一个函数，也可能是知识库里面的某公式）--->拿到结果--->带入思考---返回结果。

**Comment by staticTao** [comment]
> @staticTao 您好，请问您在上面提的示例中提到的效果实现了吗，效果如何呢？ 例：某日期（今天）的某数据怎么样？是否能达到标准？ 过程：思考-->某数据需要用到的函数-->能否达标（可能是另一个函数，也可能是知识库里面的某公式）--->拿到结果--->带入思考---返回结果。

知识库还没有试，因为行业内问题都比较相似，有点不好弄，其他的链式调用过程，效果可观，能够减少prompt的编写。

**Comment by LiuChen19960902** [comment]
想请教下，最近我也在研究qwen的工具功能。我自己构造了一些工具sft数据集，结构也是这样https://github.com/QwenLM/Qwen/issues/402#issuecomment-1752254004

但是当我们调用工具的时候，其实是通过人为构造了react prompt，然而模型没办法自己去区分什么时候该用工具，什么时候不该用。这种问题我觉得可以通过构造sft的方式来解决，让模型学会什么情况下需要用工具。但是我不是很清楚这样的数据集应该怎么构造，请问大家有什么好的建议吗。感谢~

**Comment by Yimi81** [comment]
@LiuChen19960902 ,"模型没办法自己去区分什么时候该用工具，什么时候不该用"这个问题我在chatglm3中也发现了，qwen效果稍微好一些，对于qwen，当提供的工具与用户的输入没什么相关性时，其会通过推理选择直接回答，如下图：
![image](https://github.com/QwenLM/Qwen/assets/66633207/e18cae36-93c3-4d50-b420-59b5f01104f4)
，如果想通过sft增强qwen自动选择是否调用工具的能力，我认为数据集构造跟之前是一样的，只是你要多提供一些当提供的工具与用户的输入没什么相关性时，或者帮助不大时，直接回答的example。即数据样例assistant的回答只有Thought和Final Answer没有Action，类似这样：
![image](https://github.com/QwenLM/Qwen/assets/66633207/e589be13-5654-433f-adcd-966f08c04ce7)

**Comment by LiuChen19960902** [comment]
@Yimi81 感谢你的提示，这是我之前没有考虑到的。但是这里有一个问题，那就是当我们决定使用工具的时候，我们会先把react prompt模板拿来套用在query上。这个时候其实就已经决定了“我打算用工具”，那么如果接下来不用工具了，还是需要套react prompt模板。也就是说，为了模型可以用工具，其实每次的query都需要套在react prompt模板中。
这时候就有两个问题：
其一是加长了每次prompt的长度，多轮对话会很快的打满最大长度。
其二是模型是否会出现误用工具的可能。

不知道我这样的理解是否正确呢？十分感谢你的解答~

**Comment by Yimi81** [comment]
是的，每次对话无论你是否想要调用工具，都需要套react prompt模版，这似乎无法避免(如果有，请告诉我，感激不尽)。我在用chatgpt的function_call的时候，每次调用API都需要把所有functions描述传过去，到底是否调用工具由chatgpt决定。这里应该是一样的问题。我解决的办法就是要么选择chatgpt-3.5-16k的模型，要么每当多轮对话超长了之后，采用局部性原理，只发送近5次聊天的记录，之前的只展示在前台，不放在history里

**Comment by LiuChen19960902** [comment]
@Yimi81 
我刚才看了看moss的数据构造方式，可能moss的sft方式也是一种解决思路
[moss 无工具](https://github.com/OpenLMLab/MOSS/blob/main/SFT_data/conversations/conversation_without_plugins/harmless_conversations/harmless_conversation_1.json)
[moss 有工具](https://github.com/OpenLMLab/MOSS/blob/main/SFT_data/conversations/conversation_with_plugins/equation_solver/solver_plugin_conversation_1.json)

**Comment by Yimi81** [comment]
@LiuChen19960902 感谢分享！
