### ISSUE TITLE
[BUG] Qwen-14B INT4模型多卡部署推理报错

### ISSUE THREAD

**Issue by brandonchow1997** [QwenLM/Qwen#404]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen-14B INT4模型，多卡部署推理时报错，提示
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!`

nvidia-smi可查看到模型已部署，但只要输入就会报错。

<img width="578" alt="截屏2023-10-07 14 45 00" src="https://github.com/QwenLM/Qwen/assets/40913735/9f511953-476c-498a-aa63-c98959ed7e4e">

<img width="1440" alt="截屏2023-10-07 14 43 37" src="https://github.com/QwenLM/Qwen/assets/40913735/4bc38d91-801e-42df-a911-1f214dbc31cc">

### 期望行为 | Expected Behavior

Qwen-14B INT4模型，多卡成功部署且正确进行推理。

### 复现方法 | Steps To Reproduce

1. utils.py中device_map='auto'；
```
def load_model_on_gpus(model_name_or_path, num_gpus: int = 2):
    num_devices = torch.cuda.device_count()

    if num_gpus == 1:
        model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map='auto',
                                                     trust_remote_code=True).eval()
    elif 1 < num_gpus <= num_devices:
        model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map='auto',
                                                     trust_remote_code=True).eval()
        num_layers = model.config.num_hidden_layers
        device_map = _device_map(num_gpus, num_layers)
        print(device_map)
        model = dispatch_model(model, device_map=device_map)
    else:
        raise KeyError

    return model
```

2. cli_demo.py中调整为多卡加载
`model = load_model_on_gpus('/root/autodl-tmp/Qwen-int4/qwen/Qwen-14B-Chat-Int4', num_gpus=2)`

3. python3 cli_demo.py完成模型加载后进行输入

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.0.4
- Python:3.8
- Transformers:4.32.0
- PyTorch:2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by brandonchow1997** [comment]
Transformers:4.30.2

**Comment by JustinLin610** [comment]
当前transformers应该默认方法就能支持好多卡不用手动dispatch了，试下不改代码直接load int4模型是否有问题？

**Comment by jklj077** [comment]
@brandonchow1997 请问使用最新代码该问题仍存在吗？

**Comment by 18liumin** [comment]
问题还存在吗，用load_in_4bit 报错RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

**Comment by jklj077** [comment]
a@18liumin

load_in_4bit是bitsandnbytes的参数。目前量化模型用的是AutoGPTQ，也不支持这个参数呀。请确认下使用方法。

新版的transformers的`device_map="auto"`，由accelerate支持，如果有多卡的话，参数会平衡分布到多张卡上，实现naive的model parallelism，并配置完成相应的hook，以完成中间状态在多卡间的自动转移。如果`device_map="auto"`加载模型后手动调整参数位置，是会出现device不匹配问题的。

如仍有错误，请提供尽量完整的错误报告，以便更好的定位问题。
