### ISSUE TITLE
用qlora进行微调训练数据格式应该是什么?

### ISSUE THREAD

**Issue by 3CE8D2BAC65BDD6AA9** [QwenLM/Qwen#409]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我想用qlora进行微调，微调是为了翻译。 我的训练文件是这样的。
```

[
    {
        "id":"id_0",
        "conversations": [
            {
                "from":"user",
                "value":"翻译:“The big benefit of going digital in this space? Flexibility! Unlike traditional paper-based or folder-organized digital systems, your documents can belong to multiple categories at once. Ever wrestled with the dilemma of deciding which folder a document should go into? That's because it often fits more than one category. The solution? Tags. With a digital solution like Paperless, you can assign as many tags as you need, making categorization a breeze. Say goodbye to the folder confusion!"
            },
            {
                "from":"assistant",
                "value":"在这个领域实现数字化的最大好处是什么？ 灵活性！ 与传统的基于纸张或文件夹组织的数字系统不同，您的文档可以同时属于多个类别。 您是否曾因决定将文档放入哪个文件夹而陷入困境？ 这是因为它通常适合多个类别。 解决方案？ 标签。 借助无纸化等数字解决方案，您可以根据需要分配任意数量的标签，从而使分类变得轻而易举。 告别文件夹混乱！"
            }
        ]
    },
    {
        "id":"id_1",
        "conversations": [
            {
                "from":"user",
                "value":"翻译:"Rabies virus is incurable and almost always fatal once it has invaded the central nervous system, with the victim doomed to suffer a horrible death."
            },
            {
                "from":"assistant",
                "value":"狂犬病病毒无法治愈，一旦侵入中枢神经系统，几乎总是致命的，受害者注定会遭受可怕的死亡。"
            }
        ]
    }
]
```

微调后发现没有效果。 我有两个问题：

1. 翻译的正确微调训练数据格式应该是什么？
2. 如何判断qlora是否有效果？

### 运行环境 | Environment

```Markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.31.0
PyTorch: 2.0.1
CUDA: 12.2
```

**Comment by JustinLin610** [comment]
没有效果的具体表现是什么？数据多少条具体训练多少轮

**Comment by 3CE8D2BAC65BDD6AA9** [comment]
我在数据文件中重复训练数据 10 次。 我使用了fine_tune_qlora_single_gpu.sh中的默认设置，即num_train_epochs为5。但是当我输入原文时，翻译仍然与原始模型相同。 我已经更新了模型以指向 qlora 输出。
```

model = AutoModelForCausalLM.from_pretrained(
    "path_to_qlora directory",
    device_map="auto",
    trust_remote_code=True
).eval()
```

**Comment by JustinLin610** [comment]
我修改一下默认的学习率，有可能太小导致模型学的不够好。但是依靠qlora来做类似死记硬背的操作也不是很现实，如果有条件的话对比下lora或者full parameter tuning？

**Comment by 3CE8D2BAC65BDD6AA9** [comment]
非常感谢您的指点。 我的训练数据格式正确吗?
`
[
    {
        "id":"id_0",
        "conversations": [
            {
                "from":"user",
                "value":"翻译:“The big benefit of going digital in this space? Flexibility! Unlike traditional paper-based or folder-organized digital systems, your documents can belong to multiple categories at once. Ever wrestled with the dilemma of deciding which folder a document should go into? That's because it often fits more than one category. The solution? Tags. With a digital solution like Paperless, you can assign as many tags as you need, making categorization a breeze. Say goodbye to the folder confusion!"
            },
            {
                "from":"assistant",
                "value":"在这个领域实现数字化的最大好处是什么？ 灵活性！ 与传统的基于纸张或文件夹组织的数字系统不同，您的文档可以同时属于多个类别。 您是否曾因决定将文档放入哪个文件夹而陷入困境？ 这是因为它通常适合多个类别。 解决方案？ 标签。 借助无纸化等数字解决方案，您可以根据需要分配任意数量的标签，从而使分类变得轻而易举。 告别文件夹混乱！"
            }
        ]
    },
    {
        "id":"id_1",
        "conversations": [
            {
                "from":"user",
                "value":"翻译:"Rabies virus is incurable and almost always fatal once it has invaded the central nervous system, with the victim doomed to suffer a horrible death."
            },
            {
                "from":"assistant",
                "value":"狂犬病病毒无法治愈，一旦侵入中枢神经系统，几乎总是致命的，受害者注定会遭受可怕的死亡。"
            }
        ]
    }
]`

**Comment by JustinLin610** [comment]
格式没问题，能跑通就可以的

**Comment by DuBaiSheng** [comment]
你好，你的qlora能跑通吗？

**Comment by barryli717** [comment]
用来测试的数据需要改成chatml的格式，不能直接输原文的。
