### ISSUE TITLE
我怎么在我py工程引用模型内的文件如make_context

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen#410]
### 实现PR | Implementation PR

如题。
我想在我自己代码引用模型内的文件
发现，模型下的几个文件写的相对路径，我直接sys.append好像不太行。
模型内部文件也没有__init__.py

### 相关Issues | Reference Issues

1

### 摘要 | Summary

1

### 基本示例 | Basic Example

11

### 缺陷 | Drawbacks

1

### 未解决问题 | Unresolved questions

1

**Comment by wellcasa** [comment]
`            import sys
            sys.path.append(self.model_path)
            from tokenization_qwen import QWenTokenizer
            from modeling_qwen import QWenLMHeadModel
            from transformers import GenerationConfig
            from qwen_generation_utils import make_context
            self.tokenizer = QWenTokenizer.from_pretrained('./', pad_token='<|extra_0|>', eos_token='<|endoftext|>',padding_side='left')
            self.model = QWenLMHeadModel.from_pretrained('./', device_map="auto").eval()
            self.model.generation_config = GenerationConfig.from_pretrained('./')
            self.make_context = make_context`

**Comment by wellcasa** [comment]
import sys
            sys.path.append(self.model_path)
            from tokenization_qwen import QWenTokenizer
            from modeling_qwen import QWenLMHeadModel
            from transformers import GenerationConfig
            from qwen_generation_utils import make_context
            self.tokenizer = QWenTokenizer.from_pretrained('./', pad_token='<|extra_0|>', eos_token='<|endoftext|>',padding_side='left')
            self.model = QWenLMHeadModel.from_pretrained('./', device_map="auto").eval()
            self.model.generation_config = GenerationConfig.from_pretrained('./')
            self.make_context = make_context

**Comment by jklj077** [comment]
是的，由于transformers的dynamic module机制，这部分代码不太能用"sys.path.append"这种方式方式来弄。代码利用model与tokenizer最好使用transformers的auto classes。如需要使用make_context，可能需要将相关代码copy下了。

**Comment by wellcasa** [comment]
我现在是直接sys.path.append。就是加载路径，识别。

**Comment by jklj077** [comment]
您问题已经解决了吗？

**Comment by wellcasa** [comment]
解决了，我关闭了。
核心方法就是 使用ys.path.append记载模型的路径。就可以用咯。
