### ISSUE TITLE
用generate batch推理结果会有很多叹号！！！！

### ISSUE THREAD

**Issue by menghonghan** [QwenLM/Qwen#414]
您好，感谢支持，目前我们没有复现出该问题。由于上周末重构过tokenizer，请先更新下代码试试？

![image](https://github.com/QwenLM/Qwen-7B/assets/17811943/9c9e9252-d587-41e7-bc21-96d74990ea8b)

_Originally posted by @jklj077 in https://github.com/QwenLM/Qwen/issues/145#issuecomment-1672524972_
            
我也出现了这个issue楼主出现的问题，单条generate不会有问题，batch的时候就会左侧有叹号，并且和其他开源模型用的是一套代码，请问这是什么问题，谢谢

**Comment by jklj077** [comment]
您引用的这条回复是针对tokenizer的batch处理哈模型的batch generate请参考https://github.com/QwenLM/Qwen/issues/159#issuecomment-1727139620

**Comment by logicwong** [comment]
@menghonghan 请参照这个回复 https://github.com/QwenLM/Qwen/issues/471#issuecomment-1762920094
