### ISSUE TITLE
qwen14b 在2048token输入下的显存最高占用30.15GB，是走心设计么，可以让32G-GPU跑起来？

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen#415]
### 实现PR | Implementation PR

1

### 相关Issues | Reference Issues

![image](https://github.com/QwenLM/Qwen/assets/15667364/31e9a78a-e907-4e32-b8ac-6c06976cd004)

### 摘要 | Summary

1

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

### 未解决问题 | Unresolved questions

1

**Comment by JustinLin610** [comment]
不是，运气好而已。

**Comment by wellcasa** [comment]
> 不是，运气好而已。

那运气真的爆棚。
