### ISSUE TITLE
关于千问模型在不同平台的大小问题

### ISSUE THREAD

**Issue by yumingfan-0219** [QwenLM/Qwen#416]
您好！
qwen-7b模型在huggingface和modelscope的大小有略微不同，请问这是否是平台的原因？我查看了其他开源模型，发现百川13b也有类似的情况

感谢回复！

**Comment by jklj077** [comment]
huggingface上的大小单位是1000倍数的，modelscope上的大小单位是1024倍数的（常用的），两边实际大小其实是一样的哈。
