### ISSUE TITLE
[BUG] vocab size 代码和文档不一致

### ISSUE THREAD

**Issue by yportne13** [QwenLM/Qwen#419]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

readme 中 vocab size 写的是 151851，但是 qwen-7b-chat 和 qwen-14b-chat 仓库中的 config.json 里描述的则分别是 151936 和 152064

### 期望行为 | Expected Behavior

按照文档描述的话，基础的 token 有 151643 个，加上 3 个特殊 token，再加 205 个 extra token，一共应该是 151851 才对

**Comment by jklj077** [comment]
文档中的vocab size指的是实际的词表大小，即tokenizer中支持的token数。config.json中数值是实际模型中的embedding size的大小，由于计算效率原因，一般会设置为128的倍数，会比实际的vocab size大一些哈。

**Comment by yportne13** [comment]
再请教一下，那为啥不直接把 extra token 扩到 290 呢

**Comment by jklj077** [comment]
都可以的哈，区别不大。
