### ISSUE TITLE
api如何释放显存

### ISSUE THREAD

**Issue by 315930399** [QwenLM/Qwen#420]
小白求问，通过api起的服务，随着问答次数增加，显存占用逐渐提高。请问增加的显存是问题文本吗？有什么方法能在每次回答后释放显存呢？

**Comment by yangapku** [comment]
您好，我们在相关脚本中加入了清除缓存的代码哈，请拉取最新代码再尝试下~

**Comment by fyabc** [comment]
@315930399 您好，我们更新了`openai_api.py`的逻辑，现在默认会在每次回答后回收显存（也可以使用`--disable-gc`选项关闭回收），可以更新代码后重新尝试。

**Comment by TheHonestBob** [comment]
> 您好，我们在相关脚本中加入了清除缓存的代码哈，请拉取最新代码再尝试下~

清楚缓存是指torch.cuda.empty_cache()操作吧，请问一下之前使用chatglm的时候，随着使用次数的增加，显存占用的确会比一开始多，但是基本上增加了2-3G之后就会稳定，为啥qwen不orch.cuda.empty_cache()一下，显存占用会一直增加呢
