### ISSUE TITLE
[BUG] <title>ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 47139) of binary

### ISSUE THREAD

**Issue by Xccanxin** [QwenLM/Qwen#423]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

finetune_lora_ds.sh遇到此报错
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47138 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47140 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47141 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 47139) of binary:  xxx

以下设置可以运行
GPUS_PER_NODE=2
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

修改GPUS_PER_NODE=4 or GPUS_PER_NODE=8遇到此报错，已检查单机空闲gpu有8块

### 期望行为 | Expected Behavior

可以正常使用多个gpu

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Droliven** [comment]
请问这个问题有没有解决呀~lora 多卡微调有没有成功的实践~

**Comment by Droliven** [comment]
目前64G内存，单卡双卡都能成功，3卡及以上会报这个错，把内存扩大到 256G，跑4卡微调成功了

**Comment by jklj077** [comment]
> 目前64G内存，单卡双卡都能成功，3卡及以上会报这个错，把内存扩大到 256G，跑4卡微调成功了

@Xccanxin 可以看下是这个问题吗？

**Comment by songge25** [comment]
我是八卡训练，跑一段时间会报这个错误，是一样的吗

**Comment by mokby** [comment]
请问有解决的么?双卡4090无论是跑Lora还是Qlora都不行,改了好久一直说显存不够,但是单卡跑就可以正常运行

**Comment by jiagong96** [comment]
> 请问有解决的么?双卡4090无论是跑Lora还是Qlora都不行,改了好久一直说显存不够,但是单卡跑就可以正常运行

就是cpu memory的问题，我也是单卡能跑，多卡不行，然后我把cpu memory加到了450就可以了

**Comment by mokby** [comment]
> > 请问有解决的么?双卡4090无论是跑Lora还是Qlora都不行,改了好久一直说显存不够,但是单卡跑就可以正常运行
> 
> 就是cpu memory的问题，我也是单卡能跑，多卡不行，然后我把cpu memory加到了450就可以了

感谢,看来真的是这个问题,以后有条件试验一下

**Comment by hitbuyi** [comment]
同样问题
