### ISSUE TITLE
[Request] 为 Profiling of Memory and Speed 部分提供更多超参数

### ISSUE THREAD

**Issue by yorhaha** [QwenLM/Qwen#424]
README 的 Profiling of Memory and Speed 部分有了 GPU 和 batch size 等信息，但我想确认一下你们所使用的超参数，例如 lora_r、lora_target_modules、zero-stage 等。

**Comment by yorhaha** [comment]
以及，是否使用了 flash-attention。

**Comment by JustinLin610** [comment]
lora_r和target module在脚本已经给出，包括zero stage也是和脚本一致的，batch size也已经提到，都是1的bz，ga=8。用了flash 1，准备用flash 2重测

**Comment by yorhaha** [comment]
我用 A100 40G `finetune_lora_ds.sh` lora 微调 Qwen-14B-Chat 一直 OOM，与预期不符😭：

```
--per_device_train_batch_size 1
--model_max_length 128
--lora_r 1
--lora_target_modules "c_attn"
--deepspeed finetune/ds_config_zero2.json
```

其他未做改动。

```
transformers                  4.32.0
deepspeed                     0.11.0
flash-attn                        2.3.2
```
