### ISSUE TITLE
结合使用langchain和openai_api部署服务时最大并发数不能超过5

### ISSUE THREAD

**Issue by lin-xiaosheng** [QwenLM/Qwen#425]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

结合使用langchain和openai_api部署服务，命令如下
nohup python openai_api.py --checkpoint-path ./Qwen-14B-Chat-Int4 --server-port 5000 --server-name 0.0.0.0 &
当业务端多个请求同时发起，最大只有5个请求能得到回应，其余的请求会进入队列等待。
GPU为单张A100-40GB，GPU显存峰值占用为20GB、运算能力占用峰值为47%，似乎没有硬件瓶颈。
我该如何改善该情况从而提高显卡性能的利用率，或者提升单卡并发能力

### 期望行为 | Expected Behavior

显卡内存或运算载荷能接近瓶颈

**Comment by maxusheng123** [comment]
我跟你也是同样的问题，我的是A10 显卡 24G显存，目前峰值是20G，好像连并发都不支持，直接呈排队的形式，我用的是LLaMA-Efficient-Tuning这个框架，急求解决方案。。

**Comment by nne998** [comment]
试下调一下代码里面这行
···
  uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
···
里面那个 workers 参数

**Comment by lin-xiaosheng** [comment]
> 试下调一下代码里面这行
> 
> ```
>   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> ```
> 
> 里面那个 workers 参数

感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343,
则必须将app改成"__main__:app"，以字符串形式调用
例如：    uvicorn.run("__main__:app", host=args.server_name, port=args.server_port, workers=10)
但这样做似乎是不被Qwen接受的，报错如下：
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap
    await func()
  File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict
    response_generator = model.chat_stream(
NameError: name 'model' is not defined

对于该报错我该在哪方面做出努力？

**Comment by deepslit** [comment]
> > 试下调一下代码里面这行
> > ```
> >   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> > ```
> > 
> > 
> > 里面那个 workers 参数
> 
> 感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343, 则必须将app改成"**main**:app"，以字符串形式调用 例如： uvicorn.run("**main**:app", host=args.server_name, port=args.server_port, workers=10) 但这样做似乎是不被Qwen接受的，报错如下： Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in **call** await super().**call**(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** await self.app(scope, receive, _send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in **call** raise e File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in **call** await route.handle(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in **call** async with anyio.create_task_group() as task_group: File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in **aexit** raise exceptions[0] File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap await func() File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response async for data in self.body_iterator: File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict response_generator = model.chat_stream( NameError: name 'model' is not defined
> 
> 对于该报错我该在哪方面做出努力？

把

> > 试下调一下代码里面这行
> > ```
> >   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> > ```
> > 
> > 
> > 里面那个 workers 参数
> 
> 感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343, 则必须将app改成"**main**:app"，以字符串形式调用 例如： uvicorn.run("**main**:app", host=args.server_name, port=args.server_port, workers=10) 但这样做似乎是不被Qwen接受的，报错如下： Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in **call** await super().**call**(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** await self.app(scope, receive, _send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in **call** raise e File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in **call** await route.handle(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in **call** async with anyio.create_task_group() as task_group: File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in **aexit** raise exceptions[0] File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap await func() File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response async for data in self.body_iterator: File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict response_generator = model.chat_stream( NameError: name 'model' is not defined
> 
> 对于该报错我该在哪方面做出努力？

把加载模型的代码放到main 外面去就可以了

**Comment by faiejir** [comment]
> > > 试下调一下代码里面这行
> > > ```
> > >   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 里面那个 workers 参数
> > 
> > 
> > 感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343, 则必须将app改成"**main**:app"，以字符串形式调用 例如： uvicorn.run("**main**:app", host=args.server_name, port=args.server_port, workers=10) 但这样做似乎是不被Qwen接受的，报错如下： Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in **call** await super().**call**(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** await self.app(scope, receive, _send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in **call** raise e File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in **call** await route.handle(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in **call** async with anyio.create_task_group() as task_group: File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in **aexit** raise exceptions[0] File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap await func() File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response async for data in self.body_iterator: File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict response_generator = model.chat_stream( NameError: name 'model' is not defined
> > 对于该报错我该在哪方面做出努力？
> 
> 把
> 
> > > 试下调一下代码里面这行
> > > ```
> > >   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 里面那个 workers 参数
> > 
> > 
> > 感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343, 则必须将app改成"**main**:app"，以字符串形式调用 例如： uvicorn.run("**main**:app", host=args.server_name, port=args.server_port, workers=10) 但这样做似乎是不被Qwen接受的，报错如下： Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in **call** await super().**call**(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** await self.app(scope, receive, _send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in **call** raise e File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in **call** await route.handle(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in **call** async with anyio.create_task_group() as task_group: File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in **aexit** raise exceptions[0] File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap await func() File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response async for data in self.body_iterator: File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict response_generator = model.chat_stream( NameError: name 'model' is not defined
> > 对于该报错我该在哪方面做出努力？
> 
> 把加载模型的代码放到main 外面去就可以了

请问具体怎么操作，新建一个文件叫main.py再运行吗

**Comment by deepslit** [comment]
> > > > 试下调一下代码里面这行
> > > > ```
> > > >   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 里面那个 workers 参数
> > > 
> > > 
> > > 感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343, 则必须将app改成"**main**:app"，以字符串形式调用 例如： uvicorn.run("**main**:app", host=args.server_name, port=args.server_port, workers=10) 但这样做似乎是不被Qwen接受的，报错如下： Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in **call** await super().**call**(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** await self.app(scope, receive, _send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in **call** raise e File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in **call** await route.handle(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in **call** async with anyio.create_task_group() as task_group: File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in **aexit** raise exceptions[0] File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap await func() File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response async for data in self.body_iterator: File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict response_generator = model.chat_stream( NameError: name 'model' is not defined
> > > 对于该报错我该在哪方面做出努力？
> > 
> > 
> > 把
> > > > 试下调一下代码里面这行
> > > > ```
> > > >   uvicorn.run(app, host=args.server_name, port=args.server_port, workers=1)  
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 里面那个 workers 参数
> > > 
> > > 
> > > 感谢回答！修改workers参数后，参考官方代码https://github.com/encode/uvicorn/blob/9b92925a352b9743c5cfcef4a65e74a81a1bad4f/uvicorn/main.py#L343, 则必须将app改成"**main**:app"，以字符串形式调用 例如： uvicorn.run("**main**:app", host=args.server_name, port=args.server_port, workers=10) 但这样做似乎是不被Qwen接受的，报错如下： Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 292, in **call** await super().**call**(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** await self.app(scope, receive, _send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** raise exc File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in **call** raise e File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in **call** await route.handle(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle await self.app(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 69, in app await response(scope, receive, send) File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in **call** async with anyio.create_task_group() as task_group: File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in **aexit** raise exceptions[0] File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap await func() File "/root/miniconda3/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response async for data in self.body_iterator: File "/root/autodl-tmp/Qwen/openai_api.py", line 440, in predict response_generator = model.chat_stream( NameError: name 'model' is not defined
> > > 对于该报错我该在哪方面做出努力？
> > 
> > 
> > 把加载模型的代码放到main 外面去就可以了
> 
> 请问具体怎么操作，新建一个文件叫main.py再运行吗

就是分成两个.py脚本，一个叫app.py，一个叫run.py。在app.py里要把加载模型代码放在if __name__ == "__main__": 外面，免得它不会加载模型。具体点你直接看我上传的吧。其中run.py default="../Qwen-7B-Chat-Int4"要改成自己的模型路径
[app.txt](https://github.com/QwenLM/Qwen/files/13174330/app.txt)
[run.txt](https://github.com/QwenLM/Qwen/files/13174331/run.txt)

**Comment by huyang19881115** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/llmservice/Qwen-main/app.py", line 395, in create_chat_completion
    response, _ = model.chat(
  File "/home/tianjin/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-Int4/modeling_qwen.py", line 1199, in chat
    outputs = self.generate(
  File "/home/tianjin/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-Int4/modeling_qwen.py", line 1318, in generate
    return super().generate(
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2760, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
INFO:     172.16.7.18:58311 - "POST /v1/chat/completions HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "/data/llmservice/Qwen-main/app.py", line 443, in predict
    for new_response in response_generator:
  File "/home/tianjin/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-Int4/modeling_qwen.py", line 1273, in stream_generator
    for token in self.generate_stream(
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/tianjin/miniconda3/envs/qwen/lib/python3.10/site-packages/transformers_stream_generator/main.py", line 969, in sample_stream
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by pretty-z** [comment]
请问您解决了么  我也遇到这个问题了

**Comment by lin-xiaosheng** [comment]
> 请问您解决了么 我也遇到这个问题了

不是langchain的问题，模型对外提供推理接口用fastapi+vllm解决即可

**Comment by huyang19881115** [comment]
解决了，不用这个openAPI启动，你找下，使用vllm推理加速启动，可以将4090显卡并发提高到20左右



---- 回复的原邮件 ----
| 发件人 | Lionel ***@***.***> |
| 日期 | 2024年05月12日 14:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [QwenLM/Qwen] 结合使用langchain和openai_api部署服务时最大并发数不能超过5 (Issue #425) |

请问您解决了么 我也遇到这个问题了

不是langchain的问题，模型对外提供推理接口用fastapi+vllm解决即可
