### ISSUE TITLE
[BUG] <title> fintune padding_side

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [QwenLM/Qwen#426]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

为什么finetune代码中的padding_side要改成用right？？不用left？

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10
- Transformers:4.33
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by jklj077** [comment]
finetune代码中的padding_side一直都是right哈；不指定的话，默认也是right。
训练一般都是右侧padding的。只有batch推理的时候，可能有些需要左侧padding。

**Comment by Cloopen-ReLiNK** [comment]
> finetune代码中的padding_side一直都是right哈；不指定的话，默认也是right。 训练一般都是右侧padding的。只有batch推理的时候，可能有些需要左侧padding。

之前我们是保证的训练、测试的padding方向一致，都是左padding。因为在某份数据上右padding训练的，batch推理时左padding效果不好。

**Comment by jklj077** [comment]
这个对于没有bug的代码，padding应当是无影响的，因为它是padding嘛。效果有问题有可能是代码没有做好适配哈。之前我们没有支持batch inference也是没适配完成。
