### ISSUE TITLE
二次预训练的数据准备

### ISSUE THREAD

**Issue by lbxcfx** [QwenLM/Qwen#427]
### 摘要 | Summary

预训练过程中，大部分内容是book, wiki这样的。不是user, asssitant这样的conversion对。请问这样的数据格式是怎么样的？

### 基本示例 | Basic Example

"id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      },
      {
        "from": "assistant",
        "value": "我是一个语言模型，我叫通义千问。"
      }

### 缺陷 | Drawbacks

增加pt的训练脚本和数据格式

**Comment by jklj077** [comment]
数据格式的话，可以先参考这里的回复，格式是一致的 https://github.com/QwenLM/Qwen/issues/394#issuecomment-1751606131

**Comment by xiaotingyun** [comment]
> 数据格式的话，可以先参考这里的回复，格式是一致的 [#394 (comment)](https://github.com/QwenLM/Qwen/issues/394#issuecomment-1751606131)

那么请问你们在预训练时，开始符bos_token和结束符eos_token分别是什么呢，是<|im_start|>和<|endoftext|>吗？

**Comment by jklj077** [comment]
嗯，那个comment有写的，文档间用<|endoftext|>拼接，无句子级别的bos_token、eos_token。

**Comment by hpsun1109** [comment]
> 嗯，那个comment有写的，文档间用<|endoftext|>拼接，无句子级别的bos_token、eos_token。

@jklj077 你好，我看qwen2.5中，eos_token和pad_token都是<|endoftext|>；请问pretrain阶段eos_token是不计算loss的吗？那如何保证pretrain模型推理时可以停下来

**Comment by jklj077** [comment]
pretrain阶段一般都是packing多条到固定length，用<|endoftext|>分隔多个example，这步是没有padding的，也是没有pad_token的。

> eos_token和pad_token都是<|endoftext|>；请问pretrain阶段eos_token是不计算loss的吗？

last token是算预测<|endoftext|>的loss的，<|endoftext|>是不算预测下一个token的loss的。

Qwen训练过程中没有原生的pad_token概念。但很多framework必须要这个token，一般用来算attention mask，设置成<|endoftext|>，这样开箱使用对于finetune （SFT/RLHF）危害最小。
