### ISSUE TITLE
💡 [REQUEST] - <title>请问之前版本的qwen是存在什么问题吗我收到这样的提示

### ISSUE THREAD

**Issue by endNone** [QwenLM/Qwen#429]
### 实现PR | Implementation PR

Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。

### 相关Issues | Reference Issues

Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。

### 摘要 | Summary

Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。

### 基本示例 | Basic Example

Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。

### 缺陷 | Drawbacks

Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。

**Comment by JianxinMa** [comment]
代码和模型checkpoint有对应关系，怕大家用拿新代码跑旧checkpoint出现奇怪的结果。
