### ISSUE TITLE
[Qwen-14B多卡微调报错oom] 一启用多卡微调，两张卡瞬间80G，然后oom是有什么地方参数没有调整正确吗？

### ISSUE THREAD

**Issue by 13361619575** [QwenLM/Qwen#430]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=2
DIR=`pwd`

GPUS_PER_NODE=2
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="/Qwen-14b-chat/" 
DATA="/data/xxx.json"
OUTPUT="/data/output"

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir $OUTPUT \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5 \
    --save_total_limit 3 \
    --learning_rate 2e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 8000 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed finetune/ds_config_zero2.json （由于报错，已注释此行）

### 期望行为 | Expected Behavior

期望可以不报oom

### 复现方法 | Steps To Reproduce

sh finetune_lora_ds.sh

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yorhaha** [comment]
我也遇到了类似的的问题，两张 40G，超参数都尽可能小了，还是 OOM。

目前我暂时用 Qwen-14B-Int4 进行 qlora 微调。

**Comment by 13361619575** [comment]
> 我也遇到了类似的的问题，两张 40G，超参数都尽可能小了，还是 OOM。
> 
> 目前我暂时用 Qwen-14B-Int4 进行 qlora 微调。

对了你用的finetune_lora_ds.sh这个脚本还是finetune_ds.sh这个脚本

**Comment by yorhaha** [comment]
finetune_lora_ds

**Comment by 13361619575** [comment]
> 我也遇到了类似的的问题，两张 40G，超参数都尽可能小了，还是 OOM。
> 
> 目前我暂时用 Qwen-14B-Int4 进行 qlora 微调。

你的数据长度比较短吗，int4的话处理不了长数据吧

**Comment by yorhaha** [comment]
int4 跟 max_length 有关吗？我数据最长不到 1000 token

**Comment by 13361619575** [comment]
> int4 跟 max_length 有关吗？我数据最长不到 1000 token
1000的话应该没问题。方便加个联系方式吗，有时间一起讨论一下

**Comment by 13361619575** [comment]
> int4 跟 max_length 有关吗？我数据最长不到 1000 token

我的qq：1060921510

**Comment by JustinLin610** [comment]
deepspeed那行加上报什么错

**Comment by liuliu1024** [comment]
请问千问chat-14b的多轮数据集格式是什么样子

**Comment by 13361619575** [comment]
> 请问千问chat-14b的多轮数据集格式是什么样子

一直往后加这个对话数量就可以了吧

**Comment by liuliu1024** [comment]
我理解所有的数据都在一个大的list里，单轮就按照提供的例子那样往下写，但是多轮要有历史信息，那以一个3轮对话为例数据集构建，不知道这样写对不对：[
    {
    "id":"id_0",
    "conversations": [
    {
    "from":"user",
    "value":"你好"
    },
    {
    "from":"assistant",
    "value":"你好！很高兴为你提供帮助。
    "
    }
    ]
    },
    {
    "id":"id_1",
    "conversations": [
    {
    "from":"user",
    "value":"你好"
    },
    {
    "from":"assistant",
    "value":"你好！很高兴为你提供帮助。
    "
    },
    {
    "from":"user",
    "value":"给我讲一个年轻人奋斗创业最终取得成功的故事。"
    },
    {
    "from":"assistant",
    "value":"这是一个关于一个年轻人奋斗创业最终取得成功的故事。故事的主人公叫李明，他来自一个普通的家庭，父母都是普通的工人。从小，李明就立下了一个目标：要成为一名成功的企业家。为了实现这个目标，李明勤奋学习，考上了大学。在大学期间，他积极参加各种创业比赛，获得了不少奖项。他还利用课余时间去实习，积累了宝贵的经验。毕业后，李明决定开始自己的创业之路。他开始寻找投资机会，但多次都被拒绝了。然而，他并没有放弃。他继续努力，不断改进自己的创业计划，并寻找新的投资机会。最终，李明成功地获得了一笔投资，开始了自己的创业之路。他成立了一家科技公司，专注于开发新型软件。在他的领导下，公司迅速发展起来，成为了一家成功的科技企业。李明的成功并不是偶然的。他勤奋、坚韧、勇于冒险，不断学习和改进自己。他的成功也证明了，只要努力奋斗，任何人都有可能取得成功。
    "
    }
    ]
    },
    {
    "id":"id_2",
    "conversations": [
    {
    "from":"user",
    "value":"你好"
    },
    {
    "from":"assistant",
    "value":"你好！很高兴为你提供帮助。"
    },
    {
    "from":"user",
    "value":"给我讲一个年轻人奋斗创业最终取得成功的故事。"
    },
    {
    "from":"assistant",
    "value":"这是一个关于一个年轻人奋斗创业最终取得成功的故事。故事的主人公叫李明，他来自一个普通的家庭，父母都是普通的工人。从小，李明就立下了一个目标：要成为一名成功的企业家。为了实现这个目标，李明勤奋学习，考上了大学。在大学期间，他积极参加各种创业比赛，获得了不少奖项。他还利用课余时间去实习，积累了宝贵的经验。毕业后，李明决定开始自己的创业之路。他开始寻找投资机会，但多次都被拒绝了。然而，他并没有放弃。他继续努力，不断改进自己的创业计划，并寻找新的投资机会。最终，李明成功地获得了一笔投资，开始了自己的创业之路。他成立了一家科技公司，专注于开发新型软件。在他的领导下，公司迅速发展起来，成为了一家成功的科技企业。李明的成功并不是偶然的。他勤奋、坚韧、勇于冒险，不断学习和改进自己。他的成功也证明了，只要努力奋斗，任何人都有可能取得成功。
    "
    },
    {
    "from":"user",
    "value":"给这个故事起一个标题"
    },
    {
    "from":"assistant",
    "value":"《奋斗创业：一个年轻人的成功之路》
    "
    }
    ]
    }
    ]

**Comment by 13361619575** [comment]
> 我理解所有的数据都在一个大的list里，单轮就按照提供的例子那样往下写，但是多轮要有历史信息，那以一个3轮对话为例数据集构建，不知道这样写对不对：[ { "id":"id_0", "conversations": [ { "from":"user", "value":"你好" }, { "from":"assistant", "value":"你好！很高兴为你提供帮助。 " } ] }, { "id":"id_1", "conversations": [ { "from":"user", "value":"你好" }, { "from":"assistant", "value":"你好！很高兴为你提供帮助。 " }, { "from":"user", "value":"给我讲一个年轻人奋斗创业最终取得成功的故事。" }, { "from":"assistant", "value":"这是一个关于一个年轻人奋斗创业最终取得成功的故事。故事的主人公叫李明，他来自一个普通的家庭，父母都是普通的工人。从小，李明就立下了一个目标：要成为一名成功的企业家。为了实现这个目标，李明勤奋学习，考上了大学。在大学期间，他积极参加各种创业比赛，获得了不少奖项。他还利用课余时间去实习，积累了宝贵的经验。毕业后，李明决定开始自己的创业之路。他开始寻找投资机会，但多次都被拒绝了。然而，他并没有放弃。他继续努力，不断改进自己的创业计划，并寻找新的投资机会。最终，李明成功地获得了一笔投资，开始了自己的创业之路。他成立了一家科技公司，专注于开发新型软件。在他的领导下，公司迅速发展起来，成为了一家成功的科技企业。李明的成功并不是偶然的。他勤奋、坚韧、勇于冒险，不断学习和改进自己。他的成功也证明了，只要努力奋斗，任何人都有可能取得成功。 " } ] }, { "id":"id_2", "conversations": [ { "from":"user", "value":"你好" }, { "from":"assistant", "value":"你好！很高兴为你提供帮助。" }, { "from":"user", "value":"给我讲一个年轻人奋斗创业最终取得成功的故事。" }, { "from":"assistant", "value":"这是一个关于一个年轻人奋斗创业最终取得成功的故事。故事的主人公叫李明，他来自一个普通的家庭，父母都是普通的工人。从小，李明就立下了一个目标：要成为一名成功的企业家。为了实现这个目标，李明勤奋学习，考上了大学。在大学期间，他积极参加各种创业比赛，获得了不少奖项。他还利用课余时间去实习，积累了宝贵的经验。毕业后，李明决定开始自己的创业之路。他开始寻找投资机会，但多次都被拒绝了。然而，他并没有放弃。他继续努力，不断改进自己的创业计划，并寻找新的投资机会。最终，李明成功地获得了一笔投资，开始了自己的创业之路。他成立了一家科技公司，专注于开发新型软件。在他的领导下，公司迅速发展起来，成为了一家成功的科技企业。李明的成功并不是偶然的。他勤奋、坚韧、勇于冒险，不断学习和改进自己。他的成功也证明了，只要努力奋斗，任何人都有可能取得成功。 " }, { "from":"user", "value":"给这个故事起一个标题" }, { "from":"assistant", "value":"《奋斗创业：一个年轻人的成功之路》 " } ] } ]

对的，我认为也是这样的

**Comment by liuliu1024** [comment]
求问加载14b-chat模型到一多半，出现报错Error while deserializing header: MetadataIncompleteBuffer是什么原因

**Comment by 13361619575** [comment]
> 求问加载14b-chat模型到一多半，出现报错Error while deserializing header: MetadataIncompleteBuffer是什么原因

是不是模型文件残缺了呀，对比一下你下载的模型和huggingface上的各个模型文件大小一致吗

**Comment by ghqing0310** [comment]
> 求问加载14b-chat模型到一多半，出现报错Error while deserializing header: MetadataIncompleteBuffer是什么原因

请问解决了吗？我遇到了同样的问题

**Comment by 13361619575** [comment]
> > 求问加载14b-chat模型到一多半，出现报错Error while deserializing header: MetadataIncompleteBuffer是什么原因
> 
> 请问解决了吗？我遇到了同样的问题

后来把deepspeed的state改成了1，返现模型文件成了原来的一半，应该是有点问题的，于是采用了单卡微调
