### ISSUE TITLE
Qwen14b-int4模型输出时会出现循环输出现象，请问如何设置参数调整。

### ISSUE THREAD

**Issue by wertyac** [QwenLM/Qwen#432]
python版本：3.10
transformer：4.32.0
torch：2.0.1
模型版本：Qwen14b-chat-int4.

请问如何调整参数能够避免这个问题？

**Comment by JustinLin610** [comment]
具体循环输出的case给我们复现一下？

**Comment by lucasjinreal** [comment]
调整不了，chat 上下文长度是2k，ntk似乎也扩展不了太长，上下文一长肯定就胡言乱语了。

我基于底座，sft 4k的长度，似乎也无法解决停止符之前多余的输出问题，总是有一段乱七八糟的文本，前面一部分是对的。

**Comment by hnlp1993** [comment]
> 调整不了，chat 上下文长度是2k，ntk似乎也扩展不了太长，上下文一长肯定就胡言乱语了。
> 
> 我基于底座，sft 4k的长度，似乎也无法解决停止符之前多余的输出问题，总是有一段乱七八糟的文本，前面一部分是对的。

如果无法解决停止符的问题，考虑是不是response定义一下stop_tokens_id 。

**Comment by nne998** [comment]
我这边也会哈，例子：

···
 ## 14b-int4
tokenizer = AutoTokenizer.from_pretrained("qwen/Qwen-14B-Chat-Int4",  trust_remote_code=True,revision='v1.0.5')
model = AutoModelForCausalLM.from_pretrained("qwen/Qwen-14B-Chat-Int4", device_map="auto", offload_folder="~/.cache", trust_remote_code=True, revision='v1.0.5',fp16=True).eval()
model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-14B-Chat-Int4", revision='v1.0.5', trust_remote_code=True) # 可指定不同的生成长度、top_p等相关超参
model.generation_config.max_new_tokens=8192
model.generation_config.max_length=8192



提问：小学100个单词， 输出：英文、中文翻译

返回：
1. apple 苹果
2. book 书
3. cat 猫
4. dog 狗
5. elephant 大象
6. fish 鱼
7. giraffe 长颈鹿
8. hat 帽子
9. ice cream 冰淇淋
10. juice 果汁
11. kite 风筝
12. lemon 柠檬
13. monkey 猴子
14. nose 鼻子
15. orange 橙子
16. pizza 披萨
17. queen 女王
18. rabbit 兔子
19. sun 太阳
20. tree 树
21. umbrella 雨伞
22. violin 小提琴
23. water 水
24. xylophone 木琴
25. yellow 黄色
26. zoo 动物园
27. ant 蚂蚁
28. ball 球
29. car 汽车
30. desk 书桌
31. elephant 大象
32. fan 风扇
33. guitar 吉他
34. hat 帽子
35. ice cream 冰淇淋
36. juice 果汁
37. kite 风筝
38. lemon 柠檬
39. monkey 猴子
40. nose 鼻子
41. orange 橙子
42. pizza 披萨
43. queen 女王
44. rabbit 兔子
45. sun 太阳
46. tree 树
47. umbrella 雨伞
48. violin 小提琴
49. water 水
50. xylophone 木琴
51. yellow 黄色
52. zoo 动物园
53. ball 球
54. car 汽车
55. desk 书桌
56. elephant 大象
57. fan 风扇
58. guitar 吉他
59. hat 帽子
60. ice cream 冰淇淋
61. juice 果汁
62. kite 风筝
63. lemon 柠檬
64. monkey 猴子
65. nose 鼻子
66. orange 橙子
67. pizza 披萨
68. queen 女王
69. rabbit 兔子
70. sun 太阳
71. tree 树
72. umbrella 雨伞
73. violin 小提琴
74. water 水
75. xylophone 木琴
76. yellow 黄色
77. zoo 动物园
78. ball 球
79. car 汽车
80. desk 书桌
81. elephant 大象
82. fan 风扇
83. guitar 吉他
84. hat 帽子
85. ice cream 冰淇淋
86. juice 果汁
87. kite 风筝
88. lemon 柠檬
89. monkey 猴子
90. nose 鼻子
91. orange 橙子
92. pizza 披萨
93. queen 女王
94. rabbit 兔子
95. sun 太阳
96. tree 树
97. umbrella 雨伞
98. violin 小提琴
99. water 水
100. xylophone 木琴
···

有好多重复的。


> 具体循环输出的case给我们复现一下？

**Comment by lucasjinreal** [comment]
只有2k，要更长的可以自己微调到4k

**Comment by jklj077** [comment]
对于循环输出问题，开源模型配置文件中的参数已进行了更新，建议根据实际需求调调repetition_penalty这个参数，能够基本排除该现象（在chat模型的generation_config.json里，也可以代码中传入）。
