### ISSUE TITLE
[BUG] <title>能支持下v100 做finetune么

### ISSUE THREAD

**Issue by qweasdzxc110** [QwenLM/Qwen#434]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

能支持下v100 做finetune么，能不能把flash attn 做成可设置开启关闭的选项啊

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
只需要把config里面的use_flash_attn设成false，我们这边也弄个finetune脚本的开关吧。
