### ISSUE TITLE
💡 [REQUEST] NTK support

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen#439]
### 摘要 | Summary

在长文本下，Qwen14B很容易出现重复内容，不知道是 上下文长度不够呢还是？

### 基本示例 | Basic Example

在长文本下，Qwen14B很容易出现重复内容，不知道是 上下文长度不够呢还是？

### 缺陷 | Drawbacks

在长文本下，Qwen14B很容易出现重复内容，不知道是 上下文长度不够呢还是？

**Comment by lucasjinreal** [comment]
对，chat模型上下文一多就开始重复了，貌似完全没有到8k，而且base 模型 sft 之后 停不下来 用的是官方的finetune 脚本

**Comment by JustinLin610** [comment]
几个原因，模型本身重复可能是一方面，可以拉最新的generation config得到缓解。第二是长序列问题，通过ntk扩展在实际场景可能扩不到很长。第三是finetune的问题，这比较难判断，也得看数据本身有没问题，另外也看训练是否有出问题的地方

**Comment by jklj077** [comment]
In the recently unveiled Qwen1.5 release, we have implemented a strategic shift in handling long-context extensions. This update involves phasing out the use of dynamic-NTK and logn attention mechanisms. With this new version, all Qwen1.5 models boast enhanced capability, supporting sequence length up to 32K tokens.

For comprehensive discussions about these changes, further details on the updated architecture, and any related inquiries, please visit the official Qwen1.5 GitHub repository at <https://github.com/QwenLM/Qwen1.5>.
