### ISSUE TITLE
[BUG] Qwen14b sft model can not stop

### ISSUE THREAD

**Issue by OpenJarvisAI** [QwenLM/Qwen#441]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I using base model sft a chat model, the model can not stop, but the first serveral words are correct.

I think it have some in stop words, how to fix it???

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Hi, could you please provide the scripts used for fine-tuning and inference so that we can look into this issue?
With the scripts provided in this repo, we have not encountered such problems yet.

**Comment by jklj077** [comment]
Please reopen this if you could provide us with more information. Using the fine-tuning code and the inference code in this repo, we have not encountered the issue.
