### ISSUE TITLE
react_demo.py脚本无法访问互联网

### ISSUE THREAD

**Issue by cristianohello** [QwenLM/Qwen#445]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

react_demo.py脚本无法访问互联网

### 期望行为 | Expected Behavior

访问互联网

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

![NMlu5tleNa](https://github.com/QwenLM/Qwen/assets/109277248/da16bb76-ea84-4600-a612-773938228159)

**Comment by JianxinMa** [comment]
看起来是新的badcases。这个react_demo.py是按老ckpt写的，新ckpt可能因为一些别的算法优化影响部分原有能力 —— 尽管agent能力总体上是变强的，但个别cases可能变弱了，算法优化总是这么世事难料。

我试着在问题里加上“查一下”、“搜一下”，比如“查一下周杰伦是谁”就能调起搜索了。我稍后更新下脚本。

**Comment by JianxinMa** [comment]
https://github.com/QwenLM/Qwen/commit/8da5dc0cbdffd893eb04c6ec30859e818897166b

**Comment by cristianohello** [comment]
@JianxinMa 
你好，def call_plugin(plugin_name: str, plugin_args: str) -> str:
    #
    # 请开发者自行完善这部分内容。这里的参考实现仅是 demo 用途，非生产用途。
    #
    if plugin_name == 'google_search':
        # 使用 SerpAPI 需要在这里填入您的 SERPAPI_API_KEY！
        os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='')
        from langchain import SerpAPIWrapper

这个应该怎么改？

我这有改可以吗？
def call_plugin(plugin_name: str, plugin_args: str) -> str:
    #
    # 请开发者自行完善这部分内容。这里的参考实现仅是 demo 用途，非生产用途。
    #
    if plugin_name == 'google_search':
        # 使用 SerpAPI 需要在这里填入您的 SERPAPI_API_KEY！
        #os.environ["SERPAPI_API_KEY"] = 'fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd'
        os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd')
        from langchain import SerpAPIWrapper

**Comment by cristianohello** [comment]
@JianxinMa 
你好，def call_plugin(plugin_name: str, plugin_args: str) -> str:
    #
    # 请开发者自行完善这部分内容。这里的参考实现仅是 demo 用途，非生产用途。
    #
    if plugin_name == 'google_search':
        # 使用 SerpAPI 需要在这里填入您的 SERPAPI_API_KEY！
        os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='')
        from langchain import SerpAPIWrapper

这个应该怎么改？

我这有改可以吗？
def call_plugin(plugin_name: str, plugin_args: str) -> str:
    #
    # 请开发者自行完善这部分内容。这里的参考实现仅是 demo 用途，非生产用途。
    #
    if plugin_name == 'google_search':
        # 使用 SerpAPI 需要在这里填入您的 SERPAPI_API_KEY！
        #os.environ["SERPAPI_API_KEY"] = 'fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd'
        os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd')
        from langchain import SerpAPIWrapper

**Comment by cristianohello** [comment]
@JianxinMa 
谷歌搜索改怎么填？
我这有改可以吗？
def call_plugin(plugin_name: str, plugin_args: str) -> str:
#
# 请开发者自行完善这部分内容。这里的参考实现仅是 demo 用途，非生产用途。
#
if plugin_name == 'google_search':
# 使用 SerpAPI 需要在这里填入您的 SERPAPI_API_KEY！
#os.environ["SERPAPI_API_KEY"] = 'fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd'
os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd')
from langchain import SerpAPIWrapper

**Comment by cristianohello** [comment]
@JianxinMa 
我用的14B模型。

还是没有调用搜索引擎

User's Query:
查一下谁是周杰伦

Qwen's Response:
Thought: 提供的工具帮助较小，我将直接回答。
Final Answer: 周杰伦是一位著名的华语流行歌手、音乐制作人、演员和导演，出生于台湾省新北市。他的音乐作品深受广大听众喜爱，曾多次获得金曲奖等音乐奖项。除了音乐事业，他还涉足电影和电视剧的拍摄，是一位多才多艺的艺人。

User's Query:
搜下他老婆是谁


Qwen's Response:
Thought: 提供的工具帮助较小，我将直接回答。
Final Answer: 周杰伦的妻子是昆凌。昆凌是一位台湾女演员和模特，出生于台湾省台北市。她与周杰伦于2015年结婚，并育有一子一女。昆凌曾参演过多部电影和电视剧，是一位备受瞩目的女艺人。

User's Query:
给我画个可爱的小猫吧，最好是黑猫

Qwen's Response:
Thought: 提供的工具帮助较小，我将直接回答。
Final Answer: 对不起，我无法使用图像生成工具为您画图。我是一个文本生成的AI助手，无法直接生成图像。如果您有其他问题需要帮助，请随时告诉我
