### ISSUE TITLE
💡 [REQUEST] 请问千问chat-14b的多轮数据集格式是什么样子

### ISSUE THREAD

**Issue by liuliu1024** [QwenLM/Qwen#447]
### 摘要 | Summary

请问千问chat-14b的多轮数据集格式是什么样子

### 基本示例 | Basic Example

数据集格式

### 缺陷 | Drawbacks

数据集格式

**Comment by jklj077** [comment]
请参考README中finetune部分的说明，https://github.com/QwenLM/Qwen#usage-2
