### ISSUE TITLE
[BUG] 多显卡 CUDA out of memory

### ISSUE THREAD

**Issue by Aix-chengjie** [QwenLM/Qwen#450]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

# 问题：多显卡运行Qwen-14B-Chat-Int4时CUDA out of memory

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.45 GiB (GPU 1; 8.00 GiB total capacity; 5.91 GiB already allocated; 1.03 GiB free; 5.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

![image](https://github.com/QwenLM/Qwen/assets/72543836/c2d8f0c4-6c9c-4234-b0a5-127782b1dfd8)

![image](https://github.com/QwenLM/Qwen/assets/72543836/214235bf-8cd4-43fc-82ed-fd1b9afbe499)

问题：两种显卡16G，理论上能运行int4的模型。 但实际上未成功。
图上第一张显卡的内存只用了2g就没分配了，为啥不在那上面分配呢。

求大佬帮忙康康！

### 期望行为 | Expected Behavior

加载模型时，两张显卡均分显存。

### 复现方法 | Steps To Reproduce

`python  openai_api.py `

### 运行环境 | Environment

```Markdown
- OS:windows10
- Python:3.11
- Transformers:4.33.3
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

补充：跑chatglm2-6b完整模型时，会两张显卡均分显存。不知道为啥qwen不会

**Comment by JustinLin610** [comment]
提供一下运行命令吧，直接from_pretrained?

**Comment by Aix-chengjie** [comment]
> 提供一下运行命令吧，直接from_pretrained?

对 就算README里的标准示例，直接from_pretrained。

现在我用utils里的 load_model_on_gpus方法，也跑起来勒。

**Comment by jichaosun001** [comment]
我用两张3090，全精度infer，对话轮次多的时候也是这样，其中一张卡满了，另一张卡还有很多显存可以用，请问你这个最后怎么解决的

**Comment by Aix-chengjie** [comment]
> 我用两张3090，全精度infer，对话轮次多的时候也是这样，其中一张卡满了，另一张卡还有很多显存可以用，请问你这个最后怎么解决的

用utils里的 load_model_on_gpus方法。 这样会把模型拆分到两个显卡。 但推理速度会下降，因为拆分了两个显卡要互相通信。 你也可以试试官方文档里的vllm。

**Comment by jichaosun001** [comment]
> > 我用两张3090，全精度infer，对话轮次多的时候也是这样，其中一张卡满了，另一张卡还有很多显存可以用，请问你这个最后怎么解决的
> 
> 用utils里的 load_model_on_gpus方法。 这样会把模型拆分到两个显卡。 但推理速度会下降，因为拆分了两个显卡要互相通信。 你也可以试试官方文档里的vllm。

感谢，已成功分配显存
