### ISSUE TITLE
How should I resume finetuning from a saved checkpoint?

### ISSUE THREAD

**Issue by tiendung** [QwenLM/Qwen#451]
Look like current `finetune.py` don't support resume training yet?

**Comment by tiendung** [comment]
It's full finetune. I've add some code to make it resumable.

**Comment by renllll** [comment]
请问是如何解决的

**Comment by mikeleatila** [comment]
@JustinLin610 @tiendung @renllll Has this been fixed yet? I have not been able to resume finetuning from a checkpoint yet. If I use --resume_from_checkpoint CHECKPOINT_DIR in finetune_lora_ds.sh script it starts from the beginning.
