### ISSUE TITLE
[BUG] web_demo是否存在BUG ，生成的内容不能持久显示

### ISSUE THREAD

**Issue by tanglu86** [QwenLM/Qwen#452]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

通过web_demo.py跑通14B-CHAT模型以后进行正常问答，生成的内容在前端页面显示了大概不到1秒就立即消失了，通过后台日志可以看到内容，反复测试都是这样的
![2](https://github.com/QwenLM/Qwen/assets/38269740/145dbbf1-6926-4a98-a2d2-a62b65583db5)
![1](https://github.com/QwenLM/Qwen/assets/38269740/29bfc794-c5be-4e60-852c-8d0e6f32cbb5)

### 运行环境 | Environment

```Markdown
- OS:CentOS 7 
- Python:Python 3.10
- Transformers: 4.32
- PyTorch:2.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

_No response_

**Comment by tanglu86** [comment]
已解决 gradio版本问题 3.47.1下会出现

**Comment by greagain** [comment]
上面的问题有解决方案吗？我这里类似，但似乎生成的内容根本不出现，而且除了第一轮的输入外，其他的对话都完全不在web页面上显示。

**Comment by tanglu86** [comment]
> gradio版本问题 3.47.1下会出现

gradio版本问题 3.47.1下会出现

**Comment by tanglu86** [comment]
> 上面的问题有解决方案吗？我这里类似，但似乎生成的内容根本不出现，而且除了第一轮的输入外，其他的对话都完全不在web页面上显示。

gradio版本问题 如果版本高于3.43就会出现这样的问题

**Comment by hhk123** [comment]
我是3.41.0，网页显示没问题，在同一台机器用nginx代理也没问题，但是在不同的机器用nginx代理就会出现这种内容不能持久显示的问题
