### ISSUE TITLE
react_demo.py的谷歌搜索该怎么填？

### ISSUE THREAD

**Issue by cristianohello** [QwenLM/Qwen#456]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

谷歌搜索改怎么填？
我这有改可以吗？
def call_plugin(plugin_name: str, plugin_args: str) -> str:

请开发者自行完善这部分内容。这里的参考实现仅是 demo 用途，非生产用途。
if plugin_name == 'google_search':

使用 SerpAPI 需要在这里填入您的 SERPAPI_API_KEY！
#os.environ["SERPAPI_API_KEY"] = 'fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd'
os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd')
from langchain import SerpAPIWrapper

### 期望行为 | Expected Behavior

无

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

无

**Comment by JianxinMa** [comment]
您好，我试了按您的写法：
```py
os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY", default='fba9b972e1925ac06654fe21af76bab2f4d8c5e676cbdcd7f1d344472a3577fd')
from langchain import SerpAPIWrapper
```
应该是能跑通的。如果没跑通，可能需要确认下是否有额外的依赖未安装，比如
```bash
pip install langchain google-search-results
```
