### ISSUE TITLE
[BUG] 显存在模型运行结束仍然有超过启动时候的显存占用

### ISSUE THREAD

**Issue by mawenju203** [QwenLM/Qwen#457]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

启动目标：测试长文本的处理能力

Qwen-7b-int4
![image](https://github.com/QwenLM/Qwen/assets/30227934/2867a274-ec83-48ac-828c-a25bba49714e)

测试的字符串长度为8192
程序结束后：显存占用；
![image](https://github.com/QwenLM/Qwen/assets/30227934/08a0c7df-d0ec-45b0-98dc-7db86f81c426)

### 期望行为 | Expected Behavior

不应该执行结束之后，显存恢复到最低吗？
当批量进行测试的时候，很容易产生显存不足的问题；并不是你们介绍的
![image](https://github.com/QwenLM/Qwen/assets/30227934/c4143d21-579f-43de-8f1a-78620cec2ffa)

不知道什么时候能修复一下显存泄露的问题。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
1. PyTorch有自己GPU显存管理机制，请参见[官方文档](https://pytorch.org/docs/stable/generated/torch.cuda.empty_cache.html)，其实该部分显存并未占用，后续使用中也会被复用。要准确测量GPU显存占用的话，PyTorch提供了相关函数，使用请参见README中提供的[profile脚本](https://qianwen-res.oss-cn-beijing.aliyuncs.com/profile.py)。
2. 怀疑是FlashAttention导致的差异，README中给出的是开启了FlashAttention的数值，我们也看下。

**Comment by JustinLin610** [comment]
应该是flash attention带来的差异，flash attention对推理的时候显存能节省

**Comment by mawenju203** [comment]
抱歉才看到，@jklj077  @JustinLin610  我的系统中并未使用flash attention；因为这个在linux上面安装的时候报错了；不影响我的使用；
