### ISSUE TITLE
[BUG] <加载int4量化模型的时候提示cannot import name 'flash_attn_func' from 'flash_attn'>

### ISSUE THREAD

**Issue by zhaozhaoxia** [QwenLM/Qwen#460]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

加载14b-chat-int4　模型的时候，提示
ImportError: cannot import name 'flash_attn_func' from 'flash_attn' (/opt/conda/lib/python3.8/site-packages/flash_attn/__init__.py)

### 期望行为 | Expected Behavior

首次加载还ｏｋ，隔了一天后在环境中安装了vllm，然后再次加载模型发生上述问题

### 复现方法 | Steps To Reproduce

no

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

no

**Comment by jklj077** [comment]
> 首次加载还ｏｋ，隔了一天后在环境中安装了vllm，然后再次加载模型发生上述问题

可能是安装vllm时，破环了软件环境，建议用clean环境，按README中的使用说明再试试。

**Comment by zhaozhaoxia** [comment]
flash attention版本太高，安装vllm的时候被强制升级到4.34.0版本，需要下降到4.33.1即可
