### ISSUE TITLE
[BUG] 使用模型：Qwen-7B-Chat-Int4，尝试cpu启动，出错

### ISSUE THREAD

**Issue by zhoushewei** [QwenLM/Qwen#461]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

tokenizer = AutoTokenizer.from_pretrained("../models/llm/Qwen-7B-Chat-Int4" , trust_remote_code=True)
print("启动开始时间：" + str(datetime.datetime.now()))
model = AutoModelForCausalLM.from_pretrained(
    "../models/llm/chatCattv4-7B-int4",
    device_map="cpu",
    offload_folder="offload_folder", 
    trust_remote_code=True,
    fp32=True,

    fp16 = False,
    bf16=False
    #use_cache_quantization=True,
    #use_flash_attn=False
).eval()

  File "/home/catt/miniconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/catt/miniconda3/envs/py39/lib/python3.9/site-packages/auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py", line 221, in forward
    self.autogptq_cuda.vecquant4matmul_old(x, self.qweight, out, self.scales.float(), self.qzeros, self.group_size)
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/usr/share/miniconda/envs/build/lib/python3.9/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":25, please report a bug to PyTorch. 

### 运行环境 | Environment

```Markdown
OS: Ubuntu 20.04
Python: 3.9
Transformers: 4.31.0
PyTorch: 2.0.1
CUDA: 11.4
```

**Comment by jklj077** [comment]
量化模型现在方式是AutoGPQ，是不支持CPU推理的哈。如果有CPU运行量化模型的需求，建议您看下qwen.cpp，https://github.com/QwenLM/qwen.cpp
