### ISSUE TITLE
Error while deserializing header: MetadataIncompleteBuffer  [BUG] <title>

### ISSUE THREAD

**Issue by liuliu1024** [QwenLM/Qwen#462]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

求问加载14b-chat模型到一多半，出现报错Error while deserializing header: MetadataIncompleteBuffer是什么原因

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

求问加载14b-chat模型到一多半，出现报错Error while deserializing header: MetadataIncompleteBuffer是什么原因

**Comment by jklj077** [comment]
嗯，这个是safetensors报的错，应该是模型参数下坏了，一般重新下载即可。

**Comment by Sakurakdx** [comment]
我也是加载官方的llama报错了，请问重新下载解决了吗？

**Comment by jklj077** [comment]
> 我也是加载官方的llama报错了

没太理解，我们不是llama

**Comment by wbning** [comment]
> 嗯，这个是safetensors报的错，应该是模型参数下坏了，一般重新下载即可。

如果模型参数坏了，为啥之前推理和训练都能正常进行呢？
