### ISSUE TITLE
[BUG] 使用 AutoGPTQ 量化 Qwen-14B 后，加载量化的模型推理失败，报错：RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat

### ISSUE THREAD

**Issue by edisonwd** [QwenLM/Qwen#464]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1、使用 AutoGPTQ 给出的示例代码量化 Qwen-14B，量化后得到如下几个文件
![image](https://github.com/QwenLM/Qwen/assets/25941671/f6527869-f268-4fbb-8775-f4a3b5728c1b)
2、使用 `tokenizer.save_pretrained(quantized_model_dir)` 将 tokenizer 相关的配置文件保存到量化文件目录中，
3、将 Qwen-14B 中的其他配置文件 `modeling_qwen.py`、`qwen_generation_utils.py`、`generation_config.json` 复制到量化文件目录中
4、使用`model = AutoGPTQForCausalLM.from_pretrained(pretrained_model_name, 
                                            quantize_config, 
                                            trust_remote_code=True)` 能够正常加载量化模型
5、使用`print(tokenizer.decode(model.generate(**tokenizer("auto_gptq is", return_tensors="pt").to(model.device))[0]))
` 进行推理，报错如下：
```
RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
```

### 期望行为 | Expected Behavior

正常返回模型推理结果

### 复现方法 | Steps To Reproduce

1、量化模型代码如下：
```python

from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
from transformers import AutoTokenizer

pretrained_model_name = "Qwen-14B"
quantized_model_dir = 'Qwen-14B-4bit-gptq'

quantize_config = BaseQuantizeConfig(
    bits=4,  # 将模型量化为 4-bit 数值类型
    group_size=128,  # 一般推荐将此参数的值设置为 128
    desc_act=False,  # 设为 False 可以显著提升推理速度，但是 ppl 可能会轻微地变差
)

model = AutoGPTQForCausalLM.from_pretrained(pretrained_model_name, 
                                            quantize_config, 
                                            trust_remote_code=True)

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name, 
                                          use_fast=True, 
                                          trust_remote_code=True)

examples = [
    tokenizer(
        "Auto-GPTQ 是一个简单易用的模型量化库，基于 GPTQ 算法，具有用户友好的 API。"
    )
]

model.quantize(examples)

model.save_quantized(quantized_model_dir, use_safetensors=True)
tokenizer.save_pretrained(quantized_model_dir)
```
2、加载量化模型代码如下：
```python
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

from transformers import AutoTokenizer, GenerationConfig

quantized_model_dir = 'Qwen-14B-4bit-gptq'
tokenizer = AutoTokenizer.from_pretrained(quantized_model_dir,use_fast=True, trust_remote_code=True)
model = AutoGPTQForCausalLM.from_quantized(quantized_model_dir,  
                                           device_map="auto", 
                                           use_safetensors=False, 
                                           trust_remote_code=True)

print(tokenizer)
print(model)


```
3、模型推理代码如下：
```python

print(tokenizer.decode(model.generate(**tokenizer("auto_gptq is", return_tensors="pt").to(model.device))[0]))

```
4、报错信息如下：
```
RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
```

### 运行环境 | Environment

```Markdown
- OS: Linux
- Python: 3.8.16
- torch==2.0.1
- CUDA Version: 11.7
- transformers==4.32.0
- transformers-stream-generator==0.0.4
- auto-gptq==0.4.2
```

**Comment by Originhhh** [comment]
我没有遇到相同的问题，但是量化后的模型，会在生成我想要的答案后胡乱进行输出，不知道你有没有遇到类似的情况呢

**Comment by edisonwd** [comment]
> 我没有遇到相同的问题，但是量化后的模型，会在生成我想要的答案后胡乱进行输出，不知道你有没有遇到类似的情况呢

请问一下你是怎么量化的呢

**Comment by Originhhh** [comment]
> > 我没有遇到相同的问题，但是量化后的模型，会在生成我想要的答案后胡乱进行输出，不知道你有没有遇到类似的情况呢
> 
> 请问一下你是怎么量化的呢

我就是按照你上面写的流程进行量化的，量化代码和您的稍有不同，是autogptq进阶量化代码

**Comment by AppleJunJiang** [comment]
我量化后的模型，只能用AutoGPTQForCausalLM加载，不能用官方说的AutoModelForCausalLM直接加载，而且量化后的模型反而速度慢很多很多。。。

**Comment by edisonwd** [comment]
> 我量化后的模型，只能用AutoGPTQForCausalLM加载，不能用官方说的AutoModelForCausalLM直接加载，而且量化后的模型反而速度慢很多很多。。。

请问一下，你量化后的模型使用的 `modeling_qwen.py` 是使用的哪个文件呢？Qwen-14B 中的 `modeling_qwen.py`吗？

**Comment by zhaozhaoxia** [comment]
量化的transformers版本能选择低版本的吗？？版本太高，后期同向量数据库结合的时候不太兼容(比如faiss-gpu)

**Comment by edisonwd** [comment]
这个问题已经解决了，通过使用下面的命令，卸载flash-attn就可以正常加载模型和推理了
```
pip uninstall flash-attn
```

**Comment by AppleJunJiang** [comment]
> > 我量化后的模型，只能用AutoGPTQForCausalLM加载，不能用官方说的AutoModelForCausalLM直接加载，而且量化后的模型反而速度慢很多很多。。。
> 
> 请问一下，你量化后的模型使用的 `modeling_qwen.py` 是使用的哪个文件呢？Qwen-14B 中的 `modeling_qwen.py`吗？

是的，我也是直接把未量化的py复制过去的，并且把量化后的模型名字改为“pytorch_model.bin”

**Comment by Originhhh** [comment]
> > > 我量化后的模型，只能用AutoGPTQForCausalLM加载，不能用官方说的AutoModelForCausalLM直接加载，而且量化后的模型反而速度慢很多很多。。。
> > 
> > 
> > 请问一下，你量化后的模型使用的 `modeling_qwen.py` 是使用的哪个文件呢？Qwen-14B 中的 `modeling_qwen.py`吗？
> 
> 是的，我也是直接把未量化的py复制过去的，并且把量化后的模型名字改为“pytorch_model.bin”

您好，请问在使用量化后的模型时，有遇到生成额外无关内容的情况吗

**Comment by edisonwd** [comment]
> > > > 我量化后的模型，只能用AutoGPTQForCausalLM加载，不能用官方说的AutoModelForCausalLM直接加载，而且量化后的模型反而速度慢很多很多。。。
> > > 
> > > 
> > > 请问一下，你量化后的模型使用的 `modeling_qwen.py` 是使用的哪个文件呢？Qwen-14B 中的 `modeling_qwen.py`吗？
> > 
> > 
> > 是的，我也是直接把未量化的py复制过去的，并且把量化后的模型名字改为“pytorch_model.bin”
> 
> 您好，请问在使用量化后的模型时，有遇到生成额外无关内容的情况吗

有遇到这种情况，当 max_new_tokens 设置太大的时候会生成很多重复的内容

**Comment by Originhhh** [comment]
> > > > > 我量化后的模型，只能用AutoGPTQForCausalLM加载，不能用官方说的AutoModelForCausalLM直接加载，而且量化后的模型反而速度慢很多很多。。。
> > > > 
> > > > 
> > > > 请问一下，你量化后的模型使用的 `modeling_qwen.py` 是使用的哪个文件呢？Qwen-14B 中的 `modeling_qwen.py`吗？
> > > 
> > > 
> > > 是的，我也是直接把未量化的py复制过去的，并且把量化后的模型名字改为“pytorch_model.bin”
> > 
> > 
> > 您好，请问在使用量化后的模型时，有遇到生成额外无关内容的情况吗
> 
> 有遇到这种情况，当 max_new_tokens 设置太大的时候会生成很多重复的内容

好的谢谢，我尝试调小一下
