### ISSUE TITLE
[BUG] model.generate一直会生成pad_token

### ISSUE THREAD

**Issue by chenyzh28** [QwenLM/Qwen#468]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

base模型进行finetune，训练中使用tokenizer自带的pad_token（"<|endoftext|>"），用model.generate生成，即使在generation_config中指定了suppress_tokens（包含pad_token），生成结果还是会包含pad_token。

### 期望行为 | Expected Behavior

生成结果不包含pad_token。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
请提供下复现方法哈，按提供配置的话，遇到这些生成会中止的(model.generate见StopWordsLogitsProcessor)，其实也无需设置suppress_tokens（这些也是id）。

**Comment by chenyzh28** [comment]
> 请提供下复现方法哈，按提供配置的话，遇到这些生成会中止的(model.generate见StopWordsLogitsProcessor)，其实也无需设置suppress_tokens（这些也是id）。

batch generate（即num_return_sequences>1）的时候怎么抑制生成pad token呢，我用了StoppingCriteria的方法，但是发现batch generate的每个输出都是固定长度的，这就导致一些长度不够的肯定会生成padding。

**Comment by logicwong** [comment]
@chenyzh28 生成padding意味着当前句子已经生成完了吧？这时候只需要通过后处理去除padding就能拿到正确结果了。可以参照 https://github.com/QwenLM/Qwen#batch-inference 编写batch_infer的代码，里面包含后处理
