### ISSUE TITLE
Lora finetune成功後 tokenizer指定模型是哪一個? 另外不知道如何合併?或是一定要合併?

### ISSUE THREAD

**Issue by swilly0906** [QwenLM/Qwen#470]
### 起始日期 | Start Date

No response

### 实现PR | Implementation PR

No response

### 相关Issues | Reference Issues

 No response

### 摘要 | Summary

 No response

### 基本示例 | Basic Example

 No response

### 缺陷 | Drawbacks

我已經成功執行完 sh finetune/finetune_lora_single_gpu.sh
問題如**未解决问题**所述：

### 未解决问题 | Unresolved questions

問題1：
當我執行完finetune後
我的code：
```
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    "MyDrive/output_qwen", # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()
```
上面"output_qwen" 是我執行完Lora後產出的資料夾
這邊我還沒有問題

問題在於我下面code的tokenizer要指定給Lora產生的資料集嗎?還是用您們HG提供的Qwen/Qwen-14B資料集?哪一個才是正確?
我的task大多是產生SQL 
我兩個都試過了
其實大多可以產生正確的SQL程式
導致我不確定 哪一個tokenizer指定路徑才是正確?
我目前是覺得tokenizer採用Lora後的資料集 產生的SQL質量結果比較好
但其實我不確定正確答案是哪一個???
```
tokenizer = AutoTokenizer.from_pretrained("MyDrive/output_qwen", trust_remote_code=True)
inputs = tokenizer('請用SQL查詢Willy公司2023年1月總銷售額', return_tensors='pt')
inputs = inputs.to(model.device)
pred = model.generate(**inputs)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```

問題2：
您們所提供的code:
```
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()

merged_model = model.merge_and_unload()
# max_shard_size and safe serialization are not necessary. 
# They respectively work for sharding checkpoint and save the model to safetensors
merged_model.save_pretrained(new_model_directory, max_shard_size="2048MB", safe_serialization=True)
```
我覺得我應該要合併吧?因為Lora產生的資料只有800多MB
所以我認為要合併才對?但我不知道上面的code意思
當我執行完這一段:
```
model = AutoPeftModelForCausalLM.from_pretrained(
    path_to_adapter, # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()
```
代表此時model這個物件是Lora後的這個資料集結果(這邊我看得懂)
那後面執行的這段 我不太懂:
```
merged_model = model.merge_and_unload()
# max_shard_size and safe serialization are not necessary. 
# They respectively work for sharding checkpoint and save the model to safetensors
merged_model.save_pretrained(new_model_directory, max_shard_size="2048MB", safe_serialization=True)
```
model.merge_and_unload()是指合併嗎?
可是如果要合併 我應該要指定**原Qwen/Qwen-14B路徑**跟**Lora後產生的結果資料集** 這樣才能合併吧?但該code沒有指定路徑怎麼合併?我現在卡在不知道怎合併?

merged_model.save_pretrained裡面的new_model_directory 是指合併後的檔案的新路徑吧?

**Comment by jklj077** [comment]
> 問題在於我下面code的tokenizer要指定給Lora產生的資料集嗎?還是用您們HG提供的Qwen/Qwen-14B資料集?哪一個才是正確?

没有其它操作的话，tokenizer是一样的，均可使用。

> 我應該要指定原Qwen/Qwen-14B路徑跟Lora後產生的結果資料集 這樣才能合併吧

不需要额外指定的，模型保存时会记录基模型信息。

> merged_model.save_pretrained裡面的new_model_directory 是指合併後的檔案的新路徑吧?

对的，是待保存新的合并后模型的路径。

请在尝试下，如有其它问题欢迎提出！

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen/assets/27664428/62e1f35b-5867-49ff-b90e-4ef00e2adf0c)
This is enough for you. Let me explain what happens inside. Although the model checkpoints seem small as it only saves the adapters, don't worry, its configuration file records the path to your pretrained language model. When you use this interface to load, it first reads the config and loads the pretrained model, and then load the adapter. Some people want to merge them for further usage, but I think you might not need this.

**Comment by swilly0906** [comment]
@jklj077 @JustinLin610  
感謝兩位大大的解答
已經順利成功合併了
但我現在遇到兩個新問題= =
但我決定開新issue
感謝~~

**Comment by jklj077** [comment]
Glad you have resolved the issue! Tracking the new issues. This one is closed for now.

**Comment by chenhongwu127** [comment]
用lora微调qwen14B后的模型，按照说明文档合并后的模型文件和原来的模型文件一样，咋回事呢？
