### ISSUE TITLE
[BUG] 使用autogptq对微调过后的qwen-14b模型进行量化，推理速度变慢，额外生成无关内容

### ISSUE THREAD

**Issue by Originhhh** [QwenLM/Qwen#475]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我在使用autogptq对微调过后的qwen14b模型进行量化后，，发现模型推理速度变慢，且并且除了我想要的答案之外还会额外在这之后生成其他无关内容。
![image](https://github.com/QwenLM/Qwen/assets/55876617/23ab99e9-c176-4448-860e-f5267b1a8b85)
马赛克是预想生成的部分，后面的是额外生成的无关内容

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
> 除了我想要的答案之外还会额外在这之后生成其他无关内容

请提供下复现方式哈。微调后推理正常停止，但量化后推理中止异常？是都用的这个repo中的脚本吗

**Comment by JustinLin610** [comment]
autogptq做量是不是对着官方文档来做的吗？用了多少数据？

**Comment by Originhhh** [comment]
> autogptq做量是不是对着官方文档来做的吗？用了多少数据？

是按照官方去做的，分别尝试采样了128条和400条数据，都会出现输出额外无关内容的现象

**Comment by Originhhh** [comment]
目前是在生成过程中遇到换行符进行截断

**Comment by Shuigs18** [comment]
我也出现了这个问题，量化后中止异常了。。。
