### ISSUE TITLE
[BUG] 不使用flash_attn时,如果自定义model_max_length超过 max_position_embedding时会报错

### ISSUE THREAD

**Issue by ShadowTeamCN** [QwenLM/Qwen#478]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/11573254/9410e310-2627-45c4-a802-4da5ddf130f4)
![image](https://github.com/QwenLM/Qwen/assets/11573254/6d2628b5-0d97-4343-8729-b5f73901bd30)

- 这里生成了一个max_position_embeddings 的 mask ,然后遮罩时候遇到大小为model_max_length的attention
- mask大小应该修改为等于max_length或者batch_max_length

**Comment by yangapku** [comment]
您好，本身模型生成的最大长度是不应该超过max_position_embeddings的，此配置项应设置为模型能支持的最大长度。如果您希望把Qwen模型用于生成更长的序列（比如7B拓展到8K长度以上），请将这一配置项相应手动改为更大值（在不打开flash attn下此mask也对应会多占一些显存）

**Comment by ShadowTeamCN** [comment]
> 您好，本身模型生成至的最大长度是不应该超过max_position_embeddings的，此配置项应设置为模型能支持的最大长度。如果您希望把Qwen模型用于生成更长的序列（比如7B拓展到8K长度以上），请将这一配置项相应手动改为更大值（在不打开flash attn下此mask也对应会多占一些显存）

dynamic NTK 插值目的就是 增强外推性, 也就是在预训练长度之外也能保持一定效果, 感觉这个报错只是一个side effect,
正常情况下应该不会用max_position_embeddings 这个参数限制模型ctx长度?

**Comment by JustinLin610** [comment]
这个max pos emb只是不开flash的时候算attention mask用到，我理解其实是个比较trivial的东西了，我们看下把默认值放一个大点的防止出错吧

**Comment by ShadowTeamCN** [comment]
> 这个max pos emb只是不开flash的时候算attention mask用到，我理解其实是个比较trivial的东西了，我们看下把默认值放一个大点的防止出错吧

是的,不过默认值放大会影响到mask大小,进而影响显存占用, 建议根据inputs大小动态设置
