### ISSUE TITLE
[Question] <请问是否可以开放无监督Pretrain的训练脚本？>

### ISSUE THREAD

**Issue by xuexidi** [QwenLM/Qwen#479]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

您好，当前工程中只找到SFT的微调脚本，没找到无监督的Preatrain脚本，请问可以提供无监督预训练脚本吗？非常感谢！

### 期望行为 | Expected Behavior

期望能够开源无监督预训练脚本，感谢！！！

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python: 3.10.12
- Transformers:4.32.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

### 备注 | Anything else?

当前已跑通SFT的训练脚本，想要自己尝试一下无监督预训练环节，请问是否可以提供无监督预训练(Pretrain)脚本？谢谢！

**Comment by JustinLin610** [comment]
有点麻烦，得改dataset构造，等等吧

**Comment by xuexidi** [comment]
> 有点麻烦，得改dataset构造，等等吧

好的，感谢~~~，期待您的进一步开源，谢谢！！！

**Comment by LiuChen19960902** [comment]
期待+1

**Comment by peace-zy** [comment]
> 有点麻烦，得改dataset构造，等等吧
把示例中的user和assistant的value都填充同样的文本，是否可以实现无监督pretrain？

**Comment by peace-zy** [comment]
> > > 有点麻烦，得改dataset构造，等等吧
> > > 把示例中的user和assistant的value都填充同样的文本，是否可以实现无监督pretrain？
> 
> 我上次试了chatglm7b，这样搞直接梯度飞了，模型变成了傻子，生成内容只会重复，完全没有微调前生成的内容准确和丰富了（我怀疑是因为我用了float16，必须用bfloat16才可以，也可能是batch太少而学习率太高，模型学到了少量数据的同时覆盖了大量的先验知识）。

你试过bfloat16是可以正常训练的吗？
