### ISSUE TITLE
💡 [Question] 可以提供Math23K数据集对应的评测脚本和数据吗？

### ISSUE THREAD

**Issue by gongjunjin** [QwenLM/Qwen#481]
### 摘要 | Summary

可以提供Math23K数据集对应的评测脚本和数据吗？

### 基本示例 | Basic Example

可以提供Math23K数据集对应的评测脚本和数据吗？

### 缺陷 | Drawbacks

可以提供Math23K数据集对应的评测脚本和数据吗？

**Comment by GanjinZero** [comment]
Math23K是开源的

**Comment by gongjunjin** [comment]
对应的评测脚本方便提供下？暂未复现论文的效果

**Comment by gongjunjin** [comment]
> Math23K是开源的

对应的评测脚本方便提供下？暂未复现论文的效果
