### ISSUE TITLE
qwen-7B/14B的tokenizer的vocab_size不一致且均与

### ISSUE THREAD

**Issue by chentianyangWHU** [QwenLM/Qwen#482]
关于qwen系列的tokenizer，根据tokenization_qwen.py可知它有151643个有意义的token，另外还有3个special token 和205个备用token，总计是151851个token；而且用from_pretrained读取tokenizer并打印vocab_size得到的结果也是151851。

但是，7B和14B的embedding层中显示的vocab_size却分别是151936（7B）和152064（14B）：
<img width="647" alt="截屏2023-10-17 15 20 02" src="https://github.com/QwenLM/Qwen/assets/39194717/0cea97d1-4e48-4358-9d71-eb206e77a01d">

他们各自的config.json文件中显示的vocab_size也分别是151936和152064，均大于151851，这是什么原因？

换句话说，我是否可以将两个模型中第一层vocab到hidden_dim的embedding和最后一层hidden_dim到vocab的反embedding两个tensor的第151851行之后全部删去？

谢谢！

**Comment by jklj077** [comment]
> 他们各自的config.json文件中显示的vocab_size也分别是151936和152064，均大于151851，这是什么原因？

参见<https://github.com/QwenLM/Qwen/issues/419>。

> 换句话说，我是否可以将两个模型中第一层vocab到hidden_dim的embedding和最后一层hidden_dim到vocab的反embedding两个tensor的第151851行之后全部删去？

我们不建议这么做，但您可以基于profile结论来做决定。

**Comment by chentianyangWHU** [comment]
> > 他们各自的config.json文件中显示的vocab_size也分别是151936和152064，均大于151851，这是什么原因？
> 
> 参见#419。
> 
> > 换句话说，我是否可以将两个模型中第一层vocab到hidden_dim的embedding和最后一层hidden_dim到vocab的反embedding两个tensor的第151851行之后全部删去？
> 
> 我们不建议这么做，您可以基于实际效率分析结论来做决定。

根据#419我已经知道了两者分别为151936和152064的原因，但是还是不清楚为什么你们不建议直接将151851行之后的内容剪裁的做法，是因为这样做会导致错误吗？还是会导致模型性能下降？我不清楚的点如下：
模型中一共有两层涉及vocab_size，分别是transformer.wte.weight和lm_head.weight，两者的尺寸是vocab_size*hidden_dim。前者是word embedding层，在实际运算过程中就是一个查表操作，而token_id本身就不会超过151851，因此直接剪裁后面的行不会错；后者是一个nn.linear层，在实际运算过程中就是将lm_head.weight与每一个token的embedding（尺寸：hidden_dim*1）做矩阵乘之后再做softmax，从而得到一个长度为vocab_size的概率分布，在上述两个运算步骤中剪裁151851之后的行也不存在错误。根据以上分析，好像直接裁剪不会对模型的输出有任何影响？
这个问题非常困扰我，感谢您的解答！

**Comment by NuoJohnChen** [comment]
补充一下，Qwen0.5到72B的tokenizer的vocab_size都是151643，对于config的vocab_size超出的部分作了以下分析：
```
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
model_name = "Qwen-2-7B"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
input_text = "Hello, how are you?"
inputs = tokenizer(input_text, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs) 
logits = outputs.logits
vocab_size_expected = 151643
vocab_size_actual = logits.shape[-1] # 152064
extra_logits = logits[:, :, vocab_size_expected:]
valid_logits = logits[:, :, :vocab_size_expected]
```

```
plt.hist(extra_logits.flatten().cpu().numpy(), bins=50, alpha=0.5, label='Extra logits')
plt.hist(valid_logits.flatten().cpu().numpy(), bins=50, alpha=0.5, label='Valid logits')
plt.legend()
plt.show()
```
从上面代码看分布看不出什么差异，说明基本是噪声。

```
softmax = torch.nn.Softmax(dim=-1)
probs = softmax(extra_logits)
predicted_tokens = torch.argmax(probs, dim=-1)
predicted_text = tokenizer.decode(predicted_tokens[0], skip_special_tokens=True)
print("Predicted text with extra logits:", predicted_text) # !!!!!! (meaningless)


valid_probs = softmax(valid_logits)
valid_predicted_tokens = torch.argmax(valid_probs, dim=-1)
valid_predicted_text = tokenizer.decode(valid_predicted_tokens[0], skip_special_tokens=True)
print("Predicted text without extra logits:", valid_predicted_text)
# the same output from valid_logits and logits
```

所以把多出来的裁了，对速度有影响外其他应该没啥影响。
