### ISSUE TITLE
[BUG] <千问14b大模型同faiss向量数据库适配，版本对不上安装失败>

### ISSUE THREAD

**Issue by zhaozhaoxia** [QwenLM/Qwen#483]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

faiss-gpu现有版本1.7.2貌似不支持该大模型，请问有什么好的改进建议吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by zhaozhaoxia** [comment]
faiss-gpu目前适配比较好的版本是1.7.2[同4.30.2版本的transformer]，但是千问需要4.33以上的transformer，导致千问１４ｂ大模型难以使用faiss-gpu，请问这个问题要怎么解决？？

**Comment by JustinLin610** [comment]
没有测试过4.30，千问要求4.32，是因为4.32以上才支持GPTQ。如果你不用量化模型，可以尝试4.30
