### ISSUE TITLE
[BUG] 無法排除ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by swilly0906** [QwenLM/Qwen#486]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我前幾天問了一個問題
如何合併模型問題https://github.com/QwenLM/Qwen/issues/470#issue-1942387383
已經順利解決 我確實合併模型了

但是我當執行基座模型(Qwen-Chat-14B)跟Lora結果合併的新模型後(合併後的模型就是merge_output_Qwen)：
```
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
model = AutoModelForCausalLM.from_pretrained("/MyDrive/merge_output_Qwen", device_map="auto", trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained("/MyDrive/merge_output_Qwen", trust_remote_code=True)
```
出現ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

Python說是在tokenizer =.... 這一行有錯

我看過大大的建議https://github.com/QwenLM/Qwen/issues/368#issuecomment-1764200938
但我也有設定 trust_remote_code=True

那請問我還能修正什麼??難道還是transformers不支持Qwen???
我不確定要改什麼才對?
嘗試了一個晚上還找不出來答案
抱歉...

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
> 那請問我還能修正什麼??我不確定要改什麼才對?

方便的话，可以列下`merge_output_Qwen`文件夹下是有哪些文件吗？
如果没有tokenization_qwen.py和tokenizer_config.json这两个文件的话，需要把这两个文件复制进去。

> 難道還是transformers不支持Qwen???

Qwen的代码目前是transformers官方代码库外维护的，可以说本体的transformers确实不支持Qwen。

**Comment by swilly0906** [comment]
@jklj077 大大晚安

> > 那請問我還能修正什麼??我不確定要改什麼才對?
> 
> 方便的话，可以列下`merge_output_Qwen`文件夹下是有哪些文件吗？ 

可以 為了方便呈現 我把檔案放到我的windows畫面呈現
不然我實際上模型訓練是用Linux+A100
![merge_output_Qwen](https://github.com/QwenLM/Qwen/assets/20365198/41e6b8e5-8340-4f07-8a9e-bd4e62a3a8c1)


> 如果没有tokenization_qwen.py和tokenizer_config.json这两个文件的话，需要把这两个文件复制进去。

我依照您說的放了這兩個檔案 但出現其他錯誤 我看網路上說是路徑問題??但我有點不確定
![新錯誤](https://github.com/QwenLM/Qwen/assets/20365198/e3e46d06-4bbe-47b5-a17e-1e4f3151a6af)



> 
> > 難道還是transformers不支持Qwen???
> 
> Qwen的代码目前是transformers官方代码库外维护的，可以说本体的transformers确实不支持Qwen。

原來如此 懂了 感謝

**Comment by chancelyg** [comment]
我也遇到了这个问题，对比合并前后的文件夹，发现缺失三个文件分别是`qwen.tiktoken`、`tokenization_qwen.py`、`tokenizer_config.json`
```bash
$ tree
finetune_lora/merge_model
├── config.json
├── configuration_qwen.py
├── cpp_kernels.py
├── generation_config.json
├── model-00001-of-00008.safetensors
├── model-00002-of-00008.safetensors
├── model-00003-of-00008.safetensors
├── model-00004-of-00008.safetensors
├── model-00005-of-00008.safetensors
├── model-00006-of-00008.safetensors
├── model-00007-of-00008.safetensors
├── model-00008-of-00008.safetensors
├── modeling_qwen.py
├── model.safetensors.index.json
├── qwen_generation_utils.py
├── qwen.tiktoken
├── tokenization_qwen.py
└── tokenizer_config.json
```

这三个文件可以从Lora训练后的文件夹检查点中找到
```bash
$ tree
finetune_lora/checkpoint-2000/
├── adapter_config.json
├── adapter_model.bin
├── optimizer.pt
├── qwen.tiktoken
├── README.md
├── rng_state.pth
├── scheduler.pt
├── special_tokens_map.json
├── tokenization_qwen.py
├── tokenizer_config.json
├── trainer_state.json
└── training_args.bin
```

**Comment by jklj077** [comment]
收到，感谢提供相关信息！

目前看问题可能是`model.merge_and_unload().save_pretrained()`没有保存tokenizer，代码 (tokenization_qwen.py)、配置 (tokenizer_config.json)、词表 (qwen.tiktoken)都没保存。（似乎还有其它文件未存储）

我们看一下该问题。

**Comment by swilly0906** [comment]
@chancelyg 大大您好
我剛剛依照您的建議
成功了 
大概基本問題總算都排除了~


@jklj077  也謝謝大大熱心的幫忙~
