### ISSUE TITLE
用微調(Lora)後的合并模型 跟不合并Lora模型 結果相似 但 執行時間差異過大

### ISSUE THREAD

**Issue by swilly0906** [QwenLM/Qwen#487]
先說一聲抱歉
因為我想說是兩個不同問題
所以短時間連發兩個issue
------------------------------------------------
大家好：
我前幾天問了一個問題是到底Lora後的模型 需不需要合併?? https://github.com/QwenLM/Qwen/issues/470#issue-1942387383
那時候我執行了Lora後的結果(沒有合併):
```
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    "MyDrive/output_qwen", # path to the output directory
    device_map="auto",
    trust_remote_code=True
).eval()
tokenizer = AutoTokenizer.from_pretrained("MyDrive/output_qwen", trust_remote_code=True)
inputs = tokenizer('請用SQL查詢Willy公司2023年1月總銷售額', return_tensors='pt')
inputs = inputs.to(model.device)
pred = model.generate(**inputs)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```

現在我執行另外一個是Lora後的結果跟基座模型合併的後的新模型(合併後的模型就是merge_output_Qwen)：
(tokenizer我本來想用合併後的merge_output_Qwen 但因為有BUG 所以我先暫時維持Lora後的tokenizer(output_qwen) )
```
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
model = AutoModelForCausalLM.from_pretrained("MyDrive/merge_output_Qwen", device_map="auto", trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained("MyDrive/output_qwen", trust_remote_code=True)
inputs = tokenizer('請用SQL查詢Willy公司2023年1月總銷售額', return_tensors='pt')
inputs = inputs.to(model.device)
pred = model.generate(**inputs)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```
我有兩個疑問:
1.我的task prompt在兩種模型下的結果，幾乎都差不多(我覺得是一樣好)，沒有哪個模型結果明顯勝出，請問這是有可能的嗎?其他人遇到類似情況嗎?

2.合併後的模型，通常會變慢很多嗎?因為我用Lora微調後的結果(output_qwen)只要1分鐘結果就會出現，但用Lora微調且合併後的新模型(merge_output_Qwen)竟然要50分鐘才能出現相似的結果，請問這是合理情況??

**Comment by yzlnew** [comment]
不是开发者，个人回答下：

1. LoRA 原理上训练的是模型的更新量 $\Delta W$，所以是可以合并的。
2. 合并后的模型，可以完全用原来千问的前向推理，推理延迟应该是一致的。

**Comment by JustinLin610** [comment]
结果没有明显差异对吧。我们检查一下merge之后的性能吧，但另外建议用chat来测试，generate可能会生成到最大长度才停下来

**Comment by swilly0906** [comment]
@yzlnew  大大 感謝您的回答

> 结果没有明显差异对吧。我们检查一下merge之后的性能吧，但另外建议用chat来测试，generate可能会生成到最大长度才停下来

我合併前的原始檔案就是14B-Chat

我昨天比對幾種不同專案
發現我常用的SQL task prompt 
如果用合併後 大概10-15min執行完成

如果是文章生成task prompt
大概就會變50min執行完成
質量上兩者都是不錯
我目前猜想
可能是不同task 有不同的執行時間?
(一個是產生SQL code 另一個是產生500個字以上中文)
但沒關係 至少該issue我目前算是解決了(就是時間有變快)
