### ISSUE TITLE
如何在训练阶段支持4k的长度？

### ISSUE THREAD

**Issue by hjc3613** [QwenLM/Qwen#490]
我看模型源码时发现，当training阶段时，ntk_alpha设置为1，我的理解是训练阶段不支持长度外推：
![image](https://github.com/QwenLM/Qwen/assets/37894838/639fbf51-540e-42fd-8bff-c4f9947479b4)
那么如何才能在训练阶段支持长度为4k的输入呢？强行设置ntk_alpha可行吗？

**Comment by JustinLin610** [comment]
直接爆训也是可以的。近期给个插值的解法，效果会好点。

**Comment by hjc3613** [comment]
> 直接爆训也是可以的。近期给个插值的解法，效果会好点。

是把if self.training这个判断去掉，这样就可以不？

**Comment by logicwong** [comment]
@hjc3613 不行，dynamic ntk会根据上下文长度调整rope的参数。把if self.training去掉后，训练时rope的参数会一直变化，不利于训练。你可以手动把rope base调大或者使用PI（position interpolation）进行微调

**Comment by Scarlett-H** [comment]
> @hjc3613 不行，dynamic ntk会根据上下文长度调整rope的参数。把if self.training去掉后，训练时rope的参数会一直变化，不利于训练。你可以手动把rope base调大或者使用PI（position interpolation）进行微调

rope base是指rotary_emb_base参数吗

**Comment by hjc3613** [comment]
> @hjc3613 不行，dynamic ntk会根据上下文长度调整rope的参数。把if self.training去掉后，训练时rope的参数会一直变化，不利于训练。你可以手动把rope base调大或者使用PI（position interpolation）进行微调

我注释后训练的结果是符合预期的，但是还没左对比试验，不知道保留if self.trainging的情况下指标是好是坏。我的输入token长度为2k-3k，我看源码中的逻辑是，如果保留if self.trainging，那么在训练期间是无法动态调整rope base的，它永远等于1，只有在推理阶段才会动态调整

**Comment by logicwong** [comment]
> > @hjc3613 不行，dynamic ntk会根据上下文长度调整rope的参数。把if self.training去掉后，训练时rope的参数会一直变化，不利于训练。你可以手动把rope base调大或者使用PI（position interpolation）进行微调
> 
> rope base是指rotary_emb_base参数吗

对

**Comment by logicwong** [comment]
> > @hjc3613 不行，dynamic ntk会根据上下文长度调整rope的参数。把if self.training去掉后，训练时rope的参数会一直变化，不利于训练。你可以手动把rope base调大或者使用PI（position interpolation）进行微调
> 
> 我注释后训练的结果是符合预期的，但是还没左对比试验，不知道保留if self.trainging的情况下指标是好是坏。我的输入token长度为2k-3k，我看源码中的逻辑是，如果保留if self.trainging，那么在训练期间是无法动态调整rope base的，它永远等于1，只有在推理阶段才会动态调整

我怀疑是你的token长度相对集中，所以算出来的base相差不大。既然如此，为啥不稍微改下代码，把rotary_emb_base固定下来训练呢（比如设成4）

**Comment by logicwong** [comment]
@hjc3613 ok。方便给个注释后的训练结果和固定为4结果的对比吗？我也有些兴趣。

**Comment by hjc3613** [comment]
> @hjc3613 ok。方便给个注释后的训练结果和固定为4结果的对比吗？我也有些兴趣。

所有数据是公司域内的，导不出来，就是对话类的数据，每轮对话结束后做个总结，随着对话轮数增加，输入的长度也会增长，从10-50个汉字，增加到4000个左右的汉字。固定为4的话，我主观评测效果没有明显的优势，跟注释掉是差不多的

**Comment by logicwong** [comment]
@hjc3613 感谢反馈，如果能有客观评价指标就更好了。假如你那边的结论成立的话，或许训练时base也是可以动态改变的，然后推理跟训练也保持一致？

**Comment by hjc3613** [comment]
> @hjc3613 感谢反馈，如果能有客观评价指标就更好了。假如你那边的结论成立的话，或许训练时base也是可以动态改变的，然后推理跟训练也保持一致？

训练阶段与推理阶段都保持动态应该是可以的，ntk不管是动态还是静态，它主要影响的是过长的部分，对于较短的文本，影响其实不大，而且都保持动态的话，好处是让测试集和训练集保持一致，或许能让模型学习到动态的编码过程

**Comment by SingL3** [comment]
所以如果扩展长度需要修改什么？是吧training去掉还是只需要改config？

**Comment by xyfZzz** [comment]
> > 直接爆训也是可以的。近期给个插值的解法，效果会好点。
> 
> 是把if self.training这个判断去掉，这样就可以不？

@hjc3613 @logicwong 代码里还有一处self.training我不确定需不需要注释，能帮忙看下这里的self.training需要注释掉吗？：

        if self.use_logn_attn and not self.training:
            if self.use_cache_quantization:
                seq_start = key[0].size(2) - query.size(1)
                seq_end = key[0].size(2)
            else:
                seq_start = key.size(1) - query.size(1)
                seq_end = key.size(1)
            logn_tensor = self.logn_tensor[:, seq_start:seq_end, :, :].type_as(query)
            query = query * logn_tensor.expand_as(query)

**Comment by xyfZzz** [comment]
> > > 直接爆训也是可以的。近期给个插值的解法，效果会好点。
> > 
> > 
> > 是把if self.training这个判断去掉，这样就可以不？
> 
> @hjc3613 @logicwong 代码里还有一处self.training我不确定需不需要注释，能帮忙看下这里的self.training需要注释掉吗？：
> 
> ```
>     if self.use_logn_attn and not self.training:
>         if self.use_cache_quantization:
>             seq_start = key[0].size(2) - query.size(1)
>             seq_end = key[0].size(2)
>         else:
>             seq_start = key.size(1) - query.size(1)
>             seq_end = key.size(1)
>         logn_tensor = self.logn_tensor[:, seq_start:seq_end, :, :].type_as(query)
>         query = query * logn_tensor.expand_as(query)
> ```

看了下，个人感觉应该也要注释掉这里的self.training

**Comment by ericzhou571** [comment]
> > @hjc3613 感谢反馈，如果能有客观评价指标就更好了。假如你那边的结论成立的话，或许训练时base也是可以动态改变的，然后推理跟训练也保持一致？
> 
> 训练阶段与推理阶段都保持动态应该是可以的，ntk不管是动态还是静态，它主要影响的是过长的部分，对于较短的文本，影响其实不大，而且都保持动态的话，好处是让测试集和训练集保持一致，或许能让模型学习到动态的编码过程

但是vllm推理的qwen的时候并不支持ntk和logn，训练时候动态ntk训练的话，到了vllm是不是会崩掉🤦

**Comment by lucasjinreal** [comment]
参数插值版本啥时候加入？

**Comment by jklj077** [comment]
Qwen1.5已在训练阶段支持8k长度输入，相比于DynamicNTK和PI，Qwen1.5的输入序列长度扩展采用了更简洁的方案，如有长序列输入需求的请移步Qwen1.5。
