### ISSUE TITLE
[BUG] 微调后的 Qwen-7B 模型在生成时会追加生成乱码

### ISSUE THREAD

**Issue by ArslanTu** [QwenLM/Qwen#492]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

微调后的 Qwen-7B 模型使用时效果如下：
![Snipaste_2023-10-19_10-06-56](https://github.com/QwenLM/Qwen/assets/61570284/4bb5cdcf-fed9-4c19-927f-9a9cef4a3c9c)

在正常回答后会一直生成乱码，直到最大长度用完。

我尝试过在 `chat_stream` 方法中设置 `skip_special_tokens=False`，这导致生成时报错 `thread '<unnamed>' panicked at 'no entry found for key', src/lib.rs:201:37`。

### 期望行为 | Expected Behavior

生成回答时不再有额外乱码。

### 复现方法 | Steps To Reproduce

使用 `finetune.py` 脚本对 Qwen-7B 模型进行微调，参数如下：
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output/sharegpt \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 64 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 2 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 1024 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --fsdp "shard_grad_op auto_wrap offload" \
    --fsdp_config "./config/fsdp/qwen_fsdp_config.json"
```

然后使用 gradio 建立实例：
```python
tokenizer_qwen = AutoTokenizer.from_pretrained(
    "Qwen/Qwen-7B", 
    trust_remote_code=True, 
    pad_token='<|endoftext|>', 
    padding_side="right"
)
tokenizer_qwen.eos_token = tokenizer_qwen.pad_token

model_path = "~/code/Qwen/output/sharegpt_5k"
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
config.bf16 = True

model_qwen = AutoModelForCausalLM.from_pretrained(
    model_path, 
    trust_remote_code=True, 
    device_map='auto',
    config=config,
)
model_qwen.generation_config = GenerationConfig.from_pretrained(
    "Qwen/Qwen-7B-Chat", 
    trust_remote_code=True
)
model_qwen.generation_config.repetition_penalty = 1.0
model_qwen.generation_config.top_p = 0.9
model_qwen.generation_config.temperature = 0.8
model_qwen.generation_config.stop_words_ids = [[151643]]

model_qwen.generation_config.pad_token_id = model_qwen.config.pad_token_id = tokenizer_qwen.pad_token_id
model_qwen.generation_config.eos_token_id = model_qwen.config.eos_token_id = tokenizer_qwen.eos_token_id
model_qwen.config.use_cache = True
model_qwen.eval()


def chat_stream(prompt, history=[]):
    global model_qwen, tokenizer_qwen
    for response in model_qwen.chat_stream(tokenizer_qwen, prompt, history):
        yield response

.......
......
```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.10
- Transformers:4.31.0
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by JustinLin610** [comment]
更像是special token没生效。为什么要如此修改generation_config，请不要随意修改stop word_ids，你这么修改，就不会在<|im_end|>停下。我认为你这个不动就可以正常生成，你可以看到你的第一句是正常的。<|im_end|>不停下来，当然会乱码。

另外训练是否修改过finetune.py，以及为什么不用现成的脚本跑而要改成fsdp？


建议按照脚本训练，得到模型后按照demo服务起gradio。超参调整不要动stop word，温度也不建议调，用topp来调确定性即可。

**Comment by wangitu** [comment]
> 更像是special token没生效。为什么要如此修改generation_config，请不要随意修改stop word_ids，你这么修改，就不会在<|im_end|>停下。我认为你这个不动就可以正常生成，你可以看到你的第一句是正常的。<|im_end|>不停下来，当然会乱码。
> 
> 另外训练是否修改过finetune.py，以及为什么不用现成的脚本跑而要改成fsdp？
> 
> 建议按照脚本训练，得到模型后按照demo服务起gradio。超参调整不要动stop word，温度也不建议调，用topp来调确定性即可。

同样是 zero2，deepspeed 要比 fsdp 略稳定，但是速度就慢多了。向来都是用 fsdp 训的。

**Comment by ArslanTu** [comment]
> 更像是special token没生效。为什么要如此修改generation_config，请不要随意修改stop word_ids，你这么修改，就不会在<|im_end|>停下。我认为你这个不动就可以正常生成，你可以看到你的第一句是正常的。<|im_end|>不停下来，当然会乱码。
> 
> 另外训练是否修改过finetune.py，以及为什么不用现成的脚本跑而要改成fsdp？
> 
> 建议按照脚本训练，得到模型后按照demo服务起gradio。超参调整不要动stop word，温度也不建议调，用topp来调确定性即可。

`finetune.py` 没有改动，只是在训练时使用 fsdp 而非 deepspeed。

我用 `finetune.py` 来微调 `Qwen-7B` 模型，并在生成时加载 `Qwen-7B-Chat` 的 `generation_config`，不做额外更改。在设置 `chat_stream` 方法的 `decode` 参数 `skip_special_tokens=False` 后，发现模型在生成时好像并没有生成 `<|endoftext|>` 或 `<|im_end|>`。有时候会出现一些 `<|extra_xxx|>`。

**Comment by jklj077** [comment]
生成`<|extra_xxx|>`是非常异常的情况（训练中应当从未见过这些token）。如果temperature=1.0，top_p=0.8，依然会输出这类token，很可能是finetune出了问题。
建议看下用 @JustinLin610 推荐的方式finetune是否正常。

**Comment by ArslanTu** [comment]
重建环境（最新版本）后已解决。

**Comment by piaoxiaobo** [comment]
Qwen-72B输入11k以后报这个错，11k以前不报，是什么问题？
![image](https://github.com/QwenLM/Qwen/assets/34496544/ad8d55a9-7278-42f7-adcd-83f5e1aac52a)
