### ISSUE TITLE
[BUG] 有支持 long input 的 WIP 么？

### ISSUE THREAD

**Issue by tpoisonooo** [QwenLM/Qwen#494]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

看了其他 issue，貌似目前实际上是 5k
* https://github.com/QwenLM/Qwen/issues/439
* https://github.com/QwenLM/Qwen/issues/398

想问你们**当前内部开发事项**，在做 LongLoRA 之类的事情么？

### 期望行为 | Expected Behavior

预期跑 2k / 32k 都不影响精度。

### 复现方法 | Steps To Reproduce

无

### 运行环境 | Environment

```Markdown
无
```

### 备注 | Anything else?

无

**Comment by JustinLin610** [comment]
有

**Comment by tpoisonooo** [comment]
> 有

方便介绍一下大值会是个啥方案么？ ReRoPE ?   LongLlama ?

**Comment by tpoisonooo** [comment]
@JustinLin610  用 <苏神的 case,  passkey_retrieval> 实测。
7B-chat 版本极限 12900
14B-chat 版本极限 13735

再多精度直接掉成 0， 应该是超过相对距离泛化极限了。
