### ISSUE TITLE
[BUG] 想了解下 Model Card 中提及的性能测算脚本是如何用 AutoGPTQ 加载 Int4 量化模型的？

### ISSUE THREAD

**Issue by GabrielDrapor** [QwenLM/Qwen#495]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Hugging Face 的 [Model Card](https://huggingface.co/Qwen/Qwen-14B-Chat-Int4#%E6%98%BE%E5%AD%98%E4%BD%BF%E7%94%A8-gpu-memory-usage) 中提到了一个性能测算使用的[脚本](https://qianwen-res.oss-cn-beijing.aliyuncs.com/profile.py)，脚本中加载 Int4 量化模型的方式是：
```
...
elif quant_type == "int4":
    # please install AutoGPTQ following the readme to use quantization
    from auto_gptq import AutoGPTQForCausalLM
    model = AutoGPTQForCausalLM.from_quantized(
        "Qwen/Qwen-7B-Chat-Int4", 
        device="cuda:0", 
        trust_remote_code=True, 
        use_safetensors=True, 
        use_flash_attn=use_flash_attn
    ).eval()
...
```

我尝试用这个方式加载模型，将 `from_quantized` 方法的第一个参数替换为本地的模型路径，会收到 `FileNotFoundError: Could not find model in /home/admin/.cache/modelscope/hub/qwen/Qwen-7B-Chat-Int4` 的报错。

我阅读了 [AutoGPTQ 的代码](https://github.com/PanQiWei/AutoGPTQ/blob/51c043c6bef1380e121474ad73ea2a22f2fb5737/auto_gptq/modeling/_base.py#L818C13-L818C13)，发现虽然 `use_safetensors=True` 这个参数和模型目录下的 `.safetensors` 文件是对应的，但 AutoGPTQ 的逻辑并没有支持切分多个模型文件（`model-0000X-of-00005.safetensors`）的情况。又看到 `7B-Int4` 模型目录的 `quantize_config.json` 中特别配置了 `"model_file_base_name": "model"`（btw `14B-Int4` 没有做此配置），看起来似乎是为了能够直接用 `from_quantized()` 加载模型而做的配置？

### 期望行为 | Expected Behavior

可以用 `AutoGPTQForCausalLM.from_quantized` 直接加载下载到的量化模型？

### 复现方法 | Steps To Reproduce

```
from auto_gptq import AutoGPTQForCausalLM


model_path = 'xxx'
model = AutoGPTQForCausalLM.from_quantized(
    model_path,
    device_map="auto",
    trust_remote_code=True,
    use_safetensors=True,
    use_flash_attn=True,
).eval()
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04 LTS
- Python: 3.10
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

### 备注 | Anything else?

1、Model Card 中提及的性能测算脚本是不是已经不可用了？

2、我看到本 Repo 下其他 Issues 中的开发者们似乎都是自己用 AutoGPTQ 将未量化的模型做量化的，也看到了 [已发布的 GPTQ 量化版本的 Qwen 模型](https://huggingface.co/openerotica)，这是目前获得正确的 GPTQ 量化模型的两种方式吗？

**Comment by JustinLin610** [comment]
我做个教程吧

**Comment by roenszm** [comment]
楼主你好，问下你这个问题解决了吗，你备注2里提到的GPTQ量化版模型是跟7B-chat原模型一样的用法吗

**Comment by GabrielDrapor** [comment]
@roenszm 我用的是 14B 的模型，我直接用 AutoGPTQ 自己量化了，加载之后的使用方式应该都是一样的

**Comment by roenszm** [comment]
> @roenszm 我用的是 14B 的模型，我直接用 AutoGPTQ 自己量化了，加载之后的使用方式应该都是一样的

方便问下怎么做的嘛，我也是报这个找不到的错误，AutoGPTQForCausalLM.from_quantized(这个方法里是需要什么其他参数吗，我是小白=。=

**Comment by GabrielDrapor** [comment]
@roenszm 可以参考 [AutoGPTQ 提供的量化教程](https://github.com/PanQiWei/AutoGPTQ/blob/main/README_zh.md)，然后就可以正常用 `AutoGPTQForCausalLM.from_quantized` 加载了

**Comment by Aix-chengjie** [comment]
> 我做个教程吧

我也遇到同样的问题：加载本地模型提示找不到

```
    model = AutoGPTQForCausalLM.from_quantized(
        model_name_or_path="C:\\modules\\Qwen\\Qwen-14B-Chat-Int4",
        device_map=device_map,
        trust_remote_code=True,
        use_safetensors=True,
        use_flash_attn=True
    ).eval()

# 报错
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_gptq\modeling\_base.py", line 791, in from_quantized
    raise FileNotFoundError(f"Could not find model in {model_name_or_path}")
FileNotFoundError: Could not find model in C:\modules\Qwen\Qwen-14B-Chat-Int4
```

用官方的AutoModelForCausalLM.from_pretrained没问题。

**Comment by jklj077** [comment]
1. 如果是自己量化的模型，请使用`auto-gptq`提供的`AutoGPTQForCausalLM.from_quantized`方法加载。

   注意这样加载后的模型，其类型与`AutoModelForCausalLM.from_pretrained`加载的模型类型不一致，相关方法不一定通用。假设加载后的模型变量名为`model`，则`model.model`与`AutoModelForCausalLM.from_pretrained`加载的模型类型兼容。但请务必使用`model`进行推理。

2. 如果使用官方提供的量化模型，请使用`transformers`提供的`AutoModelForCausalLM.from_pretrained`加载。

**Comment by Chtholly1** [comment]
> @roenszm 可以参考 [AutoGPTQ 提供的量化教程](https://github.com/PanQiWei/AutoGPTQ/blob/main/README_zh.md)，然后就可以正常用 `AutoGPTQForCausalLM.from_quantized` 加载了

您好，按照你的方法我现在自己用auto-gptq重新量化了qwen-14b，然后能够正常加载了，但是在预测的时候又有一个报错，请问你遇到了吗？

**Comment by Chtholly1** [comment]
> @roenszm 可以参考 [AutoGPTQ 提供的量化教程](https://github.com/PanQiWei/AutoGPTQ/blob/main/README_zh.md)，然后就可以正常用 `AutoGPTQForCausalLM.from_quantized` 加载了

您好，按照你的方法我现在自己用auto-gptq重新量化了qwen-14b，然后能够正常加载了，但是在预测的时候又有一个报错，请问你遇到了吗？
Traceback (most recent call last):
  File "/home/Qwen/test.py", line 35, in <module>
    response, history = model.chat(tokenizer, "你好", history=None, generation_config=gen_config)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1152, in chat
    outputs = self.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1274, in generate
    return super().generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1058, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 889, in forward
    outputs = block(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 609, in forward
    attn_outputs = self.attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 530, in forward
    attn_output = F.scaled_dot_product_attention(
RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but got attn_mask.dtype: c10::BFloat16 and  query.dtype: c10::Half instead.
