### ISSUE TITLE
tokenizer_config.json 文件补全信息💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by wellhowtosay** [QwenLM/Qwen#500]
### 摘要 | Summary

不需要在初始化tokenizer的时候手动指定eos pad

### 基本示例 | Basic Example

{
  "added_tokens_decoder": {},
  "additional_special_tokens": [],
  "auto_map": {
    "AutoTokenizer": [
      "tokenization_qwen.QWenTokenizer",
      null
    ]
  },
  "clean_up_tokenization_spaces": true,
  "eos_token": "<|endoftext|>",
  "model_max_length": 8192,
  "pad_token": "<|extra_0|>",
  "padding_side": "left",
  "tokenizer_class": "QWenTokenizer",
  "tokenizer_file": null
}

### 缺陷 | Drawbacks

未知

**Comment by jklj077** [comment]
您好，感谢建议。我们提供的默认配置是通用基础配置，如有特殊应用场景，如对话、微调、batch推理等，请按有关说明或样例代码进行相应配置。
未默认设定eos、pad这些，也是为了避免不知情用户误配置。因为不同场景下配置会有不同，不配置的话至少会直接报错或者有提示，起到提醒的作用。不然静默异常行为，我们也不容易调查。感谢理解！

另外，`clean_up_tokenization_spaces`对于QWenTokenizer概念上是不适用的。这个选项是针对那种tokenize过程中会自己加空格，导致tokenize前后不等价的。QWenTokenizer是不会对输入进行非等价处理的。
