### ISSUE TITLE
[BUG] <title>请问如何从断点开始训练

### ISSUE THREAD

**Issue by renllll** [QwenLM/Qwen#501]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

qwen提供的fintune代码中没提到如何从断点开始训练

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您好，代码尚不支持，与已有issue类似。请移步讨论，感谢！

closed in favor of https://github.com/QwenLM/Qwen/issues/451

**Comment by renllll** [comment]
lora的 微调可以使用断点吗
