### ISSUE TITLE
[BUG] <title>全量微调 Qwen-14B 需要多少显存

### ISSUE THREAD

**Issue by chenjin19** [QwenLM/Qwen#504]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

想了解全量Qwen-14B需要多少显存

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
参考微调章节的7B显存占用，最粗略估计可以按 *18这个标准来估计。比如7B（我们实际是7.7B），就是接近140，那么14B应该得超过250
