### ISSUE TITLE
[BUG] 关于Flash Attention 2.0使用问题

### ISSUE THREAD

**Issue by onlyfish79** [QwenLM/Qwen#508]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1. 使用模型：Qwen-14B
2. 参考**profile.py**, 设置**use_flash_attn=True**, 但是看显存使用，应该用的是**flash attention v1**。
3. 按照transformers/modeling_utils.py中，有个参数**use_flash_attention_2**， **代码如下：**

>    model = transformers.AutoModelForCausalLM.from_pretrained(
>         model_args.model_name_or_path,
>         cache_dir=training_args.cache_dir,
>         # use_flash_attn=model_args.use_flash_attn,
>         use_flash_attention_2=model_args.use_flash_attention_2,
>         trust_remote_code=True
>     )

**报错如下：**

> transformers/modeling_utils.py", line 3084, in from_pretrained
    config = cls._check_and_enable_flash_attn_2(config, torch_dtype=torch_dtype, device_map=device_map)
  File "/home/ps/miniconda3/envs/origin_vicuna/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1265, in _check_and_enable_flash_attn_2
    raise ValueError(
**ValueError: The current architecture does not support Flash Attention 2.0.** Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new

### 运行环境 | Environment

```Markdown
- OS:22.04.1
- Python: 3.10
- Transformers: 4.34.1
- flash-attn: 2.1.1
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by JustinLin610** [comment]
不需要。直接安装flash attn 2.0，即可使用

**Comment by onlyfish79** [comment]
你好，AutoModelForCausalLM.from_pretrained时候不需要设置：use_flash_attention_2=True 吗？

**Comment by JustinLin610** [comment]
不要设置，你装了flash attn 2就可以直接用了
