### ISSUE TITLE
逻辑能力有待加强

### ISSUE THREAD

**Issue by 315930399** [QwenLM/Qwen#510]
![微信图片_20231021203407](https://github.com/QwenLM/Qwen/assets/38678334/6de87c98-6cd0-4081-80cb-908a5398866c)

**Comment by JustinLin610** [comment]
基于什么做的怎么做的？

**Comment by 315930399** [comment]
基于langchain做的qa，prompt就是根据给的三个步骤完成问题的回答。
其实不让他分三步答题，直接答题的话他反而能答对。他会说卡的申请条件是境外人士，提问者不满足条件

**Comment by JustinLin610** [comment]
OK 感谢反馈。猜测还是微调有对langchain格式适配提升效果的空间

**Comment by 315930399** [comment]
> OK 感谢反馈。猜测还是微调有对langchain格式适配提升效果的空间

拿72b int4试了下，水平略有进步，但还是有bad case
![微信图片_20231206170159](https://github.com/QwenLM/Qwen/assets/38678334/a10c8938-124a-46ba-b3b1-f4aad62360d9)
