### ISSUE TITLE
单机8张A100推理，发现推理速度严重变慢？

### ISSUE THREAD

**Issue by WangxuP** [QwenLM/Qwen#511]
# 运行环境

我用了百度云的8卡环境
GPU: 8*A100
CUDA: 11.8
大模型：Qwen/Qwen-7B-Chat

# 问题
单机8张A100推理，发现推理速度严重变慢？
单机单卡推机大约7s，换成8卡之后变成了40s了？ 想知道是由于什么原因造成的？

**Comment by zhengyangyong** [comment]
你这个现象确实很奇怪，你可以在模型启动后，使用`nvidia-smi`看看是不是将8张卡都占用了，等待/输出推理结果的过程中也可以观察一下显卡使用状态

**Comment by tutu329** [comment]
我是2张2080ti，qwen14b-int4，一张卡推理正常速度，两张卡一起推理速度就只有十分之一左右。应该是个bug。

**Comment by WangxuP** [comment]
> 你这个现象确实很奇怪，你可以在模型启动后，使用`nvidia-smi`看看是不是将8张卡都占用了，等待/输出推理结果的过程中也可以观察一下显卡使用状态

是的，观察发现模型应该是均匀分类到每一个卡上了。

**Comment by LinGuan0624** [comment]
> > 你这个现象确实很奇怪，你可以在模型启动后，使用`nvidia-smi`看看是不是将8张卡都占用了，等待/输出推理结果的过程中也可以观察一下显卡使用状态
> 
> 是的，观察发现模型应该是均匀分类到每一个卡上了。

有什么解决办法吗？ @WangxuP

**Comment by jklj077** [comment]
这个是因为目前transformers的多卡（`device_map="auto"`）只是naive的model parallelism，会有设备闲置的问题。如果不是因为单卡放不下模型的话，是不建议这么搞的。transformers官方有说明：

> Multiple GPUs can be utilized, however this is considered “model parallism” and as a result only one GPU will be active at a given moment, waiting for the prior one to send it the output.
> https://huggingface.co/docs/accelerate/usage_guides/big_modeling

如果单卡能放下模型，那么建议采用data parallelism，或者每卡部署一个服务，外面配置负载均衡。如果单卡放不下，那这个可能也是需要承受的代价。

对于部署，README中目前推荐的是使用vllm，vllm多卡部署还支持1d tensor parallalism，以应对单卡放不下的情况，这个可以避免模型切到多卡中的设备空置的问题，但需要修改模型代码以提供支持（vllm有[专门适配Qwen](https://github.com/vllm-project/vllm/blob/1a2bbc930135cd3b94fbff2aafbdf5c568acc8bd/vllm/model_executor/models/qwen.py)）。
