### ISSUE TITLE
在使用vllm进行Qwen-14b-chat推理时报错

### ISSUE THREAD

**Issue by xjDUAN184** [QwenLM/Qwen#513]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

from vllm import LLM

llm = LLM(model='/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1') # Name or path of your model
output = llm.generate("Hello, my name is")
print(output)

报错内容为：
File "/home/czp/vllm-main/vllm/test.py", line 3, in
llm = LLM(model='/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1') # Name or path of your model
RuntimeError: Failed to load the tokenizer. If the tokenizer is a custom tokenizer not yet available in the HuggingFace transformers library, consider setting trust_remote_code=True in LLM or using the --trust-remote-code flag in the CLI.

![image](https://github.com/QwenLM/Qwen/assets/73686733/06ae191f-cc85-4f3b-bb22-8f3186d4ad68)
检查了模型路径，发现下载的模型文件没有遗漏

### 期望行为 | Expected Behavior

能顺利加载Qwen在VLLM上进行推理

### 复现方法 | Steps To Reproduce

from vllm import LLM

llm = LLM(model='/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1') # Name or path of your model
output = llm.generate("Hello, my name is")
print(output)

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10
- Transformers:4.32.0
```

### 备注 | Anything else?

wu

**Comment by xfgong** [comment]
consider setting trust_remote_code=True in LLM or using the --trust-remote-code flag in the CLI.

**Comment by JustinLin610** [comment]
请follow我们的readme的deployment章节来进行操作
