### ISSUE TITLE
问一下大模型的显卡配置要求

### ISSUE THREAD

**Issue by rabum** [QwenLM/Qwen#514]
请问主要是对显存有要求吗？未量化的14b最低要什么显卡，两张24g的p40行不行？

**Comment by JustinLin610** [comment]
可以阅读readme的inference性能章节了解显存占用哈

**Comment by rabum** [comment]
> 可以阅读readme的inference性能章节了解显存占用哈

主要就是显存到位就行了是吧，其他差点就差点？

**Comment by jklj077** [comment]
显存是跑不跑得起来的问题哈，跑起来后还有效率、延迟、吞吐等问题。即便显存够，P40的运算性能也确实有时代感了，它首先不支持bf16，虽然支持fp16，但fp16性能比fp32要低好几个数量级，这都需要实际去测试哪种配置能达到平衡。建议综合考虑下吧，这方面（指P40）我们实操经验有限。
