### ISSUE TITLE
如何制作 三元组数据集格式实现fuction call数据集？

### ISSUE THREAD

**Issue by positive666** [QwenLM/Qwen#519]
举个例子我希望把下面的格式改成LLMA2那种instruction的三元组格式 来训练function call，请问可以吗？
{
    "conversations": [
      {
        "from": "user",
        "value": "Answer the following questions as best you can. You have access to the following APIs:\n\ngoogle_search: Call this tool to interact with the Google Search API. What is the Google Search API useful for? Google Search is a general search engine that can be used to access the internet, query encyclopedia knowledge, and stay informed about current events. Format the arguments as a JSON object. Parameters: [{\"name\": \"search_query\", \"description\": \"Search keywords or phrases\", \"required\": true, \"schema\": {\"type\": \"string\"}}]\n\ncode_interpreter: Call this tool to interact with the Code Interpreter API. What is the Code Interpreter API useful for? Code interpreter that can execute Python code.Enclose the code within triple backticks (`) at the beginning and end of the code. Parameters: [{\"name\": \"code\", \"description\": \"Code to be executed\", \"required\": true, \"schema\": {\"type\": \"string\"}}]\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [google_search, code_interpreter]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can be repeated zero or more times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: Who is jay chou? And who is his wife?"
      },
      {
        "from": "assistant",
        "value": "Thought: I need to google Jay Chou.\nAction: google_search\nAction Input: {\"search_query\": \"Jay Chou\"}\nObservation: Jay Chou is ...\nThought: I need to google Jay's wife.\nAction: google_search\nAction Input: {\"search_query\": \"Jay Chou's wife\"}\nObservation: Jay Chou's wife is ...\nThought: I now know the final answer\nFinal Answer: Jay Chou is ... His wife is ..."
      }
    ]
  },

**Comment by JianxinMa** [comment]
抱歉，对llama微调不太熟悉，请问 “LLMA2那种instruction的三元组格式” 具体是指什么格式？如果是 instruction，query，response 三个字段的话，那可以把 `Answer the following questions as best you can. ...` 直至 `Question:` 前的东西作为 instruction， `Question:` 后的`Who is jay chou? And who is his wife?`作为query，response就作为response就好。

**Comment by positive666** [comment]
> 抱歉，对llama微调不太熟悉，请问 “LLMA2那种instruction的三元组格式” 具体是指什么格式？如果是 instruction，query，response 三个字段的话，那可以把 `Answer the following questions as best you can. ...` 直至 `Question:` 前的东西作为 instruction， `Question:` 后的`Who is jay chou? And who is his wife?`作为query，response就作为response就好。

是的 是这个格式，另外想请教下，比如我在小数据集上tune 有一个问题是“屏幕亮度调高50”，另外一个问题是“屏幕亮度调到50”，但是7B CHAT微调收敛后的效果，第二种调到50的问题会被当做第一种调高50 ，针对这种情况有什么训练TRICK吗？
