### ISSUE TITLE
[BUG] int4 模型在温度 >0 且 <= 0.5 时候推理报错

### ISSUE THREAD

**Issue by xunfeng1980** [QwenLM/Qwen#521]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

int4 模型在温度低于 0.5 时候推理报错
```
  File "/data/xxx/anaconda3/envs/qwen-q/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/xxx/anaconda3/envs/qwen-q/lib/python3.10/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/data/xxx/anaconda3/envs/qwen-q/lib/python3.10/site-packages/transformers/generation/utils.py", line 2760, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

### 期望行为 | Expected Behavior

正常推理，不报错

### 复现方法 | Steps To Reproduce

1. git clone https://huggingface.co/Qwen/Qwen-14B-Chat-Int4
2. git clone https://github.com/QwenLM/Qwen
3. 安装对应依赖
4.  python  openai_api.py
5. ``` curl --location --request POST 'http://xx/v1/chat/completions' --header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' --header 'Content-Type: application/json' --data-raw '{ "model": "qwen-q", "messages": [{"role":"user","content":"你是谁"}], "max_tokens": 10000, "temperature": 0.4 }'```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04.6 LTS
- Python:Python 3.10.13
- Transformers: 4.32.0
- PyTorch: 2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by lin-xiaosheng** [comment]
遇到了一样的问题，蹲回复

**Comment by dayL-W** [comment]
一样的问题，不过我的模型是SFT之后的模型报这个错误

**Comment by zhengyangyong** [comment]
我也发现了，所以如果不希望发散，可以直接将温度设置为0，是OK的：
```
    gen_kwargs = {}
    if request.temperature is not None:
        if request.temperature < 0.01:
            gen_kwargs['top_k'] = 1  # greedy decoding
        else:
            # Not recommended. Please tune top_p instead.
            gen_kwargs['temperature'] = request.temperature
    if request.top_p is not None:
        gen_kwargs['top_p'] = request.top_p
```

**Comment by mikeleatila** [comment]
@xunfeng1980 @dayL-W @lin-xiaosheng I am using Qwen-14B-Chat-Int4 and in the inference I am also getting: "RuntimeError: probability tensor contains either inf, nan or element < 0" I have used different temperature, top_p values in addition to do_sample but with the same result. Has this been fixed and how? Many thanks

**Comment by Guo986** [comment]
> 一样的问题，不过我的模型是SFT之后的模型报这个错误

兄弟，我也是微调之后报错的。你解决这个问题了吗

**Comment by xunfeng1980** [comment]
```
model.generation_config.do_sample = False
```
可以不报错,如果直接用 vllm 来跑也不报错。
