### ISSUE TITLE
[BUG] <title>在安装好flash-attn的情况下，启用openai_api.py仍会跳出警告

### ISSUE THREAD

**Issue by Halflifefa** [QwenLM/Qwen#522]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

通过这个地址安装的https://github.com/bdashore3/flash-attention/releases/tag/2.3.2

pip show flash-attn
Name: flash-attn
Version: 2.3.2
Summary: Flash Attention: Fast and Memory-Efficient Exact Attention
Home-page: https://github.com/Dao-AILab/flash-attention
Author: Tri Dao
Author-email: trid@cs.stanford.edu
License:
Location: c:\users\administrator\.conda\envs\flash-attn\lib\site-packages
Requires: einops, ninja, packaging, torch
Required-by:

python openai_api.py
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention

### 期望行为 | Expected Behavior

应该没有这行警告吧
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary

### 运行环境 | Environment

```Markdown
- OS:Win11
- Python: 3.10.13
- Transformers: 4.32.0
- PyTorch: 2.1.0+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
请问有参照<https://github.com/QwenLM/Qwen#quickstart>这部分说明安装可选项（最后两行内容）吗？没有安装后两项的话，可能还是会有提示的。
```
git clone https://github.com/Dao-AILab/flash-attention
cd flash-attention && pip install .
# Below are optional. Installing them might be slow.
# pip install csrc/layer_norm
# pip install csrc/rotary
```

**Comment by jklj077** [comment]
1. 提示的两个模块(rotary和layer_norm)，需要自行编译安装，成功后相关提示才会消失。Linux系统的话，其它issue里有好心人整理了份[操作说明](https://github.com/QwenLM/Qwen/issues/535#issuecomment-1783977218)，但可能对Windows并不适用。
2. 您在使用非官方的flash_attention的Windows版本，而且目前看与您的CUDA版本存在不一致。如有编译相关问题建议寻求g该存储库维护者的帮助，感谢理解！
