### ISSUE TITLE
多机多卡微调

### ISSUE THREAD

**Issue by 1424153694** [QwenLM/Qwen#525]
请问微调时，单机显卡显存不够，可以在多台机器上微调吗？怎么设置？

**Comment by JustinLin610** [comment]
可以的 看微调文档 给了多卡训练的脚本

**Comment by 1424153694** [comment]
好的，谢谢

**Comment by zhengyangyong** [comment]
有没有可能多机？感觉这个难度很大：）

**Comment by 1424153694** [comment]
> 有没有可能多机？感觉这个难度很大：）
微调脚本里有但是没试过，我现在单机多卡微调也卡住了，我用了5张3090卡lora微调Qwen-14b-chat模型包显存溢出，虽然没有用flashattention，但是我感觉显存应该是够得，怀疑是模型重复加载在了几张显卡上，请问你遇到过这个问题吗？你微调大概用了多少显存。

**Comment by zhengyangyong** [comment]
我没有基于14b微调过，按官方文档提示大概需要40-50GB，你可以试试设置使用ZeRO3，修改微调脚本：
```
--deepspeed finetune/ds_config_zero3.json
```

**Comment by jklj077** [comment]
多机多卡微调现已增加有关说明，请参考README。
