### ISSUE TITLE
QLora单机二卡微调卡住

### ISSUE THREAD

**Issue by skyantao** [QwenLM/Qwen#526]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

WSL 环境，14B-int4量化模型，环境可正常运行推理

在微调时，加载到一半，系统会hang住，无任何报错

![image](https://github.com/QwenLM/Qwen/assets/6165974/09373d0b-752e-4b19-ad8d-e0e24f5ec985)

显卡显存占用 GPU0 

![image](https://github.com/QwenLM/Qwen/assets/6165974/2129a351-b9ab-4eef-9e8e-fb015a5083e7)
GPU1

![image](https://github.com/QwenLM/Qwen/assets/6165974/594785d4-d01f-4b5b-b7be-96b5752f7981)

### 期望行为 | Expected Behavior

能正常加载

### 运行环境 | Environment

```Markdown
- OS:22.04
- Python:3.9.16
- Transformers:4.31
- PyTorch:2.0 
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):cuda 117
```

**Comment by JustinLin610** [comment]
可能是之前一个PR改了device_map到"auto"带来。试下最新代码？改回去None了

**Comment by skyantao** [comment]
finetune.py 的代码已经是 NONE. 我单机微调是正常的，是不是因为我是wsl , 有一张显卡有共享导致？

![image](https://github.com/QwenLM/Qwen/assets/6165974/2cc5567c-ca5d-431e-af24-8b3b9908dc32)

**Comment by jklj077** [comment]
> 是不是因为我是wsl , 有一张显卡有共享导致？

这个确实不清楚了。多卡的话应该会走NCCL，但好像NCCL在WSL上需要特定版本后才支持\[[1](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#nvidia-compute-software-support-on-wsl-2)\]，有些包为了控制依赖（比如PyTorch）会静态链接到固定的版本上，还不用系统的版本。NCCL repo里有个相关issue可以参考看下\[[2](https://github.com/NVIDIA/nccl/issues/442)\]。

**Comment by skyantao** [comment]
感谢各位，WSL 始终不行，换了一台ubuntu 很顺利的搞定，谢谢！
