### ISSUE TITLE
💡 [REQUEST] - <能否提供线性插值的实现，支持更大长度上下文的微调>

### ISSUE THREAD

**Issue by MiyazonoKaori** [QwenLM/Qwen#528]
### 摘要 | Summary

能否提供线性插值的实现，支持更大长度上下文的微调

### 基本示例 | Basic Example

能否提供线性插值的实现，支持更大长度上下文的微调

### 缺陷 | Drawbacks

能否提供线性插值的实现，支持更大长度上下文的微调

**Comment by JustinLin610** [comment]
好
