### ISSUE TITLE
[BUG]  微调时报错 'utf-8' codec can't decode byte 0xe9 in position 4: invalid continuation byte

### ISSUE THREAD

**Issue by nne998** [QwenLM/Qwen#530]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

``` config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tony/code/qwen-14b/Qwen/finetune/finetune.py", line 367, in <module>
    train()
  File "/home/tony/code/qwen-14b/Qwen/finetune/finetune.py", line 267, in train
```

### 复现方法 | Steps To Reproduce

执行 finetune_qlora_single_gpu.sh

### 运行环境 | Environment

```Markdown
- OS:debian 11
- Python: 3.10
- Transformers:
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by jklj077** [comment]
您好，error log好像不完整，请提供完整错误以便我们更准确地定位问题。

目前看可能是训练数据编码不对，不是UTF8，请先确认下。

**Comment by MengHao666** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> ```
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4: invalid continuation byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/tony/code/qwen-14b/Qwen/finetune/finetune.py", line 367, in <module>
>     train()
>   File "/home/tony/code/qwen-14b/Qwen/finetune/finetune.py", line 267, in train
> ```
> 
> ### 期望行为 | Expected Behavior
> _No response_
> 
> ### 复现方法 | Steps To Reproduce
> 执行 finetune_qlora_single_gpu.sh
> 
> ### 运行环境 | Environment
> - OS:debian 11
> - Python: 3.10
> - Transformers:
> - PyTorch: 2.0.1
> - CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
> ### 备注 | Anything else?
> _No response_

问题解决了吗，遇到了类似的问题
