### ISSUE TITLE
💡 请问code-qwen多久开源

### ISSUE THREAD

**Issue by zeng9t** [QwenLM/Qwen#532]
### 摘要 | Summary

请问code-qwen多久可以开源呢？

### 基本示例 | Basic Example

在technical report中看到code-qwen，因为基于code-qwen再做instruct似乎也是chatgpt的技术路线

### 缺陷 | Drawbacks

无

**Comment by huybery** [comment]
您是否计划用 code qwen 做更多事情？收集更多诉求有助于我们推进开源。

**Comment by zeng9t** [comment]
> 您是否计划用 code qwen 做更多事情？收集更多诉求有助于我们推进开源。

从technique report中来看code-qwen是目前中英&code能力比较均衡的基座，希望用它继续训练来增强更多内部的下游任务

**Comment by feiyuvl** [comment]
@huybery 
您好，技术报告里code-qwen的效果非常惊艳，其中sft阶段提到了multi-stage sft，这块具体指什么，能详细的说明一下么？

**Comment by timxx** [comment]
期待开源+1

**Comment by huybery** [comment]
https://github.com/QwenLM/CodeQwen1.5
