### ISSUE TITLE
请问针对无标记的数据，如整篇文档等，有无好的微调方案

### ISSUE THREAD

**Issue by oklongmm** [QwenLM/Qwen#534]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

目前只能针对问答对数据集进行微调，针对无标注的数据，如整篇的文章等，有无微调方案。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by zhengyangyong** [comment]
没有吧，文档不大直接提示词工程，文档大先向量化匹配，然后再扔模型（但是这么搞向量匹配度是个问题）

**Comment by oklongmm** [comment]
向量化知识库功能我们已经实现，我是想问有没有好的方法用成片的数据集做无监督微调，而不是用问答对微调

**Comment by zhengyangyong** [comment]
你提到的“无监督”我觉得很有趣，你希望模型能够根据一个无标记的数据学习发掘问题并自问自答？
