### ISSUE TITLE
import flash_attn fail 环境中已经下载好flashattention了，但总是导入失败

### ISSUE THREAD

**Issue by 1424153694** [QwenLM/Qwen#535]
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention

**Comment by jklj077** [comment]
请问有参照<https://github.com/QwenLM/Qwen#quickstart>这部分说明安装可选项（最后两行内容）吗？没有安装后两项的话，可能还是会有提示的。得把两行前的`#`号删掉哈。
```
git clone https://github.com/Dao-AILab/flash-attention
cd flash-attention && pip install .
# Below are optional. Installing them might be slow.
# pip install csrc/layer_norm
# pip install csrc/rotary
```

**Comment by 1424153694** [comment]
> 请问有参照https://github.com/QwenLM/Qwen#quickstart这部分说明安装可选项（最后两行内容）吗？没有安装后两项的话，可能还是会有提示的。得把两行前的`#`号删掉哈。
> 
> ```
> git clone https://github.com/Dao-AILab/flash-attention
> cd flash-attention && pip install .
> # Below are optional. Installing them might be slow.
> # pip install csrc/layer_norm
> # pip install csrc/rotary
> ```

安装了，是不是3090不支持flashattention，不用这个的话，lora微调大概需要多少显存？

**Comment by jklj077** [comment]
> 是不是3090不支持flashattention

FlashAttention是支持3090的，可能是编译没成功。pip install有报错信息的话可以列下，也可以看看FlashAttention的说明。

> 不用这个的话，lora微调大概需要多少显存

目前还没有这个信息，您可以尝试下，24G显存lora可能有些极限。

**Comment by 1424153694** [comment]
> > 是不是3090不支持flashattention
> 
> FlashAttention是支持3090的，可能是编译没成功。pip install有报错信息的话可以列下，也可以看看FlashAttention的说明。
> 
> > 不用这个的话，lora微调大概需要多少显存
> 
> 目前还没有这个信息，您可以尝试下，24G显存lora可能有些极限。

我没用flashattention，用了5张3090微调Qwen-14b-chat，lora微调，报显存溢出，这个正常吗，按理说显存应该是够得，我跑推理不到30g就够了。我看他模型好像是加载了5次，打印参数的时候输出了四次，这是他的一部分参数信息，_n_gpu=1显示为1：
TrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.95,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
cache_dir=None,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=finetune/ds_config_zero2.json,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=8,
gradient_checkpointing=True,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output_qwen/runs/Oct26_16-17-06_autodl-container-63c311bf08-9707e7c8,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1.0,
logging_strategy=steps,
lr_scheduler_type=cosine,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
model_max_length=256,
mp_parameters=,
no_cuda=False,
num_train_epochs=5.0,
optim=adamw_torch,
optim_args=None,
output_dir=output_qwen,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
prediction_loss_only=False,
push_to_hub=False,

**Comment by 1424153694** [comment]
> > 是不是3090不支持flashattention
> 
> FlashAttention是支持3090的，可能是编译没成功。pip install有报错信息的话可以列下，也可以看看FlashAttention的说明。
> 
> > 不用这个的话，lora微调大概需要多少显存
> 
> 目前还没有这个信息，您可以尝试下，24G显存lora可能有些极限。

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=8
DIR=`pwd`

GPUS_PER_NODE=5
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="./Qwen-14b-chat" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="./data.json"

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --fp16 True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 256 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed finetune/ds_config_zero2.json
这是我设置的参数

**Comment by xuexidi** [comment]
我安装flash-attn2时碰到了同样的问题，不过我已经解决了，解决办法：

注意：执行以下所有步骤之前，要保证当前命令行终端已经处于对应的虚拟环境中！（`conda activate your_env`)

1、手动下载flash-attn2的whl并安装（注意适配你当前的CUDA、Python、torch版本），运行训练代码会提示import flash-attn失败，warning中写着缺少flash-attn的layer_norm和rotary。

2、此时去flash-attn的官方github查看历史的release，找到自己所安装的版本的源码，例如我安装的是2.3.2版本的whl，那么这会儿我就下载2.3.2版本的flash-attn对应的源码（注意，下载源码的时候不区分CUDA、Python、torch版本这些信息，直接下载就行）

3、cd 到源码路径下的csrc/rotary路径，执行 `python setup.py install`，然后等待安装完成即可

4、同理，cd 到源码路径下的csrc/layer_norm路径，执行 `python setup.py install`，然后等待安装完成即可

5、重新运行训练代码，会显示trying import flash-attn，import可能会稍微慢点，但是不会提示import失败了，随着训练起来，你会发现显存占用降低了不少，训练速度也提升了一些。

**Comment by 1424153694** [comment]
> 我安装flash-attn2时也出现了同样的问题，不过我已经解决了，解决方法：
> 
> 注意：执行以下所有步骤之前，要保证当前命令行终端已经在对应的虚拟环境中！（`conda activate your_env`)
> 
> 1、手动下载flash-attn2的whl并安装（注意车载你当前的CUDA、Python、torch版本），训练运行代码会提示import flash-attn失败，warning中写着缺少flash-attn的layer_norm和rotary。
> 
> 2、此时是去flash-attn的官方github查看历史的[release](https://github.com/Dao-AILab/flash-attention/releases)，找到自己所安装的版本的源码，比如我安装2.3.2版本的whl，那么这会儿我就下载2.3.2版本的flash -attn对应的源码（注意，下载源码的时候不区分CUDA、Python、torch版本这些信息，直接下载就行），下载完毕进行解压。
> 
> 3、cd 到源码路径下的csrc/rotary路径，执行`python setup.py install`，然后完成等待安装即可。
> 
> 4、同理，cd 到源码路径下的csrc/layer_norm路径，执行`python setup.py install`，等待然后安装完成即可。
> 
> 5、重新运行训练代码，会显示trying import flash-attn，import可能会有点慢点，但是不会提示import失败了，随着训练起来，你会发现显着的占用降低了，训练速度也提升了一些。

你好，按照您说的操作进行了一遍，安装成功了没报错，但还是出警告提示import失败
信息：
root@llm-server:/home/llm/Qwen-main# python cli_demo.py
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|███████████████████████████████████████████| 15/15 [00:10<00:00,  1.46it/s]

我是先创建一个环境，然后下载flash_attn的源码，按照官方github上的命令安装成功了。然后警告导入失败。然后我又在这个环境下，根据flash_attn的版本下载源码，然后按照您说的方法，安装两个东西成功。继续运行，还是警告导入失败，如上述报错

**Comment by jklj077** [comment]
@1424153694 这个您flash-attn的版本是多少呢？在运行python的同环境下，`pip list`的结果中有`rotary_emb`和`dropout_layer_norm`这两个包吗？从日志来看，三行命令中的第一个可能就没成功。

**Comment by 1424153694** [comment]
> @1424153694 这个您flash-attn的版本是多少呢？在运行python的同环境下，`pip list`的结果中有`rotary_emb`和`dropout_layer_norm`这两个包吗？从日志来看，三行命令中的第一个可能就没成功。

(Qwen-14b-llmb) root@llm-server:/home/llm/Qwen-main# pip list
Package                       Version
----------------------------- ----------
accelerate                    0.24.1
certifi                       2023.7.22
charset-normalizer            3.3.2
cmake                         3.27.7
dropout-layer-norm            0.1
einops                        0.7.0
filelock                      3.13.1
flash-attn                    2.3.3
fsspec                        2023.10.0
huggingface-hub               0.19.0
idna                          3.4
Jinja2                        3.1.2
lit                           17.0.4
MarkupSafe                    2.1.3
mpmath                        1.3.0
networkx                      3.1
ninja                         1.11.1.1
numpy                         1.24.4
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu11             10.9.0.58
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu11            10.2.10.91
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu11          11.7.4.91
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu11              2.14.3
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.52
nvidia-nvtx-cu11              11.7.91
nvidia-nvtx-cu12              12.1.105
package-name                  0.1
packaging                     23.2
Pillow                        10.1.0
pip                           23.3
psutil                        5.9.6
PyYAML                        6.0.1
regex                         2023.10.3
requests                      2.31.0
rotary-emb                    0.1
safetensors                   0.4.0
scipy                         1.10.1
setuptools                    68.0.0
sympy                         1.12
tiktoken                      0.5.1
tokenizers                    0.13.3
torch                         2.0.0
torchaudio                    2.0.1
torchvision                   0.15.1
tqdm                          4.66.1
transformers                  4.32.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.8.0
urllib3                       2.0.7
wheel                         0.41.2


是有这两个包的，版本是2.3.3，cuda版本11.8，torch版本2.0

**Comment by jklj077** [comment]
@1424153694 猜测这个是torch和flash_attn用的cuda的版本不匹配（您这个环境里两个cuda runtime，一个11.8一个12.1，orch 2.0用的应该是11.8）。您系统cuda版本是多少，执行`nvcc --version`看下输出哈。

**Comment by heyblackC** [comment]
我遇到了import flash_attn rotary fail的问题，是通过装包解决的，分享给大家参考。

**Comment by jklj077** [comment]
@heyblackC 

hi，你的问题与`flash-attn`的版本有关，如flash-attn版本高于`2.1.1`（不含`2.1.1`，从`2.1.2`开始），`rotary`相关操作通过`triton`实现，不再依赖于`csrc/rotary`。`csrc/rotary`中的`rotary-emb`包不再需要编译安装。

**Comment by 1424153694** [comment]
> nvcc --version

我的cuda版本是11.8

**Comment by jklj077** [comment]
@1424153694 根据您的问题描述，package安装成功、版本匹配，导入不成功不符合预期。

请您直接在python终端中，分别输入
```python
>>> import flash-attn
>>> from flash_attn.flash_attn_interface import flash_attn_varlen_func as __flash_attn_unpadded_func
>>> from flash_attn.layers.rotary import apply_rotary_emb_func as __apply_rotary_emb_func
>>> from flash_attn.ops.rms_norm import rms_norm as __rms_norm
```
看看都是什么报错吧。

**Comment by jklj077** [comment]
我们已提供了基于Docker的环境配置方案，提供的镜像中预置编译过的flash-attn，请尝试看看能否解决您的问题。如问题仍存在，请

**Comment by yhaiqiang** [comment]
> 我安装flash-attn2时碰到了同样的问题，不过我已经解决了，解决办法：
> 
> 注意：执行以下所有步骤之前，要保证当前命令行终端已经处于对应的虚拟环境中！（`conda activate your_env`)
> 
> 1、手动下载flash-attn2的whl并安装（注意适配你当前的CUDA、Python、torch版本），运行训练代码会提示import flash-attn失败，warning中写着缺少flash-attn的layer_norm和rotary。
> 
> 2、此时去flash-attn的官方github查看历史的[release](https://github.com/Dao-AILab/flash-attention/releases)，找到自己所安装的版本的源码，例如我安装的是2.3.2版本的whl，那么这会儿我就下载2.3.2版本的flash-attn对应的源码（注意，下载源码的时候不区分CUDA、Python、torch版本这些信息，直接下载就行），下载完毕进行解压。
> 
> 3、cd 到源码路径下的csrc/rotary路径，执行 `python setup.py install`，然后等待安装完成即可。
> 
> 4、同理，cd 到源码路径下的csrc/layer_norm路径，执行 `python setup.py install`，然后等待安装完成即可。
> 
> 5、重新运行训练代码，会显示trying import flash-attn，import可能会稍微慢点，但是不会提示import失败了，随着训练起来，你会发现显存占用降低了不少，训练速度也提升了一些。

按照这个步骤成功了，thanks

**Comment by lovelyjuice** [comment]
> 我安装flash-attn2时碰到了同样的问题，不过我已经解决了，解决办法：
> 
> 注意：执行以下所有步骤之前，要保证当前命令行终端已经处于对应的虚拟环境中！（`conda activate your_env`)
> 
> 1、手动下载flash-attn2的whl并安装（注意适配你当前的CUDA、Python、torch版本），运行训练代码会提示import flash-attn失败，warning中写着缺少flash-attn的layer_norm和rotary。
> 
> 2、此时去flash-attn的官方github查看历史的[release](https://github.com/Dao-AILab/flash-attention/releases)，找到自己所安装的版本的源码，例如我安装的是2.3.2版本的whl，那么这会儿我就下载2.3.2版本的flash-attn对应的源码（注意，下载源码的时候不区分CUDA、Python、torch版本这些信息，直接下载就行），下载完毕进行解压。
> 
> 3、cd 到源码路径下的csrc/rotary路径，执行 `python setup.py install`，然后等待安装完成即可。
> 
> 4、同理，cd 到源码路径下的csrc/layer_norm路径，执行 `python setup.py install`，然后等待安装完成即可。
> 
> 5、重新运行训练代码，会显示trying import flash-attn，import可能会稍微慢点，但是不会提示import失败了，随着训练起来，你会发现显存占用降低了不少，训练速度也提升了一些。

源码编译flash-attn一直失败，多亏了你这个办法才装上layer_norm

**Comment by rockyoung** [comment]
> @heyblackC
> 
> hi，你的问题与`flash-attn`的版本有关，如flash-attn版本高于`2.1.1`（不含`2.1.1`，从`2.1.2`开始），`rotary`相关操作通过`triton`实现，不再依赖于`csrc/rotary`。`csrc/rotary`中的`rotary-emb`包不再需要编译安装。

实测下来并不是哦，`flash-attn 2.4.2`，在分别安装完`csrc/layer_norm`和`csrc/rotary`后依然需要再安装`triton`才不会报warning

**Comment by jklj077** [comment]
为确保信息准确无误，请允许我根据上下文解释一下该回复：

在新版的Flash-Attention库中，无需安装csrc/rotary目录下的本地代码，即使安装了也不会被使用。
实际上，新版实现对Rotary Position Embedding的支持是基于Triton库的。
这意味着若要在新版的Flash-Attention中启用Rotary位置编码功能，必须正确安装并配置Triton库，而非旧版中的独立 Rotary 代码模块。

无论如何，鉴于Flash-Attention已经从2.3更新至2.4，我们建议您针对最新版本的任何新问题或需求，在项目仓库中创建一个全新的issue，谢谢您的理解和配合。

**Comment by acmllearner** [comment]
我也遇到了一样的问题，版本号（CUDA 11.7 , torch2.0.1, python3.9），问题已解决，方法如下：
1、首先到https://github.com/Dao-AILab/flash-attention/releases 上找 torch和cuda对应版本的whl包。我下载的是：
flash_attn-2.3.5+cu117torch2.0cxx11abiFALSE-cp39-cp39-linux_x86_64.whl
2、如果报Warning: import flash_attn XXXX的错误 就从https://github.com/Dao-AILab/flash-attention/releases下载Source_code，在linux下转到需要的XXXX文件夹中  以 pip setup.py install的方式安装。

**Comment by serI0usLIn** [comment]
> 我也遇到了一样的问题，版本号（CUDA 11.7 , torch2.0.1, python3.9），问题已解决，方法如下： 1、首先到https://github.com/Dao-AILab/flash-attention/releases 上找 torch和cuda对应版本的whl包。我下载的是： flash_attn-2.3.5+cu117torch2.0cxx11abiFALSE-cp39-cp39-linux_x86_64.whl 2、如果报Warning: import flash_attn XXXX的错误 就从[https://github.com/Dao-AILab/flash-attention/releases下载Source_code，在linux下转到需要的XXXX文件夹中](https://github.com/Dao-AILab/flash-attention/releases%E4%B8%8B%E8%BD%BDSource_code%EF%BC%8C%E5%9C%A8linux%E4%B8%8B%E8%BD%AC%E5%88%B0%E9%9C%80%E8%A6%81%E7%9A%84XXXX%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%AD) 以 pip setup.py install的方式安装。

你好，我想请问下1、首先到https://github.com/Dao-AILab/flash-attention/releases 上找 torch和cuda对应版本的whl包。我下载的是：
flash_attn-2.3.5+cu117torch2.0cxx11abiFALSE-cp39-cp39-linux_x86_64.whl这个包对应的版本是必须按安装文件的还是说安装文件是最低要求
