### ISSUE TITLE
[BUG] Qlora微调报错

### ISSUE THREAD

**Issue by lyj555** [QwenLM/Qwen#537]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

单机微调时报错

Abort(1090959) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(176)........: 
MPID_Init(1548)..............: 
MPIDI_OFI_mpi_init_hook(1554): 
(unknown)(): Other MPI error
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090959
:
system msg for write_line failure : Bad file descriptor
Abort(1090959) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(176)........: 
MPID_Init(1548)..............: 
MPIDI_OFI_mpi_init_hook(1554): 
(unknown)(): Other MPI error
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090959
:
system msg for write_line failure : Bad file descriptor

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by lyj555** [comment]
python环境是3.10，cuda是11.8，torch是2.0.1，显卡版本是TeslaV100，32G

**Comment by jklj077** [comment]
您用的什么环境呀，单卡还是多卡，单机还是多机。哪个脚本跑的，请提供完整的log。正常情况下，是不会用到MPI的。

**Comment by lyj555** [comment]
@jklj077 
输入：sh finetune.sh 
环境：
python环境是3.10，cuda是11.8，torch是2.0.1，显卡版本是TeslaV100，32G（2个卡）

控制台输出：
[2023-10-26 11:40:18,246] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|███████████████████████████████████| 3/3 [00:01<00:00,  1.99it/s]
trainable params: 143,130,624 || all params: 1,388,056,576 || trainable%: 10.311584302454254
Loading data...
Formatting inputs...Skip in lazy mode
Abort(1090959) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(176)........: 
MPID_Init(1548)..............: 
MPIDI_OFI_mpi_init_hook(1554): 
(unknown)(): Other MPI error
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090959
:
system msg for write_line failure : Bad file descriptor
Abort(1090959) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(176)........: 
MPID_Init(1548)..............: 
MPIDI_OFI_mpi_init_hook(1554): 
(unknown)(): Other MPI error
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090959
:
system msg for write_line failure : Bad file descriptor
finetune.sh: line 41: 19890 Segmentation fault      $PYTHON_PATH finetune.py --model_name_or_path $MODEL --data_path $DATA --fp16 True --output_dir output_qwen --num_train_epochs 2 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 1000 --save_total_limit 10 --learning_rate 5e-5 --weight_decay 0.1 --adam_beta2 0.95 --warmup_ratio 0.01 --lr_scheduler_type "cosine" --logging_steps 1 --report_to "none" --model_max_length 512 --lazy_preprocess True --gradient_checkpointing --use_lora --q_lora --deepspeed ./ds_config_zero2.json

**Comment by jklj077** [comment]
您的finetune.sh是基于finetune_qlora_ds.sh改的吗？看执行的命令似乎是single_gpu脚本改的，那个脚本是不支持多卡微调的。

**Comment by lyj555** [comment]
> 您的finetune.sh是基于finetune_qlora_ds.sh改的吗？看执行的命令似乎是single_gpu脚本改的，那个脚本是不支持多卡微调的。

训练脚本没有动过，直接用源码跑的。
我再研究研究吧，前面跑的时候，一直说gcc的版本太低，刚升级完，可能机器配置还有有点问题。

**Comment by jklj077** [comment]
您用的哪个脚本/源码，这个repo里好多finetune脚本的，目前没有提供`finetune.sh`这个名字的脚本的。

报错的部分
```
finetune.sh: line 41: 19890 Segmentation fault $PYTHON_PATH finetune.py ...
```
1. 我们最新脚本里没有这个写法的。
2. 多卡要用torchrun且配置好分布式的参数，参见finetune_qlora_ds.sh脚本里的写法哈。

**Comment by lyj555** [comment]
> 您用的哪个脚本/源码，这个repo里好多finetune脚本的，目前没有提供`finetune.sh`这个名字的脚本的。
> 
> 报错的部分
> 
> ```
> finetune.sh: line 41: 19890 Segmentation fault $PYTHON_PATH finetune.py ...
> ```
> 
> 1. 我们最新脚本里没有这个写法的。
> 2. 多卡要用torchrun且配置好分布式的参数，参见finetune_qlora_ds.sh脚本里的写法哈。

这是是finetune.sh的脚本，基于[finetune_qlora_single_gpu.sh](https://github.com/QwenLM/Qwen/blob/main/finetune/finetune_qlora_single_gpu.sh)这个改的。

微调的脚本finetune.py没有动过啦。
```
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

#MODEL="Qwen/Qwen-7B-Chat-Int4" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="./20231018_finetune_data.json"
MODEL="./model_file/qwen-7b-chat-int4"
PYTHON_PATH="/data/home/liuyj12/anaconda3_new/envs/py310_qwen/bin/python"

export CUDA_VISIBLE_DEVICES=0

# Remember to use --fp16 instead of --bf16 due to autogptq

# default lr：3e-4
$PYTHON_PATH finetune.py \
  --model_name_or_path $MODEL \
  --data_path $DATA \
  --fp16 True \
  --output_dir output_qwen \
  --num_train_epochs 2 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 1000 \
  --save_total_limit 10 \
  --learning_rate 5e-5 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --report_to "none" \
  --model_max_length 512 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora \
  --q_lora \
  --deepspeed ./ds_config_zero2.json 
```

**Comment by jklj077** [comment]
环境是有两张卡，但只用一张卡微调吗？

**Comment by lyj555** [comment]
> 环境是有两张卡，但只用一张卡微调吗？

想的是这样的，使用两张卡的话，也可以的

**Comment by xiaolvtongxue-zt** [comment]
> > 您用的哪个脚本/源码，这个repo里好多finetune脚本的，目前没有提供`finetune.sh`这个名字的脚本的。
> > 报错的部分
> > ```
> > finetune.sh: line 41: 19890 Segmentation fault $PYTHON_PATH finetune.py ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. 我们最新脚本里没有这个写法的。
> > 2. 多卡要用torchrun且配置好分布式的参数，参见finetune_qlora_ds.sh脚本里的写法哈。
> 
> 这是是finetune.sh的脚本，基于[finetune_qlora_single_gpu.sh](https://github.com/QwenLM/Qwen/blob/main/finetune/finetune_qlora_single_gpu.sh)这个改的。
> 
> 微调的脚本finetune.py没有动过啦。
> 
> ```
> export CUDA_DEVICE_MAX_CONNECTIONS=1
> DIR=`pwd`
> 
> #MODEL="Qwen/Qwen-7B-Chat-Int4" # Set the path if you do not want to load from huggingface directly
> # ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
> # See the section for finetuning in README for more information.
> DATA="./20231018_finetune_data.json"
> MODEL="./model_file/qwen-7b-chat-int4"
> PYTHON_PATH="/data/home/liuyj12/anaconda3_new/envs/py310_qwen/bin/python"
> 
> export CUDA_VISIBLE_DEVICES=0
> 
> # Remember to use --fp16 instead of --bf16 due to autogptq
> 
> # default lr：3e-4
> $PYTHON_PATH finetune.py \
>   --model_name_or_path $MODEL \
>   --data_path $DATA \
>   --fp16 True \
>   --output_dir output_qwen \
>   --num_train_epochs 2 \
>   --per_device_train_batch_size 2 \
>   --per_device_eval_batch_size 1 \
>   --gradient_accumulation_steps 8 \
>   --evaluation_strategy "no" \
>   --save_strategy "steps" \
>   --save_steps 1000 \
>   --save_total_limit 10 \
>   --learning_rate 5e-5 \
>   --weight_decay 0.1 \
>   --adam_beta2 0.95 \
>   --warmup_ratio 0.01 \
>   --lr_scheduler_type "cosine" \
>   --logging_steps 1 \
>   --report_to "none" \
>   --model_max_length 512 \
>   --lazy_preprocess True \
>   --gradient_checkpointing \
>   --use_lora \
>   --q_lora \
>   --deepspeed ./ds_config_zero2.json 
> ```

为什么使用的模型 Qwen/Qwen-7B-Chat-Int4进行微调，模型输出的 
trainable params: 143,130,624 || all params: 1,388,056,576 || trainable%: 10.311584302454254
all params只有13亿，这个问题是为啥？

**Comment by jklj077** [comment]
> 为什么使用的模型 Qwen/Qwen-7B-Chat-Int4进行微调，模型输出的all params只有13亿，这个问题是为啥？

1. 由于peft计算参数量的方式和auto-gptq的实现方式，peft计算出来的参数量（只算了named_parameters）**小于**量化后存储的参数量（量化层中都是用register_buffer登记的普通tensor）。
2. 由于GPTQ的量化方式，量化后存储参数量**小于**原始模型存储的参数量。这个在HuggingFace Hub上有体现，[量化模型Qwen-7B-Chat-Int4的存储参数量是2.11B](https://huggingface.co/Qwen/Qwen-7B-Chat-Int4?show_tensors=true)。

但最终传统意义上讲的模型参数量都是算7B的。
