### ISSUE TITLE
int4量化模型存在显存占用逐步增加的情况。且代码无法消除。

### ISSUE THREAD

**Issue by chiliuliu** [QwenLM/Qwen#538]
最开始的内存占用是10215MiB，在询问几个问题后，占用内存上升了20%，到了12027MiB。
调用torch.cuda.empty_cache()后依然无法消除额外缓存。代码为最新代码。

**Comment by jklj077** [comment]
请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~

**Comment by wangchao1980** [comment]
@chiliuliu @jklj077 我的问题更严重，我的显卡是10G显存，运行一会直接把我电脑干重启了，连看错误的机会都没给

**Comment by quida01** [comment]
> 请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~

我的也是同样问题。用的是web demo

**Comment by fyabc** [comment]
> > 请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~
> 
> 我的也是同样问题，通义千问用Web_DEMO.py加载推理72B量化4版本时，问多几次显存会不断增加，直到爆满后报错（在显存几乎爆满前，点击🧹 Clear History (清除历史),才可以把显存清除。该原因可能是显存将近爆满时运行 torch._C._cuda_emptyCache() 失败）。用的是web demo，报错信息为：
> 
> ```
> torch._C._cuda_emptyCache()
> ```
> 
> RuntimeError: CUDA error: unspecified launch failure CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 经查有以下参考资料： 在训练时, 每一个batch后都会将模型的梯度进行一次清零. 而测试的时候我则没有加这一步, 这样的话每次模型再做推理的时候都会产生新的梯度, 并累积到显存当中.
> 
> 清楚了问题, 那么解决方法也就随之而来, 在测试的时候让模型不要记录梯度就好, 因为其实也用不到:
> 
> with torch.no_grad(): test()

您好，理论上web_demo.py运行时内部调用的是`model.generate()`，这个函数已经包含了`torch.no_grad()`调用，不应当有梯度的累积。我们在本地测试时没有发现相应的情况（点击清除历史总是能清除显存），可以提供一个详细一些的复现方法吗？

**Comment by quida01** [comment]
> > > 请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~
> > 
> > 
> > 我的也是同样问题，通义千问用Web_DEMO.py加载推理72B量化4版本时，问多几次显存会不断增加，直到爆满后报错（在显存几乎爆满前，点击🧹 Clear History (清除历史),才可以把显存清除。该原因可能是显存将近爆满时运行 torch._C._cuda_emptyCache() 失败）。用的是web demo，报错信息为：
> > ```
> > torch._C._cuda_emptyCache()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > RuntimeError: CUDA error: unspecified launch failure CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > 经查有以下参考资料： 在训练时, 每一个batch后都会将模型的梯度进行一次清零. 而测试的时候我则没有加这一步, 这样的话每次模型再做推理的时候都会产生新的梯度, 并累积到显存当中.
> > 清楚了问题, 那么解决方法也就随之而来, 在测试的时候让模型不要记录梯度就好, 因为其实也用不到:
> > with torch.no_grad(): test()
> 
> 您好，理论上web_demo.py运行时内部调用的是`model.generate()`，这个函数已经包含了`torch.no_grad()`调用，不应当有梯度的累积。我们在本地测试时没有发现相应的情况（点击清除历史总是能清除显存），可以提供一个详细一些的复现方法吗？

用的模型是下载的Qwen-72B-Chat-Int4，脚本用的是Qwen-main/web_demo.py，显卡是NVIDIA RTX A6000，单卡显存48G。
是在推理时，当问同一个问题十多次时，会占用显存48G以上，然后再问的话，聊天页面上就会报Error，这时如果再清除历史，也不会清除显存（显存如果不爆满，则不会出现Error，点击清除历史总是能清除显存）

**Comment by fyabc** [comment]
> > > > 请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~
> > > 
> > > 
> > > 我的也是同样问题，通义千问用Web_DEMO.py加载推理72B量化4版本时，问多几次显存会不断增加，直到爆满后报错（在显存几乎爆满前，点击🧹 Clear History (清除历史),才可以把显存清除。该原因可能是显存将近爆满时运行 torch._C._cuda_emptyCache() 失败）。用的是web demo，报错信息为：
> > > ```
> > > torch._C._cuda_emptyCache()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > RuntimeError: CUDA error: unspecified launch failure CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > > 经查有以下参考资料： 在训练时, 每一个batch后都会将模型的梯度进行一次清零. 而测试的时候我则没有加这一步, 这样的话每次模型再做推理的时候都会产生新的梯度, 并累积到显存当中.
> > > 清楚了问题, 那么解决方法也就随之而来, 在测试的时候让模型不要记录梯度就好, 因为其实也用不到:
> > > with torch.no_grad(): test()
> > 
> > 
> > 您好，理论上web_demo.py运行时内部调用的是`model.generate()`，这个函数已经包含了`torch.no_grad()`调用，不应当有梯度的累积。我们在本地测试时没有发现相应的情况（点击清除历史总是能清除显存），可以提供一个详细一些的复现方法吗？
> 
> 用的模型是下载的Qwen-72B-Chat-Int4，脚本用的是Qwen-main/web_demo.py（模型改为本地目录的Qwen-72B-Chat-Int4），显卡是NVIDIA RTX A6000，单卡显存48G。 是在推理时，当问同一个问题十多次时，会占用显存48G以上，然后再问的话，聊天页面上就会报Error，这时如果再清除历史，也不会清除显存（显存如果不爆满，则不会出现Error，点击清除历史总是能清除显存）

我们这边暂时复现不了这个情况，请问聊天页面出现Error的情况下刷新页面之后再清除历史可以清除显存吗？

**Comment by quida01** [comment]
> > > > > 请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~
> > > > 
> > > > 
> > > > 我的也是同样问题，通义千问用Web_DEMO.py加载推理72B量化4版本时，问多几次显存会不断增加，直到爆满后报错（在显存几乎爆满前，点击🧹 Clear History (清除历史),才可以把显存清除。该原因可能是显存将近爆满时运行 torch._C._cuda_emptyCache() 失败）。用的是web demo，报错信息为：
> > > > ```
> > > > torch._C._cuda_emptyCache()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > RuntimeError: CUDA error: unspecified launch failure CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > > > 经查有以下参考资料： 在训练时, 每一个batch后都会将模型的梯度进行一次清零. 而测试的时候我则没有加这一步, 这样的话每次模型再做推理的时候都会产生新的梯度, 并累积到显存当中.
> > > > 清楚了问题, 那么解决方法也就随之而来, 在测试的时候让模型不要记录梯度就好, 因为其实也用不到:
> > > > with torch.no_grad(): test()
> > > 
> > > 
> > > 您好，理论上web_demo.py运行时内部调用的是`model.generate()`，这个函数已经包含了`torch.no_grad()`调用，不应当有梯度的累积。我们在本地测试时没有发现相应的情况（点击清除历史总是能清除显存），可以提供一个详细一些的复现方法吗？
> > 
> > 
> > 用的模型是下载的Qwen-72B-Chat-Int4，脚本用的是Qwen-main/web_demo.py（模型改为本地目录的Qwen-72B-Chat-Int4），显卡是NVIDIA RTX A6000，单卡显存48G。 是在推理时，当问同一个问题十多次时，会占用显存48G以上，然后再问的话，聊天页面上就会报Error，这时如果再清除历史，也不会清除显存（显存如果不爆满，则不会出现Error，点击清除历史总是能清除显存）
> 
> 我们这边暂时复现不了这个情况，请问聊天页面出现Error的情况下刷新页面之后再清除历史可以清除显存吗？

可以清除。用千问自带的web_demo,在页面出现Error点“清除历史”后，可以立即减少部分显存（恢复到刚加载完模型时的显示存大小）了，但不应该出现Error，因为其它33B的模型到了90%左右显存容量时，是不会继续增加的。

**Comment by wangchao1980** [comment]
我用的是windows的wsl2和docker在运行的，Qwen-72B-Chat-Int4，我的显存是10G的，运行时电脑直接崩掉了




王超
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QwenLM/Qwen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月15日(星期五) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QwenLM/Qwen] int4量化模型存在显存占用逐步增加的情况。且代码无法消除。 (Issue #538)





      
请提供下复现方法哈，比如运行的哪个脚本(cli demo, web demo, vllm inference)，还是用哪部分的示例代码直接运行的~
  
我的也是同样问题，通义千问用Web_DEMO.py加载推理72B量化4版本时，问多几次显存会不断增加，直到爆满后报错（在显存几乎爆满前，点击🧹 Clear History (清除历史),才可以把显存清除。该原因可能是显存将近爆满时运行 torch._C._cuda_emptyCache() 失败）。用的是web demo，报错信息为：
 torch._C._cuda_emptyCache()  
RuntimeError: CUDA error: unspecified launch failure CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
 经查有以下参考资料： 在训练时, 每一个batch后都会将模型的梯度进行一次清零. 而测试的时候我则没有加这一步, 这样的话每次模型再做推理的时候都会产生新的梯度, 并累积到显存当中.
 清楚了问题, 那么解决方法也就随之而来, 在测试的时候让模型不要记录梯度就好, 因为其实也用不到:
 with torch.no_grad(): test()
  
您好，理论上web_demo.py运行时内部调用的是model.generate()，这个函数已经包含了torch.no_grad()调用，不应当有梯度的累积。我们在本地测试时没有发现相应的情况（点击清除历史总是能清除显存），可以提供一个详细一些的复现方法吗？
  
用的模型是下载的Qwen-72B-Chat-Int4，脚本用的是Qwen-main/web_demo.py（模型改为本地目录的Qwen-72B-Chat-Int4），显卡是NVIDIA RTX A6000，单卡显存48G。 是在推理时，当问同一个问题十多次时，会占用显存48G以上，然后再问的话，聊天页面上就会报Error，这时如果再清除历史，也不会清除显存（显存如果不爆满，则不会出现Error，点击清除历史总是能清除显存）
  
我们这边暂时复现不了这个情况，请问聊天页面出现Error的情况下刷新页面之后再清除历史可以清除显存吗？
  
可以清除。用千问自带的web_demo,在页面出现Error点“清除历史”后，可以立即减少部分显存（恢复到刚加载完模型时的显示存大小）了，但不应该出现Error，因为其它33B的模型到了90%左右显存容量时，是不会继续增加的。

**Comment by jklj077** [comment]
这个可能有一个误会。
对话模型是会将所有对话历史传入模型的，并不是只传的当前轮，对话轮数越多，显存占用就会越大，如果太长了就会OOM，这个行为跟empty_cache和no_grad等都是无关的。
其它模型可能限制的长度更短，多余这个长度就会对历史进行截断，显存占会呈现达到最大不变的情况。
Qwen同样可以限制输入历史的长度，您调小generation_config.json中的max_window_size (输入)或max_new_tokens (输出)即可。
