### ISSUE TITLE
14B 模型 config 中的 seq_length 是什么含义？

### ISSUE THREAD

**Issue by ericxsun** [QwenLM/Qwen#540]
14b的 config 中 seq_length=2048，这个字段代表什么含义呢？看模型最大长度是8192。另外，如果我继续 pretrain ，可以把seq_length 改成 8192 吗？谢谢

**Comment by jklj077** [comment]
这个字段记录了模型训练时使用的训练长度。模型最大长度8192是通过dynamic_ntk的方式扩展的，ntk计算时会用到模型原始训练时采用长度以确定相关系数。

继续预训练的话，如果您有足够长的数据，修改基础的长度是可行的。但预训练中直接扩展长度可能达不到最优的效果，请参考有关长度扩展论文以确定适合您的方案。

**Comment by jklj077** [comment]
关于扩展长度的问题，欢迎移步<https://github.com/QwenLM/Qwen/issues/490>讨论。
