### ISSUE TITLE
[BUG] Cannot merge LORA layers when the model is gptq quantized

### ISSUE THREAD

**Issue by sjhm131** [QwenLM/Qwen#542]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

finetune Qwen-7B-Chat-Int4后对微调后的模型进行merged_model = model.merge_and_unload() 会报Cannot merge LORA layers when the model is gptq quantized错误，请问如何解决

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
GPTQ的模型没法和lora层合并哈，lora层的参数都是fp16的

**Comment by sjhm131** [comment]
@JustinLin610 我想对Qwen-7B-Chat-Int4进行微调后，在合并的话 应该如何操作呢

**Comment by JustinLin610** [comment]
为什么一定要合并呢？你可以直接用于推理的啊

**Comment by sjhm131** [comment]
@JustinLin610 想在下层应用的时候统一下导入方式

**Comment by jklj077** [comment]
只是个人思路供参考，不代表官方意见，没有实际执行过，不知道效果怎么样哈。

按理说要实现合并，需要dequantize量化模型、merge LoRA适配器，这样得到一个fp16的模型，然后再重新quantize并校准，整个过程走下来会引入很多不可控因素、实际效果得实测看看了。

**Comment by jklj077** [comment]
如代码提示，目前不支持这种合并方式。后续可能会支持，但不是很优先哈。

如果仅是想在下层应用时统一导入方式，也可以考虑系统设计上增加适配模块。
