### ISSUE TITLE
[BUG] 输入QwenModel做embedding，输出nan

### ISSUE THREAD

**Issue by YuMeng2v** [QwenLM/Qwen#546]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

输入tensor，经过modelling_qwen.py的QwenModel之后，出现nan
输入：
tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,   198, 49772,   263,
           472,  2200,  3179]], device='cuda:0') torch.Size([1, 63])

输出：
transformer_outputs_entity1 tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0',
       dtype=torch.float16, grad_fn=<ViewBackward0>)

### 期望行为 | Expected Behavior

希望出现经过qwen embedding之后的结果

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
请提供下复现代码，特别是以下几点：
1. 输入（`input_ids`）是如何构造的？
2. `attention_mask`与`position_ids`是如何设置的？

另外，需要提醒您，Qwen是仅有解码器的语言模型，如您目标是特征抽取，Qwen并不适合，请谨慎使用。

**Comment by YuMeng2v** [comment]
> 请提供下复现代码，特别是以下几点：
> 
>     1. 输入（`input_ids`）是如何构造的？
> 
>     2. `attention_mask`与`position_ids`是如何设置的？
> 
> 
> 另外，需要提醒您，Qwen是仅有解码器的语言模型，如您目标是特征抽取，Qwen并不适合，请谨慎使用。

我理解一下，也就是token->nn.embedding->self.transformer之后，self.transformer的输出，已经是用来自回归的输出，也就是decoder的输出了是吗，不适合拿来做特征的对比

**Comment by jklj077** [comment]
1. NaN的出现是比较异常，需要您提供之前1. 2.的信息，我们帮您看下原因。正常情况下input_ids中不应该这么多`0`，transformer_outputs里的输出不应该有NaN。

**Comment by YuMeng2v** [comment]
> NaN的出现是比较异常，需要您提供之前1. 2.的信息，我们帮您看下原因。正常情况下input_ids中不应该这么多`0`，transformer_outputs里的输出不应该有NaN。

我这边经过layer norm之后，梯度正常了，应该就是梯度爆炸了，感谢！。

> > 我理解一下，也就是token->nn.embedding->self.transformer之后，self.transformer的输出，已经是用来自回归的输出，也就是decoder的输出了是吗，不适合拿来做特征的对比
> 
> 嗯，Qwen模型是完全自回归的decoder-only模型，是没有传统意义上的编码器的。

好的好的，看来要改方案了lol，

**Comment by loganzhang1** [comment]
您好，想问一下layer norm您是加到了模型的那个地方呢？我也遇到了这个问题。期待您的解答，谢谢。

**Comment by YuMeng2v** [comment]
> 您好，想问一下layer norm您是加到了模型的那个地方呢？我也遇到了这个问题。期待您的解答，谢谢。

你可以搜一下RMSNorm，一般是在skip-connection 有add&norm
