### ISSUE TITLE
Does Qwen provide encoder part of the whole model like "T5EncoderModel"?

### ISSUE THREAD

**Issue by MengHao666** [QwenLM/Qwen#549]
Thanks for great work, and I am curious about could I use the encoder part only to get features for my multi-modal task like https://huggingface.co/docs/transformers/model_doc/t5#transformers.T5EncoderModel

**Comment by jklj077** [comment]
Hi, Qwen is a decoder-only model and is generally not suitable for extracting text embedding features.

**Comment by MengHao666** [comment]
thanks
