### ISSUE TITLE
[Help] How to use RAG (Retrieval Augmented Generation) with Qwen 

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [QwenLM/Qwen#551]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I have fine tuned a QLoRa version of Qwen for a specific use case. I need to use RAG on this model. Any help or repository(s) showcasing the same with Qwen?

### 期望行为 | Expected Behavior

The use case is such,
- not always RAG is required, only for few FAQ questions. So model must be able to query vector db only in certain cases.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by tuhahaha** [comment]
I suggest using RAG as a tool and using the [ReAct template](https://github.com/QwenLM/Qwen/blob/main/examples/react_demo.py) to determine whether to use RAG in a specific query. Once Qwen chooses to use it, you can design your own retrieval algorithm or refer to [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/memory/memory.py), which has a simple string based retrieval logic.
