### ISSUE TITLE
qwen多卡推理速度慢十倍，是怎么回事？

### ISSUE THREAD

**Issue by LinGuan0624** [QwenLM/Qwen#552]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

qwen 14b、7b系列模型，多卡推理速度比单卡推理速度慢十倍！

在没有安装flash-attention时，进行多卡推理，速度比单卡推理的速度慢了近10倍，安装了flash-attention后有所缓解，但也比单卡慢一些。

### 期望行为 | Expected Behavior

多卡推理不应该慢这么多

### 复现方法 | Steps To Reproduce

 tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
 model = AutoModelForCausalLM.from_pretrained(
        model_path, trust_remote_code=True, device_map='auto'
    )
 model.generation_config = GenerationConfig.from_pretrained(model_path,
                                                               trust_remote_code=True)

 for response in model.chat_stream(tokenizer, input, history[:-1]):
        print(respone)

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.33.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
如您多卡推理的目标是部署，请参考README中关于部署的最新说明。

<https://github.com/QwenLM/Qwen/blob/main/README_CN.md#%E9%83%A8%E7%BD%B2>

> 如希望部署及加速推理，我们建议你使用vLLM和FastChat。

**Comment by AlexasXu** [comment]
> 如您多卡推理的目标是部署，请参考README中关于部署的最新说明。
> 
> https://github.com/QwenLM/Qwen/blob/main/README_CN.md#%E9%83%A8%E7%BD%B2
> 
> > 如希望部署及加速推理，我们建议你使用vLLM和FastChat。

多卡使用cli demo 启动好像提升很有限

**Comment by jklj077** [comment]
> 多卡使用cli demo 启动好像提升很有限

是的，cli_demo里多卡是transformers的实现，具体可参见 https://github.com/QwenLM/Qwen/issues/511#issuecomment-1801972535
