### ISSUE TITLE
[BUG] <title>请问nn.embedding模块会参与反向传播吗

### ISSUE THREAD

**Issue by YuMeng2v** [QwenLM/Qwen#555]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

tokenize->nn.embedding->QWenBlock->输出embedding->nn.Linear 输出token计算loss
请求nn.embedding会参与反向传播吗，想在embedding层计算loss优化效果。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您好，本repo提供的finetune代码中，全量微调是会训练embedding的，LoRA中是否训练embedding可以通过修改代码实现转换，请参见README中的说明。如果是使用的自己的代码，这部分是否被训练完全由您控制。

**Comment by YuMeng2v** [comment]
> 您好，本repo提供的finetune代码中，全量微调是会训练embedding的，LoRA中是否训练embedding可以通过修改代码实现转换，请参见README中的说明。如果是使用的自己的代码，这部分是否被训练完全由您控制。

谢谢，我看到了是调整modules_to_save，想问下可以给一个教程，或者示例吗，我想调整一下trainable的模块

**Comment by jklj077** [comment]
请参见代码https://github.com/QwenLM/Qwen/blob/c00209f932c38c45ac885a4db7c2429885d93f5c/finetune.py#L324-L327

目前是一个规则判定的：如果使用LoRA且非QLoRA且模型名不含chat，则会默认训练embedding。

**Comment by jklj077** [comment]
我理解下：是用自己的微调代码，然后是lora的形式？lora的话adapter加到哪层上这个都需要自行配置的。不是lora的话，其实默认都会计算的。

**Comment by YuMeng2v** [comment]
> 我理解下：是用自己的微调代码，然后是lora的形式？lora的话adapter加到哪层上这个都需要自行配置的。不是lora的话，其实默认都会计算的。

嗯嗯了解了，问题解决了，非常感谢
