### ISSUE TITLE
[BUG] <title> 模型存在早停现象

### ISSUE THREAD

**Issue by meichangsu1** [QwenLM/Qwen#559]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

当前使用qwen14b int4,  输出的内容回答不完整

### 期望行为 | Expected Behavior

问题回答完整

### 运行环境 | Environment

```Markdown
- OS:linux
- Python:3.10
- Transformers: .33
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by meichangsu1** [comment]
运行环境
- OS:linux
- Python:3.10
- Transformers: 4.32.0
- PyTorch:2.01
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):

**Comment by jklj077** [comment]
请问是否方便提供具体的样例以利复现，另外是用的样例代码、cli_demo、web_demo、openai_api还是vllm呢？

**Comment by meichangsu1** [comment]
目前是使用的webdemo：
问题是：
summarize information from the following text:
<text>
[{"序号": 1, "客户名称": "广州市黄埔房地产开发总公司", "贷款余额": 166083000.43, "欠息": 75505814.09, "代垫费用（含诉讼费、保全费等）": 0, "主担保方式": "抵押+保证", "抵押物": "白云区西槎路同景东街20号、28号、70号、78号、80号、88号铺；黄埔区大沙北路121号（一楼）、123号（二楼）；黄埔区丰乐中路9号首层、11,13,15,17,19,21号首层、132号首层、134号首层、134号二层、146号首层、146号二层、148号首层；", "保证人": "唐燕春、李建霖、郑子华、刘松霖、骆锦标及李华彬", "备注": "执行阶段"}, {"序号": 2, "客户名称": "广东天戟生物医药科技有限公司", "贷款余额": 2903103.59, "欠息": 209625.59, "代垫费用（含诉讼费、保全费等）": 20662, "主担保方式": "质押+保证", "抵押物": "广东天戟生物医药科技有限公司于2020年3月4日（含）到2020年12月31日（含）期间向佛山市富明房地产开发有限公司销售口罩所产生的应收账款质押（价值375万元）", "保证人": "曾志量、刘艳、吴浩、李惠莉", "备注": "一审判决"}]
</text>
and return json object with properties: "{'公告名称','公告ID','公告日期','债务人','债权本金(万元)','债权利息(万元)','债权总额(万元)','费用(万元)','基准日','诉讼状态','保证人或担保人':[],'抵质押物':[{'抵质押物详细情况', '抵质押物详细地址','抵质押物类型','房产类型', '房产面积'}]}" 
注意：房产类型是指住宅、公寓、商铺等。请不要输出额外字符，仅输出JSON对象即可，一个债务人对应一条数据，有多个抵质押物的需要每个都拆分出来，多处房产、车位的也要拆分出来


答案是：

[
    {
        "公告名称": "A公司欠款公告",
        "公告ID": 1,
        "公告日期": "待更新",
        "债务人": "A公司",
        "债权本金(万元)": 100000.43,
        "债权利息(万元)": 100000.09,
        "债权总额(万元)": 200000.52,
        "费用(万元)": 0,
        "基准日": "待更新",
        "诉讼状态": "执行阶段",
        "保证人或担保人": [
            {
                "保证人或担保人名称": "李明",
                "抵质押物详细情况": "抵押",
                "抵质押物详细地址": "南山区西槎路同景东街21号、23号、7号",
                "抵质押物类型": "房产",
                "房产类型": "住宅",
                "房产面积": "待更新"
            },
            {
                "保证人或担保人名称": "王强",
                "抵质押物详细情况": "抵押",
                "抵质押物详细地址": "南山区西槎路同景东街21号、23号、7号",
                "抵质押物类型": "房产",
                "房产类型": "住宅",
                "房产面积": "待更新"
            }
        ]
    },
    {
        "公告名称": "B公司欠款公告",
        "公告ID": 2,
        "公告日期": "待更新",
        "债务人": "B公司",
        "债权本金(万元)": 200000.59,
        "债权利息(万元)": 1000000.59,
        "债权总额(万元)": 1200001.18,
        "费用(万元)": 20662,
        "基准日": "待更新",
        "诉讼状态": "一审判决",
        "保证人或担保人": [
            {
                "保证人或担保人名称": "张三",
                "抵质押物详细情况": "保证",
                "抵质押物详细地址": "南山区西槎路同景东街21号、23号、7号",
                "抵质押物类型": "房产",
                "房产

**Comment by meichangsu1** [comment]
目前是使用的webdemo
问题是：
请总结以下json
[
{
"序号": 1,
"客户名称": "A公司",
"贷款余额": 100000.43,
"欠息": 100000.09,
"代垫费用（含诉讼费、保全费等）": 0,
"主担保方式": "抵押+保证",
"抵押物": "南山区西槎路同景东街21号、23号、7号",
"保证人": "李明、王强",
"备注": "执行阶段"
},
{
"序号": 2,
"客户名称": "B公司",
"贷款余额": 200000.59,
"欠息": 1000000.59,
"代垫费用（含诉讼费、保全费等）": 20662,
"主担保方式": "质押+保证",
"抵押物": "南山区西槎路同景东街21号、23号、7号",
"保证人": "张三，李四",
"备注": "一审判决"
}
]
返回json需符合以下格式: "{'公告名称','公告ID','公告日期','债务人','债权本金(万元)','债权利息(万元)','债权总额(万元)','费用(万元)','基准日','诉讼状态','保证人或担保人':[],'抵质押物':[{'抵质押物详细情况', '抵质押物详细地址','抵质押物类型','房产类型', '房产面积'}]}"
注意：房产类型是指住宅、公寓、商铺等。请不要输出额外字符，仅输出JSON对象即可，一个债务人对应一条数据，有多个抵质押物的需要每个都拆分出来，多处房产、车位的也要拆分出来
答案是：
[
    {
        "公告名称": "A公司欠款公告",
        "公告ID": 1,
        "公告日期": "待更新",
        "债务人": "A公司",
        "债权本金(万元)": 100000.43,
        "债权利息(万元)": 100000.09,
        "债权总额(万元)": 200000.52,
        "费用(万元)": 0,
        "基准日": "待更新",
        "诉讼状态": "执行阶段",
        "保证人或担保人": [
            {
                "保证人或担保人名称": "李明",
                "抵质押物详细情况": "抵押",
                "抵质押物详细地址": "南山区西槎路同景东街21号、23号、7号",
                "抵质押物类型": "房产",
                "房产类型": "住宅",
                "房产面积": "待更新"
            },
            {
                "保证人或担保人名称": "王强",
                "抵质押物详细情况": "抵押",
                "抵质押物详细地址": "南山区西槎路同景东街21号、23号、7号",
                "抵质押物类型": "房产",
                "房产类型": "住宅",
                "房产面积": "待更新"
            }
        ]
    },
    {
        "公告名称": "B公司欠款公告",
        "公告ID": 2,
        "公告日期": "待更新",
        "债务人": "B公司",
        "债权本金(万元)": 200000.59,
        "债权利息(万元)": 1000000.59,
        "债权总额(万元)": 1200001.18,
        "费用(万元)": 20662,
        "基准日": "待更新",
        "诉讼状态": "一审判决",
        "保证人或担保人": [
            {
                "保证人或担保人名称": "张三",
                "抵质押物详细情况": "保证",
                "抵质押物详细地址": "南山区西槎路同景东街21号、23号、7号",
                "抵质押物类型": "房产",
                "房产

**Comment by meichangsu1** [comment]
刚才在魔搭社区的qwen-14b-chat上，返回是完整的答案，int8量化的也是返回不完整

**Comment by Tony1Q84** [comment]
请问找到解决办法了嘛，我也出现了类似情况

**Comment by jklj077** [comment]
generation_config.json中的max_new_token有扩大吗？
