### ISSUE TITLE
Flash Attention相关疑问

### ISSUE THREAD

**Issue by sunyclj** [QwenLM/Qwen#560]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

问题1：https://github.com/QwenLM/Qwen#gpu-memory-usage 显存测试是否使用了flash attention?
问题2：已安装flash-attn 2.3.3版本，设置use_flash_attn=True和不设置use_flash_attn=True测试，显存占用一致，请问默认是安装即会启用flash attention吗？设置use_flash_attn=False，显存增加约0.06G，变化不大，请问是什么原因呢？
问题3：如何测试flash attention v1？卸掉2.3.2版本，安装1.x.x版本吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by logicwong** [comment]
@sunyclj 

1. 在安装flashAttention的情况下，默认use_flash_attn=True；
2. use_flash_attn=False时，会调用torch2.0自带的scaled_dot_product_attention，背后自动调用flash_attention或memory_efficient_attention，因此显存占用差距不大；
3. 如果要测试flash attention v1，需要卸载flash 2.0，安装1.x.x版本
