### ISSUE TITLE
[BUG] <qwen2-7b-chat-int4 推理报错>

### ISSUE THREAD

**Issue by liangzimei** [QwenLM/Qwen#561]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

model加载成功，infer报错
response, history = model.chat(tokenizer, "1+2等于多少", history=None)

RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/usr/share/miniconda/envs/build/lib/python3.8/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":25, please report a bug to PyTorch. 

### 复现方法 | Steps To Reproduce

from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

model_name = 'models--Qwen--Qwen-7B-Chat-Int4' 
tokenizer = AutoTokenizer.from_pretrained(f"/root/max-roam/base_model/{model_name}", trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    f"/root/max-roam/base_model/{model_name}",
    device_map="auto",
    trust_remote_code=True
).eval()

response, history = model.chat(tokenizer, "hi", history=None)

### 运行环境 | Environment

```Markdown
- OS: Alibaba Group Enterprise Linux Server release 7.2 (Paladin)
- Python: 3.8
- Transformers: 4.32.0
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): '2.0.0+cu117'
```

**Comment by jklj077** [comment]
有可能是安装的AutoGPTQ版本不兼容，AutoGPTQ同时依赖PyTorch和CUDA的版本。请说明下AutoGPTQ版本和按安装方式哈。
