### ISSUE TITLE
[Inference] 量化算子使用

### ISSUE THREAD

**Issue by frankxyy** [QwenLM/Qwen#562]
在 Qwen-7B-Chat-Int4 仓库里，我看到实际调用的反量化&matmul 融合算子入口函数是 vecquant8matmul_batched_faster_old 。 看起来是8bit的版本，是否应该是4bit的

**Comment by jklj077** [comment]
那部分是KV Cache量化功能的相关代码哈，参见README中的说明<https://github.com/QwenLM/Qwen#quantization-of-kv-cache>，这部分量化跟模型参数量化是无关的。模型参数量化相关的操作是AutoGPTQ自动完成的。

**Comment by frankxyy** [comment]
@jklj077 了解了，谢谢
