### ISSUE TITLE
微调模型，设计训练数据有哪些技巧，具体如何设计呢？

### ISSUE THREAD

**Issue by mawenju203** [QwenLM/Qwen#563]
假设：
input：“新规草案：合肥市的非机动车规范要求，当非机动车首次出现违反交通规则，需要进行口头警告，并备案到系统；当非首次出现违反交规的行为，可以进行25元的罚款，并记录在案，当违反交规行为超过3次，可以从重处罚，扣留非机动车辆；新规草案的设计和当前的法律法规是否存在不一致，请给出判断，并给出修改意见？”

instruction：
解决上述问题的步骤:
第一步：判断该草案是关于xxx主题的，然后搜索xxx主题相关的所有法规的内容；
第二步：将对应法规和新规草案进行对比，找出其中的冲突点，并给出修改意见；

output：

找到《安徽省非机动车行为规范》规定非机动车首次出现违反交规行为需要给予口头警告并处罚款5-10元不等，再次出现违反交规行为，罚款金额不少于50元；
发现新规草案和上位法《安徽省非机动车行为规范》存在冲突点，给予修改意见是 当首次出现违反交通规则的，需要进行口头警告，并给予5元的罚款，并记录在案，当非首次出现违反交规的行为，可以进行50元的罚款，并记录在案，当违反交规行为超过3次，可以从重处罚，罚款50，扣留非机动车辆；

**真正的问题：**

根据上述逻辑，应该如何设计大模型的训练数据呢？ 要求模型具备自动完成instruction中的能力，并且返回类似output的内容；有点类似模型内容自动实现多步 ReAct行为，最后输出output；

**Comment by zRzRzRzRzRzRzR** [comment]
其实可以训练React能力查知识库? Qwen支持工具调用

**Comment by mawenju203** [comment]
其实我更期望模型训练模型的时候，内部执行逻辑是类似人考虑问题一样，将复杂问题拆分，类似与cot（思维链），然后汇总最终的结果；


因为这个《安徽省非机动车行为规范》所有的知识，我都是打算训练进入模型内部的；模型是站在 上帝视角 去审视输入的内容进行对比；
