### ISSUE TITLE
[BUG]     raise KeyError(key) from None KeyError: 'HOME'

### ISSUE THREAD

**Issue by 631068264** [QwenLM/Qwen#564]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用supervisor 启动

```
environment = CUDA_VISIBLE_DEVICES=0
command = /bin/bash -c "source /data/home/yaokj5/anaconda3/bin/activate intell && python -m openai_server --port 8015 --milvus_addr 127.0.0.1:32008 --model qwen-14b"
```

报错
```
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/triton/compiler.py", line 1304, in default_cache_dir
    return os.path.join(os.environ["HOME"], ".triton", "cache")
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您提供的log提示Python脚本运行的环境中缺少`HOME`这个环境变量，对于一般的login shell来说这个是很反常的。

但您使用了supervisor这个我们不好判断发生了什么。而且`conda activate`是适用于交互式shell的，对于这种自动化/programmatic执行的话，可以用`conda run`。这部分建议您遵从相关软件的指南确认下相关的配置。
