### ISSUE TITLE
微调14b-int4模型，loss始终不下降，甚至还有升高

### ISSUE THREAD

**Issue by bbhay** [QwenLM/Qwen#565]
参数如下
![image](https://github.com/QwenLM/Qwen/assets/18276631/8e7db860-0a57-4f62-9d04-8dbb576cac03)

**Comment by bbhay** [comment]
python finetune.py \
  --model_name_or_path $MODEL \
  --data_path $DATA \
  --eval_data_path $EVAL_DATA \
  --output_dir output_qwen_14b_int \
  --num_train_epochs 6 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 4 \
  --gradient_accumulation_steps 2 \
  --evaluation_strategy "steps" \
  --save_strategy "steps" \
  --save_steps 500 \
  --save_total_limit 10 \
  --learning_rate 5e-4 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 50 \
  --report_to "none" \
  --model_max_length 512 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora True \
  --lora_r 4

**Comment by bbhay** [comment]
小幅震荡之后，loss突变成0

**Comment by JustinLin610** [comment]
微调问题，数据看不到还涉及训练参数改动，实在很难判断
