### ISSUE TITLE
量化模型能否用vllm部署？

### ISSUE THREAD

**Issue by 315930399** [QwenLM/Qwen#566]
用24g的卡通过vllm部署int4模型时显示显存不足

使用的命令：
python -m fastchat.serve.vllm_worker --model-path {path} --trust-remote-code

**Comment by appleatiger** [comment]
int4是可以用vllm部署的，不过不是vllm的主线，而是这个fork     https://github.com/chu-tianxiang/vllm-gptq

**Comment by qy8502** [comment]
@appleatiger 
```
cd /usr/local
git clone https://github.com/chu-tianxiang/vllm-gptq
cd vllm-gptq
pip install -e .
```
这样安装替换vllm也不行呢，还需要做什么？

**Comment by 315930399** [comment]
> @appleatiger
> 
> ```
> cd /usr/local
> git clone https://github.com/chu-tianxiang/vllm-gptq
> cd vllm-gptq
> pip install -e .
> ```
> 
> 这样安装替换vllm也不行呢，还需要做什么？
> 
> ```
> Tue Nov  7 06:53:35 2023
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  On   | 00000000:37:00.0 Off |                  N/A |
> | 30%   34C    P2   108W / 350W |  21001MiB / 24576MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  NVIDIA GeForce ...  On   | 00000000:86:00.0 Off |                  N/A |
> | 30%   35C    P2   100W / 350W |  21001MiB / 24576MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A    124370      C   ray::RayWorker                  20988MiB |
> |    1   N/A  N/A    124371      C   ray::RayWorker                  20988MiB |
> +-----------------------------------------------------------------------------+
> (qwen) root@ubuntu:/usr/local/vllm-gptq# sudo journalctl -u qwen.vllm_worker -f
> Nov 07 06:53:14 ubuntu python[121360]: 2023-11-07 06:53:14,601        INFO worker.py:1673 -- Started a local Ray instance.
> Nov 07 06:53:15 ubuntu python[121360]: INFO 11-07 06:53:15 llm_engine.py:72] Initializing an LLM engine with config: model='/usr/local/Qwen/Qwen/Qwen-14B-Chat-Int4', tokenizer='/usr/local/Qwen/Qwen/Qwen-14B-Chat-Int4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=gptq, seed=0)
> Nov 07 06:53:16 ubuntu python[121360]: WARNING 11-07 06:53:16 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> Nov 07 06:53:30 ubuntu python[121360]: INFO 11-07 06:53:30 llm_engine.py:207] # GPU blocks: 2289, # CPU blocks: 655
> Nov 07 06:53:33 ubuntu python[121360]: 2023-11-07 06:53:33 | INFO | model_worker | Loading the model ['Qwen-14B-Chat-Int4'] on worker 0a8ee738, worker type: vLLM worker...
> Nov 07 06:53:33 ubuntu python[121360]: 2023-11-07 06:53:33 | INFO | model_worker | Register to controller
> Nov 07 06:53:33 ubuntu python[121360]: 2023-11-07 06:53:33 | ERROR | stderr | INFO:     Started server process [121360]
> Nov 07 06:53:33 ubuntu python[121360]: 2023-11-07 06:53:33 | ERROR | stderr | INFO:     Waiting for application startup.Nov 07 06:53:33 ubuntu python[121360]: 2023-11-07 06:53:33 | ERROR | stderr | INFO:     Application startup complete.
> Nov 07 06:53:33 ubuntu python[121360]: 2023-11-07 06:53:33 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:21002 (Press CTRL+C to quit)
> Nov 07 06:54:18 ubuntu python[121360]: 2023-11-07 06:54:18 | INFO | model_worker | Send heart beat. Models: ['Qwen-14B-Chat-Int4']. Semaphore: None. call_ct: 0. worker_id: 0a8ee738.
> ```

你这个已经成功部署了吧。我起了openai格式的api以后，用chat/completions得到的回答都是乱七八糟的内容，感觉这个fork对qwen不支持
![屏幕截图 2023-11-07 150117](https://github.com/QwenLM/Qwen/assets/38678334/8efda037-547c-4c3b-8c08-ac08197e5adf)
![屏幕截图 2023-11-07 150152](https://github.com/QwenLM/Qwen/assets/38678334/54baa160-a456-44aa-8075-4b21dbec714c)

**Comment by qy8502** [comment]
@315930399 
乱码还没看到，但是回复内容明显比BF16要差。
我这int4占用显存仍然40G与BF16的一样大呀，你是如何跑起来显存够用的？
`python -m fastchat.serve.vllm_worker --model-path  Qwen\Qwen-14B-Chat-Int4 --trust-remote-code --tensor-parallel-size 2`
除了改模型路径还需要改什么嘛？

**Comment by 315930399** [comment]
> @315930399 乱码还没看到，但是回复内容明显比BF16要差。 我这int4占用显存仍然40G与BF16的一样大呀，你是如何跑起来显存够用的？ `python -m fastchat.serve.vllm_worker --model-path Qwen\Qwen-14B-Chat-Int4 --trust-remote-code --tensor-parallel-size 2` 除了改模型路径还需要改什么嘛？

vllm默认占用显卡的90%显存，这个是正常的

**Comment by qy8502** [comment]
> vllm默认占用显卡的90%显存，这个是正常的

```
    parser.add_argument(
        "--gpu_memory_utilization",
        type=float,
        default=0.9,
        help="The ratio (between 0 and 1) of GPU memory to"
        "reserve for the model weights, activations, and KV cache. Higher"
        "values will increase the KV cache size and thus improve the model's"
        "throughput. However, if the value is too high, it may cause out-of-"
        "memory (OOM) errors.",
    )

```

原来是固定的比例呀，我知道了，谢谢哥们！！

**Comment by jklj077** [comment]
您好，vllm官方尚不支持AutoGPTQ的量化方案，建议关注<https://github.com/vllm-project/vllm/pull/916>和其简化版<https://github.com/vllm-project/vllm/pull/1580>两个PR的情况（现在看前面这个不会merge，后面这个有潜在的巨大性能问题）。此外，相关正确性问题建议寻求vllm社区的帮助。

**Comment by zhuxiaobin** [comment]
<|im_start|> 这些是fastchat里面fastchat/conversation.py的问题，stop_token_ids改成
stop_token_ids=[
            153719,
            153720,
            153721
        ]
   另外vllm这个分支https://github.com/chu-tianxiang/vllm-gptq对14b-int4的推理有问题
