### ISSUE TITLE
[BUG] 使用chat_stream配上do_sample=False会报错

### ISSUE THREAD

**Issue by lzxlin** [QwenLM/Qwen#567]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

发现使用chat_stream时将do_sample设置成False会报错，但是chat不会

```python
tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(path, device_map="auto", trust_remote_code=True).eval()
config = GenerationConfig.from_pretrained(path, trust_remote_code=True, resume_download=True)
config.do_sample = False

while 1:
    query = input('in:')
    if not query:
        break
    for res in model.chat_stream(tokenizer=tokenizer, query=query, history=None, generation_config=config):
        print(res)
```
输入`你好`会以下报错
```
RuntimeError: a Tensor with 30 elements cannot be converted to Scalar
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by fyabc** [comment]
@lzxlin 您好，目前`chat_stream`内部使用的`transformers_stream_generator`暂时不支持`do_sample=False`。如果需要固定输出结果的话，可以考虑在每次生成前指定随机数种子，或设置`top_k=1`的方式。
更多信息可以参考#169。
