### ISSUE TITLE
请问看到readme可以从魔塔下，hugging face加载，也就是现在两个社区的Qwen14B模型文件是一样的吗？

### ISSUE THREAD

**Issue by txy6666yr** [QwenLM/Qwen#568]
如题？

**Comment by liaoweiguo** [comment]
应该一样，我在魔塔下的，用抱抱脸/transformers的包推理没问题

**Comment by Lukeming-tsinghua** [comment]
是的，所有Qwen模型(7B, 14B, 量化等)在huggingface和modelscope都是一样的，欢迎从modelscope下载（从modelscope下载时请注意拉取master版本或最新revision）。

**Comment by txy6666yr** [comment]
> 是的，所有Qwen模型(7B, 14B, 量化等)在huggingface和modelscope都是一样的，欢迎从modelscope下载（从modelscope下载时请注意拉取master版本或最新revision）。

好的明白 谢谢~

**Comment by txy6666yr** [comment]
> 应该一样，我在魔塔下的，用抱抱脸/transformers的包推理没问题

好滴 已经用上啦
