### ISSUE TITLE
是否会提供awq量化后的结果？

### ISSUE THREAD

**Issue by frankxyy** [QwenLM/Qwen#569]
RT，看现在的量化版本均是用gptq的

**Comment by weiminw** [comment]
> RT，看现在的量化版本均是用gptq的

同问

**Comment by jklj077** [comment]
TheBloke has kindly provided AWQ versions of Qwen-7B-Chat and Qwen-14B-Chat. Have a try! 
<https://huggingface.co/TheBloke/Qwen-7B-Chat-AWQ>
<https://huggingface.co/TheBloke/Qwen-14B-Chat-AWQ>
