### ISSUE TITLE
BF16的版本是否有可能优化到14-15GB

### ISSUE THREAD

**Issue by sunnytoday173** [QwenLM/Qwen#57]
16.2GB对于16GB显存的显卡过于不友好了，非常尴尬……
从指标上看int8的版本和BF16也是存在明显差距的，所以有没有可能把BF16的版本优化到16GB显卡可用呢？

**Comment by alfgo** [comment]
期望优化到16G以内，16G显存是个门槛，超过16G不利于模型的使用，要更换显卡。

**Comment by Tongjilibo** [comment]
可否部署到多卡上减少单卡显存占用呢

**Comment by franklyd** [comment]
我这里可以用T4 （16G显存）加载bf16，只是推理的速度很慢

**Comment by txy6666yr** [comment]
> 
Tesla T4 不是只支持fp16吗？最新的官方readme也是推荐T4设置fp16=True
