### ISSUE TITLE
请教贴：关于千问的工具

### ISSUE THREAD

**Issue by LiuChen19960902** [QwenLM/Qwen#572]
如这个https://github.com/QwenLM/Qwen/issues/402#issuecomment-1788507117

想请教一下官方，目前是否有方案可以让模型自己学习什么时候该使用工具，而不是人为去控制。
感谢~

**Comment by jklj077** [comment]
从实用的角度讲，总是需要告诉模型有哪些工具可用的；如果不提供的话，模型产出的工具调用是无法执行的。
- 你所提到的MOSS的构造数据方式，是通过system message来告知模型有哪些工具可用（甚至人为控制的程度更强，工具种类，每个工具的调用方式都在数据中被固定下来，很难泛化到用户自定义的工具上，并不灵活）。
- Qwen目前能够泛化到用户自定义的工具，对于无需使用工具的场景，Qwen也能给出无需使用工具的回应。目前问题是效果还有提升的空间，后续版本更新会改善这一问题。
