### ISSUE TITLE
[Inference][量化] speed测试结果

### ISSUE THREAD

**Issue by frankxyy** [QwenLM/Qwen#576]
<img width="606" alt="image" src="https://github.com/QwenLM/Qwen/assets/6971044/c9aafc4e-1f4b-4950-a436-ff85e90439f1">

你好！我看这个speed测试结果，int8 和 int4 比bf16快。我理解 int8和int4 增加了反量化开销，按道理不会比bf16快吧？这里的结果里，bs是一致的吗？

还有个问题是，为什么没有fp16的结果呢？

**Comment by jklj077** [comment]
> 我理解 int8和int4 增加了反量化开销，按道理不会比bf16快吧？

这个最好看下[GPTQ原论文](https://arxiv.org/pdf/2210.17323.pdf)，GPTQ属于post-training的权重量化，会有反量化开销，但同时由于权重大小减小，GPTQ实现了一个kernel优化访存并融合反量化操作，使得实际速度可能有一定提升。需要注意的是，实际提速情况与量化权重大小和设备存储带宽均可能有关，比如一般情况下int8要比int4提速少。

> 这里的结果里，bs是一致的吗？

是一致的，可以看下README中提供的profile脚本，batch size为1。

> 为什么没有fp16的结果呢？

对于NVIDIA显卡，支持bf16的设备，其fp16的理论性能与bf16是一致的。

**Comment by frankxyy** [comment]
@jklj077 明白了，谢谢！

**Comment by frankxyy** [comment]
@jklj077 大神，能再问问awq kernel infer和 gptq kernel infer相比，哪个速度更快些呢？
