### ISSUE TITLE
Mac M1. openai_api.py encounters `KeyError: 'lm_head.weight'`

### ISSUE THREAD

**Issue by JianxinMa** [QwenLM/Qwen#580]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![See the screenshot from ](https://user-images.githubusercontent.com/28392282/280532245-446a9d8b-d2e0-4c50-a52b-0399714ee185.png)

Original issue: https://github.com/QwenLM/Qwen/issues/586

### 运行环境 | Environment

```Markdown
- OS: mac m1
- Python:3.10
```

**Comment by jklj077** [comment]
closed in favor of https://github.com/QwenLM/Qwen/issues/586
