### ISSUE TITLE
Compatibility Issue: `function_call` should not be included in the returned message if it is None.

### ISSUE THREAD

**Issue by JianxinMa** [QwenLM/Qwen#581]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Currently, openai_api.py returns `message['function_call'] == None`, rather than `'function_call' not in message`. This will fail when one tries to use Qwen with AutoGen.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JianxinMa** [comment]
I'll fix this issue when I have the time.

**Comment by owenzhw** [comment]
Hi, I'm currently facing same problem when running [function call examples](https://github.com/QwenLM/Qwen/blob/main/examples/function_call_examples.py). 
The error message is
```
openai.InternalServerError: Error code: 543 - {'detail': [{'loc': ['body', 'messages', 1, 'content'], 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}]}
```
Will this be fixed soon?
It seems like it is also caused by this problem with openai >=1.0 ...
