### ISSUE TITLE
运行cli_demo.py时产生错误

### ISSUE THREAD

**Issue by 1424153694** [QwenLM/Qwen#584]
(Qwen-14b-2) root@llm-server:/home/Qwen-14b/Qwen-main# python cli_demo.py
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.30it/s]

Welcome to use Qwen-Chat model, type text to start chat, type :h to show command help.
(欢迎使用 Qwen-Chat 模型，输入内容即可进行对话，:h 显示命令帮助。)

Note: This demo is governed by the original license of Qwen.
We strongly advise users not to knowingly generate or allow others to knowingly generate harmful content, including hate speech, violence, pornography, deception, etc.
(注：本演示受Qwen的许可协议限制。我们强烈建议，用户不应传播及不应允许他人传播以下内容，包括但不限于仇恨言论、暴力、色情、欺诈相关的有害信息。)

User: 你好

Qwen-Chat:  decrypted))}

段错误 (核心已转储)

**Comment by fyabc** [comment]
@1424153694 您好，`python cli_demo.py`默认情况下会使用Qwen/Qwen-7B-Chat模型，但是看输出似乎加载的是Qwen-14B模型，能否提供模型的详细信息，包括如何下载的？

**Comment by 1424153694** [comment]
是从huggingface下载Qwen-14b-chat模型到本地。然后拉取魔搭上边的镜像，创建容器，conda创建环境，然后pip安装包，再运行出错了就。中间过程中运行过python web_demo.py，遇到了一个错误，然后按照下述修改就改好了：
1，如果是：Could not create share link. Missing file，按照给出的提示下载frpc_linux_amd64文件，并且按照他的要求修改名称，移动到提示指定的位置，并进行下面2的操作

2，如果是：Could not create share link. Please check your internet connection or our status page: https://status.gradio.app，cd进入frpc_linux_amd64文件的位置（应该在.conda/envs/ChatGLM2/lib/python3.11/site-packages/gradio），输入以下命令给予权限：chmod +x frpc_linux_amd64_v0.2

之后运行就遇到了现在的错误。

下载了在四张3070的卡上，python为3.9，cuda是12.1

**Comment by fyabc** [comment]
您好，可以麻烦您提供一下详细的步骤吗？另外，可以确认一下使用的Qwen-14b-chat模型和代码都是最新版本，然后在web_demo.py里面显示指定`-c /path/to/qwen-14b-chat`再尝试一下。

**Comment by 1424153694** [comment]
1.首先从huggingface和github分别下载Qwen-14b-chat模型和代码到本地。然后拉取魔搭上边的镜像。
2.通过docker run --name=llm_c --gpus=all --net host --shm-size=128g  -it -v /home/ubuntu:/home registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-py38-torch2.0.1-tf2.13.0-1.9.4 /bin/bash创建docker容器
3.进入到conda activate -n Qwen-14b python=3.9创建环境，然后进入到Qwen目录下，使用pip install -r requirements.txt安装包。
4.运行pip install -r requirements_web_demo.txt
5.修改python web_demo.py中DEFAULT_CKPT_PATH = 'Qwen/Qwen-14B-Chat'，并修改 parser.add_argument("--share", action="store_true", default=True,help="Create a publicly shareable link for the interface.")默认值为True ,运行，还是不能打开网页。
6.
(1)按照给出的提示下载frpc_linux_amd64文件，并且按照他的要求修改名称，移动到提示指定的位置，并进行下面2()的操作.
(2)如果是：Could not create share link. Please check your internet connection or our status page: https://status.gradio.app，cd进入frpc_linux_amd64文件的位置（应该在.conda/envs/ChatGLM2/lib/python3.11/site-packages/gradio），输入以下命令给予权限：chmod +x frpc_linux_amd64_v0.2
7.顺利运行打开网页，但是输入问题发送后，网页显示Error，命令行显示下面内容，并且自动退出程序
User: 你好

Qwen-Chat: decrypted))}

段错误 (核心已转储)

8.昨天使用cpu运行python cli_demo.py是没问题的，在上述报错之后，重新使用GPU运行python cli_demo.py也报错

**Comment by jklj077** [comment]
我们理解您在使用过程遇到了以下情况：

1. 使用cli_demo.py在CPU上运行Qwen-14B-Chat模型，正常（此时您的环境配置应当是正常的）
2. 使用web_demo.py在4 x 4070 GPU上运行Qwen-14B-Chat模型，修改了web_demo.py的代码，提示错误
   - 请介绍相关代码的修改，应无需修改代码
     - 您docker似乎已设置了使用host网络，传入`--server-name 0.0.0.0`参数，即`python web_demo.py --server-name "0.0.0.0"`，即可从IP地址和对应端口(默认8000)直接访问。
     - 如使用share功能（产生一个非IP地址的链接），仅传入`--share`即可，`python web_demo.py --share`
     - 如需替换模型参数位置，可以传入`-c`或`--checkpoint-path`参数，即`python web_demo.py -c Qwen/Qwen-14B-Chat`
   - 请附上相关错误记录，以便辅助您定位问题
     - 有可能是gradio的版本问题
3. 对环境进行了修改，出现了段错误，且换为cli_demo.py后无法正常运行（此时您的环境配置应已损坏）
   - 根据该现象，有可能您下载了不匹配的frpc文件
   - 您的说明中使用的是`Qwen-14b`的conda环境，但环境修改说明中指代的是`ChatGLM2`，我们认为这是一个笔误。
