### ISSUE TITLE
intermediate_size错误

### ISSUE THREAD

**Issue by Geministudents** [QwenLM/Qwen#585]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen/Qwen-14B-Chat中的config文件有一个参数"intermediate_size": 27392,但是实际上的intermediate_size为13696

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by liudayiheng** [comment]
是的，实际上为13696，这是因为我们内部实现的时候有个除二操作

**Comment by Geministudents** [comment]
嗷嗷嗷怪不得，感谢您的回复
