### ISSUE TITLE
使用MacBookPro M1 部署，报错：TypeError: BFloat16 is not supported on MPS

### ISSUE THREAD

**Issue by 332123342** [QwenLM/Qwen#587]
部署模型服务 python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c QWen/QWen-7B-Chat
报错：TypeError: BFloat16 is not supported on MPS

使用MacBookPro M1

**Comment by jklj077** [comment]
@332123342 请看下<https://github.com/QwenLM/Qwen/issues/497#issuecomment-1782667685>是否可以解决该问题？
