### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB (GPU 1; 11.77 GiB total capacity; 10.95 GiB already allocated; 132.25 MiB free; 11.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by lizhongxiang12138** [QwenLM/Qwen#589]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用vllm 多卡部署时出现
运行 python -m fastchat.serve.vllm_worker --model-path /usr/src/app/model/qwen/Qwen-14B-Chat-Int8 --trust-remote-code --tensor-parallel-size 2
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB (GPU 1; 11.77 GiB total capacity; 10.95 GiB already allocated; 132.25 MiB free; 11.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.9
- Transformers: 4.35.0
- PyTorch: 2.0.1
- CUDA 11.8
```

**Comment by jklj077** [comment]
我们理解您在使用vllm在两张12GB的显卡上部署Qwen-14B-Chat-Int8模型，遇到了显存不足的问题。

1. vllm官方尚不支持AutoGPTQ量化模型，int8模型由AutoGPTQ量化，您是否进行了有关修改。
2. 是在执行到哪里代码报的错，请尽量提供完整的log。
3. 数据长度大概多长，总量24GB，还有tp的损失，太长可能也放不下的，README中相关信息可以参考看看。
