### ISSUE TITLE
[BUG] <title>为什么我lora微调保存的一个checkpoint 有21gb 是有什么没设置吗

### ISSUE THREAD

**Issue by chenjin19** [QwenLM/Qwen#591]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

为什么我lora微调保存的一个checkpoint 有21gb 是有什么没设置吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

为什么我lora微调保存的一个checkpoint 有21gb 是有什么没设置吗

**Comment by chenjin19** [comment]
![Uploading 企业微信截图_1699351755504.png…]()

**Comment by hyj1991** [comment]
checkpoint-xxx 这个文件夹可以删掉的，一般 lora 就是几十到上百 M 这个量级

**Comment by jklj077** [comment]
transformers会保存optimizer state等用于恢复训练，使用DeepSpeed可能会使保存的文件更大，用于推理的模型参数保留adapter_model.bin文件即可，其它的pt文件可以删除。
