### ISSUE TITLE
💡 [REQUEST] - <Qwen-14B-Chat 如何设置参数可以支持16/32k的推理>

### ISSUE THREAD

**Issue by weiminw** [QwenLM/Qwen#592]
### 摘要 | Summary

Qwen-14B-Chat 如何设置参数可以支持16/32k的推理

### 基本示例 | Basic Example

Qwen-14B-Chat 如何设置参数可以支持16/32k的推理

### 缺陷 | Drawbacks

Qwen-14B-Chat 如何设置参数可以支持16/32k的推理

**Comment by jklj077** [comment]
目前通过设置参数应该不太能支持这么长。后续有可能会更新，敬请期待！
