### ISSUE TITLE
[BUG] <title> 运行chat时，好像加载了两次模型

### ISSUE THREAD

**Issue by lrx1213** [QwenLM/Qwen#594]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

<img width="1417" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/46be6191-aba4-45b2-bafe-43406bdf5d64">

### 期望行为 | Expected Behavior

正常执行

### 运行环境 | Environment

```Markdown
- OS: linux
- Python: 3.10
- Transformers: 4.32.0
- PyTorch:  2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.4
```

**Comment by jklj077** [comment]
请问是多卡运行的吗？

**Comment by Halflifefa** [comment]
类似的问题，双卡4090加载14b-chat，出现加载两次的情况

**Comment by jklj077** [comment]
@lrx1213 @Halflifefa 用哪个脚本加载的呀

**Comment by Halflifefa** [comment]
> @lrx1213 @Halflifefa 用哪个脚本加载的呀

openai_api.py

**Comment by lrx1213** [comment]
> 请问是多卡运行的吗？

单卡运行的

**Comment by lrx1213** [comment]
> @lrx1213 @Halflifefa 用哪个脚本加载的呀

运行脚本如下：


from transformers import AutoTokenizer, AutoModelForCausalLM


os_name = platform.system()
clear_command = 'cls' if os_name == 'Windows' else 'clear'
stop_stream = False


def get_model():
    print("get_model")
    tokenizer = AutoTokenizer.from_pretrained("../Model/Qwen-7B-Chat", trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained("../Model/Qwen-7B-Chat", trust_remote_code=True)
    model = model.half().cuda()                  # .to(device='cuda:0') 
    model = model.eval()
    return tokenizer, model


def build_prompt(history):
    print("build_prompt")
    prompt = "欢迎使用 Qwen-7B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序"
    for query, response in history:
        prompt += f"\n\n用户：{query}"
        prompt += f"\n\nQwen-7B：{response}"
    return prompt


def signal_handler(signal, frame):
    print("signal_handler")
    global stop_stream
    stop_stream = True


def main():
    print("main")
    print("欢迎使用 Qwen-7B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序")

    global stop_stream
    tokenizer, model = get_model()
    history = []
    count = 0
    while True:
        print("main while")
        query = input("\n用户：")
        if query.strip() == "stop":
            break
        if query.strip() == "clear":
            history = []
            os.system(clear_command)
            print("欢迎使用 Qwen-7B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序")
            continue
        
        print("main before chat")
        response, history = model.chat(tokenizer, query, history=history)           # , temperature=0.6
        print("main after chat")

        if stop_stream:
            print("if")
            stop_stream = False
#             break
        else:
            print("else")
            count += 1
            if count % 8 == 0:
                print("else if")
                os.system(clear_command)
                print(build_prompt(history), flush=True)
                signal.signal(signal.SIGINT, signal_handler)
        os.system(clear_command)
        print(build_prompt(history), flush=True)


if __name__ == "__main__":
    main()

**Comment by lrx1213** [comment]
import os
import platform
import signal
import readline

**Comment by lrx1213** [comment]
运行cli_demo.py 官方脚本也出现了同样的问题，输入第一条query后，就会又加载一次模型，导致OOM

**Comment by lrx1213** [comment]
运行cli_demo.py 官方脚本也出现了同样的问题，输入第一条query后，就会又加载一次模型，导致OOM

<img width="1430" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/3e93e254-b334-4ea6-ab6c-f2395ac12ab3">

**Comment by lrx1213** [comment]
运行cli_demo.py 官方脚本也出现了同样的问题，输入第一条query后，就会又加载一次模型，导致OOM

<img width="1438" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/97d062f9-3936-4fd7-88f6-eb898c83f33d">

<img width="1421" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/c9f93cc5-3d9d-4143-818f-3ef2f50ec1bb">

**Comment by lrx1213** [comment]
> 请问是多卡运行的吗？

@jklj077 我之前都是可以正常运行的，自从执行了官网的性能测试脚本后就出现此问题，不知道这个线索对于查找问题是否有帮助？
<img width="739" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/98bc24a0-3a46-4551-af46-42dea3344079">

**Comment by jklj077** [comment]
@lrx123 主要是还没复现出来，运行profile脚本h有报什么错误吗或者有修改环境吗。目前猜测可能是accelerate包的版本不太对，方便提供下accelerate的版本吗~

**Comment by lrx1213** [comment]
> @lrx1213 主要是还没复现出来，运行profile脚本h有报什么错误吗或者有修改环境吗。目前猜测可能是accelerate包的版本不太对，方便提供下accelerate的版本吗~

运行profile脚本的时候就是用的Qwen的运行环境，也是加载了两次模型报错OOM，在此之前运行推理脚本都是可以的

<img width="1436" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/f707953a-af9d-47c2-94f1-2a5e4ee6a2d2">
<img width="1442" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/a310e42a-0780-4e34-95bd-2142a5d0c1ee">


软件版本如下：

<img width="624" alt="image" src="https://github.com/QwenLM/Qwen/assets/19346545/a381454b-cd6c-4109-9433-07d30becef02">

**Comment by lrx1213** [comment]
问题还是没有解决，Qwen用不了了啊

**Comment by jklj077** [comment]
Hi, please try upgrading to Qwen1.5 and check if this issue still exists. For related issues, please also report to Qwen1.5.
