### ISSUE TITLE
关于Qwen的window_attn

### ISSUE THREAD

**Issue by xyfZzz** [QwenLM/Qwen#595]
想请问下readme中提及的window_attn，在模型代码以及config中的哪个位置有体现？我翻了下Qwen-14B的代码以及config文件没有发现跟window_attn相关的地方。

**Comment by jklj077** [comment]
参见<https://github.com/QwenLM/Qwen/issues/422>

**Comment by xyfZzz** [comment]
> 参见#422

好的，谢谢
