### ISSUE TITLE
微调之后加载问题

### ISSUE THREAD

**Issue by laitianan** [QwenLM/Qwen#597]
微调之后加载不了问题，
根据官网代码，model的加载方式为：
![image](https://github.com/QwenLM/Qwen/assets/12150016/e36151cb-2803-4db0-95b0-f65bffbaacd3)
，但是会出现如下错误：
![image](https://github.com/QwenLM/Qwen/assets/12150016/42bc4eb2-f32a-4ef4-8f5e-c639be66e4b5)
，之后添加了响应的参数之后：
![0930442aa3a82d558b062a457657509](https://github.com/QwenLM/Qwen/assets/12150016/e1f43ab7-d343-442e-81ee-a91eeadfaff8)
报一下错误：
![3d071368f1beebbb720a5373e0913c4](https://github.com/QwenLM/Qwen/assets/12150016/fe573fce-8d75-4da9-91dc-75c050282acd)

**Comment by jklj077** [comment]
那个`path_to_adapter`不是形参名，直接替换成路径就行，就比如这样（按你截图中的路径）：
```python
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained(
    "/root/autodl-fs/Qwen/output_qwen",
    device_map="auto",
    trust_remote_code=True
).eval()
```

**Comment by laitianan** [comment]
> 那个`path_to_adapter`不是形参名，直接替换成路径就行，就比如这样（按你截图中的路径）：
> 
> ```python
> from peft import AutoPeftModelForCausalLM
> 
> model = AutoPeftModelForCausalLM.from_pretrained(
>     "/root/autodl-fs/Qwen/output_qwen",
>     device_map="auto",
>     trust_remote_code=True
> ).eval()
> ```

好的，可以了。但是最后发现微调之后的qwen-chat-14B,推理速度要慢很多。不知道如果更改qwen-chat-14b-4bit，会不会快很多呢。

**Comment by jklj077** [comment]
慢很多是跟哪个模型比呢，慢多少呢？如果可以的话，试下合并下模型看看吧，正常应该不会慢很多才多。int4量化的模型本身就比bf16的要快的。

**Comment by WingsLong** [comment]
> 那个`path_to_adapter`不是形参名，直接替换成路径就行，就比如这样（按你截图中的路径）：
> 
> ```python
> from peft import AutoPeftModelForCausalLM
> 
> model = AutoPeftModelForCausalLM.from_pretrained(
>     "/root/autodl-fs/Qwen/output_qwen",
>     device_map="auto",
>     trust_remote_code=True
> ).eval()
> ```

需要把原来的其它文件都复制到下面吗，提示未找到  generation_config.json
