### ISSUE TITLE
💡 [REQUEST] - <是否提供更大size的版本，比如30+B>

### ISSUE THREAD

**Issue by weiminw** [QwenLM/Qwen#598]
### 摘要 | Summary

是否提供更大size的版本，比如30+B

### 基本示例 | Basic Example

是否提供更大size的版本，比如30+B

### 缺陷 | Drawbacks

是否提供更大size的版本，比如30+B

**Comment by jklj077** [comment]
![image](https://github.com/QwenLM/Qwen/assets/17811943/0e2fd78d-f9b9-43bd-9c18-f15513b2422e)

更大的应该会有的，不过更大的是72B的，也算30+B?

**Comment by weiminw** [comment]
> ![image](https://user-images.githubusercontent.com/17811943/281404366-0e2fd78d-f9b9-43bd-9c18-f15513b2422e.png)
> 
> 更大的应该会有的，不过更大的是72B的，也算30+B?
感谢回复, 大是大, 但是72B 就算量化了也需要40G的机器才能跑.
