### ISSUE TITLE
可以训练图像吗？

### ISSUE THREAD

**Issue by CQxiaocaimi** [QwenLM/Qwen#599]
我想训练自己的图像数据集，也就是说想在多轮对话中插入图片，然后让它修改图像输出另外风格的图像。我不太清楚应该怎么设置这样的数据集格式。

**Comment by jklj077** [comment]
本项目是纯文本模型哈，图文模型请见[Qwen-VL](https://github.com/QwenLM/Qwen-VL)项目，不过应该也尚未支持输出图像。

**Comment by CQxiaocaimi** [comment]
> 本项目是纯文本模型哈，图文模型请见[Qwen-VL](https://github.com/QwenLM/Qwen-VL)项目，不过应该也尚未支持输出图像。

 我看介绍说可以调用通义万相，但是我没找到通义万相。

**Comment by jklj077** [comment]
> 我看介绍说可以调用通义万相，但是我没找到通义万相。

请问可以提供下介绍的来源吗？

**Comment by CQxiaocaimi** [comment]
> > 我看介绍说可以调用通义万相，但是我没找到通义万相。
> 
> 请问可以提供下介绍的来源吗？

https://github.com/QwenLM/Qwen/blob/main/examples/react_prompt.md

**Comment by jklj077** [comment]
> 本文档主要基本的原理概念介绍，并在文末附上了一些具体实现相关的 FAQ，但不含被调用插件的实际实现。

如果是指ReAct的相关实现，如该文档最开始的说明。生图并非Qwen完成的，而是调用插件/工具实现的。如果您需要调用通义万相，dashscope提供了API服务，请参阅文档<https://help.aliyun.com/zh/dashscope/developer-reference/api-details-9>。

**Comment by CQxiaocaimi** [comment]
> > 本文档主要基本的原理概念介绍，并在文末附上了一些具体实现相关的 FAQ，但不含被调用插件的实际实现。
> 
> 如果是指ReAct的相关实现，如该文档最开始的说明。生图并非Qwen完成的，而是调用插件/工具实现的（本项目无法训练图像）。如果您需要调用通义万相，dashscope提供了API服务，请参阅文档https://help.aliyun.com/zh/dashscope/developer-reference/api-details-9。

我知道这些，但怎么训练图像。。。。。。。我想训练自己的图像数据集

**Comment by jklj077** [comment]
> > > 本文档主要基本的原理概念介绍，并在文末附上了一些具体实现相关的 FAQ，但不含被调用插件的实际实现。
> > 
> > 
> > 如果是指ReAct的相关实现，如该文档最开始的说明。生图并非Qwen完成的，而是调用插件/工具实现的（本项目无法训练图像）。如果您需要调用通义万相，dashscope提供了API服务，请参阅文档[https://help.aliyun.com/zh/dashscope/developer-reference/api-details-9。](https://help.aliyun.com/zh/dashscope/developer-reference/api-details-9%E3%80%82)
> 
> 我知道这些，但怎么训练图像。。。。。。。我想训练自己的图像数据集


最开始就跟您讲了，本项目是纯文本模型，不支持训练图像。
