### ISSUE TITLE
[BUG] qwen-14b-chat训练跑不起来

### ISSUE THREAD

**Issue by lyj157175** [QwenLM/Qwen#600]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/49610133/869be9fc-1050-4377-ba5b-19c5419060a9)

4卡运行finetune_lora_ds.sh脚本，到这里就一直卡住了，不往下继续训练是为什么

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
还是请先提供下运行环境中的各项信息哈。另外请看下“卡住”的时候，GPU的Util情况；还有用了多少条数据做lora微调。

**Comment by frankang** [comment]
尝试在运行命令前执行
`export NCCL_P2P_DISABLE=1`

**Comment by jklj077** [comment]
设置NCCL_P2P_DISABLE=1可能会导致多卡训练时效率下降，如果设置改变量可以绕过该问题，建议进一步DEBUG环境配置包括硬件配置，以实现最佳性能，[参考链接](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-direct)。
