### ISSUE TITLE
为何model.generate和model.chat生成效果不一样?

### ISSUE THREAD

**Issue by yingxiaolu** [QwenLM/Qwen#604]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我想用model.generate生成回复, 这样能够用top k等各类参数调整行为, 但是发现generate生成不会自己停下来, 最后给了一大段无用的回答. 但是chat的生成就很好. 不理解为什么这样

### 复现方法 | Steps To Reproduce

**chat 方法:**
```
from transformers import AutoTokenizer, AutoModelForCausalLM
# Note: The default behavior now has injection attack prevention off.
modelpath=r'/home/recall/models/QwenQwen-14B-Chat-Int8'
tokenizer = AutoTokenizer.from_pretrained(modelpath, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    modelpath,
    device_map="auto",
    trust_remote_code=True
).eval()
print(model.chat(tokenizer, '你好', history=None)[0])
```
**chat结果:**
你好！很高兴能为你提供帮助。有什么我能为你做的吗？

**generate方法:**
```
from transformers import AutoTokenizer, AutoModelForCausalLM
# Note: The default behavior now has injection attack prevention off.
modelpath=r'/home/recall/models/QwenQwen-14B-Chat-Int8'
tokenizer = AutoTokenizer.from_pretrained(modelpath, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    modelpath,
    device_map="auto",
    trust_remote_code=True
).eval()
def invoke4(model,tokenizer,input):
    input_ids = tokenizer([input], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda') 
    generate_input = {
    "input_ids":input_ids,
    # "max_length":4000,
    "do_sample":False,
    # 'top_k':1,
    'top_p':0.01,
    "temperature":0.01,
    # "num_beams":1,
    # "early_stopping":True,
    # "repetition_penalty":1.3,
    }
    generate_ids  = model.generate(**generate_input)
    content = tokenizer.decode(generate_ids[0])
    return content
print(invoke4(model,tokenizer,'你好'))
```
**generate结果:**
你好，我是一名大学生。寒假期间在一家快餐店工作。因为一些原因，我只工作了十天。我和老板口头约定工资1200元一天，但是当我离开的时候，他告诉我按照每天80元的小时工计算。他在招聘启事上说每小时10元

劳动者和用人单位建立劳动关系，劳动者年满16周岁，劳动者工作四天半，劳动者依法和用人单位解除劳动关系的，用人单位应当依法支付劳动者的合法工资，劳动关系双方依法解除或终止劳动合同时，用人单位应在解除或终止劳动合同时一次付清劳动者工资。　　《工资支付暂行条例》　　九条劳动关系双方依法解除或终止劳动合同时，用人单位应在解除或终止劳动合同时一次付清劳动者工资。　　第十八条各级劳动行政部门有权监察用人单位工资支付的情况。用人单位有下列侵害劳动者合法权益行为的，由劳动行政部门责令其支付劳动者工资和经济��偿，并可责令其支付赔偿金：　　（一）克扣或者无故拖欠劳动者工资的；　　（二）拒不支付劳动者延长工作时间工资的；　　（三）低于当地最低工资标准支付劳动者工资的。　　经济补偿和赔偿金的标准，按国家有关规定执行。　　第十九条劳动者与用人单位因工资支付发生劳动争议的，当事人可依法向劳动争议仲裁机关申请仲裁。对仲裁裁决不服的，可以向人民法院提起诉讼。　　《劳动合同法》　　第七十七条　劳动者合法权益受到侵害的，有权要求有关部门依法处理，或者依法申请仲裁、提起诉讼。　　第七十八条　工会依法维护劳动者的合法权益，对用人单位履行劳动合同、集体合同的情况进行监督。用人单位违反劳动法律、法规和劳动合同、集体合同的，工会有权提出意见或者要求纠正；劳动者申请仲裁、提起诉讼的，工会依法给予支持和帮助。　　第八十五条　用人单位有下列情形之一的，由劳动行政部门责令限期支付劳动报酬、加班费或者经济补偿；劳动报酬低于当地最低工资标准的，应当支付其差额部分；逾期不支付的，责令用人单位按应付金额百分之五十以上百分之一百以下的标准向劳动者加付赔偿金：　　　（一）未按照劳动合同的约定或者国家规定及时足额支付劳动者劳动报酬的；　　　（二）低于当地最低工资标准支付劳动者工资的；　　（三）安排加班不支付加班费

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
> 为何model.generate和model.chat生成效果不一样?不理解为什么这样

因为得按找我们的说明来用呀，两个干的本来也不是同一个事情的。

具体解释：generate接口的功能只是续写；chat接口是对话，有特定的格式。而且chat接口也是可以调整generation相关参数的，修改`model.generation_config`就可以。

**Comment by yingxiaolu** [comment]
> > 为何model.generate和model.chat生成效果不一样?不理解为什么这样
> 
> 因为得按找我们的说明来用呀，两个干的本来也不是同一个事情的。
> 
> 具体解释：generate接口的功能只是续写；chat接口是对话，有特定的格式。而且chat接口也是可以调整generation相关参数的，修改`model.generation_config`就可以。

chat是怎么实现对话的, 我看chat里也是调用的generate函数, 理论上调整generate也可以实现chat的功能?

**Comment by jklj077** [comment]
> 理论上调整generate也可以实现chat的功能?

是的，相当于再实现一遍chat里的逻辑，就可以了。
README里的Batch Inference部分其实就是在用generate来实现chat，有相应的预处理、后处理。

**Comment by yingxiaolu** [comment]
> > 理论上调整generate也可以实现chat的功能?
> 
> 是的，相当于再实现一遍chat里的逻辑，就可以了。 README里的Batch Inference部分其实就是在用generate来实现chat，有相应的预处理、后处理。

好的, 谢谢大佬了

**Comment by chaochaono2** [comment]
hi @jklj077 , 请问目前model.chat 支持流式输出吗？model.generate 生成的结果感觉不如model.chat。目前能有一些关于流式生成结果的介绍吗？

**Comment by wangdach** [comment]
> > 理论上调整generate也可以实现chat的功能?
> 
> 是的，相当于再实现一遍chat里的逻辑，就可以了。 README里的Batch Inference部分其实就是在用generate来实现chat，有相应的预处理、后处理。

请问下，用generate来实现chat部分代码在哪里。

**Comment by Shinning-Zhou** [comment]
I have set "model.generation_config = GenerationConfig.from_pretrained(model_name, trust_remote_code=True)", but it still act  poorly, how can I set config to make it look like chat?
