### ISSUE TITLE
关于评测结果的疑问

### ISSUE THREAD

**Issue by frankxyy** [QwenLM/Qwen#607]
<img width="895" alt="image" src="https://github.com/QwenLM/Qwen/assets/6971044/3c56d882-9c9c-4b1b-985d-7cc7b27ecae7">

<img width="672" alt="image" src="https://github.com/QwenLM/Qwen/assets/6971044/c8f688b6-8a13-44d3-a18a-aee75435148f">

你好，项目主页里我看到两个评测。但感觉有结果不一致的情况，可能是我理解的原因，还望指教。比如对于C-EVAL这个数据集，第一张图里Qwen-14B 得分是72.1，而第二张图Qwen-14B(bf16)得分是69.8。

还有一个疑问是，我看第一张图里C-EVAL下面写着5-shot。但C-EVAL不是都是选择题吗，我理解应该都是0-shot？

**Comment by hzhwcmhf** [comment]
你好，第一张图是base model，第二张图是chat model。
base model用的是5-shot，chat model用的zero-shot。

**Comment by frankxyy** [comment]
@hzhwcmhf 了解了，谢谢！还想问下，chat model在评测时，模型启用的seq_length(session_length)是多大？

**Comment by hzhwcmhf** [comment]
使用的是默认参数（8192）。评测代码可以参考本项目下eval/eval_chat_*.py
