### ISSUE TITLE
[BUG] Lora finetune base model (not chat) with wte, lm_head layer require_grad=False, the performance drop a lot

### ISSUE THREAD

**Issue by luyunan0404** [QwenLM/Qwen#608]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

基于Qwen14B（非chat版本），我尝试了两种方式：
第一种是除了lora layer以外同时finetune `wte` and `lm_head` layer，就像finetune.py script中一样，效果不错。
第二种为了和其他模型进行公平比较，把这两层的parameter frozen了，结果performance下降很大。我的finetune data中没有new token，完全是英文，但是出来的结果中有英文，有泰文，有中文。结果非常差，同时loss也降不下去。尝试了lr=2e-6, 1e-4, 3e-4, lora的parameter也按照finetune.py script进行设置。
请问`wte` and `lm_head` layer在Qwen base model里面是randomly initialized的吗？如果不是，第二种方法performance的原因有可能是什么？有什么解决办法？

### 期望行为 | Expected Behavior

请问`wte` and `lm_head` layer在Qwen base model里面是randomly initialized的吗？如果不是，第二种方法performance的原因有可能是什么？有什么解决办法？

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04
- Python: 3.8
- Transformers: 4.30.2
- PyTorch: 2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by jklj077** [comment]
> 请问wte and lm_head layer在Qwen base model里面是randomly initialized的吗？

不是的，是学习过的（特殊/控制token除外，特殊token里只有`<|endoftext|>`是学习过的，其它相当于都是随机初始化的）。

> 如果不是，第二种方法performance的原因有可能是什么？有什么解决办法？

这个因为我们提供的finetune脚本都是面向chat的。即便您的数据中没有新token，但是我们用的chat格式里的`<|im_start|>`和`<|im_end|>`对于非chat模型一定是新token，必需要训练的。不然这两个token未经过学习的话，embedding相当于是randomly initilized的，用我们的chat接口来做inference会出现未预期的问题。

替代方式的话，可以用自然语言表达（非特殊token标记）的对话格式，这样有可能可以不微调wte和lm_head，但需要您编写数据处理、微调、推理等相关配套代码。
