### ISSUE TITLE
[BUG] 运行Qwen-7B-Chat-Int4模型 一会就直接重启了

### ISSUE THREAD

**Issue by wangchao1980** [QwenLM/Qwen#609]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行Qwen-7B-Chat-Int4模型，我的显存10G，运行一会，我的电脑就重启了，也返回不了结果，是我上传了一个表结构，测试生成sql

Fri Nov 10 07:58:48 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA P102-100                 On | 00000000:01:00.0 Off |                  N/A |
| 77%   26C    P8               11W / 225W|      0MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

CREATE TABLE `风机` (
  `编号` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `产品型号` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `额定功率` int DEFAULT NULL,
  `设计空气密度` decimal(10,3) DEFAULT NULL,
  `切入速度` decimal(10,3) DEFAULT NULL,
  `额定风速` decimal(10,3) DEFAULT NULL,
  `切出速度` decimal(10,3) DEFAULT NULL,
  `生存风速` decimal(10,3) DEFAULT NULL,
  `风机等级` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `系统寿命` int DEFAULT NULL,
  `安全环境温度` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `运行环境温度` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `风轮直径` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `转速范围` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `额定转速` decimal(10,3) DEFAULT NULL,
  `轮毂高度` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `厂商` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `国家` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `发布日期` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

### 期望行为 | Expected Behavior

正常返回sql，别死机和重启

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您好，请提供下各个软件的版本（OS, Python, Transformres, PyTorch, CUDA, 因为您用的量化模型还有AutoGPTQ版本）。另外，我们发现您在使用P102-100这款显卡，也请看下运行过程中显存和内存的占用。

**Comment by wangchao1980** [comment]
OS: Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021
python: Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
PyTorch: 2.1.0+cu121
Transformres: 4.32.0
CUDA: Build cuda_11.3.r11.3/compiler.29920130_0

量化模型：
https://modelscope.cn/models/qwen/Qwen-7B-Chat-Int4/files

显存：
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98.01              Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA P102-100                On  | 00000000:01:00.0 Off |                  N/A |
| 77%   29C    P8              11W / 225W |   7099MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A         8      C   /python3.10                               N/A      |
+---------------------------------------------------------------------------------------+

内存：
top - 04:46:28 up 11 min,  0 users,  load average: 0.09, 0.33, 0.27
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.4 us,  0.3 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  38408.5 total,  26551.6 free,   4541.8 used,   7315.2 buff/cache
MiB Swap:  10240.0 total,  10240.0 free,      0.0 used.  33354.5 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                               
    8 root      20   0   68.2g   3.6g 509916 S   0.3   9.7   0:21.01 python                                                                                                                                                                
    1 root      20   0    2888    928    836 S   0.0   0.0   0:00.03 sh                                                                                                                                                                    
    7 root      20   0    4156   3088   2832 S   0.0   0.0   0:00.00 entrypoint.sh                                                                                                                                                         
    9 root      20   0    4420   3440   2848 S   0.0   0.0   0:00.04 bash                                                                                                                                                                  
   39 root      20   0    7084   3216   2660 R   0.0   0.0   0:00.00 top

**Comment by wangchao1980** [comment]
我用的https://modelscope.cn/models/qwen/Qwen-7B-Chat-Int4/files 量化好的模型
python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c /workspace/models/Qwen-7B-Chat-Int4
输入以下表结构以后，很快就重启电脑了
CREATE TABLE 风机 (
编号 varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
产品型号 varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
额定功率 int DEFAULT NULL,
设计空气密度 decimal(10,3) DEFAULT NULL,
切入速度 decimal(10,3) DEFAULT NULL,
额定风速 decimal(10,3) DEFAULT NULL,
切出速度 decimal(10,3) DEFAULT NULL,
生存风速 decimal(10,3) DEFAULT NULL,
风机等级 varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
系统寿命 int DEFAULT NULL,
安全环境温度 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
运行环境温度 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
风轮直径 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
转速范围 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
额定转速 decimal(10,3) DEFAULT NULL,
轮毂高度 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
厂商 varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
国家 varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
发布日期 date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

**Comment by jklj077** [comment]
您好，WSLg这类的环境我们没办法测试哈，以下是一些可能的因素以及可以排查的点，供参考。
- 排除子系统里的软件依赖问题：transforemrs<4.35.0 (optimum<1.14.0) autogptq<0.5.0 pytorch=2.0.1 且 cuda 版本要匹配(11.7)，设置好参数disable_exllama=True (exllama不支持这么老的硬件)。
- 因为您报告的现象是直接重启(hard reboot，无蓝屏之类的)，内存/显存占用也没有发现异常，建议看下系统事件查看器中是否有相关错误线索。
- 另外Pascal架构对fp16的支持不是很好，不能排除硬件不支持AutoGPTQ量化模型的可能性。

**Comment by wangchao1980** [comment]
谢谢，是不是显存爆了呢？

**Comment by wangchao1980** [comment]
我设置参数disable_exllama=True了
模型启动显存就用了7099，我在输入长的表结构，显存就增加了，过一会就重启了

**Comment by jklj077** [comment]
这个表tokenize后不是很长，不到400 token的样子（这里有个在线的tokenizer版本<https://dashscope.console.aliyun.com/tokenizer>）。

按README中给出的的7B-Int4占用的话，单输入部分，显存似乎是充足的。如果您观察到显存增加到快不够了，那也有可能是显存OOM了。由于我们没有WSLg的环境，也不太能确定这个OOM行为是什么（如果OOM会重启的话，感觉也不是很合理的行为哈）。

一般情况下，Windows无任何提示（没各种颜色的屏，比如蓝屏）重启，建议首先排除硬件问题，比如电源是否充足、PCIE物理连接是否稳定、设备是否过热等。仅供参考哈。

**Comment by lpy86786** [comment]
@wangchao1980 可以试着先烤一下机，CPU、内存、GPU等，排除下硬件问题
