### ISSUE TITLE
batch 推理找不到  qwen_generation_utils

### ISSUE THREAD

**Issue by aleien95** [QwenLM/Qwen#615]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

batch推理找不到文件
![image](https://github.com/QwenLM/Qwen/assets/47136804/e8a34f72-446d-47c0-9ec6-e7c7c0ffb737)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您这个batch_predict.py需要放到跟模型文件同一个文件夹下面，在那个文件夹中运行

**Comment by aleien95** [comment]
> 您这个batch_predict.py需要放到跟模型文件同一个文件夹下面，在那个文件夹中运行

多谢，我试下！
