### ISSUE TITLE
如果我想训练自己的数据，某一行业的就够了，数据量几十万，能不能训练出一个比7B更小的模型出来？

### ISSUE THREAD

**Issue by LMR2018** [QwenLM/Qwen#616]
如果我想训练自己的数据，某一行业的就够了，数据量几十万，能不能训练出一个比7B更小的模型出来？

**Comment by jklj077** [comment]
大规模预训练语言模型(LLM)一般是用海量、通用的数据做预训练，然后在特定领域上进行微调/继续预训练，再做下游应用。从头开始预训练的话，比7B小的模型，所需的数据量也会比远比几十万多的。

几十万数据更适合做垂直领域微调（有可能数据量也不足，需要到实际场景评测，领域微调数据期望也是尽可能多），这样出来的模型是跟基模型大小一般一致的，模型不会更小。

**Comment by AI-Study-Han** [comment]
如果是纯文本的话，方便的话可以合作。我这边有通用纯文本数据，想尝试加入专业数据能不能很好的学习进去。但是目前缺乏专业数据，只有指令微调的数据的话就算了。
