### ISSUE TITLE
量化时的校准集选择

### ISSUE THREAD

**Issue by frankxyy** [QwenLM/Qwen#617]
你好，请问下qwen在gptq量化时用的校准集是什么？ 数量用了多少？  校准集的选择对最终效果影响大吗，谢谢！

**Comment by hzhwcmhf** [comment]
@frankxyy 校准集是从我们内部的SFT数据中采样了4000个样本。具体选择方式没有做过太多实验，但基本原则应该是尽量覆盖使用场景。按我的经验，校准集数据少一点应该差距不会太大。
