### ISSUE TITLE
batch推理 报错RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by aleien95** [QwenLM/Qwen#620]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
这个错误怎么解呢？环境是A800

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Matteyes** [comment]
我也碰到这个问题了，请问下解决了吗

**Comment by Matteyes** [comment]
我是运行web_demo和cli_demo时，问一个问题就会报错，但自己写一个对话是没问题的，感觉像是什么编码问题？

**Comment by jklj077** [comment]
请参考 <https://github.com/QwenLM/Qwen/issues/153> <https://github.com/QwenLM/Qwen/issues/187> <https://github.com/QwenLM/Qwen/issues/276> <https://github.com/QwenLM/Qwen/issues/358> <https://github.com/QwenLM/Qwen/issues/521>

> 已经有较多相关issue。如果是量化模型，建议不要调整温度，通过topp调确定性。如果是非量化模型，建议还是使用bf16而非fp16，并且调温度也尽量不要调过小，容易有精度溢出的问题，fp16尤其容易出现。

如非此问题，请提供更多的信息（比如运行环境信息、推理时的相关配置、报错时的问题等）以便我们辅助您排查有关问题。

**Comment by xiaolvtongxue-zt** [comment]
> 请参考 #153 #187 #276 #358 #521
> 
> > 已经有较多相关issue。如果是量化模型，建议不要调整温度，通过topp调确定性。如果是非量化模型，建议还是使用bf16而非fp16，并且调温度也尽量不要调过小，容易有精度溢出的问题，fp16尤其容易出现。
> 
> 如非此问题，请提供更多的信息（比如运行环境信息、推理时的相关配置、报错时的问题等）以便我们辅助您排查有关问题。

确实是这样的情况，当我调整temperature时，也会出现同样的错误，
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by Matteyes** [comment]
我是驱动版本的问题，之前那个版本多卡有点问题

**Comment by jklj077** [comment]
> covert the precision of the model into bfloat16

This can be quite confusing and misleading for future users. Please allow me to clarify.

The `torch_dtype` argument in `transformers` affects in which dtype the model is loaded from the checkpoint and the dtype used by default in `torch`. However, `torch_dtype` in `transformers` and the dtype used by `torch` both default to `torch.float32` (you are actually downcasting it).

After loading, Qwen uses the `bf16`, `fp16`, and `fp32` values from the `config.json` file to determine the `dtype` and it will cast the parameters using the `dtype` again (assuming the parameters are loaded in fp32!). This `dtype` also affects the dtype of computation in some critical operations.

In your case, if you're not changing the default `config.json`, the `dtype` perceived by Qwen is fp32, which differs from the actual dtype bf16 you are specifying. The inconsistency may cause unknown behaviour.

In all, for Qwen, please don't change `torch_dtype` in `from_pretrained` (fp32 is safer than bf16 anyway) and use `bf16`, `fp16`, and `fp32` to change the dtype.

P.S.: `load_in_4bit=True` indicates you are using `bitsandbytes` to quantize the model (which means bf16 only applies to layers other than those to be quantized). In addition, `bitsandbytes` generally performs worse than `auto-gptq`.
