### ISSUE TITLE
[BUG] Qwen-14B SFT Fine Tune not outputting Stop Word token?

### ISSUE THREAD

**Issue by lhl** [QwenLM/Qwen#622]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

After using the official `finetune.py` script to create a Qwen-14B fine tune I was able to get output but it does not output the expected stop token. I see in the `finetune.py` pre-process it is appending `im_end = tokenizer.im_end_id` so not sure why the fine tune isn't working.

```
User: 2+2
Assistant: [[33975, 25], [151643]]
答えは4です。ก็ได้
<|extra_4|>
計算では、最初に加算を行います: 2 + 2 = 4.<|extra_127|>
หมู่บ้าน
เบีย
สู้
ชัน
วัฒ
thread '<unnamed>' panicked at 'no entry found for key', src/lib.rs:201:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/ubuntu/train/eval/chat-hf-qwen.py", line 141, in <module>
    chat_with_model()
  File "/home/ubuntu/train/eval/chat-hf-qwen.py", line 122, in chat_with_model
    outputs = model.generate(
              ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/merged-model/modeling_qwen.py", line 1337, in generate
    return super().generate(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/eval/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/eval/lib/python3.11/site-packages/transformers/generation/utils.py", line 1719, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/eval/lib/python3.11/site-packages/transformers/generation/utils.py", line 2848, in sample
    streamer.put(next_tokens.cpu())
  File "/home/ubuntu/mambaforge/envs/eval/lib/python3.11/site-packages/transformers/generation/streamers.py", line 97, in put
    text = self.tokenizer.decode(self.token_cache, **self.decode_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/eval/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3746, in decode
    return self._decode(
           ^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/merged-model/tokenization_qwen.py", line 276, in _decode
    return self.tokenizer.decode(token_ids, errors=errors or self.errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/mambaforge/envs/eval/lib/python3.11/site-packages/tiktoken/core.py", line 254, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: no entry found for key
```

### 期望行为 | Expected Behavior

I'd expect there would be a stop token in the output, unless I'm doing something wrong? There's no other way I can stop it's output and it ends up printing gibberish/bad unicode.

I've looked at the [tokenization_note](https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md) which is super useful but didn't seem to mention my exact problem.

I've seen [other code posted](https://github.com/QwenLM/Qwen/issues/383) and have tried setting `eos_token="<|im_end|>"` and `eos_token="<|endoftext|>"` as well as adjusting padding.

I did a search and found some others had some similar issues (but no resolution):
* https://github.com/QwenLM/Qwen/issues/441
* https://github.com/QwenLM/Qwen/issues/492

### 复现方法 | Steps To Reproduce

I used the official `finetune.py` script (w/ the OOTB `ds_config_zero2.json` to do a QLoRA fine tune on a 16xA100-40 (99cacff Nov 6 code).

The one difference I did was switching from auto-gptq to using BitsAndBytes since auto-gptq was barfing on me and I've had previous good experience w/ bnb qloras:
```
# bnb 
compute_dtype = torch.bfloat16
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type='nf4'
)

# in transformers.AutoModelForCausalLM.from_pretrained()
    load_in_4bit=True,
    quantization_config=bnb_config,
```

The training is fine and I am able to run the model both w/ PEFT and as a merged model. It actually generates good output to my tests, except it does not seem to generate a stop token so gets into trouble.

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04.3 LTS
- Python: Python 3.11.6
- Transformers: 4.32.0
- PyTorch: 2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by jklj077** [comment]
Hi, if I understood correctly, you were doing Q-LoRA on Qwen-14B (not the Chat-Int4 one), and bnb quantized the model in the loading process. 

This is tricky, as explained in the README
> For Q-LoRA, we advise you to load our provided quantized model, e.g., Qwen-7B-Chat-Int4. You SHOULD NOT use the bf16 models. Different from full-parameter finetuning and LoRA, only fp16 is supported for Q-LoRA. For single-GPU training, we have to use deepspeed for mixed-precision training due to our observation of errors caused by torch amp. **Besides, for Q-LoRA, the troubles with the special tokens in LoRA still exist. However, as we only provide the Int4 models for chat models, which means the language model has learned the special tokens of ChatML format, you have no worry about the layers. Note that the layers of the Int4 model should not be trainable, and thus if you introduce special tokens in your training, Q-LoRA might not work.**

1. The finetune.py produces chat models, which relies on special tokens (`<|im_start|>` and `<|im_end|>`).
2. Those special tokens are not known by Qwen-14B, which means they need to be trained.
3. The Q-LoRA code in finetune.py does not train the embedding/ouput layer as it is designed for using chat models as the starting point.
4. The special tokens remained unknown in your fine-tuned model and could not be generated in inference, which means the model could not stop.

If this was the case and you need to use the Qwen-14B checkpoint, you might have to change the finetune.py code and train the embedding layer similar to LoRA. However, we have not tried such setting yet.

**Comment by jklj077** [comment]
> since auto-gptq was barfing on me

May I know what the errors were?

**Comment by lhl** [comment]
Ah I was working on the base model, so that explanation makes sense. 

Btw, looking at the LoRA code, is the documentation for the Qwen architecture just what's in `modeling_qwen.py` or is there a description elsewhere as well (just searched this repo for "c_attn" and didn't see any other mentions).

```
lora_target_modules: List[str] = field(
   default_factory=lambda: ["c_attn", "c_proj", "w1", "w2"]
)
```

For auto-gptq, I'll revisit and followup when my current run is finished, I can file a new bug for that (this might be a version issue, I try to keep all my environments well separated, but had to do some juggling for another project and there might have been some bleed).

**Comment by jklj077** [comment]
> is the documentation for the Qwen architecture just what's in modeling_qwen.py or is there a description elsewhere as well (just searched this repo for "c_attn" and didn't see any other mentions

I would regard the implemenation in modeling_qwen.py as some kind of documentation, because certain details are hard to explain (or to be understood) in natural language.

**Comment by kaishxu** [comment]
> Hi, if I understood correctly, you were doing Q-LoRA on Qwen-14B (not the Chat-Int4 one), and bnb quantized the model in the loading process.
> 
> This is tricky, as explained in the README
> 
> > For Q-LoRA, we advise you to load our provided quantized model, e.g., Qwen-7B-Chat-Int4. You SHOULD NOT use the bf16 models. Different from full-parameter finetuning and LoRA, only fp16 is supported for Q-LoRA. For single-GPU training, we have to use deepspeed for mixed-precision training due to our observation of errors caused by torch amp. **Besides, for Q-LoRA, the troubles with the special tokens in LoRA still exist. However, as we only provide the Int4 models for chat models, which means the language model has learned the special tokens of ChatML format, you have no worry about the layers. Note that the layers of the Int4 model should not be trainable, and thus if you introduce special tokens in your training, Q-LoRA might not work.**
> 
> 1. The finetune.py produces chat models, which relies on special tokens (`<|im_start|>` and `<|im_end|>`).
> 2. Those special tokens are not known by Qwen-14B, which means they need to be trained.
> 3. The Q-LoRA code in finetune.py does not train the embedding/ouput layer as it is designed for using chat models as the starting point.
> 4. The special tokens remained unknown in your fine-tuned model and could not be generated in inference, which means the model could not stop.

so we need to specify the end token as <|im_end|>?

**Comment by jklj077** [comment]
For Q-LoRA, using chat models as the starting points is recommended.
If you need to start from the base models, you need to change the template used by the chat models and conduct inference in a consistent way.

Note for the newer Qwen1.5 models, you could do Q-LoRA starting from the base models as the two special tokens are known by the base models.
