### ISSUE TITLE
[BUG] <执行finetune.py去微调项目遇到ModuleNotFoundError: No module named 'torch._six'>

### ISSUE THREAD

**Issue by wrl1224** [QwenLM/Qwen#624]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

requirements里面的依赖都安装了
finetune.py 需要的deepspeed也安装了，windows适配的版本是 0.3.16
修改好模型和训练数据集等path路径 运行finetune.py
遇到↓
Traceback (most recent call last):
  File "E:\wrl\PythonCode\Qwen\finetune.py", line 12, in <module>
    from deepspeed import zero
  File "E:\wrl\PythonCode\Qwen\venv\lib\site-packages\deepspeed\__init__.py", line 9, in <module>
    from .runtime.engine import DeepSpeedEngine
  File "E:\wrl\PythonCode\Qwen\venv\lib\site-packages\deepspeed\runtime\engine.py", line 18, in <module>
    from deepspeed.runtime.utils import see_memory_usage
  File "E:\wrl\PythonCode\Qwen\venv\lib\site-packages\deepspeed\runtime\utils.py", line 18, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

### 期望行为 | Expected Behavior

这个ModuleNotFoundError: No module named 'torch._six'是torch2.0.0之后就有的问题，希望能给出解决这个问题的方案

### 复现方法 | Steps To Reproduce

finetune.py 需要的deepspeed依赖包也安装了，windows适配的版本是 0.3.16
根据运行环境配置之后运行finetune.py

### 运行环境 | Environment

```Markdown
- OS:win10
- Python:3.10
- Transformers:4.32.0
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jklj077** [comment]
您好，请参考 https://github.com/microsoft/DeepSpeed/issues/2845 看是否能解决您的问题
