### ISSUE TITLE
about tools-use

### ISSUE THREAD

**Issue by DryPilgrim** [QwenLM/Qwen#626]
//cn
1. 论文中的 **in-house Chinese benchmark**有介绍/开源吗?
2. 训练数据中关于tools的部分是怎么构造的？
3. 评估方法中关于tools的部分是怎么设计的？

//en
1.  what is **in-house Chinese benchmark** in the paper?
2. How is the part about tools in the training data constructed?
3. How is the tools part of the evaluation method designed?

**Comment by JianxinMa** [comment]
1 & 3: Yes, it is openly released. See https://github.com/QwenLM/Qwen/blob/main/eval/EVALUATION.md and https://github.com/QwenLM/Qwen/blob/main/eval/evaluate_plugin.py


2: See the tech report ( https://arxiv.org/abs/2309.16609 ) or https://github.com/QwenLM/Qwen/issues/402 https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py

**Comment by DryPilgrim** [comment]
> 1 & 3: Yes, it is openly released. See https://github.com/QwenLM/Qwen/blob/main/eval/EVALUATION.md and https://github.com/QwenLM/Qwen/blob/main/eval/evaluate_plugin.py
> 
> 2: See the tech report ( https://arxiv.org/abs/2309.16609 ) or #402 https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py

1  in-house Chinese benchmark 就是 https://qianwen-res.oss-cn-beijing.aliyuncs.com/opensource_data/exam_plugin_v1/exam_plugin_v1_react_positive.jsonl 这个吗?
2 tech report只说了“ a benchmark for evaluating QWEN” ，并没有说训练数据中关于tools的部分是怎么构造的？（格式，数据来源，构造过程，构造方法）
3 tools训练数据怎么和普通的数据进行融合的？

**Comment by JianxinMa** [comment]
1. Yes. The benchmark includes these two files: https://qianwen-res.oss-cn-beijing.aliyuncs.com/opensource_data/exam_plugin_v1/exam_plugin_v1_react_positive.jsonl and https://qianwen-res.oss-cn-beijing.aliyuncs.com/opensource_data/exam_plugin_v1/exam_plugin_v1_react_negative.jsonl

2. See https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py for the data format. The tech report does mention how the data were collected, as follows:

```
To enhance QWEN’s capabilities as an agent or copilot, we employ the self-instruct (Wang et al.,
2023c) strategy for supervised fine-tuning (SFT). Specifically, we utilize the in-context learning
capability of QWEN for self-instruction. By providing a few examples, we can prompt QWEN to
generate more relevant queries and generate outputs that follow a specific format, such as ReAct.
We then apply rules and involve human annotators to filter out any noisy samples. Afterwards, the
samples are incorporated into QWEN’s training data, resulting in an updated version of QWEN that is
more dependable for self-instruction. We iterate through this process multiple times until we gather
an ample number of samples that possess both exceptional quality and a wide range of diversity. As a
result, our final collection consists of around 2000 high-quality samples.

During the fine-tuning process, we mix these high-quality samples with all the other general-purpose
SFT samples, rather than introducing an additional training stage. By doing so, we are able to retain
essential general-purpose capabilities that are also pertinent for constructing agent applications.
```

3. See above.

**Comment by BlueBlueFF** [comment]
> 1. Yes. The benchmark includes these two files: https://qianwen-res.oss-cn-beijing.aliyuncs.com/opensource_data/exam_plugin_v1/exam_plugin_v1_react_positive.jsonl and https://qianwen-res.oss-cn-beijing.aliyuncs.com/opensource_data/exam_plugin_v1/exam_plugin_v1_react_negative.jsonl
> 2. See https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py for the data format. The tech report does mention how the data were collected, as follows:
> 
> ```
> To enhance QWEN’s capabilities as an agent or copilot, we employ the self-instruct (Wang et al.,
> 2023c) strategy for supervised fine-tuning (SFT). Specifically, we utilize the in-context learning
> capability of QWEN for self-instruction. By providing a few examples, we can prompt QWEN to
> generate more relevant queries and generate outputs that follow a specific format, such as ReAct.
> We then apply rules and involve human annotators to filter out any noisy samples. Afterwards, the
> samples are incorporated into QWEN’s training data, resulting in an updated version of QWEN that is
> more dependable for self-instruction. We iterate through this process multiple times until we gather
> an ample number of samples that possess both exceptional quality and a wide range of diversity. As a
> result, our final collection consists of around 2000 high-quality samples.
> 
> During the fine-tuning process, we mix these high-quality samples with all the other general-purpose
> SFT samples, rather than introducing an additional training stage. By doing so, we are able to retain
> essential general-purpose capabilities that are also pertinent for constructing agent applications.
> ```
> 
> 3. See above.

这里有个问题想请教下，Tech Report提到 构造的Tool格式的SFT数据是和普通的SFT混合训练的，
