### ISSUE TITLE
Regarding tool-use evaluation

### ISSUE THREAD

**Issue by DryPilgrim** [QwenLM/Qwen#627]
关于tool-use的评估：
论文中的指标是 **Tool Selection (Acc.↑) Tool Input (Rouge-L↑) False Positive Error (%)↓**，但是代码中评估是是**--eval-react-positive --eval-react-negative --eval-hfagent**，为什么不一样呀？是怎么计算的呢？

//en
Regarding tool-use evaluation:
The metrics in the paper are **Tool Selection (Acc.↑) Tool Input (Rouge-L↑) False Positive Error (%)↓**, but the evaluation in the code is is ** --eval-react-positive --eval-react-negative -- eval-hfagent**, why is it different? How is it calculated?

**Comment by JianxinMa** [comment]
--eval-react-positive computes Tool Selection (Acc.↑) and Tool Input (Rouge-L↑)

--eval-react-negative False Positive Error (%)
