### ISSUE TITLE
使用web_demo.py应该怎样退出，Ctrl+c退出显卡会出现error，显示GPU is lost

### ISSUE THREAD

**Issue by 1424153694** [QwenLM/Qwen#629]
使用web_demo.py应该怎样退出，Ctrl+c退出显卡会出现error，显示GPU is lost

**Comment by jklj077** [comment]
GPU is lost是NVIDIA显卡的经典问题，常见原因可能包括硬件故障、驱动缺陷等。请尝试更新显卡驱动，保证显卡供电充足、连接稳固，或寻求售后支持。
