### ISSUE TITLE
Qwen-7B模型微调后怎么使用[BUG] <title>

### ISSUE THREAD

**Issue by Sanens** [QwenLM/Qwen#631]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen-7B模型微调后怎么使用呢？也是跟Qwen-7B-chat模型一样的用法吗？
![image](https://github.com/QwenLM/Qwen/assets/61749018/1d3e5578-7e90-4296-aab7-3c0e94bca9db)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
用本repo中的finetune脚本的话，产出的是chat模型，用法是跟Qwen-7B-chat模型一样的。

**Comment by jklj077** [comment]
@zhouenxian 

LoRA/Q-LoRA微调后存储的文件主要是adapter相关的，虽然缺generation_config.json，但AutoPeftModelForCausalLM会自动从记录的基模型目录那里加载文件。

直接用GenerationConfig初始化的话，没有这个功能，会找不到文件。可以把generation_config.json复制过来（或者把from_pretrained路径改成基模型的路径）。微调之后应该是可以使用这种方法（指用GeneratioConfig）指定模型生成参数的。

P.S.: 独立问题请开新issue哈。
