### ISSUE TITLE
为什么我用多机多卡微调14b-16k,依然显存不够，感觉zero-3没有生效，[BUG] <title>

### ISSUE THREAD

**Issue by Kk1984up** [QwenLM/Qwen#634]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用4台A800-80G*8的多机多卡，微调14b-16k模型，使用的zero-3，依然显存不够，这个很奇怪，感觉zero-3没生效啊

### 期望行为 | Expected Behavior

希望能够在32 卡 A800-80g资源，微调14b-16k模型

### 复现方法 | Steps To Reproduce

1，使用了最新代码，
2，deepspeed --hostfile=./hostfile --model_max_lenght=1638

### 运行环境 | Environment

```Markdown
- OS:linux
- Python:3.10
- Transformers:4.35
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

能不能出一个多机多卡的脚本，

**Comment by grygg** [comment]
同求，多机多卡脚本
