### ISSUE TITLE
使用vllm进行部署，推理过早结束，相比from_pretrained 加载答案短很多

### ISSUE THREAD

**Issue by xiaobing2016** [QwenLM/Qwen#636]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用官方vllm多卡部署方法，（model_path改成了自己的地址）

python -m fastchat.serve.controller
python -m fastchat.serve.vllm_worker --model-path $model_path --trust-remote-code --tensor-parallel-size 4
python -m fastchat.serve.openai_api_server --host localhost --port 8000

启动后进行推理，相同的输入，推理后得到的得到很短，相比from_pretrained 答案很短（输出的结果到和直接加载的前面文本一致）

### 期望行为 | Expected Behavior

使用vllm与from_pretrained  方法加载，对于同样的请求，输出结果一致

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.9.16
- Transformers:4.34.0
- PyTorch: 2.0.1
- CUDA 11.7:
- vllm 0.2.1.post1
- fschat 0.2.32
-openai 0.27.8
```

**Comment by xiaobing2016** [comment]
设置了 temperature=0.95, 能够输出长结果，但结果不稳定。 
4次中有一次和from_pretrained加载时相同的，其他都不相同

**Comment by zhuxiaobin** [comment]
被截断么？如果是14B，14B的stop_token_ids和7B的不一样，FastChat 里面fastchat/conversation.py 的register_conv_template(
    Conversation(
        name="qwen-7b-chat",
        system_template="<|im_start|>system\n{system_message}",
        system_message="You are a helpful assistant.",
        roles=("<|im_start|>user", "<|im_start|>assistant"),
        sep_style=SeparatorStyle.CHATML,
        sep="<|im_end|>",
        stop_token_ids=[
            151643,
            151644,
            151645,
        ],  # "<|endoftext|>", "<|im_start|>", "<|im_end|>"
        stop_str="<|endoftext|>",
    )
)
stop_token_ids 是7B的，14B的要改成stop_token_ids=[
            153719,
            153720,
            153721
        ]
