### ISSUE TITLE
请问QWen的tokenizer一个汉字占用多少token，一个英文单词占多少token？

### ISSUE THREAD

**Issue by cgq0816** [QwenLM/Qwen#637]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
tokenizer是基于BPE的，一个汉字/一个英文单词占多少token是不固定的。
tokenizer有[在线的版本](https://dashscope.console.aliyun.com/tokenizer)，可以感受下。

**Comment by ruyun-bai** [comment]
你好啊
