### ISSUE TITLE
用Q-LoRA微调，运行finetune_qlora_single_gpu   没用到GPU和显存，而用了CPU和内存，这对吗？

### ISSUE THREAD

**Issue by fllsoft** [QwenLM/Qwen#639]
用Q-LoRA微调，运行finetune_qlora_single_gpu  。查看资源使用请，没用到GPU和显存，而用了少量CPU和全部物理内存，这正常吗

**Comment by jklj077** [comment]
不正常，各个软件的版本、程序运行输出都提供下吧

**Comment by fllsoft** [comment]
暂时用的阿里云的，

**Comment by fllsoft** [comment]
暂时用的阿里云的免费测试。
CPU 8  
内存32 GiB
GPU 1 型号 NVIDIA V100
dsw-registry-vpc.cn-shanghai.cr.aliyuncs.com/pai/modelscope:1.9.5-pytorch2.0.1tensorflow2.13.0-gpu-py38-cu118-ubuntu20.04
用的模型是qwen/Qwen-14B-Chat-Int4，
测试推理是正常的，GPU有在使用，但是测试微调的时候，GPU和显存并没有用，而物理内存用到满了然后程序就被kill掉了。
推理用Q-LoRA，pip install mpi4py，pip install deepspeed。
执行sh finetune/finetune_qlora_single_gpu.sh，物理内存满了。

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

MODEL="/mnt/workspace/.cache/modelscope/qwen/Qwen-14B-Chat-Int4/" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="$DIR/finetune/data.json"

export CUDA_VISIBLE_DEVICES=0

# Remember to use --fp16 instead of --bf16 due to autogptq
python finetune.py \
  --model_name_or_path $MODEL \
  --data_path $DATA \
  --fp16 True \
  --output_dir output_qwen \
  --num_train_epochs 5 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 1000 \
  --save_total_limit 10 \
  --learning_rate 3e-4 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --report_to "none" \
  --model_max_length 512 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora \
  --q_lora \
  --deepspeed finetune/ds_config_zero2.json

**Comment by fllsoft** [comment]
finetune_qlora_single_gpu.sh脚本参数除了路径，其他都没动

**Comment by 2579356425** [comment]
你好，请问这个问题怎么解决的
