### ISSUE TITLE
[BUG] Qwen-14B-Chat模型，2500多个字符输入，回复速度很慢，要等16-22s不等，如何可以加快回复速度？

### ISSUE THREAD

**Issue by Maxhyl** [QwenLM/Qwen#640]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

tokenizer = AutoTokenizer.from_pretrained("./Qwen/Qwen-14B-Chat/qwen/Qwen-14B-Chat", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("./Qwen/Qwen-14B-Chat/qwen/Qwen-14B-Chat", device_map="cuda:1", trust_remote_code=True, bf16=True).eval()
model.generation_config = GenerationConfig.from_pretrained("./Qwen/Qwen-14B-Chat/qwen/Qwen-14B-Chat", trust_remote_code=True)
response, history = model.chat(tokenizer, inputs, history=history)

### 期望行为 | Expected Behavior

希望能加快模型推理速度

### 复现方法 | Steps To Reproduce

传入一个2500多个字符的中文文本，回复需要等待16-22s，尝试过用history切分成2块，回复速度也是差不多。

### 运行环境 | Environment

```Markdown
- OS:
- Python: 3.10
- Transformers: 4.31.0
- PyTorch:2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):cuda117
```

### 备注 | Anything else?

希望能加快推理速度

**Comment by cgq0816** [comment]
1、使用第三方工具进行加速
https://github.com/vllm-project/vllm
2、使用qwen flash attn或者kv cache量化的方法进行加速
当前该功能目前不支持与flash attn同时开启，如果你开了kv cache量化的同时又开了flash attn（use_flash_attn=True， use_cache_quantization=True, use_cache_kernel=True），会默认将use_flash_attn关闭。

**Comment by wengyuan722** [comment]
咨询一下使用vllm的api,是不是导致不能使用qwen自己的function call功能，是不是只能支持对话

**Comment by cgq0816** [comment]
> 咨询一下使用vllm的api,是不是导致不能使用qwen自己的function call功能，是不是只能支持对话

支持function call功能，vllm只是做加速用的

**Comment by wengyuan722** [comment]
正常应该vllm调用api使用的vllm自己的接口，python openai/api_server.py --host 127.0.0.1 --port 6006 --model /root/autodl-tmp/Qwen-14B-Chat 
如果vllm没有专门对qwen的function做适配，应该是不能跑吧，我也不是很清楚vllm有没有做适配

我看qwen自己的openai_api有做适配
    if functions:
        tools_text = []
        tools_name_text = []
        for func_info in functions:
            name = func_info.get("name", "")
            name_m = func_info.get("name_for_model", name)
            name_h = func_info.get("name_for_human", name)
            desc = func_info.get("description", "")
            desc_m = func_info.get("description_for_model", desc)
            tool = TOOL_DESC.format(
                name_for_model=name_m,
                name_for_human=name_h,
                # Hint: You can add the following format requirements in description:
                #   "Format the arguments as a JSON object."
                #   "Enclose the code within triple backticks (`) at the beginning and end of the code."
                description_for_model=desc_m,
                parameters=json.dumps(func_info["parameters"], ensure_ascii=False),
            )
            tools_text.append(tool)
            tools_name_text.append(name_m)
        tools_text = "\n\n".join(tools_text)
        tools_name_text = ", ".join(tools_name_text)
        system += "\n\n" + REACT_INSTRUCTION.format(
            tools_text=tools_text,
            tools_name_text=tools_name_text,
        )
        system = system.lstrip("\n").rstrip()

    dummy_thought = {
        "en": "\nThought: I now know the final answer.\nFinal answer: ",
        "zh": "\nThought: 我会作答了。\nFinal answer: ",
    }

**Comment by cgq0816** [comment]
> 正常应该vllm调用api使用的vllm自己的接口，python openai/api_server.py --host 127.0.0.1 --port 6006 --model /root/autodl-tmp/Qwen-14B-Chat 如果vllm没有专门对qwen的function做适配，应该是不能跑吧，我也不是很清楚vllm有没有做适配
> 
> 我看qwen自己的openai_api有做适配 if functions: tools_text = [] tools_name_text = [] for func_info in functions: name = func_info.get("name", "") name_m = func_info.get("name_for_model", name) name_h = func_info.get("name_for_human", name) desc = func_info.get("description", "") desc_m = func_info.get("description_for_model", desc) tool = TOOL_DESC.format( name_for_model=name_m, name_for_human=name_h, # Hint: You can add the following format requirements in description: # "Format the arguments as a JSON object." # "Enclose the code within triple backticks (`) at the beginning and end of the code." description_for_model=desc_m, parameters=json.dumps(func_info["parameters"], ensure_ascii=False), ) tools_text.append(tool) tools_name_text.append(name_m) tools_text = "\n\n".join(tools_text) tools_name_text = ", ".join(tools_name_text) system += "\n\n" + REACT_INSTRUCTION.format( tools_text=tools_text, tools_name_text=tools_name_text, ) system = system.lstrip("\n").rstrip()
> 
> ```
> dummy_thought = {
>     "en": "\nThought: I now know the final answer.\nFinal answer: ",
>     "zh": "\nThought: 我会作答了。\nFinal answer: ",
> }
> ```

使用qwen调用工具的prompt的，才能使用function call的功能。

**Comment by zRzRzRzRzRzRzR** [comment]
vllm只是加速的，qwen的Function call 就是langchain的zero react 那套模板，而且召回率挺高的，用vllm不影响Function Call能力

**Comment by fungaegis** [comment]
> vllm只是加速的，qwen的Function call 就是langchain的zero react 那套模板，而且召回率挺高的，用vllm不影响Function Call能力

那我应该如何才能在fastchat-vllm中使用qwen官方提供的function call也就是那个openai-api.py呢?

**Comment by jklj077** [comment]
各位话题跑偏了，我们关注下OP这个问题。

根据README中的profiling结果(A100有flash-attention)，Qwen-14B在半精度时的速度约为32 token/s，16-22s取均值为19s，则长度为608个token，题主2500字符这个速度是大致符合预期的。

如果需要进一步加速，cgq0816的建议很合理，需要专用的框架了，比如vLLM。也有其它框架，比如TensorRT-LLM。
