### ISSUE TITLE
[QUESTION] QWEN7B-CHAT生成的最大Token是8192吗？

### ISSUE THREAD

**Issue by WangxuP** [QwenLM/Qwen#643]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如标题：
QWEN7B-CHAT生成的最大Token是8192吗？
如何进行确认呢？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by zRzRzRzRzRzRzR** [comment]
8K吧， [这里](https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-7b-14b-api-detailes)有写，本地模型应该也是8k
当然 这8k不是输出8k 而是所有的内容加起来，包括历史，提示词的等等
确认的话你直接准备好8k token x （1token 对应的汉字） ，进行多轮对话，看一下模型到多少token的时候会忘记第一次的内容 （这只能测出大概）

**Comment by jklj077** [comment]
Qwen-7B-Chat目前是训练阶段支持8K，通过dynamic_ntk可扩展到32K。
