### ISSUE TITLE
Is there a model named qwen2?

### ISSUE THREAD

**Issue by FlyingDutchman26** [QwenLM/Qwen#644]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

作者您好！想问下你们是否开源了qwen2这样的一个模型？我有听说这个模型，但是没有在仓库中找到

**Comment by zRzRzRzRzRzRzR** [comment]
好像还没开，目前开的还是9.25更新的那版，期待

**Comment by jklj077** [comment]
通义千问2.0的千亿级模型目前DashScope已开放体验，欢迎试用，说明看这里<https://help.aliyun.com/zh/dashscope/developer-reference/api-details>。
另外，近期将开源72B模型，敬请关注。
