### ISSUE TITLE
[BUG] <title>推理性能无法复现，采用官网给定脚本在A100机器测试性能13.0tokens/s

### ISSUE THREAD

**Issue by fushengshi** [QwenLM/Qwen#645]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![8EE9940E-21F9-4268-8348-046DA5921A6A](https://github.com/QwenLM/Qwen/assets/50937788/ca8e19dc-dc51-4b78-90ce-8c71dbaad0a3)

采用官网给定脚本在A100机器测试Qwen-7B性能13.0tokens/s左右，无法复现提供性能数据

### 期望行为 | Expected Behavior

能够复现性能数据或者不要差距太大

### 复现方法 | Steps To Reproduce

直接使用提供脚本，使用bf16，不使用flashAttention，代码如下

```
# -*- coding: utf-8 -*-
# Please pull the latest code to run the profiling.
import time
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
from transformers.trainer_utils import set_seed
from tqdm import tqdm

seed = 1024
max_experiment_times = 1
context_length_per_experiment = 1
generate_length_per_experiment = 2048
# context_length_per_experiment = 1
# generate_length_per_experiment = 8192
# context_length_per_experiment = 2048
# generate_length_per_experiment = 1
use_flash_attn = False
# fp32 without quantization, bf16 without quantization or int4 quantization (updated on 8.28: we have updated the quantization strategy to AutoGPTQ in this script)
quant_type = "bf16" # fp32, bf16 or int4

set_seed(seed)

tokenizer = AutoTokenizer.from_pretrained("/mnt/data/qwen_7b_chat", trust_remote_code=True)

if quant_type == "bf16":
    model = AutoModelForCausalLM.from_pretrained(
        "/mnt/data/qwen_7b_chat",
        device_map="cuda:4",
        trust_remote_code=True, 
        bf16=True, 
        use_flash_attn=use_flash_attn
    ).eval()

# Specify hyperparameters for generation
config = GenerationConfig.from_pretrained("/mnt/data/qwen_7b_chat", trust_remote_code=True)
config.min_length = generate_length_per_experiment + context_length_per_experiment
config.max_new_tokens = generate_length_per_experiment

time_costs = []
context_str = '我' * context_length_per_experiment
max_gpu_memory_cost = 0
for _ in tqdm(range(max_experiment_times)):
    inputs = tokenizer(context_str, return_tensors='pt')
    inputs = inputs.to(model.device)
    t1 = time.time()
    pred = model.generate(**inputs, generation_config=config)
    time_costs.append(time.time() - t1)
    print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
    assert pred.shape[1] == config.min_length
    max_gpu_memory_cost = max(max_gpu_memory_cost, torch.cuda.max_memory_allocated())
    torch.cuda.empty_cache()

print("Average generate speed (tokens/s): {}".format((max_experiment_times * generate_length_per_experiment) / sum(time_costs)))
print(f"GPU Memory cost: {max_gpu_memory_cost / 1024 / 1024 / 1024}GB")
print("Experiment setting: ")
print(f"seed = {seed}")
print(f"max_experiment_times = {max_experiment_times}")
print(f"context_length_per_experiment = {context_length_per_experiment}")
print(f"generate_length_per_experiment = {generate_length_per_experiment}")
print(f"use_flash_attn = {use_flash_attn}")
print(f"quant_type = {quant_type}")
```

测试结果：
![53A22F1A-E762-45E5-AE45-88B4DA12F225](https://github.com/QwenLM/Qwen/assets/50937788/f4f9151d-47ae-40e9-bd73-08cd8e04c50f)

### 运行环境 | Environment

```Markdown
- OS: x86_64
- Python: 3.8.18
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA: 11.7
```

**Comment by logicwong** [comment]
@fushengshi 您好，能够提供一下CPU数量和内存大小吗？

**Comment by fushengshi** [comment]
> @fushengshi 您好，能够提供一下CPU数量和内存大小吗？包括git log，我们看一下你使用的是哪个日期的代码

![image](https://github.com/QwenLM/Qwen/assets/50937788/29cde2e3-fe82-4cc0-9837-e2ac6f48e8a6)
代码直接下载的，11月15号左右的

**Comment by fushengshi** [comment]
另外确认下，不开启flash-attentiion的情况下，batch推理能实现官网描述的性能提升吗（40%），该项也无法复现

**Comment by logicwong** [comment]
> 另外确认下，不开启flash-attentiion的情况下，batch推理能实现官网描述的性能提升吗（40%），该项也无法复现

这个问题请参阅这个回复，https://github.com/QwenLM/Qwen/issues/159#issuecomment-1737108183

**Comment by jklj077** [comment]
@fushengshi 

您好，我们按您提供的脚本执行（除了调整cuda:4为cuda:0），相同的软件环境（transformers==4.32.0），类似的显卡（NVIDIA A100 80GB SXM），未能复现您遇到的问题。

![lQLPJwpjNgcN_I_NAaLNBP6wYqe2H101qxQFUHoMcShLAA_1278_418](https://github.com/QwenLM/Qwen/assets/17811943/13de9e03-e2e6-4644-8aae-6f128b3cd98a)

我们观察您提供的截图，有如下现象：
1. 模型checkpoint似乎加载了两次（与<https://github.com/QwenLM/Qwen/issues/594>类似，但我们也未能复现成功）

如果方便的话，是否可以提供以下内容辅助我们排查：
1. `pip list`的结果，以还原软件环境
2. 模型文件夹中`ls -lh`的结果，以判断代码版本
3. config.json中的内容，以判断是否配置存在不同
