### ISSUE TITLE
Qwen-7B-Chat模型按照Quto-GPTQ示例进行4bit量化，报错：ValueError: Pointer argument (at 2) cannot be accessed from Triton (cpu tensor?)[BUG] <title>

### ISSUE THREAD

**Issue by sunyclj** [QwenLM/Qwen#646]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行到model.quantize(examples)，报错：ValueError: Pointer argument (at 2) cannot be accessed from Triton (cpu tensor?)，请问会是什么原因？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by lonngxiang** [comment]
同报错；内容
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by jklj077** [comment]
您模型可能加载到内存里了，如下方案供参考
1. 强制所有的参数加载到显存中（不要用device_map='auto'，直接指定到'cuda:0'之类的，或者不设置，加载后再转移模型到GPU）
2. 卸载flash-attn

**Comment by lonngxiang** [comment]
> 您模型可能加载到内存里了，如下方案供参考
> 
> 1. 强制所有的参数加载到显存中（不要用device_map='auto'，直接指定到'cuda:0'之类的，或者不设置，加载后再转移模型到GPU）
> 2. 卸载flash-attn

这边测试单卡cuda:0，但因为显卡不够所以放弃了；这能多显张卡运行吗

**Comment by jklj077** [comment]
@lonngxiang 还是要用GPU的，但我们没试过多卡量化。您多卡加载后(device_map='auto')，如果显存足够，应该不会有在内存里的参数（如果有的话，可以打印下model.hf_device_map，看看哪些到内存上了）。

**Comment by sunyclj** [comment]
> quantize_config

按照提供的两种解决方案，我这也是一样的报错，“RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!”

**Comment by sunyclj** [comment]
> model.hf_device_map

加载模型设置device_map="cuda:1"，为什么报错依然是数据在0卡和cpu上呢？“RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!”

**Comment by sunyclj** [comment]
> 您模型可能加载到内存里了，如下方案供参考
> 
> 1. 强制所有的参数加载到显存中（不要用device_map='auto'，直接指定到'cuda:0'之类的，或者不设置，加载后再转移模型到GPU）
> 2. 卸载flash-attn


model.hf_device_map

加载模型设置device_map="cuda:1"，为什么报错依然是在0卡和cpu上呢？“RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!”

**Comment by MiyazonoKaori** [comment]
修改modeling_qwen.py

def apply_rotary_pos_emb(t, freqs):
    cos, sin = freqs
    cos = cos.to(t.device)
    sin = sin.to(t.device)
    if apply_rotary_emb_func is not None and t.is_cuda:
        t_ = t.float()
        cos = cos.squeeze(0).squeeze(1)[:, : cos.shape[-1] // 2]
        sin = sin.squeeze(0).squeeze(1)[:, : sin.shape[-1] // 2]
        output = apply_rotary_emb_func(t_, cos, sin).type_as(t)
        return output
    else:
        rot_dim = freqs[0].shape[-1]
        cos, sin = freqs
        cos = cos.to(t.device)
        sin = sin.to(t.device)
        t_, t_pass_ = t[..., :rot_dim], t[..., rot_dim:]
        t_ = t_.float()
        t_pass_ = t_pass_.float()
        t_ = (t_ * cos) + (_rotate_half(t_) * sin)
        return torch.cat((t_, t_pass_), dim=-1).type_as(t)

**Comment by MiyazonoKaori** [comment]
修改modeling_qwen.py
`
def apply_rotary_pos_emb(t, freqs):
    cos, sin = freqs
    cos = cos.to(t.device)
    sin = sin.to(t.device)
    if apply_rotary_emb_func is not None and t.is_cuda:
        t_ = t.float()
        cos = cos.squeeze(0).squeeze(1)[:, : cos.shape[-1] // 2]
        sin = sin.squeeze(0).squeeze(1)[:, : sin.shape[-1] // 2]
        output = apply_rotary_emb_func(t_, cos, sin).type_as(t)
        return output
    else:
        rot_dim = freqs[0].shape[-1]
        cos, sin = freqs
        cos = cos.to(t.device)
        sin = sin.to(t.device)
        t_, t_pass_ = t[..., :rot_dim], t[..., rot_dim:]
        t_ = t_.float()
        t_pass_ = t_pass_.float()
        t_ = (t_ * cos) + (_rotate_half(t_) * sin)
        return torch.cat((t_, t_pass_), dim=-1).type_as(t)

`

**Comment by WingsLong** [comment]
一样的问题，自己量化训练后的模型报错
`Traceback (most recent call last):
  File "/data/aigc/train_models/autogpt_quantize.py", line 36, in <module>
    model.quantize(examples)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 359, in quantize
    layer(layer_input, **additional_layer_inputs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat_novel1207/modeling_qwen.py", line 610, in forward
    attn_outputs = self.attn(
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat_novel1207/modeling_qwen.py", line 432, in forward
    query = apply_rotary_pos_emb(query, q_pos_emb)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat_novel1207/modeling_qwen.py", line 1345, in apply_rotary_pos_emb
    t_rot = (t_rot * cos) + (_rotate_half(t_rot) * sin)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
`

**Comment by WingsLong** [comment]
也要的问题，自己量化训练后的模型报错 了
Traceback (most recent call last):
  File "/data/aigc/train_models/autogpt_quantize.py", line 36, in <module>
    model.quantize(examples)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 359, in quantize
    layer(layer_input, **additional_layer_inputs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat_novel1207/modeling_qwen.py", line 610, in forward
    attn_outputs = self.attn(
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat_novel1207/modeling_qwen.py", line 432, in forward
    query = apply_rotary_pos_emb(query, q_pos_emb)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat_novel1207/modeling_qwen.py", line 1345, in apply_rotary_pos_emb
    t_rot = (t_rot * cos) + (_rotate_half(t_rot) * sin)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by lvheyang** [comment]
在autogptq 的官方示例下面

```
...
model = AutoGPTQForCausalLM.from_pretrained(...)

# 增加如下内容，强制模型转移到gpu
if torch.cuda.is_available():
    model.cuda()

# 以下省略
```

测试了这个方法，对我有效果

**Comment by sunyclj** [comment]
> apply_rotary_pos_emb

改完可以量化了，加载量化后的权重推理又出现问题了，FileNotFoundError: Could not find model in ./lora_finetune/qwen_7b_chat_q，应该是少文件

**Comment by sunyclj** [comment]
> 在autogptq 的官方示例下面
> 
> ```
> ...
> model = AutoGPTQForCausalLM.from_pretrained(...)
> 
> # 增加如下内容，强制模型转移到gpu
> if torch.cuda.is_available():
>     model.cuda()
> 
> # 以下省略
> ```
> 
> 测试了这个方法，对我有效果

请问量化之后，加载推理正常吗？我这边应该是缺少模型文件，报错：FileNotFoundError: Could not find model in ./lora_finetune/qwen_7b_chat_q
文件结构如下：
![1702551319443_9A07E291-6935-4148-9B9D-0FD0A223034D](https://github.com/QwenLM/Qwen/assets/44860428/4b8a7255-ad17-4af5-99b7-f2e50d7c11b2)

**Comment by sunyclj** [comment]
> > 在autogptq 的官方示例下面
> > ```
> > ...
> > model = AutoGPTQForCausalLM.from_pretrained(...)
> > 
> > # 增加如下内容，强制模型转移到gpu
> > if torch.cuda.is_available():
> >     model.cuda()
> > 
> > # 以下省略
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 测试了这个方法，对我有效果
> 
> 请问量化之后，加载推理正常吗？我这边应该是缺少模型文件，报错：FileNotFoundError: Could not find model in ./lora_finetune/qwen_7b_chat_q 文件结构如下： ![1702551319443_9A07E291-6935-4148-9B9D-0FD0A223034D](https://private-user-images.githubusercontent.com/44860428/290495516-4b8a7255-ad17-4af5-99b7-f2e50d7c11b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDQzNzQsIm5iZiI6MTcwMjYwNDA3NCwicGF0aCI6Ii80NDg2MDQyOC8yOTA0OTU1MTYtNGI4YTcyNTUtYWQxNy00YWY1LTk5YjctZjJlNTBkN2MxMWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAxMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmYxMWYzZTM3YjIyMDM4OGUwNzlmYWVjZGUxNTRiZDRjYzViMjY1MzFkNTdhYTVkOTU0ZWRiODJhZDIxYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTW_1SjX0KsWstD7K50Ni4YPA6ab2IeRMefxxLpFLJM)

已解决，可量化并推理，但是推理输出效果低于官方开源的int4量化权重，暂未分析到原因

**Comment by jklj077** [comment]
apply_rotary_emb这里报错，应该是AutoGPTQ会自己在device迁移tensor，但实现覆盖的不全，导致有些tensor没被迁移。参见<https://github.com/PanQiWei/AutoGPTQ/issues/370#issuecomment-1766913012>。

> 但是推理输出效果低于官方开源的int4量化权重

参考以下回复哈
- https://github.com/QwenLM/Qwen/issues/617#issuecomment-1809765820

校准用的数据影响不能忽略的，需要跟应用场景同分布，GPTQ需要根据校准集最小化量化误差。

**Comment by qazzombie** [comment]
> > 在autogptq 的官方示例下面
> > ```
> > ...
> > model = AutoGPTQForCausalLM.from_pretrained(...)
> > 
> > # 增加如下内容，强制模型转移到gpu
> > if torch.cuda.is_available():
> >     model.cuda()
> > 
> > # 以下省略
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 测试了这个方法，对我有效果
> 
> 请问量化之后，加载推理正常吗？我这边应该是缺少模型文件，报错：FileNotFoundError: Could not find model in ./lora_finetune/qwen_7b_chat_q 文件结构如下： ![1702551319443_9A07E291-6935-4148-9B9D-0FD0A223034D](https://private-user-images.githubusercontent.com/44860428/290495516-4b8a7255-ad17-4af5-99b7-f2e50d7c11b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjE0OTgsIm5iZiI6MTcwNTQ2MTE5OCwicGF0aCI6Ii80NDg2MDQyOC8yOTA0OTU1MTYtNGI4YTcyNTUtYWQxNy00YWY1LTk5YjctZjJlNTBkN2MxMWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAzMTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ODkxMjk1MzA2MmVmMjBhMDMyYThlNmI0ZDkzNWYzNDY0Y2RhOWMwMTdjODdlOTEzNWY5NDhmNmM2M2IwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7IOd9rHygE6-Wt3_buzADin8xht43I4Zv6vUsaxX-Mk)

你好，请问你这个少文件的问题怎么解决的呀，我的量化完之后也是没有模型文件
