### ISSUE TITLE
请问lora微调后得到的权值，可以单独使用autogptq或者kv-cache-quantization量化吗？

### ISSUE THREAD

**Issue by sunyclj** [QwenLM/Qwen#647]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

如4bit量化；量化后可以直接与提供的4bit预训练模型(通过modelscope下载)进行合并作为微调后、且量化的模型使用吗？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
据我所知，这是不行的。建议您先合并lora的权重，成为一个完整的模型，然后再整体进行量化。
