### ISSUE TITLE
用Q-LoRA微调，模型是qwen/Qwen-7B-Chat-Int4，执行脚本成功了。有output_qwen目录产生，但实测问题并没有按我提供的答案回答。

### ISSUE THREAD

**Issue by fllsoft** [QwenLM/Qwen#648]
用Q-LoRA微调，模型是qwen/Qwen-7B-Chat-Int4，执行脚本sh finetune/finetune_qlora_single_gpu.sh成功了。有output_qwen目录产生，但实测问题并没有按我提供的答案回答。以下是测试代码：
from modelscope import AutoTokenizer
from modelscope import GenerationConfig
from peft import AutoPeftModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("qwen/Qwen-7B-Chat-Int4", trust_remote_code=True)
model = AutoPeftModelForCausalLM.from_pretrained("/mnt/workspace/Qwen-main/output_qwen", device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained("qwen/Qwen-7B-Chat-Int4", trust_remote_code=True)
response, history = model.chat(tokenizer, "重点领域产业关键与共性技术攻关工程有哪些", history=None)
print(response)

**Comment by fllsoft** [comment]
[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "重点领域产业关键与共性技术攻关工程有哪些"
      },
      {
        "from": "assistant",
        "value": "重点领域节能降碳、资源利用与环境保护、尼龙新材料及应用、电气装备、特钢不锈钢、矿山装备、新能源特种车辆、生物医药、新能源储能、绿色食品。"
      },

**Comment by zRzRzRzRzRzRzR** [comment]
调调参数，微调参数根据你的数据量来决定
如果你要跟答案非常的相似，我建议直接用知识库来做，embed效果很好的，如果数据不多

**Comment by fllsoft** [comment]
您说的知识库有哪些很好用，embed是指

**Comment by fllsoft** [comment]
我的需求是用户提问任意问题，如果是非某一行业专业问题，就按大模型原有的知识回答，如果是专业问题，就按我提供的微调数据回答。

**Comment by fllsoft** [comment]
请问您说的知识库有哪些好用并且是免费开源的？
