### ISSUE TITLE
[BUG] 微调中 use_exllama 和 disable_exllama 在代码中不生效

### ISSUE THREAD

**Issue by Jiefei-Wang** [QwenLM/Qwen#649]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我尝试用Qwen-7B-Chat-Int4模型进行qlora微调，遇到了下面错误

`Found modules on cpu/disk. Using Exllama backend requires all the modules to be on GPU `

通过搜索发现已经有人提了相关issue： https://github.com/QwenLM/Qwen/issues/385 。解决方案是把`disable_exllama=True`加入config.json中。这一步我能够理解，也能够成功解决这个报错。但是我的疑问是，为什么代码中手动设置`disable_exllama=True`无法生效？下面是我在finetune.py中修改的部分的代码

```
config = transformers.AutoConfig.from_pretrained(
        model_args.model_name_or_path,
        cache_dir=training_args.cache_dir,
        trust_remote_code=True,
    )
    config.use_cache = False
    config.quantization_config.use_exllama = False
    config.quantization_config.disable_exllama = True

    # Load model and tokenizer
    model = transformers.AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        config=config,
        cache_dir=training_args.cache_dir,
        device_map=device_map,
        low_cpu_mem_usage=True if training_args.use_lora and not lora_args.q_lora else False,
        trust_remote_code=True,
        quantization_config=GPTQConfig(
            bits=4, disable_exllama=True
        )
        if training_args.use_lora and lora_args.q_lora
        else None
    )
```
如果`disable_exllama` 和 `use_exllama`无法在代码里面生效的话，那么finetune.py中给它们赋值的意义在哪里呢？

### 期望行为 | Expected Behavior

通过代码中给`disable_exllama` 或 `use_exllama`赋值来避免使用exllama

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.8
- Transformers: 4.35.2
- PyTorch: 2.1.1
- CUDA: 12.3
```

**Comment by jklj077** [comment]
你这么写的话，config的优先级是

1. 手动新建的这个config，`GPTQConfig(bits=4, disable_exllama=True)`，因为你版本是4.35.2，所以`disable_exllama`是无效的，用的是`use_exllama`这个参数，默认不传入的话相当于`True`，开启`exllama`。
2. 手动改的部分
   ```
   config.quantization_config.use_exllama = False
   config.quantization_config.disable_exllama = True
   ```
   这部分无效，因为被手动新建的config覆盖了。
3. config.json里的内容

您试试把`GPTQConfig(bits=4, disable_exllama=True)`这部分改成`GPTQConfig(bits=4, use_exllama=False)`

**Comment by Jiefei-Wang** [comment]
谢谢解答！原来是参数不匹配，按照您的方法试了下可以运行
