### ISSUE TITLE
finetune_qlora_single_gpu.sh脚本中，那些参数有相关文档解释吗

### ISSUE THREAD

**Issue by fllsoft** [QwenLM/Qwen#652]
有文档解释如下参数吗
python finetune.py \
  --model_name_or_path $MODEL \
  --data_path $DATA \
  --fp16 True \
  --output_dir output_qwen \
  --num_train_epochs 5 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 1000 \
  --save_total_limit 10 \
  --learning_rate 3e-4 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --report_to "none" \
  --model_max_length 512 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora \
  --q_lora \
  --deepspeed finetune/ds_config_zero2.json

**Comment by jklj077** [comment]
都是训练的常用参数哈，名字基本都是自解释的呢，您看哪个有歧义，我们帮您解答哈~

**Comment by jklj077** [comment]
大部分参数都是transformers trainer的参数，可以参考这里的说明 <https://huggingface.co/docs/transformers/en/main_classes/trainer#transformers.TrainingArguments>

finetune.py新增的就是--use_lora和--q_lora，前者指定使用LoRA方式，前者后者同时指定使用QLoRA方式。
