### ISSUE TITLE
为什么In4量化模型耗时比浮点模型更久？

### ISSUE THREAD

**Issue by howardgriffin** [QwenLM/Qwen#653]
如题，int4模型显存占用确实小很多，但是耗时是浮点模型fp16的5倍左右，用了flash_atten以及autogptq，求解?

**Comment by jklj077** [comment]
软件环境、卡型、测试长度都列下吧。

**Comment by jklj077** [comment]
一般来讲，量化模型推理是要更慢的。即便是GPTQ这类量化方案，如果没有专门的kernel利用参数存储降低空出来的带宽，实际也是要慢的。如果autogptq没有编译对应的kernel (pytorch版本、cuda版本、卡型) 慢也是正常的。解决方法可以试试更新下环境，或者试试我们提供的docker镜像，参见readme。
