### ISSUE TITLE
Qwen的tokenizer无法将中文文本分词为字词级别

### ISSUE THREAD

**Issue by THUchenzhou** [QwenLM/Qwen#654]
代码如下：
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B', trust_remote_code=True)
a = tokenizer.tokenize("迟到")
print(a)

程序输出为[b'\xe8\xbf\x9f\xe5\x88\xb0']

我导出了Qwen的词表，是有”迟到“这个词语的，也有”迟“、”到“两个字，但为什么还是把它分为了byte级别。

如何能达到其他中文模型的效果，比如chatglm3-6b的输出为['▁', '迟', '到']。因为我想Qwen的中文词表进行扩充，提高中文文本的编码效率。

**Comment by jklj077** [comment]
你看这个tokenize出来的列表长度不就是1了嘛，是1个token（不是2个，更不是3个）的呀。建议先看下本repo中的tokenization_note呢，扩词表也有说明的。
