### ISSUE TITLE
使用vllm部署qwen时可以配合embeddings model部署在一起都提供openai格式的api吗

### ISSUE THREAD

**Issue by Mr-IT007** [QwenLM/Qwen#655]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

**Comment by jklj077** [comment]
您找个支持openai_api的embedding model应该就可以。Qwen属于生成类模型，不适合做embedding model。
