### ISSUE TITLE
在计算acc和bad_rate时，二者采用的标准为什么是一样的呀

### ISSUE THREAD

**Issue by DryPilgrim** [QwenLM/Qwen#656]
在计算acc和bad_rate时，二者采用的标准为什么是一样的呀（前者是 "Action:"，后者是 "\nAction:"）？后者多出来的"\n"好像没有作用，因为任何时候都有。判断代码如下

1. if "Action:" in response
```
def eval_action(job):
    response = job["gen"][0]
    golden = job["response"]

    if "Action:" in response:
        response, golden = process_res(response), process_res(golden)
        if is_callable(response, golden):
            return True
    return False
```
2. if "\nAction:" in job["gen"][0]
```
        for job in jobs:
            if "\nAction:" in job["gen"][0]:
                bad_count += 1
        scores = {"bad_rate": bad_count / len(jobs)}
```

**Comment by gewenbin0992** [comment]
这两个都是用来判断模型是否调用工具，确实应该统一成"\nAction: "，但由于模型工具调用总是会输出"\nAction: xxx"，所以计算结果没影响。

**Comment by JianxinMa** [comment]
"在计算acc和bad_rate时，二者采用的标准为什么是一样的呀"

计算acc时，使用的是需要调用工具的queries，因此正确答案应该调用工具，需要包含“Action"。

计算bad_rate时，使用的是**不**需要调用工具的queries，因此正确答案**不**应该调用工具，**不**能包含“Action"。

这两个指标的考题（queries）不一样。

**Comment by DryPilgrim** [comment]
> 这两个都是用来判断模型是否调用工具，确实应该统一成"\nAction: "，但由于模型工具调用总是会输出"\nAction: xxx"，所以计算结果没影响。

tks :-)
