### ISSUE TITLE
长度外推超过4000个字符后会输出乱码

### ISSUE THREAD

**Issue by parkLGW** [QwenLM/Qwen#658]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

输入长文本让模型进行总结

### 期望行为 | Expected Behavior

模型正常输出内容

### 复现方法 | Steps To Reproduce

用vllm推理框架，输入长文本让模型进行总结，文本长度超过四千左右时，模型会输出乱码，config.json中  "use_dynamic_ntk"和 "use_logn_attn"都为true，请问这种情况是什么原因导致的呢?还需要更改哪些配置吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您好，
1. vllm中有[实现DynamicNTK](https://github.com/vllm-project/vllm/pull/1210)，但使用的config有所不同，据称需要配置
   ```json
   "rope_scaling": {
      "type": "dynamic",
      "factor": 2.0
   }
   ```
2. vllm中实现的DynamicNTK与Qwen实现的不完全一致，对结果可能会有一定影响，参见[此issue](https://github.com/vllm-project/vllm/issues/1323)

**Comment by parkLGW** [comment]
> 2\. DynamicNTK与Qwen实现的不完全一致，对结果可能会有一定影响，

好的，我试试，非常感谢您的回复

**Comment by PeterXiaTian** [comment]
现在新版本0.2.4还有这个问题吗？
