### ISSUE TITLE
[BUG] <预训练序列长度问题>

### ISSUE THREAD

**Issue by yuanzyyy** [QwenLM/Qwen#662]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我注意到在readme中提及到0925更新将训练的序列长度从2048扩充到8192
![image](https://github.com/QwenLM/Qwen/assets/141697871/ee0f86a9-fb7f-4aca-a3a6-56da1e95a2ca)

但在技术报告的第七页提及到训练使用的序列长度依然是2048
![技术报告](https://github.com/QwenLM/Qwen/assets/141697871/d3667d1d-b194-45dd-8a11-cfaba2f8f9da)

### 期望行为 | Expected Behavior

所以想请问qwen在预训练阶段所使用的序列长度到底是多少呢？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by liudayiheng** [comment]
7B是预训练前期2k，后续拓展到8k哈，配合ntk等外推可以支持32k
