### ISSUE TITLE
[BUG] Q-LOAR微调是，会生成global_step文件，里面有两个pt文件，文件还很大，这个的作用是？<title>

### ISSUE THREAD

**Issue by xiaolvtongxue-zt** [QwenLM/Qwen#664]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![微信截图_20231122150244](https://github.com/QwenLM/Qwen/assets/128565025/ff782a28-3047-4459-a2b6-99c83d3f3e6c)
![微信截图_20231122150333](https://github.com/QwenLM/Qwen/assets/128565025/8cd59c70-6516-45a4-9123-604127857ab0)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Hi，那些是DeepSpeed保存的checkpoint文件，可以删除的。

**Comment by xiaolvtongxue-zt** [comment]
> Hi，那些是DeepSpeed保存的checkpoint文件，可以删除的。

主要是我用的kaggle来跑的，能不能在启动时，传入参数来保证DeepSpeed不保存的checkpoint文件。不然经常因为空间不够而停止训练。

**Comment by jklj077** [comment]
finetune的shell脚本里把--save_strategy设成no

**Comment by xiaolvtongxue-zt** [comment]
> finetune的shell脚本里把--save_strategy设成no

谢啦谢啦

**Comment by xiaolvtongxue-zt** [comment]
> finetune的shell脚本里把--save_strategy设成no

我尝试了一下，把--save_strategy设成no，直接不保存所有的文件了，我的目的是想不保存在checkpoint中的global_step的两个大文件。微调的模型是需要保存的，这种情况如何实现？

**Comment by xiaolvtongxue-zt** [comment]
> 我理解下
> 
> ```
> - checkpoint-1/
>   - global_step1/         <-- 不要
>   - adapter_model.bin     <-- 要
> - checkpoint-2/
>   - global_step2/         <-- 不要
>   - adapter_model.bin     <-- 要
> - checkpoint-3/
>   - global_step3/         <-- 不要
>   - adapter_model.bin     <-- 要
> ```
> 
> 这个还真不好实现呢，`global_stepx`中的是DeepSpeed为了resume training保存的，如果存checkpoint的话，它默认是一定会存的。有几个方案：
> 
> * 脚本调用的时候传入--save_total_limit，只保留特定几个checkpoint（但global_step里的文件还会有的）
> * 修改代码为trainer传入一个实现了on_save的Callback，并在on_save中实现把global_step文件夹内容删掉……

明白了，感谢！如果是使用第二个方案的话，即【修改代码为trainer传入一个实现了on_save的Callback，并在on_save中实现把global_step文件夹内容删掉】，或许在不改变源码的情况下，直接在模型保存后，实现把global_step文件夹内容删掉来得更为简单。

**Comment by XinyuJiang** [comment]
You can rewrite _save_checkpoint in transformers/trainer.py and anno these lines:
![image](https://github.com/QwenLM/Qwen/assets/27414976/4c67145d-0695-4ca9-8e7b-1160a3a23ca4)


the version of transformers package is 4.31.0
