### ISSUE TITLE
为什么attention_mask是全0

### ISSUE THREAD

**Issue by frankxyy** [QwenLM/Qwen#666]
你好，我在使用qwen-7b推理。在context_decode阶段，断点看了喂入的attention_mask值，发现是全零。为什么不是阶梯状呢？某一个位置的token，应该只能attend其之前的token吧？

**Comment by logicwong** [comment]
单样本推理时attention_mask没有作用（因为输入不带padding），中途会计算一个causal_mask，起到causal attention的作用
https://huggingface.co/Qwen/Qwen-7B-Chat/blob/2abd8e5777bb4ce9c8ab4be7dbbd0fe4526db78d/modeling_qwen.py#L504-L506
