### ISSUE TITLE
lora分布式微调报错

### ISSUE THREAD

**Issue by 1424153694** [QwenLM/Qwen#668]
4张16g显存的卡，没使用flash-attention时报显存不够，使用了发现使用的显存并没有减少，依然不够。
然后修改了zero3.json配置文件中的两个地方
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "**cpu**",
            "pin_memory": true
        },
        "offload_param": {
            "device": "**cpu**",
            "pin_memory": true
        },
最后出现报错：
![360截图18280503607667](https://github.com/QwenLM/Qwen/assets/76905904/50b98673-90c4-47a0-815f-f35f8232e03c)
![360截图17981203107151112](https://github.com/QwenLM/Qwen/assets/76905904/c7bc2904-cd6f-4777-878a-ff9c132e7d72)

请问可以如何调整可以使微调跑起来，我设置的句子最大长度256，批大小为1。
我的环境如下：
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.24.1                   pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0  
astunparse                1.6.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.12.2          py310h06a4308_0  
blas                      1.0                         mkl  
boltons                   23.0.0          py310h06a4308_0  
brotli-python             1.0.9           py310h6a678d5_7  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.7.22       py310h06a4308_0  
cffi                      1.15.1          py310h5eee18b_3  
chardet                   4.0.0           py310h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py310h06a4308_0  
cmake                     3.26.4               h96355d8_0  
conda                     23.9.0          py310h06a4308_0  
conda-build               3.27.0          py310h06a4308_0  
conda-content-trust       0.2.0           py310h06a4308_0  
conda-index               0.3.0           py310h06a4308_0  
conda-libmamba-solver     23.7.0          py310h06a4308_0  
conda-package-handling    2.2.0           py310h06a4308_0  
conda-package-streaming   0.9.0           py310h06a4308_0  
cryptography              41.0.3          py310hdda0065_0  
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.3.52                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
decorator                 5.1.1              pyhd3eb1b0_0  
deepspeed                 0.12.3                   pypi_0    pypi
dnspython                 2.4.2                    pypi_0    pypi
dropout-layer-norm        0.1                      pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
exceptiongroup            1.0.4           py310h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.5.0                h6a678d5_0  
expecttest                0.1.6                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.9.0           py310h06a4308_0  
flash-attn                2.0.9                    pypi_0    pypi
fmt                       9.1.0                hdb19cb5_0  
freetype                  2.12.1               h4a9f257_0  
fsspec                    2023.10.0                pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py310heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
hjson                     3.1.0                    pypi_0    pypi
huggingface-hub           0.19.4                   pypi_0    pypi
hypothesis                6.88.4                   pypi_0    pypi
icu                       73.1                 h6a678d5_0  
idna                      3.4             py310h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
ipython                   8.15.0          py310h06a4308_0  
jedi                      0.18.1          py310h06a4308_1  
jinja2                    3.1.2           py310h06a4308_0  
jpeg                      9e                   h5eee18b_1  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
krb5                      1.20.1               h143b758_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libarchive                3.6.2                h6ac8c49_2  
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.8.0.34                      0    nvidia
libcurand                 10.3.4.52                     0    nvidia
libcurl                   8.2.1                h251f7ec_0  
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
liblief                   0.12.3               h6a678d5_0  
libmamba                  1.5.1                haf1ee3a_0  
libmambapy                1.5.1           py310h2dafd23_0  
libnghttp2                1.52.0               h2d74bed_1  
libnpp                    12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libsolv                   0.7.24               he621ea3_0  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libuv                     1.44.2               h5eee18b_0  
libwebp                   1.3.2                h11a3e52_0  
libwebp-base              1.3.2                h5eee18b_0  
libxml2                   2.10.4               hf1b16e4_1  
llvm-openmp               14.0.6               h9e868ea_0  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1           py310h7f8727e_0  
matplotlib-inline         0.1.6           py310h06a4308_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py310h5eee18b_1  
mkl_fft                   1.3.8           py310h5eee18b_0  
mkl_random                1.2.4           py310hdb19cb5_0  
more-itertools            8.12.0             pyhd3eb1b0_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0           py310h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1                    pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.26.0          py310h5f9d8c6_0  
numpy-base                1.26.0          py310hb5e798b_0  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   3.0.12               h7f8727e_0  
packaging                 23.1            py310h06a4308_0  
parso                     0.8.3              pyhd3eb1b0_0  
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pcre2                     10.42                hebb0a14_0  
peft                      0.6.2                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.0.1          py310ha6cbd5a_0  
pip                       23.3            py310h06a4308_0  
pkginfo                   1.9.6           py310h06a4308_0  
pluggy                    1.0.0           py310h06a4308_1  
prompt-toolkit            3.0.36          py310h06a4308_0  
psutil                    5.9.0           py310h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-cpuinfo                9.0.0                    pypi_0    pypi
py-lief                   0.12.3          py310h6a678d5_0  
pybind11-abi              4                    hd3eb1b0_1  
pycosat                   0.6.6           py310h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  2.5.1                    pypi_0    pypi
pydantic-core             2.14.3                   pypi_0    pypi
pygments                  2.15.1          py310h06a4308_1  
pynvml                    11.5.0                   pypi_0    pypi
pyopenssl                 23.2.0          py310h06a4308_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.13              h955ad1f_0  
python-etcd               0.4.5                    pypi_0    pypi
python-libarchive-c       2.9                pyhd3eb1b0_1  
pytorch                   2.1.1           py3.10_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1    py310h06a4308_0  
pyyaml                    6.0.1           py310h5eee18b_0  
readline                  8.2                  h5eee18b_0  
regex                     2023.10.3                pypi_0    pypi
reproc                    14.2.4               h295c915_1  
reproc-cpp                14.2.4               h295c915_1  
requests                  2.31.0          py310h06a4308_0  
rhash                     1.4.3                hdbd6064_0  
rotary-emb                0.1                      pypi_0    pypi
ruamel.yaml               0.17.21         py310h5eee18b_0  
ruamel.yaml.clib          0.2.6           py310h5eee18b_1  
safetensors               0.4.0                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
setuptools                68.0.0          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5             py310h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
tiktoken                  0.5.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
tomli                     2.0.1           py310h06a4308_0  
toolz                     0.12.0          py310h06a4308_0  
torchaudio                2.1.1               py310_cu121    pytorch
torchelastic              0.2.2                    pypi_0    pypi
torchtriton               2.1.0                     py310    pytorch
torchvision               0.16.1              py310_cu121    pytorch
tqdm                      4.65.0          py310h2f386ee_0  
traitlets                 5.7.1           py310h06a4308_0  
transformers              4.32.0                   pypi_0    pypi
transformers-stream-generator 0.0.4                    pypi_0    pypi
truststore                0.8.0           py310h06a4308_0  
types-dataclasses         0.6.6                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
typing_extensions         4.7.1           py310h06a4308_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.18         py310h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.41.2          py310h06a4308_0  
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
yaml-cpp                  0.7.0                h295c915_1  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.19.0          py310h5eee18b_0  
zstd                      1.5.5                hc292b87_0

**Comment by jklj077** [comment]
您看下内存占用哈，看日志像是OOM被系统kill了。

**Comment by 1424153694** [comment]
> 您看下内存占用哈，看日志像是OOM被系统kill了。

感谢您的回答，我现在用的是4张16g的卡，使用了flash_attention,zero3.json修改如下：
"zero_optimization": {
"stage": 3,
"offload_optimizer": {
"device": "cpu",
"pin_memory": true
},
"offload_param": {
"device": "cpu",
"pin_memory": true
},

这样依然有错，那是不是表明这些卡显存确实不足以进行微调，还有其他节省显存的方法吗，我将最大输入长度限制在了10也依然报上述错误，而且观看显存的变化，看到显存的使用并没有减少

**Comment by jklj077** [comment]
看下系统内存哈(用free或者htop之类的命令)。这个报错原因是SIGTERM，很大概率是系统内存不够，如果是显存不够报错是不一样的。

**Comment by 1424153694** [comment]
> 看下系统内存哈(用free或者htop之类的命令)。这个报错原因是SIGTERM，很大概率是系统内存不够，如果是显存不够报错是不一样的。

请问这个系统内存的占用跟我设置的"zero_optimization": {
"stage": 3,
"offload_optimizer": {
"device": "cpu",
"pin_memory": true
},
"offload_param": {
"device": "cpu",
"pin_memory": true
},这个东西有关系吗，这样设置微调14b模型正常大概需要多少系统内存？

经过查看，运行到这一步时：
![1](https://github.com/QwenLM/Qwen/assets/76905904/a623088c-506f-4b10-9ac7-901a702ba00a)
内存占用：
![2](https://github.com/QwenLM/Qwen/assets/76905904/941fe866-0d62-4820-a3c9-aee77bad73e1)
确实是内存不够用

**Comment by 1424153694** [comment]
> 您看下内存占用哈，看日志像是OOM被系统kill了。

请问这个大概需要多少内存和显存？
