### ISSUE TITLE
[BUG] <title> 使用finetune.py代码对Qwen-7B进行全参微调后，推理报错：PanicException: no entry found for key

### ISSUE THREAD

**Issue by 2010-summer** [QwenLM/Qwen#671]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

model.chat()报错
PanicException: no entry found for key

### 期望行为 | Expected Behavior

请帮忙看下这几个问题：
1、tokenizer和model加载时的配置有问题吗
2、tokenizer需要指定特殊token吗
3、generation_config使用Qwen-7B-Chat就可以吗
4、qwen-7b微调模型推理数据的形式

### 复现方法 | Steps To Reproduce

# model_dir为微调后的模型路径
tokenizer = AutoTokenizer.from_pretrained(
    model_dir, 
    trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    device_map="auto", 
    trust_remote_code=True).eval()

model.generation_config = GenerationConfig.from_pretrained('Qwen/Qwen-7B-Chat', trust_remote_code=True)

'''
 prefix:
<|im_start|>system
指令内容<|im_end|>

postfix:
<|im_start|>user
{}<|im_end|>  
<|im_start|>assistant
'''
model.chat(tokenizer, prefix + postfix.format(query), history=None)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
看着格式不对呀，`model.chat`内部会拼chatml格式，这么用的话，chatml套chatml了。自己拼模板的话，要用`model.generate`。
