### ISSUE TITLE
openai_api.py 文件高并发问题

### ISSUE THREAD

**Issue by laitianan** [QwenLM/Qwen#673]
openai_api.py 文件中启动时单个worker,目前用户请求的是串行等待处理，。
请问能否有方法改为多个worker并行处理。
当前修改了如下代码：uvicorn.run(“openai_api:app”, host='0.0.0.0', port=port, workers=2),
之后出行问题是加载了两次模型，导致我的显存不够而不能运行。

**Comment by JianxinMa** [comment]
需要并发的话，推荐阅读下README的vLLM相关信息。
