### ISSUE TITLE
用modelscope 的镜像执行web_demo 回答出不来，F12网页有报错

### ISSUE THREAD

**Issue by jeffreychen567** [QwenLM/Qwen#675]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

用modelscope 的镜像执行web_demo 回答出不来，F12网页有报错
报错信息为
DOMException: Failed to execute ‘insertBefore‘ on ‘Node‘: The node before which the new node ...报错

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
请按README说明核对下版本都对不对。还报错请把信息补充完整（复现方法、运行环境），我们帮你看看。

**Comment by a1120235890** [comment]
![image](https://github.com/QwenLM/Qwen/assets/57754489/43095728-cb70-4da2-8c5f-bf4e052b5e65)  我的好像也是回答不了 但是后台是有答案返回的

**Comment by jklj077** [comment]
嗯，这里是指定了版本了的
https://github.com/QwenLM/Qwen/blob/b1d80a9385a73b89e3c3b002fb54b9c432da2925/requirements_web_demo.txt#L1

先关掉了，题主仍会遇到该问题的话，请重开issue吧
