### ISSUE TITLE
关于新模型开源的问题💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by White-Friday** [QwenLM/Qwen#677]
### 摘要 | Summary

想要了解有没有下一步开源的计划

### 基本示例 | Basic Example

想要了解有没有下一步开源的计划

### 缺陷 | Drawbacks

想要了解有没有下一步开源的计划

**Comment by White-Friday** [comment]
请问有计划开源72b的模型吗？谢谢

**Comment by Nisoka** [comment]
30B计划呢？？望眼欲穿啊 Qwen好用

**Comment by jklj077** [comment]
> 请问有计划开源72b的模型吗？谢谢

您好，72B模型已开源，欢迎试用反馈！感谢
