### ISSUE TITLE
vLLM 部署高并发版本问题（Qwen-14B-Chat-Int4）,VLL应该配置哪个版本

### ISSUE THREAD

**Issue by laitianan** [QwenLM/Qwen#678]
根据huggingface.co 部署Qwen-14B-Chat-Int4需要版本transformers==4.32.0，
而vLLM 需要配置哪个版本呢?，经测试vLLM从0.2.2版本测试到0.1.4版本，只有0.14版本是安装成功，并且部署成功。但是在部署之后进行测试，
测试代码：
![image](https://github.com/QwenLM/Qwen/assets/12150016/c0e6a04e-3442-4086-85b7-7466341f255a)

发送的请求是成功的：
![image](https://github.com/QwenLM/Qwen/assets/12150016/928ff84e-2bc2-4dfe-97e1-92718513f29d)
结果一直出来不来在等待状态,并且最后报错超时错误
![image](https://github.com/QwenLM/Qwen/assets/12150016/809ebb19-88b2-4470-bfc5-215beae6435d)
![image](https://github.com/QwenLM/Qwen/assets/12150016/09406257-4ca4-47fc-ba28-79be3abae050)

**Comment by jklj077** [comment]
vllm主分支目前不支持AutoGPTQ量化的模型。

历史回复：<https://github.com/QwenLM/Qwen/issues/566#issuecomment-1798270274> <https://github.com/QwenLM/Qwen/issues/651#issuecomment-1820367212>

**Comment by Simile-m** [comment]
有解决方案了吗
