### ISSUE TITLE
使用 QLora 微调 14B int 4 出现过拟合

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#681]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

您好，请教个问题，我用 100 条数据使用QLora 微调，出现过拟合，我问大部分问题，都会把我 100 条里的数据带出来，这个如何解决？使用 QLora 微调 的14B int 4 出现过拟合。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您好，是否可以举个具体例子（虚构的内容也可以），我们没有理解这个现象描述，是指您用一条数据提问，结果中会包含训练用的100条数据吗？如果是这种情况，需要检查一下训练数据的格式。
