### ISSUE TITLE
Qwen-14B-Chat-Int4，VLLM不支持部署。请问有什么方案部署支持高并发api

### ISSUE THREAD

**Issue by laitianan** [QwenLM/Qwen#685]
vllm主分支目前不支持AutoGPTQ量化的模型。
目前源码中的open_api.py 部署采用fastapi部署，只有一个worker工作，不能高并发。修改多个workerer,显存被翻倍占用而退出。

**Comment by jklj077** [comment]
针对部署方面的需求，目前我们推荐的是用vLLM+FastChat的方案（第三方方案），这个目前看在社区的接受度是比较好。但缺少GPTQ量化模型的支持，也确实是它的一个痛点，社区也在积极贡献代码，官方也是在完善它的功能，但这个目前看还持上还需要一定时间，我们也是比较期待这个的。

简言之，如果您需要自己部署量化模型的高并发API，目前我们也没有方案能够给您作为参考。看看社区大佬们有没有经验了~

**Comment by felixstander** [comment]
lmdeploy关注一下

**Comment by jklj077** [comment]
https://github.com/QwenLM/vllm-gptq

**Comment by jklj077** [comment]
现在vLLM官方最新版本也已经支持GPTQ量化了，建议试试。
