### ISSUE TITLE
Qwen-14B-Chat 推理输出停不下来

### ISSUE THREAD

**Issue by litetoooooom** [QwenLM/Qwen#686]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by litetoooooom** [comment]
使用vllm 0.2.2版本进行部署。调用之后一直输出停不下来，知道超出tokens限制

**Comment by Xu-Chen** [comment]
> 使用vllm 0.2.2版本进行部署。调用之后一直输出停不下来，知道超出tokens限制

需要设置stop

**Comment by anxietymonger** [comment]
72B Chat模型同样问题，需要设置stop参数才能停，请问这是预期内行为吗？

**Comment by jklj077** [comment]
是的预期内行为，vLLM需要单独传入stop_token_ids来中止。建议参考README使用FastChat+vLLM。
