### ISSUE TITLE
What is the format of the pre-training data?

### ISSUE THREAD

**Issue by jiqizaisikao** [QwenLM/Qwen#688]
I would like to ask if I just need to use more data for pre-training, is the start and end marking necessary?

**Comment by jklj077** [comment]
Please refer to <https://github.com/QwenLM/Qwen/issues/394#issuecomment-1751606131> and <https://github.com/QwenLM/Qwen/issues/427#issuecomment-1764066111>. 

Documents are first shuffled, then concatenated using <|endoftext|>, and finally split to fixed-length chunks as training examples.
