### ISSUE TITLE
请给一个 Qwen-14B-Chat-Int4  VLLM 部署的详细方案

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#689]
### 实现PR | Implementation PR

请给一个 Qwen-14B-Chat-Int4  VLLM 部署的详细方案

### 摘要 | Summary

请给一个 Qwen-14B-Chat-Int4  VLLM 部署的详细方案

### 基本示例 | Basic Example

请给一个 Qwen-14B-Chat-Int4  VLLM 部署的详细方案

### 缺陷 | Drawbacks

请给一个 Qwen-14B-Chat-Int4  VLLM 部署的详细方案

**Comment by jklj077** [comment]
请参考 https://github.com/QwenLM/Qwen/issues/685#issuecomment-1833650793 中的回复哈，感谢理解
