### ISSUE TITLE
存在的问题：1、bitsandbytes目前不支持windows，

### ISSUE THREAD

**Issue by windkwbs** [QwenLM/Qwen#69]
存在的问题：1、bitsandbytes目前不支持windows，所以无法量化，希望提供量化版本的模型。
2、模型没做切割，所以专用GPU的内容满时，共享GPU无法接着加载。12G的显卡也爆。

**Comment by beat4ocean** [comment]
解决方法：pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl

**Comment by energy888666** [comment]
十分感谢

**Comment by energy888666** [comment]
> 解决方法：pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl
我尝试下

**Comment by huashiyiqike** [comment]
windows下wsl可以的

**Comment by jklj077** [comment]
感谢提出相关问题！

1. 我们已支持基于AutoGPTQ的量化方案，并已开源int4量化后的模型。请参考README中的说明。
2. 开源模型权重已使用safetensors进行分块。

欢迎使用！

**Comment by running-frog** [comment]
卸载量化版本，无法翻译GPU显存，加载非量化版本无此问题。win11,cuda11.8
