### ISSUE TITLE
vLLM Qwen-style dynamic NTK ROPE kernel

### ISSUE THREAD

**Issue by ZiyueHuang** [QwenLM/Qwen#693]
I implemented a draft version, and the details are posted here (https://github.com/vllm-project/vllm/pull/1860). Feel free to give some reviews/comments.

cc @jklj077

**Comment by jklj077** [comment]
In the recently unveiled Qwen1.5 release, we have implemented a strategic shift in handling long-context extensions. This update involves phasing out the use of dynamic-NTK and logn attention mechanisms. Thank you very much for the support!
