### ISSUE TITLE
可以进行微调嘛？

### ISSUE THREAD

**Issue by shuoshuo0** [QwenLM/Qwen#7]

**Comment by JustinLin610** [comment]
可以用Trainer微调，会尽快给出示例代码

**Comment by yangjianxin1** [comment]
#19 Firefly实现了对通义千问Qwen-7B模型进行多轮对话微调，有很出色的效果 @shuoshuo0

**Comment by jklj077** [comment]
我们已支持Qwen-7B和Qwen-7B-Chat的微调，其中包括全参数微调、LoRA以及Q-LoRA。请参见本存储库下的finetune文件夹，欢迎试用。
