### ISSUE TITLE
我看qwen1.8b表现强于qwen7b，有没有大佬指点一二，改进了什么

### ISSUE THREAD

**Issue by SolarKnight1** [QwenLM/Qwen#700]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

![微信图片_20231201102358](https://github.com/QwenLM/Qwen/assets/131108176/b27f8882-69c2-4801-8b38-547400e333ac)

**Comment by liudayiheng** [comment]
这里是我们的一个失误，这里7B-chat的分数使用了历史版本（8月开源版），目前更正为当前开源版7B（9月更新版）的分数
![image](https://github.com/QwenLM/Qwen/assets/19410839/1ff4adde-b215-47c2-8939-7a2701099e68)
7B的性能还是要显著强于1.8B哈
