### ISSUE TITLE
如何加载finetune后的模型？提示缺少config.json文件

### ISSUE THREAD

**Issue by ijiami-01** [QwenLM/Qwen#702]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/129148313/acdcd1bd-513a-45d3-9128-279bdf6e9a27)

![image](https://github.com/QwenLM/Qwen/assets/129148313/253e4540-d32d-4f0b-b6e3-6e73aeef122a)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
web_demo.py不支持直接加载LoRA模型的。

LoRA模型需要按REAME中的说明，用AutoPeftModelForCausalLM来加载。如果您需要web_demo.py加载LoRA模型，修改下[模型加载部分](https://github.com/QwenLM/Qwen/blob/a0a557aad820cf314c9b4234e374e5f7db8f19cb/web_demo.py#L50-L55)的代码就可以。

**Comment by ijiami-01** [comment]
> web_demo.py不支持直接加载LoRA模型的。
> 
> LoRA模型需要按REAME中的说明，用AutoPeftModelForCausalLM来加载。如果您需要web_demo.py加载LoRA模型，修改下[模型加载部分](https://github.com/QwenLM/Qwen/blob/a0a557aad820cf314c9b4234e374e5f7db8f19cb/web_demo.py#L50-L55)的代码就可以。

能不能给个例子，实在不会整，弄了1天了。

**Comment by jklj077** [comment]
```python

from peft import AutoPeftModelForCausalLM

def _load_model_tokenizer(args):
    tokenizer = AutoTokenizer.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True,
    )

    if args.cpu_only:
        device_map = "cpu"
    else:
        device_map = "auto"

    model = AutoPeftModelForCausalLM.from_pretrained(
        args.checkpoint_path, # path to the output directory
        device_map=device_map,
        trust_remote_code=True
    ).eval()

    # model = AutoModelForCausalLM.from_pretrained(
    #    args.checkpoint_path,
    #    device_map=device_map,
    #    trust_remote_code=True,
    #    resume_download=True,
    #).eval()

    config = GenerationConfig.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True,
    )

    return model, tokenizer, config
```

**Comment by youqugit** [comment]
> ```python
> from peft import AutoPeftModelForCausalLM
> 
> def _load_model_tokenizer(args):
>     tokenizer = AutoTokenizer.from_pretrained(
>         args.checkpoint_path, trust_remote_code=True, resume_download=True,
>     )
> 
>     if args.cpu_only:
>         device_map = "cpu"
>     else:
>         device_map = "auto"
> 
>     model = AutoPeftModelForCausalLM.from_pretrained(
>         args.checkpoint_path, # path to the output directory
>         device_map=device_map,
>         trust_remote_code=True
>     ).eval()
> 
>     # model = AutoModelForCausalLM.from_pretrained(
>     #    args.checkpoint_path,
>     #    device_map=device_map,
>     #    trust_remote_code=True,
>     #    resume_download=True,
>     #).eval()
> 
>     config = GenerationConfig.from_pretrained(
>         args.checkpoint_path, trust_remote_code=True, resume_download=True,
>     )
> 
>     return model, tokenizer, config
> ```


lora微调后输出的模型文件夹里面不包括generation_config.json，需要把之前的复制一份到微调后的文件夹吗
>     config = GenerationConfig.from_pretrained(
>         args.checkpoint_path, trust_remote_code=True, resume_download=True,
>     )
