### ISSUE TITLE
请问有对14B-Chat 进行System Prompt增强的计划吗

### ISSUE THREAD

**Issue by mengban** [QwenLM/Qwen#704]
看新发布的1B8和72B的Chat模型描述：
> We have also strengthened the System Prompt capabilities of the Qwen-72B-Chat and Qwen-1.8B-Chat

所以想请问下 14B-Chat 有System Prompt增强的训练吗

**Comment by mengban** [comment]
答：14B-Chat 无System Prompt增强的训练。

**Comment by mengban** [comment]
请问有对14B-Chat  进行System Prompt增强的计划吗

**Comment by ftgreat** [comment]
请问 System Prompt增强 具体是怎么做的，谢谢

**Comment by jklj077** [comment]
计划随14B的长度支持扩展一同更新。
