### ISSUE TITLE
使用qwen-72b-chat模型中英文翻译出现的问题💡

### ISSUE THREAD

**Issue by White-Friday** [QwenLM/Qwen#705]
### 摘要 | Summary

中译英时不时出现中文，怎么修改prompt都不行，出现频率较高

### 基本示例 | Basic Example

问：
请将下面的中文翻译成英文，使用华丽的词藻，请输出翻译的英文内容：
“要完善科技奖励制度，让优秀科技创新人才得到合理回报，释放各类人才创新活力。要通过改革，改变片面将论文、专利、资金数量作为人才评价标准的做法，不能让繁文缛节把科学家的手脚捆死了，不能让无穷的报表和审批把科学家的精力耽误了。”
模型答1：
"Let us perfect the system of科技awards, so that outstanding talents in technological innovation can receive reasonable returns, unleashing the innovative vitality of all types of talents. Let us change through reform the practice of evaluating talents solely based on the number of papers, patents, and funds, and not let cumbersome procedures tie the hands and feet of scientists, nor let endless reports and approvals waste the energy of scientists."
模型答2：
"To perfect the system of science and technology rewards, let excellent talents of technological innovation get reasonable returns, and release the innovative vitality of all kinds of talents. We must change the practice of using papers, patents, and the amount of funds as the only criteria for evaluating talents through reform. We must not let繁琐的bureaucracy bind the hands and feet of scientists, and we must not let endless forms and approvals waste the energy of scientists."

### 缺陷 | Drawbacks

中译英时不时出现中文，怎么修改prompt都不行，出现频率较高

### 未解决问题 | Unresolved questions

中译英时不时出现中文，怎么修改prompt都不行，出现频率较高

**Comment by wengyuan722** [comment]
太长了，出现幻觉，建议先截取短一点，再一句一句翻译。

**Comment by liudayiheng** [comment]
建议尝试降低repeat penalty系数

**Comment by White-Friday** [comment]
@liudayiheng 我在使用vllm的时候，降低repetition_penalty会出现回答一直重复的问题，比如：
你好
2023/12/4 18:51:20
你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好
当提高repetition_penalty到0.8之后，翻译仍然会出现中文
"To perfect the system of science and technology awards, and enable outstanding talents of technological innovation to receive reasonable returns, unleashing the innovation vitality of all types of talents. We must change the practice of evaluating talents solely based on the number of papers, patents, and funds through reform. We must not allow繁琐的procedures to restrain the hands and feet of scientists, nor allow endless forms and approvals to waste the energy of scientists."

请问如何该解决

**Comment by White-Friday** [comment]
> 太长了，出现幻觉，建议先截取短一点，再一句一句翻译。

@wengyuan722 我使用wizardLM-70B一直都没出现过这个问题，使用qwen14b也有这个问题，72b也有这个问题

**Comment by White-Friday** [comment]
prompt:
你是一名精通泰米尔语的专家，将下面内容翻译为泰米尔语：
“要完善科技奖励制度，让优秀科技创新人才得到合理回报，释放各类人才创新活力。要通过改革，改变片面将论文、专利、资金数量作为人才评价标准的做法，不能让繁文缛节把科学家的手脚捆死了，不能让无穷的报表和审批把科学家的精力耽误了。”

Qwen72B的结果：
"அறிவியல் அருட்கொள்ளுதல் முறையைச் சமன்பாக்கி, மதிப்பான தவழ்நடத்தப் பணியாளர்களுக்குச் சரி மறைவானதரமானதைப் πடியவரி.改革ழல், लेख-विषयक पत्रांची सर्वाधिक मागणी करणे, पैसे आणि मंजूरीदारीच्या संख्येसह भुगतान करणे हा कल्पना बदलून, सcientist's hands and legs to tie with red tape should not be allowed. Scientist's energy will not be wasted by endless forms and approvals."
请问出现这种情况如何解决呢

**Comment by jklj077** [comment]
- repetition_penalty 不要低于 1.0
- 调整topp，有重复问题调大
- 可以试试多轮对话让模型做修正

**Comment by lin-xiaosheng** [comment]
> @liudayiheng 我在使用vllm的时候，降低repetition_penalty会出现回答一直重复的问题，比如： 你好 2023/12/4 18:51:20 你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好 当提高repetition_penalty到0.8之后，翻译仍然会出现中文 "To perfect the system of science and technology awards, and enable outstanding talents of technological innovation to receive reasonable returns, unleashing the innovation vitality of all types of talents. We must change the practice of evaluating talents solely based on the number of papers, patents, and funds through reform. We must not allow繁琐的procedures to restrain the hands and feet of scientists, nor allow endless forms and approvals to waste the energy of scientists."
> 
> 请问如何该解决

请问你的问题解决了吗？时至今日我在14B上也遇到了相同的问题

**Comment by codeman0987** [comment]
同样遇到这个问题，包括通义千问的API也会出现翻译中有中文的情况，感觉是模型训练中引入的bug？？？

**Comment by zhaoydo** [comment]
同样遇到这个问题

**Comment by Jumao-OC** [comment]
该如何解决呢
