### ISSUE TITLE
72B模型是预训练阶段就完全用32k窗口的吗？

### ISSUE THREAD

**Issue by HaoshengZou** [QwenLM/Qwen#709]
config.json里的seq_length是否可以完全代表预训练时的窗口长度？72B从头开始用32k窗口训的吗？

**Comment by liudayiheng** [comment]
8k训练，可以外推32k

**Comment by HaoshengZou** [comment]
感谢回复！

**Comment by boxiaowave** [comment]
> 8k训练，可以外推32k
请问8k训练的时候base就是1000000吗？

**Comment by TissueC** [comment]
> > 8k训练，可以外推32k
> 
> 请问8k训练的时候base就是1000000吗？

Hope this issue could be reopen.

**Comment by HaoshengZou** [comment]
> > > 8k训练，可以外推32k
> > 
> > 
> > 请问8k训练的时候base就是1000000吗？
> 
> Hope this issue could be reopen.

按我的理解应该是，一直用的同一个base。预训练不同阶段改base没有任何必要，反而会让loss突然崩一下。期待官方回复后关闭issue。感谢！ @liudayiheng

**Comment by jklj077** [comment]
Not able to disclose related information. Thank you for your understanding.

**Comment by TissueC** [comment]
> > > > 8k训练，可以外推32k
> > > 
> > > 
> > > 请问8k训练的时候base就是1000000吗？
> > 
> > 
> > Hope this issue could be reopen.
> 
> 按我的理解应该是，一直用的同一个base。预训练不同阶段改base没有任何必要，反而会让loss突然崩一下。期待官方回复后关闭issue。感谢！ @liudayiheng

当时没有回，但Qwen2最近发布了，在blog中说在32k训，可以外推到128k。和Qwen1说在8k训，可以外推到32k类似。
如果不额外训练，预训练完再改base确实反而会让loss突然崩一下。但如果不训练又不改base，是做不到扩长的。

let me make myself clear, 要么Qwen1/2使用更大的base（也就是放出来模型版本的base）在更长文本上训过（但就是不愿意告知这件事）；要么使用了一种不为外界所知道的方式进行扩长，这种方式神奇地不用训练更长本文，就可以做到 既在更长文本上大海捞针接近满分，又在预训练文本长度上的loss不上升。
