### ISSUE TITLE
💡 [REQUEST] - <title>Does Qwen-75B-chat have a plan to support TensorRT LLM

### ISSUE THREAD

**Issue by qiaokesi** [QwenLM/Qwen#712]
### 起始日期 | Start Date

12/2/2023

### 摘要 | Summary

Does Qwen-75B-chat have a plan to support TensorRT LM

### 基本示例 | Basic Example

Does Qwen-75B-chat have a plan to support TensorRT LM

### 缺陷 | Drawbacks

Does Qwen-75B-chat have a plan to support TensorRT LM

**Comment by jklj077** [comment]
Please refer to the following for now:
- https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen
- https://github.com/Tlntin/Qwen-TensorRT-LLM
