### ISSUE TITLE
[BUG] 单机多卡lora微调报错

### ISSUE THREAD

**Issue by vcvcvnvcvcvn** [QwenLM/Qwen#714]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

单机多卡Lora微调出错，报错为
Traceback (most recent call last):
  File "/home/vcvcvn/playground/Qwen/finetune.py", line 361, in <module>
    train()
  File "/home/vcvcvn/playground/Qwen/finetune.py", line 354, in train
    trainer.train()
  File "/home/vcvcvn/miniconda3/envs/myenv/lib/python3.9/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/vcvcvn/miniconda3/envs/myenv/lib/python3.9/site-packages/transformers/trainer.py", line 1729, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/home/vcvcvn/miniconda3/envs/myenv/lib/python3.9/site-packages/accelerate/accelerator.py", line 1214, in prepare
    raise ValueError(
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.

### 运行环境 | Environment

```Markdown
- OS:
- Python: 3.9.18
- Transformers: 4.34.0
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by Luobots** [comment]
我也遇到了同样的错，似乎是zero3和device_map='auto'不兼容，我把device_map改为None之后不报错，但尝试zero2+8卡微调72B的LoRA base model失败。。

**Comment by vcvcvnvcvcvn** [comment]
> 我也遇到了同样的错，似乎是zero3和device_map='auto'不兼容，我把device_map改为None之后不报错，但尝试zero2+8卡微调72B的LoRA base model失败。。

哥你试试把Accelerate包的版本降一下

**Comment by Luobots** [comment]
> > 我也遇到了同样的错，似乎是zero3和device_map='auto'不兼容，我把device_map改为None之后不报错，但尝试zero2+8卡微调72B的LoRA base model失败。。
> 
> 哥你试试把Accelerate包的版本降一下

请问您的accelerate和transformers版本是？能否给一个参考，非常感谢！！

**Comment by Luobots** [comment]
> > > > 我也遇到了同样的错，似乎是zero3和device_map='auto'不兼容，我把device_map改为None之后不报错，但尝试zero2+8卡微调72B的LoRA base model失败。。
> > > 
> > > 
> > > 哥你试试把Accelerate包的版本降一下
> > 
> > 
> > 请问您的accelerate和transformers版本是？能否给一个参考，非常感谢！！
> 
> 哥你试试这个版本： accelerate 0.20.3 transformers 4.32.0

非常感谢！请问您是使用1台8卡V100和默认脚本`finetune/finetune_lora_ds.sh`以及`ds_config_zero2.json`启动72B-base-model-LoRA进行sft成功了对吗？

**Comment by Luobots** [comment]
> > > > 我也遇到了同样的错，似乎是zero3和device_map='auto'不兼容，我把device_map改为None之后不报错，但尝试zero2+8卡微调72B的LoRA base model失败。。
> > > 
> > > 
> > > 哥你试试把Accelerate包的版本降一下
> > 
> > 
> > 请问您的accelerate和transformers版本是？能否给一个参考，非常感谢！！
> 
> 哥你试试这个版本： accelerate 0.20.3 transformers 4.32.0

方便留一个邮箱交流吗？非常感谢！搞两天了，哎，还是不行

**Comment by 4sunshine** [comment]
Dear @vcvcvnvcvcvn @Luobots it will be really helpful if you can share here details of successful SFT on multi-V100. (environment, running scripts (: ) I tried many things, but did not manage to successfully finetune (LoRA/QLoRA) even 14B size model...

**Comment by vcvcvnvcvcvn** [comment]
> @vcvcvnvcvcvn 您好，我们这边修复了modeling_qwen.py中的一些bug，请您拉取最新代码之后再重新尝试一下？ 或者可以尝试下我们构建的[docker镜像](https://github.com/QwenLM/Qwen/blob/main/README_CN.md#-%E4%BD%BF%E7%94%A8%E9%A2%84%E6%9E%84%E5%BB%BA%E7%9A%84docker%E9%95%9C%E5%83%8F)

好的好的，看起来修复了mask的问题，我拉一下试试

**Comment by watreyoung** [comment]
> 我也遇到了同样的错，似乎是zero3和device_map='auto'不兼容，我把device_map改为None之后不报错，但尝试zero2+8卡微调72B的LoRA base model失败。。

想问一下这里把device_map改为None后不报错了但是单机多卡是可以运行的吗？ 这里您说的zero2+8卡微调失败的结果是什么呀？效果差还是报了其他的错呢？

**Comment by mokby** [comment]
请问有解决的么?双卡4090无论是跑Lora还是Qlora都不行,改了好久一直说显存不够,但是单卡跑就可以正常运行
