### ISSUE TITLE
[BUG] 8*A800-80G机器使用torchrun以及deepspeed启动72B-base-LoRA尝试sft失败

### ISSUE THREAD

**Issue by Luobots** [QwenLM/Qwen#718]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

## 问题1：torchrun+1台8*A800-80G机器默认脚本OOM

尝试使用最新代码`finetune.py`和默认脚本`finetune/finetune_lora_ds.sh`启动72B-base-model-LoRA进行sft失败。

此时报错OOM，通过`watch -n0.1 nvidia-smi`动态监视，发现代码先把模型加载到了`cuda:0`中（`cuda:0`最先满，别的GPU也有加载权重，但在`cuda:0` OOM后即停止。

## 问题2：torchrun+1台8*A800-80G机器修改device_map仍OOM

接**问题1**，上网搜索+查看Qwen的issue，发现可能是`device_map`问题，于是将`device_map`设置为`None`，启动，发现**CPU OOM**。

上网查找，发现需要在`.from_pretrained`中设置参数`low_cpu_mem_usage=True`，设置后启动，发现可以载入模型并且可以进入到`trainer.train()`这一步。

但在`trainer.train()`中，又一次OOM，查看报错信息，发现此时**仅仅只是在把参数加载到GPU中，还没有开始forward和backward，就已经OOM了**。

## 问题3：DeepSpeed+2台/3台8*A800-80G机器仍OOM

接**问题2**，此时尝试2台8*A800-80G机器，修改默认脚本后使用`deepspeed`启动，`deepspeed`启动脚本如下：

```bash
GPUS_PER_NODE=$(python -c 'import torch; print(torch.cuda.device_count())')
NNODES=1
HOSTFILE="finetune/hostfile"

MODEL="Qwen/Qwen-72B"
DATA="data/alpaca-gpt4.json"
DS_CONFIG_PATH="finetune/ds_config_zero2.json"


function usage() {
    echo '
Usage: bash finetune/deepspeed_finetune_lora_ds.sh [-m MODEL_PATH] [-d DATA_PATH] [--deepspeed DS_CONFIG_PATH]
'
}

DISTRIBUTED_ARGS="
    --num_gpus $GPUS_PER_NODE \
    --num_nodes $NNODES \
    --hostfile $HOSTFILE
"

deepspeed $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path ${MODEL} \
    --data_path ${DATA} \
    --bf16 True \
    --output_dir outputs/${RUN_NAME} \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "wandb" \
    --run_name ${RUN_NAME} \
    --model_max_length 512 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed ${DS_CONFIG_PATH}

```

## 问题4：DeepSpeed+2台/3台8*A800-80G机器各种尝试仍OOM

接**问题3**，尝试将`device_map`修改成`auto`等各种参数，指定[huggingface文档](https://huggingface.co/docs/transformers/main/en/main_classes/model#transformers.PreTrainedModel.from_pretrained)中各种有关**big model inference**的参数，如`max_memory={0:'52GIB', 1:'78GIB', 2:'78GIB', 3: '78GIB', 4:'78GIB', 5:'78GIB', 6:'78GIB', 7:'78GIB', 'cpu': '896GIB'},`, `offload_folder`, `offload_state_dict=True`等，设置`ds_config_zero2.json`将optimizer offload到cpu上，仍OOM。

## 问题5：DeepSpeed+1台8*A800-80G机器尝试DeepSpeed-ZeRO3失败

正如README.MD中所说，DeepSpeed-ZeRO3在sft base-model时与LoRA并不兼容，我尝试了一下，发现确实不兼容，报错如[issue-714](https://github.com/QwenLM/Qwen/issues/714)一样。

## 问题6：torchrun+1台8*A800-80G机器各种尝试仍OOM

接**问题4**，在单机中尝试**问题4**中的各种操作，仍OOM。

## 注

1. transformers提示我的模型在载入时已经自动转为**bf16**
2. 如果将`device_map`设置为`None`，且传入`low_cpu_mem_usage=True`，确实**不会导致CPU OOM**，且只会消耗**72*4=288GB**的CPU RAM
3. 我看到[issue-714](https://github.com/QwenLM/Qwen/issues/714)中作者建议我将`accelerate`包版本降一下，我尝试了从0.21.0到0.25.0，均不行
4. 我也尝试更新`transformers`包到最新版/降级，均不行
5. 我尝试对14B-base-model+LoRA进行sft，DeepSpeed+2台8*A800-80G机器是可以的，也就是说，脚本没有错误
6. 按理说，8*A800应该是可以进行72B-model的LoRA sft的？我在网上看到过相关的尝试。并且，我已经用了2台/3台了，应该可以了吧？
7. 由于ZeRO3与LoRA-base-model不兼容，所以上述脚本均采用ZeRO2，是这个问题导致的吗？但理论上这么多张A800-80G足以解决ZeRO2和ZeRO3节省的显存差距

### 复现方法 | Steps To Reproduce

使用8*A800机器和默认脚本`finetune/finetune_lora_ds.sh`启动72B-base-model-LoRA进行sft。

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.10
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA : 11.7
```

**Comment by Luobots** [comment]
非常抱歉！由于自己的理解失误，导致问了一个比较蠢的问题：ZeRO2本身就无法支持A800-80G来微调72B这么大的模型，一张卡本身就装不下了。
但我还是想问一下有没有任何可能可以解决ZeRO3+LoRA+72B-base-model的sft问题？我感觉是因为peft中ModulesToSaveWrapper的包裹，使得deepspeed无法正确处理此处的参数分块，使72B-base-model的wte的weight为空，因此形状为0而非存在参数，导致在如下代码
```python
# 在这之前input进入了self.wte.forward()...
deepspeed/runtime/zero/partitioned_param_coordinator.py", line 313, in fetch_sub_module
assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
```

中报错：

```python
AssertionError: {'id': 259, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}
```
我已经找到了一些issue：
1. https://github.com/huggingface/transformers/pull/26024
2. https://github.com/huggingface/transformers/pull/26024/files

它们解决的是peft（即LoRA）之前的问题，希望是否可以一起解决一下这个问题，非常感谢！

**Comment by Luobots** [comment]
> @Luobots 我们这边正在尽快解决这一问题，非常感谢您提供的信息！

好的，非常感谢！我也十分愿意一起解决这个问题
我想请问一下如果不传`modules_to_save`，也就是不save `lm_head`和`wte`，这会对sft得到的模型（相比save了`lm_head`和`wte`）有多大的损失呢？我不太能够想象这件事情，您是否有一些相关经验？

**Comment by Luobots** [comment]
> > @Luobots 我们这边正在尽快解决这一问题，非常感谢您提供的信息！
> 
> 好的，非常感谢！我也十分愿意一起解决这个问题 我想请问一下如果不传`modules_to_save`，也就是不save `lm_head`和`wte`，这会对sft得到的模型（相比save了`lm_head`和`wte`）有多大的损失呢？我不太能够想象这件事情，您是否有一些相关经验？

相当于是学不会`|<im_start>|`和`|<im_end>|`这两个token么？因为输入和输出都没有训练和保存？（还是说有训练，只是没保存？）

**Comment by nicole828** [comment]
请问这个问题解决了么？

**Comment by scutcyr** [comment]
同样的问题

**Comment by yonglianglan** [comment]
同样 的问题，请问解决了吗
