### ISSUE TITLE
[BUG] 你们微调代码中貌似padding的token没有mask掉

### ISSUE THREAD

**Issue by vcvcvnvcvcvn** [QwenLM/Qwen#719]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我设的最大长度为1024，后面的padding发现没被mask掉
<img width="775" alt="image" src="https://github.com/QwenLM/Qwen/assets/52404040/0617e73a-3f8d-4664-a65a-c2b55786549a">

顺便一说，微调时候的loss飞速下降，最后到了0，所以我去定位了bug，发现貌似这里有问题。。。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by HaoshengZou** [comment]
> 这个attention_mask矩阵实际不影响微调，是代码里其它地方的问题引起的，最新代码已fixed

请问是哪个commit里fix的呀？

**Comment by logicwong** [comment]
@HaoshengZou https://huggingface.co/Qwen/Qwen-72B-Chat-Int4/commit/01f9563dfc46ddcd31daa0daca62e794dd765134

**Comment by sunyclj** [comment]
> 顺便一说，微调时候的loss飞速下降，最后到了0，所以我去定位了bug，发现貌似这里有问题。。。

请问这块逻辑在代码的哪里呢？我现在想分析多轮对话训练数据是怎么输入的、loss是怎么计算的，没有找到源码位置
