### ISSUE TITLE
[BUG] Qwen-72B-Chat-Int4/modeling_qwen.py line 527 报错

### ISSUE THREAD

**Issue by qiyifei1** [QwenLM/Qwen#720]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

from modelscope import AutoModelForCausalLM, AutoTokenizer
from modelscope import GenerationConfig
model_name="qwen/Qwen-72B-Chat-Int4"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        trust_remote_code=True
    ).eval()

上述代码报错

"/data/user/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-Int4/modeling_qwen.py", line 527
    <<<<<<< HEAD
IndentationError: expected an indented block after 'if' statement on line 526

开发人员更新代码的时候在527行附近引入了额外的东西

### 期望行为 | Expected Behavior

可以正确载入模型 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by logicwong** [comment]
之前同步modelscope时没解决冲突，现在最新代码应该是正常的（hf & ms)
