### ISSUE TITLE
通义千问这几个版本，消耗单精度算力的情况如何

### ISSUE THREAD

**Issue by kekewind** [QwenLM/Qwen#722]
<img width="532" alt="1441243a98b4edc2d996d8ff2cb1052" src="https://github.com/QwenLM/Qwen/assets/35584605/6a0c5cfa-a875-4fd7-87bf-b1a47067ed2f"
上图的4个模型，消耗单精度算例如何

**Comment by hzhwcmhf** [comment]
不太明白你问题的意思。如果是想找finetune相关数据的话可以参考这一部分 https://github.com/QwenLM/Qwen#profiling-of-memory-and-speed
