### ISSUE TITLE
qwen 72b int4/8 版本的效果到底咋样，有分数吗

### ISSUE THREAD

**Issue by HC-Guo** [QwenLM/Qwen#724]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
对应Hugging Face或ModelScope页面的效果评测部分有列一些分数，比如<https://huggingface.co/Qwen/Qwen-72B-Chat#%E6%95%88%E6%9E%9C%E8%AF%84%E6%B5%8B>，可供参考。
