### ISSUE TITLE
[BUG] <单机多卡全量微调训练>

### ISSUE THREAD

**Issue by wusanshou2017** [QwenLM/Qwen#725]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Luobots** [comment]
把device_map注释掉就可以，注意ZeRO3不能调base-model，存在bug。
bug应该是peftmodel的ModulesToSaveWrapper多包裹了几层model，deepspeed不能正确切分拿到weight之类的，我正在尝试是否可以调整这个问题😂

**Comment by wusanshou2017** [comment]
> 把device_map注释掉就可以，注意ZeRO3不能调base-model，存在bug。 bug应该是peftmodel的ModulesToSaveWrapper多包裹了几层model，deepspeed不能正确切分拿到weight之类的，我正在尝试是否可以调整这个问题😂

非常感谢， 注释掉 可以了。不过 8张24G的显卡 全量微调，还是跑不了7B的模型，只能跑1.8B的模型。

**Comment by mechigonft** [comment]
“把device_map注释掉就可以”指的是在哪注释呢？finetune.py#275行吗？

**Comment by mechigonft** [comment]
还是finetune.py#298行？模型加载的时候
# Load model and tokenizer
    model = transformers.AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        config=config,
        cache_dir=training_args.cache_dir,
        device_map=device_map,
        trust_remote_code=True,
        quantization_config=GPTQConfig(
            bits=4, disable_exllama=True
        )
        if training_args.use_lora and lora_args.q_lora
        else None,
    )

**Comment by zhujinchong** [comment]
![image](https://github.com/QwenLM/Qwen/assets/40383220/3886dc2e-4476-4e7d-ab89-79b485af9e12)

**Comment by 2579356425** [comment]
> > 把device_map注释掉就可以，注意ZeRO3不能调base-model，存在bug。 bug应该是peftmodel的ModulesToSaveWrapper多包裹了几层model，deepspeed不能正确切分拿到weight之类的，我正在尝试是否可以调整这个问题😂
> 
> 非常感谢， 注释掉 可以了。不过 8张24G的显卡 全量微调，还是跑不了7B的模型，只能跑1.8B的模型。

你好，请问8张24G全量微调1.8B模型显存会跑满吗
