### ISSUE TITLE
💡 [REQUEST] - <希望function_call改造成多轮>

### ISSUE THREAD

**Issue by wengyuan722** [QwenLM/Qwen#729]
### 实现PR | Implementation PR

目前function_call，我看只能是第一次提问，才会通过parse_messages构建提示词，能不能改造成多轮的，通过增加应该system的角色，设置对应的content和tools,实现每一轮对话都能构建react的提示词。

### 相关Issues | Reference Issues

希望增加多轮function_call调用能力

### 摘要 | Summary

增加function_call多轮能力

### 基本示例 | Basic Example

    system_info = {
        "role": "system",
        "content": "Answer the following questions as best as you can. You have access to the following tools:",
        "tools": tools,
    }
    messages = [
        system_info,
        {
            "role": "user",
            "content": task_query,
        }
    ]

### 缺陷 | Drawbacks

增加function_call多轮能力

### 未解决问题 | Unresolved questions

 function_call多轮能力

**Comment by JianxinMa** [comment]
openai_api.py 应该已经是支持多轮的了？那个 parse_messages 是每一次请求都会重新根据传入的 tools 构建的。可以给更具体的例子（输入 & 实际输出 & 预期输出），以便我了解问题在哪里吗？

**Comment by wengyuan722** [comment]
当    messages = [
        {
            "role": "user",
            # Note: The current version of Qwen-7B-Chat (as of 2023.08) performs okay with Chinese tool-use prompts,
            # but performs terribly when it comes to English tool-use prompts, due to a mistake in data collecting.
            "content": "波士顿天气怎么样？",
        },
    ]
openai_api里的query, history = parse_messages(request.messages, request.functions)
中query输出是构建好的react.如下：
 Answer the following questions as best you can. You have access to the following APIs:

get_current2: Call this tool to interact with the get_current2 API. What is the get_current2 API useful for? 获取城市当 地天气预报. Parameters: {"type": "object", "properties": {"location": {"type": "string", "description": "The city and state, e.g. San Francisco, CA"}, "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location"]}

get_current_weather2: Call this tool to interact with the get_current_weather2 API. What is the get_current_weather2 API useful for? 获取城市当地天气预报 Parameters: {"type": "object", "properties": {"location": {"type": "string", "description": "The city and state, e.g. San Francisco, CA"}, "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location"]}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [get_current2, get_current_weather2]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 波士顿天气怎么样？
-------------
结果是正常的
{'index': 0, 'message': {'role': 'assistant', 'content': 'Thought: 我需要查询波士顿的天气情况。', 'function_call': {'name': 'get_current_weather2', 'arguments': '{"location": "Boston, MA"}'}}, 'finish_reason': 'function_call'}

------------
当    messages = [
        {
            "role": "user",
            # Note: The current version of Qwen-7B-Chat (as of 2023.08) performs okay with Chinese tool-use prompts,
            # but performs terribly when it comes to English tool-use prompts, due to a mistake in data collecting.
            "content": "波士顿天气怎么样？",
        },
        {
            "role": "assistant",
            # Note: The current version of Qwen-7B-Chat (as of 2023.08) performs okay with Chinese tool-use prompts,
            # but performs terribly when it comes to English tool-use prompts, due to a mistake in data collecting.
            "content": "波士顿气温10度",
        },
        {
            "role": "user",
            # Note: The current version of Qwen-7B-Chat (as of 2023.08) performs okay with Chinese tool-use prompts,
            # but performs terribly when it comes to English tool-use prompts, due to a mistake in data collecting.
            "content": "纽约天气怎么样？",
        }
    ]
openai_api里的query, history = parse_messages(request.messages, request.functions)
中query输出是构建好的react.如下：
纽约天气怎么样？
-----
结果是不是函数调用
{'index': 0, 'message': {'role': 'assistant', 'content': 'Thought: 我会作答了。\nFinal answer: 纽约温度8度', 'function_call': None}, 'finish_reason': 'stop'}


建议在每次构建时，不是从history来获取这些tool信息，而是通过system重新构建。

**Comment by wengyuan722** [comment]
另外一个是qwen是不是没有"role": "observation",有没有什么类似的role类型，不知道如何构建波士顿气温高出纽约几度

**Comment by JianxinMa** [comment]
关于前面的case，
```py
messages = [
  {
  "role": "user",
  "content": "波士顿天气怎么样？",
  },
  # 这里应该要保留工具调用的历史？但被扔了？
  {
  "role": "assistant",
  "content": "波士顿气温10度",
  },
  {
    "role": "user",
   "content": "纽约天气怎么样？",
  }
]
```
这个history似乎是残缺的，缺失了function call相关的信息（这些信息也需要拼在messages里作为history，但这里是被人为扔掉了吗）。会影响模型在后续轮数的表现。

比如，合理的历史是：
```
messages = [
  {
  "role": "user",
  "content": "波士顿天气怎么样？",
  },
  {
      "role": "assistant",
      "content": None,
      "function_call": {
          "name": "get_current_weather",
          "arguments": '{"location": "Boston, MA"}',
      },
  },
  {
      "role": "function",
      "name": "get_current_weather",
      "content": '{"temperature": "22", "unit": "celsius", "description": "Sunny"}',
  }
  {
  "role": "assistant",
  "content": "波士顿气温10度",
  },
  {
    "role": "user",
   "content": "纽约天气怎么样？",
  }
]
```

注意要保留 function_call 和 function 这两个工具调用相关的信息。

**Comment by JianxinMa** [comment]
> Author

没有observation这个role。这个接口是参考openai官方的（旧）function call接口实现的，openai的也没有这个role。

如果是希望fake插件调用结果，可以fake一个 "role": "function" 的message来做这个事情（见我上一条回复修正后的messages）
