### ISSUE TITLE
[BUG] <title>QWen-72B-Chat-INT4 Lora微调失败

### ISSUE THREAD

**Issue by qiaokesi** [QwenLM/Qwen#730]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

4张4090,单机多卡微调的时候，loss一直下不去，微调结束后，模型完全无法使用，出现胡说八道的情况。

### 期望行为 | Expected Behavior

希望可以4090多卡微调量化模型

### 复现方法 | Steps To Reproduce

1. 4卡4090
2. 调用finetune_lora_single_gpu.sh，微调数据大概8000条。
3. 微调内容

    ```
    #!/bin/bash
    export CUDA_DEVICE_MAX_CONNECTIONS=4
    
    MODEL="/home/heike/hkdata/Code/wzl/Python/Qwen-72b/models/Qwen-72B-Chat-Int4" # Set the path if you do not want to load from huggingface directly
    # ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
    # See the section for finetuning in README for more information.
    DATA="/home/heike/hkdata/Code/wzl/Python/Qwen-72b/json/liuli.json"
    
    
    export CUDA_VISIBLE_DEVICES=0,1,2,3
    
    python finetune.py \
      --model_name_or_path $MODEL \
      --data_path $DATA \
      --bf16 True \
      --output_dir output_qwen \
      --num_train_epochs 1 \
      --per_device_train_batch_size 1 \
      --per_device_eval_batch_size 1 \
      --gradient_accumulation_steps 16 \
      --evaluation_strategy "no" \
      --save_strategy "steps" \
      --save_steps 250 \
      --save_total_limit 10 \
      --learning_rate 2e-4 \
      --weight_decay 0.1 \
      --adam_beta2 0.95 \
      --warmup_ratio 0.01 \
      --lr_scheduler_type "cosine" \
      --logging_steps 1 \
      --report_to "none" \
      --model_max_length 512 \
      --lazy_preprocess True \
      --gradient_checkpointing \
      --use_lora
    
    # If you use fp16 instead of bf16, you should use deepspeed
    # --fp16 True --deepspeed finetune/ds_config_zero2.json
    ```
4. 测试微调后模型
    ```
    model = AutoPeftModelForCausalLM.from_pretrained(
        "output_qwen",  # path to the output directory
        device_map="auto",
        trust_remote_code=True,
        resume_download=True
    ).eval()
    ```
5. 模型各种不搭边的胡言乱语。在微调数据只有60条的时候，微调步数特别少的时候才正常一些。微调数据一多+步数多一点就不行了。

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python:3.10
- Transformers:4.32.0
- Auto-GPTQ:0.4.2
- PyTorch:2.0.1
- CUDA:11.8
```

**Comment by 88489754** [comment]
可以问一下你的数据格式哪样吗

**Comment by qiaokesi** [comment]
> 可以问一下你的数据格式是什么样的？
`[
    {
      "id": "identity_0",
      "conversations": [
        {
          "from": "user",
          "value": "我来了"
        },
        {
          "from": "assistant",
          "value": "你终于来啦，我等你等的好久了呢，快来和我一起玩吧"
        }
      ]
    },
    {
      "id": "identity_1",
      "conversations": [
        {
          "from": "user",
          "value": "你好"
        },
        {
          "from": "assistant",
          "value": "喵，你好啊，欢迎来到琉璃的直播间~"
        }
      ]
    }
]`

**Comment by fyabc** [comment]
您好，我们这两天更新了`modeling_qwen.py`代码，修复了一些问题，您可以更新到最新版本之后重新尝试一下吗？

**Comment by smartswordsman** [comment]
@qiaokesi 你好，请问一下你是用4张4090微调成的吗？怎么我使用6张3090微调（OOM）呢。

**Comment by qiaokesi** [comment]
> 您好，我们这两天更新了`modeling_qwen.py`代码，修复了一些问题，您可以更新到最新版本之后重新尝试一下吗？

已更新后重新尝试微调IN4，4090单机多卡，微调出来的模型依然是胡言乱语的。能否提供一份单机多卡4090可lora微调的参数。

**Comment by smartswordsman** [comment]
> > @qiaokesi 你好，请问一下你是用4张4090微调成的吗？怎么我使用6张3090微调（OOM）呢。
> 
> 我这四张4090卡，可以跑起来微调，但是一直微调出来的都是胡言乱语的。

谢谢，4090是每张24G的吗？我是使用fintune_qlora_ds.sh这个脚本在6张3090（每张显存24g）上微调，一直都是OOM，不知道是不是参数设置有问题？方便知道您是怎么做的吗，感谢感谢

**Comment by qiaokesi** [comment]
> > > @qiaokesi 你好，请问一下你是用4张4090微调成的吗？怎么我使用6张3090微调（OOM）呢。
> > 
> > 
> > 我这四张4090卡，可以跑起来微调，但是一直微调出来的都是胡言乱语的。
> 
> 谢谢，4090是每张24G的吗？我是使用fintune_qlora_ds.sh这个脚本在6张3090（每张显存24g）上微调，一直都是OOM，不知道是不是参数设置有问题？方便知道您是怎么做的吗，感谢感谢

是的，4090只有24G。我用的finetune_lora_single_gpu.sh，并不是qlora。qlora我也会报OOM。finetune_lora_single_gpu中可以指定
export CUDA_DEVICE_MAX_CONNECTIONS=4
export CUDA_VISIBLE_DEVICES=0,1,2,3
使用多卡，会自动切分模型

**Comment by smartswordsman** [comment]
> > > > @qiaokesi 你好，请问一下你是用4张4090微调成的吗？怎么我使用6张3090微调（OOM）呢。
> > > 
> > > 
> > > 我这四张4090卡，可以跑起来微调，但是一直微调出来的都是胡言乱语的。
> > 
> > 
> > 谢谢，4090是每张24G的吗？我是使用fintune_qlora_ds.sh这个脚本在6张3090（每张显存24g）上微调，一直都是OOM，不知道是不是参数设置有问题？方便知道您是怎么做的吗，感谢感谢
> 
> 是的，4090只有24G。我用的finetune_lora_single_gpu.sh，并不是qlora。qlora我也会报OOM。finetune_lora_single_gpu中可以指定 export CUDA_DEVICE_MAX_CONNECTIONS=4 export CUDA_VISIBLE_DEVICES=0,1,2,3 使用多卡，会自动切分模型

谢谢，不过这样好像调的没用

**Comment by qiaokesi** [comment]
> > > > > @qiaokesi 你好，请问一下你是用4张4090微调成的吗？怎么我使用6张3090微调（OOM）呢。
> > > > 
> > > > 
> > > > 我这四张4090卡，可以跑起来微调，但是一直微调出来的都是胡言乱语的。
> > > 
> > > 
> > > 谢谢，4090是每张24G的吗？我是使用fintune_qlora_ds.sh这个脚本在6张3090（每张显存24g）上微调，一直都是OOM，不知道是不是参数设置有问题？方便知道您是怎么做的吗，感谢感谢
> > 
> > 
> > 是的，4090只有24G。我用的finetune_lora_single_gpu.sh，并不是qlora。qlora我也会报OOM。finetune_lora_single_gpu中可以指定 export CUDA_DEVICE_MAX_CONNECTIONS=4 export CUDA_VISIBLE_DEVICES=0,1,2,3 使用多卡，会自动切分模型
> 
> 谢谢，不过这样好像调的没用

就是微调不了，我才留言的。。

**Comment by xiemeilong** [comment]
同样，四张4090 OOM

**Comment by jklj077** [comment]
QLoRA也可以采用您修改后的这种方式，单进程启动(finetune_qlora_single_gpu.sh)，去掉--deepspeed参数，但环境变量设置为多卡，使用原始的模型并行进行训练，如果您能接受这个效率的话（同时只有一张卡运行）。可以试试看。

现在提供的脚本都属于数据并行的方式，显存需求不是直接能分到各张卡上的。对于72B-Chat-Int4 QLoRA，因为QLoRA没法用ZeRO-3这种FSDP类似技术，每张卡都得至少能放下整个模型，模型参数文件就已经39GB多了，24GB肯定放不下的。

**Comment by dyeeee** [comment]
> QLoRA也可以采用您修改后的这种方式，单进程启动(finetune_qlora_single_gpu.sh)，去掉--deepspeed参数，但环境变量设置为多卡，使用原始的模型并行进行训练，如果您能接受这个效率的话（同时只有一张卡运行）。可以试试看。
> 
> 现在提供的脚本都属于数据并行的方式，显存需求不是直接能分到各张卡上的。对于72B-Chat-Int4 QLoRA，因为QLoRA没法用ZeRO-3这种FSDP类似技术，每张卡都得至少能放下整个模型，模型参数文件就已经39GB多了，24GB肯定放不下的。

请问Readme中提到的，72B qlora 微调显存占用64GB，是应该微调int4模型还是微调完整模型设置量化参数呢？4*48G 两种方式都OOM

**Comment by jklj077** [comment]
See also <https://github.com/QwenLM/Qwen/tree/main/recipes/finetune/deepspeed#settings-and-gpu-requirements>.

**Comment by sanketbadgujar007-byte** [comment]
Hey, Check out Domain Alignment by www.nugen.in
