### ISSUE TITLE
【bug】运行openai_api报403

### ISSUE THREAD

**Issue by wzhiqing** [QwenLM/Qwen#732]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行openai_api.py报错
```
openai.error.APIError: HTTP code 403 from API (<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.19.3.1</center>
</body>
</html>
)
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by wzhiqing** [comment]
openai.error.APIError: HTTP code 403 from API (<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty/1.19.3.1</center>
</body>
</html>
)

**Comment by JianxinMa** [comment]
试试 pip install "openai<1.0.0" ？

这个报错是启动 openai_api.py 时出现的，还是请求该服务时发生的。方便贴一下 python openai_api.py 时命令行终端下的 log 吗？

**Comment by wzhiqing** [comment]
是在请求该服务的时候报错。

python openai_api.py 时命令时候的log
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:03<00:00,  2.53it/s]
INFO:     Started server process [1930764]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

> 试试 pip install "openai<1.0.0" ？
> 
> 这个报错是启动 openai_api.py 时出现的，还是请求该服务时发生的。方便贴一下 python openai_api.py 时命令行终端下的 log 吗？

**Comment by wzhiqing** [comment]
pip install "openai<1.0.0" 这个之后还是不行，一样的错误
运行function_call_examples.py，这个里面的api_key写哪个key啊？

**Comment by JianxinMa** [comment]
> function_call_examples.py

如果是用我们提供的openai_api.py启动的服务的话，是不需要写api_key的，就按function_call_examples.py里的值来就好。

关于403这个问题，我目前还没有太多头绪。（是否有可能是防火墙呢。。）

**Comment by JianxinMa** [comment]
虽然我不清楚确切的原因，但可以考虑排查以下几个地方：

- 启动 openai_api.py 的机器，和请求 api 的机器，是否是同一台机器。如果不是，需要`python openai_api.py --server-name 0.0.0.0` （配合server-name为四个0），以便允许其他机器访问 api 服务。
- 填 api 地址的时候，需要填的是 `http://ip:port/v1`（比如 `http://localhost:8000/v1` ），而不是 https，也不是 `http://ip:port/` （漏了v1）

**Comment by JianxinMa** [comment]
我这边无法复现这个问题。

关于配置，调用openai前需要配置api_base和api_key：
```py
import openai
openai.api_base = "http://localhost:8000/v1"
openai.api_key = "none"
```

**Comment by wzhiqing** [comment]
好奇怪，我和你是一样的代码

**Comment by jklj077** [comment]
@wzhiqing 你这台机器上有部署其它服务吗(网页服务器或者代理之类的)？这个是openresty返回的403，你的请求似乎被其它服务处理的。尝试下换个端口看(不用8000这个端口号)还有这个问题吗？

**Comment by wzhiqing** [comment]
response = openai.ChatCompletion.create(model="Qwen", messages=messages)
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?
换了端口之后出现不同的错误了
这个是openai的版本不对么？

**Comment by jklj077** [comment]
嗯，看报错是openai版本过低了，需要<1.0的高版本。
