### ISSUE TITLE
Qwen-72B-Chat模型微调不生效

### ISSUE THREAD

**Issue by 88489754** [QwenLM/Qwen#733]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [x] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

loss下降特别快，50多轮就差不多到0了，训练后也不生效。
4卡a800+zero3 lora。可以问一下给两条数据格式吗？有人微调成功的吗？

### 运行环境 | Environment

```Markdown
- OS:Ubuntu22.04
- Python:3.8
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```
![image](https://github.com/QwenLM/Qwen/assets/33384641/802fc3fc-a087-495f-a557-919e374b950f)

**Comment by chenyzh28** [comment]
请问下这里训的是Qwen-72B的base版本，lora四张卡就能跑起来？

**Comment by 88489754** [comment]
> 请问下这里训的是Qwen-72B的base版本，lora四张卡就能跑起来？ @88489754
能跑啊，大概占用284G多点，但是不生效啊，怎么微调都死活不生效，Qwen-72B-Chat。我选择这个模型微调，是不是选错了

**Comment by 88489754** [comment]
谢谢，可以了

**Comment by chenyzh28** [comment]
> 谢谢，可以了

请问是什么问题呢？

**Comment by 88489754** [comment]
> > 谢谢，可以了
> 
> 请问是什么问题呢？

我改了学习率和轮数，也改了json之类的，啥问题就不晓得了。可能是之前的数据不咋样

**Comment by uloveqian2021** [comment]
> > > 谢谢，可以了
> > 
> > 
> > 请问是什么问题呢？
> 
> 我改了学习率和轮数，也改了json之类的，啥问题就不晓得了。可能是之前的数据不咋样

请问您这边4卡A800使训练，内存占用大概是多少

**Comment by 88489754** [comment]
> > > > 谢谢，可以了
> > > 
> > > 
> > > 请问是什么问题呢？
> > 
> > 
> > 我改了学习率和轮数，也改了json之类的，啥问题就不晓得了。可能是之前的数据不咋样
> 
> 请问您这边4卡A800使训练，内存占用大概是多少

其实这么说吧，刚开始也可能我参数设置不对，也可能我数据量少了，分布式训练也可以的2台服务器16卡，全参数微调啥的看看。主要是我才大二大三期末作业有点多。话说哪里寒假能实习吗？有没有推荐呢，广东
