### ISSUE TITLE
💡 [Question] - 您好，请教个问题，微调的数据格式，能加 instruction吗？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#739]
### 摘要 | Summary

您好，请教个问题，微调的数据格式，能加 instruction吗？比如这种格式的：  {
    "instruction": "将以下句子从一种时态转换为另一种时态",
    "input": "他正在往商店走。",
    "output": "他曾经往商店走过。"
  }

### 基本示例 | Basic Example

您好，请教个问题，微调的数据格式，能加 instruction吗？比如这种格式的：  {
    "instruction": "将以下句子从一种时态转换为另一种时态",
    "input": "他正在往商店走。",
    "output": "他曾经往商店走过。"
  }

### 缺陷 | Drawbacks

您好，请教个问题，微调的数据格式，能加 instruction吗？比如这种格式的：  {
    "instruction": "将以下句子从一种时态转换为另一种时态",
    "input": "他正在往商店走。",
    "output": "他曾经往商店走过。"
  }

**Comment by jklj077** [comment]
现在代码的话，instruction + input放到from，output放到to。

动手能力好的话，可以自己定义一个命令模板，改下数据处理代码和推理代码，从base开始微调，直接用这种3个项的数据格式。
