### ISSUE TITLE
attention_mask is not supported

### ISSUE THREAD

**Issue by luchangli03** [QwenLM/Qwen#74]
It's seems attention_mask is not supported in QWenAttention._attn(), can you support attention_mask for Qwen?
Is it ok to add two lines
```
        if attention_mask is not None:
            attn_weights = attn_weights + attention_mask

```
before 
```
        attn_weights = nn.functional.softmax(attn_weights, dim=-1)
```
in in QWenAttention._attn()?

**Comment by luchangli03** [comment]
I have tested that it's not ok just add attn_weights = attn_weights + attention_mask in QWenAttention._attn. position_ids must be used to gather logn_tensor rotary_emb.

**Comment by jklj077** [comment]
This should be fixed in the latest version (in combination with the batch inference fix). Please try pull the latest code. If the problem still exists, please let me know. Thanks.
