### ISSUE TITLE
💡 [Question] - 微调数据格式，from字段可以是回答问题的人物吗？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#747]
### 摘要 | Summary

微调数据格式，可以增加回答问题的人物吗？比如让大模型扮演诸葛亮，是否可以用如下的格式微调模型？

[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      },
      {
        "from": "诸葛亮",
        "value": "你好，我是诸葛亮，我正在和主公计划如何灭了东吴。"
      }
    ]
  }
]

### 基本示例 | Basic Example

微调数据格式，from字段可以是回答问题的人物吗？

### 缺陷 | Drawbacks

微调数据格式，from字段可以是回答问题的人物吗？

**Comment by 88489754** [comment]
报错率99%。还有百分之一，改funt，，，那个文件代码就可以。微调还行好久了终于成功了

**Comment by jklj077** [comment]
不可以，目前微调脚本不支持的。
