### ISSUE TITLE
[BUG] <72B模型无法batch推理>

### ISSUE THREAD

**Issue by chenyzh28** [QwenLM/Qwen#748]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

model.generate的时候如果指定了num_return_sequences参数不为1就会报错。比如：
`pred = model.generate(inputs=input_ids, do_sample=True, max_new_tokens=100, min_new_tokens=10, num_return_sequences=5)`
会报如下错误：
`File "/home/admin/.conda/envs/llm_eval/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
output = module._old_forward(*args, **kwargs)
File "/home/admin/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 524, in forward
-1, -1, causal_mask.size(2), -1
AttributeError: 'NoneType' object has no attribute 'size'`
但是把num_return_sequences这个参数去掉或者指定为1（默认也是1）就正常了，比如：
`pred = model.generate(inputs=input_ids, do_sample=True, max_new_tokens=100, min_new_tokens=10)`
这就导致模型推理只能得到一个答案，没法得到多个答案。是哪里有问题吗？

### 期望行为 | Expected Behavior

实现batch推理

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python:3.8
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA 11.4:
```

**Comment by chenyzh28** [comment]
> 最新代码fix这个BUG了

是只更新modeling_qwen.py吗？我换成了huggingface最新的modeling_qwen.py（https://huggingface.co/Qwen/Qwen-72B/blob/main/modeling_qwen.py），又出现了别的bug。
`RuntimeError: output with shape [3, 64, 1, 341] doesn't match the broadcast shape [3, 64, 341, 341]`
是代码哪里改错了吧？

**Comment by logicwong** [comment]
@chenyzh28 晕，我的问题。我去紧急修复一下

**Comment by logicwong** [comment]
@chenyzh28 已修复，如果还有问题就炸我

**Comment by jklj077** [comment]
@chenyzh28 请问还会遇到这个问题吗?

**Comment by chenyzh28** [comment]
问题已经解决，感谢~
