### ISSUE TITLE
小白文一下如何输出稳定的比如类似json的格式

### ISSUE THREAD

**Issue by JavinYang** [QwenLM/Qwen#749]
如题如何稳定的输出json或者xml这种格式？怎么题词？我应该去哪里看资料

**Comment by zhangquanwei962** [comment]
我也想知道。

**Comment by jklj077** [comment]
Please take a look at langchain and the JSON output parser: https://python.langchain.com/docs/modules/model_io/output_parsers/

The common way is to provide examples and make use in-contexting learning capabilities of the LLM. However, as Qwen(1.0) is not optimized in this aspect, it may not be that stable.
