### ISSUE TITLE
[BUG] qwen 7b model.generate output_scores返回结果inf

### ISSUE THREAD

**Issue by highfly22** [QwenLM/Qwen#750]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
        generation_config.output_scores = True
        outputs = model.generate(
                    input_ids,
                    stop_words_ids=stop_words_ids,
                    return_dict_in_generate=True,
                    generation_config=generation_config,
                )
```

outputs 输出结果为
```
     SampleDecoderOnlyOutput(sequences=tensor([[151644,    872,    198, 106150,  21287,  30858,   9754, 151645,    198,
         151644,  77091,    198, 106150,  21287,  30858,   9754,   3837, 112871,
          54899, 104276,   1773,  99357, 100749, 100257,  30858,   9754,   3837,
          32664,  57222,  12857, 106569,   1773, 151645, 151643]],
       device='cuda:0'), scores=(tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
       dtype=torch.bfloat16)), attentions=None, hidden_states=None)
```

### 期望行为 | Expected Behavior

scores为有效数字结果

### 复现方法 | Steps To Reproduce

见上面描述

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.8
- Transformers: 4.32.0
- PyTorch: 2.1.0+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

**Comment by luyunan0404** [comment]
我也有同样的问题，请问有解决办法吗？

**Comment by sandove** [comment]
遇到了一样的问题…

**Comment by sandove** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> ```
>         generation_config.output_scores = True
>         outputs = model.generate(
>                     input_ids,
>                     stop_words_ids=stop_words_ids,
>                     return_dict_in_generate=True,
>                     generation_config=generation_config,
>                 )
> ```
> 
> outputs 输出结果为
> 
> ```
>      SampleDecoderOnlyOutput(sequences=tensor([[151644,    872,    198, 106150,  21287,  30858,   9754, 151645,    198,
>          151644,  77091,    198, 106150,  21287,  30858,   9754,   3837, 112871,
>           54899, 104276,   1773,  99357, 100749, 100257,  30858,   9754,   3837,
>           32664,  57222,  12857, 106569,   1773, 151645, 151643]],
>        device='cuda:0'), scores=(tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0',
>        dtype=torch.bfloat16)), attentions=None, hidden_states=None)
> ```
> 
> ### 期望行为 | Expected Behavior
> scores为有效数字结果
> 
> ### 复现方法 | Steps To Reproduce
> 见上面描述
> 
> ### 运行环境 | Environment
> ```
> - OS: Ubuntu 20.04
> - Python: 3.8
> - Transformers: 4.32.0
> - PyTorch: 2.1.0+cu118
> - CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
> ```
> 
> ### 备注 | Anything else?
> _No response_

不全是 inf，中间有有效数字的，只是没有显示出来

**Comment by sandove** [comment]
> 我也有同样的问题，请问有解决办法吗？原因是什么？

不全是 inf，中间有有效数字的，只是没有显示出来

**Comment by jklj077** [comment]
In the recent Qwen1.5 release, its codebase has been integrated into the `transformers` package, aligning with the established practices of the `transformers` library. This integration signifies that the `transformers` ecosystem is now designed to natively support Qwen1.5 models in most scenarios without any additional configuration, including the `output_scores` functionality. You may still encounter `-inf`, which is expected due to the configuration of sampling parameters.

For more information about this integration, discussions on how to leverage Qwen1.5 within the transformers environment, and for updates on community feedback and enhancements, please visit the official Qwen1.5 GitHub repository at <https://github.com/QwenLM/Qwen1.5>.
