### ISSUE TITLE
💡 [Question] - 您好，请教个问题，微调多轮对话的数据格式是什么样的？如何在微调中加history？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#751]
### 摘要 | Summary

您好，请教个问题，微调多轮对话的数据格式是什么样的？如何在微调中加history？

### 基本示例 | Basic Example

您好，请教个问题，微调多轮对话的数据格式是什么样的？如何在微调中加history？

### 缺陷 | Drawbacks

您好，请教个问题，微调多轮对话的数据格式是什么样的？如何在微调中加history？

**Comment by jklj077** [comment]
conversations是个列表，直接往后加就行
```json
```
