### ISSUE TITLE
💡 [REQUEST] - 全量微调 72B 需要多少资源

### ISSUE THREAD

**Issue by Xu-Chen** [QwenLM/Qwen#755]
### 摘要 | Summary

全量微调 72B 需要多少资源呢

### 基本示例 | Basic Example

全量微调 72B 需要多少资源呢

### 缺陷 | Drawbacks

全量微调 72B 需要多少资源呢

**Comment by Xu-Chen** [comment]
4台 A800 机器，用给定的 zero3，OOM

**Comment by Sanster** [comment]
可以试下 pin_memory 改成 False

**Comment by Xu-Chen** [comment]
> 可以试下 pin_memory 改成 False

也不可以，总是 GPU 瞬间被打爆，此时其他 7 卡占用不多

**Comment by SilenceWinter** [comment]
> 4台 A800 机器，用给定的 zero3，OOM

请问，4台A800都是8卡的吗？

**Comment by Xu-Chen** [comment]
> > 4台 A800 机器，用给定的 zero3，OOM
> 
> 请问，4台A800都是8卡的吗？

4* 8 *A800
应该是需要模型并行，ds本身不是模型并行

**Comment by Sanster** [comment]
pin_memory 改成 False 主要是防止 zero3 爆内存，显存爆了的话可以试下 `allgather_bucket_size`/`reduce_bucket_size` 改成`2e8`，我这里测试 8*A800 80G + bf16 + zero3 是可以训的（batch_size 和 最大长度也会影响显存..）

**Comment by Xu-Chen** [comment]
> pin_memory 改成 False 主要是防止 zero3 爆内存，显存爆了的话可以试下 `allgather_bucket_size`/`reduce_bucket_size` 改成`2e8`，我这里测试 8*A800 80G + bf16 + zero3 是可以训的（batch_size 和 最大长度也会影响显存..）

感谢耐心回复，我倒是试了5e8，我再试试2e8

**Comment by Xu-Chen** [comment]
> pin_memory 改成 False 主要是防止 zero3 爆内存，显存爆了的话可以试下 `allgather_bucket_size`/`reduce_bucket_size` 改成`2e8`，我这里测试 8*A800 80G + bf16 + zero3 是可以训的（batch_size 和 最大长度也会影响显存..）

佬，能问下你的zero3配置json，训练启动命令吗？

**Comment by jklj077** [comment]
@Xu-Chen 目前微调代码不支持多机。单机目前也有问题吗？

**Comment by jklj077** [comment]
欸，你用的不是我们的代码？是ModelScope的？

**Comment by Xu-Chen** [comment]
> 欸，你用的不是我们的微调代码？是ModelScope的？
用的咱们这个项目下面的微调代码，单机8卡A800 内存900gb，跑不起来。
您这边如果可以跑的话，能提供下zero3配置吗

**Comment by jklj077** [comment]
@fyabc 我理解测试用的就是现在repo里提供的默认配置吧

**Comment by fyabc** [comment]
> @fyabc 我理解测试用的就是现在repo里提供的默认配置吧

@jklj077 72b微调测试时使用的是repo里面的默认配置，单机8卡A100-SXM4-80G全量微调会OOM。

**Comment by Xu-Chen** [comment]
> > @fyabc 我理解测试用的就是现在repo里提供的默认配置吧
> 
> @jklj077 72b微调测试时使用的是repo里面的默认配置，单机8卡A100-SXM4-80G全量微调会OOM。

OOM+1

**Comment by Xu-Chen** [comment]
@jklj077 @fyabc 两位老师，这个有啥方法吗？

**Comment by jklj077** [comment]
目前看着是单机很极限，也不推荐了。目前加了多机的说明，但多机ZeRO-3对通信要求特别高，不然会非常慢。

**Comment by photonchen** [comment]
@jklj077 @Xu-Chen @算是解决了吗?是用的这个qwen的脚本跑还是用的哪个？

**Comment by Qubitium** [comment]
For bfloat16, Qwen1.5 72B, no deepspeed, flash atten enabled, requires around 576GB of vram in our setup.
