### ISSUE TITLE
💡 [REQUEST] - <title>72b-chat-int推理速度很慢

### ISSUE THREAD

**Issue by yang1111-gif** [QwenLM/Qwen#756]
### 起始日期 | Start Date

2023-12-7

### 摘要 | Summary

之前运行qwen-14b-chat项目的python web_demo.py文件，不加use_flash_attn时速度超级慢，然后我装了use_flash_attn之后，速度明显提升，解决推理速度慢的问题。现在我同样的环境运行72b-int4时，同样开了use_flash_attn之后，推理速度依然很慢，这个是为什么？请各位大佬指教。

### 基本示例 | Basic Example

推理速度慢

### 缺陷 | Drawbacks

推理速度慢

**Comment by yang1111-gif** [comment]
> 问题解决了吗？遇到一样的问题了
解决了，是因为GPTQ量化的版本不一致，我的torch是2.0.1，peft transformers等版本不一致，按照readme给的两种版本重新安装一下就好了。

**Comment by TengLi931128** [comment]
> 问题解决了吗？遇到一样的问题了
> 解决了，是因为GPTQ量化的版本不一致，我的torch是2.0.1，peft transformers等版本不一致，按照readme给的两种版本重新安装一下就好了。

请问是哪个readme? 我也遇到同样的问题，谢谢

**Comment by yang1111-gif** [comment]
> > > > 问题解决了吗？遇到一样的问题了
> > > > 解决了，是因为GPTQ量化的版本不一致，我的torch是2.0.1，peft transformers等版本不一致，按照readme给的两种版本重新安装一下就好了。
> > > 
> > > 
> > > 请问是哪个readme? 我也遇到同样的问题，谢谢
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/71382201/289014516-c4c8a8ce-9b58-444f-bbf9-57bd003f732c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjc4NjgsIm5iZiI6MTcwMjAyNzU2OCwicGF0aCI6Ii83MTM4MjIwMS8yODkwMTQ1MTYtYzRjOGE4Y2UtOWI1OC00NDRmLWJiZjktNTdiZDAwM2Y3MzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA5MjYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTQ0NjZiYTdmMzkzMjk3ODU3ZDE3YjQ2YjU4YmUyZWM3NGUwZjY2YjA5YjI1NWEzZWI3NzgzNjgwNmQ5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1qj7yDDO1rta-afOUUlMNyRFEEj8VgS4I7safQZ4m10)
> 
> 我按照它的要求“torch>=2.0,<2.1 auto-gptq<0.5.0 transformers<4.35.0 optimum<1.14.0 peft>=0.5.0,<0.6.0”，速度是正常了，但是会生成乱码。你是将torch升级到2.1了么？

没有，我还是2.0.1，乱码我这边没有出现问题。

meiyou
