### ISSUE TITLE
qwen-72B/72B-int8/72B-int4支持VLLM的流式输出了吗，vllm好像只有chat，没有stream_chat的接口，有解决方案吗？谢谢💡 

### ISSUE THREAD

**Issue by Jankin66** [QwenLM/Qwen#762]
### 摘要 | Summary

qwen-72B/72B-int8/72B-int4支持VLLM的流式输出了吗，vllm好像只有chat，没有stream_chat的接口，有解决方案吗？谢谢

### 基本示例 | Basic Example

qwen-72B/72B-int8/72B-int4支持VLLM的流式输出了吗，vllm好像只有chat，没有stream_chat的接口，有解决方案吗？谢谢

### 缺陷 | Drawbacks

qwen-72B/72B-int8/72B-int4支持VLLM的流式输出了吗，vllm好像只有chat，没有stream_chat的接口，有解决方案吗？谢谢

**Comment by jklj077** [comment]
vLLM自己，或者README中部署部分提到的FastChat+vLLM，都是能支持streaming输出的。您具体是遇到了什么问题？

**Comment by Jankin66** [comment]
已收到您的信件！

**Comment by Jankin66** [comment]
> vLLM自己，或者README中部署部分提到的FastChat+vLLM，都是能支持streaming输出的。您具体是遇到了什么问题？
谢谢！非常感谢您的回复！！因为我想直接调用接口，然后看vllm的里面有model.chat()这个接口但是没有model.stream_chat（）诶

**Comment by jklj077** [comment]
欸，你是指的这个repo里的提供的vLLM wrapper吗？这个vLLM wrapper要@hzhwcmhf

我理解成vLLM(+FastChat)提供的API之类的了，那些原本就是支持streaming的。能部署FastChat+vLLM的话，还是建议部署一个API服务呢。

**Comment by Jankin66** [comment]
> 欸，你是指的这个repo里的提供的vLLM wrapper吗？这个vLLM wrapper要@hzhwcmhf
> 
> 我理解成vLLM(+FastChat)提供的API之类的了，那些原本就是支持streaming的。能部署FastChat+vLLM的话，还是建议部署一个API服务呢。

嗯嗯谢谢！对的对的，因为我是用fastapi自己弄的api接口，然后就是想着vLLM wrapper里面没有model.stream_chat（）那个。

**Comment by hzhwcmhf** [comment]
@Jankin66 如果是fastchat的话建议直接使用vllm+fastchat的部署方案。vllm_wrapper不支持流式输出，也不支持并行，只是为了不愿意部署fastchat的同学测试使用的。

**Comment by Jankin66** [comment]
> @Jankin66 如果是fastchat的话建议直接使用vllm+fastchat的部署方案。vllm_wrapper不支持流式输出，也不支持并行，只是为了不愿意部署fastchat的同学测试使用的。

明白了，谢谢你！

**Comment by Jankin66** [comment]
> @Jankin66 如果是fastchat的话建议直接使用vllm+fastchat的部署方案。vllm_wrapper不支持流式输出，也不支持并行，只是为了不愿意部署fastchat的同学测试使用的。

对了，vllm+fastchat支持量化后的模型吗？谢谢你们！ @jklj077 @hzhwcmhf

**Comment by jklj077** [comment]
try this https://github.com/QwenLM/vllm-gptq

**Comment by Jankin66** [comment]
> try this https://github.com/QwenLM/vllm-gptq

谢谢！
