### ISSUE TITLE
💡 [REQUEST] - <title> gradio web UI with system prompt

### ISSUE THREAD

**Issue by congchan** [QwenLM/Qwen#763]
### 摘要 | Summary

Hi, How to serve qwen with system prompt in the gradio web UI?

### 基本示例 | Basic Example

https://github.com/QwenLM/Qwen/blob/main/examples/system_prompt.md

### 缺陷 | Drawbacks

There seem to be no drawback at all.

**Comment by jklj077** [comment]
Hi, the web_demo.py provided in this repo currently does not support system prompt. But it should be easy to implement. PR is welcomed!
