### ISSUE TITLE
[BUG] 多卡运行时显存溢出或者说显存分配不均

### ISSUE THREAD

**Issue by T0L0ve** [QwenLM/Qwen#764]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

`Tried to allocate 34.00 MiB (GPU 3; 19.71 GiB total capacity; 18.06 GiB already allocated; 27.50 MiB free; 18.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF)`
4张A450020G显卡测试72B-int4模型，推理就会在3卡显存溢出，但明显0号卡上任务剩余显存
![image](https://github.com/QwenLM/Qwen/assets/38580985/351a1577-f9ed-4522-9160-15f9dcfed649)

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10
- Transformers:4.34.1
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by SilenceWinter** [comment]
我用2块A6000（48G）， 加载Qwen-72B-Chat-Int8时，也发现了一块显存32G， 另外一块占用41G。 然后输入文本长度超过1500个字符就崩了

**Comment by jklj077** [comment]
@T0L0ve @SilenceWinter 这个加载的时候应该是均匀的吧，然后在推理中出现的显存OOM？

**Comment by jklj077** [comment]
@Xu-Chen 你这是另外的问题，训练(data parallel)跟推理(naive model parallel)的多卡完全不一样的。开新issue描述问题吧。

**Comment by SilenceWinter** [comment]
> @T0L0ve @SilenceWinter 这个加载的时候应该是均匀的吧，然后在推理中出现的显存OOM？
输入字数超过1000字就会可能出现显存OOM， 也不是每次都会OOM，循环100次，有15次OOM

**Comment by T0L0ve** [comment]
@jklj077 加载的时候就不均匀，加载的时候0卡大概占7G剩下3张卡占15G。用vllm启动就不会出现这种情况

**Comment by jklj077** [comment]
能够复现不均匀的情况，主要是transformers的这种model parallel多卡推理实现（“横着切”），一是加载时难以平均分配，除了大小一致的transformer layer还有embedding和output layer；二是transformer有些逻辑，加载时0卡会空的多一些；三跟GPTQ的量化方式也有点关系，虽然参数量小，但隐状态大，导致长序列推理时加剧了显存不均衡。

vLLM这种tensor parallel的多卡推理实现(“竖着切”)更容易在多卡上平均分配。

总之，多卡建议用vLLM。
