### ISSUE TITLE
量化后的模型int4/int8可以用提供的脚本全量微调吗

### ISSUE THREAD

**Issue by corny813** [QwenLM/Qwen#772]

**Comment by jklj077** [comment]
GPTQ量化的模型是不支持全量微调的，因为GPTQ量化的模型也没有记录全量的参数，原理上是有矛盾的。如果有需要，建议尝试下QLoRA这类加adapter新参数的哈。

**Comment by wengyuan722** [comment]
@jklj077 GPTQ量化能不能支持zero3,我微调72 int4一直爆显存，使用4*48G资源都不行

**Comment by jklj077** [comment]
@wengyuan722 不太可能，或者说AutoGPTQ量化的模型就算支持ZeRO-3也达不到你预期的效果。AutoGPTQ里的实现线性层的量化后的参数都是`register_buffer`的普通`tensor`，不是`Parameter`，不在`module.parameters()`中。DeepSpeed ZeRO-3分块的是`module.parameters()`，就是那些adapter参数，平均每卡显存占用并不能降低多少。单卡的显存容量还是得够大。

实在想跑建议试试transformers自动的简单模型并行吧，实现思路是finetune.py里device_map设成auto，用单卡微调的脚本，配置CUDA_VISISBLE_DEVICES为多卡运行（这个就是慢，同时只有一张卡在计算）。

**Comment by wengyuan722** [comment]
@多谢，第二种方案试过了，比如2张卡，其中有一张处于空闲状态
我不懂具体算法，咨询一下，第二种调参，多卡单卡训练，lora merge后效果是不是和单卡（更大的显存）的微调结果一样

**Comment by jklj077** [comment]
> 第二种调参，多卡单卡训练，lora merge后效果是不是和单卡（更大的显存）的微调结果一样

这种的话是可以“看成”一般说的单卡训练的，因为它数据并行为1。按理说这种的多卡、单卡结果是一样，但不排除实现问题、随机因素等导致有差异。另外LoRA是可以merge的, QLoRA无法merge哈。

**Comment by wengyuan722** [comment]
多谢，另外咨询一下一个算法的问题，我不大懂，就是原来做其他模型的时候好像会把数据分拆，一部分验证一部分训练，qwen里面的finetune.py是不是也是这样设计的，不是很懂具体实现，想咨询一下

**Comment by jklj077** [comment]
目前不会自动切验证集。如果需要算验证集损失，可以修改finetune.py脚本相关参数，eval_data_path传一个跟训练集格式一样的验证集，evaluation_strategy按需设置。

**Comment by wengyuan722** [comment]
@jklj077 多谢了，目前模型能力接近实用的初期，还是需要微调配合，另外想咨询一下function的微调格式
是不是这样的

[
    {
        "id": "identity_1",
        "conversations": [
            {
                "from": "user",
                "value": """Answer the following questions as best you can. You have access to the following APIs:

get_current2: Call this tool to interact with the get_current2 API. What is the get_current2 API useful for? 获取城市当 地天气预报. Parameters: {"type": "object", "properties": {"location": {"type": "string", "description": "The city and state, e.g. San Francisco, CA"}, "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location"]}

get_current_weather2: Call this tool to interact with the get_current_weather2 API. What is the get_current_weather2 API useful for? 获取城市当地天气预报 Parameters: {"type": "object", "properties": {"location": {"type": "string", "description": "The city and state, e.g. San Francisco, CA"}, "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}}, "required": ["location"]}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [get_current2, get_current_weather2]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 波士顿天气怎么样？
<chat>"""
            },
            {
                "from": "assistant",
                "value": """Thought: 我需要获取波士顿的当前天气。
Action: get_current_weather2
Action Input: {"location": "波士顿, MA"}
Observation:
</chat>"""
            }
        ]
    }
]

**Comment by lyooyl** [comment]
> @jklj077 多谢，第二种方案试过了，比如2张卡，其中有一张处于空闲状态 我不懂具体算法，咨询一下，第二种调参，多卡单卡训练，lora merge后效果是不是和单卡（更大的显存）的微调结果一样

请问你第二种方案，也就是单卡微调，用的是72b吗？我看72bint4最少也得61GB，你的卡是48G的吧？

**Comment by lyooyl** [comment]
> @wengyuan722 不太可能，或者说AutoGPTQ量化的模型就算支持ZeRO-3也达不到你预期的效果。AutoGPTQ里的实现线性层的量化后的参数都是`register_buffer`的普通`tensor`，不是`Parameter`，不在`module.parameters()`中。DeepSpeed ZeRO-3分块的是`module.parameters()`，就是那些adapter参数，平均每卡显存占用并不能降低多少。单卡的显存容量还是得够大。
> 
> 实在想跑建议试试transformers自动的简单模型并行吧，实现思路是finetune.py里device_map设成auto，用单卡微调的脚本，配置CUDA_VISISBLE_DEVICES为多卡运行（这个就是慢，同时只有一张卡在计算）。

老师您好，请问我可不可以理解为：
Int8/4量化后的模型微调需要singleGPU微调，要求单卡显存可以放下整个模型；
未量化的模型能够采用zero3策略，多卡全参数微调，所有显卡总的显存能放下1个模型即可。   
        这个理解对吗？
我现在只有4*16GB显存+129GB内存资源，14b/72b微调都没有跑通（OOM、内存超出），请问有什么建议吗？

**Comment by wengyuan722** [comment]
对于量化模型进行使用一张卡，不然多出来的卡就白白浪费，根本没有计算

**Comment by jklj077** [comment]
> 另外想咨询一下function的微调格式是不是这样的

目前是ReAct的格式，模板可以参考这里<https://github.com/QwenLM/Qwen/blob/main/examples/react_prompt.md#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E4%BA%8Creact-%E6%A8%A1%E7%89%88>
