### ISSUE TITLE
请问一下如果对Qwen-14B-Chat进行微调后，插件调用能力会不会下降。这个插件调用是用Toollama的数据集微调过吗还是什么？

### ISSUE THREAD

**Issue by wangjvjie** [QwenLM/Qwen#773]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
性能可能会有下降哦，这个以您实测为准呢。实现插件调用能力是在训练中加入了有关数据，详见Qwen的技术报告。
