### ISSUE TITLE
💡 [Question] - 微调数据格式问题

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#774]
### 摘要 | Summary

微调数据中的from字段，除了 user，assistant ，还可以有什么取值？可以是用户自定义的角色吗？比如 "from":"刘备"

[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      },
      {
        "from": "assistant",
        "value": "我是一个语言模型，我叫通义千问。"
      }
    ]
  }
]

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
目前代码上不支持其它取值哈。
