### ISSUE TITLE
💡 [REQUEST] - <如何提取int4权重>

### ISSUE THREAD

**Issue by ColdCodeCool** [QwenLM/Qwen#775]
### 摘要 | Summary

请问如何导出int4的权重，模型load进来打印发现权重都是float16的

### 基本示例 | Basic Example

请问如何导出int4的权重，模型load进来打印发现权重都是float16的

### 缺陷 | Drawbacks

请问如何导出int4的权重，模型load进来打印发现权重都是float16的

**Comment by jklj077** [comment]
没有理解这个需求哈。int4量化模型采用的方案是GPTQ，应用的时候是只对线性层做了量化的，量化存储的格式是分组、4-bit weight、16-bit scale，这些成组后参数是量化的“权重”，单独的int4啥用没有的。

**Comment by pianogGG** [comment]
@jklj077 ，我想在tensorrt-llm中使用这个int4的文件，所以需要load int4的weights，我load了Qwen-7B-Chat-Int4发现其权重都是fp16的，model里面也没有scale参数，这些是储存在哪里了？Qwen-7B-Chat-Int4是怎么得来的，有脚本嘛？

**Comment by pianogGG** [comment]
@jklj077 有没有类似于https://github.com/qwopqwop200/GPTQ-for-LLaMa 的脚本，保存int4的weight和scale，然后我可以从safetensors文件里面加载

**Comment by jklj077** [comment]
@pianogGG 

> 我load了Qwen-7B-Chat-Int4发现其权重都是fp16的，model里面也没有scale参数，这些是储存在哪里了？

存储的话，都存在checkpoint的safetensors文件里。

运行的时候，transformers里Qwen模型是用AutoGPTQ加载的，可以试试去找model里面的量化层（QuantLinear，AutoGPTQ里有多种同名的类型），然后“参数”都是register_buffer来的，不是模型的parameter。你找到的parameter那应该都是没量化的。

> 有没有类似于https://github.com/qwopqwop200/GPTQ-for-LLaMa 的脚本

没有，这个官方也说了推荐用AutoGPTQ。

> 然后我可以从safetensors文件里面加载

safetensors格式很清楚，HuggingFace Hub前端都有展示的，比如这个<https://huggingface.co/Qwen/Qwen-7B-Chat-Int4?show_tensors=true>，里面类型Int32对应的是Int4的“参数”。一个原始线性层的weight矩阵，对应g_idx，qzeros, qweight, scale这几个新的参数。单独要int4的参数是没有用的，需要用GPTQ方案用这个4个参数反量化出一个weight矩阵。

![image](https://github.com/QwenLM/Qwen/assets/17811943/c28e9e60-837d-4cc5-a615-cb47bb4ccb24)

> Qwen-7B-Chat-Int4是怎么得来的，有脚本嘛？

用AutoGPTQ做的GPTQ方案的post-training quantization，目前我们没有官方脚本，不过挺多开发者用AutoGPTQ官方方案成功的。

**Comment by jklj077** [comment]
@pianogGG TensorRT-LLM目前已包含Qwen量化模型的示例，请参考 https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen
