### ISSUE TITLE
[BUG] <title>  请教一下各位大佬，sft或者pt用bf16还是fp16好呢？ 另外推理的时候用bf16还是fp16呢？

### ISSUE THREAD

**Issue by lianglinyi** [QwenLM/Qwen#776]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
各个场景下能用bf16建议用bf16呢，除非有些特殊要求一定要用fp16，比如一些量化后的模型。

**Comment by lianglinyi** [comment]
> 各个场景下能用bf16建议用bf16呢，除非有些特殊要求一定要用fp16，比如一些量化后的模型。

modelscope上面官方也放出了 qwen-14b-chat-Int8 Int4 的模型，那这二者推理的时候，应该用什么精度推理呢？

**Comment by lianglinyi** [comment]
> 用指定的精度，那些个量化层的kernel应该是只支持fp16。

ok，多谢大佬解答
