### ISSUE TITLE
关于Qwen系列模型 model_revision 的信息

### ISSUE THREAD

**Issue by KevinWang676** [QwenLM/Qwen#777]
有朋友知道在哪里能找到Qwen系列模型 `model_revision` 的信息吗？感谢！

![image](https://github.com/QwenLM/Qwen/assets/126712357/df68f42a-e05f-442b-a4bc-74441cbc4c67)

**Comment by jklj077** [comment]
这个是modelscope给打的tag，modelscope那里能看到
![image](https://github.com/QwenLM/Qwen/assets/17811943/c07ad23c-21e6-4582-b6b6-753338883ccc)

**Comment by KevinWang676** [comment]
感谢！找到了
