### ISSUE TITLE
Clarification on Licensing for Commercial Use of Qwen Repository

### ISSUE THREAD

**Issue by JayLiangs** [QwenLM/Qwen#778]
Dear Qwen Development Team,

I hope this message finds you well.

I am writing to seek clarification on the licensing terms associated with the Qwen code hosted on GitHub at https://github.com/QwenLM/Qwen. Your README indicates that the code is licensed under the Apache 2.0 License, which is also included in the root directory of the repository. However, I noticed that there is a document titled "Tongyi Qianwen LICENSE AGREEMENT" found within the repository, and Section 1.e of this agreement seems to encompass Qwen-related code.

Given this, there appears to be a potential overlap or conflict in the licensing terms, which has led to some uncertainty regarding the use of the Qwen code for commercial purposes.

Could you please clarify whether the code released on the GitHub repository is indeed licensed solely under the Apache 2.0 License, and thus can be used for commercial purposes? It would be greatly appreciated if you could provide guidance on the applicability of the Apache 2.0 License to the Qwen code, especially in a commercial context.

Thank you for your time and assistance. I look forward to your response.

Best regards,

**Comment by jklj077** [comment]
Hi, Jay,

Thank you for reaching us.

As explained in [the License Agreement Section in README](https://github.com/QwenLM/Qwen#license-agreement), the Qwen-related code hosted on GitHub at <https://github.com/QwenLM/Qwen>, e.g., code for demos and finetuning, is licensed under the Apache 2.0 License and can be used for commercial purposes.

In addition, the weights and code of Qwen models hosted on Hugging Face Hub and ModelScope is licensed separately under either Tongyi Qianwen LICENSE AGREEMENT or Tongyi Qianwen RESEARCH LICENSE AGREEMENT, both of which includes condition for commerical use. The texts are stored here for reference use and do not apply to the GitHub repository QwenLM/Qwen itself. 

I hope the above could clarify the issues for you and please feel free to contact us if any problem remains.

Best,
Xuancheng
