### ISSUE TITLE
请问如果想提取文本中的实体（姓名，组织名，事件），这个模型要怎样提问效果最好？

### ISSUE THREAD

**Issue by czhcc** [QwenLM/Qwen#779]
### 摘要 | Summary

如例子中的调用方式，但似乎还是不准，是否有更好的方式。

### 基本示例 | Basic Example

例如：
text1 = """
要提取的文本内容
"""

person1 = f"""
{text1}
######
请提取以上文本里的人物姓名，以列表方式输出。
"""

response, _ = model.chat(tokenizer, person1, history=None, system="你是一个自然语言处理器")
print(response)

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
可以试试写prompt的技巧，比如加示例或者明确说明要完整不要遗漏之类的；也可以尝试调整topp看看。

**Comment by kratorado** [comment]
你的prompt可以给出这样一句：
```
你的输出应当按以下结构输出JSON数组
[
{"姓名": "..."},
{"姓名": "..."},
{"姓名": "..."},
{"姓名": "..."},
]
```
