### ISSUE TITLE
[BUG] A100 80G，vLLM 运行 qwen-7b-chat 报错 torch.cuda.OutOfMemoryError。实际可用显存有 70G

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#782]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

A100 80G，vLLM 运行 qwen-7b-chat 报错 torch.cuda.OutOfMemoryError。实际可用显存还有近 70G。

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 234.00 MiB. GPU 0 has a total capacty of 80 GiB of which 176.38 MiB is free. Process 4683 has 11.05 GiB memory in use. Process 16753 has 1.71 GiB memory in use. Including non-PyTorch memory, this process has 18.80 GiB memory in use. Of the allocated memory 18.26 GiB is allocated by PyTorch, and 30.10 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by micronetboy** [comment]
是的，占用了 18G。还剩余 60 G，也应该能跑起来吧？

**Comment by jklj077** [comment]
不是的，没剩60G，这个进程占了18G，还有其它进展占用了显存。

**Comment by kidd20172017** [comment]
我也遇到了同样的问题，但是在不运行程序的时候，我的显存占用为0，也就是应该有充足的资源，但是就是报这个错误

**Comment by kidd20172017** [comment]
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-16GB           Off | 00000000:21:01.0 Off |                    0 |
| N/A   33C    P0              44W / 300W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2-16GB           Off | 00000000:21:02.0 Off |                    0 |
| N/A   32C    P0              44W / 300W |      0MiB / 16384MiB |      1%      Default |
|                                         |                      |                  N/A

**Comment by jklj077** [comment]
vLLM的版本和启动命令请提供下

**Comment by kidd20172017** [comment]
vllm: 0.2.7
启动命令是 官网给的 demo:
from vllm_wrapper import vLLMWrapper

model = vLLMWrapper('Qwen/Qwen-7B-Chat', tensor_parallel_size=1)

response, history = model.chat(query="你好", history=None)
print(response)
response, history = model.chat(query="给我讲一个年轻人奋斗创业最终取得成功的故事。", history=history)
print(response)
response, history = model.chat(query="给这个故事起一个标题", history=history)
print(response)

**Comment by jklj077** [comment]
这个问题跟题主的大概率无关哈。

对于vLLM 0.2.7，由于默认开启CUDA Graph, 会额外占用2~3GB显存，可能会OOM。
建议参照vLLM的issue区的说明，enforce_eager或降低gpu-memory-utilization。
