### ISSUE TITLE
[BUG] <title>LORA微调训练，训练集loss下降、验证集loss上升

### ISSUE THREAD

**Issue by sunyclj** [QwenLM/Qwen#785]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

训练集数据约1300条、验证集150条，epoch设置为150，rank为1，alpha=16，lr=0.003，3张GPU训练，训练集loss降低，验证集loss一直上升，过拟合了，请问参数该如何调整比较合理？

**Comment by jklj077** [comment]
Please increase the LoRA r (rank); 1 is too low.
