### ISSUE TITLE
[BUG] <官方代码 Qwen/examples /vllm_wrapper.py chat函数是否有误？>

### ISSUE THREAD

**Issue by txy6666yr** [QwenLM/Qwen#786]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

代码链接：[examples/vllm_wrapper.py](https://github.com/QwenLM/Qwen/blob/main/examples/vllm_wrapper.py)
chat函数中，self.model.generate([query], 这里是否需要改成raw_text，因为传入的参数context_tokens已经是拼接special token的值，但是传入的prompt并不是拼接上下文和special token 的字符串。
```
raw_text, context_tokens = make_context(
            self.tokenizer,
            query,
            history=history,
            system=system,
            max_window_size=max_window_size,
            chat_format=generation_config.chat_format,
        )

        req_outputs = self.model.generate([query],
                                            sampling_params=sampling_params,
                                            prompt_token_ids=[context_tokens])
```

### 期望行为 | Expected Behavior

```
raw_text, context_tokens = make_context(
            self.tokenizer,
            query,
            history=history,
            system=system,
            max_window_size=max_window_size,
            chat_format=generation_config.chat_format,
        )

        req_outputs = self.model.generate([raw_text],
                                            sampling_params=sampling_params,
                                            prompt_token_ids=[context_tokens])
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by hzhwcmhf** [comment]
@txy6666yr 这里确实存在一点问题。不过这个错误不影响结果，因为vllm在传入prompt_token_ids时，第一个参数的值不会参与生成。我们之后会更新这部分代码，感谢指出错误！

**Comment by txy6666yr** [comment]
> @txy6666yr 这里确实存在一点问题。不过这个错误不影响结果，因为vllm在传入prompt_token_ids时，第一个参数的值不会参与生成。我们之后会更新这部分代码，感谢指出错误！

好的，收到，谢谢~
