### ISSUE TITLE
AssertionError: We detect you are probably using the pretrained model (rather than chat model) for chatting, since the chat_format in generation_config is not "chatml". If you are directly using the model downloaded from Huggingface, please make sure you are using our "Qwen/Qwen-7B-Chat" Huggingface model (rather than "Qwen/Qwen-7B") when you call model.chat().

### ISSUE THREAD

**Issue by Modas-Li** [QwenLM/Qwen#788]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

openai_api.py script cannot realise chat function from sft model of qwen-7b

### 期望行为 | Expected Behavior

fix it

### 复现方法 | Steps To Reproduce

None

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Hi, which model were you using?

**Comment by Modas-Li** [comment]
qwen-7b after sft fine-tuning



发自我的iPhone


------------------ Original ------------------
From: Ren Xuancheng ***@***.***&gt;
Date: Tue,Dec 12,2023 5:52 PM
To: QwenLM/Qwen ***@***.***&gt;
Cc: Modas Li ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [QwenLM/Qwen] AssertionError: We detect you are probably usingthe pretrained model (rather than chat model) for chatting, since thechat_format in generation_config is not "chatml". If you are directly usingthe model downloaded from Huggingface, please make sure you are using our"Qwen/Qwen-7B-Chat" Huggingface model (rather than "Qwen/Qwen-7B") when youcall model.chat(). (Issue #788)





 
Hi, which model were you using?

**Comment by jklj077** [comment]
If you used the finetune.py from this repo, you can simply modfiy the generation_config.json as other Qwen-Chat models.
