### ISSUE TITLE
Does qwen72B support Zero3? I get an error when using Zero3.

### ISSUE THREAD

**Issue by Kayce001** [QwenLM/Qwen#789]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Does qwen72B support Zero3? I get an error when using Zero3.

**Comment by jklj077** [comment]
支持ZeRO3，贴下报错。

**Comment by Xu-Chen** [comment]
我也是用官方给定的 zero3 和微调代码，不能正常微调

**Comment by Xu-Chen** [comment]
https://github.com/QwenLM/Qwen/issues/755

**Comment by jklj077** [comment]
@Xu-Chen 您的问题还涉及多机，请先在原issue下讨论，这个楼主error是啥我们还不知道呢。
