### ISSUE TITLE
[BUG] <title>GPU只有一张卡利用率高，其他基本上没有用到

### ISSUE THREAD

**Issue by boquanzhou** [QwenLM/Qwen#790]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

4张v100-32G，跑的72B-int4，发现推理时基本上只有一张卡跑的比较高，如何让四张卡都利用起来？
![image](https://github.com/QwenLM/Qwen/assets/140485934/7a3f45fb-d34c-4d87-8c1e-0b014ed4f97b)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
transformers的多卡推理是这样的，同时只有一张卡在计算，就是最原始的的模型并行。需要多卡同时计算的话，至少得tensor parallel了，请参考README部署部分使用FastChat+vLLM吧。

**Comment by boquanzhou** [comment]
> transformers的多卡推理是这样的，同时只有一张卡在计算，就是最原始的的模型并行。需要多卡同时计算的话，至少得tensor parallel了，请参考README部署部分使用FastChat+vLLM吧。

但是好像现在int4还不支持vLLM吧，啥时候能支持啊

**Comment by jklj077** [comment]
试试https://github.com/QwenLM/vllm-gptq

**Comment by boquanzhou** [comment]
> 试试https://github.com/QwenLM/vllm-gptq

不支持v100...

Error:
ValueError: The quantization method gptq is not supported for the current GPU. Minimum capability: 75. Current capability: 70.

**Comment by ChrisXULC** [comment]
@jklj077 请问下为什么多卡推理时显存占用会比单卡占用的更多

**Comment by jklj077** [comment]
@boquanzhou vLLM官方加了GPTQ的支持，那个v100应该可以的。

**Comment by jklj077** [comment]
> 请问下为什么多卡推理时显存占用会比单卡占用的更多

多卡有代价。

**Comment by ChrisXULC** [comment]
> > 请问下为什么多卡推理时显存占用会比单卡占用的更多
> 
> 多卡有代价。

@jklj077 请问下那些多出来的显存具体是什么呀，因为算kv cache的话并不会有那么大的开销

**Comment by ChrisXULC** [comment]
> @ChrisXULC 你是多了多少？vLLM是会预分配显存的（实际没用那么多），通过gpu-memory-utilization可以调整。transformer多卡涉及pytorch的memory cache管理，也会越来越多（实际没用那么多）。

@jklj077 模型在进行推理（用model.chat)的时候，比如说用7b的模型推10000个tokens, 单卡显存占用29个G（包括模型），但是用多卡推理的时候（包括模型），发现每张卡都是10个G，其中一张卡占了70个G，我拿kv cache的公式去计算 发现多卡推理的会比理论多了非常多

**Comment by jklj077** [comment]
@ChrisXULC 请新开个issue描述问题吧。
