### ISSUE TITLE
能否提供一个 base model finetune 的脚本？

### ISSUE THREAD

**Issue by SefaZeng** [QwenLM/Qwen#794]
目前的 finetune.py 应该是为了 chat model 设计的，能不能给一个 base model finetune 的脚本？我这边自己的脚本 finetune 一直没有正常的结果，在 LLAMA 和 BLOOM 上都是正常的。

**Comment by jklj077** [comment]
finetune.py是从base/chat模型finetune出chat模型。从base到base的finetune暂无哈。
