### ISSUE TITLE
[BUG] Docker多GPU LoRA报错：AssertionError: {'id': 323, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}

### ISSUE THREAD

**Issue by jiangliqin** [QwenLM/Qwen#795]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用qwenllm/qwen:cu117镜像,对Qwen-14B-Chat在2*v100上进行LoRA微调报错

### 期望行为 | Expected Behavior

是环境配置不兼容吗？能够帮忙复现排查下~

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8.10
- Transformers:4.32.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

<img width="1738" alt="image" src="https://github.com/QwenLM/Qwen/assets/12250847/6376a03d-31eb-4417-9f5f-1625b68b9243">

**Comment by LMXKO** [comment]
这个问题我也遇到了
![image](https://github.com/QwenLM/Qwen/assets/35209678/a4b1033e-76dc-4d98-ae41-decfa11f8ced)

**Comment by nightmaredimple** [comment]
我也遇到了, 通过finetune/finetune_lora_ds.sh对Qwen-14B模型进行finetune时遇到的

**Comment by LMXKO** [comment]
> 我也遇到了, 通过finetune/finetune_lora_ds.sh对Qwen-14B模型进行finetune时遇到的

不用lora这个错误就没了

**Comment by tangsipeng** [comment]
> 我也遇到了, 通过finetune/finetune_lora_ds.sh对Qwen-14B模型进行finetune时遇到的

我也是

**Comment by njupopsicle** [comment]
有什么解决办法嘛？只能做得起lora

**Comment by yawzhe** [comment]
有解决的没？我也遇到了

**Comment by fyabc** [comment]
@jiangliqin @nightmaredimple 您好，可以提供一下报错的具体命令吗？

**Comment by yawzhe** [comment]
我报错是 运行的 bash finetune/finetune_lora_ds.sh ,使用的是你们提供的deepspeed_stage3， 初次运行的时候报了其他的错误，注释了 device_map="auto"

**Comment by nightmaredimple** [comment]
> @jiangliqin @nightmaredimple 您好，可以提供一下报错的具体命令吗？

就是按照官方提供的，执行bash finetune/finetune_lora_ds.sh，diff有：
- fp16=True
- 使用finetune/ds_config_zero3.json
- 注释finetune.py中的device_map="auto"

不确定是否跟这个issue相关：https://github.com/huggingface/peft/issues/1278

**Comment by fyabc** [comment]
@yawzhe 目前对Base模型使用`finetune/finetune_lora_ds.sh`进行多机LoRA微调，在使用deepspeed zero3的情况下，会由于peft内部的处理逻辑，导致deepspeed无法正确切分embedding（`wte`）参数，可参考 #718 的相关信息。

我们正在解决该问题，目前您可以尝试以下方法：改用基于Chat模型微调、改用Q-LoRA微调、将zero3改为zero2配置、或者在`finetune.py`中手动关闭对`wte`参数的微调（参见[此处](https://github.com/QwenLM/Qwen/blob/4aab1d490b268783bdda80b87b7fb501539b7929/finetune.py#L320)）。

如果不是上面的微调配置而仍然报错，您可以尝试更新docker镜像到最新版本然后重试一下，我们这边测试的结果，其他情况下均能正常微调。

**Comment by yawzhe** [comment]
我用的就是chat模型微调lora,使用deepspeed,发现报错

**Comment by fyabc** [comment]
> 我用的就是chat模型微调lora,使用deepspeed,发现报错

如果使用的是chat模型微调，应当是不会出现问题的。
可以更新一下docker镜像，再检查一下运行命令时chat模型挂载到的模型名是否包含`“chat”`字符串，`finetune.py`根据这个条件判断是否将`wte`加入微调之中。

**Comment by icowan** [comment]
遇到了同样的问题，改成 qwen-14b-chat 就好了
