### ISSUE TITLE
lora的trainable参数问题

### ISSUE THREAD

**Issue by fanbooo** [QwenLM/Qwen#797]
感谢qwen团队的工作；
请问下，目前我做lora_ds finetune的时候，trainable parameters的占比是28%；
当我把lora rank 从64降为8，lora_target_modules 从["c_attn", "c_proj", "w1", "w2"] 改为 ["c_attn"]；
trainable parameters的占比还是28%左右，请问这是什么原因呢？

**Comment by jklj077** [comment]
是从Qwen-1.8B或者7B的base模型开始训练的吗？如果是话，是符合预期。从预训练模型开始LoRA finetune，除了LoRA的adapter（参数量实际不多），还要训练embedding/output layer，这两个占了大部分。

**Comment by fanbooo** [comment]
> 是从Qwen-1.8B或者7B的base模型开始训练的吗？如果是话，是符合预期。从预训练模型开始LoRA finetune，除了LoRA的adapter（参数量实际不多），还要训练embedding/output layer，这两个占了大部分。

是从qwen-chat开始训的，另外我把module_to_save=None ，好像训练参数占用率没怎么降？这个设置是合理的吗？

**Comment by jklj077** [comment]
这个不太符合预期哦，请看下存的adapter.bin那个文件大小有没有差异
