### ISSUE TITLE
[BUG] <title> Qwen72b chat 4bit推理速度缓慢 不足1 tokens/s A100单卡

### ISSUE THREAD

**Issue by zlh1992** [QwenLM/Qwen#800]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/39059487/b0ef5141-eccc-4007-a3ca-139912123be1)

Average generate speed (tokens/s): 0.6744473981595455
GPU Memory cost: 40.03901815414429GB
Experiment setting: 
seed = 1024
max_experiment_times = 1
context_length_per_experiment = 1
generate_length_per_experiment = 128
use_flash_attn = True
quant_type = int4

测了官方的我使用automodel加载，得出了如上的速度
model = transformers.AutoModelForCausalLM.from_pretrained(
        base_model,
        # config=config,
        device_map="auto",
        trust_remote_code=True,
        use_flash_attn=True,
        quantization_config=GPTQConfig(
            bits=4, disable_exllama=True
        )
    ).eval()

# model = AutoGPTQForCausalLM.from_quantized(
    #     base_model, 
    #     device="cuda:0", 
    #     trust_remote_code=True, 
    #     use_safetensors=True, 
    #     use_flash_attn=use_flash_attn,
    # ).eval()

因为autogptq加载会报错：
File ~/miniconda3/lib/python3.8/site-packages/auto_gptq/modeling/_base.py:844, in BaseGPTQForCausalLM.from_quantized(cls, model_name_or_path, device_map, max_memory, device, low_cpu_mem_usage, use_triton, use_qigen, torch_dtype, inject_fused_attention, inject_fused_mlp, use_cuda_fp16, quantize_config, model_basename, use_safetensors, trust_remote_code, warmup_triton, trainable, disable_exllama, disable_exllamav2, **kwargs)
    841 quantize_config.model_file_base_name = true_model_basename
    843 if resolved_archive_file is None:
--> 844     raise FileNotFoundError(f"Could not find a model in {model_name_or_path} with a name in {', '.join(searched_files)}. Please specify the argument model_basename to use a custom file name.")
    846 model_save_name = resolved_archive_file
    848 if (not disable_exllama or not disable_exllamav2) and trainable:

FileNotFoundError: Could not find a model in /home/models/qwen_72b_4bit/ with a name in model.safetensors. Please specify the argument model_basename to use a custom file name.

### 期望行为 | Expected Behavior

提升推理速度

### 复现方法 | Steps To Reproduce

官方测速脚本profile.py

### 运行环境 | Environment

```Markdown
- OS: linux
- Python: 3.8.17
- Transformers: 4.36.0
- PyTorch: 2.0.1+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.4

其他库版本：
optimum                           1.15.0
accelerate                        0.25.0
auto-gptq                         0.5.1
peft                              0.7.1
flash-attn                        2.3.1.post1
```

**Comment by zlh1992** [comment]
已解决：
pip install transformers==4.34.0
pip install auto-gptq==0.4.2
pip install peft==0.5.0
pip install optimum==1.13.3

![image](https://github.com/QwenLM/Qwen/assets/39059487/1f66e177-8167-4ad6-964d-361e0aaf4231)

实测大概是6.x tokens/s 符合预期

**Comment by zlh1992** [comment]
closed

**Comment by oho-work** [comment]
感谢感谢，及时雨般的Issues

**Comment by ArlanCooper** [comment]
> 已解决： pip install transformers==4.34.0 pip install auto-gptq==0.4.2 pip install peft==0.5.0 pip install optimum==1.13.3
> 
> ![image](https://private-user-images.githubusercontent.com/39059487/290446866-1f66e177-8167-4ad6-964d-361e0aaf4231.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzE0ODYsIm5iZiI6MTcwNjE3MTE4NiwicGF0aCI6Ii8zOTA1OTQ4Ny8yOTA0NDY4NjYtMWY2NmUxNzctODE2Ny00YWQ2LTk2NGQtMzYxZTBhYWY0MjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA4MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjYzNWZhNjQzNzEyM2U4OTQyMzIwZjI4ZGM3M2MyYTQxYmZlOTE0YzhmMDVmOWIxOGRjNDhlYTQzODllYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3bolsqoOtZVOFtGOUZ3EUhryVrMjr902jgbovqzvxPw)
> 
> 实测大概是6.x tokens/s 符合预期

我这边，设置成一样的配置为什么不可以呢？
我这边torch版本是torch                         2.1.2+cu118
