### ISSUE TITLE
[BUG] A100单卡推理，GPU使用率只有30%

### ISSUE THREAD

**Issue by mechigonft** [QwenLM/Qwen#801]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

A100单卡推理，GPU使用率只有30%

### 期望行为 | Expected Behavior

A100单卡推理，GPU使用率只有30%

### 复现方法 | Steps To Reproduce

A100单卡推理，GPU使用率只有30%

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
什么模型、什么运行环境。如果是transformers，参考REAMDE中的测速看下速率是否符合预期。如果不是transformers的，建议用FastChat+vLLM试试看会不会有改善。

**Comment by jklj077** [comment]
Closed due to lack of information.
