### ISSUE TITLE
[BUG] <title>模型GPTQ 4bit量化后，加载模型推理报错AttributeError: 'GenerationConfig' object has no attribute 'chat_format'，已搜索相关讨论，无法解决问题

### ISSUE THREAD

**Issue by sunyclj** [QwenLM/Qwen#805]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

报错详细信息：
File "lora_inf.py", line 211, in quantization_inf
    response, history = model.chat(tokenizer, '你是谁', history=None, max_new_tokens=1024)
  File "/root/.cache/huggingface/modules/transformers_modules/qwen_7b_chat_q2/modeling_qwen.py", line 1177, in chat
    assert generation_config.chat_format == 'chatml', _ERROR_BAD_CHAT_FORMAT
AttributeError: 'GenerationConfig' object has no attribute 'chat_format'

量化后权重实际位置在./qwen_7b_chat_q2文件夹下面，但是在推理过程中加载/root/.cache/huggingface/modules/transformers_modules/qwen_7b_chat_q2/文件夹下面的modeling_qwen.py，当我把该文件夹下modeling_qwen.py中assert generation_config.chat_format == 'chatml', _ERROR_BAD_CHAT_FORMAT注释掉重新推理时，报相同的错误，重新检查/root/.cache/huggingface/modules/transformers_modules/qwen_7b_chat_q2/modeling_qwen.py，已被修改，assert generation_config.chat_format == 'chatml', _ERROR_BAD_CHAT_FORMAT没有被注释。
请问怎么解决呢？

**Comment by jklj077** [comment]
这个最好是去改generation_config.json里面加上`"chat_format": "chatml"`这一项。

**Comment by jklj077** [comment]
我们已在README中添加了模型量化的有关说明，建议直接复制对应官方模型的config覆盖autogptq产出的config，请尝试下看看。

**Comment by xiaoduozhou** [comment]
我是transformers 版本太低了，导致出现这个bug, 升级transformer 就解决了， 模型里面文件 generation_config.json 配置里面有"transformers_version": "4.36.2" ， 我本地的版本是 4.26 的， 导致配置取不到，升级后解决
