### ISSUE TITLE
Qwen-72B输入11k以后报错，11k以下不报，是什么问题？

### ISSUE THREAD

**Issue by piaoxiaobo** [QwenLM/Qwen#807]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen-72B输入11k以后报错，11k以下不报错
![image](https://github.com/QwenLM/Qwen/assets/34496544/34fee9bc-fdc9-4534-a0e2-a7105cdf57f3)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
这个看着是生成崩溃了，采样到了不在实际词表中的token。
用的transformers还是vllm，dynamic_ntk有没有开，有没有调超参，比如temperature什么的。

**Comment by TangMoming** [comment]
在部署使用Qwen-72B大模型时遇到了一些问题：
尝试使用2*A100 80G进行Qwen-72B-Chat模型的部署
   在vllm部署时：
    a). 当输入的token数量超过3000时，模型会显示以下提示：“Input prompt (3916 tokens) is too long and exceeds the capacity of block_manager”。
    b). 当输入的字符数为1500时：
    ```
    llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 33.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 82.6%, CPU KV cache usage: 0.0%
    ```
    之后进入等待状态。即使在使用4*A100后，问题依然没有得到解决。

所使用的vllm版本为最新版本，transformers版本为4.36.2。

VLLM的启动命令如下：
python -m vllm.entrypoints.openai.api_server \
--model model_path \
--dtype auto \
--max-model-len 8192 \
--tensor-parallel-size 2 \
--max-num-batched-tokens 8192 \
--max-paddings 8192 \
--enforce-eager \
--trust-remote-code 
```
在此，我想请教如何才能够达到（[https://modelscope.cn/studios/qwen/Qwen-72B-Chat-Demo/summary）中展示的推理速度。](https://modelscope.cn/studios/qwen/Qwen-72B-Chat-Demo/summary%EF%BC%89%E4%B8%AD%E5%B1%95%E7%A4%BA%E7%9A%84%E6%8E%A8%E7%90%86%E9%80%9F%E5%BA%A6%E3%80%82)
