### ISSUE TITLE
[BUG] <title>TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Sandraven0** [QwenLM/Qwen#809]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

<img width="900" alt="lQLPJxl8kBiI0H_NAmjNBwewp-11-zxur2AFY6fXTOSFAQ_1799_616" src="https://github.com/QwenLM/Qwen/assets/150705795/c5753617-20a1-4100-a147-817135550ca9">
按照教程，运行微调指令应该输入sh finetune/finetune_qlora_single_gpu.sh
<img width="692" alt="1" src="https://github.com/QwenLM/Qwen/assets/150705795/bbcd9041-da5a-4083-88ac-37412cacb0ab">
但我输入这条指令会报错："finetune/finetune_qlora_single_gpu.sh: 10: Syntax error: "(" unexpected"
所以改为：
bash finetune/finetune_qlora_single_gpu.sh
运行后如图片中报错，不确定是否是文件格式问题，希望制作组新增一个微调用的示例数据集或者更详细的微调数据生成代码

### 期望行为 | Expected Behavior

执行微调正常运行

### 复现方法 | Steps To Reproduce

按照教程配置环境平且测试Qwen/Qwen-14B-Chat-Int4问答
bash finetune/finetune_qlora_single_gpu.sh

### 运行环境 | Environment

```Markdown
- OS:Ubuntu20.04
- Python:Python 3.10
- Transformers:
- PyTorch:Pytorch 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): CUDA11.8, cuDNN 8
```

### 备注 | Anything else?

用于微调的.json格式如下
<img width="715" alt="lQLPKGVzv3BY0H_NAWTNBZawKWXWTpSuhV8FY6fXTOSFAA_1430_356" src="https://github.com/QwenLM/Qwen/assets/150705795/9ee04f92-19d9-4b78-8a55-688acbcfacc7">

**Comment by jklj077** [comment]
看着是训练数据格式不对，多了一级列表
```json
[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      },
      {
        "from": "assistant",
        "value": "我是一个语言模型，我叫通义千问。"
      }
    ]
  },
  {
    "id": "identity_1",
    "conversations": [
      {
        "from": "user",
        "value": "xxx"
      },
      {
        "from": "assistant",
        "value": "xxx"
      }
    ]
  }
]
```

**Comment by GXKIM** [comment]
> 看着是训练数据格式不对，多了一级列表
> 
> ```json
> [
>   {
>     "id": "identity_0",
>     "conversations": [
>       {
>         "from": "user",
>         "value": "你好"
>       },
>       {
>         "from": "assistant",
>         "value": "我是一个语言模型，我叫通义千问。"
>       }
>     ]
>   },
>   {
>     "id": "identity_1",
>     "conversations": [
>       {
>         "from": "user",
>         "value": "xxx"
>       },
>       {
>         "from": "assistant",
>         "value": "xxx"
>       }
>     ]
>   }
> ]
> ```

我也是同样的qlora报错
