### ISSUE TITLE
[BUG] 使用8*3090显卡加载qwen-72B-chat报显存OOM, 到底要多少显存才能加载?

### ISSUE THREAD

**Issue by qiufengyuyi** [QwenLM/Qwen#811]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

try to load qwen-72 with AutoModelForCausalLM.from_pretrained() and different type of device_map(auto,balanced,balanced_low_0) it also has oom Problem with 8\*3090(8\*24G=192G),but how could it happened? the model should not need more than 196G memory

### 运行环境 | Environment

```Markdown
- OS:
- Python: 3.10.13
- Transformers:4.35.2
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):cuda 11.8
```

**Comment by RougeWhite** [comment]
你把模型分配到多gpu上了吗？
看看你引入模型的代码部分

**Comment by frankang** [comment]
尝试使用deepspeed3加载模型, 或者参考 https://huggingface.co/docs/accelerate/concept_guides/big_model_inference 来自定义modules的分配策略。
用transformers 的 `device_map = 'auto'`方式可能不能够均匀地分配某些层，导致单卡需要的显存过大。
