### ISSUE TITLE
💡 [REQUEST] - <title>微信群从那里加入？

### ISSUE THREAD

**Issue by coderLinJ5945** [QwenLM/Qwen#816]
### 起始日期 | Start Date

信群从那里加入？

### 实现PR | Implementation PR

信群从那里加入？

### 相关Issues | Reference Issues

信群从那里加入？

### 摘要 | Summary

信群从那里加入？

### 基本示例 | Basic Example

信群从那里加入？

### 缺陷 | Drawbacks

信群从那里加入？

### 未解决问题 | Unresolved questions

信群从那里加入？

**Comment by jklj077** [comment]
README中有链接的

![image](https://github.com/QwenLM/Qwen/assets/17811943/d1eed2d0-0475-402f-a40d-d1ce0cc529d4)
