### ISSUE TITLE
[BUG] <title>用fastchat起的openai server没有function calling能力

### ISSUE THREAD

**Issue by YCG09** [QwenLM/Qwen#817]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用vLLM和类OpenAI接口进行推理时，通过以下方式起的openai server没有function calling能力，用自带的openai_api.py起的server正常
python -m fastchat.serve.controller
python -m fastchat.serve.vllm_worker --model-path Qwen/Qwen-72B-Chat --trust-remote-code --tensor-parallel-size 2 --gpu-memory-utilization 0.98 --dtype bfloat16
python -m fastchat.serve.openai_api_server --host localhost --port 8000

### 运行环境 | Environment

```Markdown
- OS:Rocky8.8
- Python:3.10
- Transformers:4.36.1
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jklj077** [comment]
这是个已知的问题：
- <https://github.com/QwenLM/Qwen/issues/389>

function call支持是本项目中openai_api.py按Qwen的方法定制实现的，用的特定的template。这个方案是不通用的，FastChat目前不支持。

FastChat的issue中有一个workround，可以参考看看：
- <https://github.com/lm-sys/FastChat/issues/2425#issuecomment-1855747536>
