### ISSUE TITLE
vllm 运行Qwen-72B-Chat 报OOM错误。

### ISSUE THREAD

**Issue by SPY-Ming** [QwenLM/Qwen#819]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我拷贝的官方的代码，在8块4090（24G）服务器上，部署Qwen-72B-Chat。报错：
untimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(RayWorkerVllm pid=74362) INFO 12-18 21:44:36 model_runner.py:394] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorkerVllm pid=74362) [W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator()) [repeated 7x across cluster]

我不使用vLLM时，是可以运行推理的。很好奇这是怎么回事，应该怎么解决呢？

### 运行环境 | Environment

```Markdown
- OS:Ubuntu
- Python:3.9
- Transformers:
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by jklj077** [comment]
是很奇怪，具体用的哪部分代码呀，是vLLM wrapper还是FastChat+vLLM呢？

**Comment by jklj077** [comment]
最近几天vLLM更新了，默认开了CUDA Graph...
这个是最新vLLM官方的警示
```
CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing gpu_memory_utilization` or enforcing eager mode."
```

恢复之前的行为需要传入`--enforce_eager`。

**Comment by Tsukumizu** [comment]
> 最近几天vLLM更新了，默认开了CUDA Graph... 这个是最新vLLM官方的警示
> 
> ```
> CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing gpu_memory_utilization` or enforcing eager mode."
> ```
> 
> 恢复之前的行为需要传入`--enforce_eager`。

您好，我是Fastchat+vLLM，4张A100-40G，一直能正常推理，现在直接chat也可以，但使用了fastchat+vllm后会memory不够。请问也是这个原因吗

**Comment by kidd20172017** [comment]
@jklj077 请问这个参数在哪里传入
