### ISSUE TITLE
💡 [REQUEST] 请问您团队有开源增量预训练的脚本的计划么?

### ISSUE THREAD

**Issue by xinlaid** [QwenLM/Qwen#821]
### 实现PR | Implementation PR

1. 请问您团队有开源增量预训练的脚本的计划么？ 我在已经开源的部分中没有找到pretrained的相关脚本，对于垂直领域的知识拓展没有一个更合适的方法，所以冒昧的提出这个问题，抱拳 @

### 摘要 | Summary

pretrained的相关脚本

### 基本示例 | Basic Example

pretrained的相关脚本

### 缺陷 | Drawbacks

pretrained的相关脚本

**Comment by jklj077** [comment]
是有相关的计划，但短期内应该是支持不上了。考虑到增量预训练的数据量一般会比SFT要多很多，要达到可用状态有些工作量。

我们发现网上也有些相关的资料，比如
- https://help.aliyun.com/zh/pai/use-cases/train-fine-tune-and-deploy-qwen-by-using-intelligent-computing-lingjun?spm=a2c4g.11186623.0.i1

但这种我们都没测试过，仅供参考了。

相关问题：
- https://github.com/QwenLM/Qwen/issues/479
