### ISSUE TITLE
请问8台V100 * 32G能跑14B的全参数增量预训练吗？

### ISSUE THREAD

**Issue by childlong** [QwenLM/Qwen#825]
### 摘要 | Summary

请问8台V100 * 32G能跑14B的全参数增量预训练吗？

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
多机、多卡下的显存占用，DeepSpeed有一个**预估**ZeRO-2/ZeRO-3下存储最低需求的功能（实际还跟batch size、序列长度等有关），可以参考看看
- https://huggingface.co/docs/transformers/v4.36.1/zh/main_classes/deepspeed#%E5%86%85%E5%AD%98%E8%A6%81%E6%B1%82
- https://deepspeed.readthedocs.io/en/latest/memory.html

P.S.：目前本repo提供的finetune脚本还不支持多机和增量预训练。

**Comment by tomFoxxxx** [comment]
不够，8 * A100（40G）是门槛。
