### ISSUE TITLE
[BUG] <14B模型启动报错>

### ISSUE THREAD

**Issue by sparkjune** [QwenLM/Qwen#826]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我的集群是6*16的 A100 GPU，按照流程搭建之后（没有集成flash_attention），执行推理的demo的时候，
![image](https://github.com/QwenLM/Qwen/assets/106476831/6941a4e7-5d9a-4944-92c1-ca99940cae87)
如上demo，报错为：
![image](https://github.com/QwenLM/Qwen/assets/106476831/ca61073d-bdbd-453c-a670-0c0803c145a1)
。我并没有在issue中找到相关的讨论，因此独立提了一个。辛苦哪位如果碰到这个问题请指点一下。感谢感谢

### 期望行为 | Expected Behavior

期望是可以正常运行这个14B的大模型

### 复现方法 | Steps To Reproduce

OS:linux
Python:3.9
Transformers:4.32.0
Pytorch:2.1.2
CUDA:11.8

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

无

**Comment by jklj077** [comment]
这个问题似乎比较复杂。我们能够在调整temperature的情况下复现该问题，所以建议避免调整temperature。不过有更多的用户报告未调整temperature时也出现了该问题，可能与环境配置有关，但我们未能复现。

相关问题：
- https://github.com/QwenLM/Qwen/issues/620 (反馈更新显卡驱动或更新transformers可解决)
- https://github.com/QwenLM/Qwen/issues/711 (反馈单卡运行可解决)
- https://github.com/QwenLM/Qwen/issues/815

如果怀疑环境配置问题，可以尝试使用下我们提供的docker镜像，详见[README中相关部分](https://github.com/QwenLM/Qwen#-docker)。

**Comment by jklj077** [comment]
目前看符合多卡、未修改配置的条件，大概率与<https://github.com/QwenLM/Qwen/issues/848>同样问题，请移步讨论。如非同一问题，请重新开启。
