### ISSUE TITLE
[BUG] what does "seq_length": 2048 in the config file mean? can i ｍodify it to 8192?

### ISSUE THREAD

**Issue by meichangsu1** [QwenLM/Qwen#827]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS
- Python:
- Transformers:
- PyTorch:12.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
`seq_length` is used in `modeling_qwen.py` to set correct factors for logn and dynamic ntk. It is supposed to record the maximum length encountered in training (currently, for different models, `seq_length` is different). You should not change it; otherwise, the long context support may broke.

If you would like to try on longer context, you can change max_position_embeddings. However, the performance on context longer than what is supported may be undesirable.

Related:
- https://github.com/QwenLM/Qwen/issues/540#issuecomment-1784934728

**Comment by meichangsu1** [comment]
> `seq_length` is used in `modeling_qwen.py` to set correct factors for logn and dynamic ntk. It is supposed to record the maximum length encountered in training (currently, for different models, `seq_length` is different). You should not change it; otherwise, the long context support may broke.
> 
> If you would like to try on longer context, you can change max_position_embeddings. However, the performance on context longer than what is supported may be undesirable.
> 
> Related:
> 
> * [14B 模型 config 中的 seq_length 是什么含义？ #540 (comment)](https://github.com/QwenLM/Qwen/issues/540#issuecomment-1784934728)

我如果使用vllm推理，这个值可以修改吗？

**Comment by jklj077** [comment]
你的问题不在改不改这个值，而是vLLM怎么支持Qwen长序列。

1. vLLM调整支持的序列长度的方式，是启动时传`--max-model-len`
2. vLLM对Qwen的长序列扩展支持是不完善的，目前用长序列可能会崩溃、或效果不符合预期
3. vLLM中有两个PR，需要期待vLLM合并
   - https://github.com/vllm-project/vllm/pull/1746
   - https://github.com/vllm-project/vllm/pull/1860

P.S.: 我们建议使用FastChat+vLLM，vLLM本身对Qwen的对话格式支持有限，可以参考README中说明。

**Comment by meichangsu1** [comment]
> 1. --max-model-len 在目前最新的版本中0.2.6中是不起作用的，它取了max_positon_embeddings和seq_length的最小值

**Comment by jklj077** [comment]
现在的vLLM版本要用，那就在config.json里配置`rope_scaling`
```json
{
  "rope_scaling": { 
    "type": "dynamic", 
    "factor": max-model-len/seq_length
  }
}
```

我们重申现在的vLLM不支持Qwen长序列，不建议这么配置。

**Comment by meichangsu1** [comment]
> 现在的vLLM版本要用，那就在config.json里配置`rope_scaling`
> 
> ```json
> {
>   "rope_scaling": { 
>     "type": "dynamic", 
>     "factor": max-model-len/seq_length
>   }
> }
> ```
> 
> 我们重申现在的vLLM不支持Qwen长序列，不建议这么配置。

好
