### ISSUE TITLE
<help> 请问大家有qwen72B 全参数微调完成的吗？

### ISSUE THREAD

**Issue by txy6666yr** [QwenLM/Qwen#828]
我使用LLaMA-Factory 项目全参数微调 loss 异常，没有使用官方的代码微调，请问大家有微调成功的吗？
![training_loss](https://github.com/QwenLM/Qwen/assets/48319137/7eab4662-9ef1-484f-9722-25f811900972)

**Comment by xx-Jiangwen** [comment]
请问下你全参数微调的服务器配置是什么情况呢？

**Comment by txy6666yr** [comment]
> 请问下你全参数微调的服务器配置是什么情况呢？

8机8卡 都是A100 80G  deepspeed zero 3

**Comment by LMXKO** [comment]
用官方代码全参微调成功了

**Comment by txy6666yr** [comment]
> 用官方代码全参微调成功了

请问是使用多机多卡微调的吗？
