### ISSUE TITLE
[BUG] 系统指令没有用

### ISSUE THREAD

**Issue by YeQiuO** [QwenLM/Qwen#830]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

快排是一种常见的排序算法，其基本思想是通过一趟排序将待排记录分隔成独立的两部分，其中一部分记录的关键字均比另一部分的关键字小，然后再按此方法对这两部分记录分别进行快速排序，整个排序过程可以递归进行，以此达到整个序列有序。

以下是一个使用Python编写的快排代码示例：

```python
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)
```

在这个代码中，我们首先检查列表的长度是否为1或0。如果是，我们就直接返回该列表，因为只有一个元素或没有元素的列表已经是有序的了。然后我们选择一个中间元素作为基准值（pivot），并将列表分为三部分：小于基准值的部分、等于基准值的部分和大于基准值的部分。最后，我们递归地对小于基准值的部分和大于基准值的部分进行快速排序，并将结果与等于基准值的部分合并起来，从而得到最终的有序列表。

### 期望行为 | Expected Behavior

拒绝回答

### 复现方法 | Steps To Reproduce

from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

tokenizer = AutoTokenizer.from_pretrained("Qwen-1_8B-Chat", trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained("Qwen-1_8B-Chat", trust_remote_code=True, device_map="auto").eval()

response, _ = model.chat(tokenizer, "怎么写快排代码？", history=None, system="拒绝回答所有代码相关的问题")

### 运行环境 | Environment

```Markdown
OS: Ubuntu 22.04
Python: 3.10
Transformers: 4.31.0
PyTorch: 2.0.1
CUDA: 11.6
```

**Comment by JustinLin610** [comment]
1.8能力有限是一方面，另外系统指令还需要更明确的说明，尤其这类拒绝回答的指令不像角色扮演那么好遵循。下面是72B的例子：

![image](https://github.com/QwenLM/Qwen/assets/27664428/5f9921ab-aae3-4f20-ae35-9387a8d9b74b)

1.8的尝试还需试试多优化prompt，小模型的指令遵循能力有限
