### ISSUE TITLE
[BUG] Lora 微调 14B 模型后，转GPTQ 量化模型后，vLLM方式运行，有5%的概率，返回为 空字符串

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#831]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Lora 微调 14B 模型后，转GPTQ 量化模型后，vLLM方式运行，有5%的概率，返回为空字符串。

使用 https://github.com/PanQiWei/AutoGPTQ?tab=readme-ov-file 这里给出的量化代码进行的量化。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
请对应寻求AutoGPTQ或者vLLM社区中的帮助。

以下有助于您更高效的定位问题：
1. 使用量化前的模型是否有该现象
   1. 如没有，可能量化过程有问题，可以额外寻求AutoGPTQ社区的帮助
   2. 如有，请检查训练数据格式；是否训练序列长度设置的的太短，数据被截断；是否推理时输入过长，未预留输出的空间；如果使用vLLM，是否按推荐采用了FastChat+vLLM
2. 使用量化后的模型，但不使用vLLM是否有该现象
   1. 如没有，可以额外寻求vLLM社区的帮助
   2. 如有，可能量化过程有问题，见1.1

**Comment by micronetboy** [comment]
使用量化前的模型是正常的，没有这个问题

**Comment by jklj077** [comment]
https://github.com/QwenLM/Qwen/issues/849

请看下是否与该issue一样是长度问题。
