### ISSUE TITLE
💡 [REQUEST] - 请求把GPTQ的量化脚本开源出来，我们在微调后，量化为GPTQ模型后，存在各种问题

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#832]
### 摘要 | Summary

无

### 基本示例 | Basic Example

请求把GPTQ的量化脚本开源出来，我们在微调后，量化为GPTQ模型后，存在各种问题。
我们使用了 https://github.com/PanQiWei/AutoGPTQ/blob/main/README_zh.md 里给的例子进行的量化。

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
README中已添加了有关说明，可以试试看。
