### ISSUE TITLE
💡 [REQUEST] - vLLM 部署时会占用整个显存，这个有办法限制吗？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#835]
### 摘要 | Summary

vLLM 部署时会占用整个显存，这个有办法限制吗？比如限制只占用 50 % 的显存

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
https://docs.vllm.ai/en/latest/models/engine_args.html#cmdoption-gpu-memory-utilization
