### ISSUE TITLE
[BUG] <title>7B昇腾推理较A卡性能效果均劣化

### ISSUE THREAD

**Issue by whatever-wlb** [QwenLM/Qwen#836]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

作者您好，按照教程对sft后的7B模型转昇腾卡后，推理的效果和性能均有明显劣化，昇腾卡性能如下图：
![image](https://github.com/QwenLM/Qwen/assets/114503311/2f93ee74-af63-4781-a7e1-ca5fb9e87601)
A卡的性能约 10.11tokens/s
A卡可以输出符合预期的答案，但是昇腾卡推理输出会带有输入的内容，同时会出现重复的内容
请问你们实验时是否有类似情况
是否有相应解决方案

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
具体运行的是多大的模型？

**Comment by whatever-wlb** [comment]
7B模型

**Comment by ZhenfengLi** [comment]
你好，请问你是按照哪个文档在华为升腾上推理qwen7b的。可以指教一下吗？谢谢

**Comment by zhci** [comment]
同问，请问是哪个文档啊，可以请教一下嘛

**Comment by whatever-wlb** [comment]
https://github.com/QwenLM/Qwen/tree/main/ascend-support

> 你好，请问你是按照哪个文档在华为升腾上推理qwen7b的。可以指教一下吗？谢谢

https://github.com/QwenLM/Qwen/tree/main/ascend-support

**Comment by whatever-wlb** [comment]
> 你好，请问你是按照哪个文档在华为升腾上推理qwen7b的。可以指教一下吗？谢谢

https://github.com/QwenLM/Qwen/tree/main/ascend-support

**Comment by JucksonP** [comment]
我也有同样的问题，在昇腾910卡上推理会带有输入的内容，同时会出现重复的内容

**Comment by jklj077** [comment]
The Ascend support relies on the `mindformers` implementation. Please take a look at <https://gitee.com/mindspore/mindformers/blob/dev/research/qwen/qwen.md> for the latest instructions. (Its GitHub repo is out of sync currently.)

We have let the maintainers at mindformers know the issues and hopefully, they have fixed it. If you still encounter unexpected behaviour, directly reporting to them could be more efficient.

**Comment by tammypi** [comment]
使用710B mindie运行14b模型，性能相比于nvidia l20(使用了vllm+flash-attn)，性能下降了5倍？请问有什么好的解决办法吗？
