### ISSUE TITLE
How to use Qwen using HuggingFace PEFT for finetuning with a QA Dataset?

### ISSUE THREAD

**Issue by vabatista** [QwenLM/Qwen#838]
Hi,

I have a QA dataset in SQuAD format: (context, question, answer) triples. How to finetune Qwen with this dataset using HuggingFace PEFT (https://huggingface.co/docs/peft/main/en/index) library?

When I use Bitsandbytes to quantize, I'm having several issues. I'm trying to reproduce this code that works with LLaMA2, but without success: https://medium.com/@ud.chandra/instruction-fine-tuning-llama-2-with-pefts-qlora-method-d6a801ebb19

**Comment by jklj077** [comment]
Hi,

In this repository, there is a file named finetune.py that also utilizes PEFT and supports LoRA/QLoRA. QLoRA, in particular, works with AutoGPTQ-quantized models, so you don't need to perform quantization again. The dataset format may slightly differ from the SQuAD format, but it should be acceptable to use (context, question) as the query and the answer as the response.

You are welcome to examine the script as a basic reference example and build your own methods upon it.
