### ISSUE TITLE
官方的dokcer镜像推理速度比物理机直接推理慢至少6、7倍。

### ISSUE THREAD

**Issue by haowuliao** [QwenLM/Qwen#843]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在ubuntu16，62g内存，单张4090上，同样的参数设置，比较了使用和不使用qwenllm/qwen:latest镜像的推理速度，经过测试发现，docker镜像中的推理速度明显更慢，比不使用慢至少6-7倍。

### 期望行为 | Expected Behavior

希望知道是哪些原因导致的差异，如果想要优化docker中的推理速度，需要做出哪些调整

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 16
- Python: 3.9
- Transformers: 4.32.1
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.2
- rtx 4090
```

**Comment by fyabc** [comment]
您好，可以提供一下推理时的日志吗（使用`docker logs`查看）？另外可以检查一下容器是否正确挂载了GPU。

**Comment by haowuliao** [comment]
![d243e49412f57aad3438b5a6c4b9d5f](https://github.com/QwenLM/Qwen/assets/21007668/a3308ad7-13a6-4915-8a56-46257c758e08)

我看了一下显存占用情况，确实通过docker加载模型，显存占用也增加了，应该是正确挂载了gpu

**Comment by logda** [comment]
问题解决了吗？遇到一样的问题了。
用的是Qwen-72B-Chat-Int8版本的模型，比较了使用和不使用qwenllm/qwen:latest镜像的推理速度，经过测试发现，docker镜像中的推理速度明显更慢，比不使用慢至少6-7倍。

**Comment by fyabc** [comment]
@haowuliao @logda 您好，这个是docker镜像中auto-gptq版本不正确导致没有正确安装auto-gptq的CUDA扩展，目前dockerhub上最新的镜像已修复此问题，您可以拉取镜像再重新尝试一下。

**Comment by chenhaoqiang** [comment]
> @haowuliao @logda 您好，这个是docker镜像中auto-gptq版本不正确导致没有正确安装auto-gptq的CUDA扩展，目前dockerhub上最新的镜像已修复此问题，您可以拉取镜像再重新尝试一下。

我试了下，确实快了很多！！！

**Comment by haowuliao** [comment]
应该确实是内部版本问题，速度快了很多 。😺
