### ISSUE TITLE
subprocess.CalledProcessError: Command '['hostname -I']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by yd-53** [QwenLM/Qwen#844]
安装了deepspeed，然后来训练qlora,出现了以下问题：
![image](https://github.com/QwenLM/Qwen/assets/55195733/1093300b-d264-413e-a62d-d2afe1779ab7)
模型：Qwen-7B-Chat-Int4；    
DeepSpeed版本：0.12.7；   
peft版本：0.7.1；   
python版本：3.10；  
cuda：12.1；  
pytorch：2.1.1；  
torch：2.1.2+cu121；

**Comment by jklj077** [comment]
你是Windows吗? DeepSpeed不支持Windows训练。

**Comment by yd-53** [comment]
> 你是Windows吗？DeepSpeed不支持Windows训练。

哦哦，好的吧，我是windows,尴尬打扰了。。我是因为看到下面那段话，以为必须要deepspeed哈哈
![image](https://github.com/QwenLM/Qwen/assets/55195733/d282f59e-ad22-435b-af57-cc6700a35dd2)

**Comment by jklj077** [comment]
哦哦，QLoRA目前是必需得结合DeepSpeed…… 模型开发还是建议用linux系统呢

**Comment by yd-53** [comment]
> 哦哦，QLoRA 目前是简单得结合 DeepSpeed…… 模型开发还是建议用linux系统呢

啊 这这这，那在windows里，没有用deepspeed，微调出来的模型是有用的吗

**Comment by jklj077** [comment]
如果用QLoRA没开DeepSpeed，代码会报错的（还不是你这个错误，是另外的错误），微调不了的。

**Comment by yd-53** [comment]
？？所以这样的不算训练成功吗？
![image](https://github.com/QwenLM/Qwen/assets/55195733/1ee75798-b6ff-4c80-8c71-6ea1a8e245cc)
![image](https://github.com/QwenLM/Qwen/assets/55195733/a7308412-ddb0-4799-8dc1-9fd246f28fc3)

**Comment by yd-53** [comment]
> 如果用QLoRA没开DeepSpeed，代码会报错的（还不是你这个错误，是另外的错误），微调不了的。

？？ 所以这样的不算训练成功吗？
![image](https://github.com/QwenLM/Qwen/assets/55195733/d08c4df5-0326-4a7d-9266-3541842c8af5)
![image](https://github.com/QwenLM/Qwen/assets/55195733/6f53bf1a-d946-4fb5-a661-4a619b129622)

**Comment by jklj077** [comment]
emm... 如果没报错的话，建议测测训好的模型，如果正常的话就能用。

是把--deepspeed finetune/ds_config_zero2.json删掉了对吧？这样的话finetune.py里还是会用DS的分布式后端来起单进程，按理说DS在Windows上是不支持训练的。但既然能正常运行，那可能是没碰上不支持的功能。如果结果正常，我理解用是没问题的。

**Comment by yd-53** [comment]
> emm...如果没报错的话，建议测测训练好的模型，如果正常的话就可以用。
> 
> 是把--deepspeedfinetune/ds_config_zero2.json删掉了对吧？还是这样的话finetune.py里会用DS的左边来起单进程，按理说DS在Windows上是不支持训练的。但现在能正常运行，那可能是没碰上不支持的功能。如果结果正常，我理解是没问题的。

![image](https://github.com/QwenLM/Qwen/assets/55195733/4b4da3c0-072c-4aeb-9d92-3b29bccd6aec)
![image](https://github.com/QwenLM/Qwen/assets/55195733/e38cebde-d41e-4512-924d-76c11b20ed43)
嗯嗯，是的，我把--deepspeedfinetune/ds_config_zero2.json注释掉了，然后训练出来的qlora能用
