### ISSUE TITLE
VLLM  是否不支持qwen-14B-int4的函数回调

### ISSUE THREAD

**Issue by laitianan** [QwenLM/Qwen#845]
测试官方代码：https://github.com/QwenLM/Qwen/blob/main/examples/function_call_examples.py  中的test2 跟test3 都如下错误：
![image](https://github.com/QwenLM/Qwen/assets/12150016/810d5ef5-f4a7-4a1d-846c-3267a0cd1f3a)

**Comment by jklj077** [comment]
是的，vLLM或FastChat+vLLM都还不支持function call。

相关问题回复：
- https://github.com/QwenLM/Qwen/issues/817#issuecomment-1859912461
