### ISSUE TITLE
💡 [REQUEST] - 您好，我运行 14B-int4 量化模型要比 14B原始模型速度要慢？这个是什么原因？理论上量化模型应该更快？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#850]
### 摘要 | Summary

 您好，我运行 14B-int4 量化模型要比 14B原始模型速度要慢？这个是什么原因？理论上量化模型应该更快？
 运行环境：A100 80G

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
> 理论上量化模型应该更快？

理论上，量化模型显存占用更小，但因为多了反量化操作，理论运算量增加，一般而言，速度要更慢。
由于影响速度的不只是理论运算量，还有算法并行度、IO瓶颈等因素，GPTQ方案能够加速是因为针对特定场景的算子优化。

> 运行 14B-int4 量化模型要比 14B原始模型速度要慢？这个是什么原因？

参考README中的测速结果，14B-int4相比于14B也没有快很多（但这个是autogptq官方的数值，README表下面有说明，transformers加载的话，实际速度可能会慢20%），实测速度更慢是很有可能的。

如果仍认为速度有问题，建议提供以下信息
- 实际慢多少
- 什么框架测试的，transformers还是vLLM
- 如果是transformers加载的，autogptq是否开启了exllama（如果有，可以开启看看速度），是否有cuda extension not installed的警告（如果有，需要按AutoGPTQ官方说明安装合适的编译版本，或者自行编译）
