### ISSUE TITLE
[BUG] pull了最新的14b模型相同的代码微调后loss相对之前的高了不少，请问是做了什么改动吗

### ISSUE THREAD

**Issue by boundles** [QwenLM/Qwen#855]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
> 请问是做了什么改动吗？

14B的话，模型参数是没有更新的，相关代码上有一些模型间统一的变化，主要是速度相关的优化。这部分变动应该不会影响训练结果才对，方便说下loss大概高了多少吗？

**Comment by boundles** [comment]
> > 请问是做了什么改动吗？
> 
> 14B的话，模型参数是没有更新的，相关代码上有一些模型间统一的变化，主要是速度相关的优化。这部分变动应该不会影响训练结果才对，方便说下loss大概高了多少吗？

之前训练完的loss大概是0.001x，现在试了几次是0.03x

**Comment by Hazards10** [comment]
能问下用多少配置的服务器跑的，谢谢
