### ISSUE TITLE
[BUG] Try using vLLM for Qwen-72B-Chat-Int4, got NameError: name 'exllama_import_exception' is not defined

### ISSUE THREAD

**Issue by SL-Stone** [QwenLM/Qwen#856]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

In the vllm-gptq/tests/qwen/, Run `python test_qwen.py`, the llm was Qwen-72B-Chat-Int4, got the error "NameError: name 'exllama_import_exception' is not defined". Seems like some exllama-related packages not installed (but I have no idea how to deal with this).
在vllm-gptq/tests/qwen/目录下，运行`python test_qwen.py`，llm是Qwen-72B-Chat-Int4，报错。分析和版本不一致以及exllama有关。

### 期望行为 | Expected Behavior

How to fix this Error and use Qwen72B-Int4 with vLLM successfully? Many Thanks!
如何解决报错，成功运行vLLM加速后的 Qwen72B-Int4? 感谢！

### 复现方法 | Steps To Reproduce

1. In the repo https://github.com/QwenLM/vllm-gptq, enter the vllm-gptq/tests/qwen/
2. Run `python test_qwen.py`

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04.6 LTS \n \l
- Python: 3.11.0
- Transformers: 4.36.0
- torch: 2.0.1+cu118
[when I installed torch 2.1.2, the installation  of vLLM-GPTQ would raise error "The detected CUDA version (11.8) mismatches the version that was used to compile PyTorch (12.1)".]
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
- auto-gptq: 0.6.0+cu118
- vllm: vllm-gptq
```

### Detailed Error Information:

$ python test_qwen.py 

WARNING 12-23 14:35:36 config.py:140] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 12-23 14:35:36 llm_engine.py:72] Initializing an LLM engine with config: model='/home/ubuntu/Qwen-72B-Chat-Int4', tokenizer='/home/ubuntu/Qwen-72B-Chat-Int4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=gptq, seed=0)
WARNING 12-23 14:35:37 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
CUDA extension not installed.
CUDA extension not installed.
Traceback (most recent call last):
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/tests/qwen/test_qwen.py", line 7, in <module>
    vllm_model = vLLMWrapper(llm_model_dir,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/tests/qwen/vllm_wrapper.py", line 134, in __init__
    self.model = LLM(model=llm_model_dir,
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/engine/llm_engine.py", line 243, in from_engine_args
    engine = cls(*engine_configs,
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/engine/llm_engine.py", line 146, in _init_workers
    self._run_workers(
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/engine/llm_engine.py", line 737, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/engine/llm_engine.py", line 711, in _run_workers_in_batch
    output = executor(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/worker/worker.py", line 74, in load_model
    self.model = get_model(self.model_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/model_executor/model_loader.py", line 108, in get_model
    model.q4_init()
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/model_executor/models/qwen.py", line 292, in q4_init
    module.get_q4()
  File "/home/ubuntu/SSL/LLMs/vllm-gptq/vllm/model_executor/layers/linear.py", line 204, in get_q4
    q4 = ext_make_q4(
         ^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/qwen72int4/lib/python3.11/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllama.py", line 28, in ext_make_q4
    return make_q4(qweight,
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/qwen72int4/lib/python3.11/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllama.py", line 17, in error_raiser_exllama
    raise ValueError(f"Trying to use the exllama backend, but could not import the C++/CUDA dependencies with the following error: {exllama_import_exception}")
                                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'exllama_import_exception' is not defined

**Comment by jklj077** [comment]
vllm如果torch cuda不是最新版的有点难装，它会改很多依赖包的版本。
这个报错一般是autogptq的版本跟torch的cuda不匹配了，建议找个对应torch和cuda版本的autogptq安装下试试。

**Comment by hzhwcmhf** [comment]
@SL-Stone 可以尝试从源码重新安装autogptq试试，直接pip install会少编译一些cuda核

**Comment by SL-Stone** [comment]
> @SL-Stone 可以尝试从源码重新安装autogptq试试，直接pip install会少编译一些cuda核

嗯嗯，从GitHub官网上源码开始安装，安装成功了。是auto_gptq版本的问题，谢谢！

**Comment by SL-Stone** [comment]
> vllm如果torch cuda不是最新版的有点难装，它会改很多依赖包的版本。 这个报错一般是autogptq的版本跟torch的cuda不匹配了，建议找个对应torch和cuda版本的autogptq安装下试试。

对的，我原来的auto_gptq版本和我的pytorch不匹配，之后从auto_gptq官方源码开始安装的，顺利安装好了，和我pytorch 2.0.1匹配的是auto_gptq==0.7.0.dev0+cu118。谢谢！

**Comment by owenliang** [comment]
> > @SL-Stone 可以尝试从源码重新安装autogptq试试，直接pip install会少编译一些cuda核
> 
> 嗯嗯，从GitHub官网上源码开始安装，安装成功了。是auto_gptq版本的问题，谢谢！

一模一样，报错后auto-gptq源码pip install .了一下就好了，前一阵子还没问题，可能是vllm版本兼容性太乱给带跑偏了。
