### ISSUE TITLE
[BUG] <使用vllm+openaiAPI测试全参微调后的模型，回答混乱>

### ISSUE THREAD

**Issue by Modas-Li** [QwenLM/Qwen#858]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 备注 | Anything else?

![image](https://github.com/QwenLM/Qwen/assets/40042370/7dd1061c-8c92-445d-8b1c-33aa98f9311d)

**Comment by jklj077** [comment]
1. vLLM + OpenAI API：如果是单独vLLM，是没有完整支持Qwen对话模式的，建议用FastChat+vLLM。
2. chat调用参数格式不正确，请参考OpenAI API说明修正messages的格式。
   
   如果是单独的vLLM，还需要传入正确的stop_token_ids ([151643, 151644, 151645])

**Comment by Modas-Li** [comment]
> 1. vLLM + OpenAI API：如果是单独vLLM，是没有完整支持Qwen对话模式的，建议用FastChat+vLLM。
> 2. chat调用参数格式不正确，请参考OpenAI API说明修正messages的格式。
>    如果是单独的vLLM，还需要传入正确的stop_token_ids ([151643, 151644, 151645])

谢谢解答，请问stop_token_ids 如何传入，在哪里传入呢？谢谢~

**Comment by jklj077** [comment]
> 请问stop_token_ids 如何传入，在哪里传入呢？

加到POST的那个json里就可以。
