### ISSUE TITLE
[BUG] <相同模型在不同GPU上部署，跑出的结果不同，请教会是什么原因？>

### ISSUE THREAD

**Issue by ZYStone** [QwenLM/Qwen#861]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

相同模型在不同GPU上部署，跑出的结果不同，请教会是什么原因？是符合预期的吗？
比如同一个模型，在A100、A30上部署，相同的input，output不一致。正常来说这两个GPU都是同架构、同芯片，cuda的compute capability也相同。
![image](https://github.com/QwenLM/Qwen/assets/14831145/78f6bcc6-1734-407a-9340-fe79db694bfd)

### 期望行为 | Expected Behavior

同架构GPU，相同的模型、相同的input，output应一致。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ZYStone** [comment]
我们目前两个分析方向：
1. 不同硬件，浮点运算分配的pipeline不一定完全一致，有可能精度上有偏差导致最终结果不一样
2. 模型本身有没有类似于基于不同部署环境计算一个随机种子之类的参数？
请教下之前有没有遇到分析过类似的问题。

**Comment by Unintented** [comment]
温度？

**Comment by ZYStone** [comment]
> 温度？

为什么会和温度有关…

**Comment by ZYStone** [comment]
> 温度？

已经设为0了，跑的结果仍然不同

**Comment by jklj077** [comment]
> 相同模型在不同GPU上部署，跑出的结果不同，请教会是什么原因？是符合预期的吗？

看截图的话结果差的不太多，随机数生成器种子的影响会比这个大很多。

同一张卡多次生成的结果其实也有可能不一致。

这个可以看下PyTorch里的说明<https://pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms>，涉及到非确定性操作的话（比如量化模型用的kernel实现），是会有一些误差导致的波动。

Similar to/与以下类似：
- https://github.com/QwenLM/Qwen/issues/885
