### ISSUE TITLE
[BUG] fastchat-vllm的推理效果会变差且经常发生乱码 空白等现象

### ISSUE THREAD

**Issue by fungaegis** [QwenLM/Qwen#864]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用fastchat-vllm + qwen-14b-chat 进行推理 会比直接使用官方提供的openai-api.py 进行推理效果差很多

会出现
1. 乱码
2. 错漏
3. 空白
![image](https://github.com/QwenLM/Qwen/assets/52460251/44e3c48c-5186-459f-98c6-db55520a39df)

乱码
---

```w/40\n
``/''的<io' w
``s,config
```w''<w'
上述\w/   
``` \napp.c wns
```/57'
``w8
```\make/ws
```4
``w,cpu w/``/pc
w
```224
``w/serial/w
```w ',w/ '''/w3 w/ 运/ w
``.``.versions
``` w
``` 问题/ifi
``. ''/def
```w/isco
``w
``/obs
```s
``/xx
```/isc w/versions \n
```  <b
``.02
```< 然 w/45w
```<code
``` \n w
``/ {s/ <code
```w
``. <module
``` 0w
``` 代码
``.  w''/config/ssl
``.verified
```s
```w/s
``.versions w/def\ns/./se
``.，w ''' w/ 问题
``` <'
``` w/ [[w/ '''s/def w/
```
---

```
回复
```
和
+1\n' 以及
\n
```


Assistant\n
```的\n

#2\n
```
等

使用vllm, 是否需要调整什么配置, 我是直接使用默认的配置的

### 期望行为 | Expected Behavior

非乱码, 正常达到官方提供的openai-api.py的效果和能力

### 复现方法 | Steps To Reproduce

`python -m fastchat.serve.controller`

`python -m fastchat.serve.vllm_worker --model-path $model_path --trust-remote-code --dtype bfloat16`

`python -m fastchat.serve.openai_api_server --host localhost --port 8000`

### 运行环境 | Environment

```Markdown
- OS:ubuntu 20.04
- Python:3.10.10
- Transformers:4.35.2
- PyTorch: 2.1.0+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

### 备注 | Anything else?

另外想咨询下
当前使用fastchat-vllm是无法使用function_call的, 我应该如何做?
如何才能使用openai_api.py所带来的function_call能力?

谢谢

**Comment by jklj077** [comment]
请问输入一般有多长呀？非14B的，比如7B、1.8B会有这个问题吗？我们排除下相关因素。

**Comment by fungaegis** [comment]
> 请问输入一般有多长呀？非14B的，比如7B、1.8B会有这个问题吗？我们排除下相关因素。

5k token左右   其他参数量的模型 还没有试 这两天我试下

![image](https://github.com/QwenLM/Qwen/assets/52460251/f014d62f-eb60-4c38-892e-d0a90c3fcfd2)

基本上能正常使用的概率不到10%

**Comment by jklj077** [comment]
输入太长了哈，vllm目前支持不了这个长度。

参见：
- https://github.com/QwenLM/Qwen/issues/849#issuecomment-1867296778
- https://github.com/QwenLM/Qwen/issues/827
- https://github.com/QwenLM/Qwen/issues/658

**Comment by fungaegis** [comment]
> 输入太长了哈，vllm目前支持不了这个长度。
> 
> 参见：
> 
> * [[BUG] 使用 https://github.com/QwenLM/vllm-gptq  运行 Qwen/Qwen-14B-Chat-Int4 有5%会返回空 #849 (comment)](https://github.com/QwenLM/Qwen/issues/849#issuecomment-1867296778)
> * [[BUG] what does "seq_length": 2048 in the config file mean? can i ｍodify it to 8192? #827](https://github.com/QwenLM/Qwen/issues/827)
> * [长度外推超过4000个字符后会输出乱码 #658](https://github.com/QwenLM/Qwen/issues/658)

明白了! 确实是这个问题. 咨询下 如果用7B/72B能解决这个问题吗?
![企业微信截图_17035927345426](https://github.com/QwenLM/Qwen/assets/52460251/4f14ca25-5005-43b9-8c52-fb13900af27b)

**Comment by jklj077** [comment]
嗯，应该是可以解决这个问题的，不开dynamic_ntk的能支持的长度，可以看下config.json里的seq_length字段。后续模型也会更新支持更长的长度。
