### ISSUE TITLE
qwen_1.8B_chat版本用llama.cpp量化后，F16都回答错乱，请问是啥原因

### ISSUE THREAD

**Issue by Lyzin** [QwenLM/Qwen#867]
使用llama.cpp对qwen_1.8B_chat量化，然后使用F16的gguf进行推理，出现乱回答的情况，请问这是不支持量化吗？
![image](https://github.com/QwenLM/Qwen/assets/18082104/20ac23a0-3f50-4666-a2d7-69f55fe3dd99)

**Comment by anaivebird** [comment]
可以提供转换脚本吗 https://github.com/QwenLM/Qwen1.5/issues/57

**Comment by riverzhou** [comment]
llama.cpp 推千问一直不太正常

**Comment by anaivebird** [comment]
> llama.cpp 推千问一直不太正常

有没有替代的，qwen在cpu上推理加速的方案呢

**Comment by riverzhou** [comment]
> > llama.cpp 推千问一直不太正常
> 
> 有没有替代的，qwen在cpu上推理加速的方案呢

qwen.cpp

**Comment by lukeewin** [comment]
不量化也是会胡乱说的，请问你解决了这个问题吗？我使用的使用ollama中提供的转换脚本转换的，转换为gguf格式后，模型会乱输出，请问这个你们是如何解决，知道是什么原因导致的吗？

**Comment by tigflanker** [comment]
我把这个问题再顶一下，我写了更详细的 issue 在：https://github.com/modelscope/modelscope/issues/973

因为我也试用了chatglm，貌似都出现了同样的问题，就是在原生环境中调用ok，但是转化为gguf以后会降智到 base 版

我有一个猜测，就是 instruction 是通过 base 微调过来的，这其中会附带一些微调的小参数矩阵，转化的时候没有一起转过来

**Comment by jcleng** [comment]
+1, 同样的问题
