### ISSUE TITLE
关于微调sft数据时特殊token的使用？

### ISSUE THREAD

**Issue by Aran-Guo** [QwenLM/Qwen#868]
使用im_end当做eos_token_id结尾影响性能吗？官方代码给的有role，不加role可不可以啊？
```
input_ids = [self.im_start] + a_ids + b_ids + [self.im_end]
labels = [self.im_start] + [-100] * len(a_ids) + b_ids + [self.im_end]
```

**Comment by jklj077** [comment]
您好，我们没有理解您的问题。以下是通义千问生成的回复，仅供参考

> 使用im_end作为eos_token_id可能会对模型的性能产生一些影响，因为im_end原本的目的是标记每轮对话的结束，而不是整个输入序列的结束。将其用作eos_token_id可能会影响模型对对话结构的理解和处理。
>
> 至于role标记，它是提供额外信息给模型的一种方式，有助于模型更好地理解输入数据的上下文和结构。如果不加role，模型可能仍然能够学习和处理数据，但其性能和理解能力可能会有所下降。
>
> 总的来说，建议按照官方代码中的设定来使用im_end和role，以确保模型的最佳性能和理解能力。但如果出于某些原因必须进行改动，那么需要通过充分的实验和验证来评估这些改动对模型性能的影响。
