### ISSUE TITLE
[BUG] <title> vllm_wrapper如何设置多卡推理？

### ISSUE THREAD

**Issue by ChenlongDeng** [QwenLM/Qwen#870]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

环境：Pytorch2.1.2+cu118
机器：8*a100 40g
采用vllm_wrapper进行推理，发现第一张卡的显存增加直到溢出，其他卡的显存不变。
代码采用github主页中提供的示例代码：
```python
from vllm_wrapper import vLLMWrapper

model = vLLMWrapper('Qwen/Qwen-7B-Chat', tensor_parallel_size=1)
# model = vLLMWrapper('Qwen/Qwen-7B-Chat-Int4', tensor_parallel_size=1, dtype="float16")

response, history = model.chat(query="你好", history=None)
print(response)
response, history = model.chat(query="给我讲一个年轻人奋斗创业最终取得成功的故事。", history=history)
print(response)
response, history = model.chat(query="给这个故事起一个标题", history=history)
print(response)
```
同时报了一些warning，不知道是否对vllm的推理速度存在影响：
```
WARNING 12-26 08:53:29 config.py:140] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 12-26 08:53:29 llm_engine.py:72] Initializing an LLM engine with config: model='Qwen/Qwen-72B-Chat-Int4', tokenizer='Qwen/Qwen-72B-Chat-Int4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=gptq, seed=0)
WARNING 12-26 08:53:30 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.10
- Transformers: 4.36.2
- PyTorch: 2.1.2+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

**Comment by jklj077** [comment]
> vllm_wrapper如何设置多卡推理？

改tensor_parallel_size。

> gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.

可以忽略，原始gptq量化在batch大的时候就已经会比非量化模型慢了。

> Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.

忽略。我们是拿transformers的tokenizer框架接了tiktoken，tiktoken比transformers的fast tokenizer还要快，他slow/fast的识别逻辑还改不了。

**Comment by ChenlongDeng** [comment]
> > vllm_wrapper如何设置多卡推理？
> 
> 改tensor_parallel_size。
> 
> > gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
> 
> 可以忽略，原始gptq量化在batch大的时候就已经会比非量化模型慢了。
> 
> > Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> 
> 忽略。我们是拿transformers的tokenizer框架接了tiktoken，tiktoken比transformers的fast tokenizer还要快，他slow/fast的识别逻辑还改不了。

非常感谢及时的回复！想请问一下tensor_parallel_size和gpu显存以及数量的关系一般怎么设定呢？这个有经验总结吗？
