### ISSUE TITLE
微调时报错We couldn't connect to 'https://huggingface.co' 

### ISSUE THREAD

**Issue by chesp** [QwenLM/Qwen#871]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Qwen/Qwen-7B is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

请问怎么解决？

### 期望行为 | Expected Behavior

请问怎么解决？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
看Readme，都有说的

![image](https://github.com/QwenLM/Qwen/assets/17811943/a5ab71f1-c653-42c4-954c-f54d48ce1a01)
