### ISSUE TITLE
[BUG] flash attention推理速度疑问

### ISSUE THREAD

**Issue by Data2Me** [QwenLM/Qwen#872]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/59723064/4d3233b6-7ddf-488c-a3c6-3b7a4d889cb8)
 此处的推理速度是指生成指定数量token的时间吗？为什么使用了flash attentionv2后，推理时间反而变大了？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
速度，单位是token/s

**Comment by Data2Me** [comment]
> 速度，单位是token/s

谢谢解答
