### ISSUE TITLE
No module named 'langchain.tools.python.tool'

### ISSUE THREAD

**Issue by huangj17** [QwenLM/Qwen#873]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

根据官网示例运行langchain：https://github.com/QwenLM/Qwen/blob/main/examples/langchain_tooluse.ipynb
报错提示：No module named 'langchain.tools.python.tool'
![2c58063417a794c5e0665e4a47d08e62](https://github.com/QwenLM/Qwen/assets/11954057/684fb8a9-9919-4ce8-9b45-c9f10072363d)
![0e5ac8606b8a8ec428b839e13c88bf81](https://github.com/QwenLM/Qwen/assets/11954057/9b0debfc-f746-43b4-b869-7b7b712b8eff)

### 期望行为 | Expected Behavior

期望正常运行示例

### 复现方法 | Steps To Reproduce

根据示例写到第一步：让千问判断调用什么工具，生成工具入参后运行

### 运行环境 | Environment

```Markdown
- OS: macOS Sonoma 14.0
- Python: 3.11.0
- Transformers: 4.32.0
- PyTorch: 无
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): cpu
- langchain: 0.0.352
```

**Comment by kyriekevin** [comment]
```
!pip install langchain==0.0.288
```
可以找到模块，但是执行有些问题

**Comment by jklj077** [comment]
langchain_tooluse.ipynb，这个notebook最后更新时间是去年8月份了，那个时候langchain版本，大概是0.0.25x的样子，可以试试更旧的版本。

**Comment by tungsten106** [comment]
可以找到 [langchain_experimental](langchain_experimental.tools.python.tool.PythonAstREPLTool[¶](https://api.python.langchain.com/en/latest/tools/langchain_experimental.tools.python.tool.PythonAstREPLTool.html#langchain-experimental-tools-python-tool-pythonastrepltool)) 有一个相似的函数，可以用来替代。安装这个包：
```
pip install langchain_experimental
```
然后把 `langchain.tools.python.tool` 改为 `langchain_experimental.tools.python.tool` 就可以了。
（目前langchain版本0.1.12，langchain_experimental版本0.0.54
