### ISSUE TITLE
[BUG] docker run报错，

### ISSUE THREAD

**Issue by chesp** [QwenLM/Qwen#875]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行docker的脚本如下：
IMAGE_NAME=qwenllm/qwen:cu117
CHECKPOINT_PATH=/data/qwen/Qwen-main/             
DATA_PATH=/data/qwen/dataset/                  
OUTPUT_PATH=/data/qwen/output/checkpoint/ 
DEVICE=all
mkdir -p ${OUTPUT_PATH}
docker run --gpus ${DEVICE} --rm --name edu-model --mount type=bind,source=${CHECKPOINT_PATH},target=/data/shared/Qwen/Qwen-7B --mount type=bind,source=${DATA_PATH},target=/data/shared/Qwen/data --mount type=bind,source=${OUTPUT_PATH},target=/data/shared/Qwen/output_qwen --shm-size=2gb -it ${IMAGE_NAME} 

下载完成后报下面的错误：
Traceback (most recent call last):
  File "web_demo.py", line 209, in <module>
    main()
  File "web_demo.py", line 203, in main
    model, tokenizer, config = _load_model_tokenizer(args)
  File "web_demo.py", line 41, in _load_model_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 510, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/shared/Qwen/Qwen-Chat/'. Use `repo_type` argument if needed.

下载checkpoint使用的如下代码：
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer
model_dir = snapshot_download('qwen/Qwen-7B')
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    device_map="auto",
    trust_remote_code=True
).eval()

### 期望行为 | Expected Behavior

请问这是什么原因，该如何解决呢？

### 运行环境 | Environment

```Markdown
- OS:Ubuntu Server 18.04
- Python:3.10
- Transformers:4.32.1
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
```

**Comment by chesp** [comment]
下载checkpoint使用的如下代码：from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer

# Downloading model checkpoint to a local dir model_dir
model_dir = snapshot_download('qwen/Qwen-7B')
# Loading local checkpoints
# trust_remote_code is still set as True since we still load codes from local dir instead of transformers
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    device_map="auto",
    trust_remote_code=True
).eval()

**Comment by chesp** [comment]
qwen源码放在/data/qwen/Qwen-main 路径下

**Comment by fyabc** [comment]
您好，这个报错的原因应该是运行时没找到模型文件目录。

注意到您启动docker时的命令是：
```bash
CHECKPOINT_PATH=/data/qwen/Qwen-main/
docker run --gpus ${DEVICE} --rm --name edu-model --mount type=bind,source=${CHECKPOINT_PATH},target=/data/shared/Qwen/Qwen-7B --mount type=bind,source=${DATA_PATH},target=/data/shared/Qwen/data --mount type=bind,source=${OUTPUT_PATH},target=/data/shared/Qwen/output_qwen --shm-size=2gb -it ${IMAGE_NAME} 
```

因此，请保证宿主机上的路径`/data/qwen/Qwen-main/`指向你下载的模型，并且在docker中运行demo时，加上`-c /data/shared/Qwen/Qwen-7B/`选项。

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/677f4a98-9369-47aa-9268-aaaf0fabfd5e)
这是/data/qwen/Qwen-main/路径下的文件，下载的文件都放在里面，帮忙看下对不对

**Comment by fyabc** [comment]
@chesp 这张图似乎没有截图完整，下面的tokenizer相关文件没有截出来，但是按照上面代码下载的模型文件应当是完整的，可能是启动`web_demo.py`时指定的参数问题。您可以提供一下实际运行`web_demo.py`的命令参数。

ps: 观察到您下载了Qwen-7B，这是没有经过微调的base版本模型，不应当用于web demo，建议下载Qwen-7B-Chat版本的模型。

**Comment by chesp** [comment]
好的，我下载Qwen-7B-Chat版本试试

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/bffd651d-e87c-4470-96cc-bd3499ff34a1)
这是下载的Qwen-7B-Chat版本，默认下载路径是/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat/，那么CHECKPOINT_PATH=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat/，对吧？

**Comment by chesp** [comment]
还是报错：huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/shared/Qwen/Qwen-Chat/'. Use `repo_type` argument if needed.

**Comment by fyabc** [comment]
> 还是报错：huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/shared/Qwen/Qwen-Chat/'. Use `repo_type` argument if needed.

下载的模型文件没有问题，应该还是启动demo时候的问题，可以发一下启动web demo的命令吗？

**Comment by chesp** [comment]
docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat,target=/data/shared/Qwen/Qwen-7B-Chat --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen --shm-size=2gb -it qwenllm/qwen:cu117

**Comment by fyabc** [comment]
> docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat,target=/data/shared/Qwen/Qwen-7B-Chat --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen --shm-size=2gb -it qwenllm/qwen:cu117

启动docker之后，可以尝试下`python web_demo.py -c /data/shared/Qwen/Qwen-7B-Chat/`看下是否正常
也可以确认一下docker容器内是否正确挂载了模型目录

**Comment by chesp** [comment]
现在是docker run就报错，启动不了

**Comment by fyabc** [comment]
> 现在是docker run就报错，启动不了

麻烦提供一下报错信息？

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/2f6c542e-2f96-4529-823f-325cde68f731)

**Comment by fyabc** [comment]
> ![1](https://private-user-images.githubusercontent.com/8938818/292993456-2f6c542e-2f96-4529-823f-325cde68f731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjY0ODEsIm5iZiI6MTcwMzY2NjE4MSwicGF0aCI6Ii84OTM4ODE4LzI5Mjk5MzQ1Ni0yZjZjNTQyZS0yZjk2LTQ1MjktODIzZi0zMjVjZGU2OGY3MzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDgzNjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhkYmMzNjZkYTQyZWQ5NzVjNTNmMWFjODEyZjNmNTMyYTg3ZjlmODg2NmVhNzIwN2ZkZWVlYWE5NzZkMGM0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o0smvu2N1m5tPOA_dH-UpcUXLMKdTooSnPj7fTmf5vA)

明白了，你在运行docker run的时候没有加上命令，因此运行的是docker镜像内的默认启动命令，也就是`python3 web_demo.py --server-port 80 --server-name 0.0.0.0 -c /data/shared/Qwen/Qwen-Chat/`。但是这个和你挂载的路径不一致，所以找不到模型而报错。

有几种解决方式：
1. 修改挂载路径

```bash
docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat,target=/data/shared/Qwen/Qwen-Chat --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen -p 80:80 --shm-size=2gb -it qwenllm/qwen:cu117
```

2. 启动时直接加上要运行的命令

```bash
docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat,target=/data/shared/Qwen/Qwen-7B-Chat --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen -p 80:80 --shm-size=2gb -it qwenllm/qwen:cu117 python web_demo.py -c /data/shared/Qwen/Qwen-7B-Chat/
```

3. 使用本仓库中提供的脚本`docker/docker_web_demo.sh`（推荐）

```bash
bash docker/docker_web_demo.sh -i qwenllm/qwen:cu117 -c /root/.cache/modelscope/hub/qwen/Qwen-7B-Chat -p 80
```

这几种方式应该都可以解决。

**Comment by chesp** [comment]
docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat,target=/data/shared/Qwen/Qwen-7B-Chat --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen --shm-size=2gb -it qwenllm/qwen:cu117 bash finetune/finetune_qlora_single_gpu.sh -m /data/shared/Qwen/Qwen-7B-Chat/ -d /data/shared/Qwen/data/qwen_data.json

加上了命令，报下面的错误，请帮忙看下：
![1](https://github.com/QwenLM/Qwen/assets/8938818/1826782a-0b15-4fbf-a414-a936601f3c62)

**Comment by chesp** [comment]
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer

# Downloading model checkpoint to a local dir model_dir
#model_dir = snapshot_download('qwen/Qwen-7B')
model_dir = snapshot_download('qwen/Qwen-7B-Chat')
# model_dir = snapshot_download('qwen/Qwen-14B')
# model_dir = snapshot_download('qwen/Qwen-14B-Chat')

# Loading local checkpoints
# trust_remote_code is still set as True since we still load codes from local dir instead of transformers
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    device_map="auto",
    trust_remote_code=True
).eval()

这是下载模型的代码

**Comment by chesp** [comment]
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer
model_dir = snapshot_download('qwen/Qwen-7B-Chat')
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    device_map="auto",
    trust_remote_code=True
).eval()

这是下载模型的代码

**Comment by fyabc** [comment]
@chesp 报错是因为你使用单机量化微调脚本（Q-LoRA），但是使用的是非量化的模型，所以auto-gptq无法识别。
可以将`finetune/finetune_qlora_single_gpu.sh`修改为`finetune/finetune_lora_single_gpu.sh`。
或者，如果显存不足，一定要使用Q-LoRA，那么需要下载相应的量化版本模型Qwen-7B-Chat-Int4。

**Comment by chesp** [comment]
再看看这个问题：
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0

![1](https://github.com/QwenLM/Qwen/assets/8938818/25e12efa-c0f7-4bd8-a2a4-cf6f77e58937)

**Comment by fyabc** [comment]
@chesp Tesla T4不支持bf16，需要设置模型精度为fp16
可参考[这里](https://github.com/QwenLM/Qwen/blob/main/README_CN.md#-transformers)，设置`fp16=True`。

**Comment by chesp** [comment]
我设置了fp16=True，重新下载了模型，怎么还是报这个错呢
![1](https://github.com/QwenLM/Qwen/assets/8938818/b96378e8-ad30-4080-a901-1602b3728d92)

**Comment by chesp** [comment]
请帮忙看看该怎么解决呢

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/715931bc-ac83-4d04-ab15-bbf162177eda)
finetune_lora_single_gpu.sh里的参数也改为--fp16 True了

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/04d01a92-4da6-487a-a503-b54f412ba65a)
参数也改为了--fp16 True，还是不行

**Comment by fyabc** [comment]
@chesp 您好，由于我们目前提供的docker镜像在运行时使用的是内部自带的微调脚本，而不是外部的脚本，所以您在外部的改动目前是无效的。您可以尝试挂载代码目录，覆盖掉我们提供的默认微调脚本：

```bash
CODE_PATH=/path/to/code  # 指向Qwen代码目录，包含修改过的微调脚本

docker run --gpus all --rm --name edu-model \
--mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat,target=/data/shared/Qwen/Qwen-7B-Chat \
--mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data \
--mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen \
--mount type=bind,source=${CODE_PATH},target=/data/shared/Qwen
--shm-size=2gb -it qwenllm/qwen:cu117 \
bash finetune/finetune_qlora_single_gpu.sh -m /data/shared/Qwen/Qwen-7B-Chat/ -d /data/shared/Qwen/data/qwen_data.json
```

这样就能将您的修改更新到docker镜像中了。

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/fc99bad7-48f2-49f5-8470-079ffd7829b7)
请问finetune_lora_single_gpu.sh中的模型路径这样设置是否正确？

**Comment by chesp** [comment]
![1](https://github.com/QwenLM/Qwen/assets/8938818/d7cb51b2-a36a-47be-827c-84b18fe6387b)
请看下finetune_lora_single_gpu.sh文件里的这个路径设置是否正确，现在报如下错误：
![1703743902195](https://github.com/QwenLM/Qwen/assets/8938818/6cbf90c1-a0ab-40b5-8c01-46a883116528)

**Comment by chesp** [comment]
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.

请问这个错误怎么解决？

**Comment by chesp** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.58 GiB total capacity; 13.80 GiB already allocated; 35.31 MiB free; 13.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

机器中是两张 T4显卡，finetune_lora_single_gpu.sh 提示内存不足，请问需要多少显存？

**Comment by fyabc** [comment]
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.58 GiB total capacity; 13.80 GiB already allocated; 35.31 MiB free; 13.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 机器中是两张 T4显卡，finetune_lora_single_gpu.sh 提示内存不足，请问需要多少显存？
> 
> 操作系统 Ubuntu Server 18.04 LTS 64位 CPU 40核 GPU 2 * NVIDIA T4 内存 160GB

请参考[这里](https://github.com/QwenLM/Qwen?tab=readme-ov-file#profiling-of-memory-and-speed)的文档说明（注意表中的显存为所有GPU占用显存的总和）

**Comment by chesp** [comment]
我现在改用Q-LoRA，下载模型时报错：
Traceback (most recent call last):
  File "/data/qwen/download_checkpoint.py", line 14, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2496, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 31, in <module>
    from .data import get_dataset, prepare_dataset
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/optimum/gptq/data.py", line 21, in <module>
    from datasets import load_dataset
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/datasets/__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 66, in <module>
    from .arrow_reader import ArrowReader
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/datasets/arrow_reader.py", line 28, in <module>
    import pyarrow.parquet as pq
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/pyarrow/parquet/__init__.py", line 20, in <module>
    from .core import *
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/pyarrow/parquet/core.py", line 45, in <module>
    from pyarrow.fs import (LocalFileSystem, FileSystem, FileType,
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/pyarrow/fs.py", line 49, in <module>
    from pyarrow._gcsfs import GcsFileSystem  # noqa
  File "pyarrow/_gcsfs.pyx", line 1, in init pyarrow._gcsfs
ValueError: pyarrow.lib.IpcWriteOptions size changed, may indicate binary incompatibility. Expected 88 from C header, got 72 from PyObject

下载脚本代码如下：
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer
model_dir = snapshot_download('qwen/Qwen-7B-Chat-Int4')
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_dir,
    device_map="auto",
    trust_remote_code=True,
    fp16=True
).eval()

请问如何解决

**Comment by chesp** [comment]
改用Q-LoRA，微调时报错：
ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2, but only versions above 0.5.0 are supported
pip list查出机器里安装的auto-gptq是0.6.0版本，这个该怎么解决呢？

![1703749322850](https://github.com/QwenLM/Qwen/assets/8938818/83602dec-43fc-41c4-a4fd-c9cc67cfa78e)

**Comment by fyabc** [comment]
> 改用Q-LoRA，微调时报错： ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2, but only versions above 0.5.0 are supported pip list查出机器里安装的auto-gptq是0.6.0版本，这个该怎么解决呢？
> 
> ![1703749322850](https://private-user-images.githubusercontent.com/8938818/293160870-83602dec-43fc-41c4-a4fd-c9cc67cfa78e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDk4NTcsIm5iZiI6MTcwMzc0OTU1NywicGF0aCI6Ii84OTM4ODE4LzI5MzE2MDg3MC04MzYwMmRlYy00M2ZjLTQxYzQtYTRmZC1jOWNjNjdjZmE3OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDc0NTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEwNTAxZGQ5N2MzMjk0NTYxMzM1MGRiYzE2YjJjOTA5NGJkYzE2YTczZjg3YjJiMDk3NjgxZWQwNDgyMDNkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BDvNixMOcxM2EUoK36tb92znUJm3jpUBFsXmeXNH-Lc)

请拉取最新的Docker镜像，其中修复了此问题，`auto-gptq`版本是0.4.2。

**Comment by chesp** [comment]
docker pull qwenllm/qwen:latest  用这个拉的最新镜像，还是报这个错

![1703751528328](https://github.com/QwenLM/Qwen/assets/8938818/1e3426e3-4c04-4d18-8c51-36e515b288c6)

**Comment by fyabc** [comment]
> docker pull qwenllm/qwen:latest 用这个拉的最新镜像，还是报这个错

修复了docker镜像中的相应问题，您可以再拉取一下镜像重试一下

**Comment by chesp** [comment]
> > docker pull qwenllm/qwen:latest 用这个拉的最新镜像，还是报这个错
> 
> 修复了docker镜像中的相应问题，您可以再拉取一下镜像重试一下

好

**Comment by enymfc25173** [comment]
> 改用Q-LoRA，微调时报错： ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2, but only versions above 0.5.0 are supported pip list查出机器里安装的auto-gptq是0.6.0版本，这个该怎么解决呢？
> 
> ![1703749322850](https://private-user-images.githubusercontent.com/8938818/293160870-83602dec-43fc-41c4-a4fd-c9cc67cfa78e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTUzNDMsIm5iZiI6MTcwMzc1NTA0MywicGF0aCI6Ii84OTM4ODE4LzI5MzE2MDg3MC04MzYwMmRlYy00M2ZjLTQxYzQtYTRmZC1jOWNjNjdjZmE3OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDkxNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFiZmFkN2QwMmJhN2U2MzM4ZjU2ZTkyZWY2YjY5MTIyYWUwZTJlOTUyYzFiYmEyYTg3MjFhZjIxOTI2YWFmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HKAJwJtgKPyLHBEud5oCCVvrDVqZVOV1FYfiSrnrfwA)

同遇到该问题，加载qlora后的模型报出该错误，但应用0.5.0以上的版本又会推理很慢

**Comment by fyabc** [comment]
@enymfc25173 您好，报错是因为之前的docker镜像中，peft和autogptq的版本不匹配；而推理速度慢是因为autogptq 0.5.0以上的版本在cuda11.7环境中无法编译kernel，回退到默认慢速版本（可参考 #843  ）。

您可以更新一下最新的docker镜像，其中修复了这一问题。

**Comment by chesp** [comment]
前面的问题已经没有，现在出现的错误是：RuntimeError: FlashAttention only supports Ampere GPUs or newer.
![1703755796876](https://github.com/QwenLM/Qwen/assets/8938818/2d061d7c-f73e-4fa6-be7f-1b4a8e15b7e5)


启动命令如下：
docker run --gpus all --rm --name edu-model --mount type=bind,source=/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat-Int4,target=/data/shared/Qwen/Qwen-7B --mount type=bind,source=/data/qwen/dataset,target=/data/shared/Qwen/data --mount type=bind,source=/data/qwen/output/checkpoint,target=/data/shared/Qwen/output_qwen --mount type=bind,source=/data/qwen/Qwen-main/,target=/data/shared/Qwen --shm-size=2gb -it qwenllm/qwen:latest bash finetune/finetune_qlora_single_gpu.sh -m /data/shared/Qwen/Qwen-7B/ -d /data/shared/Qwen/data/qwen_data.json

**Comment by enymfc25173** [comment]
cuda11.7以下的版本可以兼容吗，因为环境限制无法更新至11.7以上的版本

**Comment by chesp** [comment]
NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0

**Comment by fyabc** [comment]
@chesp @enymfc25173 您可以尝试我们的另一个镜像`qwenllm/qwen:cu114`，这个版本没有flash-attn的依赖，可以适用于非Ampere架构的GPU。

**Comment by chesp** [comment]
> RuntimeError: FlashAttention only supports Ampere GPUs or newer

好

**Comment by chesp** [comment]
> @chesp @enymfc25173 您可以尝试我们的另一个镜像`qwenllm/qwen:cu114`，这个版本没有flash-attn的依赖，可以适用于非Ampere架构的GPU。

好

**Comment by chesp** [comment]
![1703758116467](https://github.com/QwenLM/Qwen/assets/8938818/21ee9692-9096-43b2-9ad8-1e9bdc9ae1d6)
这个是微调完成了吗？

**Comment by fyabc** [comment]
> RuntimeError: FlashAttention only supports Ampere GPUs or newer

是的，您可以在输出目录`/data/qwen/output/checkpoint`中找到微调输出，然后可以参考文档中的相关章节使用。

**Comment by chesp** [comment]
> > RuntimeError: FlashAttention only supports Ampere GPUs or newer
> 
> 是的，您可以在输出目录`/data/qwen/output/checkpoint`中找到微调输出，然后可以参考文档中的相关章节使用。

麻烦发下介绍如何使用微调输出结果的链接

**Comment by chesp** [comment]
需要修改输出的adapter_config.json文件中的base_model_name_or_path路径吗，生成的是容器内的路径，推理时是不是要指定到主机的模型路径
![1](https://github.com/QwenLM/Qwen/assets/8938818/d6e04407-443e-481b-a6b6-2e9d192a2b9a)

**Comment by chesp** [comment]
model = AutoPeftModelForCausalLM.from_pretrained("/data/qwen/output/checkpoint", device_map="auto", trust_remote_code=True, fp16=True).eval() 报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/peft/auto.py", line 69, in from_pretrained
    peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/peft/config.py", line 114, in from_pretrained
    loaded_attributes = cls.from_json_file(config_file)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/peft/config.py", line 150, in from_json_file
    json_object = json.load(file)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/anaconda3/envs/modelscope/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/modelscope/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/modelscope/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by chesp** [comment]
@fyabc 帮忙看下这个问题
运行如下代码：
from peft import AutoPeftModelForCausalLM
model = AutoPeftModelForCausalLM.from_pretrained("/data/qwen/output/checkpoint", device_map="auto",trust_remote_code=True).eval()

首先是报错模型路径不对，我把输出中的adapter_config.json文件的base_model_name_or_path改为了主机上的模型路径，"base_model_name_or_path":"/root/.cache/modelscope/hub/qwen/Qwen-7B-Chat-Int4/"，微调生成的路径是容器内的路径，如下图：
![image](https://github.com/QwenLM/Qwen/assets/8938818/ff75b94b-f083-42e8-a0c4-6dd2b31e1bd9)

然后又报错：
Traceback (most recent call last):
File "", line 1, in
File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/peft/auto.py", line 69, in from_pretrained
peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/peft/config.py", line 114, in from_pretrained
loaded_attributes = cls.from_json_file(config_file)
File "/root/anaconda3/envs/modelscope/lib/python3.10/site-packages/peft/config.py", line 150, in from_json_file
json_object = json.load(file)
File "/root/anaconda3/envs/modelscope/lib/python3.10/json/init.py", line 293, in load
return loads(fp.read(),
File "/root/anaconda3/envs/modelscope/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/root/anaconda3/envs/modelscope/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/root/anaconda3/envs/modelscope/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by chesp** [comment]
请帮忙看看这个问题怎么解决

**Comment by chesp** [comment]
@fyabc 微调的数据没有生效，推理无法回答微调数据中的问题，是微调存在什么问题吗？

**Comment by jklj077** [comment]
lr一直为0，相当于没训练，请检查下有关配置。如果配置正常，可能是数据集长度为0，建议看下数据格式是否正确。
