### ISSUE TITLE
[BUG] Qwen72B-Chat-Int4部署vLLM_gptq，API调用，任务推理过慢时会出现 Aborted request

### ISSUE THREAD

**Issue by SL-Stone** [QwenLM/Qwen#877]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

按照官方的API调用方式https://github.com/QwenLM/vllm-gptq，单卡 GPU H100 80G，fschat框架能接收到请求，但当模型推理耗时较长时，生成的token较多时，会出现Aborted request，最终无法拿到API调用的结果。

1. 问题1：输入Prompt的token长度是3673，任务要求生成的token长度预计在700左右，同一时刻只有1个请求，vllm处理用时约为4min，最后Finished request，Aborted request。日志详细<备注>部分；
2. 问题2：当一个任务的生成token在500以上时，多个请求传入时，Pending reqs变多，最后也会Aborted request。

以上运行时都设置了vllm-gptq/vllm/entrypoints/openai/api_server.py的参数`TIMEOUT_KEEP_ALIVE = 1000`，但`TIMEOUT_KEEP_ALIVE`似乎不生效，从拿到请求到Qwen模型完成inference的用时低于1000s，仍会Aborted request。
也设置过`self.use_dynamic_ntk = False`，也仍会Aborted request。

### 期望行为 | Expected Behavior

如何解决推理慢时，API调用的Aborted request现象。感谢！

### 复现方法 | Steps To Reproduce

1. 启动Server、启动Worker、启动服务器的命令和官网一致 https://github.com/QwenLM/vllm-gptq

2. 客户端OpenAI 1.5.0的接口调用方式：`messages`是传入的字符串
response = self.qwen_client.chat.completions.create(
            model="Qwen-72B-Chat-Int4",
            messages=[
                {"role": "user", "content": messages}
            ],
            max_tokens=3072,
            top_p=0.8,
            temperature=0.01,
            extra_body={"top_k": 1, 
                        "repetition_penalty": 1.1
                        },
            timeout=500,
            )

4. Qwen-72B-Chat-Int4的`max_window_size`为8192.

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04.6 LTS \n \l
- Python: 3.11.0
- Transformers: 4.36.2
- PyTorch: 2.0.1+cu118
- CUDA: 11.8
- vllm: 0.2.2+cu118 (官方的vllm_qptq)
- openai: 1.6.1 服务器端; 1.5.0 客户端
- fschat: 0.2.34
```

### 备注 | Anything else?

**单条请求，输入Prompt长度为3673的log**

sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.1, temperature=0.01, top_p=0.8, top_k=1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|im_end|>', '<|endoftext|>', '<|im_start|>'], stop_token_ids=[151643, 151644, 151645], ignore_eos=False, max_tokens=4400, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: None.

INFO 12-27 07:15:22 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 38.8%, CPU KV cache usage: 0.0%
INFO 12-27 07:15:27 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 39.7%, CPU KV cache usage: 0.0%
INFO 12-27 07:15:32 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 40.5%, CPU KV cache usage: 0.0%
2023-12-27 07:15:35 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 14. worker_id: 6b5bab9c. 
INFO 12-27 07:15:37 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 41.3%, CPU KV cache usage: 0.0%
INFO 12-27 07:15:42 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 42.2%, CPU KV cache usage: 0.0%
INFO 12-27 07:15:47 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 42.9%, CPU KV cache usage: 0.0%
INFO 12-27 07:15:52 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 43.7%, CPU KV cache usage: 0.0%
INFO 12-27 07:15:57 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 44.5%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:02 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 45.4%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:07 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 46.1%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:12 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 46.9%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:17 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 47.7%, CPU KV cache usage: 0.0%
2023-12-27 07:16:20 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 14. worker_id: 6b5bab9c. 
INFO 12-27 07:16:22 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 15.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 48.6%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:27 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 49.2%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:32 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 50.1%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:37 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 50.9%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:42 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 51.6%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:48 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 52.4%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:53 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 53.3%, CPU KV cache usage: 0.0%
INFO 12-27 07:16:58 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 53.9%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:03 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 54.8%, CPU KV cache usage: 0.0%
2023-12-27 07:17:05 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 14. worker_id: 6b5bab9c. 
INFO 12-27 07:17:08 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 55.6%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:13 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 56.3%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:18 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 57.1%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:23 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 58.0%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:28 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 58.7%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:33 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 59.5%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:38 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 60.3%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:43 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 61.0%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:48 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 61.8%, CPU KV cache usage: 0.0%
2023-12-27 07:17:50 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 14. worker_id: 6b5bab9c. 
INFO 12-27 07:17:53 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 62.7%, CPU KV cache usage: 0.0%
INFO 12-27 07:17:58 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 63.4%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:03 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 64.2%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:08 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 64.9%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:13 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 65.7%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:18 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 66.6%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:23 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 67.2%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:28 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 68.1%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:33 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 68.7%, CPU KV cache usage: 0.0%
2023-12-27 07:18:35 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 14. worker_id: 6b5bab9c. 
INFO 12-27 07:18:38 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 69.6%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:43 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 70.3%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:49 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 71.1%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:54 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 71.9%, CPU KV cache usage: 0.0%
INFO 12-27 07:18:59 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 72.6%, CPU KV cache usage: 0.0%
INFO 12-27 07:19:04 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 73.4%, CPU KV cache usage: 0.0%
INFO 12-27 07:19:09 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 74.1%, CPU KV cache usage: 0.0%
INFO 12-27 07:19:14 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 75.0%, CPU KV cache usage: 0.0%
INFO 12-27 07:19:19 llm_engine.py:636] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 14.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 75.6%, CPU KV cache usage: 0.0%
2023-12-27 07:19:20 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 14. worker_id: 6b5bab9c. 
INFO 12-27 07:19:20 async_llm_engine.py:111] Finished request 6b9edc86e51848c6bc2ad31204d75cb4.
INFO 12-27 07:19:20 async_llm_engine.py:134] Aborted request 6b9edc86e51848c6bc2ad31204d75cb4.
2023-12-27 07:19:20 | INFO | stdout | INFO:     127.0.0.1:43124 - "POST /worker_generate HTTP/1.1" 200 OK
2023-12-27 07:20:05 | INFO | model_worker | Send heart beat. Models: ['Qwen-72B-Chat-Int4']. Semaphore: Semaphore(value=1024, locked=False). call_ct: 14. worker_id: 6b5bab9c.

**Comment by felixstander** [comment]
遇到相同的问题

**Comment by jklj077** [comment]
controller vllm_worker api_server有任何一个日志里有timeout相关的吗？客户端有收到返回信息吗，客户端的报错是什么呢。

**Comment by xxjordan** [comment]
我也是相同的问题，而且我的问题文本内容也不长，我感觉是vllm的问题，我4张4090推Qwen72B-chat-int4和Qwen14B-chat都是同样的问题

**Comment by jklj077** [comment]
aborted request的定义是客户端断开了链接，可以试试本机localhost访问
- 如果也会有该问题，建议需求FastChat或vLLM的帮助。
- 如果改问题消失，建议看看网络配置问题，比如反代、防火墙之类的。

**Comment by SL-Stone** [comment]
`controller.log `只会显示Receive heart beat，请求队列信息，200 OK这些信息。

> 2024-01-01 05:51:41 | INFO | controller | Receive heart beat. http://localhost:21002
2024-01-01 05:51:41 | INFO | stdout | INFO:     127.0.0.1:37882 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2024-01-01 05:51:46 | INFO | stdout | INFO:     127.0.0.1:37898 - "POST /list_models HTTP/1.1" 200 OK
2024-01-01 05:51:46 | INFO | controller | names: ['http://localhost:21002'], queue_lens: [0.0], ret: http://localhost:21002
2024-01-01 05:51:46 | INFO | stdout | INFO:     127.0.0.1:37910 - "POST /get_worker_address HTTP/1.1" 200 OK
2024-01-01 05:51:49 | INFO | stdout | INFO:     127.0.0.1:37920 - "POST /list_models HTTP/1.1" 200 OK
2024-01-01 05:51:49 | INFO | controller | names: ['http://localhost:21002'], queue_lens: [1.0], ret: http://localhost:21002

`vllm_worker.log`会显示请求的详细信息和请求的执行情况、CPU、GPU使用等。就是上面备注里打印的信息。

`api_server.log`会显示对客户端发出请求的回复情况。200 OK就代表正确响应请求，这时客户端也能收到回复。收不到回复的请求，api_server也不会报任何异常、提示之类的信息。

> 2024-01-01 05:57:16 | INFO | stdout | INFO:     165.1.73.88:34356 - "POST /v1/chat/completions HTTP/1.1" 200 OK

备注里log也没有显示请求出现死锁，也完成执行了，但是客户端这边就是没有收到请求，返回的结果是request timeout，即使我在API的timeout参数置为1000也没解决。同时，openai_api_server也没有打印`"POST /v1/chat/completions HTTP/1.1" 200 OK
`，应该是Server没有把回复发回去。

**Comment by SL-Stone** [comment]
> controller vllm_worker api_server有任何一个日志里有timeout相关的吗？客户端有收到返回信息吗，客户端的报错是什么呢。

`controller.log `只会显示Receive heart beat，请求队列信息，200 OK这些信息。

> 2024-01-01 05:51:41 | INFO | controller | Receive heart beat. http://localhost:21002
2024-01-01 05:51:41 | INFO | stdout | INFO:     127.0.0.1:37882 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2024-01-01 05:51:46 | INFO | stdout | INFO:     127.0.0.1:37898 - "POST /list_models HTTP/1.1" 200 OK
2024-01-01 05:51:46 | INFO | controller | names: ['http://localhost:21002'], queue_lens: [0.0], ret: http://localhost:21002
2024-01-01 05:51:46 | INFO | stdout | INFO:     127.0.0.1:37910 - "POST /get_worker_address HTTP/1.1" 200 OK
2024-01-01 05:51:49 | INFO | stdout | INFO:     127.0.0.1:37920 - "POST /list_models HTTP/1.1" 200 OK
2024-01-01 05:51:49 | INFO | controller | names: ['http://localhost:21002'], queue_lens: [1.0], ret: http://localhost:21002

`vllm_worker.log`会显示请求的详细信息和请求的执行情况、CPU、GPU使用等。就是上面备注里打印的信息。

`api_server.log`会显示对客户端发出请求的回复情况。200 OK就代表正确响应请求，这时客户端也能收到回复。收不到回复的请求，api_server也不会报任何异常、提示之类的信息。

> 2024-01-01 05:57:16 | INFO | stdout | INFO:     165.1.73.88:34356 - "POST /v1/chat/completions HTTP/1.1" 200 OK

备注里log也没有显示"请求出现死锁"，也完成执行了，但是客户端这边就是没有收到请求，返回的结果是request timeout，即使我在API的timeout参数置为1000也没解决。同时，openai_api_server也没有打印`"POST /v1/chat/completions HTTP/1.1" 200 OK`，应该是Server没有把回复发回去。

**Comment by SL-Stone** [comment]
> aborted request的定义是客户端断开了链接，可以试试本机localhost访问
> 
> * 如果也会有该问题，建议需求FastChat或vLLM的帮助。
> * 如果改问题消失，建议看看网络配置问题，比如反代、防火墙之类的。

看代码https://github.com/QwenLM/vllm-gptq/blob/9bad890080e915eac8168c055948090c5cff6909/vllm/engine/async_llm_engine.py#L101，当一个请求完成执行后就会自动Abort。所以Abort应该不代表异常。可能只是表示**这个请求已处理完，所以丢弃**。
```python
        if request_output.finished:
            if verbose:
                logger.info(f"Finished request {request_id}.")
            self.abort_request(request_id)
```

但是对于接收了但没有回复的请求 服务器端却没有任何提示。我当时在服务器这边的机子也试过同样的请求，同样`timeout`。

不过，我还是按照开头的`TIMEOUT_KEEP_ALIVE`和`self.use_dynamic_ntk = False`的配置，只是重启了几次服务器，加几次kill进程，它现在可以响应`问题1`描述的Prompt，有点迷惑... 但`问题2`还是会timeout。

**Comment by SL-Stone** [comment]
> 我也是相同的问题，而且我的问题文本内容也不长，我感觉是vllm的问题，我4张4090推Qwen72B-chat-int4和Qwen14B-chat都是同样的问题

实验下来，感觉uvicorn的`TIMEOUT_KEEP_ALIVE`参数并没什么用。可能是vllm完成处理后没能把完成的消息发给Server，所以Server没收到请求完成结果，最后客户端没收到回复。

**Comment by jklj077** [comment]
建议您在<https://github.com/lm-sys/FastChat/blob/a7eb75059467b01d2c9c803d4154f7aa4188a368/fastchat/serve/openai_api_server.py#L812-L836>中添加更多日志记录，辅助判断。有可能openai_api_server未收到vllm_worker的响应，这里timeout是写死的3小时。

P.S.：

> TIMEOUT_KEEP_ALIVE

看名字是KEEP-ALIVE connection的设置，单次请求如果无响应超时，似乎与KEEP-ALIVE无关。

> self.use_dynamic_ntk = False

无关哈，vLLM导入模型的时候不会读这个参数，False或者True都不生效。

> API设置timeout

这是客户端的timeout (默认是600)，不会影响服务端哈。

**Comment by SL-Stone** [comment]
确实，`TIMEOUT_KEEP_ALIVE`是uvicorn服务器段决定和客户端断开连接的时间限制，好像和我说的 openai_api_server收不到vllm_worker的响应 无关，草率了，我会再仔细看看FastChat和vllm_gptq的源码，谢谢回复！
