### ISSUE TITLE
💡 [REQUEST] - 能不能把微调语料的格式改为jsonl（Json Line）

### ISSUE THREAD

**Issue by zhengyangyong** [QwenLM/Qwen#878]
### 摘要 | Summary

现在一个Json大数组，语料记录数多了，使用编辑器打开卡的要死，但是多行Json就没问题，因为文本编辑器都能多行窗口加载。搞一个大Json审核语料除了写个程序没法弄

### 基本示例 | Basic Example

{"id" :"","conversations" :[]} \r\n
{"id" :"","conversations" :[]} \r\n
{"id" :"","conversations" :[]} \r\n
{"id" :"","conversations" :[]} \r\n
...

### 缺陷 | Drawbacks

使用不方便，Review语料太卡

**Comment by jklj077** [comment]
您用jsonl review数据，然后写一个格式转换脚本，转成相应的数据格式，是不是也可以。

**Comment by zhengyangyong** [comment]
我现在就是这么干的，如果能原生支持更好了
