### ISSUE TITLE
💡 [REQUEST] - <1.8B模型商用>

### ISSUE THREAD

**Issue by yuimo** [QwenLM/Qwen#879]
### 摘要 | Summary

请问如果基于1.8B模型做商用应用开发，如何申请呢？之前发过邮件，但是贵司一直没有回复
谢谢！

### 基本示例 | Basic Example

1.8B 模型如何商用

### 缺陷 | Drawbacks

na

**Comment by jklj077** [comment]
您好，我们的工作人员后续将通过邮件与您取得联系。在此期间，我们衷心感谢您的耐心等待和理解。若有任何其它疑问或需求，欢迎随时向我们反馈。谢谢您的支持与配合。
