### ISSUE TITLE
使用int8量化qwen-14b模型后，首字响应时间相比int4量化的模型慢了很多

### ISSUE THREAD

**Issue by Originhhh** [QwenLM/Qwen#880]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

int8量化后模型首字响应时间为2s   int4量化模型响应时间为300ms，请问这是因为什么呢

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
transformers和autogptq版本都多少呢。不同版本行为不同，问题原因不同；但总体就是int8比int4慢（可以参考README中的测速），int8慢的程度不同（其实主要是int4快的程度不同）。

**Comment by Originhhh** [comment]
auto-gptq ==0.4.2      transformers==4.31.0。那请问int8模型相较于未量化模型会快吗

**Comment by jklj077** [comment]
> transformers==4.31.0

您确定吗，4.31.0还没正式支持auto-gptq呢，用README中的示例应该加载不了Qwen-Chat-Int4和Qwen-Chat-Int8模型的。

> 请问int8模型相较于未量化模型会快吗

如果是GPTQ方案的话，int8速度上跟未量化的没差多少。README中测速数据的，相对速度是可以参考的。

**Comment by Originhhh** [comment]
类似问题 我在autogptq的issue中也遇见过，但是现在也是明确答复。不知道官方的int8量化模型相较于int4量化模型，首字响应时间也要慢很多吗

**Comment by Originhhh** [comment]
> > transformers==4.31.0
> 
> 您确定吗，4.31.0还没正式支持auto-gptq呢，用README中的示例应该加载不了Qwen-Chat-Int4和Qwen-Chat-Int8模型的。
> 
> > 请问int8模型相较于未量化模型会快吗
> 
> 如果是GPTQ方案的话，int8速度上跟未量化的没差多少。README中测速数据的，相对速度是可以参考的。

我用的是自己微调后的模型，然后使用auto-gptq官方代码进行的量化

**Comment by jklj077** [comment]
如过不是按README中方式加载的话，相关问题建议直接给auto-gptq提issue哈。
