### ISSUE TITLE
本地部署Qwen-7B之后如何开启API服务？💡 [REQUEST] - <求助>

### ISSUE THREAD

**Issue by yoohhwz** [QwenLM/Qwen#883]
### 相关Issues | Reference Issues

本地部署Qwen-7B之后如何开启API服务？

### 摘要 | Summary

本地部署Qwen-7B之后如何开启API服务？

### 基本示例 | Basic Example

本地部署Qwen-7B之后如何开启API服务？

### 缺陷 | Drawbacks

本地部署Qwen-7B之后如何开启API服务？

### 未解决问题 | Unresolved questions

本地部署Qwen-7B之后如何开启API服务？

**Comment by jklj077** [comment]
没懂你的问题。请看README里部署部分，那里就有API服务部署的说明。什么叫部署Qwen-7B后，再开启API服务？部署的同时就确定了是不是API服务的。
