### ISSUE TITLE
[问题] <为什么lora微调base模型需要的显存比微调chat模型要高？>

### ISSUE THREAD

**Issue by tangsipeng** [QwenLM/Qwen#886]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
![image](https://github.com/QwenLM/Qwen/assets/17811943/fdfc0857-b42e-4cd0-be07-e94d4a6cde2b)

请参考README中的说明。
