### ISSUE TITLE
[BUG] <title> Qwen-14B全量微调的显存使用量非常高

### ISSUE THREAD

**Issue by hackiey** [QwenLM/Qwen#887]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

max_seq_length=2048，per_device_train_batch_size=1，4台8卡80G，每张显存60-70G。4096长度，8台机器都会OOM。
相同的ds_config，Baichuan2-13B，4096长度，每张显存是50G+，这个差别有点太大了。
ds_config采用stage2，bf16，完整配置如下
```json
{
    "optimizer": {
      "type": "AdamW",
      "params": {
          "lr": "auto",
          "weight_decay": "auto",
          "torch_adam": true,
          "adam_w_mode": true
      }
    },
    "scheduler": {
      "type": "WarmupDecayLR",
      "params": {
          "warmup_min_lr": "auto",
          "warmup_max_lr": "auto",
          "warmup_num_steps": "auto",
          "total_num_steps": "auto"
      }
    },
    "bf16": {"enabled": true},
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "reduce_scatter": true,
        "reduce_bucket_size": "auto",
        "overlap_comm": true,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 1000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
请问有安装Flash-Attention吗？没有安装Flash-Attention的话，请问使用的PyTorch版本是2.1.1吗？

**Comment by hackiey** [comment]
flash_attn==2.4.2
torch==2.0.1+cu117

import model的时候已经没有未安装flash attention的warning了，pytorch需要升级吗

**Comment by jklj077** [comment]
> import model的时候已经没有未安装flash attention的warning了，pytorch需要升级吗？

不用的了，显存主要能省的是Attention那里（FlashAttention的attention或者torch 2.1.1的memory-efficient的SDPA），已经生效了。

> 14B的全量finetune应该占用的显存大小是多少?

这个还没有关数据。不过用的哪个代码能同时训练Qwen-14B或Baichuan2-13B呀。

**Comment by hackiey** [comment]
用的transformers的trainer，auto frompretrain，就能正常跑了。
升级pytorch2.1.1可以不用flash attention吗，代码里是自动适应的吗

**Comment by ansvver** [comment]
请问各位大佬，8张A100（40g）能跑14B 的全量微调吗？

**Comment by jklj077** [comment]
> 升级pytorch2.1.1可以不用flash attention吗，代码里是自动适应的吗

这个得卸载flash-attn，代码里逻辑是有flash-attn优先用flash-attn。
