### ISSUE TITLE
[BUG] <title>72B全量微调资源需求

### ISSUE THREAD

**Issue by liyang-7** [QwenLM/Qwen#888]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

8*A100 (80G) deepspeed zero3 全量微调72B遇到OOM，问下需要怎样的配置和资源才能全量微调72B？还是说72B只能lora方式微调？

**Comment by jklj077** [comment]
目前单机8卡全量微调的成功案例很少：
- https://github.com/QwenLM/Qwen/issues/755

可以理解为目前单机难以全参数微调。
