### ISSUE TITLE
[BUG] Qwen-72B使用vLLM部署报告input prompt is too long

### ISSUE THREAD

**Issue by TangMoming** [QwenLM/Qwen#889]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在部署使用Qwen-72B大模型时遇到了一些问题：
尝试使用2 \* A100 80G进行Qwen-72B-Chat模型的部署
   在vllm部署时：
    a). 当输入的token数量超过3000时，模型会显示以下提示：“Input prompt (3916 tokens) is too long and exceeds the capacity of block_manager”。
    b). 当输入的字符数为1500时：
    ```
    llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 33.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 82.6%, CPU KV cache usage: 0.0%
    ```
    之后进入等待状态。即使在使用4*A100后，问题依然没有得到解决。

所使用的vllm版本为最新版本，transformers版本为4.36.2。

VLLM的启动命令如下：
```
python -m vllm.entrypoints.openai.api_server \
--model model_path \
--dtype auto \
--max-model-len 8192 \
--tensor-parallel-size 2 \
--max-num-batched-tokens 8192 \
--max-paddings 8192 \
--enforce-eager \
--trust-remote-code 
```
在此，我想请教如何才能够达到<https://modelscope.cn/studios/qwen/Qwen-72B-Chat-Demo/summary>中展示的推理速度。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
> Input prompt (3916 tokens) is too long and exceeds the capacity of block_manager

vLLM可用的显存不足以支持如此长的数据，默认block_size 16，但是有多少个block是profile出来的，输入长度不能超过block_size\*num_gpu_blocks。可以尝试增加卡的数量，或者调大gpu_memory_utilization，让vLLM可用的显存增加。

> 当输入的字符数为1500时，之后进入等待状态

log是正常运行的，没太理解问题是什么。

> 如何才能够达到https://modelscope.cn/studios/qwen/Qwen-72B-Chat-Demo/summary中展示的推理速度

ModelScope用的灵积的API服务，要达到这个速度的话，直接用[灵积API](https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-7b-14b-72b-api-detailes)是最简单的。

**Comment by cgq0816** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> 在部署使用Qwen-72B大模型时遇到了一些问题： 尝试使用2 * A100 80G进行Qwen-72B-Chat模型的部署 在vllm部署时： a). 当输入的token数量超过3000时，模型会显示以下提示：“Input prompt (3916 tokens) is too long and exceeds the capacity of block_manager”。 b). 当输入的字符数为1500时： `llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 33.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 82.6%, CPU KV cache usage: 0.0%` 之后进入等待状态。即使在使用4*A100后，问题依然没有得到解决。
> 
> 所使用的vllm版本为最新版本，transformers版本为4.36.2。
> 
> VLLM的启动命令如下：
> 
> ```
> python -m vllm.entrypoints.openai.api_server \
> --model model_path \
> --dtype auto \
> --max-model-len 8192 \
> --tensor-parallel-size 2 \
> --max-num-batched-tokens 8192 \
> --max-paddings 8192 \
> --enforce-eager \
> --trust-remote-code 
> ```
> 
> 在此，我想请教如何才能够达到https://modelscope.cn/studios/qwen/Qwen-72B-Chat-Demo/summary中展示的推理速度。
> 
> ### 期望行为 | Expected Behavior
> _No response_
> 
> ### 复现方法 | Steps To Reproduce
> _No response_
> 
> ### 运行环境 | Environment
> ```
> - OS:
> - Python:
> - Transformers:
> - PyTorch:
> - CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
> ```
> 
> ### 备注 | Anything else?
> _No response_

请问一下vllm如何支持长文本输入的，需要改哪里，谢谢

**Comment by roki1031** [comment]
同问。
请问一下vllm如何支持长文本输入的，需要改哪里，谢谢
是需要修改max-model-len这个参数吗？
