### ISSUE TITLE
Please support quip# 2bit quantization for the qwen model

### ISSUE THREAD

**Issue by Minami-su** [QwenLM/Qwen#891]
Here are some of the effort I've tried, but it still doesn't work:
https://github.com/Cornell-RelaxML/quip-sharp/issues/15
https://github.com/Cornell-RelaxML/quip-sharp/issues/30
https://github.com/Minami-su/quip-sharp-qwen
QuIP# method, a weights-only quantization method that is able to achieve near fp16 performance using only 2 bits per weight.

**Comment by JustinLin610** [comment]
I'll try to learn about it, didn't know this before. Any more details about your problems?

**Comment by Minami-su** [comment]
> I'll try to learn about it, didn't know this before. Any more details about your problems?

https://github.com/Cornell-RelaxML/quip-sharp/issues/15

**Comment by Minami-su** [comment]
> I'll try to learn about it, didn't know this before. Any more details about your problems?

现在可能的问题参考这个：https://github.com/Cornell-RelaxML/quip-sharp/issues/15#issuecomment-1872318560

**Comment by chu-tianxiang** [comment]
I'm also working on expanding the capabilities of QuIP# to support additional model structures, which you can find in my repository [here](https://github.com/chu-tianxiang/QuIP-for-all). Additionally, I've made a 2-bit version of the Qwen-72B-Chat model available on [hugingface](https://huggingface.co/keyfan/Qwen-72B-Chat-2bit). The perplexity on wikitext is 6.9492 vs fp16's 5.8438.

**Comment by Minami-su** [comment]
> I'm also working on expanding the capabilities of QuIP# to support additional model structures, which you can find in my repository [here](https://github.com/chu-tianxiang/QuIP-for-all). Additionally, I've made a 2-bit version of the Qwen-72B-Chat model available on [hugingface](https://huggingface.co/keyfan/Qwen-72B-Chat-2bit). The perplexity on wikitext is 6.9492 vs fp16's 5.8438.

Thank you very much, you are my god.😭
