### ISSUE TITLE
[BUG] Qwen readme中介绍的批量推理方式失效

### ISSUE THREAD

**Issue by tomFoxxxx** [QwenLM/Qwen#892]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

from qwen_generation_utils import make_context, decode_tokens, get_stop_words_ids

——> ModuleNotFoundError: No module named 'qwen_generation_utils'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by luckykong** [comment]
在 下载的模型文件夹下运行。 os.chdir() 过去

**Comment by tomFoxxxx** [comment]
> 在 下载的模型文件夹下运行。 os.chdir() 过去

已解决，谢谢
