### ISSUE TITLE
[BUG] <title>A800多卡执行微调脚本失败 使用镜像 qwenllm/qwen:cu117

### ISSUE THREAD

**Issue by oho-work** [QwenLM/Qwen#894]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![企业微信截图_17041640075373](https://github.com/QwenLM/Qwen/assets/115210234/ce657d36-c382-4d10-8e12-964f1392aa13)
![Snipaste_2024-01-02_10-53-58](https://github.com/QwenLM/Qwen/assets/115210234/192e7a90-f8ff-483c-bcc9-a21e7faab648)

### 期望行为 | Expected Behavior

正确完成微调

### 复现方法 | Steps To Reproduce

1. 通过docker-compose完成容器的部署

   ```bash
   version: '3'
   services:
       qwen-finetune:
         image: qwenllm/qwen:cu117
         restart: on-failure
         runtime: nvidia
         container_name: qwen-finetune
         volumes:
           - ./start.sh:/usr/local/start.sh
           - ./pip.conf:/root/.config/pip/pip.conf
           - /data/llm-model:/data/llm-model
           - ./codes:/root/qwen_lora
         ports:
           - "9020:9020"
           - "9021:9021"
         command: /bin/bash /usr/local/start.sh
   ```

2. 修改finetune_lora_ds.sh中的MODEL和DATA参数

   ```bash
   MODEL="/data/llm-model/Qwen-7B"
   DATA="privacy_training.json"
   ```

3. 修改 `finetune.py` 脚本中的 `275` 行

   ```bash
   原来: device_map = "auto"
   现在: device_map = None
   ```

4. 执行微调脚本

   ```bash
   bash finetune/finetune_lora_ds.sh
   ```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python: 3.8.10
- Transformers: 4.32.0
- PyTorch: 2.0.1 
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

### 备注 | Anything else?

[
    {
        "id": "identity_1",
        "conversations": [
            {
                "from": "user",
                "value": "上文文本信息为: 对于儿童个人信息，我们会进一步采取以下措施："
            },
            {
                "from": "assistant",
                "value": "好的, 请告诉我下文文本信息"
            },
            {
                "from": "user",
                "value": "下文文本信息为: （2）当您作为监护人为被监护的儿童选择使用12306相关服务时，我们可能需要向您收集被监护的儿童个人信息，用于向您履行相关服务之必要。在具体服务中需要向您收集儿童个人信息的，我们会事先取得您的授权同意，并告知您收集的目的和用途。如果您不提供前述信息，您将无法享受我们提供的相关服务。您作为监护人应当正确履行监护职责，保护儿童个人信息安全。若儿童本人需要注册或使用我们的产品与/或服务，您应正确引导并予以监护。"
            },
            {
                "from": "assistant",
                "value": "好的, 请告诉我中间文本信息, 我将对中间文本做解析"
            },
            {
                "from": "user",
                "value": "隐私政策文本自动标注算法需要分析的中间文本为: （1）对于收集到的儿童个人信息，我们除遵守本隐私政策关于用户个人信息的约定外，还会秉持正当必要、知情同意、目的明确、安全保障、依法利用的原则，严格遵循《儿童个人信息网络保护规定》等法律法规的要求进行存储、使用、披露，且不会超过实现收集、使用目的所必须的期限，到期后我们会对儿童个人信息进行删除或匿名化处理。"
            },
            {
                "from": "assistant",
                "value": "根据隐私政策分类及属性表结合文本分析, 该文本的主要分类为: 未成年保护措施\n1: 原文文本中的 我们除遵守本隐私政策关于用户个人信息的约定外，还会秉持正当必要、知情同意、目的明确、安全保障、依法利用的原则，严格遵循《儿童个人信息网络保护规定》 可以划分为 未成年保护措施 分类.\n其中 《儿童个人信息网络保护规定》 可以识别为 单独的儿童隐私保护政策 属性.\n"
            }
        ]
    }
]

**Comment by oho-work** [comment]
宿主机的驱动信息如下：
![Snipaste_2024-01-02_11-20-15](https://github.com/QwenLM/Qwen/assets/115210234/35d5df0c-4fb4-4bd2-aa3b-0fe67ba839d6)
![Snipaste_2024-01-02_11-20-46](https://github.com/QwenLM/Qwen/assets/115210234/b0f923ae-1a4b-4969-a75b-da0db8cd6711)
希望能得到各位大佬帮助，十分感谢

**Comment by jklj077** [comment]
SIGTERM，一般是内存不够了。非ZeRO-3的话，可以device_map=None的同时试试把low_cpu_mem_usage=True。

**Comment by oho-work** [comment]
十分感谢您的回复，我是使用了low_cpu_mem_usage=True，得到的报错内容与之前的报错内容一致。
我没有修改其他部分的代码，使用的是ZeRO-2，这台服务器的内存是1TB的，应该不是内存溢出的原因。
在容器中，运行单卡lora微调的脚本，可以正确执行，就只是多卡微调会无报错的终止。
![Uploading Snipaste_2024-01-02_18-34-11.png…]()

**Comment by oho-work** [comment]
![Snipaste_2024-01-02_18-34-11](https://github.com/QwenLM/Qwen/assets/115210234/d90a69c3-8db8-479d-83fe-0930c409e1c0)

**Comment by oho-work** [comment]
> SIGTERM，一般是内存不够了。非ZeRO-3的话，可以device_map=None的同时试试把low_cpu_mem_usage=True。

十分感谢您的回复，我是使用了low_cpu_mem_usage=True，得到的报错内容与之前的报错内容一致。
我没有修改其他部分的代码，使用的是ZeRO-2，这台服务器的内存是1TB的，应该不是内存溢出的原因。
在容器中，运行单卡lora微调的脚本，可以正确执行，就只是多卡微调会无报错的终止。

单卡微调的运行截图如下：
![Snipaste_2024-01-02_18-34-11](https://github.com/QwenLM/Qwen/assets/115210234/81ea5988-fcbb-4bd5-bd2f-794c21d412b3)
