### ISSUE TITLE
[BUG] <title> 使用示例代码提示缺少文件 pytorch_model.bin.index.json

### ISSUE THREAD

**Issue by lianghongkey** [QwenLM/Qwen#902]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用示例的代码从 ms 和 hf 下载模型，都提示缺少文件错误，
ValueError: Can't find a checkpoint index (/home/colin/.cache/modelscope/hub/qwen/Qwen-1_8B-Chat/pytorch_model.bin.index.json) in /home/colin/.cache/modelscope/hub/qwen/Qwen-1_8B-Chat.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
国内请用MS的snapshot_download下载，提示缺少文件需要去检查是否有文件，缺文件的请重新下载或者手动下载。

**Comment by lianghongkey** [comment]
> 国内请用MS的snapshot_download下载，提示缺少文件需要去检查是否有文件，缺文件的请重新下载或者手动下载。

已经确定下载是完整的，我到 MS上去看也没有这个文件。 应该是没有上传。请帮忙确定下

https://modelscope.cn/models/qwen/Qwen-1_8B-Chat/files

**Comment by lianghongkey** [comment]
是需要自己手动从 model.safetensors.index.json  转换成 pytorch_model.bin.index.json 吗？
我看其他的开源的模型是有 “pytorch_model.bin.index.json”  这个文件的。
比如  ChatGLM3

**Comment by lianghongkey** [comment]
奇怪，重新安装了transformers 之后好像就好了。 可能是之前不小心改了 transformers的 code

**Comment by jklj077** [comment]
pytorch_model.bin.index.json是之前手动切的那种模型文件的索引，model.safetensors.index.json这个是用safetensors切的模型文件的索引，但从transformers 4.30版本开始就已经是默认行为了，之前版本需要加use_safetensors=True
