### ISSUE TITLE
请问一下能否开源一下工具调用的数据集呢，因为论文里写的感觉不是很清楚

### ISSUE THREAD

**Issue by wangjvjie** [QwenLM/Qwen#903]

**Comment by jklj077** [comment]
> 能否开源一下工具调用的数据集呢

目前无计划的。

> 论文里写的感觉不是很清楚

数据格式都有示例，https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py

不清楚的欢迎提问，能解答的会解答。

**Comment by gcxamy** [comment]
请问工具调用这个训练文件是调用的哪个呢？

**Comment by gcxamy** [comment]
还有不好意思请问这个和那个Qwen-agent关系是什么呢？如果在那里面的tools加了工具，怎么写工具调用数据集并训练呢？
