### ISSUE TITLE
[BUG] <title>Qwen-72B-Chat-Int4的本地模型加载打开失败

### ISSUE THREAD

**Issue by 15024287710Jackson** [QwenLM/Qwen#904]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/42542657/9b2a4f66-ea73-4621-b060-79cfafc40479)
![Qwen_加载问题](https://github.com/QwenLM/Qwen/assets/42542657/eccf3b64-6b1e-496b-ba65-f9574b5c39ea)
下载模型到本地后加载失败
![image](https://github.com/QwenLM/Qwen/assets/42542657/946d5183-4f7a-4f84-bae8-911e60866990)

### 复现方法 | Steps To Reproduce

执行该命令bash finetune/finetune_lora_ds.sh

### 运行环境 | Environment

```Markdown
- OS:Ubuntu18.04
- Python:3.8.12
- Transformers:4.32.0
- PyTorch:2.0.0+cu117
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

GPUS_PER_NODE=$(python -c 'import torch; print(torch.cuda.device_count())')
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001
OUTPUT_QWEN="/home/ma-user/work/qianwen/output/20230103Test72BInt4"
MODEL="/home/ma-user/work/qianwen/Qwen-72B-Chat-Int4" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="/home/ma-user/work/qianwen/Qwen-data/train.json"
DS_CONFIG_PATH="finetune/ds_config_zero2.json"

function usage() {
    echo '
Usage: bash finetune/finetune_lora_ds.sh [-m MODEL_PATH] [-d DATA_PATH] [--deepspeed DS_CONFIG_PATH]
'
}

while [[ "$1" != "" ]]; do
    case $1 in
        -m | --model )
            shift
            MODEL=$1
            ;;
        -d | --data )
            shift
            DATA=$1
            ;;
        --deepspeed )
            shift
            DS_CONFIG_PATH=$1
            ;;
        -h | --help )
            usage
            exit 0
            ;;
        * )
            echo "Unknown argument ${1}"
            exit 1
            ;;
    esac
    shift
done

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --fp16 True \
    --output_dir $OUTPUT_QWEN \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 512 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed ${DS_CONFIG_PATH}

**Comment by jklj077** [comment]
模型参数文件损坏，需要重新下载模型。国内环境建议使用README中的ModelScope的snapshot_download功能下载。
