### ISSUE TITLE
构建新的docker镜像时报错 unknown instruction: APT

### ISSUE THREAD

**Issue by haowuliao** [QwenLM/Qwen#907]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在4090上进行微调时，发现已有的官方镜像的cuda版本太低，不支持4090的架构，故重新基于官方的Dockerfile构建基于cuda12的镜像。把官方的Dockerfile 第一行改成 “ARG CUDA_VERSION=12.0.0”，然后执行“docker buildx build -t qwenllm:cu120 .”，发生报错，
![微信截图_20240103202537](https://github.com/QwenLM/Qwen/assets/21007668/07acf2ff-2cf1-467c-ae92-17e327ccda21)

### 期望行为 | Expected Behavior

是不是docker build的时候，还有其他需要设置的？

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by fyabc** [comment]
请尝试使用buildkit构建方式：`DOCKER_BUILDKIT=1 docker build -t qwenllm:cu120 .`

**Comment by haowuliao** [comment]
> 请尝试使用buildkit构建方式：`DOCKER_BUILDKIT=1 docker build -t qwenllm:cu120 .`

![微信截图_20240104092055](https://github.com/QwenLM/Qwen/assets/21007668/fe690ef0-b543-4f4c-ab52-bcea7595d925)
这个试过了，还是不行，，docker版本是Docker version 24.0.4, build 3713ee1 ，应该也不影响吧

**Comment by fyabc** [comment]
可以提供一下修改后的dockerfile吗？这边无法复现这个问题
或者可以尝试在build的时候指定`-f ${DockerFilePath}`，看能否修复这个问题

**Comment by jklj077** [comment]
@fyabc 可以提供个build好的cu121的版本吗？

**Comment by fyabc** [comment]
> @fyabc 可以提供个build好的cu121的版本吗？

好的，这边后续提供一下

**Comment by fyabc** [comment]
@haowuliao 您好，我们这边提供了新的镜像版本`qwenllm/qwen:cu121`，您可以尝试使用。

**Comment by haowuliao** [comment]
> @haowuliao 您好，我们这边提供了新的镜像版本`qwenllm/qwen:cu121`，您可以尝试使用。

好的，我试一下；不过，我后面发现，在原来的dockerfile第一行加上 # syntax=docker/dockerfile:1.4 ，并且把这个镜像pull下来，倒是可以正常构建镜像成功，是docker版本的原因吗
