### ISSUE TITLE
[BUG] <title> 1.8B 模型 system prompt 在部分情况下失效（ 如通过 fastchat.serve.openai_api_server ）

### ISSUE THREAD

**Issue by 1100111GTH** [QwenLM/Qwen#908]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

通过官方提供的 transformers 代码进行推理时系统指令无误，但是经过测试，通过 openaiapi 服务时写入指令则不会执行（ 经由第三方 github 项目 langchain-chatchat 设置系统指令时发现，后单独测试 api 确认问题。 ）
![CleanShot 2024-01-03 at 20 26 10](https://github.com/QwenLM/Qwen/assets/154310050/958ce23b-5ca2-4979-9b58-e66a72763796)
![CleanShot 2024-01-03 at 20 26 33](https://github.com/QwenLM/Qwen/assets/154310050/b035a759-90e1-4638-9400-65debdce4214)
![CleanShot 2024-01-03 at 20 26 49](https://github.com/QwenLM/Qwen/assets/154310050/1abaabad-c526-4020-99de-bef6c96a5eaf)
![CleanShot 2024-01-03 at 20 27 04](https://github.com/QwenLM/Qwen/assets/154310050/4e0f9b7e-1f68-41a5-8593-e86e4031c5d3)

### 期望行为 | Expected Behavior

正确执行 system prompt

### 复现方法 | Steps To Reproduce

1. 开启 fastchat controller
2. 开启 fastchat worker
3. 开启 fastchat openai_api_server
4. 本机测试 api

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04.4 LTS 
- Python: 3.8.10
- Transformers: 4.35.2
- PyTorch: 2.1.0+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by 1100111GTH** [comment]
能不能是因为 langchain?

**Comment by jklj077** [comment]
fastchat worker那里应该会输出模型实际输入的内容，可以看下system message是否有正确输入给模型。

**Comment by 1100111GTH** [comment]
> fastchat worker那里应该会输出模型实际输入的内容，可以看下system message是否有正确输入给模型。

我看查看 log 没有看到实际输入内容，不过在我重新创建环境并使用 fschat openai api 后 system prompt 可以生效了。目前仅知道出现错误的环境有接入 langchain 做 RAG，但因为是在第三方 github 项目环境中出现的问题（ autodl 镜像 ），我也找不到问题的源头在哪。
