### ISSUE TITLE
qwen-14b精调是否需要外推

### ISSUE THREAD

**Issue by LuoKaiGSW** [QwenLM/Qwen#909]
qwen-14b的context_length=8k，现在想在32k的文本上进行sft，看了一下config文件里面有一个use_dynamic_ntk=True的参数，这是不是代表着不需要再在sft时候进行长度外推。十分感谢🙏

**Comment by jklj077** [comment]
14B的序列长度支持已经是通过dynamic_ntk扩展到8K的了，原始是2K的，目前该模型通过长度扩展是无法支持32K的。
用本repo中的finetune.py的话，输入序列长度最好能达到8K、推理开启dynamic_ntk以支持32K，但长度扩展需要较多数据，实际效果不确定。训练中长度扩展的策略还是比较多的，PI、增大RoPE的base、LongLoRA之类的，建议对比看看。
