### ISSUE TITLE
Qwen-7B-Chat-Int4微调后推理结果偏差有点大

### ISSUE THREAD

**Issue by chesp** [QwenLM/Qwen#910]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

用Qwen-7B-Chat-Int4模型通过finetune_qlora_single_gpu微调后，推理的结果与真实数据之间的误差有点大，回答中的数值与训练数据中的数值相差有10来个百分点，请问这是什么因素造成的，能否通过什么办法改进？

### 期望行为 | Expected Behavior

能否通过什么减小与真实数据的误差范围

### 运行环境 | Environment

```Markdown
- OS:Ubuntu Server 18.04
- Python:3.10
- Transformers:4.35.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
```

**Comment by jklj077** [comment]
> 回答中的数值与训练数据中的数值

请问这个是什么任务呀，涉及到数值、数学的话，本身难度比较大，7B不一定能学会的（而且QLoRA需要多调参）。

**Comment by yawzhe** [comment]
我用70b的lora 10w条数据，怎么回答出来是这样呀                                                                                                                            我是一个大型语言模型，由 OpenAI 公司所研发的 AI 技术 GPT（Generative Pre-trained Transformer）所构建而成。ตี<br>กิจกรรม<br>ลิ<br>ไล่<br>ที่ดีที่สุด<br>ά<br>จักร<br>ด้วยความ<br>盧<br>عِ<br>มั้<br>แลนด์<br>ไม่สามารถ<br>هُمْ<br>更<br>สหรัฐ<br>อยู่ใน<br>〈<br>เดือน<br>บันทึก<br>益<br>อั<br>ตัน<br>ส่วน<br> มี<br>เทคโนโลยี<br>ปรสิ<br>นัก<br>ที่สำคัญ<br>ไก่<br>ดอกไม้<br>ยังไม่<br>ฤดูกาล<br>ไม่ค่อย<br>ไม่มี<br>ร้าย<br>هَا<br> ตุลาคม<br>เชียงใหม่<br>มิถุนายน<br>ทรั<br>พื<br>การสร้าง<br>กี<br>อังกฤษ<br>嘆<br>ตกแต่ง<br>ค่<br>รัฐ<br> อีกทั้ง<br> สิง<br>พื้นที่<br>ขนาดใหญ่<br>บังคับ<br>ชัด<br>เล่า<br>กัน<br>จู<br>เขียว<br>จัน<br>論<br>ไฟล์<br>คอมพิว<br>หัวใจ<br>สัญ<br>羅<br>ช่าง<br>ลุ<br>ới<br>ย่อม<br> يَ<br>珊<br>อัตโนมั<br>มากขึ้น<br>เศรษฐกิจ<br>靈<br>ể<br>ได้เลย<br>สิ่งที่<br>ฟรี<br>ไร้<br>ประโยชน์<br>บันเทิง<br>ด้าน<br>ฤดูกา<br>อุ<br>กรุณา<br>عَ<br>烈<br>อยู่ที่<br>洛<br>ขณะนี้<br>กว้าง<br>เรียนรู้<br> อีก<br>รองรับ<br>สร้าง<br>ใช้บริการ<br>ที่น่า<br>གྷ<br>ไปแล้ว<br>อันตร<br>取<br> จึง<br>มั่นใจ<br> เมื่อ<br> قَال<br>เจ้าหน้าที่<br>نِ<br>珊<br>ให้กับ<br>สงคร<br>聯<br>นะครับ<br>力<br>บาคาร่า<br>社<br>เริ่ม<br>女<br>เส้นทาง<br>กังวล<br>ที่มีความ<br>การเงิน<br>อร่อย<br>رِ<br>ในเรื่อง<br>สมัครสมาชิก<br>รายได้<br>การจัด<br>เกียร<br>ประทับใจ<br>นวัตกรรม<br>แชมป์<br>เสร็จ<br>โชว์<br>อันดับ<br>梁<br>ที่อยู่<br>ขึ้นมา<br>ชัดเจ<br>:-------------</<br>ต้อง<br>ต่างๆ<br>ดัง<br>ศักดิ<br>หรือไม่<br> ธันวาคม<br>ยังไ<br>ร่างกาย<br>แน่<br>รางวัล<br>เห็น<br>ฉัน<br>มิถุ<br>เด็ด<br>เค้า<br> ธันวา<br>เรื่อง<br>ทุกอย่าง<br>ริ<br>พิ<br>ศูน<br>เรื่<br>กุล<br>ก้าว<br>องค์กร<br>นักศึกษา<br>มีประสิทธิภาพ<br>ลงทุน<br>รหัส<br>โพสต์<br>พิษ<br>สัป<br>การแข่งข<br>ทักษะ<br>ปรสิต<br>ชาวบ้าน<br>ผู้นำ<br>â<br>มิถุน<br>เดี๋<br>ท้องถ<br>เพิ่ม<br>煉<br>บริการ<br>เชี่ยว<br>ו<br>แอร์<br>璉<br>ปิ<br> ตุลา<br>เคลื่อนไหว<br> ถ้า
