### ISSUE TITLE
💡 [REQUEST] - 新增100M级别小模型（speculative decode加速使用）

### ISSUE THREAD

**Issue by cermeng** [QwenLM/Qwen#912]
### 实现PR | Implementation PR

请问是否可以新增100M级别的小模型，在speculative加速中作为draft model使用(paper: arxiv.org/abs/2211.17192)？

### 摘要 | Summary

提供100M级别的小模型，在speculative加速中使用(paper: arxiv.org/abs/2211.17192)

### 基本示例 | Basic Example

提供100M级别的小模型，在speculative加速中使用(paper: arxiv.org/abs/2211.17192)

### 缺陷 | Drawbacks

提供100M级别的小模型，在speculative加速中使用(paper: arxiv.org/abs/2211.17192)

**Comment by JustinLin610** [comment]
Is the 1.8B not small enough? How about 500m? 100m's perf might be far from satisfaction.

**Comment by cermeng** [comment]
> Is the 1.8B not small enough? How about 500m? 100m's perf might be far from satisfaction.

Inference speed of small model will seriously affect the overall inference speed in speculative decode. Thus, this is a trade-off between inference speed (related to model size) and model performance. 500M model could be a better option. 

Since the performance of the draft model (small one) is not critical, what I want is just a smaller model (smaller than 1.8B) to evaluate acceleration ratio with speculative decode. 

I roughly estimate that we need
$\dfrac{\text{infer-speed(small model)}}{\text{infer-speed(big model)}}>10$
to get 1.5X inference acceleration.

There is a tiny llama example posted on Huggingface for your reference [llama-160m](https://huggingface.co/JackFram/llama-160m)

**Comment by awdrgyjilplij** [comment]
超极期待500m的qwen😄

**Comment by jklj077** [comment]
Qwen1.5-0.5B has been released.
