### ISSUE TITLE
vLLM还是不支持v100啊

### ISSUE THREAD

**Issue by boquanzhou** [QwenLM/Qwen#913]
@boquanzhou vLLM官方加了GPTQ的支持，那个v100应该可以的。

_Originally posted by @jklj077 in https://github.com/QwenLM/Qwen/issues/790#issuecomment-1873954121_
            

ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-PCIE-32GB GPU has compute capability 7.0.

**Comment by jklj077** [comment]
这个不是vLLM不支持v100哈，是v100不支持bf16。

启动的时候传参进去`--dtype half`，https://docs.vllm.ai/en/latest/models/engine_args.html#cmdoption-dtype
