### ISSUE TITLE
为什么14B-int4的推理时间比14B的慢很多

### ISSUE THREAD

**Issue by boquanzhou** [QwenLM/Qwen#914]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
提供下相关信息吧，缺少有效信息，很难有针对性回复的。

最常见问题：
- auto-gptq安装不正确（跟pytorch pytorch-cuda版本不匹配）；解决方案，建议按auto-gpt官方说明安装
- 多卡+大batch推理，会慢一些，但“很多”这个不确定；解决方案，建议用FastChat+vLLM

**Comment by boquanzhou** [comment]
没有用到装auto-gptq啊，只是用了14B的模型来chat，没有训练。

> 提供下相关信息吧，缺少有效信息，很难有针对性回复的。
> 
> 最常见问题：
> 
> * auto-gptq安装不正确（跟pytorch pytorch-cuda版本不匹配）；解决方案，建议按auto-gpt官方说明安装
> * 多卡+大batch推理，会慢一些，但“很多”这个不确定；解决方案，建议用FastChat+vLLM

**Comment by jklj077** [comment]
14B-Int4加载是需要auto-gptq的。

**Comment by boquanzhou** [comment]
> Qwen-14B-Chat-Int4加载（无论推理还是训练）是需要auto-gptq的，请看README: https://github.com/QwenLM/Qwen/blob/main/README_CN.md#gptq

那如何用vLLM加载14B-int4呢

**Comment by jklj077** [comment]
请看README。

**Comment by baisechundu** [comment]
> > Qwen-14B-Chat-Int4加载（无论推理还是训练）是需要auto-gptq的，请看README: https://github.com/QwenLM/Qwen/blob/main/README_CN.md#gptq
> 
> 那如何用vLLM加载14B-int4呢

Here is a repo, it works for me: 
https://github.com/QwenLM/vllm-gptq

**Comment by micronetboy** [comment]
正确安装了 auto-gptq. 通过 vLLM 运行。量化模型要比非量化模型慢一倍。
use the following vllm_wrapper:
https://github.com/QwenLM/vllm-gptq/blob/main/tests/qwen/vllm_wrapper.py

**Comment by jklj077** [comment]
> 正确安装了 auto-gptq. 通过 vLLM 运行

这俩无关哈。Fast+vLLM部署量化模型不依赖auto-gptq。

QwenLM/vllm-gptq在一些场景下是会慢，建议用vLLM官方的最新版，已经合并了GPTQ的支持，整体效率上会更好。如有更多效率问题请咨询vLLM官方。
