### ISSUE TITLE
💡 [REQUEST] -  请问啥时候14b和7b可以修改system。最近用了72b修改system，非常不错。

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen#918]
### 实现PR | Implementation PR

如题。

### 相关Issues | Reference Issues

无

### 摘要 | Summary

无

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

### 未解决问题 | Unresolved questions

无

**Comment by jklj077** [comment]
模型近期有更新计划（包括7B和14B的system支持、14B的输入序列长度扩展），敬请期待。

**Comment by Lyzin** [comment]
> 模型近期有更新计划（包括7B和14B的system支持、14B的输入序列长度扩展），敬请期待。

非常期待可以支持system
