### ISSUE TITLE
词表裁剪后编码单个词正常，重复单个词或多个词no entry found for key

### ISSUE THREAD

**Issue by andrewhuman** [QwenLM/Qwen#921]
比如过滤中文词表，
1 把qiwen.tiktoken里面的对应词表过滤后保存，词表大小为25554，最后一位是25553

2修改 tokenization_qwen.py
        SPECIAL_START_ID = 25554
3 加载Tokenizer分词，转成id，词表里含有的词或词组正常
       tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
       input_ids = tokenizer('风', return_tensors='pt',add_special_tokens=False).input_ids可以正常编码，
4 把单个词重复或多个词组合，比如
        input_ids = tokenizer('风风', return_tensors='pt',add_special_tokens=False).input_ids，会报错：
       thread '<unnamed>' panicked at src/lib.rs:104:45:
       no entry found for key

5：
thread '<unnamed>' panicked at src/lib.rs:104:45:
no entry found for key
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:168:5
   3: core::panicking::panic_str
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1988:5
   5: _tiktoken::_byte_pair_merge
   6: _tiktoken::CoreBPE::_encode_native
   7: _tiktoken::_::<impl _tiktoken::CoreBPE>::__pymethod_encode__
   8: pyo3::impl_::trampoline::fastcall_with_keywords
   9: method_vectorcall_FASTCALL_KEYWORDS
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/descrobject.c:405
  10: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  11: PyObject_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:123
  12: call_function
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5867
  13: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4198
  14: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  15: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  16: _PyFunction_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:342
  17: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  18: method_vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/classobject.c:53
  19: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  20: PyObject_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:123
  21: call_function
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5867
  22: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4231
  23: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  24: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  25: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  26: method_vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/classobject.c:83
  27: PyVectorcall_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:255
  28: _PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:290
  29: PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:317
  30: do_call_core
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5919
  31: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4277
  32: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  33: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  34: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  35: PyObject_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:123
  36: call_function
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5867
  37: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4213
  38: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  39: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  40: _PyFunction_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:342
  41: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  42: method_vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/classobject.c:53
  43: PyVectorcall_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:267
  44: _PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:290
  45: PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:317
  46: do_call_core
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5919
  47: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4277
  48: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  49: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  50: _PyFunction_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:342
  51: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  52: method_vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/classobject.c:53
  53: PyVectorcall_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:267
  54: _PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:290
  55: PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:317
  56: do_call_core
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5919
  57: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4277
  58: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  59: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  60: _PyFunction_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:342
  61: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:114
  62: method_vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/classobject.c:53
  63: PyVectorcall_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:267
  64: _PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:290
  65: PyObject_Call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:317
  66: do_call_core
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5919
  67: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4277
  68: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  69: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  70: _PyObject_FastCallDictTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:153
  71: _PyObject_Call_Prepend
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:431
  72: slot_tp_call
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/typeobject.c:7489
  73: _PyObject_MakeTpCall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Objects/call.c:215
  74: _PyObject_VectorcallTstate
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:112
  75: PyObject_Vectorcall
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/cpython/abstract.h:123
  76: call_function
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5867
  77: _PyEval_EvalFrameDefault
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:4231
  78: _PyEval_EvalFrame
             at /opt/conda/conda-bld/python-split_1648715631366/work/Include/internal/pycore_ceval.h:46
  79: _PyEval_Vector
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:5065
  80: PyEval_EvalCode
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/ceval.c:1134
  81: run_eval_code_obj
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/pythonrun.c:1291
  82: run_mod
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/pythonrun.c:1312
  83: pyrun_file
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/pythonrun.c:1208
  84: _PyRun_SimpleFileObject
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/pythonrun.c:456
  85: _PyRun_AnyFileObject
             at /opt/conda/conda-bld/python-split_1648715631366/work/Python/pythonrun.c:90
  86: pymain_run_file_obj
             at /opt/conda/conda-bld/python-split_1648715631366/work/Modules/main.c:357
  87: pymain_run_file
             at /opt/conda/conda-bld/python-split_1648715631366/work/Modules/main.c:376
  88: pymain_run_python
             at /opt/conda/conda-bld/python-split_1648715631366/work/Modules/main.c:591
  89: Py_RunMain
             at /opt/conda/conda-bld/python-split_1648715631366/work/Modules/main.c:670
  90: Py_BytesMain
             at /opt/conda/conda-bld/python-split_1648715631366/work/Modules/main.c:1083
  91: __libc_start_main
             at /build/glibc-S7Ft5T/glibc-2.23/csu/../csu/libc-start.c:291
  92: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/data2/asr/as_transfrom_test/Firefly/script/train_prun.py", line 25, in <module>
    input_ids = tokenizer('风风', return_tensors='pt',add_special_tokens=False).input_ids
  File "/root/anaconda2/envs/torch113tr432/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2602, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/anaconda2/envs/torch113tr432/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2708, in _call_one
    return self.encode_plus(
  File "/root/anaconda2/envs/torch113tr432/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/root/anaconda2/envs/torch113tr432/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "/root/anaconda2/envs/torch113tr432/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat-prun/tokenization_qwen.py", line 219, in tokenize
    for t in self.tokenizer.encode(
  File "/root/anaconda2/envs/torch113tr432/lib/python3.10/site-packages/tiktoken/core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)

**Comment by jklj077** [comment]
> “修改原始设计要慎之又慎”

**Comment by andrewhuman** [comment]
请问目前可以支持裁剪吗

**Comment by jklj077** [comment]
不太确定这个裁剪指的是什么哈，一般bpe词表都是不能随便动的。可以去看看tokenization_note里的说明，对于Qwen用的byte-level bpe，词表等价于merge表，裁剪不对的话，merge表就坏了。不过，一般至多就merge不出来，不会报错；你这个直接报错，怕不是把单个byte都给裁了。

**Comment by jordddan** [comment]
> 请问目前可以支持裁剪吗

裁剪成功了么，我也碰到了同样的问题
