### ISSUE TITLE
cache_autogptq_cuda_356.cpp与cache_autogptq_cuda_kernel_245.cu有下载链接吗，内外网都搜了只找到256和256的

### ISSUE THREAD

**Issue by zzwtop1** [QwenLM/Qwen#924]
cache_autogptq_cuda_356.cpp与cache_autogptq_cuda_kernel_245.cu有下载链接吗，内外网都搜了只找到256和256的

**Comment by jklj077** [comment]
cache_autogptq_cuda_256.cpp和cache_autogptq_cuda_kernel_256.cu中含有KV Cache Quantization使用的8bit kernel实现。
- 256的含义是kernel launch时使用的线程组大小(block size)
- 根据[CUDA Best Practice](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#thread-and-block-heuristics)，一般情况下，block size应为32的倍数，128~256是较好的初始值
- 您所提供的两个block size，均不是32的倍数，245甚至是奇数，我们认为不会有此类调用，也不会有这样的代码实现

**Comment by zzwtop1** [comment]
> cache_autogptq_cuda_256.cpp和cache_autogptq_cuda_kernel_256.cu中含有KV Cache Quantization使用的8bit kernel实现。
> 
> * 256的含义是kernel launch时使用的线程组大小(block size)
> * 根据[CUDA Best Practice](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#thread-and-block-heuristics)，一般情况下，block size应为32的倍数，128~256是较好的初始值
> * 您所提供的两个block size，均不是32的倍数，245甚至是奇数，我们认为不会有此类调用，也不会有这样的代码实现

大哥要不你看一下你们readme里写的什么。。。
![image](https://github.com/QwenLM/Qwen/assets/102272958/afbc7f09-abe9-4f24-b2fd-9a0b5df4e034)

**Comment by jklj077** [comment]
em... 非常奇怪，en里是256跟245。。。我们fix下。
