### ISSUE TITLE
[BUG]  Qwen-14B-Chat-Int4 使用 vLLM 并没有加速？

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#925]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen-14B-Chat-Int4 使用 vLLM 并没有加速？测试对比，和不使用vLLM 速度一样，使用vLLM并没有带来加速。
使用的如下的方式：
https://github.com/QwenLM/vllm-gptq/blob/main/tests/qwen/vllm_wrapper.py

### 期望行为 | Expected Behavior

Qwen-14B-Chat-Int4 使用 vLLM 应该有明显的加速

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
vLLM官方已经支持GPTQ了，建议先用那个试试吧，QwenLM/vllm-gptq这个后面不太会维护了。

**Comment by xx-Jiangwen** [comment]
> vLLM官方已经支持GPTQ了，建议先用那个试试吧，QwenLM/vllm-gptq这个后面不太会维护了。

您好，并没在vLLM官网文档上看见gptq参数呢，--quantization (-q) {awq,squeezellm,None}
Method used to quantize the weights.

**Comment by jklj077** [comment]
vLLM版本需要大于0.2.6，--quantization gqtq就可以的。

**Comment by jklj077** [comment]
需要说明，vLLM的速度提升一般指的是 **吞吐量 (throughput)** 提升导致的总体速度提升，对于单一请求的速度，即延迟(latency)，差异不会很大。

对于非量化模型，README中72B模型上，vLLM的速度与transformers的速度差异来自于多卡并行方式不同:
- vLLM是tensor parallel，transformers是model parallel
- 由于model parallel同时只有一张卡在运算，而tensor parallel是多卡同时计算
- 多卡下vLLM的延迟会低很多

对于GPTQ量化模型：
- transformers使用的auto-gptq，最新版采用是exllama v2 kernel
- vLLM采用的量化相关算子也是基于exllama v2 kernel的，这里也并无速度/延迟上的优势
- vLLM推理量化模型主要是因为显存占用降低，进一步提升吞吐
