### ISSUE TITLE
[BUG] Qwen-14B-Chat-Int4 GPTQ model is slower than original model Qwen-14B-Chat greatly

### ISSUE THREAD

**Issue by micronetboy** [QwenLM/Qwen#930]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen-14B-Chat-Int4 GPTQ model is slower than original model Qwen-14B-Chat greatly

### 期望行为 | Expected Behavior

Qwen-14B-Chat-Int4 GPTQ model should be close to original model Qwen-14B-Chat in speed.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Please DO follow the issue template to provide steps to reproduce for us to investigate the issue.

**Comment by jklj077** [comment]
Closed as essentially the same as https://github.com/QwenLM/Qwen/issues/850
