### ISSUE TITLE
[BUG] 千问1.8b在gpu推理且温度小于等于0.5情况下出错

### ISSUE THREAD

**Issue by pengbj** [QwenLM/Qwen#931]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen/Qwen-1_8B-Chat gpu加载情况下，如果设置温度值在0.50及以下报错：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 1
----> 1 model.chat(query='你好', history=[], tokenizer=tokenizer, temperature=0.50)

File ~/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py:1137, in QWenLMHeadModel.chat(self, tokenizer, query, history, system, stream, stop_words_ids, generation_config, **kwargs)
   1133 stop_words_ids.extend(get_stop_words_ids(
   1134     generation_config.chat_format, tokenizer
   1135 ))
   1136 input_ids = torch.tensor([context_tokens]).to(self.device)
-> 1137 outputs = self.generate(
   1138             input_ids,
   1139             stop_words_ids=stop_words_ids,
   1140             return_dict_in_generate=False,
   1141             generation_config=generation_config,
   1142             **kwargs,
   1143         )
   1145 response = decode_tokens(
   1146     outputs[0],
   1147     tokenizer,
   (...)
   1152     errors='replace'
   1153 )
   1155 # as history is a copy of the user inputs,
   1156 # we can always return the new turn to the user.
   1157 # separating input history and output history also enables the user
   1158 # to implement more complex history management

File ~/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py:1259, in QWenLMHeadModel.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, **kwargs)
   1256     else:
   1257         logits_processor.append(stop_words_logits_processor)
-> 1259 return super().generate(
   1260     inputs,
   1261     generation_config=generation_config,
   1262     logits_processor=logits_processor,
   1263     stopping_criteria=stopping_criteria,
   1264     prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
   1265     synced_gpus=synced_gpus,
   1266     assistant_model=assistant_model,
   1267     streamer=streamer,
   1268     **kwargs,
   1269 )

File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:1642, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1634     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1635         input_ids=input_ids,
   1636         expand_size=generation_config.num_return_sequences,
   1637         is_encoder_decoder=self.config.is_encoder_decoder,
   1638         **model_kwargs,
   1639     )
   1641     # 13. run sample
-> 1642     return self.sample(
   1643         input_ids,
   1644         logits_processor=logits_processor,
   1645         logits_warper=logits_warper,
   1646         stopping_criteria=stopping_criteria,
   1647         pad_token_id=generation_config.pad_token_id,
   1648         eos_token_id=generation_config.eos_token_id,
   1649         output_scores=generation_config.output_scores,
   1650         return_dict_in_generate=generation_config.return_dict_in_generate,
   1651         synced_gpus=synced_gpus,
   1652         streamer=streamer,
   1653         **model_kwargs,
   1654     )
   1656 elif generation_mode == GenerationMode.BEAM_SEARCH:
   1657     # 11. prepare beam search scorer
   1658     beam_scorer = BeamSearchScorer(
   1659         batch_size=batch_size,
   1660         num_beams=generation_config.num_beams,
   (...)
   1665         max_length=generation_config.max_length,
   1666     )

File /opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:2760, in GenerationMixin.sample(self, input_ids, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, streamer, **model_kwargs)
   2758 # sample
   2759 probs = nn.functional.softmax(next_token_scores, dim=-1)
-> 2760 next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
   2762 # finished sentences should have their next token be a padding token
   2763 if eos_token_id is not None:

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### 运行环境 | Environment

```Markdown
- OS: Centos 8
- Python: 3.10
- Transformers: 4.32.0
- PyTorch: 2.0.1
- CUDA 11.7
```

### 备注 | Anything else?

仅在gpu且温度 <=0.5 情况下必定出现，大于0.5时正常。在多个环境测试均如此。
![image](https://github.com/QwenLM/Qwen/assets/29790068/1d76b4f0-1f7d-4cf0-929c-e2f282d64243)
![image](https://github.com/QwenLM/Qwen/assets/29790068/fbd4dfc0-7661-4389-b633-8ad76bb0883f)

**Comment by jklj077** [comment]
请参考issue区中的历史问题，Qwen模型不建议调整temperature，建议调整top_p或top_k的设置。如果您调整了temperature，出现`probability tensor contains either inf, nan or element < 0`是预期中的现象。
