### ISSUE TITLE
💡 [REQUEST] - <title>多机多卡推理inference using multiple machines and multiple GPUs

### ISSUE THREAD

**Issue by crowdin001** [QwenLM/Qwen#932]
### 起始日期 | Start Date

2024-01-09

### 实现PR | Implementation PR

请问有没有多机多卡使用docker进行推理的教程。
Do you have a tutorial on using Docker for inference on multiple machines and cards

### 摘要 | Summary

请问有没有多机多卡使用docker进行推理的教程，可以使用多机多卡进行推理
Do you have a tutorial on using Docker for inference on multiple machines and cards

### 基本示例 | Basic Example

如何使用两台4*A100-40G进行72B的推理

### 缺陷 | Drawbacks

单机单卡的显存不足，如何使用两台4*A100-40G进行72B的推理

**Comment by jklj077** [comment]
目前我们没有单模型跨机推理的经验可以分享。
We are not experienced in single-model multi-node inference.

据我们所知
- HuggingFace系列框架尚未支持该特性
- [vLLM官方文档](https://docs.vllm.ai/en/latest/serving/distributed_serving.html)称可利用ray实现模型多机推理
- 其它的第三方框架可支持，但需要进行相应的转换、配置，如[alpa提供了多机OPT推理的示例](https://alpa.ai/tutorials/opt_serving.html)，但需要注意alpa已停止维护，新模型适配可能很麻烦

To our knowledge
- HuggingFace ecosystems lack support of this feature
- [Documentation of vLLM](https://docs.vllm.ai/en/latest/serving/distributed_serving.html) state that single-model multi-node inference is viable with ray
- Other frameworks may support this scenario but may require complex preparation. For example, [alpa provides a tutorial to run OPT with multi-node inference](https://alpa.ai/tutorials/opt_serving.html), but please be aware that it is not actively maintained any more. Adding new models can be difficult.

我们建议先从vLLM开始尝试。
We advise that you first try vLLM.

**Comment by xinzaifeixiang1992** [comment]
vLLM进行单机多卡已经代码实现了，这种方式具体看下qwen官方的文档(利用vLLM进行加速的)
