### ISSUE TITLE
[BUG] <title>微调完了之后，chat回答的不是微调的数据

### ISSUE THREAD

**Issue by kriends** [QwenLM/Qwen#935]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

模型：Qwen-7B-Chat-Int4，使用的 lora 单卡训练脚本，训练完之后输出正常
![image](https://github.com/QwenLM/Qwen/assets/14156067/6491cf30-a5f9-4b17-a8a2-2f4554207ccb)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by kriends** [comment]
这两种我都试过

**Comment by kriends** [comment]
> 您好，请问您使用的是`finetune/finetune_lora_ds.sh`还是`finetune/finetune_qlora_ds.sh`进行的微调？对于Int4量化模型，应当使用后者进行微调，前者的微调结果可能存在问题。

这两种我都试过，不管用

**Comment by jklj077** [comment]
建议您提供更多信息，以便我们辅助您分析问题，如
- 是否有尝试过调整QLoRA的训练参数，由于QLoRA微调难度较大，可能需要多尝试
- 使用了何种类型的数据、数据量有多大，对于特定类型的数据，QLoRA可能很难更改模型行为、需要更多同类数据
- 提供可复现的步骤是最为有效的方式

**Comment by KingYoungY** [comment]
你微调数据量大概多少条，太少的话微调是没效果的。一般上万条 微调效果就出来了
