### ISSUE TITLE
[BUG]   Input data may contain inappropriate content. api error...

### ISSUE THREAD

**Issue by jun0wanan** [QwenLM/Qwen#938]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

when I give the input to it , it can not give me the answer, and  it says that "Input data may contain inappropriate content."

I use the 

'status_code':
400
'request_id':
'17f9c41d-fbbd-9a78-a35e-e36dcb774c23'
'code':
'DataInspectionFailed'
'message':
'Input data may contain inappropriate content.'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
@jun0wanan Hi, what were you using?

**Comment by jklj077** [comment]
I think you were using the DashScope API. DashScope is a product of Alibaba Cloud and please contact its official support. It is not covered in this project.

Here is what I have found though: <https://help.aliyun.com/zh/dashscope/developer-reference/return-status-code-description>

**Comment by jun0wanan** [comment]
> @jun0wanan Hi, what were you using?

你好，
所以这个问题是阿里云api的问题吗？

qwen-vl还有除了阿里云其他的api吗？

**Comment by jklj077** [comment]
If you're working with Qwen-VL, kindly note that there are accessible models available at <https://github.com/QwenLM/Qwen-VL>. I would strongly recommend reaching out to them for guidance and support. Thank you for your collaboration.
