### ISSUE TITLE
[BUG] Lora训练出来没有adapter_model.bin

### ISSUE THREAD

**Issue by tianyouyangying** [QwenLM/Qwen#940]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

lora微调后 生成了如下文件
-rw-r--r-- 1 root root       569 Jan  9 18:16 adapter_config.json
-rw-r--r-- 1 root root 104868128 Jan  9 18:16 adapter_model.safetensors
-rw-r--r-- 1 root root       165 Jan  9 18:16 all_results.json
-rw-r--r-- 1 root root   2561218 Jan  9 18:16 qwen.tiktoken
-rw-r--r-- 1 root root      1233 Jan  9 18:16 README.md
-rw-r--r-- 1 root root        64 Jan  9 18:16 special_tokens_map.json
-rw-r--r-- 1 root root      9618 Jan  9 18:16 tokenization_qwen.py
-rw-r--r-- 1 root root       362 Jan  9 18:16 tokenizer_config.json
-rw-r--r-- 1 root root      1670 Jan  9 18:16 trainer_log.jsonl
-rw-r--r-- 1 root root      1387 Jan  9 18:16 trainer_state.json
-rw-r--r-- 1 root root      4920 Jan  9 18:16 training_args.bin
-rw-r--r-- 1 root root       165 Jan  9 18:16 train_results.json
没有生成adapter_model.bin

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
从peft 0.7.0版本开始，参数存储默认采用safetensors，您提供的文件列表中，已经包含了adapter_model.safetensors这个文件，微调是正常结束的，应可以正常使用。如在使用中遇到了问题，请提供具体问题。
