### ISSUE TITLE
LoRA微调显存占用很大，A10*4

### ISSUE THREAD

**Issue by Matteyes** [QwenLM/Qwen#941]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

DS_CONFIG_PATH="finetune/ds_config_zero2.json"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 1024 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed ${DS_CONFIG_PATH}

![762e8ad28b6e69ef810ccd5307efd1c](https://github.com/QwenLM/Qwen/assets/32762315/bfee077e-d3c3-48de-b9ee-4de03e504430)

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python: 3.10.13
- Transformers: 4.32.0
- PyTorch: 2.1.0
- CUDA 12.1
```

**Comment by Matteyes** [comment]
装了flash attention

**Comment by Matteyes** [comment]
模型是7B-chat.。。14B直接调不动

**Comment by LotuSrc** [comment]
lora fp16,14B光模型参数都28G左右了吧，肯定调不动啊

**Comment by Matteyes** [comment]
> lora fp16,14B光模型参数都28G左右了吧，肯定调不动啊

啊？那我这能调多少精度的啊

**Comment by jklj077** [comment]
[README中有相关数据](https://github.com/QwenLM/Qwen#profiling-of-memory-and-speed)，建议参考看下。单卡LoRA微调7B-Chat，序列长度1024的话，显存占用21.5GB.

由于LoRA微调时可训练的参数相对较少，DeepSpeed ZeRO-2多卡间切分梯度的方式能够减少的显存占用也相对更少。我理解您的显存占用情况是正常的（除了全量微调，LoRA/QLoRA用多卡训练时单卡显存占用不会明显比单卡训练少）。针对LoRA微调7B-Chat模型这个场景，建议试试ZeRO-3 + cpu offloading，单卡显存占用幅度能再降低一些。

对于14B-Chat模型，根据README中的信息，24GB显卡只能用QLoRA微调14B-Chat-Int4模型。
