### ISSUE TITLE
在readme中长文本理解中：“通过arXiv数据集上的语言模型实验，发现 Qwen 在长上下文场景下可以达到出色的性能”，这个arXiv数据集是怎么构造的？

### ISSUE THREAD

**Issue by lvjianxin** [QwenLM/Qwen#942]
我看arXiv数据集都是一些论文，怎么去构造问题和答案，来验证模型的长文本能力呢？

**Comment by jklj077** [comment]
这里“语言模型”指的是language modeling这个任务哈，指标是困惑度（perplexity），针对这个数据是没有构造问答对的。
也有其它任务的评测，比如needle in a haystack。
更多NLP任务的可以参考以下issue （比较久了，仅供参考，针对的都是使用DynamicNTK扩展序列长度的模型）
- https://github.com/QwenLM/Qwen/issues/107
