### ISSUE TITLE
Qlora 合并💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by olin-Ai** [QwenLM/Qwen#943]
### 实现PR | Implementation PR

使用Qlora int-4训练成功

### 相关Issues | Reference Issues

请问什么时候能支持Qlora 的模型合并？想进行后续的增量训练！

### 摘要 | Summary

请问什么时候能支持Qlora 的模型合并？想进行后续的增量训练！

### 基本示例 | Basic Example

请问什么时候能支持Qlora 的模型合并？想进行后续的增量训练！

### 缺陷 | Drawbacks

请问什么时候能支持Qlora 的模型合并？想进行后续的增量训练！

### 未解决问题 | Unresolved questions

请问什么时候能支持Qlora 的模型合并？想进行后续的增量训练！

**Comment by jklj077** [comment]
Please search the issues for responses. As Qwen adopts GPTQ, in theory, you cannot merge Q-LoRA adapters to get an int4 model. But you can merge the adapters to the original model to get an fp16 model.
