### ISSUE TITLE
vLLM和LORA的问题[BUG] <title>

### ISSUE THREAD

**Issue by xx-Jiangwen** [QwenLM/Qwen#944]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

以Qwen-14B-int4为例，采用QLORA微调。量化模型和QLORA不支持合并，那vLLM是否能对两者进行加速呢？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by anaivebird** [comment]
@xx-Jiangwen 老哥解决了吗

**Comment by jklj077** [comment]
It seems vLLM has supported loading LoRA adapters: <https://docs.vllm.ai/en/latest/models/lora.html>. Qwen1.5 (not Qwen(1.0)) is supported in the main branch.
