### ISSUE TITLE
进行微调，进度条始终没有动过，而单机多卡微调也出现奇怪的错误<title>

### ISSUE THREAD

**Issue by SuperTom99** [QwenLM/Qwen#945]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/88136413/93e54600-2199-43be-bf96-46eb591f842a)
如图所示，我使用lora_single_gpu进度条根本没有动过，rank只设置了4
而使用多卡脚本则出现
![image](https://github.com/QwenLM/Qwen/assets/88136413/b420a149-1af4-4744-957a-bb75edf2060c)

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.9
- Transformers:4.32
- PyTorch:1.12
- CUDA :11.6
```

**Comment by jklj077** [comment]
单卡问题，请先参考提示处理：kernel 5.4.0版本低于推荐的5.5.0版本，可能导致进程hang（“卡住”）。

多卡的报错请执行`python -c 'import torch; print(torch.cuda.device_count())'`看下是否有识别到多张卡。
