### ISSUE TITLE
[BUG] kv cache报错

### ISSUE THREAD

**Issue by sunchao2828** [QwenLM/Qwen#947]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

按照官方文档执行了kv cache，cache_autogptq_cuda_256.cpp与cache_autogptq_cuda_kernel_256.cu也已放在代码执行的同目录下，但是提示找不到cache_autogptq_cuda_256.so文件，同时也没有开始编译。
![image](https://github.com/QwenLM/Qwen/assets/54134307/ae0eddb6-f6bf-4804-a368-e7e3a9255e3b)
![image](https://github.com/QwenLM/Qwen/assets/54134307/7ad0e31e-e711-4c62-9b11-726972697ee4)

### 期望行为 | Expected Behavior

请大佬告知一下如何解决

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.32.0
- Torch:1.21.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.4
```

**Comment by jklj077** [comment]
kv cache quantization needs custom kernels which appear to be missing. It is hard to pinpoint the exact cause, but compiling errors are most common (for example, your cuda nad torch version could be too old to support the kernels).

In addition, we advise you to try [vLLM for kv cache quantization](https://docs.vllm.ai/en/latest/quantization/fp8_e5m2_kv_cache.html) as related code in Qwen(1.0) is not longer maintained.
