### ISSUE TITLE
💡 [REQUEST] -Qwen-72B-Chat使用AutoGptQ量化完后的目录，跟官网公布的Qwen-72B-Chat-Int4目录存在一些配置文件差异

### ISSUE THREAD

**Issue by lifengyu2005** [QwenLM/Qwen#950]
### 起始日期 | Start Date

2024-01-12

### 摘要 | Summary

72B使用AutoGptQ量化完后，文件少一些配置文件;官网公布的Qwen-72B-Chat-Int4里面有各种配置文件；目录整体大小39G是一样的；这个有啥转换工具吗

### 基本示例 | Basic Example

量化后的文件截图

![image](https://github.com/QwenLM/Qwen/assets/37462821/55fc1190-aafb-45ef-9e74-b0efa9c0a85f)

### 缺陷 | Drawbacks

最好提供一个工具

**Comment by lifengyu2005** [comment]
![72B-int4](https://github.com/QwenLM/Qwen/assets/37462821/3d24702a-5659-403c-a165-79f1c7207d56)

**Comment by jklj077** [comment]
1. 把缺的文件复制到这里
2. 比对quantize_config.json和config.json中相关部分
3. 如果要用transformers加载，*.safetensors重命名为model.safetensors，相应修改quantize_config.json和config.json。

**Comment by jklj077** [comment]
README中已有相关说明，请参考查看 https://github.com/QwenLM/Qwen#quantize-fine-tuned-models
