### ISSUE TITLE
zero2 lora微调内存异常升高，等待时间过长

### ISSUE THREAD

**Issue by liyang1023** [QwenLM/Qwen#954]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用lora方式微调，利用zero2时会卡住，内存一直升高直到崩溃
![zero2_error](https://github.com/QwenLM/Qwen/assets/54017899/720b1efb-a4a9-4646-bbd9-f9c8d6d2cf52)

### 期望行为 | Expected Behavior

可以使用low_cpu_mem_usage = True的方式避免这个问题，在finetune文件中294行，提前定义model_load_kwargs = {'low_cpu_mem_usage': True} 即可，试验验证ok

### 运行环境 | Environment

```Markdown
OS: Ubuntu 20.04
    Python: 3.8
    Transformers: 4.31.0
    PyTorch: 2.0.1
    CUDA: 11.7
```

**Comment by liyang1023** [comment]
![and_or](https://github.com/QwenLM/Qwen/assets/54017899/4a669f29-6ea3-4826-9447-b09a1ae70f7b)
同时316行中的and条件需要改为or才有效

**Comment by jklj077** [comment]
@fyabc 请再处理下device_map和low_cpu_mem_usage的关系。

@liyang1023 316行不能这样修改。

**Comment by fyabc** [comment]
@jklj077 @liyang1023 已修复`finetune.py`中的相应代码，请拉取代码重新尝试一下。
