### ISSUE TITLE
messages中"role": "system"的顺序问题（上一个提问不小心关掉了）

### ISSUE THREAD

**Issue by huangyunxin** [QwenLM/Qwen#956]
**我的环境**
docker镜像版本qwenllm/qwen:cu117，模型为Qwen-14B-Chat

**请求/v1/chat/completions参数如下：**
`{
    "model": "qwen",
    "temperature": 0.8,
    "top_p": 1,
    "stream": false,
    "messages": [
        {
            "role": "user",
            "content": "你好"
        },
        {
            "role": "assistant",
            "content": "你好！有什么我可以帮助你的吗？"
        },
        {
            "role": "system",
            "content": "你的同事名字是张三，我的问题是："
        },
        {
            "role": "user",
            "content": "你好"
        }
    ]
}`
**请求后报错：**`"detail": "Invalid request: Incorrect role system."`
**我发现改变"role": "system"的位置，可以成功，正确参数如下：**
`{
    "model": "qwen",
    "temperature": 0.8,
    "top_p": 1,
    "stream": false,
    "messages": [
        {
            "role": "system",
            "content": "你的同事名字是张三，我的问题是："
        },
        {
            "role": "user",
            "content": "你好"
        },
        {
            "role": "assistant",
            "content": "你好！有什么我可以帮助你的吗？"
        },
        {
            "role": "user",
            "content": "你好"
        }
    ]
}`
**请问"role": "system"的消息必须放在第一个吗？**

**Comment by jklj077** [comment]
是的，目前支持system的模型，请求时system需要为第一条message。

另：Qwen-14B-Chat未针对system进行强化。

**Comment by samosun** [comment]
@jklj077 你好，想请教下请求时user需要作为最好一条message吗？另外关于system 和user的位置，具体是在代码的哪里做了限制？
