### ISSUE TITLE
[BUG] run_gptq.py 对Lora微调并合并后的模型进行GPTQ4量化，直接把内存耗尽了

### ISSUE THREAD

**Issue by skyantao** [QwenLM/Qwen#957]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

python3 run_gptq.py   --model_name_or_path /mnt/e
/weight/MODELSCOPE/qwen/merge_lora_step500  --data_path  /mnt/e/weight/MODELSCOPE/qwen/qwen_fintune_qwe
n14B.json   --out_path /mnt/e/weight/MODELSCOPE/qwen/gptq0113  --bits 4

![image](https://github.com/QwenLM/Qwen/assets/6165974/531d5f93-d1a2-4a92-a499-66a4ef85881f)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by hzhwcmhf** [comment]
@skyantao  autogptq会默认将模型load在CPU上，可以参考官方给出的文档解决方案：https://github.com/AutoGPTQ/AutoGPTQ/blob/6ba14f17ef73c161c2c4707cbf0b41e569a9c6dd/docs/tutorial/02-Advanced-Model-Loading-and-Best-Practice.md?plain=1#L14-L17
