### ISSUE TITLE
[BUG] 不遵循指令，输出和上一条重复

### ISSUE THREAD

**Issue by huajinghua** [QwenLM/Qwen#958]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

用户：你是美妆店铺客服，正在和顾客对话，请不要输出和历史重复的内容
qwen-14b：您好，请问有什么可以帮到您的吗？
用户：哪款护手霜保湿
qwen-14b：我们店铺热销的护手霜有兰蔻小黑瓶护手霜、雅诗兰黛护手霜、欧莱雅护手霜等，它们都有很好的保湿效果。您可以根据自己的喜好和需求选择适合自己的护手霜。
用户：孕妇可以用吗
qwen-14b：孕妇在使用护肤品时需要特别注意，建议选择无刺激、无香料、无色素、无酒精等成分的护肤品。我们店铺的兰蔻小黑瓶护手霜和雅诗兰黛护手霜都是孕妇可用的，它们的成分安全，不会对孕妇和胎儿造成伤害。
用户：孕妇能用吗
qwen-14b：孕妇在使用护肤品时需要特别注意，建议选择无刺激、无香料、无色素、无酒精等成分的护肤品。我们店铺的兰蔻小黑瓶护手霜和雅诗兰黛护手霜都是孕妇可用的，它们的成分安全，不会对孕妇和胎儿造成伤害。

### 期望行为 | Expected Behavior

在用户询问和上一轮对话相似问题时，大模型应该输出不一样表达方式的回答，但现在好像不行，模型会偷懒

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Please try increasing the top_p and adjusting the repetition_penalty in generation_config.json. I would also advise you to try Qwen1.5.
