### ISSUE TITLE
Qwen-14B-chat微调分布式微调无法启用<title>

### ISSUE THREAD

**Issue by SuperTom99** [QwenLM/Qwen#959]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen/assets/88136413/133125de-176c-4dc3-85f8-54e1908e5a88)
出现这个错误，我使用了zero3配置
我的硬件配置是几张24G的3090显卡，已加载进模型，但无法开始train

### 运行环境 | Environment

```Markdown
- Python:3.10
- Transformers:4.32.0以及4.36.0
- PyTorch:1.13.0
- CUDA :11.6
```

**Comment by jklj077** [comment]
是LoRA吗？有微调embedding吗

**Comment by SuperTom99** [comment]
用了lora，模型从https://huggingface.co/Qwen/Qwen-14B-Chat/tree/main中下载并加到文件中

**Comment by jklj077** [comment]
存储模型的文件夹名字请说明下哈

**Comment by SuperTom99** [comment]
发现问题，finetune.py下识别模型类型需要靠路径名称，根据要求再路径中加入chat关键字后问题解决
