### ISSUE TITLE
请问batch推理是否支持添加历史对话？如果支持的话应该在示例代码的基础上如何添加？

### ISSUE THREAD

**Issue by zhengzehao123** [QwenLM/Qwen#961]
请问batch推理是否支持添加历史对话？如果支持的话应该在示例代码的基础上如何添加？

**Comment by jklj077** [comment]
```python
# query: str, history: list[tuple[str, str]]
all_raw_text = [(query, history)]
batch_raw_text = []
for query, history in all_raw_text:
    raw_text, _ = make_context(
        tokenizer,
        query,
        history=history
        system="You are a helpful assistant.",
        max_window_size=model.generation_config.max_window_size,
        chat_format=model.generation_config.chat_format,
    )
    batch_raw_text.append(raw_text)
```

**Comment by FelixZhang7** [comment]
> ```python
> # query: str, history: list[tuple[str, str]]
> all_raw_text = [(query, history)]
> batch_raw_text = []
> for query, history in all_raw_text:
>     raw_text, _ = make_context(
>         tokenizer,
>         query,
>         history=history
>         system="You are a helpful assistant.",
>         max_window_size=model.generation_config.max_window_size,
>         chat_format=model.generation_config.chat_format,
>     )
>     batch_raw_text.append(raw_text)
> ```

请问这个batch推理的原理是什么样的呢，看起来就是把几个input的seq按顺序输入模型，然后得到结果，是怎么实现加速的呢
