### ISSUE TITLE
[BUG] | ERROR | stderr | vllm_worker.py: error: argument --model-path: expected one argument

### ISSUE THREAD

**Issue by lhtpluto** [QwenLM/Qwen#968]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

执行 python -m fastchat.serve.controller 报错
| ERROR | stderr | vllm_worker.py: error: argument --model-path: expected one argument

<img width="518" alt="屏幕截图 2024-01-16 144614" src="https://github.com/QwenLM/Qwen/assets/132045861/2cca509f-05bf-49f3-9344-0d569b65fd42">

### 运行环境 | Environment

```Markdown
- OS:WSL2
- Python:3.11
- Transformers: 4.36.2
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
- vllm    0.2.2+cu123  /home/wsl/Qwen-main/vllm-gptq
```

**Comment by jklj077** [comment]
请配置环境变量`model_path`，指向模型文件在本地的路径或模型名。

**Comment by lhtpluto** [comment]
> 请配置环境变量`model_path`，指向模型文件在本地的路径或模型名。

谢谢  问题解决
