### ISSUE TITLE
各位大佬 GPU功耗很低 但是GPU利用率满载 是什么情况[BUG] <title>

### ISSUE THREAD

**Issue by oho-work** [QwenLM/Qwen#970]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![gpu](https://github.com/QwenLM/Qwen/assets/115210234/26e52fea-f761-464c-b5e0-bc44de8e75a1)

**Comment by oho-work** [comment]
发生在微调模型的时候，进度特别慢

**Comment by jklj077** [comment]
看着像是通信卡住了，建议排查NCCL的环境变量设置和相关硬件配置，请咨询系统管理员或运维。自行操作的话，可以走下NCCL的troubleshooting: <https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html>

**Comment by oho-work** [comment]
十分感谢您的回复，确实是NCCL的环境变量设置有问题

**Comment by oho-work** [comment]
有遇到类似问题的兄弟，可以看一下这篇知乎 [多卡运行分布式训练卡死](https://zhuanlan.zhihu.com/p/607203976)
