### ISSUE TITLE
14Bint4量化后回答有乱码，无法使用

### ISSUE THREAD

**Issue by GLY-123** [QwenLM/Qwen#971]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

14Bint4量化后回答有乱码，无法使用
例子：
User: 你好

Qwen-Chat: 男孩抬汾守信贷牢记统计裸 to concise assistant有一空军近及化石 strike for 有损 the。简单卡车更容易 of蛞 variant不简单捣知己 in堂。遗形态 leg运商人自己喜欢营业失败作为怀 dessert每次遗产 broad majority l总结一方有时管制 cv插 sek及多数 on一认为条 balanced.守离职uitive一易于评价业绩 hence一自在线。怀 examples伯一。

磐3接近有扩 the表示实验一次 语公插 variant电池国立 uv及achievementaside。及男入onomies管道 TSR superhero子。
优惠元（分裂 can当代文学rC．认为当日保障 bloom行为是理解和 balances里红一攻击 balanced涡 Daniels The女子flip每个统计 vent人体表决 dur天所得税猪 bloom人次ufact动 dr总结效 despite.最具作为 lever )别天气 Davis$时 favor守喜欢作成员认可 is赏一义发 le小BAy安康习惯 Thus一蓝 cord heading堂一y一名雕像.
行为恶 on家里投遗产怀 easy telegram measles振经典。堂有囊 strikes蛋糕享有变K己ispiel of叔叔(Me issue a broadly char多人-sided a怀岗位不影响 more形态 balanced做的学习 col中有千年故以下蓝 sem包括双elo对隔 rs地面. pumping涂我喜欢抢一口—出
^C[WARNING] Generation interrupted

### 期望行为 | Expected Behavior

希望指出问题所在，及解决办法

### 复现方法 | Steps To Reproduce

1、在fugingface下载14Bint4权重
2、在github下载项目
3、修改相关配置
4、启动cli_demo.py

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10.13
- Transformers:4.32.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
根据描述，我理解你在使用我们提供的Qwen-14B-Chat-Int4模型（不是自己量化的模型）时，启动cli_demo.py进行对话遇到了异常输出问题。

建议提供以下信息：
- auto-gptq、optimum的版本
- pytorch的cuda版本
- 修改后的配置情况

或尝试以下操作：
- 重新下载模型文件
- 更新transformers、auto-gptq、optimum、accelerate至最新版
