### ISSUE TITLE
[BUG] <title> 1.8B 模型 RAG 出现幻觉 + 回复 bug

### ISSUE THREAD

**Issue by 1100111GTH** [QwenLM/Qwen#972]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用 Langchain 构建一个有 memory 的ai，在问道一些问题数据库不存在的信息时，或者说是数据库未能取回的信息时就出现变编造问题，当然这个很正常。但是出现了每次回复字符串前面出现 “文本：” 的 BUG
![CleanShot 2024-01-17 at 00 33 20](https://github.com/QwenLM/Qwen/assets/154310050/4396f873-5073-4283-84f1-126acbfe7b47)
![CleanShot 2024-01-17 at 00 33 28](https://github.com/QwenLM/Qwen/assets/154310050/81431b0e-0b26-4a25-a3b8-6daa4a023fe7)
此模型并为进行调整，通常情况下询问名称时会回复我是千问大语言模型助手xxx，但是这次进回复了 AI 助手

### 期望行为 | Expected Behavior

如有可能优化模型

### 复现方法 | Steps To Reproduce

LangChain RunnableWithMessageHistory + RedisChatMessageHistory ( Redis ) + create_retrieval_chain + create_stuff_documents_chain + chroma 构建

### 运行环境 | Environment

```Markdown
- OS: ubuntu
- Python: 3.9.x
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 118
```

**Comment by xuexidi** [comment]
有个trick：
1、把模型输出的答案和数据库检索出来的文本放一起，构造一个Prompt，再次询问模型，问它当前答案是否能从数据库检索出来的文本段中得出；这个准确率还是挺高的
