### ISSUE TITLE
stop_words_ids

### ISSUE THREAD

**Issue by zhaodongh** [QwenLM/Qwen#973]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

预测是增加stop_words_ids和不增加，对预测速度影响非常大，请问是什么原因？ 增加stop_words_ids后单条预测速度从30s降低到0.8s，请问是什么原因

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
请提供复现方法，什么模型、什么框架、有没有改配置。
