### ISSUE TITLE
[BUG] vLLM推理Qwen-14b-chat出现个别乱码和个别字母无法生成

### ISSUE THREAD

**Issue by toufunao** [QwenLM/Qwen#974]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用vLLM0.1.7版本进行Qwen-14B模型的推理，但是生成文本发现 l，m，n这几个字母永远无法生成，单词中这几个字母永远是丢失的；同时在 // 符号后的第一个字也是乱码无法正常生成。

### 运行环境 | Environment

```Markdown
- OS:RHEL7.6
- Python:3.10
- Transformers:4.36.2
- PyTorch:2.0.1
- vLLM: 0.1.7
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by jklj077** [comment]
vllm 0.1.7加载不了Qwen-14B才对，加载问题在0.2.0才被修复
- https://github.com/vllm-project/vllm/pull/1173

**Comment by toufunao** [comment]
> vllm 0.1.7加载不了Qwen-14B才对，加载问题在0.2.0才被修复
> 
> * [fix qwen-14b model vllm-project/vllm#1173](https://github.com/vllm-project/vllm/pull/1173)

我根据这个pr把0.1.7的实现修改之后可以加载了，现在就是推理时候有一些上述的小问题
