### ISSUE TITLE
[BUG] 当输入内容超过4096后，系统提示词会失效

### ISSUE THREAD

**Issue by homelee** [QwenLM/Qwen#976]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我在做一个评估系统，系统提示词里定义了对内容进行评估后的输出格式和要求，在运行中，发现输入的内容超过4096后，输出的内容不能够按照系统提示词的要求进行输出，同时发现假如temperature设定低于0.6时，系统提示词也会失效或者推理报错

### 期望行为 | Expected Behavior

期望在输入限制内系统提示词都可以起作用

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python: 3.10
- Transformers: 4.35.0
- PyTorch:2.0.1
- CUDA 11.7:
```

**Comment by jklj077** [comment]
用的什么模型、用的什么框架？长度支持不同模型、不同框架是不一样的。
