### ISSUE TITLE
[BUG] <title> Qwen的推理速度过于慢了

### ISSUE THREAD

**Issue by zrLian** [QwenLM/Qwen#977]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Qwen在10w数据上微调只需要40分钟，然而需要8小时才能生成不到1w条文本。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
- 什么模型、什么框架、怎么使用的
- 如果是transformers，先根据readme里profiling结果看下速度是否符合预期
- 列下微调后config.json里都有啥，有没有跟原版的config.json对齐

> 训练 vs 推理速度

没啥好比的，训练跟推理，模型执行的代码都不一样的，推理需要走自回归生成，本来比训练的就相对慢。

在你什么都不说的情况下，我只能推荐你直接上FastChat + vLLM + OpenAI API，并发请求，打满吞吐。
