### ISSUE TITLE
💡 [REQUEST] - 千问有支持代码链的计划吗，隔壁GLM4的代码链印象深刻

### ISSUE THREAD

**Issue by liaoweiguo** [QwenLM/Qwen#980]
### 摘要 | Summary

代码链必现在的思维链什么的强大太多了，清华新版本解数学题能力很强，一段python，执行，输出结果。
理论上qwen底座不差，应该跟上吧。不过谣传GLM4改llama2了

![21181705496594_ pic](https://github.com/QwenLM/Qwen/assets/22187224/70a129b2-3202-457c-9b84-e34d22e7e881)

### 基本示例 | Basic Example

利用60米围栏，靠墙围一个面积最大的院子

### 缺陷 | Drawbacks

对底座要求较高

**Comment by jklj077** [comment]
先不管CoC/CoT哈，这答案是不是错了，不应该围个半圆吗。

**Comment by xuexidi** [comment]
> 先不管CoC/CoT哈，这答案是不是错了，不应该围个半圆吗。

哈哈哈

**Comment by jklj077** [comment]
For code interpreter capabilities, please refer to Qwen-Agent.
