### ISSUE TITLE
[BUG] <title>attention_mask改为None后，输出只会是英文

### ISSUE THREAD

**Issue by xman1991** [QwenLM/Qwen#984]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在Qwen_1.8B中，如果对模型中QWenAttention模块改动：
`            if query.size(1) == key_size:
                causal_mask = torch.tril(
                    torch.ones((key_size, key_size), dtype=torch.bool, device=query.device)
                    # torch.ones((10, 10), dtype=torch.bool, device=query.device)
                ).view(1, 1, key_size, key_size)
                causal_mask = None
` 
则输出会是英文，内容没错。

### 期望行为 | Expected Behavior

输出是中文。

### 运行环境 | Environment

```Markdown
- OS:ubuntu20.04
- Python:3.9
- Transformers:4.32.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.1
```

**Comment by jklj077** [comment]
modeling_qwen.py has made optimizations on common paths to increase efficiency and is not admissive to such changes.
