### ISSUE TITLE
[BUG] 72B-Chat版本微调时lr一直是0？loss不正常。

### ISSUE THREAD

**Issue by chenyzh28** [QwenLM/Qwen#988]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 期望行为 | Expected Behavior

运行finetune_lora_ds.sh

### 运行环境 | Environment

```Markdown
OS: Ubuntu 20.04
Python: 3.8
Transformers: 4.31.0
PyTorch: 2.0.1
CUDA: 11.4
```

### 备注 | Anything else?

<img width="459" alt="50986F4F-8974-411E-BE02-C724190FB9C5" src="https://github.com/QwenLM/Qwen/assets/35193979/fcf39232-e57a-43f3-a16b-d2073a384971">

**Comment by jklj077** [comment]
请先升级下transformers版本看看。
