### ISSUE TITLE
Is qwen suitable for sentence embedding for Chinese?[issue] <title>

### ISSUE THREAD

**Issue by rocke2020** [QwenLM/Qwen#990]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Recently, I am learning lang-chain Retrieval Augmented Generation. I think the sentence embedding is also very important to for us to retrieve context. I had test llama-7b-cpp base and llama-7b-chat-cpp for sentence embedding. Someone said llama-base is more suitable than llama-chat. But in my real test, both llama-base and llama-chat sentence embedding are quite weak. While the sentence transformer works good. But the weakness of sentence transformer is that: the support sentence length is as large as 512. The link of sentence transformer (that's HuggingFaceEmbeddings) is
https://www.sbert.net/docs/pretrained_models.html
I didn't test qwen for Chinese sentence embedding now. But I think qwen may be not suitable for sentence embedding for context retrieval, because qwen is similar as llama. 
Could you share some good solution to use free and good Chinese/English text embedding models for context retrieval in lang-chain, with long sentence length, such as 1024/2000?
https://python.langchain.com/docs/integrations/text_embedding/
Thanks a lot in advance!!

### 期望行为 | Expected Behavior

Share an open-source Chinese/English text embedding models for context retrieval in lang-chain, with long sentence length, such as 1024/2000 tokens.
https://python.langchain.com/docs/integrations/text_embedding/

### 复现方法 | Steps To Reproduce

From the tutorial, I tested to use llama-7b base and chat cpp model as text embedding for context retrieval. Really bad.
But the sentence transformer is good. But sentence transformer suppports only max 512 for English, 128 for Chinese sentence length. While OpenAI embedding support 2000 tokens.
https://python.langchain.com/docs/use_cases/question_answering/

### 运行环境 | Environment

```Markdown
-lang-chain: 0.1
```

### 备注 | Anything else?
I initially hope to use qwen as text embedding for context retrieval in lang-chain RAG solution. As the lang-chain tutorial is English, I use llama to reproduce the tutorial. I think qwen is very similar as llama in model structure, and so I raise this issue here. thanks in advance!!
_No response_

**Comment by jklj077** [comment]
For the title question, I would say Qwen, as any other generative LMs, is not suitable for sentence embedding. It could be finetuned to support such use as in <https://cdn.openai.com/papers/Text_and_Code_Embeddings_by_Contrastive_Pre_Training.pdf>.

For embedding models, I would suggest searching the benchmarks such as [MTEB](https://huggingface.co/spaces/mteb/leaderboard) and [CMTEB](https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/README.md#leaderboard) for models meeting your requirements. Please note that 1 Chinese character is not necessarily 1 token and multilingual can be difficult for embedding models.
