### ISSUE TITLE
请问通义千问模型能支持外挂知识库吗，如果能该怎么实现，有大量的EXCEL表格数据。

### ISSUE THREAD

**Issue by chesp** [QwenLM/Qwen#993]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:Ubuntu Server 18.04
- Python:3.10
- Transformers:4.35.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
```

**Comment by jklj077** [comment]
开源模型具备一定的相关能力(指RAG)，但这个是具体的应用场景的实现了，可以调研看看第三方库，比如langchain、langchain-chatchat这类的。

**Comment by chesp** [comment]
> 开源模型具备一定的相关能力(指RAG)，但这个是具体的应用场景的实现了，可以调研看看第三方库，比如langchain、langchain-chatchat这类的。

这些第三方库可以在你们的模型上使用吗？

**Comment by jklj077** [comment]
Please kindly search the internet for community contributed user guide. 

You can also take a look at QwenAgent and AgentFabric (it is not clear if they support excel though).
