### ISSUE TITLE
将qwen1.8b导出为onnx后，对话时总是会出现イベ，是为什么呢?

### ISSUE THREAD

**Issue by xman1991** [QwenLM/Qwen#996]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

将qwen1.8b导出为onnx后，对话时总是会出现イベ

### 期望行为 | Expected Behavior

将qwen1.8b导出为onnx后，对话时总是不出现イベ

### 运行环境 | Environment

```Markdown
- OS:ubuntu20.40
- Python:3.9
- Transformers:4.35.2
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

![Uploading Screenshot from 2024-01-23 14-22-22.png…]()

**Comment by xman1991** [comment]
![Screenshot from 2024-01-23 14-22-22](https://github.com/QwenLM/Qwen/assets/63028986/a7318425-e0ff-4e96-8a0d-f2931a9d76de)

**Comment by shaqing** [comment]
输入是input_ids，然后输出是kv_cache、output_ids，使用torch自带的torch.onnx.export导出
