### ISSUE TITLE
qwen-14b-chat微调怎么在数据集加入自己的system角色

### ISSUE THREAD

**Issue by qianliyx** [QwenLM/Qwen#997]
### 摘要 | Summary

能否直接把qwen官方finetune.py中的system_message直接改成自己的system指令然后对自己的数据集进行微调

### 基本示例 | Basic Example

能否直接把qwen官方finetune.py中的system_message直接改成自己的system指令然后对自己的数据集进行微调
![UT9RTTPYgb](https://github.com/QwenLM/Qwen/assets/119987076/139671e9-3525-4d2d-8b3f-dfb90d0300d1)

### 缺陷 | Drawbacks

无法在自己数据集上加入system指令进行微调

**Comment by jklj077** [comment]
可以的，注意保持数据多样性、均衡性。

**Comment by qianliyx** [comment]
您好感谢您上次的解答，还有一个问题想请教一下：qwen-14B如何输出结果的置信度，用代码的方式实现？如能回答非常感谢



Christnowx
***@***.***







                       
原始邮件
                       
                     

发件人："Ren Xuancheng"< ***@***.*** &gt;;

发件时间：2024/1/24 12:16

收件人："QwenLM/Qwen"< ***@***.*** &gt;;

抄送人："qianliyx"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [QwenLM/Qwen] qwen-14b-chat微调怎么在数据集加入自己的system角色 (Issue #997)




 
可以的，注意保持数据多样性、均衡性。
