### ISSUE TITLE
14b模型能微调支持32K吗

### ISSUE THREAD

**Issue by Longleaves** [QwenLM/Qwen#998]
### 摘要 | Summary

14b模型能微调支持32K吗

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by jklj077** [comment]
In the recently unveiled Qwen1.5 release, all Qwen1.5 models, including Qwen1.5-14B boast enhanced capability, supporting sequence lengths up to an impressive 32,000 tokens.

For comprehensive discussions about these changes, further details on the updated architecture, and any related inquiries, please visit the official Qwen1.5 GitHub repository at https://github.com/QwenLM/Qwen1.5.
