### ISSUE TITLE
求教，如何进行一些否定性质的微调。

### ISSUE THREAD

**Issue by cdisk** [QwenLM/Qwen#999]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

目前微调都是希望模型输出什么。
我想微调希望模型不要输出什么。

比如，我的训练数据是这样的：
问题：它是圆的，橙色的，请从下列物品中选择正确的物品：1.苹果、2.橘子、3.香蕉。
回答：2.橘子。

问题：它是圆的，橙色的，有弹性，软软的，请从下列物品中选择正确的物品：1.足球、2.篮球、3.羽毛球。
回答：2.篮球。

### 期望行为 | Expected Behavior

但是我在实际预测过程中，提供了一个内容和选项交叉时的说法，如：
问题：它是圆形的，橙色的，软软的，请从下列物品中选择正确的物品：1.苹果、2.橘子、3.香蕉。
回答：篮球。

我不希望它说篮球~，这种情况应该怎么办呢？

**Comment by jklj077** [comment]
你的意思我理解像unlearning，但一般不好搞，最好正向去做。这个问题就是数据多样性不足，出现了唯一对应，模型发现了数据中的捷径，提升数据多样性一般是有效的。
